### ISSUE TITLE
Type Error: x and y in RectProps are defined to be undefined or NumberProp, but the implementation also accepts null. 

### ISSUE THREAD

**Issue by Shagamii** [react-native-community/react-native-svg#1000]
Rect props is declared as this
https://github.com/react-native-community/react-native-svg/blob/0835b500568c542dc815066c0b012be00ddb9bfd/index.d.ts#L295-L303

but, looking at this implementation, it seems that null is also accepted.
https://github.com/react-native-community/react-native-svg/blob/0835b500568c542dc815066c0b012be00ddb9bfd/elements/Rect.js#L22-L39

Type definition may be wrong.
which one is correct?

**Comment by msand** [comment]
The nulls in this case comes from how the handling of the non-standard shorthand transform properties (x, y, translate, translateX, translateY, scale, scaleX, scaleY, origin, originX, originY, rotation, skew, skewX, skewY) is implemented: https://github.com/react-native-community/react-native-svg/blob/0835b500568c542dc815066c0b012be00ddb9bfd/lib/extract/extractTransform.js#L20-L76

They're needed when the element (Rect in this case) has existing properties / presentation attributes defined by the svg spec, such as x and y in this case. The call to extractProps gets a newly constructed object, with the result of propsAndStyles spread, and the x and y properties overridden with null, to avoid adding them to the transform matrix. 

Instead, we give the x and y values directly to the native RNSVGRect as direct properties without any processing. And the native side can handle both strings and numbers. This way, the rest of shorthand props can be supported by reusing the props2transform logic in extractProps:
https://github.com/react-native-community/react-native-svg/blob/0835b500568c542dc815066c0b012be00ddb9bfd/lib/extract/extractProps.js#L17-L31

The allowed values are still defined by the standard. In this case, x and y of Rect are defined as SVGLength, and in javascript, you can give either a Number or a String with an optional unit (px, em etc). Giving null / undefined / no value, should make it use the default value instead.

**Comment by Shagamii** [comment]
Thank you for the detailed commentary!
I understand this source code!
