### ISSUE TITLE
How to integrate with react-native-gesture-handler

### ISSUE THREAD

**Issue by sJJdGG** [react-native-community/react-native-svg#1011]
Right now when you wrap a SVG component e.g. Line in a gesture handler imported from [react-native-gesture-handler](http://github.com/kmagiera/react-native-gesture-handler) it will activate on touching any part of the whole rectangle view created by line component to render itself not just the line which makes it unusable in practice.

Currently PanResponder works perfectly with RNSVG but due to performance reasons which was the main reason RNGH has been created in the first place, it makes it hard to have smooth animations and UX in svg based UIs.

react-native-reanimated works with RNSVG. Considering  RNR and RNGH usaully gets used together (e.g. react-navigation). I think it's worth the consideration.

**Comment by alamothe** [comment]
Wondering if this should be filed against `react-native-gesture-handler` instead?

**Comment by msand** [comment]
I haven't looked at the code of react-native-gesture-handler yet. I would suspect that if you want it to react only on part of the canvas where there is stroke or fill color painted, then you would have to change their implementation significantly, and probably make the performance of it significantly worse. But, it might be possible to implement efficiently enough, with some changes to this library as well. Or just optimizing the current gesture handling logic might bring big wins as well. It would certainly deserve more profiling with real world data, if you have some time you're able to dedicate to this.

**Comment by msand** [comment]
Check out redash and e.g. this video: https://www.youtube.com/watch?v=uSucm5jjkRI
