### ISSUE TITLE
Expose a LazySvgPackage version for lazy instantiation on Android

### ISSUE THREAD

**Issue by jacobdfriedmann** [react-native-community/react-native-svg#1012]
This [article on Parashuram's blog](http://blog.nparashuram.com/2019/04/lazy-native-modules-react-native-android.html?m=1) outlines several optimizations that can be made to native modules to help improve the initialization time of React Native, which can particularly be important in large or hybrid applications.

It might be nice to expose a `com.horcrux.svg.LazySvgPackage` that was based on the `LazyReactPackage` class outlined in that blog post.

**Comment by msand** [comment]
Would you be willing to make a pr?
