### ISSUE TITLE
How is this problem solved?

### ISSUE THREAD

**Issue by vtn-dev2016** [react-native-community/react-native-svg#1015]
i'm use "react-native-svg": "^9.4.0", and "react-native": "0.59.8",

<img width="323" alt="Screen Shot 2562-05-26 at 21 21 24" src="https://user-images.githubusercontent.com/30209508/58383078-638a3980-7ffc-11e9-8186-7e9869d1a3c7.png">
<img width="507" alt="Screen Shot 2562-05-26 at 21 21 56" src="https://user-images.githubusercontent.com/30209508/58383081-6c7b0b00-7ffc-11e9-8768-b3bf383c2d83.png">

**Comment by msand** [comment]
Do you have react-native-svg-uri installed?

**Comment by vtn-dev2016** [comment]
@msand Thank you very much.
