### ISSUE TITLE
Can't use svg file from sketch

### ISSUE THREAD

**Issue by vtn-dev2016** [react-native-community/react-native-svg#1016]
i try svg file from http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg it work but i use svg that is exported from the sketch will be found error according in this picture.

<img width="347" alt="Screen Shot 2562-05-27 at 13 14 50" src="https://user-images.githubusercontent.com/30209508/58399538-b575a280-8082-11e9-8a66-59859798dd53.png">

**Comment by gregory-light-it** [comment]
Same for me. Example of svg files:
1. `<svg width="193px" height="195px" viewBox="0 0 193 195" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">    <defs>        <rect id="path-1" x="0" y="0" width="230" height="230"></rect>        <rect id="path-3" x="0" y="0" width="230" height="230"></rect>        <path d="M50,-286 C46.4101491,-286 43.5,-288.910149 43.5,-292.5 C43.5,-296.089851 46.4101491,-299 50,-299 C53.5898509,-299 56.5,-296.089851 56.5,-292.5 C56.5,-288.910149 53.5898509,-286 50,-286 Z M50,-289 C51.9329966,-289 53.5,-290.567003 53.5,-292.5 C53.5,-294.432997 51.9329966,-296 50,-296 C48.0670034,-296 46.5,-294.432997 46.5,-292.5 C46.5,-290.567003 48.0670034,-289 50,-289 Z M79.5,-163.5 C79.5,-164.328427 80.1715729,-165 81,-165 C81.8284271,-165 82.5,-164.328427 82.5,-163.5 C82.5,-161.567003 84.0670034,-160 86,-160 C86.8284271,-160 87.5,-159.328427 87.5,-158.5 C87.5,-157.671573 86.8284271,-157 86,-157 C82.4101491,-157 79.5,-159.910149 79.5,-163.5 Z M148.120462,-282.489249 C147.320262,-282.274836 146.497757,-282.74971 146.283344,-283.549909 C146.068932,-284.350108 146.543805,-285.172614 147.344004,-285.387027 C149.211136,-285.887323 150.319175,-287.806502 149.818878,-289.673634 C149.604465,-290.473833 150.079339,-291.296338 150.879538,-291.510751 C151.679738,-291.725164 152.502243,-291.25029 152.716656,-290.450091 C153.645777,-286.982561 151.587991,-283.418371 148.120462,-282.489249 Z M202.120462,-125.489249 C201.320262,-125.274836 200.497757,-125.74971 200.283344,-126.549909 C200.068932,-127.350108 200.543805,-128.172614 201.344004,-128.387027 C203.211136,-128.887323 204.319175,-130.806502 203.818878,-132.673634 C203.604465,-133.473833 204.079339,-134.296338 204.879538,-134.510751 C205.679738,-134.725164 206.502243,-134.25029 206.716656,-133.450091 C207.645777,-129.982561 205.587991,-126.418371 202.120462,-125.489249 Z M203,-206 C199.410149,-206 196.5,-208.910149 196.5,-212.5 C196.5,-216.089851 199.410149,-219 203,-219 C206.589851,-219 209.5,-216.089851 209.5,-212.5 C209.5,-208.910149 206.589851,-206 203,-206 Z M203,-209 C204.932997,-209 206.5,-210.567003 206.5,-212.5 C206.5,-214.432997 204.932997,-216 203,-216 C201.067003,-216 199.5,-214.432997 199.5,-212.5 C199.5,-210.567003 201.067003,-209 203,-209 Z M33,-116 C29.4101491,-116 26.5,-118.910149 26.5,-122.5 C26.5,-126.089851 29.4101491,-129 33,-129 C36.5898509,-129 39.5,-126.089851 39.5,-122.5 C39.5,-118.910149 36.5898509,-116 33,-116 Z M33,-119 C34.9329966,-119 36.5,-120.567003 36.5,-122.5 C36.5,-124.432997 34.9329966,-126 33,-126 C31.0670034,-126 29.5,-124.432997 29.5,-122.5 C29.5,-120.567003 31.0670034,-119 33,-119 Z M153,-155 C153,-155.828427 153.671573,-156.5 154.5,-156.5 C155.328427,-156.5 156,-155.828427 156,-155 L156,-154 C156,-153.171573 155.328427,-152.5 154.5,-152.5 C153.671573,-152.5 153,-153.171573 153,-154 L153,-155 Z M153,-144 C153,-144.828427 153.671573,-145.5 154.5,-145.5 C155.328427,-145.5 156,-144.828427 156,-144 L156,-143 C156,-142.171573 155.328427,-141.5 154.5,-141.5 C153.671573,-141.5 153,-142.171573 153,-143 L153,-144 Z M159.5,-147.5 C158.671573,-147.5 158,-148.171573 158,-149 C158,-149.828427 158.671573,-150.5 159.5,-150.5 L161,-150.5 C161.828427,-150.5 162.5,-149.828427 162.5,-149 C162.5,-148.171573 161.828427,-147.5 161,-147.5 L159.5,-147.5 Z M148.5,-147.5 C147.671573,-147.5 147,-148.171573 147,-149 C147,-149.828427 147.671573,-150.5 148.5,-150.5 L150,-150.5 C150.828427,-150.5 151.5,-149.828427 151.5,-149 C151.5,-148.171573 150.828427,-147.5 150,-147.5 L148.5,-147.5 Z M26,-221 C26,-221.828427 26.6715729,-222.5 27.5,-222.5 C28.3284271,-222.5 29,-221.828427 29,-221 L29,-220 C29,-219.171573 28.3284271,-218.5 27.5,-218.5 C26.6715729,-218.5 26,-219.171573 26,-220 L26,-221 Z M26,-210 C26,-210.828427 26.6715729,-211.5 27.5,-211.5 C28.3284271,-211.5 29,-210.828427 29,-210 L29,-209 C29,-208.171573 28.3284271,-207.5 27.5,-207.5 C26.6715729,-207.5 26,-208.171573 26,-209 L26,-210 Z M32.5,-213.5 C31.6715729,-213.5 31,-214.171573 31,-215 C31,-215.828427 31.6715729,-216.5 32.5,-216.5 L34,-216.5 C34.8284271,-216.5 35.5,-215.828427 35.5,-215 C35.5,-214.171573 34.8284271,-213.5 34,-213.5 L32.5,-213.5 Z M21.5,-213.5 C20.6715729,-213.5 20,-214.171573 20,-215 C20,-215.828427 20.6715729,-216.5 21.5,-216.5 L23,-216.5 C23.8284271,-216.5 24.5,-215.828427 24.5,-215 C24.5,-214.171573 23.8284271,-213.5 23,-213.5 L21.5,-213.5 Z M203,-309 C203,-309.828427 203.671573,-310.5 204.5,-310.5 C205.328427,-310.5 206,-309.828427 206,-309 L206,-308 C206,-307.171573 205.328427,-306.5 204.5,-306.5 C203.671573,-306.5 203,-307.171573 203,-308 L203,-309 Z M203,-298 C203,-298.828427 203.671573,-299.5 204.5,-299.5 C205.328427,-299.5 206,-298.828427 206,-298 L206,-297 C206,-296.171573 205.328427,-295.5 204.5,-295.5 C203.671573,-295.5 203,-296.171573 203,-297 L203,-298 Z M209.5,-301.5 C208.671573,-301.5 208,-302.171573 208,-303 C208,-303.828427 208.671573,-304.5 209.5,-304.5 L211,-304.5 C211.828427,-304.5 212.5,-303.828427 212.5,-303 C212.5,-302.171573 211.828427,-301.5 211,-301.5 L209.5,-301.5 Z M198.5,-301.5 C197.671573,-301.5 197,-302.171573 197,-303 C197,-303.828427 197.671573,-304.5 198.5,-304.5 L200,-304.5 C200.828427,-304.5 201.5,-303.828427 201.5,-303 C201.5,-302.171573 200.828427,-301.5 200,-301.5 L198.5,-301.5 Z" id="path-5"></path>    </defs>    <g id="Illustrations-✔︎-✔︎-[comments]" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">        <g id="illustrations" transform="translate(-80.000000, -1484.000000)">            <rect fill="#F9FBFC" x="0" y="0" width="1500" height="2500"></rect>            <g id="Group-5" transform="translate(60.000000, 1370.000000)">                <g id="illustrations/illustrations/combo" transform="translate(0.000000, 95.000000)">                    <g id="illustrations/illustrations/">                        <mask id="mask-2" fill="white">                            <use xlink:href="#path-1"></use>                        </mask>                        <g id="container"></g>                        <g id="illustrations/illustrations/assets/backgound/sparks" mask="url(#mask-2)">                            <g id="bg-sparks" transform="translate(0.000000, 330.000000)">                                <mask id="mask-4" fill="white">                                    <use xlink:href="#path-3"></use>                                </mask>                                <g id="container"></g>                                <mask id="mask-6" fill="white">                                    <use xlink:href="#path-5"></use>                                </mask>                                <use id="Shape" fill="#FFFFFF" fill-rule="nonzero" xlink:href="#path-5"></use>                                <g id="colors/primary-color" opacity="0.4" mask="url(#mask-6)" fill="#52BEF9">                                    <g transform="translate(0.000000, -330.000000)" id="Rectangle-Copy-2">                                        <rect x="0" y="0" width="230" height="230"></rect>                                    </g>                                </g>                            </g>                        </g>                        <g id="illustrations/illustrations/assets/illustrations/security" mask="url(#mask-2)">                            <g transform="translate(50.000000, 50.000000)">                                <g>                                    <rect id="container" x="0" y="0" width="130" height="130"></rect>                                    <g id="illustration-security" transform="translate(23.000000, 10.000000)">                                        <path d="M0,13.1724138 C12.461095,13.1724138 22.7477215,10.4166961 31.0072033,5.83708475 C33.8770788,4.24583311 36.28598,2.54664047 38.248289,0.855627963 C38.9263385,0.271321418 39.4980547,-0.267273339 39.9651358,-0.745501062 C40.2332251,-1.0199881 40.4001992,-1.20485867 40.4677491,-1.28538215 L42,-3.11191501 L43.5322509,-1.28538215 C43.5998008,-1.20485867 43.7667749,-1.0199881 44.0348642,-0.745501062 C44.5019453,-0.267273339 45.0736615,0.271321418 45.751711,0.855627963 C47.71402,2.54664047 50.1229212,4.24583311 52.9927967,5.83708475 C61.2522785,10.4166961 71.538905,13.1724138 84,13.1724138 L86,13.1724138 L86,51.3681034 C86,71.1922205 77.2269082,89.871396 62.0088504,101.752111 C56.0841333,106.379247 49.6056958,109.84344 42.5654113,111.918413 L42,112.085056 L41.4345887,111.918413 C34.3958466,109.843895 27.9200687,106.38086 21.9914337,101.752333 C6.77309181,89.871396 -2,71.1922205 -2,51.3681034 L-2,13.1724138 L0,13.1724138 Z" id="Stroke-46" stroke="#52BEF9" stroke-width="4" fill="#FFFFFF" stroke-linejoin="round"></path>                                        <path d="M29.9765734,89.855675 C18.3993,80.9229713 11.5,66.5001586 11.5,51.2644764 L11.5,25.992368 L12.8137441,25.8279673 C24.2544005,24.3962946 33.66107,20.7585139 41.1677192,15.7520783 L42,15.1970023 L42.8322808,15.7520783 C50.33893,20.7585139 59.7455995,24.3962946 71.1862559,25.8279673 L72.5,25.992368 L72.5,51.2644764 C72.5,66.4996594 65.6010767,80.9226961 54.025063,89.8558109 C50.3794376,92.6683725 46.528634,94.8628164 42.5392396,96.3997216 L42,96.6074625 L41.4607604,96.3997216 C37.4706281,94.8625321 33.6198176,92.6678241 29.9765734,89.855675 Z" id="Stroke-48" stroke="#52BEF9" stroke-width="3" fill="#C6E2F7" stroke-linejoin="round"></path>                                        <path d="M29.4142136,53.5857864 C28.633165,52.8047379 27.366835,52.8047379 26.5857864,53.5857864 C25.8047379,54.366835 25.8047379,55.633165 26.5857864,56.4142136 L36.5857864,66.4142136 C37.366835,67.1952621 38.633165,67.1952621 39.4142136,66.4142136 L57.4142136,48.4142136 C58.1952621,47.633165 58.1952621,46.366835 57.4142136,45.5857864 C56.633165,44.8047379 55.366835,44.8047379 54.5857864,45.5857864 L38,62.1715729 L29.4142136,53.5857864 Z" id="Path" fill="#52BEF9" fill-rule="nonzero"></path>                                    </g>                                </g>                            </g>                        </g>                    </g>                </g>            </g>        </g>    </g></svg>`

2. ```<?xml version="1.0" encoding="UTF-8"?><svg width="92px" height="118px" viewBox="0 0 92 118" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">    <!-- Generator: Sketch 55 (78076) - https://sketchapp.com -->    <title>illustration-security@1x</title>    <desc>Created with Sketch.</desc>    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">        <g id="illustrations/illustrations/assets/illustrations/security" transform="translate(-19.000000, -6.000000)">            <g id="illustration-security">                <g transform="translate(23.000000, 10.000000)">                    <path d="M0,13.1724138 C12.461095,13.1724138 22.7477215,10.4166961 31.0072033,5.83708475 C33.8770788,4.24583311 36.28598,2.54664047 38.248289,0.855627963 C38.9263385,0.271321418 39.4980547,-0.267273339 39.9651358,-0.745501062 C40.2332251,-1.0199881 40.4001992,-1.20485867 40.4677491,-1.28538215 L42,-3.11191501 L43.5322509,-1.28538215 C43.5998008,-1.20485867 43.7667749,-1.0199881 44.0348642,-0.745501062 C44.5019453,-0.267273339 45.0736615,0.271321418 45.751711,0.855627963 C47.71402,2.54664047 50.1229212,4.24583311 52.9927967,5.83708475 C61.2522785,10.4166961 71.538905,13.1724138 84,13.1724138 L86,13.1724138 L86,51.3681034 C86,71.1922205 77.2269082,89.871396 62.0088504,101.752111 C56.0841333,106.379247 49.6056958,109.84344 42.5654113,111.918413 L42,112.085056 L41.4345887,111.918413 C34.3958466,109.843895 27.9200687,106.38086 21.9914337,101.752333 C6.77309181,89.871396 -2,71.1922205 -2,51.3681034 L-2,13.1724138 L0,13.1724138 Z" id="Stroke-46" stroke="#52BEF9" stroke-width="4" fill="#FFFFFF" stroke-linejoin="round"></path>                    <path d="M29.9765734,89.855675 C18.3993,80.9229713 11.5,66.5001586 11.5,51.2644764 L11.5,25.992368 L12.8137441,25.8279673 C24.2544005,24.3962946 33.66107,20.7585139 41.1677192,15.7520783 L42,15.1970023 L42.8322808,15.7520783 C50.33893,20.7585139 59.7455995,24.3962946 71.1862559,25.8279673 L72.5,25.992368 L72.5,51.2644764 C72.5,66.4996594 65.6010767,80.9226961 54.025063,89.8558109 C50.3794376,92.6683725 46.528634,94.8628164 42.5392396,96.3997216 L42,96.6074625 L41.4607604,96.3997216 C37.4706281,94.8625321 33.6198176,92.6678241 29.9765734,89.855675 Z" id="Stroke-48" stroke="#52BEF9" stroke-width="3" fill="#C6E2F7" stroke-linejoin="round"></path>                    <path d="M29.4142136,53.5857864 C28.633165,52.8047379 27.366835,52.8047379 26.5857864,53.5857864 C25.8047379,54.366835 25.8047379,55.633165 26.5857864,56.4142136 L36.5857864,66.4142136 C37.366835,67.1952621 38.633165,67.1952621 39.4142136,66.4142136 L57.4142136,48.4142136 C58.1952621,47.633165 58.1952621,46.366835 57.4142136,45.5857864 C56.633165,44.8047379 55.366835,44.8047379 54.5857864,45.5857864 L38,62.1715729 L29.4142136,53.5857864 Z" id="Path" fill="#52BEF9" fill-rule="nonzero"></path>                </g>            </g>        </g>    </g></svg>```

**Comment by catalinmiron** [comment]
Can you please pass through https://www.smooth-code.com/open-source/svgr/playground/ your svg and check React-Native as output 
![image](https://user-images.githubusercontent.com/2805320/58637957-f0324180-82f3-11e9-8a8f-a798311c3f30.png)

Alternative, try referring to: https://github.com/react-native-community/react-native-svg#use-with-svg-files.
Use react-native-svg-uri: https://github.com/react-native-community/react-native-svg#use-with-content-loaded-from-uri.
Here's a link to the snack: https://snack.expo.io/@catalinmiron/grounded-milkshake.

Thanks!

**Comment by KamranKhankhail** [comment]
@catalinmiron I've followed `https://github.com/react-native-community/react-native-svg#use-with-content-loaded-from-uri`
but same issue as mentioned above by @vtn-dev2016.
Anybody have ever solved this problem?

**Comment by msand** [comment]
Latest version has built in xml parser and fetching from uri. Try using that, and reopen if you're still having issues.
