### ISSUE TITLE
Can't animate inherited color

### ISSUE THREAD

**Issue by derekstavis** [react-native-community/react-native-svg#1017]
# Bug

Using `createAnimatedComponent` and animating the `color` style property is not supported.

## Environment info

React native info output:

```bash

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 51.68 MB / 32.00 GB
      Shell: 3.0.0 - /usr/local/bin/fish
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
```

Library version: 8.0.10

## Steps To Reproduce

Describe what you expected to happen:

1. Create an animated component from `Svg` component.
1. Use `currentColor` to inherit the `color` from `style` prop.
1. Use `Animated.Value` to interpolate the `color` on `<Svg style=`
1. See the color transition

## Reproducible sample code

See the following Snack:

https://snack.expo.io/@derekstavis/react-native-svg-color-animation

**Comment by msand** [comment]
Can you test the latest commit in the develop branch?

**Comment by tberman** [comment]
@msand since this was merged, I get an error about `processColor` not being called from every RN-SVG component. Downgrading to 9.5.1 fixed it.

**Comment by msand** [comment]
Oh really? Can you make a repro?
