### ISSUE TITLE
Svg to React Native Svg converter doesn't work correct.

### ISSUE THREAD

**Issue by ForeverYouth** [react-native-community/react-native-svg#1020]
Hi everyone. I have next problem. I tried convert SVG file which given me by designer. I use [this service](https://www.smooth-code.com/open-source/svgr/playground/). But something wrong. I could do it. It doesn't render. 

Can you help me ? Or maybe can you give me another solution for using my svg file in project.

Sorry about my decor. It's my first issues which i have ever posted.

My svg file: 
`<svg width="304" height="168" viewBox="0 0 304 168" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 0V168H304V0H0Z" fill="url(#paint0_linear)"/>
<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="304" height="168">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 0V168H304V0H0Z" fill="url(#paint1_linear)"/>
</mask>
<g mask="url(#mask0)">
<g filter="url(#filter0_d)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 -98V226L230.956 142.485C242.307 138.38 245.199 123.664 236.245 115.569L0 -98Z" fill="url(#paint2_linear)"/>
</g>
<g filter="url(#filter1_d)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M0 -40V163L135.02 114.055C146.355 109.946 149.245 95.2533 140.311 87.1573L0 -40Z" fill="url(#paint3_linear)"/>
</g>
</g>
<defs>
<filter id="filter0_d" x="-24" y="-106" width="273.52" height="356" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dx="-8" dy="8"/>
<feGaussianBlur stdDeviation="8"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0.486275 0 0 0 0 0.764706 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<filter id="filter1_d" x="-24" y="-48" width="177.573" height="235" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dx="-8" dy="8"/>
<feGaussianBlur stdDeviation="8"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0.486275 0 0 0 0 0.764706 0 0 0 0.8 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
<linearGradient id="paint0_linear" x1="-8.08597e-06" y1="168" x2="92.3382" y2="-19.9742" gradientUnits="userSpaceOnUse">
<stop stop-color="#1581E6"/>
<stop offset="1" stop-color="#1A9EFD"/>
</linearGradient>
<linearGradient id="paint1_linear" x1="304" y1="-8.76188e-06" x2="161.757" y2="257.392" gradientUnits="userSpaceOnUse">
<stop stop-color="#FFA800"/>
<stop offset="1" stop-color="#FF6F00"/>
</linearGradient>
<linearGradient id="paint2_linear" x1="-6.80923e-06" y1="226" x2="223.448" y2="27.3793" gradientUnits="userSpaceOnUse">
<stop stop-color="#1581E6"/>
<stop offset="1" stop-color="#1A9EFD"/>
</linearGradient>
<linearGradient id="paint3_linear" x1="-4.25577e-06" y1="163" x2="139.959" y2="38.8983" gradientUnits="userSpaceOnUse">
<stop stop-color="#1581E6"/>
<stop offset="1" stop-color="#1A9EFD"/>
</linearGradient>
</defs>
</svg>`

**Comment by TheJoeCollins** [comment]
You are going to want to take a look at react-native-svg-transformer. 
Then make sure you updated your babel or metro config to handle .svg assets.

Its all explained within the repo.
