### ISSUE TITLE
Bring this package under @react-native-community/svg ?

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/react-native-svg#1021]
# Feature Request

## Why it is needed
I think a lot of packages within community are now under `@react-native-community` namespace, perhaps svg should be there as well for consistency i.e. from next big version bump perhaps?

**Comment by msand** [comment]
Sure, fine by me at least. Could even publish under both. But I'm not sure what it would require. @cpojer can you give me the rights to publish under that namespace? Or how are the rights handled? Perhaps I'm able to already? Or should CI be set up to autopublish? Perhaps safer to restrict publishing rights to npm more than merging rights to master.

**Comment by cpojer** [comment]
@msand what's your npm username?

**Comment by msand** [comment]
@cpojer https://www.npmjs.com/~msand

**Comment by cpojer** [comment]
I added you to @react-native-community.

**Comment by msand** [comment]
Great, thanks!
