### ISSUE TITLE
Touch event issues with <Text> and get the location of the touched element

### ISSUE THREAD

**Issue by meraklis56** [react-native-community/react-native-svg#1026]
I am trying to implement simple touch events on a <Text> element. Due to <Text> element properties the user must press exactly on the letter, thus half of the touches are gone undetected. 

Currently, the text is dynamic, so I can not use a <Rect> and detect the missing touches.

Is there any way that I can achieve that? 

Also, currently I have implemented drag n drop in which it receives the touch location and changes the x and y of the element. But I since I can not know, exactly where on the element the user has pressed, the drag n drop is not smooth. Any ideas on that?

**Comment by msand** [comment]
I've added getBBox, getCTM, getScreenCTM, getTotalLength, getPointAtLength and isPointInFill to the develop branch now. Would you be available to help testing?
I have a PR open here: #1135

**Comment by msand** [comment]
Can you try with the latest version?
