### ISSUE TITLE
Changing color prop on svg element doesn't  trigger rerender

### ISSUE THREAD

**Issue by SergeyPanchenkoWeWork** [react-native-community/react-native-svg#1029]
# Bug
changing `color` prop on SVG element doesn't trigger a change to inherited colors.

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 129.69 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: 9.5.1

## Steps To Reproduce
Create SVG component with color prop
Have a child in svg using `currentColor`
Change the color prop

Describe what you expected to happen:

1. The child color to be updated to the new color

## Reproducible sample code
https://snack.expo.io/r1yWWPAA4

**Comment by njdancer** [comment]
I believe I'm having the same issue. I'm using [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer) so am not specifying the svg the same way but I have an svg that uses currentColor. I can change the colour that is ultimately rendered by changing the color style on the svg however if this changes at runtime the svg color does not update.

Did you find any workaround for this? At this stage I'm considering maintaining seperate versions of the svg file in both colors I need and switching between them which will be a PITA but I can't think of anything else.

**Comment by msand** [comment]
I have a fix for this, I'll just need to test it first, will probably publish later today.

**Comment by SergeyPanchenkoWeWork** [comment]
@njdancer I found a workaround but it is really hacky.
when I detect color prop change I render `null` instead of the component and then after 20 milliseconds, I rerender the svg with the new color.

**Comment by msand** [comment]
Can you test the latest commit in the develop branch?

**Comment by SergeyPanchenkoWeWork** [comment]
I was able to validate locally that it fixes the issue

**Comment by njdancer** [comment]
@SergeyPanchenkoWeWork Thats cool. Does that cause a flicker because a single frame renders nothing? I just ended up duplicating the few svg's I needed in multiple colours which gives me a unique component reference for each colour. Because the files are exact duplicates I believe they won't take up extra space in the repo, only the final bundle. Looking forward to a proper fix though.

@msand Thanks for the quick turnaround. Great library! Keep up the great work.

**Comment by slorber** [comment]
Can confirm this issue. Not that I really need the feature but it drove me crazy not understanding why my storybook color knob didn't work :)

Simple workaround is key={color} to remount the SVG

**Comment by SergeyPanchenkoWeWork** [comment]
@slorber That is a very elegant solution. Nice, Thanks.

**Comment by njdancer** [comment]
@slorber This works great until expo update their dependency on react-native-svg. Thanks.
