### ISSUE TITLE
Android rect paths are stored as integers

### ISSUE THREAD

**Issue by driley-emoney** [react-native-community/react-native-svg#1033]
# Bug

Internally paths for a Rect are stored as integers (Android graphics path). This can create rounding issues on devices with non integer pixel ratios

For instance if I specify a rect like so

```
<Svg width="100%" height="100%" viewBox="0 0 17 17">
  <Rect width="17" height="17" />
</Svg>
```

Internally the library multiplies those values by the pixel ratio of the device (mScale) and stores them as integers so, if you have a pixel ratio that is not an even integer like 2.6 you have:

width = round(17 * 2.6) = round(44.2) = 44

As the SVG get scaled up this .2 error gets scaled up to so your rect no longer covers your svg.

In order to get around this I have to pre-divide any values by the pixel ratio. Then it works perfectly.

## Environment info

React native info output:

```bash
   React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 25.07 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 27, 28
        Build Tools: 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

Library version: 9.4.0

## Steps To Reproduce

Create an svg like this: 

Describe what you expected to happen:

1. Create a small svg set to scale to fill device width

```
<Svg width="100%" height="100%" viewBox="0 0 17 17">
  <Rect width="17" height="17" />
</Svg>
```

2. Run on a device like nexus 5 with a weird pixel ratio

3. Observe that rect does not fill screen

**Comment by msand** [comment]
Can you try with the latest commit in the develop branch?

**Comment by msand** [comment]
This is fixed in the latest version, closing.
