### ISSUE TITLE
Android: Error while updating property matrix of a view managed by RNSVGPath

### ISSUE THREAD

**Issue by manuTro** [react-native-community/react-native-svg#1039]
Sometimes my android app crashes with this error: 
 `Android: Error while updating property matrix of a view managed by RNSVGPath`. 
It happens sometimes, I cannot reproduce it. 

  "react-native-svg": "^9.3.5",
    "react": "^16.3.1",
    "react-native": "^0.55.4",

![Screenshot_1562163922](https://user-images.githubusercontent.com/25326470/60605316-996bcc00-9db9-11e9-90df-5e258d85f44d.png)

**Comment by msand** [comment]
Hard to help in any way without a reproduction. Have you tried upgrading to the latest versions?
