### ISSUE TITLE
Android : Error : Invariant Violation: is not usable as a native method argument

### ISSUE THREAD

**Issue by sourabhchotia** [react-native-community/react-native-svg#1041]
So i Wanted to Implement Charts in My React-native App and For that i installed react-native-chart-kit packed and it said that i need to install the react-native-svg package also so i did

Commands fired are

npm i react-native-chart-kit --save
npm i react-native-svg
react-native link react-native-svg

after running react-native run-android i got error
``ef6c45d3-878a-4fbc-9…-cf18399ccbf4:40283 Invariant Violation: [57,"RNSVGRect",21,{"matrix":[1,0,0,1,0,0],"rotation":0,"scaleX":1,"scaleY":1,"x":"<<NaN>>","y":-76,"propList":["fill"],"opacity":1,"fill":[0,857407378],"fillRule":1,"fillOpacity":1,"stroke":null,"strokeOpacity":1,"strokeLinecap":0,"strokeLinejoin":0,"strokeDasharray":null,"strokeWidth":1,"strokeDashoffset":null,"strokeMiterlimit":4,"vectorEffect":0,"width":"16px","height":"16px","rx":8,"ry":8}] is not usable as a native method argument

This error is located at:
    in RNSVGRect (at Rect.js:22)
    in Rect (at progress-chart.js:93)
    in RNSVGGroup (at G.js:23)
    in G (at progress-chart.js:90)
    in RNSVGGroup (at G.js:23)
    in G (at progress-chart.js:61)
    in RNSVGGroup (at G.js:23)
    in G (at Svg.js:127)
    in RNSVGSvgView (at Svg.js:116)
    in Svg (at progress-chart.js:48)
    in RCTView (at View.js:45)
    in View (at progress-chart.js:40)
    in ProgressChart (at Component.js:211)
    in RCTView (at View.js:45)
    in View (at Component.js:210)
    in RCTView (at View.js:45)
    in View (at Component.js:209)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at Component.js:188)
    in Dashboard (at navigationStore.js:448)
    in Wrapped (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:477)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:476)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in RCTView (at View.js:45)
    in View (at DrawerLayoutAndroid.android.js:198)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:217)
    in DrawerLayoutAndroid (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:477)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:476)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
    in Router (at app/index.js:108)
    in AuthenticScreen (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

Please Help me Solving This

react-native version = 0.59.8
react-native-svg version = 9.5.1
react-native-chart-kit version = 3.0.0

``

**Comment by msand** [comment]
The "x":"<>" part looks strange, probably some issue with the data, processing or something in that library. Hard to say anything without a complete replication, could you make a snack or a cloneable git repo?

**Comment by sourabhchotia** [comment]
> The "x":"<>" part looks strange, probably some issue with the data, processing or something in that library. Hard to say anything without a complete replication, could you make a snack or a cloneable git repo?

the issue was resolved by setting the state 

i was directly assigning data to the progress chart

like data ={ [0.4] }
