### ISSUE TITLE
Native module RNSVGSvgViewManager tried to override SvgViewModule

### ISSUE THREAD

**Issue by manastunga787** [react-native-community/react-native-svg#1043]
#  Native module RNSVGSvgViewManager tried to override SvgViewModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. if the was your intention, set canOverrideExistingModule=ture

I am manually trying to link react-native-svg to my **react-native  android project**
by following the procedures mentioned in the [docs](https://github.com/react-native-community/react-native-svg#android)

Add new SvgPackage() to the list returned by the getPackages() method MainApplication.java file.
my,  MainApplication.java file has the following code

```
package com.helloboy;
import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.horcrux.svg.SvgPackage;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new SvgPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**Comment by manastunga787** [comment]
I am using 

```
 "react": "16.8.6",
 "react-native": "0.60.0",
 "react-native-svg": "^9.5.1"
```
don't import `import com.horcrux.svg.SvgPackage;`
in  `android/app/src/main/java/[...]/MainApplication.java` as suggested by [docs](https://github.com/react-native-community/react-native-svg#android) 

No need to add `new SvgPackage()`  to the list returned by the `getPackages()` method.

so leave the `MainApplication.java`  as it is.

So i have commented out `import com.horcrux.svg.SvgPackage;` and `packages.add(new SvgPackage());
` in my MainApplication.java.

 Now it works 😀
```
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
// import com.horcrux.svg.SvgPackage;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
     // packages.add(new SvgPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**Comment by nileshprajapati007444** [comment]
I am facing the same error.

I have upgraded my react native app version to 0.60 latest. Do we not required to change/add packages in MainApplication.java file ?

Will app work without adding in MainApplication.java file ?

**Comment by Manil-SoftNEP** [comment]
This worked for me.
Inside 'android/app/src/main/java/com/<your_app_name>/MainApplication.java '.

1. I removed `import com.horcrux.svg.SvgPackage;` to the imports at the top of the file.

2. In the `getPackages()` method, below `List<ReactPackage> packages = new PackageList(this).getPackages();` I removed `packages.add(new SvgPackage());` or `new SvgPackage()`.

**Comment by Witillan** [comment]
> Estou enfrentando o mesmo erro.
> 
> "react-native-svg": "^13.9.0" esta é a versão mais recente nesta versão que enfrenta o problema
> 
> Isso funcionou para mim.
> 
> Estou usando "react": "18.2.0", "react-native": "0.71.8", "react-native-svg": "^12.3.0"
> 
> Dentro de 'android/app/src/main/java/com/<your_app_name>/MainApplication.java'.
> 
> Eu removi import com.horcrux.svg.SvgPackage; às importações na parte superior do arquivo. No método getPackages(), abaixo de List packages = new PackageList(this).getPackages(); Eu removi packages.add(new SvgPackage()); ou novo SvgPackage().

This worked for me
