### ISSUE TITLE
Archive IOS fails but build goes well

### ISSUE THREAD

**Issue by acaballero4** [react-native-community/react-native-svg#1045]
# Bug

Hello! 

I have two errors when i do the archive option in Xcode (always the first error, sometimes the second error):

First error: 

- Multiple commands produce '../Xcode/DerivedData/x/Build/Intermediates.noindex/ArchiveIntermediates/x/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libRNSVG.a':

1) Target 'RNSVG' has a command with output '../Xcode/DerivedData/x/Build/Intermediates.noindex/ArchiveIntermediates/x/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libRNSVG.a'
2) Target 'RNSVG' has a command with output '../Xcode/DerivedData/x/Build/Intermediates.noindex/ArchiveIntermediates/x/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libRNSVG.a'

Sometimes the error has only 1 line (instead of two same lines).

![imagen](https://user-images.githubusercontent.com/32458206/60894029-39b26c80-a262-11e9-97ce-129f1a47dfb0.png)

![imagen](https://user-images.githubusercontent.com/32458206/60894446-f4db0580-a262-11e9-9e71-3753e40aa763.png)

I have tried with the all linking documentation and suggestions and the error doesn't fix. Even i try unistall-install & unlink-link options and nothing, also clean Derived Data of Xcode.

Second error:

- clang: error: no such file or directory: '../Xcode/DerivedData/x/Build/Intermediates.noindex/ArchiveIntermediates/x/BuildProductsPath/Release-iphoneos/libRNSVG.a'
Command Ld failed with a nonzero exit code.

This error appears sometimes in the different attempts to do the Archive (i have linked correctly the "libRNSVG.a" module).

The build and the library on the project works well, it's only when i want distribute this app when i have this problems.

## Environment info

React native info output:

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 145.99 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: 9.5.1

## Steps To Reproduce

Exactly the same steps of the documentation.

Thanks in advance!

**Comment by liaoyinglong** [comment]
hi, do  you  resolve ?

**Comment by acaballero4** [comment]
Hi, for the moment, I didn't find the way to solve it. I tried to remove all the data of the library and install it again, doing exactly the same steps of the manual to link the library but nothing yet.

**Comment by acaballero4** [comment]
Hi, for the moment, I didn't find the way to solve it. I tried to remove all the data of the library and install it again, doing exactly the same steps of the manual to link the library but nothing yet.

**Comment by msand** [comment]
Can you make a cloneable git repo with a reproduction?

**Comment by acaballero4** [comment]
yes, I will create the repo between today and tomorrow

**Comment by acaballero4** [comment]
Hi, i created a new app with the command "react-native init x", install the library and do the steps to link. After all, i do the Archive and i get the second error that i have mentioned in the post: 

- clang: error: no such file or directory: '../Xcode/DerivedData/x/Build/Intermediates.noindex/ArchiveIntermediates/x/BuildProductsPath/Release-iphoneos/libRNSVG.a'
Command Ld failed with a nonzero exit code

This is the repo to do a reproduction: https://github.com/acaballero4/testsvg4
Thank you guys.

**Comment by acaballero4** [comment]
Hi! Finally I solve this issue removing references on react project (Pods React). Thanks you.

**Comment by waleedarshad** [comment]
Hi @acaballero4 how did you remove these references

**Comment by acaballero4** [comment]
On Xcode side menu (folder icon): Pods project (blue icon) -> Development Pods and click on React remove option -> Remove References. With that do the archive correctly.

**Comment by alexlevy0** [comment]
hello, 
I have the same issue with RN 0.61.5 and RNSVG 9.13.6
@acaballero4 what version of RN are you using please ?

**Comment by acaballero4** [comment]
@alexlevy0 I'm using React native 0.59.8

**Comment by gomezmark** [comment]
Any solutions for this?
I am using 
"react-native": "0.59.9",
"react-native-svg": "9.13.6",
"react-native-svg-transformer": "^0.14.3",

Thanks

**Comment by acaballero4** [comment]
Hi @gomezmark I solved this issue removing the duplicated library import. 

I had a podfile link and "manual linking" (xcode) so I removed the xcode linking and I solved the issue.

**Comment by gomezmark** [comment]
Hi @acaballero4 , thanks for the tip. It is working now.
I did manual linking then restart the xCode.
Thanks much
