### ISSUE TITLE
Error while updating property 'width' in shadow node of type: RNSVGSvgView

### ISSUE THREAD

**Issue by brajeshsipl** [react-native-community/react-native-svg#1046]
# Bug

## Environment info

I am getting below error in the android application.

```bash
 "react-native": "0.55.4",
```

Library version: "react-native-svg": "^8.0.10",

![Screenshot_20190710-182235_Stage   Set](https://user-images.githubusercontent.com/20771295/60972170-570b3780-a343-11e9-94a5-99e908937049.jpg)

**Comment by msand** [comment]
Can you try upgrading to the latest version?

**Comment by inferusvv** [comment]
Have this issue after upgrading to RN 0.61.1

**Comment by msand** [comment]
Can you post a reproduction?
