### ISSUE TITLE
SVG Image does not render local SVG files (cached files, not assets)

### ISSUE THREAD

**Issue by ali-farooq0** [react-native-community/react-native-svg#1047]
# Bug
Locally stored SVG image files fail to render when using `react-native-svg`'s `Image` component.

## Environment info

React native info output:

```bash
 info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
      Memory: 27.60 MB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 9.5.1

## Steps To Reproduce

1. Clone `git@github.com:ali-farooq0/RN-svg-repro.git`
2. Run `npm install`
3. Run `npm run android` (make sure an emulator/device is running)
4. Make sure app is running
5. Observe that there is no SVG displayed in the app

For further debugging
6. Run `adb logcat`
7. Observe following log output
```
07-10 21:51:20.217 19877 20258 D skia    : --- Failed to create image decoder with message 'unimplemented'
07-10 21:51:20.218 19877 20258 D skia    : --- Failed to create image decoder with message 'unimplemented'
07-10 21:51:20.220 19877 20259 W unknown:ProgressiveDecoder: unknown image format, {uri: file:///data/user/0/com.svgrepro/files/RNFetchBlobTmp_xoz9wsh6exnqhfz610e2o, firstEncodedBytes: 3C73766720786D6C6E73, length: 422}
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: RNSVG: fetchDecodedImage failed!
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: com.facebook.imagepipeline.decoder.DecodeException: unknown image format
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:62)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
07-10 21:51:20.221 19877 19877 W unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
```

Describe what you expected to happen:
`Image` component to successfully render locally stored SVG image files. Reading through the log, looks like it fails to parse the SVG file `07-10 21:51:20.220 19877 20259 W unknown:ProgressiveDecoder: unknown image format, {uri: file:///data/user/0/com.svgrepro/files/RNFetchBlobTmp_xoz9wsh6exnqhfz610e2o, firstEncodedBytes: 3C73766720786D6C6E73, length: 422}`. This package needs to add support for SVG image decoder, something like: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/svg/SvgDecoderExample.java

## Reproducible sample code
Created a fresh codebase that reproduces the issue
https://github.com/ali-farooq0/RN-svg-repro/blob/master/App.tsx

To verify that the issue is with the decoder, and not my setup, simply comment out line https://github.com/ali-farooq0/RN-svg-repro/blob/master/App.tsx#L12
and uncomment https://github.com/ali-farooq0/RN-svg-repro/blob/master/App.tsx#L13

## Workarounds that I've tried
1. I've used https://github.com/react-native-community/react-native-svg/blob/master/README.md#use-with-content-loaded-from-uri to fetch svgs remotely, however it doesn't work for me as I need to fetch an SVG with custom `GET` headers (cookies, csrf token, etc.), which is why I've had to use `RNFetchBlob.fetch(...)`.

2. I've also tried using `react-native-svg-uri` by setting the `svgXmlData` field. That works for simple cases, but does not work for complex svg files. Already filed an issue with them regarding that: https://github.com/vault-development/react-native-svg-uri/issues/186

## When rendering an SVG:
![image](https://user-images.githubusercontent.com/25732808/61016427-99417280-a35d-11e9-9436-cf7319306a27.png)

## When rendering a jpg (using the same code):
![image](https://user-images.githubusercontent.com/25732808/61016459-af4f3300-a35d-11e9-90aa-6d32b492f57b.png)

It's really unfortunate that an RN SVG component can't render SVG files :(

**Comment by Kingles** [comment]
Hey there!

Sorry for the frustration; unfortunately I do not believe this is a bug; the Image component is designed specifically to display Images as supported by react-native directly (see: https://facebook.github.io/react-native/docs/image#source).

Any ability to display `.svg` files would be the purview of either another project or a future enhancement.

**Comment by ali-farooq0** [comment]
@Kingles Seeing that our project requires the capability of displaying `.svg` files, what's the best way to go about adding this enhancement to either this project or the `Image` component directly?

**Comment by msand** [comment]
How about https://github.com/react-native-community/react-native-svg/blob/master/README.md#use-with-content-loaded-from-uri

**Comment by ali-farooq0** [comment]
@msand as mentioned in the description, already tried it, doesn't work because i need to use custom `GET` request (with custom cookies, csrf). But even if I did the component itself just parses the content and sets data through `svgXmlData` field, which doesn't work. Have already opened a bug for them: https://github.com/vault-development/react-native-svg-uri/issues/186

> I've used vault-development/react-native-svg-uri to fetch svgs remotely, however it doesn't work for me as I need to fetch an SVG with custom GET headers (cookies, csrf token, etc.), which is why I've had to use RNFetchBlob.fetch(...).

**Comment by Kingles** [comment]
At this point it seems like the issue is going to be with `react-native-svg-uri` rather than here. @msand --Can we close for now as supporting `.svg` in this way isn't within the current purview of this project?

**Comment by ali-farooq0** [comment]
@Kingles If this project does not support `.svg` files then which one would? I don't think there is one. It makes sense to have either the builtin `Image` component support `.svg` file rendering or this project. Otherwise there is no way to render `.svg` files.

**Comment by msand** [comment]
The latest version now supports .svg files, xml content, and fetching from uris.
