### ISSUE TITLE
Touchable opacity on press not working  inside SVG tags 

### ISSUE THREAD

**Issue by aravind1078** [react-native-community/react-native-svg#1050]
# Bug
I have a component inside an SVG where I have a button(touchable Opacity with View) inside the component while the button onClick worked fine standalone,  it's not working when I wrap the component inside the SVG

## Environment info
RN-0.59.6

minimal code:
```bash
 <Svg width={'100%'} height={'100%'} viewBox='0 0 360 243' {...props}>
      <Defs>
        <LinearGradient
          id='prefix__b'
          x1={'75.7%'}
          y1={'34.3%'}
          x2={'84.6%'}
          y2={'-9.6%'}
          gradientUnits='objectBoundingBox'
        >
          <Stop offset={1} stopColor='#2ff290' />
        </LinearGradient>
      </Defs>
      <View >
          <TouchableOpacity
              onPress={() => {
                console.log('DSDA')
              }}
            ><Text>Click me!!</Text>
          </TouchableOpacity>
          </View>
    </Svg>
```
Library version: 9.3.7

Describe what you expected to happen:

1.onClick event fires and it console logs

**Comment by msand** [comment]
Using View inside Svg is not supported at the moment. You can use e.g. TouchableOpacityG with svg content from here: https://github.com/react-native-community/react-native-svg/issues/645#issuecomment-453693511 or move the View outside the Svg root in the same parent, and position it absolutely on top of the Svg.
