### ISSUE TITLE
When in production can't import svg and no render images

### ISSUE THREAD

**Issue by mrigo** [react-native-community/react-native-svg#1052]
# Bug

When in development everything works fine, when I'm trying to create a release version, I've got the error:
```
Error: The file name must end with .xml or .png
```
for every file, so I've added `android.disableResourceValidation=true` to `gradle.properties` file.
Now I can compile and create my release version of the app, but when start the app I can't see any of the svg.

How can I fix this?

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 1.19 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
      npm: 6.3.0 - ~/.nvm/versions/node/v8.4.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
        System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.58.5 => 0.58.5
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: 9.5.1

Thanks!

**Comment by Kingles** [comment]
Hey Friend, 

Can you provide some more information about your setup? Perhaps some example code or a repro case?

**Comment by rasmniel** [comment]
I'm having this exact issue as well. Adding `android.disableResourceValidation=true` fixes the problem of compiling, but adds a warning to the build:
```WARNING: The option setting 'android.disableResourceValidation=true' is experimental and unsupported.```
And the result is that no SVGs are rendered at all.
