### ISSUE TITLE
Invariant Violation: View config not found for name <svg width ...

### ISSUE THREAD

**Issue by ithustle** [react-native-community/react-native-svg#1054]
# Bug

![Screenshot_1563544674](https://user-images.githubusercontent.com/5114680/61540727-18a60480-aa36-11e9-9b69-09b661061c9a.png)

React native info output:

```
System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 1.40 GB / 11.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4
```

Library version: 9.5.3

## Steps To Reproduce
Before:
yarn add react-native-svg
yarn add react-native-svg-transformer -D

After
Enable hermes
yarn add babel-plugin-inline-import -D

Describe what you expected to happen:

1. Show icons 

## Reproducible sample code

myComponent.js
```
import React from "react";
import { Platform } from "react-native";

import IconHome from "./../imgs/icon/home.svg";
export const Home = props => ( <IconHome { ...props } width={22} height={22} /> );
```
...

screen.js
```
import { Search, Genero, MinhasMusicas, Home } from "./../components/Icon";
<Home key={1} />
```

**Comment by Sylwuchaa** [comment]
Hello, I have the same problem, did You solve it ??

**Comment by ithustle** [comment]
Noup, @Sylwuchaa

**Comment by msand** [comment]
Can you make a reproduction as a clonable git repo?

**Comment by ithustle** [comment]
> Can you make a reproduction as a clonable git repo?

@msand, I use a private repo. But you can download here 
[ithustle-toqueplay-d29670962b65.zip](https://github.com/react-native-community/react-native-svg/files/3418160/ithustle-toqueplay-d29670962b65.zip)

**Comment by msand** [comment]
Actually, it seems the transformer isn't working/configured correctly. Seems you're trying to use the svg string as a component, rather than an actual js / react component.

**Comment by ithustle** [comment]
This same code works before I've updated RN 0.60.3 to 0.64 and enabled Hermes ... I cannot undestand why... 

Can you show me a correct configuration? I'm using [react-native-svg-transformer](kristerkari/react-native-svg-transformer) to transforme dinamicaly svg images...

**Comment by ithustle** [comment]
@Sylwuchaa , anything?

**Comment by msand** [comment]
Sorry, wasn't at the computer at the moment, just read the actual error message. Does it work with 0.60.4 with hermes disabled?

**Comment by msand** [comment]
I suspect the issue is with react-native-svg-transformer and hermes, or some change to the handling of the metro config, @kristerkari any ideas?

**Comment by kristerkari** [comment]
It looks like they have updated something in the newest React Native version. I haven't been home so much lately, but I can have a look at this tomorrow.

**Comment by ithustle** [comment]
Maybe @kristerkari is right. I used like this:
myComponentIcon.js

```
import HomeIcon from “./imgs/home.svg”;

export const Home = props => (<HomeIcon {...props} />);
```

Screen.js

```
import { Home } from “./myComponentIcon”;

...
render() {
    return (
        <Home />
    );
}
```

#That way it doesn’t work. But if I call `import HomeIcon from “./imgs/home.svg”;` directly on `screen.js` some svg imagens works ...

**Comment by ithustle** [comment]
@msand Noup. It doesn’t

**Comment by ithustle** [comment]
**** UPDATE *****
![Screenshot_1563870122](https://user-images.githubusercontent.com/5114680/61695496-7df64000-ad2b-11e9-81f9-f703b8c88090.png)

A svg image downloaded from www.flaticon.com called directly on `screen.js`. But my images worked on Inkscape works fine.

**Comment by kristerkari** [comment]
I created a new React Native project and installed both `react-native-svg` and the transformer. 

Everything was working fine, both on iOS and Android (with Hermes disabled and enabled), so this looks like something related to @ithustle's project/configuration.

**Comment by waleedarshad** [comment]
Same issue While running svg with transformation



package.json
`  "react-native": "0.59.9"`,
`    "react-native-svg-transformer": "^0.13.0",`,
`    "react-native-svg": "^9.9.4",`

Metro.config.js
`const { getDefaultConfig } = require("metro-config");

     module.exports = (async () => {
      const {
       resolver: { sourceExts, assetExts }
      } = await getDefaultConfig();
      return {
      transformer: {
         getTransformOptions: async () => ({
           transform: {
            experimentalImportSupport: false,
            inlineRequires: false
         }
      }),
        babelTransformerPath: require.resolve("react-native-svg-transformer")
      },
       resolver: {
        assetExts: assetExts.filter(ext => ext !== "svg"),
        sourceExts: [...sourceExts, "svg"]
        }
     };
    })();`


index.js
 ```
import { Bower } from "./bower.svg";
 <Bower width={120} height={40} /> Not working???
```

if I use with SvgXml it works.

```
import { SvgXml } from "react-native-svg";
 <SvgXml width="200" height="200" xml={Bower} /> Working
```


<img width="371" alt="Screenshot 2019-10-14 at 17 59 41" src="https://user-images.githubusercontent.com/5329697/66761313-6b178580-eeac-11e9-929e-b82cf94117a1.png">

**Comment by lucca-cardial** [comment]
Nothing here ?

**Comment by kopax** [comment]
I still have this issue on expo sdk 36. Is there a way to use svg in react native at this time?

**Comment by msand** [comment]
You're probably having some configuration issue related to react-native-svg-transformer rather than react-native-svg

**Comment by kristerkari** [comment]
@kopax is it possible for you to upload your project somewhere where I could have a look at it? It's very difficult to help without seeing the project/configurations in use.

**Comment by bensonnn7** [comment]
> Same issue While running svg with transformation
> 
> package.json
> ` "react-native": "0.59.9"`,
> ` "react-native-svg-transformer": "^0.13.0",`,
> ` "react-native-svg": "^9.9.4",`
> 
> Metro.config.js
> `const { getDefaultConfig } = require("metro-config");
> 
> ```
>  module.exports = (async () => {
>   const {
>    resolver: { sourceExts, assetExts }
>   } = await getDefaultConfig();
>   return {
>   transformer: {
>      getTransformOptions: async () => ({
>        transform: {
>         experimentalImportSupport: false,
>         inlineRequires: false
>      }
>   }),
>     babelTransformerPath: require.resolve("react-native-svg-transformer")
>   },
>    resolver: {
>     assetExts: assetExts.filter(ext => ext !== "svg"),
>     sourceExts: [...sourceExts, "svg"]
>     }
>  };
> })();`
> ```
> 
> index.js
> 
> ```
> import { Bower } from "./bower.svg";
> <Bower width={120} height={40} /> Not working???
> ```
> 
> if I use with SvgXml it works.
> 
> ```
> import { SvgXml } from "react-native-svg";
>  <SvgXml width="200" height="200" xml={Bower} /> Working
> ```
> 
> <img alt="Screenshot 2019-10-14 at 17 59 41" width="371" src="https://user-images.githubusercontent.com/5329697/66761313-6b178580-eeac-11e9-929e-b82cf94117a1.png">

Hi, I have encountered the same issue, did u figure it out?
