### ISSUE TITLE
SVG imported get imported as numbers

### ISSUE THREAD

**Issue by Muljayan** [react-native-community/react-native-svg#1055]
# Bug

## Environment info

React native info output:

```bash
"react": "16.8.3",
"react-native": "0.59.8"
```

Library version: 1.2.3

## Steps To Reproduce

1. Import the svg as `import MySVG from './mysvg.svg';`
2. Log the imported svg above return statement `console.log(MySVG)`

Describe what you expected to happen:

1. When MySVG is console logged it should log the imported SVG as a string format.
2. Sometimes this works as expected and returns the SVG in string format.

## Reproducible sample code
```
import React from 'react';
// import SvgUri from 'react-native-svg-uri';

import MySVG from './mysvg.svg';

const MyComponent = () => {
  console.log(MySVG); // Outputs numbers
  return (
     <>
      {/* <SvgUri
        svgXmlData={MySVG}
        width="25"
        height="25"
      /> */}
    </>
  );
};

export default MyComponent;
```

**Comment by msand** [comment]
Check the docs: https://github.com/react-native-community/react-native-svg#use-with-svg-files

**Comment by Muljayan** [comment]
@msand Thank you for your response. Upon checking the docs I noticed that I have to include the following code in .babelrc file.
```

  "plugins": [
    ["babel-plugin-inline-import", {
      "extensions": [
        ".svg"
      ]
    }]
  ]
```

Since I am using react native 0.6 i included it in babel.config.js and now it works.
