### ISSUE TITLE
The file name must end with .xml or .png

### ISSUE THREAD

**Issue by joshi-anshul** [react-native-community/react-native-svg#1056]
Hello,
I generate apk(React-native) and get error "The file name must end with .xml or .png". The problem connected to files I add to the page using <SvgUri> (import SvgUri from 'react-native-svg';) tag. Those are the only files that has extension of svg in drawable-mdpi folder. What to do?
#react-native-svg

Thanks

**Comment by msand** [comment]
Remove the files from the drawable folders.

**Comment by joshi-anshul** [comment]
Issue fixed, "react-native-svg-transformer" worked for me.
