### ISSUE TITLE
Invariant Violation: requireNativeComponent "RNSVGCIRCLE" was not found in the UIMANAGER

### ISSUE THREAD

**Issue by saudahmed** [react-native-community/react-native-svg#1058]
# Bug

## Environment info

React native info output:
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 28.97 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 22.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
    react-native: 0.59.1

Library version: 9.5.3

## Steps To Reproduce

1. react-native init SomeProject
2. cd SomeProject
3. npm i react-native-svg
4. react-native link

Also manually linked but of no use.

Describe what you expected to happen:

1. Circle and rect to appear.

## Reproducible sample code
import Svg,{
    Circle,
    Ellipse,
    G,
    Text,
    TSpan,
    TextPath,
    Path,
    Polygon,
    Polyline,
    Line,
    Rect,
    Use,
    Image,
    Symbol,
    Defs,
    LinearGradient,
    RadialGradient,
    Stop,
    ClipPath,
    Pattern,
    Mask,
} from 'react-native-svg';

/* Use this if you are using Expo
import { Svg } from 'expo';
const { Circle, Rect } = Svg;
*/

import React from 'react';
import { View, StyleSheet } from 'react-native';

export default class SvgExample extends React.Component {
  render() {
    return (
      <View
        style={[
          StyleSheet.absoluteFill,
          { alignItems: 'center', justifyContent: 'center' },
        ]}>
        <Svg height="50%" width="50%" viewBox="0 0 100 100">
          <Circle
            cx="50"
            cy="50"
            r="45"
            stroke="blue"
            strokeWidth="2.5"
            fill="green"
          />
          <Rect
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
          />
        </Svg>
      </View>
    );
  }
}

**Comment by stefanosandes** [comment]
Did you try to run `pod install` on the ios folder?

**Comment by mayankgarg056** [comment]
I am facing same issue , and i didn't try to run pod install command in ios folders.

**Comment by saudahmed** [comment]
only use manual install, it fixed it for me. Dont use react-native link

**Comment by mayankgarg056** [comment]
Yes , i always followed the manual linking procedure .

**Comment by msand** [comment]
With the latest react-native you don't need to do any manual linking nor call react-native link. iOS requires that you run pod install, android just works. 

## Try this:

react-native init SomeProject
cd SomeProject
yarn add react-native-svg
cd ios
pod install

## Change App.js to this:
```jsx
import React from 'react';
import { Svg, Rect, Circle } from 'react-native-svg';
export default () => (
  <Svg width="100%" height="100%" viewBox="0 0 100 100">
    <Rect x={0} y={0} width={100} height={100} fill="green" stroke="black" />
    <Circle cx={50} cy={50} r={50} fill="blue" stroke="white" opacity={0.5} />
  </Svg>
);
```

## Then run
react-native run-ios

## Start an android emulator before running this, or start from android studio
react-native run-android

**Comment by mayankgarg056** [comment]
Thanks , it is working fine but i can not click on Text svg component onPress() method , it does not work properly .

This is my code: 

`        <Text
        key={index}
          fill={Colors.blue}
          fontSize="15"
          x={x}
          y={y}
        textAnchor="start"
          strokeWidth="100"
          height={100}
          width={100}
          
          onPress={()=>this.onPressSelectedValue(index)}
         
        >{2}</Text>`

**Comment by msand** [comment]
Can you try with v9.6.2? there was a regression on iOS in 9.6.0 and 9.6.1, no issues on android.

**Comment by msand** [comment]
At least this seems to work fine:

```jsx
import React from 'react';
import { Svg, Text } from 'react-native-svg';
export default () => (
  <Svg width="100%" height="100%" viewBox="0 0 100 100">
    <Text
      x={50}
      y={75}
      fill="black"
      fontSize="50"
      textAnchor="middle"
      onPress={() => alert('press')}
    >
      2
    </Text>
  </Svg>
);

```

**Comment by msand** [comment]
Pressing on the stroked regions seems to work correctly as well:

```jsx
import React from 'react';
import { Svg, Text } from 'react-native-svg';
export default () => (
  <Svg width="100%" height="100%" viewBox="0 0 70 100">
    <Text
      x={35}
      y={95}
      fill="green"
      fontSize="130"
      strokeWidth="5"
      textAnchor="middle"
      stroke="rgba(0, 0, 255, 0.8)"
      onPress={() => alert('press')}
    >
      2
    </Text>
  </Svg>
);


```

**Comment by mayankgarg056** [comment]
Ok I will check it out

**Comment by Princejain21** [comment]
requireNtiveComponent: "RNSVGRect" was not found in the UIManager 
can anyone help to resolve it?
