### ISSUE TITLE
TextInput Support

### ISSUE THREAD

**Issue by Kida007** [react-native-community/react-native-svg#1059]
# Feature Request

Would be awesome to have a TextInput Component 

## Why it is needed

so I wanted to create an awesome SearchBar with Clip Animation (just like whatsapp)

**Comment by msand** [comment]
Perhaps you can use absolute positioning of TextInput, View and Svg components to achieve it?

**Comment by Kida007** [comment]
Thanks for the reply, I'm already doing that . works fine on Android .
but on IOS: all the Touchables on that absolute container aren't responding !

**Comment by Kida007** [comment]
well I managed it using absolute views .

**Comment by rodgomesc** [comment]
this not worked for me, some one can provide a minimal example using textInput?

**Comment by Megablake** [comment]
> 
> 
> this not worked for me, some one can provide a minimal example using textInput?

I started a blank project to try this out. I basically just put the svg element and the TextInput tags at the same level, then attach whatever styles you want to the TextInput. 

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {Svg, Circle, Rect} from 'react-native-svg';
import { TextInput } from 'react-native';

const App: () => React$Node = () => {
  return (
    <>
      <Svg height="50%" width="50%" viewBox="0 0 100 100">
        <Circle
          cx="50"
          cy="50"
          r="45"
          stroke="blue"
          strokeWidth="2.5"
          fill="green"
        />
        <Rect
          x="15"
          y="15"
          width="70"
          height="70"
          stroke="red"
          strokeWidth="2"
          fill="yellow"
        />
      </Svg>
      <TextInput placeholder="Type in me!"></TextInput>
    </>
  );
};

export default App;
`

If you want TextInput on top of svg elements, try either putting the TextInput elements after the Svg elements or absolute positioning and a higher zIndex in style.
