### ISSUE TITLE
Path on Android not rendering on real-device, but renders on the emulator

### ISSUE THREAD

**Issue by dekelev** [react-native-community/react-native-svg#106]
I'm trying to use the Path shape example from the README in my Android app and the emulator shows that it renders correctly, but the same Path shape does not render when the app runs on a real device (OnePlus One) and there's also no errors.

On the other hand, the Polygon example works both on the emulator and the device.

Reproduced with _react-native-svg_ v4.0.0-rc and _react-native_ v0.30.0

**Comment by msand** [comment]
I guess this can be closed.
