### ISSUE TITLE
App crashing with fill property on SVG

### ISSUE THREAD

**Issue by vinicius98s** [react-native-community/react-native-svg#1061]
# Bug

Hello,

When I run the application with `react-native run-android` everything goes well, but when I try to generate an apk for testing as soon as I open some screen with the SVG (that contains the fill property) it crashes.

![image](https://user-images.githubusercontent.com/38966428/62055048-3cfda000-b1f1-11e9-8993-8d4a46540781.png)

I ran it with the `adb logcat` and this is the error message I'm getting:

```
E/AndroidRuntime( 5567): java.lang.IllegalStateException: java.lang.NoSuchFieldException: fill
E/AndroidRuntime( 5567): 	at com.horcrux.svg.t.a(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.j.b(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.j.a(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.t.d(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.x.a(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.x.j(Unknown Source)
E/AndroidRuntime( 5567): 	at com.horcrux.svg.x.onDraw(Unknown Source)
```

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
      Memory: 133.89 MB / 7.70 GB
      Shell: 5.5.1 - /usr/bin/zsh
    Binaries:
      Node: 10.15.2 - /usr/bin/node
      npm: 6.10.1 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 9.5.3

I initially installed the version 9.5.1, and upgraded to try to solve this problem but it didn't

## Steps To Reproduce

1. Generate an apk with `assembleRelease`
2. Open the app
...

Describe what you expected to happen:

1. Run without crashing

## Reproducible sample code

This is the SVG making the app crash (if I remove the fill prop and build my apk it runs normally)

```javascript
<Svg fill="#f09e3e" height="64px" viewBox="-4 0 480 480.00003" width="64px">
    <Path d="m184 288h16v16h-16zm0 0" />
    <Path d="m136 288h16v16h-16zm0 0" />
    <Path d="m88 288h16v16h-16zm0 0" />
    <Path d="m232 288h16v16h-16zm0 0" />
    <Path d="m224 160h16.574219l4.25 56.601562 15.953125-1.203124-4.152344-55.398438h174.75l-22.800781 304h-56.574219v16h64c4.195312.011719 7.683594-3.21875 8-7.398438l23.425781-312.601562h16.574219c4.417969 0 8-3.582031 8-8v-40c0-4.417969-3.582031-8-8-8h-96v-96c0-4.417969-3.582031-8-8-8h-32c-4.417969 0-8 3.582031-8 8v96h-96c-4.417969 0-8 3.582031-8 8v40c0 4.417969 3.582031 8 8 8zm112-144h16v88h-16zm-104 104h224v24h-224zm0 0" />
    <Path d="m40 480h256c22.082031-.027344 39.972656-17.917969 40-40v-32c0-4.417969-3.582031-8-8-8h-.207031c10.941406-14.128906 10.941406-33.871094 0-48h.207031c4.417969 0 8-3.582031 8-8 .011719-31.625-12.503906-61.972656-34.808594-84.390625l-2.917968-44.136719-16 1.054688 1.910156 28.863281c-20.007813-13.929687-43.804688-21.394531-68.183594-21.390625h-96c-66.242188.074219-119.9257812 53.757812-120 120 0 4.417969 3.582031 8 8 8h.207031c-10.941406 14.128906-10.941406 33.871094 0 48h-.207031c-4.417969 0-8 3.582031-8 8v32c.0273438 22.082031 17.917969 39.972656 40 40zm280-40c0 13.253906-10.746094 24-24 24h-256c-13.253906 0-24-10.746094-24-24v-24h304zm-79.398438-40 63.796876-46.398438c10.875 4.042969 17.285156 15.296876 15.21875 26.714844-2.066407 11.414063-12.015626 19.707032-23.617188 19.683594zm-24.800781-1.742188-69.402343-46.257812h133zm-95.800781-158.257812h96c54.3125.0625 99.453125 41.855469 103.695312 96h-303.390624c4.242187-54.144531 49.386718-95.9375 103.695312-96zm-104 136c0-13.253906 10.746094-24 24-24h77.601562l72 48h-149.601562c-13.253906 0-24-10.746094-24-24zm0 0" />
    <Path d="m208 256h16v16h-16zm0 0" />
    <Path d="m160 256h16v16h-16zm0 0" />
    <Path d="m112 256h16v16h-16zm0 0" />
    <Path d="m280.019531 184.566406 15.960938-1.140625 1.144531 16-15.960938 1.140625zm0 0" />
  </Svg>
```

**Comment by fgagneten** [comment]
You have to add:

    -keep public class com.horcrux.svg.** {*;}
in proguard-rules.pro (app)

**Comment by vinicius98s** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

This solved the problem, thank you!

**Comment by quocbaovu15101996** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

save my life

**Comment by huuphudn2017** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

Tks you so much ^^

**Comment by MujtabaFR** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

thanks a lot ..
just to clarify the path.. it's `android/app/proguard-rules.pro`

**Comment by oeduardoal** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

It's work! Tks! 🚀

**Comment by joeybronner** [comment]
Great, it works like a charm 👍

**Comment by BiplovQss** [comment]
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```

thanks. It worked.

**Comment by drb1** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

after adding this crash is gone but i got

Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.

java.io.FileNotFoundException: ......android/app/keep public class com.horcrux.svg.** {* (No such file or directory)

error in release mode.

**Comment by sverano** [comment]
thanks @fgagneten It worked for me.

**Comment by salyndev0** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

It's 2021 you have safe my life.

**Comment by jyotiska** [comment]
It's almost 2022, you still have saved my life.

**Comment by renomi** [comment]
> > > You have to add:
> > > ```
> > > -keep public class com.horcrux.svg.** {*;}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > in proguard-rules.pro (app)
> > 
> > 
> > save my life
> 
> My life also dude :)

It  needs patience and tears— you still have saved my life, thank you dude!

**Comment by navidkhalilian** [comment]
You still have saved my life. Thanks dude!

**Comment by Dalu26** [comment]
This is a lifesaver!!

**Comment by briankim5399** [comment]
> > You have to add:
> > ```
> > -keep public class com.horcrux.svg.** {*;}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in proguard-rules.pro (app)
> 
> This solved the problem, thank you!

Worked for me!!!

**Comment by thespacemanatee** [comment]
It's almost 2023 and this saved my life as well.

**Comment by TaufanP** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

It's mid 2022 and you saved another soul :) thanks a ton!

**Comment by midoalone** [comment]
> 

you saved my entire life, spent dozen of hours trying to get a solution for this, thanks

**Comment by monkeyK1n9** [comment]
please how do you solve this issue in Expo managed workflow?

**Comment by Manil-SoftNEP** [comment]
> > You have to add:
> > ```
> > -keep public class com.horcrux.svg.** {*;}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in proguard-rules.pro (app)
> 
> thanks a lot .. just to clarify the path.. it's `android/app/proguard-rules.pro`

After employing this the app worked fine on actual devices (Galaxy M02 and XIAOMI MI A2). But the crashes persist on the emulator (Pixel 4).

**Comment by Ali-Goher-Shabir** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

Saved my life too. :) 👍

**Comment by isurugg** [comment]
Saved my life too. :)  :*

**Comment by jimgitonga** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

This solved mine 2022 still worked hurray

**Comment by sqlsystems** [comment]
Oh my gosh! Nice! It worked very well!

**Comment by rodrigodiasf1984** [comment]
> 
@drb1 have you managed to solve this error? I've got the same error after adding the --keep public class com.horcrux.svg
![image](https://user-images.githubusercontent.com/30758309/214025148-17c2c0bd-3c2b-4054-b964-13fafbf9a10b.png)
![image](https://user-images.githubusercontent.com/30758309/214025572-b22d3459-f1fc-49f7-966a-a729e8dd6f77.png)

**Comment by raphaelBbs** [comment]
> > 
> 
> @drb1 have you managed to solve this error? I've got the same error after adding the --keep public class com.horcrux.svg ![image](https://user-images.githubusercontent.com/30758309/214025148-17c2c0bd-3c2b-4054-b964-13fafbf9a10b.png) ![image](https://user-images.githubusercontent.com/30758309/214025572-b22d3459-f1fc-49f7-966a-a729e8dd6f77.png)

Have you resolve your problem, I have the same error

**Comment by stephanrotolante** [comment]
Saved my life Feb 2023 🚀

**Comment by twocs** [comment]
@MuhammadAbdullah54321 said
> Suggested solution worked like charm .... had to spend a lot of time on it.
> 
> Just in case if anyone else is still facing same issue and is using some other libraries as well :: I had to to include all these other rules as well to make it work
> 
> -keep class com.swmansion.reanimated.** { _; } 
-keep class com.facebook.hermes.unicode._* { _; } 
-keep class com.facebook.jni._* { _; } 
-keep class com.facebook.react.turbomodule._* { _; } 
-keep public class com.horcrux.svg._* {*;}

This is very interesting, but how did you identify all the libraries that were needed?

**Comment by ducpt-bili** [comment]
Save me. Just curious why in the document not mention this :(

**Comment by bhagwandas** [comment]
My app uses vis.js in WebView.

It was crashing for this reason on one mobile(Samsung M31, Android 12) but on other phones, it worked well.

On adding this in proguard-rules.pro, it stopped crashing in that mobile but it became very slow in drawing vis.js network diagrams. But in other mobiles, it runs pretty smooth.

Any ideas on why this happened?

**Comment by jlag34** [comment]
For anyone using expo, add this to your app.config.js/app.json:

```
  'expo': {
    'plugins': [
      [
        'expo-build-properties',
        {
          'android': {
            'enableProguardInReleaseBuilds': true,
            'extraProguardRules': '-keep public class com.horcrux.svg.** {*;}'
          }
        }
      ]
    ],
  }
  ```

**Comment by IamGideonIdoko** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

One line that saves. Thanks!

**Comment by DevicyKenitou** [comment]
> For anyone using expo, add this to your app.config.js/app.json:
> 
> ```
>   'expo': {
>     'plugins': [
>       [
>         'expo-build-properties',
>         {
>           'android': {
>             'enableProguardInReleaseBuilds': true,
>             'extraProguardRules': '-keep public class com.horcrux.svg.** {*;}'
>           }
>         }
>       ]
>     ],
>   }
> ```

Big thanks to you ! 🤩

**Comment by FarhanKhan1815** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

omg god bless you my friend it really works

**Comment by thachsteven** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

You save my day. Tks a lot

**Comment by React-RN-Pratik** [comment]
> You have to add:
> 
> ```
> -keep public class com.horcrux.svg.** {*;}
> ```
> 
> in proguard-rules.pro (app)

Thanks for the answer it helps me lot.....
