### ISSUE TITLE
Task :react-native-svg:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by ElavanResu** [react-native-community/react-native-svg#1067]
I installed react-native-svg using npm install --save react-native-svg. Then I used manual linking to install it.

Now, when I am using react-native run-android, it's throwing me an error.

> Task :react-native-svg:compileDebugJavaWithJavac FAILED
/Users/shubham/finclusion/oneaccess/oneaccess_frontend/agent_native_app/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/TSpanView.java:1156: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                                                        ^
  symbol:   variable P
  location: class VERSION_CODES
/Users/shubham/finclusion/oneaccess/oneaccess_frontend/agent_native_app/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/TSpanView.java:1157: error: no suitable method found for create(Typeface,int,boolean)
            typeface = Typeface.create(typeface, weight, isItalic);
                               ^
    method Typeface.create(String,int) is not applicable
      (actual and formal argument lists differ in length)
    method Typeface.create(Typeface,int) is not applicable
      (actual and formal argument lists differ in length)
2 errors

react-native: 0.57.1
react-native-svg: 9.6.1

**Comment by ElavanResu** [comment]
I was using react-native-svg-charts. I just updated the package and it resolved my error.

**Comment by bcneves13** [comment]
Hi, i need help with these, im using the latest version of react-native-svg and react-native-svg-uri but still got the error

**Comment by nxhoang** [comment]
> I was using react-native-svg-charts. I just updated the package and it resolved my error.

what package did you update for?

**Comment by abdulghanitech** [comment]
Any update? did the issue got solved?

**Comment by sunzq071** [comment]
I had the same problem. How to solve it?

**Comment by tushgup** [comment]
Still having this problem, any solutions?

**Comment by lfabl** [comment]
Please run this and then test again:
```
yarn remove react-native-svg
```
or
```
npm uninstall react-native-svg
```
