### ISSUE TITLE
Linking Bug

### ISSUE THREAD

**Issue by SethTyemill** [react-native-community/react-native-svg#1070]
There is a bug with linking the library with IOS.

Currently running latest version of react and attempted to follow the automatic installation instructions. As a result I was met with this error message
![image](https://user-images.githubusercontent.com/52678992/62984585-9ddbc980-bde8-11e9-852f-96262a7fbe1d.png)

I have attempted cleaning the build, removing pods and reinstalling, removing node_modules and reinstalling, and relinking the package but came up with nothing. Any help with this issue would be greatly appreciated!

**Comment by Jasonvdb** [comment]
@SethTyemill did you solve your issue? I'm still stuck with the same error.
