### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by franciscocabrera23** [react-native-community/react-native-svg#1071]
Hi, im using react native 0.59.8 and when try to run I get the following error

SpanView.java:1156: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                                                        ^
  symbol:   variable P
  location: class VERSION_CODES
/Users/sensordata/Proyectos/sensordata-app-android/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/TSpanView.java:1157: error: no suitable method found for create(Typeface,int,boolean)
            typeface = Typeface.create(typeface, weight, isItalic);
                               ^
    method Typeface.create(String,int) is not applicable
      (actual and formal argument lists differ in length)
    method Typeface.create(Typeface,int) is not applicable
      (actual and formal argument lists differ in length)
2 errors

FAILURE: Build failed with an exception.

**Comment by msand** [comment]
Can you try setting compileSdkVersion = 28
