### ISSUE TITLE
Can an element overflow the svg container?

### ISSUE THREAD

**Issue by franbe7** [react-native-community/react-native-svg#1082]
Originaly posted [this issue on victory-native](https://github.com/FormidableLabs/victory-native/issues/499) but we figured maybe it was a limitation of `react-native-svg`.
Is there a way we can make it so an element overflows the container? In this example we would want the green circle to render outside the red container:
<p align="center">
<img src="https://user-images.githubusercontent.com/6749415/63869962-698f0e00-c98f-11e9-9b3c-31181c9606d5.png" width="300">
</p>

```js
import React from 'react';
import {SafeAreaView, View} from 'react-native';
import Svg, {Circle, Rect} from 'react-native-svg';
const App = () => {
  return (
    <SafeAreaView>
      <View
        style={{
          alignItems: 'center',
          backgroundColor: 'blue',
          height: '100%',
          justifyContent: 'center',
          width: '100%',
        }}>
        <Svg
          style={{backgroundColor: 'red', overflow: 'visible'}}
          height="50%"
          width="50%"
          viewBox="0 0 100 100">
          <Circle
            cx="50"
            cy="50"
            r="60"
            stroke="green"
            strokeWidth="2.5"
            fill="green"
          />
          <Rect
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
          />
        </Svg>
      </View>
    </SafeAreaView>
  );
};
export default App;
```

**Comment by msand** [comment]
The width and height on the svg root decides the dimensions of the bitmap used by canvas/cgcontext to draw on, if you need more pixels then you need to grow that / make it fullscreen size.

**Comment by SrBrahma** [comment]
> The width and height on the svg root decides the dimensions of the bitmap used by canvas/cgcontext to draw on, if you need more pixels then you need to grow that / make it fullscreen size.

Does making it fullscreen sized impact too much in performance? If not using it, my code needs to wait for the component to render to get its size and then apply it on the svg size.
