### ISSUE TITLE
Path not rendering after upgrade to react-native-svg 9.8.0

### ISSUE THREAD

**Issue by dpyeates** [react-native-community/react-native-svg#1083]
# Bug

Having today updated to 9.8.0, a SVG that has been rendering OK up until now is now not working.

I've narrowed it down to this part of the SVG. if I remove this, the remainder of the SVG renders OK:

`          <Path
            d="M469.61 246.97h-147.4l-39.5 97.88-35.15-99.8-35.17 99.8-39.25-97.88H25.26"
            fill="none"
            stroke="#fff"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-miterlimit="10"
            stroke-width="4"
          />`

The 'Red box' error says:
` Exception thrown while executing UI block: -[__NSCFString characterAtIndex:] Range index out of bounds` 

The console output is:

`2019-08-30 19:01:40.953 [error][tid:main][RCTUIManager.m:1133] Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #3: Error setting property 'd' of RNSVGPath with tag #3: Error setting property 'd' of RNSVGPath with tag #3: Error setting property 'd' of RNSVGPath with tag #3: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Error setting property 'd' of RNSVGPath with tag #13: Exception thrown while executing UI block: 'parentNode' is a required parameter`

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 106.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 22.0.1, 23.0.1, 23.0.3, 24.0.0, 25.0.0, 26.0.2, 27.0.0, 27.0.3, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 11.2.2725575
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-native: ^0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

Library version: 9.8.0

**Comment by eahrold** [comment]
I'm seeing a similar issue on android

```
08-30 13:32:08.633  7241  7241 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' of a view managed by: RNSVGPath
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	... 21 more
08-30 13:32:08.633  7241  7241 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=106; index=106
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at java.lang.String.charAt(Native Method)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathParser.skip_digits(PathParser.java:573)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathParser.parse_number(PathParser.java:533)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:497)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathParser.parse(PathParser.java:152)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathParser.parseData(PathParser.java:13)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.PathView.setD(PathView.java:31)
08-30 13:32:08.633  7241  7241 E AndroidRuntime: 	at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:395)
```

**Comment by msand** [comment]
Can you try with v9.8.1?

**Comment by dpyeates** [comment]
> Can you try with v9.8.1?

Resolved. The above Path in the initial post nows renders correctly.
Thank you!

**Comment by eahrold** [comment]
Resolved on Android too. Thanks.

**Comment by msqar** [comment]
Guys, i'm currently using SVG 9.8.1 but... not using react-native-svg, i'm using react-native-svg-uri, and all of a sudden i started to get these errors after upgrading everything to latest versions on both Android/iOS. 

iOS:
Exception thrown while executing UI block: -[__NSCFString characterAtIndex:] Range index out of bounds 

Android: 
error while updating property d of a view managed by RNSVGPath

Problem is, i'm using quite a few SVGs in my app, so I don't know what might be causing this. I'm using SVGs from assets folder, and some others directly like '<svg>..... </svg' for Android.

What can I do to fix this? As i said, i'm currently using v9.8.1, RN 0.60.5, React 16.8.6

**Comment by eahrold** [comment]
Yeah, it looks like there could be a condition where ‘[self skip_spaces]’ pushes the index out of range since ‘i’ Is mutated inside that call and may need a check after that method is run.

https://github.com/react-native-community/react-native-svg/blob/72ef550ebfbb1ee376c074099065d1fd35e3ab07/ios/Utils/RNSVGPathParser.m#L48-L51

https://github.com/react-native-community/react-native-svg/blob/72ef550ebfbb1ee376c074099065d1fd35e3ab07/android/src/main/java/com/horcrux/svg/PathParser.java#L40-L43

**Comment by msqar** [comment]
@eahrold oh :( any idea on how can i solve this? you recommend debugging? im testing on real devices, i guess i can debug on XCode, put a breakpoint somewhere and look. Although i don't completely understand the explanation since i don't know anything about ObjectiveC.

**Comment by msqar** [comment]
Nice @eahrold ! Thanks i will give it a try. Is this 9.8.2?

**Comment by msand** [comment]
Can you try v9.8.4?

**Comment by msqar** [comment]
@msand hey msand, yes, i will try with 9.8.4. Read that some people already fixed it by using this version. Because i had to go back to 9.7.1, i will try that again after i finish some chat features. Thanks!

**Comment by msand** [comment]
Please try with the latest version. And reopen if you're still having issues.
