### ISSUE TITLE
react-native-svg/index has no exported member 'SvgUri'

### ISSUE THREAD

**Issue by tkulpa** [react-native-community/react-native-svg#1089]
# Question
![image](https://user-images.githubusercontent.com/18174866/64345561-e30ea800-cff0-11e9-8519-8e7ea2a5e423.png)

version: ^9.8.4

**Comment by msand** [comment]
Is this a web or native project?

**Comment by RageOfJustice** [comment]
I have the same for RN (0.60.5) with this
![image](https://user-images.githubusercontent.com/18666217/64363956-8e802280-d01a-11e9-80b4-c0191b65a55c.png)

**Comment by tkulpa** [comment]
Mobile

> Is this a web or native project?

mobile

**Comment by msand** [comment]
Does that mean react-native or plain mobile web react using dom / react-dom / react-native-web?

**Comment by RageOfJustice** [comment]
Just no definitions for all export elements for `xml.js` file
![image](https://user-images.githubusercontent.com/18666217/64417035-02fda480-d0a1-11e9-89cd-0c1f199761cc.png)

**Comment by msand** [comment]
Ahaa, would you mind making a pr?

**Comment by RageOfJustice** [comment]
Of course. But not right now. Maybe tomorrow if I dont forget

**Comment by RageOfJustice** [comment]
Added PR
https://github.com/react-native-community/react-native-svg/pull/1092

**Comment by msand** [comment]
I've corrected quite a few of the types, and migrated everything internally to typescript now as well.
There's still one use of any left:
https://github.com/react-native-community/react-native-svg/blob/467dd22d3e7132fa30a6f96f15ae341484fc4a97/src/lib/extract/extractResponder.ts#L7-L35

And I'm using unknown in two places:
https://github.com/react-native-community/react-native-svg/blob/467dd22d3e7132fa30a6f96f15ae341484fc4a97/src/elements/Shape.tsx#L6-L26

https://github.com/react-native-community/react-native-svg/blob/467dd22d3e7132fa30a6f96f15ae341484fc4a97/src/lib/util.ts#L1-L12

Any help with removing these / making the types stricter would be greatly appreciated!

**Comment by msand** [comment]
Closing as there exists types now, reopen if you find any issues.

**Comment by Sileo1024** [comment]
@msand I'm having the same issue with `Color`
