### ISSUE TITLE
Issues with 9.8.6 and 9.9.0 packages

### ISSUE THREAD

**Issue by MrAusnadian** [react-native-community/react-native-svg#1095]
9.8.5 contents on left, 9.8.6 contents on right:

![image](https://user-images.githubusercontent.com/9650258/64554973-42223480-d2f1-11e9-8400-6f982524f8d0.png)

**Comment by msand** [comment]
Can you try with v9.9.2?

**Comment by MrAusnadian** [comment]
Seems good now, thanks!
