### ISSUE TITLE
Web imports not working after upgrade to 9.9.3

### ISSUE THREAD

**Issue by marnusw** [react-native-community/react-native-svg#1096]
# Bug

Everything worked fine with `9.7.0`. After upgrading to `9.9.3` our web Storybook stopped working. All imports from `react-native-svg` were undefined.

I'm not sure exactly what changed to cause this problem but it seems related to the native components now being exposed/exported. The main fields in `package.json` are currently:

```json
  "main": "lib/commonjs/index.js",
  "module": "lib/module/index.js",
  "react-native": "src/index.ts",
  "types": "src/index.d.ts",
```

We were able to get it working again by changing the `module` entry point to `"lib/module/index.web.js"`. This should be fine for React Native since it has its own entry point.

My guess is that the Webpack `resolve.extensions` are not taken into account because `lib/module/index.js` specifies the explicit extension. I'm not sure that quite explains why it worked before, though.

If this sounds plausible I could make a PR if it'll help. If you think further investigation is required I'll make a minimal reproduction.

## Environment info

React native info output: N/A since it applies to web

Storybook v5 Webpack config with some customization. Importantly it includes:

```js
config.resolve.extensions = ['.web.js', '.js', '.web.jsx', '.jsx', '.web.ts', '.ts', '.web.tsx', '.tsx', '.json']
```

Library version: 9.9.3

**Comment by msand** [comment]
I recently took react-native-bob into use, and it's very likely that your hypothesis is correct. A pr would be greatly appreciated!

**Comment by msand** [comment]
Previously there were no build outputs, only the source files, and thus no module/react-native set in package.json

**Comment by msand** [comment]
Not sure how your suggested fix would interact with haul / webpack in a react-native (not web) project though

**Comment by marnusw** [comment]
> Not sure how your suggested fix would interact with haul / webpack in a react-native (not web) project though

Good point. I did not consider Haul.

I've looked at how the Expo team is handling this in their libraries. `expo-linear-gradient` seems to be the most relevant since it also has two entirely distinct implementations for native and web. In their build output they have:

```
index.js
NativeLinearGradient.android.js
NativeLinearGradient.ios.js
NativeLinearGradient.web.js
```

The `package.json` main field points to `index.js` and it contains simply:

```js
export { default as LinearGradient } from "./LinearGradient";
```

Perhaps we could have:

```
ReactNativeSvg.js  // The current index.js with native exports
ReactNativeSvg.web.js  // The current index.web.js with the web implementation
index.js // export * from './ReactNativeSvg'
```
