### ISSUE TITLE
Low quality of mask, iOS

### ISSUE THREAD

**Issue by zmnv** [react-native-community/react-native-svg#1098]
Hello. I just tryed to apply circle stroke mask.

Android 8 draws it perfectly like something vector.
But iOS draws it low quality:

![image](https://user-images.githubusercontent.com/25253501/64632493-d380cc00-d401-11e9-99ad-f7588961144d.png)
(Screenshot from iOS)

```jsx
import { Svg, Defs, Rect, Circle, LinearGradient, Stop, G, Mask, Use } from 'react-native-svg';

const STOP_COLOR = 'red';

class Keck extends PureComponent {
    render() {
        const { rotation } = this.props;
        const innerDefs = [
            // bottom left rectangle
            { x: 0, y: 60, start: 0.9, end: 1 },
            // top left rectangle
            { x: 0, y: 0, start: 0.9, end: 0.75 },
            // top right rectangle
            { x: 60, y: 0, start: 0.75, end: 0.3 },
            // bottom right rectangle
            { x: 60, y: 60, start: 0, end: 0.5 },
        ];
        return (
            <Svg height="120" width="120" fill="transparent">
                <Defs>
                    <Mask id="mask"
                        x="0"
                        y="0"
                        width={120}
                        height={120}
                        maskUnits="userSpaceOnUse"
                    >
                        <Circle
                            r={42}
                            cx={60}
                            cy={60}
                            stroke="white"
                            strokeWidth={6}
                            strokeDasharray="1 4.5"
                        />
                    </Mask>
                </Defs>
                <G mask="url(#mask)">
                    <G rotation={rotation} origin="60, 60">
                        <OpticalGradient definitions={innerDefs} />
                    </G>
                </G>
            </Svg>
        );
    }
}
```

Why does it happens? Looks like something about 1x, 2x, 3x dpi.. but I don't get it where props about resolution...

PS: I don't show you `<OpticalGradient ... />` because it's simple gradients rectangles which works fine. But mask of dotted circle is very ugly on iOS. If I use <Circle ... /> without mask -- it renders well, but I need to rotate gradient only inside Circle strokes.

**Comment by msand** [comment]
Interesting, not sure why that would happen, would need to debug the masking logic. Not sure when I'll have time to look at this atm.

**Comment by zmnv** [comment]
> Interesting, not sure why that would happen, would need to debug the masking logic. Not sure when I'll have time to look at this atm.

it's looks good on iOS then I add to parent scale=0.5:

```
<Svg height={CONTAINER_SIZE} width={CONTAINER_SIZE} fill="transparent" transform={[{scale: 0.5}]}>
...
</Svg>
```

But it is complicate....

**Comment by zmnv** [comment]
Maybe I can do gradient line-dots-strokes  without masks?

**Comment by zmnv** [comment]
Just change stroke to fill and get the same result....

![image](https://user-images.githubusercontent.com/25253501/64639326-501aa700-d410-11e9-889d-5594762d2763.png)

**Comment by msand** [comment]
You might want to set breakpoints in xcode and step through these two places:
https://github.com/react-native-community/react-native-svg/blob/467dd22d3e7132fa30a6f96f15ae341484fc4a97/ios/RNSVGNode.m#L296-L299

https://github.com/react-native-community/react-native-svg/blob/467dd22d3e7132fa30a6f96f15ae341484fc4a97/ios/RNSVGRenderable.m#L192-L222

**Comment by msand** [comment]
Also, could you try the https://github.com/react-native-community/react-native-svg/tree/filters_rebase branch? It has an alternative implementation for this.

**Comment by msand** [comment]
filters_rebase branch:
https://github.com/react-native-community/react-native-svg/blob/257c7082c28ae5c8f7072f2be528ec7cb2ab8c01/ios/RNSVGRenderable.m#L240-L263

**Comment by zmnv** [comment]
@msand okay, my steps:

0. Width and height of <Svg /> and <Mask /> is 193.

1. Update rnsvg to 9.9.3 (was 9.5.x or something that)

2. Launch iPhone 5s emulator from XCode.

3. Breakpoint at **line 296** of `RNSVGNode.m` but It doesn't worked, because `if (self.clipPath)` above is false.

4. Breakpoint at line 195 of `RNSVGRenderable` stopped with:
<a href="https://user-images.githubusercontent.com/25253501/64654630-7ea97980-d432-11e9-881e-743384be7164.png"><img src="https://user-images.githubusercontent.com/25253501/64654630-7ea97980-d432-11e9-881e-743384be7164.png" height="128" /></a>

next steps I see values like 193...

It's my first time to do this in XCode and I can't understand what I should see.
What is going to happen? Number 193 should be 193*2? Or 193/2? I don't get it, sorry. Not so smart for this.

I prepared to you my component file, you can try with it:
https://gist.github.com/zmnv/85c8ac3ab6ea13555c40d06e70795505

**Comment by zmnv** [comment]
@msand 

I installed `filters_rebase` branch into new clean project.
But the result as the same.

**package.json**
```
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-svg": "github:react-native-community/react-native-svg#filters_rebase"
  },
```

source - https://gist.github.com/zmnv/85c8ac3ab6ea13555c40d06e70795505

![image](https://user-images.githubusercontent.com/25253501/64924824-5387a700-d7f1-11e9-8689-247a58cd2863.png)

This version is more stranger.... It just Duke Nukem or first Doom...
You can try simple test project – https://gitlab.com/zmnv/rnsvg-ios-test

index.js -> SvgMask/SvgMask.js

https://gitlab.com/zmnv/rnsvg-ios-test/blob/svg/SvgMask/SvgMask.js

**Comment by zmnv** [comment]
I can't use `style={{transform: [{scale: TRANSFORM_RESOLUTION}]}}` because it will drop fps with animation.

**Comment by msand** [comment]
Looking closer I realize the bitmap used has a low resolution, add a viewBox attribute to ensure a large enough bitmap for the mask, and use percentages in the width and height attributes of the Svg root instead like this:

```jsx
import React, {PureComponent} from 'react';
import {View, StyleSheet} from 'react-native';
import {
  Svg,
  Defs,
  Rect,
  Circle,
  LinearGradient,
  Stop,
  G,
  Mask,
  Use,
} from 'react-native-svg';

const STOP_COLOR = 'red'; // Gradient color
const CONTAINER_SIZE = 1000;
const ELEMENT_SIZE = CONTAINER_SIZE / 2;

const OpticalGradient = props => {
  return props.definitions.map(({x, y, start, end}) => [
    <Defs key="gradient">
      <LinearGradient id={`gradient-${x}-${y}`} gradientUnits="userSpaceOnUse">
        <Stop offset="0%" stopColor={STOP_COLOR} stopOpacity={start} />
        <Stop offset="100%" stopColor={STOP_COLOR} stopOpacity={end} />
      </LinearGradient>
    </Defs>,
    <Rect
      key="rectangle"
      x={x}
      y={y}
      width={ELEMENT_SIZE}
      height={ELEMENT_SIZE}
      fill={`url(#gradient-${x}-${y})`}
    />,
  ]);
};

class MaskedCircleWithDashes extends PureComponent {
  render() {
    const {rotation = 180} = this.props;
    const innerDefs = [
      // bottom left rectangle
      {x: 0, y: ELEMENT_SIZE, start: 0.9, end: 1},
      // top left rectangle
      {x: 0, y: 0, start: 0.9, end: 0.5},
      // top right rectangle
      {x: ELEMENT_SIZE, y: 0, start: 0.75, end: 0.5},
      // bottom right rectangle
      {x: ELEMENT_SIZE, y: ELEMENT_SIZE, start: 0, end: 0.5},
    ];
    return (
      <Svg
        width="100%"
        height="100%"
        fill="transparent"
        viewBox={`0 0 ${CONTAINER_SIZE} ${CONTAINER_SIZE}`}>
        <Defs>
          <Mask
            id="mask"
            x="0"
            y="0"
            width={CONTAINER_SIZE}
            height={CONTAINER_SIZE}
            maskUnits="userSpaceOnUse"
            maskContentUnits="userSpaceOnUse">
            <Circle
              r={ELEMENT_SIZE - 16}
              cx={ELEMENT_SIZE}
              cy={ELEMENT_SIZE}
              stroke="white" // Mask color
              strokeWidth="4%"
              strokeDasharray="1% 4%"
            />
          </Mask>
        </Defs>
        <G mask="url(#mask)">
          <G rotation={rotation} origin={`${ELEMENT_SIZE}, ${ELEMENT_SIZE}`}>
            <OpticalGradient definitions={innerDefs} />
          </G>
        </G>
      </Svg>
    );
  }
}

export default () => (
  <View style={styles.container}>
    <MaskedCircleWithDashes />
  </View>
);

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
});

```

**Comment by daxaxelrod** [comment]
Facing this issue as well
Without mask
<img width="401" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/10982992/30192c15-864c-4b84-99e5-efe9f5ff4225">

With mask
<img width="414" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/10982992/6e15d278-237b-42e4-9e38-f248e554bf4f">
