### ISSUE TITLE
change import _ from 'lodash' to import {xxx} from 'lodash'

### ISSUE THREAD

**Issue by scarcoco** [react-native-community/react-native-svg#1101]
please change

```
import _ from 'lodash'
```

to 

```
import { xxx } from 'lodash'

or 

improt xxx from 'lodash/xxx'
```

because when config with [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports), and with options `preventFullImport = true` some build failed.

**Comment by msand** [comment]
We're not depending on lodash, in fact, we have no dependencies at all.
