### ISSUE TITLE
Error in reading the following URI that works in a browser

### ISSUE THREAD

**Issue by LucasBrazi06** [react-native-community/react-native-svg#1103]
# Bug
The code below does not work but the SVG shows up correctly in a browser:

`<SvgUri width="50" height="50" source={{uri:'https://slf.evse.cfapps.eu10.hana.ondemand.com/assets/img/connectors/type1-ccs.svg'}} />`

![image](https://user-images.githubusercontent.com/25266945/64815694-72462d80-d5a6-11e9-982f-31c1260b9597.png)

## Environment info

```bash
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 309.59 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1. Copy the code above and run it

Describe what you expected to happen:

1. The SVG icon should be displayed like in a browser

## Reproducible sample code

Already provided above

**Comment by prashantchothani** [comment]
We are facing several issues like this as well.

**Comment by msand** [comment]
Seems you're using SvgUri from some other library, we're not using any dependencies, and your stacktrace is inside domparser / sax.js
