### ISSUE TITLE
react-native-web compatibility broke in 9.8.6

### ISSUE THREAD

**Issue by bananer** [react-native-community/react-native-svg#1106]
# Bug

Apologies if this turns out to be just me using it wrong, my project setup grew quite complicated over time...

I'm using react-native-svg in a project with react-native and react-native-web. When upgrading from 9.8.5 to 9.8.6 (or later) the web build starts breaking with the following error:

```Failed to compile.

./node_modules/react-native-svg/lib/module/elements/Image.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.
```

It seems to me like the web compatibility layer is not used anymore, since it should not be loading that file for web at all. I tried looking at [the diff for these versions](https://github.com/react-native-community/react-native-svg/compare/v9.8.5...v9.8.6) but it's quite large and all I can tell ist that the relevant files `index.js` and `index.web.js` were moved and renamed to `.ts`. I have WebpackResolve extensions set up like this: `'.web.tsx', '.web.ts', '.web.js', '.ts','.tsx', '.js'`, which should still cover the changed extension from my point of view.

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 7.54 GB / 23.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

Library version: 9.8.6, also applies for 9.9.3

Versions of other packages:
```
react@16.8.6
react-native@0.60.5
react-native-web@0.11.7
```

## Steps To Reproduce

Sorry I can't provide more detailed steps right now. If you can point me to the currently recommended way of setting up a project that builds for native and web from the same codebase I can attempt to reproduce the issue with a fresh project.

Any hints towards what might be the problem for me are highly appreciated.

**Comment by adrian1388** [comment]
Similar issue... 

```(bash)
./node_modules/react-native-svg/lib/module/elements/Rect.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.
```

Just added this library in order to use Font Awesome as [here](https://github.com/FortAwesome/react-native-fontawesome#installation) is explained.

My package.json file has:

```(json)
...
    "react-native": "0.60.5",
    "react-native-svg": "^9.9.3",
    "react-native-svg-web": "^1.0.1",
    "react-native-web_improved": "^0.9.9"
...
```

**Comment by bananer** [comment]
9.9.4 fixes the issue for me, thanks a lot!

**Comment by adrian1388** [comment]
I fixed it changing from react-scripts to react-app-rewired and doing some changes in config-overrides.js

**Comment by OKNoah** [comment]
> I fixed it changing from react-scripts to react-app-rewired and doing some changes in config-overrides.js

Share the changes.

**Comment by adrian1388** [comment]
Sorry @OKNoah , my bad. Just this:

(Project Root)/config-overrides.js
```(js)
module.exports = function override(config, env) {
  config.resolve.alias["react-native-svg"] = "react-native-svg-web";
  return config;
};
```

**Comment by liming-developer** [comment]
I have same bug but i didn't use react-native-svg
I am using react-native-video but has same error

Who can help me?

**Comment by RadagastRotN** [comment]
I have the same problem using @react-native-community/slider

**Comment by erickgtzh** [comment]
> I have the same problem using @react-native-community/slider

Did you find how to figure it out?

**Comment by shamoons** [comment]
I'm having the same issue with `react-native-gradient`

**Comment by zamanstar** [comment]
I'm having the same issue with react-native-gradient

**Comment by flyskywhy** [comment]
npm install --save-dev react-app-rewired

Create a `config-overrides.js` in your project root

```
// used by react-app-rewired

const webpack = require('webpack');
const path = require('path');

module.exports = {
  webpack: function (config, env) {
    config.module.rules[1].use[0].options.baseConfig.extends = [
      path.resolve('.eslintrc.js'),
    ];

    const webAliases = {
      'react-native': path.resolve('web/aliases/react-native'),
    };
    Object.assign(config.resolve.alias, webAliases);

    config.plugins.push(
      new webpack.DefinePlugin({
        __DEV__: process.env.NODE_ENV !== 'production',
      }),
    );

    return config;
  },
  paths: function (paths, env) {
    paths.appIndexJs = path.resolve('index.web.js');
    paths.appSrc = path.resolve('.');
    paths.moduleFileExtensions.push('ios.js');
    return paths;
  },
};
```

Also create a `web/aliases/react-native/index.js`
```
// ref to https://levelup.gitconnected.com/react-native-typescript-and-react-native-web-an-arduous-but-rewarding-journey-8f46090ca56b

import {Text as RNText, Image as RNImage} from 'react-native-web';
// Let's export everything from react-native-web
export * from 'react-native-web';

// And let's stub out everything that's missing!
export const ViewPropTypes = {
  style: () => {},
};
RNText.propTypes = {
  style: () => {},
};
RNImage.propTypes = {
  style: () => {},
  source: () => {},
};

export const Text = RNText;
export const Image = RNImage;
// export const ToolbarAndroid = {};
export const requireNativeComponent = () => {};
```

Now you can just run `react-app-rewired start` instead of `react-scripts start`
