### ISSUE TITLE
offsetPath &  offsetDistance not working

### ISSUE THREAD

**Issue by aloptrbl** [react-native-community/react-native-svg#1107]
# offsetPath &  offsetDistance not working
I want to convert from web svg animation to react native svg animation but unfortunately offsetPath & offsetDistance properties can't be access using react native svg package. My idea is from here, Animating objects along SVG Paths https://go.tiny.cloud/blog/guide-svg-animation/, hope I can get a response ASAP.

**Comment by msand** [comment]
We essentially have the required logic available for it, in the TextPath / TSpan implementation. Would you be available to work on this?

**Comment by msand** [comment]
android setup:
https://github.com/react-native-community/react-native-svg/blob/4865c66c204b9307ec42315a2b29fc5915203eac/android/src/main/java/com/horcrux/svg/TSpanView.java#L272-L283

android use:
https://github.com/react-native-community/react-native-svg/blob/4865c66c204b9307ec42315a2b29fc5915203eac/android/src/main/java/com/horcrux/svg/TSpanView.java#L954

ios setup:
https://github.com/react-native-community/react-native-svg/blob/95b0e0f498849515039c5998907c60563e97eff6/ios/Text/RNSVGTSpan.m#L1062-L1084

ios helpers: 
https://github.com/react-native-community/react-native-svg/blob/72a53f373028e4c1d89286c1e6c93c7a229ebc90/ios/Text/RNSVGTextPath.m#L160-L263

ios use:
https://github.com/react-native-community/react-native-svg/blob/95b0e0f498849515039c5998907c60563e97eff6/ios/Text/RNSVGTSpan.m#L963-L993

**Comment by msand** [comment]
@wcandillon You have any good workaround for this atm?

**Comment by wcandillon** [comment]
@msand I do 🙋🏼‍♂️

The SVG path can be normalized into a sequence of Bezier curves and from there, the offset/distance can be computed using Bezier tools. 

@aloptrbl does this video help? https://www.youtube.com/watch?v=uSucm5jjkRI

**Comment by aloptrbl** [comment]
thanks a lot. I refer your code as reference!

**Comment by msand** [comment]
@aloptrbl I've made an initial implementation of getTotalLength, getPointAtLength and isPointInFill now
Could you please help testing and ensuring it's compatible with the web?
#1135

Any other native methods you would have use for? I have getBBox, getCTM and getScreenCTM in the pipeline

**Comment by msand** [comment]
Added getBBox, getCTM and getScreenCTM, and changed signatures: made callbacks to be the last argument, unless there are optional options.
