### ISSUE TITLE
[iOS][crash]EXC_BAD_ACCESS: countByEnumeratingWithState:objects:count: > setSrc: > Attempted to dereference garbage pointer 0x30.

### ISSUE THREAD

**Issue by wenkangzhou** [react-native-community/react-native-svg#1108]
<h1>Environment</h1>
System: 

OS: macOS 10.14.5
CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Memory: 669.12 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman

SDKs:
iOS SDK:
Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
Android SDK:
API Levels: 23, 24, 25, 26, 27, 28
Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3

npmPackages:
react: ^16.8.6 => 16.8.6
react-native: 0.59.9 => 0.59.9

<h1>Platforms</h1>
iOS
<h1>Versions</h1>

iOS: 12.3.1
react-native-svg: 9.5.3
react-native: 0.59.9
react: 16.8.6
<h1>Description</h1>

It crashed when I keep switching pictures multiple times
this is error:
![](https://upload-images.jianshu.io/upload_images/5018455-1dff122118428b38.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![](https://upload-images.jianshu.io/upload_images/5018455-b14100daa40a1b21.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![](https://upload-images.jianshu.io/upload_images/5018455-afdaf047ff7f5f95.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by msand** [comment]
Can you make a full reproduction?

**Comment by msand** [comment]
Closing until a reproduction is available. Reopen when it is, or create a new issue.
