### ISSUE TITLE
Rect does not recognize both rx and ry props

### ISSUE THREAD

**Issue by brittrestine** [react-native-community/react-native-svg#1112]
# Bug
When using `Rect` I am unable to get both `rx` and `ry` props to work as anticipated. As shown in the code below, I am trying to maintain the curve of rx to 20 and would like ry to have no curve at all, therefor I set it to 0. 
## Environment info

Library version: 9.9.3

## Steps To Reproduce

1. Added a `Rect` inside `SVG`
2. Add rx="20" and ry="0" props to `Rect`
...

Describe what you expected to happen:

1. I anticipated that the left side of my rect would be curved 20px and the right side have no curve at all

## Reproducible sample code
```
<Svg width={250} height={50} style={{ alignSelf: 'center' }}>
      <Rect width="100%" height={50} fill={pink} opacity="0.20" rx="20" ry="0" />
      <Rect width={20} height={50} fill={red} rx="20" ry="0" />
      <SVGText
        fontSize="16"
        fontWeight="600"
        x="80%
        y="70%"
        fill={white}
      >
        {20}
      </SVGText>
    </Svg>
```

•As you can see below both sides of the rect are curved
![image](https://user-images.githubusercontent.com/27243969/65350147-a921d200-dbaa-11e9-80c7-ef6f5d682279.png)

**Comment by msand** [comment]
Can you try with https://github.com/react-native-community/react-native-svg/commit/c12d66e77923b9d8e5dc99a2fb81a090f0e38129

**Comment by HilSny** [comment]
Hi @msand we are still seeing this issue in the latest release

```
<Rect width={f.percentify(percentToUse)} height={height} fill={palette[metric]} ry={20} rx={0} />
```

<img width="375" alt="Screen Shot 2019-10-02 at 11 17 39 AM" src="https://user-images.githubusercontent.com/16581033/66062046-43b4d600-e506-11e9-9be3-74dcf4e35ea9.png">
