### ISSUE TITLE
Error while updating property 'focusable' of view managed by: RNSVGSvgView

### ISSUE THREAD

**Issue by inferusvv** [react-native-community/react-native-svg#1117]
# Bug

React Native: 0.61.1
react-native-svg: 9.9.5
react-native-svg-transformer: 0.13.0

I've updated RN to 0.61.1 version and now getting this error.

![photo_2019-09-25 20 21 50](https://user-images.githubusercontent.com/3227120/65624383-6a3cb380-dfd2-11e9-89d0-cfa4f299a139.jpeg)

I use library with `react-native-svg-transformer`. If I go across "Use with xml strings" then everything works.

My `metro.config.js` is the same as in documentation

**Comment by dmeij** [comment]
Same here

**Comment by mavishay** [comment]
Same here

**Comment by msand** [comment]
Can you post a full reproduction?

**Comment by NickRuigrok** [comment]
Yep got the same error, yesterday it was working fine but I reinstalled all my modules today and now I have this error.

**Comment by gavrichards** [comment]
I installed this package because I'm using `react-native-fontawesome` and it said to install it as part of the installation steps there.

So on the home screen of my app I do for example:
```
import {FontAwesomeIcon} from '@fortawesome/react-native-fontawesome';
import {faBars, faComment} from '@fortawesome/free-solid-svg-icons';
```

As of upgrading to React Native 0.61.1, when running the Android simulator, I'm now getting the error shown above. The iOS simulator seems absolutely fine.

**Comment by inferusvv** [comment]
> Can you post a full reproduction?

@msand What you need more? I think you need go across this tutorial: https://github.com/react-native-community/react-native-svg#use-with-svg-files

My icons are from fontawesome website.

I'll try to make fresh project setup and reproduce issue this evening.

**Comment by msand** [comment]
A reproduction means a piece of code I can copy paste, including everything needed to reproduce the issue, essentially the entire App.js, or if that's not sufficient to reproduce it, a complete git repo I can clone, npm install, run the emulator, and see the issue without any extra work on my part.

**Comment by inferusvv** [comment]
@msand Here an example: https://github.com/inferusvv/react-native-svg-issue

See [2nd commit](https://github.com/inferusvv/react-native-svg-issue/commit/71932d2288dab92b3485c8a11696988c19f19b84)

**Comment by gavrichards** [comment]
@msand thanks for the rapid fix and release!

**Comment by anthonytietjen** [comment]
Thank you!! I just hit this as well.

**Comment by haveamission** [comment]
I am getting this same error on version 9.11.1, with React Native version .61.2

**Comment by msand** [comment]
@haveamission Can you make a full reproduction?

**Comment by haveamission** [comment]
I'll try later. I will note that downgrading to 9.9.6 fixed my issue

**Comment by michang05** [comment]
same 9.9.6 fixed my issue, weird the latest missed that
