### ISSUE TITLE
svg cannot be rendered

### ISSUE THREAD

**Issue by klower** [react-native-community/react-native-svg#1120]
`
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      width="51"
      height="20"
      viewBox="0 0 51 20"
    >
      <defs>
        <path
          id="a"
          d="M0.112119368 0.196339921L2.53911462 0.196339921 2.53911462 2.62055336 0.112119368 2.62055336z"
        />
        <path
          id="c"
          d="M0 19.1362281L50.9185613 19.1362281 50.9185613 -0.0000604743083 0 -0.0000604743083z"
        />
      </defs>
      <g
        fill="none"
        fillRule="evenodd"
        stroke="none"
        strokeWidth="1"
        transform="translate(-53 -57) translate(53 57)"
      >
        <g transform="translate(48.38 16.516)">
          <mask id="b" fill="#fff">
            <use xlinkHref="#a" />
          </mask>
          <path
            fill="#FEFEFE"
            d="M1.296 1.328c.19 0 .473.033.473-.244C1.77.873 1.596.85 1.43.85h-.386v.479h.252zm.638.756h-.2l-.386-.626h-.304v.626H.877V.73h.591c.36 0 .481.135.481.36 0 .265-.187.365-.427.37l.412.625zm.412-.678c0-.588-.43-1.051-1.018-1.051C.735.355.304.818.304 1.406c0 .596.43 1.054 1.024 1.054.588 0 1.018-.458 1.018-1.054zm-2.234 0a1.213 1.213 0 112.426.007 1.213 1.213 0 01-2.426-.007z"
            mask="url(#b)"
          />
        </g>
        <mask id="d" fill="#fff">
          <use xlinkHref="#c" />
        </mask>
        <path
          fill="#FEFEFE"
          d="M0 1.32210949L9.24611858 1.32210949 9.24611858 -0.0000604743083 0 -0.0000604743083z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M0 3.8432834L9.24611858 3.8432834 9.24611858 2.52272609 0 2.52272609z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M2.64010672 6.36586838L6.60500395 6.36586838 6.60500395 5.04047312 2.64010672 5.04047312z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M2.64010672 8.87918063L6.60500395 8.87918063 6.60500395 7.56104229 2.64010672 7.56104229z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M2.64010672 11.4009593L6.60500395 11.4009593 6.60500395 10.0834257 2.64010672 10.0834257z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M2.64010672 13.9243506L6.60500395 13.9243506 6.60500395 12.6037933 2.64010672 12.6037933z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M0 16.4469356L9.24611858 16.4469356 9.24611858 15.1279909 0 15.1279909z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M0 18.9662953L9.24611858 18.9662953 9.24611858 17.643319 0 17.643319z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M10.56 2.523h14.248c.12.215.4 1.039.433 1.32H10.56v-1.32z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M13.2067826 6.36586838L17.1626087 6.36586838 17.1626087 5.04047312 13.2067826 5.04047312z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M21.124 5.04h4.224c.013.278-.117 1.06-.222 1.326h-4.002V5.04zM13.207 10.083H23.38c.331.23.94.98 1.186 1.316h-11.36v-1.316z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M13.2067826 13.9243506L17.1626087 13.9243506 17.1626087 12.6037933 13.2067826 12.6037933z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M21.124 12.604h4.019c.088.187.239 1.063.23 1.32h-4.249v-1.32zM10.56 15.128h14.645c-.021.302-.3 1.127-.433 1.319H10.559v-1.319zM10.56 17.643H23.8c-1.173.984-2.207 1.323-4.026 1.323h-9.215v-1.323z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M29.0470601 7.56108261L36.5535344 7.56108261 36.9702024 8.74496798 37.388483 7.56108261 44.8923368 7.56108261 44.8923368 8.87922095 40.9292538 8.87922095 40.9292538 7.81285731 40.554313 8.87922095 33.3844791 8.87922095 33.0077241 7.81285731 33.0077241 8.87922095 29.0470601 8.87922095z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M29.0470198 11.4009593L33.0076838 11.4009593 33.0076838 10.0834257 29.0470198 10.0834257z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M29.0470198 13.9243506L33.0076838 13.9243506 33.0076838 12.6037933 29.0470198 12.6037933z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M26.4057036 16.441896L33.0078854 16.441896 33.0078854 15.1279909 26.4057036 15.1279909z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M26.4057036 18.9662953L33.0078854 18.9662953 33.0078854 17.643319 26.4057036 17.643319z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M40.0802751 0.0000201581028L47.531113 0.0000201581028 47.531113 1.32219012 39.6095834 1.32219012z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M39.1847917 2.52272609L47.5310526 2.52272609 47.5310526 3.8432834 38.7149063 3.8432834z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M38.2898727 5.0405336L44.8924577 5.0405336 44.8924577 6.36592885 37.8209953 6.36592885z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M40.929415 11.4009593L44.892498 11.4009593 44.892498 10.0834257 40.929415 10.0834257z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M40.929415 13.9243506L44.892498 13.9243506 44.892498 12.6037933 40.929415 12.6037933z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M40.929415 16.441896L47.5311937 16.441896 47.5311937 15.1279909 40.929415 15.1279909z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M40.929415 18.9662953L47.5311937 18.9662953 47.5311937 17.643319 40.929415 17.643319z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M33.8027194 10.0834055L40.1343794 10.0834055 39.6796126 11.4009391 34.2641383 11.4009391z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M34.6807055 12.603753L39.2622391 12.603753 38.7963854 13.9243103 35.1431324 13.9243103z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M35.5663719 15.1280514L38.3798383 15.1280514 37.9218462 16.4419565 36.0239609 16.4419565z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M36.4486719 17.6432787L37.4985059 17.6432787 37.0417233 18.9662549 36.905253 18.9662549z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M13.207 8.881H23.38c.331-.228.94-.98 1.186-1.317h-11.36V8.88z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M33.8625688 0.0000201581028L26.4131419 0.0000201581028 26.4131419 1.32219012 34.3324542 1.32219012z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M34.7582739 2.52272609L26.4132225 2.52272609 26.4132225 3.8432834 35.2289656 3.8432834z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M35.652185 5.0405336L29.0522206 5.0405336 29.0522206 6.36592885 36.1238846 6.36592885z"
          mask="url(#d)"
        />
        <path
          fill="#FEFEFE"
          d="M10.56 1.322H23.8C22.626.336 21.592 0 19.773 0h-9.215v1.322z"
          mask="url(#d)"
        />
      </g>
    </svg>`

**Comment by msand** [comment]
You content is invalid in many ways.

This works: 
```html
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 51 20">
  <g stroke="none"> <g transform="translate(48.38 16.516)">  <path fill="#FEFEFE" d="M1.296 1.328c.19 0 .473.033.473-.244C1.77.873 1.596.85 1.43.85h-.386v.479h.252zm.638.756h-.2l-.386-.626h-.304v.626H.877V.73h.591c.36 0 .481.135.481.36 0 .265-.187.365-.427.37l.412.625zm.412-.678c0-.588-.43-1.051-1.018-1.051C.735.355.304.818.304 1.406c0 .596.43 1.054 1.024 1.054.588 0 1.018-.458 1.018-1.054zm-2.234 0a1.213 1.213 0 112.426.007 1.213 1.213 0 01-2.426-.007z"></path> </g>  <path fill="#FEFEFE" d="M0 1.32210949L9.24611858 1.32210949 9.24611858 -0.0000604743083 0 -0.0000604743083z"></path> <path fill="#FEFEFE" d="M0 3.8432834L9.24611858 3.8432834 9.24611858 2.52272609 0 2.52272609z"></path> <path fill="#FEFEFE" d="M2.64010672 6.36586838L6.60500395 6.36586838 6.60500395 5.04047312 2.64010672 5.04047312z"></path> <path fill="#FEFEFE" d="M2.64010672 8.87918063L6.60500395 8.87918063 6.60500395 7.56104229 2.64010672 7.56104229z"></path> <path fill="#FEFEFE" d="M2.64010672 11.4009593L6.60500395 11.4009593 6.60500395 10.0834257 2.64010672 10.0834257z"></path> <path fill="#FEFEFE" d="M2.64010672 13.9243506L6.60500395 13.9243506 6.60500395 12.6037933 2.64010672 12.6037933z"></path> <path fill="#FEFEFE" d="M0 16.4469356L9.24611858 16.4469356 9.24611858 15.1279909 0 15.1279909z"></path> <path fill="#FEFEFE" d="M0 18.9662953L9.24611858 18.9662953 9.24611858 17.643319 0 17.643319z"></path> <path fill="#FEFEFE" d="M10.56 2.523h14.248c.12.215.4 1.039.433 1.32H10.56v-1.32z"></path> <path fill="#FEFEFE" d="M13.2067826 6.36586838L17.1626087 6.36586838 17.1626087 5.04047312 13.2067826 5.04047312z"></path> <path fill="#FEFEFE" d="M21.124 5.04h4.224c.013.278-.117 1.06-.222 1.326h-4.002V5.04zM13.207 10.083H23.38c.331.23.94.98 1.186 1.316h-11.36v-1.316z"></path> <path fill="#FEFEFE" d="M13.2067826 13.9243506L17.1626087 13.9243506 17.1626087 12.6037933 13.2067826 12.6037933z"></path> <path fill="#FEFEFE" d="M21.124 12.604h4.019c.088.187.239 1.063.23 1.32h-4.249v-1.32zM10.56 15.128h14.645c-.021.302-.3 1.127-.433 1.319H10.559v-1.319zM10.56 17.643H23.8c-1.173.984-2.207 1.323-4.026 1.323h-9.215v-1.323z"></path> <path fill="#FEFEFE" d="M29.0470601 7.56108261L36.5535344 7.56108261 36.9702024 8.74496798 37.388483 7.56108261 44.8923368 7.56108261 44.8923368 8.87922095 40.9292538 8.87922095 40.9292538 7.81285731 40.554313 8.87922095 33.3844791 8.87922095 33.0077241 7.81285731 33.0077241 8.87922095 29.0470601 8.87922095z"></path> <path fill="#FEFEFE" d="M29.0470198 11.4009593L33.0076838 11.4009593 33.0076838 10.0834257 29.0470198 10.0834257z"></path> <path fill="#FEFEFE" d="M29.0470198 13.9243506L33.0076838 13.9243506 33.0076838 12.6037933 29.0470198 12.6037933z"></path> <path fill="#FEFEFE" d="M26.4057036 16.441896L33.0078854 16.441896 33.0078854 15.1279909 26.4057036 15.1279909z"></path> <path fill="#FEFEFE" d="M26.4057036 18.9662953L33.0078854 18.9662953 33.0078854 17.643319 26.4057036 17.643319z"></path> <path fill="#FEFEFE" d="M40.0802751 0.0000201581028L47.531113 0.0000201581028 47.531113 1.32219012 39.6095834 1.32219012z"></path> <path fill="#FEFEFE" d="M39.1847917 2.52272609L47.5310526 2.52272609 47.5310526 3.8432834 38.7149063 3.8432834z"></path> <path fill="#FEFEFE" d="M38.2898727 5.0405336L44.8924577 5.0405336 44.8924577 6.36592885 37.8209953 6.36592885z"></path> <path fill="#FEFEFE" d="M40.929415 11.4009593L44.892498 11.4009593 44.892498 10.0834257 40.929415 10.0834257z"></path> <path fill="#FEFEFE" d="M40.929415 13.9243506L44.892498 13.9243506 44.892498 12.6037933 40.929415 12.6037933z"></path> <path fill="#FEFEFE" d="M40.929415 16.441896L47.5311937 16.441896 47.5311937 15.1279909 40.929415 15.1279909z"></path> <path fill="#FEFEFE" d="M40.929415 18.9662953L47.5311937 18.9662953 47.5311937 17.643319 40.929415 17.643319z"></path> <path fill="#FEFEFE" d="M33.8027194 10.0834055L40.1343794 10.0834055 39.6796126 11.4009391 34.2641383 11.4009391z"></path> <path fill="#FEFEFE" d="M34.6807055 12.603753L39.2622391 12.603753 38.7963854 13.9243103 35.1431324 13.9243103z"></path> <path fill="#FEFEFE" d="M35.5663719 15.1280514L38.3798383 15.1280514 37.9218462 16.4419565 36.0239609 16.4419565z"></path> <path fill="#FEFEFE" d="M36.4486719 17.6432787L37.4985059 17.6432787 37.0417233 18.9662549 36.905253 18.9662549z"></path> <path fill="#FEFEFE" d="M13.207 8.881H23.38c.331-.228.94-.98 1.186-1.317h-11.36V8.88z"></path> <path fill="#FEFEFE" d="M33.8625688 0.0000201581028L26.4131419 0.0000201581028 26.4131419 1.32219012 34.3324542 1.32219012z"></path> <path fill="#FEFEFE" d="M34.7582739 2.52272609L26.4132225 2.52272609 26.4132225 3.8432834 35.2289656 3.8432834z"></path> <path fill="#FEFEFE" d="M35.652185 5.0405336L29.0522206 5.0405336 29.0522206 6.36592885 36.1238846 6.36592885z"></path> <path fill="#FEFEFE" d="M10.56 1.322H23.8C22.626.336 21.592 0 19.773 0h-9.215v1.322z"></path> </g> 
</svg>
```

And this:
```jsx
import Svg, { Path } from 'react-native-svg'

const SvgComponent = props => (
  <Svg width="100%" height="100%" viewBox="0 0 51 20" {...props}>
    <Path
      fill="#FEFEFE"
      d="M49.676 17.844c.19 0 .473.033.473-.244.001-.211-.173-.234-.339-.234h-.386v.479h.252zm.638.756h-.2l-.386-.626h-.304v.626h-.167v-1.354h.591c.36 0 .481.135.481.36 0 .265-.187.365-.427.37l.412.625zm.412-.678c0-.588-.43-1.051-1.018-1.051-.593 0-1.024.463-1.024 1.051 0 .596.43 1.054 1.024 1.054.588 0 1.018-.458 1.018-1.054zm-2.234 0a1.213 1.213 0 112.426.007 1.213 1.213 0 01-2.426-.007zM0 1.322h9.246V0H0zM0 3.843h9.246v-1.32H0zM2.64 6.366h3.965V5.04H2.64zM2.64 8.88h3.965V7.56H2.64zM2.64 11.401h3.965v-1.318H2.64zM2.64 13.924h3.965v-1.32H2.64zM0 16.447h9.246v-1.319H0zM0 18.966h9.246v-1.323H0zM10.56 2.523h14.248c.12.215.4 1.039.433 1.32H10.56v-1.32zM13.207 6.366h3.956V5.04h-3.956zM21.124 5.04h4.224c.013.278-.117 1.06-.222 1.326h-4.002V5.04zm-7.917 5.043H23.38c.331.23.94.98 1.186 1.316h-11.36v-1.316zM13.207 13.924h3.956v-1.32h-3.956zM21.124 12.604h4.019c.088.187.239 1.063.23 1.32h-4.249v-1.32zM10.56 15.128h14.645c-.021.302-.3 1.127-.433 1.319H10.559v-1.319zm0 2.515H23.8c-1.173.984-2.207 1.323-4.026 1.323h-9.215v-1.323zM29.047 7.561h7.507l.416 1.184.418-1.184h7.504V8.88H40.93V7.813l-.375 1.066h-7.17l-.376-1.066v1.066h-3.96zM29.047 11.401h3.96v-1.318h-3.96zM29.047 13.924h3.96v-1.32h-3.96zM26.406 16.442h6.602v-1.314h-6.602zM26.406 18.966h6.602v-1.323h-6.602zM40.08 0h7.451v1.322H39.61zM39.185 2.523h8.346v1.32h-8.816zM38.29 5.04h6.602v1.326h-7.071zM40.93 11.401h3.962v-1.318H40.93zM40.93 13.924h3.962v-1.32H40.93zM40.93 16.442h6.601v-1.314H40.93zM40.93 18.966h6.601v-1.323H40.93zM33.803 10.083h6.331l-.454 1.318h-5.416zM34.68 12.604h4.582l-.466 1.32h-3.653zM35.566 15.128h2.814l-.458 1.314h-1.898zM36.449 17.643h1.05l-.457 1.323h-.137zM13.207 8.881H23.38c.331-.228.94-.98 1.186-1.317h-11.36V8.88zM33.863 0h-7.45v1.322h7.92zM34.758 2.523h-8.345v1.32h8.816zM35.652 5.04h-6.6v1.326h7.072zM10.56 1.322H23.8C22.626.336 21.592 0 19.773 0h-9.215v1.322z"
    />
  </Svg>
)
```
