### ISSUE TITLE
Importing SvgUri crashes the App.

### ISSUE THREAD

**Issue by brandtnewww** [react-native-community/react-native-svg#1121]
# Bug

Importing SvgUri described like in the documentation crashes the App:

```
import * as React from 'react';
import { SvgUri } from 'react-native-svg';

export default () => (
  <SvgUri
    width="100%"
    height="100%"
    uri="http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg"
  />
);
```

Error Message:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 995.09 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

Library version:  "react-native-svg": "~9.5.1",

## Steps To Reproduce

1. Create an app with expo SDK 34
2. Import SvgUri

Describe what you expected to happen:

I expect the documented import to work: https://github.com/react-native-community/react-native-svg#use-with-content-loaded-from-uri

**Comment by msand** [comment]
I think the version of react-native-svg included in  expo sdk 34 and earlier doesn't include the SvgUri and related elements. It should be possible to upgrade, as they are purely js components and don't require any changes to the native code.

**Comment by msand** [comment]
Alternatively, you can take the xml.js file from this repo and include it in your project manually.

**Comment by mzschwartz5** [comment]
@brandtnewww Did you ever find a remedy for this? I'm running into the same issue and I'm not seeing anyone else talking about this anywhere.

**Comment by ansmlc** [comment]
> @brandtnewww Did you ever find a remedy for this? I'm running into the same issue and I'm not seeing anyone else talking about this anywhere.

Hi, have you found a solution for this?
