### ISSUE TITLE
error: Build input file cannot be found:

### ISSUE THREAD

**Issue by fabioplaka** [react-native-community/react-native-svg#1123]
Hello,
During the build in react-native on iOS it gives me an error that made me confuse. The error said:
**error: Build input file cannot be found: 'node_modules/react-native-svg/ios/Utils/RNSVGPercentageConverter.m'**
I uninstalled _react-native-svg_ and installed again, and again give me that error.
Please someone help me to solve this.
Thank you in advance!

**Comment by Rizwanilahi** [comment]
Facing the same problem since yesterday.

**Comment by msand** [comment]
Try running pod install

**Comment by fabioplaka** [comment]
I solve it. I uninstalled and installed again, and restarted PC.
Thank you guys :)

**Comment by Ivan-Stashak-CardinalPeak** [comment]
In my case, 'npm install react-native-svg' is not uploading RNSVGPercentageConverter.m and RNSVGPercentageConverter.h, and pod install doesn't help either.

**Comment by msand** [comment]
The file not used / does not exist anymore. Not sure why you'd get any errors. Try removing the dependency and adding it again.

**Comment by Ivan-Stashak-CardinalPeak** [comment]
I can see the file in the v9 branch on github.

**Comment by jdnichollsc** [comment]
I can see the reference of the file here https://github.com/react-native-community/react-native-svg/blob/6bd27dfeba3422482b43b15bef287b72d1bf7d54/ios/RNSVG.xcodeproj/project.pbxproj#L23

**Comment by Rizwanilahi** [comment]
I fixed it.

1. `react-native unlink react-native-svg` 
2. `rm -rf node_modules`
3. `npm install`
4. `react-native link react-native-svg`

**Comment by jdnichollsc** [comment]
I created a new PR to fix this issue => https://github.com/react-native-community/react-native-svg/pull/1128

**Comment by jdnichollsc** [comment]
@fabioplaka can you reopen this issue in the meantime? :)

**Comment by smalbois-panoptio** [comment]
Build works with run-android
Build is fine in xcode.
Build fails with run-ios only - this is what I get.

Tried 9.10.1 and 9.10.2.

Any idea anyone? I have unlinked, resinstalled, etc... 

 ```error: Build input file cannot be found: '/GitHub/mobile/node_modules/react-native-svg/ios/Utils/RNSVGPercentageConverter.m' (in target 'RNSVG' from project 'RNSVG')

 warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.0.99. (in target 'AirMaps' from project 'AirMaps')

 error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening flittermobile.xcodeproj

 2019-10-02 23:51:49.081 xcodebuild[22635:4710280]  DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:49.113 xcodebuild[22635:4710272]  DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:49.331 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:49.340 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.112 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.115 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.126 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.128 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.149 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
 2019-10-02 23:51:50.152 xcodebuild[22635:4710130] [MT] DTDeviceKit: deviceType from 00008006-0004ED2E1153002E was NULL
** BUILD FAILED **


 The following build commands failed:
 	CompileC /GitHub/mobile/ios/build/flittermobile/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGPercentageConverter.o /GitHub/mobile/node_modules/react-native-svg/ios/Utils/RNSVGPercentageConverter.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
 (1 failure)
 . Run CLI with --verbose flag for more details.```

**Comment by msand** [comment]
Have you tried cleaning the build?
Alternatively, you might have a reference to the RNSVGPercentageConverter files which don't exist anymore.

**Comment by smalbois-panoptio** [comment]
I just spotted that this seems to be an issue only if I link the library. If I do link it, I cannot build with run-ios... If I don't link it, I can build with run-ios successfully. Verified on 9.10.2. Anyone else?

**Comment by smalbois-panoptio** [comment]
Cleaned all properly and now can build on with run-ios. Thanks for your help!

**Comment by rhydvik** [comment]
I was able to build it by removing `yarn.lock` and doing `yarn install` again

**Comment by georgiosApo** [comment]
Looking at my Pods-folder, I could see some old dependencies there. Deleting that folder and running pod install solved my issue.

**Comment by umit-turk** [comment]
I was facing same issue and uninstalled the folder, I tried to npx-pod-install then it worked.
