### ISSUE TITLE
Cover react-native-svg with FlowJS

### ISSUE THREAD

**Issue by LouisJS** [react-native-community/react-native-svg#1125]
# Question

Many uses of SVG property are 'uncovered codeflow coverage' by FlowJS.

How can i make my SVGs icon covered by Flow ?

Properties are such as : Path, G, ClipPath, ect.

**Comment by msand** [comment]
@LouisJS  I've published a new version with flow types generated from typescript. Comment or re-open if they're insufficient.

**Comment by mjmasn** [comment]
@msand for some reason Flow is still complaining that the module is untyped:

```
Importing from an untyped module makes it `any` and is not safe! Did you mean to add `// @flow` to the top of `react-native-svg`? (`untyped-import`)Flow(LintError-untyped-import)
```

Looking at the package in node_modules, the right index.js.flow files seem to be in place, but for some reason flow isn't picking them up :thinking:

I'll try to make a simple repro soon.
