### ISSUE TITLE
9.9.7+ LinearGradient regression 

### ISSUE THREAD

**Issue by mjmasn** [react-native-community/react-native-svg#1126]
# Bug

Previously we were using code like:
```
<LinearGradient id="gradient" x1="0" y1="0" x2="0" y2={height}>
  <Stop
    offset={0}
    stopColor="#cccccc"
    stopOpacity={1}
  />
  <Stop
    offset={1}
    stopColor="#333333"
    stopOpacity={1}
  />
</LinearGradient>
```
That now displays a solid colour (the 2nd colour, so `#333333` in this case I think).

## Environment info

React native info output:

```bash
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 1.16 GB / 15.54 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 24, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.1 => 0.61.1 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

```

Library version: 9.9.7

## Steps To Reproduce

1. See code above, reverting to 9.9.6 fixes the issue

Describe what you expected to happen:

1. Linear gradient to be rendered correctly

## Reproducible sample code

See code above

**Comment by msand** [comment]
Can you try making a plan svg version of the same, and verify that browsers render what you expect, you might need to set gradientUnits

**Comment by mjmasn** [comment]
@msand thanks for the quick reply, yeah I'm not sure if that svg is "correct", just that it worked previously. I basically want a 2 colour, top-to-bottom gradient, is there a better way to do that?

Will do some browser testing tomorrow either way :)

**Comment by msand** [comment]
If you set y2 to 100% you'll probably get what you want. Alternatively, setting gradientUnits="userSpaceOnUse" should also work :)

**Comment by mjmasn** [comment]
Thanks @msand, both of those solutions work!

Did a quick browser test and it looks like the new `react-native-svg` behaviour matches the SVG rendering in Google Chrome at least, so I guess this was more a case of a bug/undefined behaviour being fixed than a new bug being created. 

Will close this, thanks again for your help :+1:
