### ISSUE TITLE
Doesn't compile with with RN 0.61

### ISSUE THREAD

**Issue by buraky84** [react-native-community/react-native-svg#1129]
React/RCTImageLoader.h file not found

**Comment by msand** [comment]
Unable to replicate.

**Comment by likern** [comment]
@msand I've updated to React Native 0.61.1 and get this error, related to SVG.
I've found this error in FortAwesome/react-native-fontawesome#29. Not sure, but think this might be relevant to react-native-svg.

![Screenshot_1570038225](https://user-images.githubusercontent.com/842306/66068024-805bee00-e555-11e9-8cb6-c1e561028e96.png)

**Comment by mblenton** [comment]
I am also facing the same problem on iOS

**Comment by msand** [comment]
Can you make a complete reproduction?

**Comment by idoor88** [comment]
I got the same problem:
<img width="795" alt="Screen Shot 2019-10-08 at 3 15 07 PM" src="https://user-images.githubusercontent.com/27703710/66425798-7ebf7980-e9de-11e9-9af9-c85fb3afb151.png">

I have RN 0.61.2 and "react-native-svg": "^9.11.1"
I did fresh pod install with react-native-svg pod, also It was mentioned here that RCTImageLoader.h is removed from RCTImage:
https://github.com/pilot4u/react-native-fs/pull/1/commits/05097bcfd8877a195d1a3734ac1565aa13fea19f

**Comment by Eukki** [comment]
Try this [#1141](https://github.com/react-native-community/react-native-svg/issues/1141#issuecomment-540940897)

**Comment by msand** [comment]
Are you missing the CoreModules pod from your Podfile perhaps?
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
https://github.com/react-native-community/react-native-svg/issues/1141#issuecomment-544129871
Alternatively, can you try the latest commit in the develop branch, it should fix it as well. https://github.com/react-native-community/react-native-svg/commit/3c22c9757277145a18a509c3aee36dddc6a610e7

**Comment by msand** [comment]
So, you're most likely missing React-CoreModules form your Podfile, or 'RCTImage' if you're on RN pre 0.60, closing now.
https://github.com/react-native-community/react-native-svg/issues/1141#issuecomment-544137460
