### ISSUE TITLE
Text can only partially display when mixing Chinese/non-Chinese charaters

### ISSUE THREAD

**Issue by chunghe** [react-native-community/react-native-svg#113]
test version: 4.0.0

code:
```
      <Svg height={svgHeight} width={defaultWidth}>
        <Text y={0}>hello</Text>
        <Text y={10}>哈囉</Text>
        <Text y={20}>hello 哈囉</Text>
        <Text y={30}>hello world</Text>
        <Text y={40}>hello 123</Text>
        <Text y={50}>特斯拉连续13季度亏损 如何收购亏损的SolarCity</Text>
      </Svg>
```

result:
```
hello
哈囉
hello
hello world
hello 123
斯拉连续
```

should be
```
hello
哈囉
hello 哈囉
hello world
hello 123
特斯拉连续13季度亏损 如何收购亏损的SolarCity
```

it doesn't happen in the older version. This only happens on IOS, Android is not affected.

**Comment by magicismight** [comment]
You have to specify a Chinese fontFamily on Text instead of using the default fontFamily.
It cannot automatically fallback to the right fontFamily while mixing Chinses and non-Chinese charaters togethor.

**Comment by tuananhtd** [comment]
@magicismight can you suggest any fontFamily?
