### ISSUE TITLE
9.10.0 Compile Error

### ISSUE THREAD

**Issue by switchtrue** [react-native-community/react-native-svg#1130]
# Bug

In xcode, building a debug release for the simulator with react-native-svg 9.10.0 I am getting the following error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSVGMarkerPosition", referenced from:
      objc-class-ref in libRNSVG.a(RNSVGRenderable.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe this to be new with 9.10.0 as this is where `RNSVGMarkerPosition` was added.

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 535.57 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

Library version: 9.10.0

## Steps To Reproduce

1. Install react-native-svg 9.10.0
2. Clean
3. Build (debug)
...

Describe what you expected to happen:

1. Build successfully

**Comment by JoaoVitorViana** [comment]
I also have the same problem

<img width="1209" alt="Captura de Tela 2019-10-01 às 15 58 46" src="https://user-images.githubusercontent.com/25251463/65995973-81612280-e464-11e9-82a9-9c90ca50f387.png">

`
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 73.57 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3,
 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: android-18 | Google APIs Intel x86 Atom, android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs ARM EABI v7a, android-19 | 
Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3 
    react-native: 0.59.0 => 0.59.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
`

**Comment by msand** [comment]
Can you try relinking or running pod install?

**Comment by mjm918** [comment]
I guess this issue is back in v12.1.0

I tried to unlink and link again. but no luck for me

**Comment by dushantSW** [comment]
I second that! v12.1.0 and XCode 12.5 has brought back the issue

**Comment by hyousi** [comment]
I got the same issue in both v12.1.0 and v12.1.1.

Then I uninstall v12.1.0 and install v12.2.0. Surprisingly, this version works for me.
