### ISSUE TITLE
Gradient color not rendering.

### ISSUE THREAD

**Issue by jmarkstevens** [react-native-community/react-native-svg#1132]
# Bug

Between 9.9.9 and 9.10.0 the gradient color for the following svg no longer renders.

```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1080 1080"><defs><circle id="a" cx="540.2" cy="540" r="537.8"/></defs><linearGradient id="b" gradientUnits="userSpaceOnUse" x1="178.8" y1="178.6" x2="903.4" y2="903.2"><stop offset="0" stop-color="#f89841"/><stop offset="1" stop-color="#f47721"/></linearGradient><use xlink:href="#a" overflow="visible" fill="url(#b)"/><clipPath id="c"><use xlink:href="#a" overflow="visible"/></clipPath><g clip-path="url(#c)"><path d="M887.7 181.6c-289.2-.9-416.2 237.7-468.4 429C354.9 366 202 176.8-76.3 176c-29.9-.1-61.1 2.5-95.1 6.5v9.5h16.3c332.7 1 473.8 457.7 473.1 685.8-.1 33.9 1.2 66.6 1 105.9-.5 157.5-33.1 171-160.8 189.6v8.2c57-2.6 169.8-6.3 233.6-6.1 67.9.2 184.6 3.3 241.7 7.5v-9.5c-164.3-15.5-170.9-56.2-170.5-183.8.1-33.9 1.6-69.2 1.7-103.2.8-272.9 123-694.8 444.8-693.8 12.2 0 24.4.1 38 1.5v-9.5a903.1 903.1 0 0 0-59.8-3z" fill-rule="evenodd" clip-rule="evenodd" fill="#fff"/></g></svg>```

Render in 9.9.9

![Screen Shot 2019-10-02 at 10 33 30 AM](https://user-images.githubusercontent.com/8116777/66067733-0c8ff600-e501-11e9-9c8a-16792140c51c.png)

Render in 9.10.0

![Screen Shot 2019-10-02 at 10 11 42 AM](https://user-images.githubusercontent.com/8116777/66067756-1b76a880-e501-11e9-9205-54d0bd9ba7b5.png)

## Environment info

info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 29.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /var/folders/j0/qwgbt77d4x76z218zk9j_y040000gn/T/yarn--1570038108803-0.8387260480380185/node
    Yarn: 1.19.0 - /var/folders/j0/qwgbt77d4x76z218zk9j_y040000gn/T/yarn--1570038108803-0.8387260480380185/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
✨  Done in 5.80s.

React native info output:

```bash
 // paste it here
```

Library version: 9.9.9 - 9.10.0

## Steps To Reproduce

1. yarn add react-native-svg@9.9.9, cd ios, pod install, cd .., react-native start, run project in xCode
2. yarn add react-native-svg@9.10.0, cd ios, pod install, cd .., react-native start, run project in xCode

Describe what you expected to happen:

1. Gradient colors should render
2.

## Reproducible sample code

[https://github.com/jmarkstevens/pt61](https://github.com/jmarkstevens/pt61)

**Comment by msand** [comment]
This seems to work:
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="0 0 1080 1080">
  <linearGradient id="b" gradientUnits="userSpaceOnUse" x1="178.8" y1="178.6" x2="903.4" y2="903.2">
      <stop offset="0" stop-color="#f89841"/>
      <stop offset="1" stop-color="#f47721"/>
  </linearGradient>
  <circle fill="url(#b)" cx="540.2" cy="540" r="537.8"/>
  <path d="M887.7 181.6c-289.2-.9-416.2 237.7-468.4 429C354.9 366 202 176.8-76.3 176c-29.9-.1-61.1 2.5-95.1 6.5v9.5h16.3c332.7 1 473.8 457.7 473.1 685.8-.1 33.9 1.2 66.6 1 105.9-.5 157.5-33.1 171-160.8 189.6v8.2c57-2.6 169.8-6.3 233.6-6.1 67.9.2 184.6 3.3 241.7 7.5v-9.5c-164.3-15.5-170.9-56.2-170.5-183.8.1-33.9 1.6-69.2 1.7-103.2.8-272.9 123-694.8 444.8-693.8 12.2 0 24.4.1 38 1.5v-9.5a903.1 903.1 0 0 0-59.8-3z" 
  fill-rule="evenodd" clip-rule="evenodd" fill="#fff"/>
</svg>
```

But certainly something buggy with having the clipPath outside any Defs element.

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="0 0 1080 1080">
  <defs>
    <circle id="a" cx="540.2" cy="540" r="537.8"/>
    <clipPath id="c">
        <use xlink:href="#a" overflow="visible"/>
    </clipPath>
  </defs>
  <linearGradient id="b" gradientUnits="userSpaceOnUse" x1="178.8" y1="178.6" x2="903.4" y2="903.2">
    <stop offset="0" stop-color="#f89841"/>
    <stop offset="1" stop-color="#f47721"/>
  </linearGradient>
    <use xlink:href="#a" overflow="visible" fill="url(#b)"/>
    <g clip-path="url(#c)">
        <path d="M887.7 181.6c-289.2-.9-416.2 237.7-468.4 429C354.9 366 202 176.8-76.3 176c-29.9-.1-61.1 2.5-95.1 6.5v9.5h16.3c332.7 1 473.8 457.7 473.1 685.8-.1 33.9 1.2 66.6 1 105.9-.5 157.5-33.1 171-160.8 189.6v8.2c57-2.6 169.8-6.3 233.6-6.1 67.9.2 184.6 3.3 241.7 7.5v-9.5c-164.3-15.5-170.9-56.2-170.5-183.8.1-33.9 1.6-69.2 1.7-103.2.8-272.9 123-694.8 444.8-693.8 12.2 0 24.4.1 38 1.5v-9.5a903.1 903.1 0 0 0-59.8-3z" 
              fill-rule="evenodd" 
              clip-rule="evenodd" 
              fill="#fff"/>
    </g>
</svg>
```

**Comment by jmarkstevens** [comment]
Thanks, that does work. I have made a query as to which app was used to generate the svg for your information. I am sorry I do not have the time to troubleshoot further on this.

**Comment by IljaDaderko** [comment]
I can jump in and help with troubleshooting 👍 I have same issue with gradients. Code below now returns just 1 solid color (whatever the first `<Stop />` is set to).  I am on v `9.11.1` and upgraded from `9.8.4`. Code for this component didn't change. I also upgraded from rn 0.60 to 0.61, perhaps this could've caused the issue?

cc @jmarkstevens did you also update your rn version?

```ts
<Svg height={100} width={100}>
        <Defs>
          <LinearGradient
            id='HeathManaBar-gradient'
            x1="0"
            x2="0"
            y1="0"
            y2={100}
          >
            <Stop
              offset="0"
              stopColor=#EC561B'
              stopOpacity="1"
            />
            <Stop
              offset="0.5"
              stopColor='#8D1B00'
              stopOpacity="1"
            />
            <Stop
              offset="1"
              stopColor='#9F3606'
              stopOpacity="1"
            />
          </LinearGradient>
        </Defs>
          <Path
            x={-20}
            fill="url(#HeathManaBar-gradient)"
            d="...super long path string"
          />
      </Svg>
```

**Comment by msand** [comment]
@IljaDaderko Try setting gradientUnits="userSpaceOnUse" or alternatively y2="100%", I've recently fixed the spec conformance / web compatibility of this.

**Comment by IljaDaderko** [comment]
`gradientUnits="userSpaceOnUse"` did the trick in my case.

**Comment by jmarkstevens** [comment]
@IljaDaderko I did update to 61.1 so am not sure whether the behavior is the same on 60.*

**Comment by msand** [comment]
@IljaDaderko  Also, another option would be to change y2={1}, if you want to use gradientUnits="objectBoundingBox" which is the default unit

**Comment by IljaDaderko** [comment]
@msand Gotcha, well in my case that that value of y can range beyond `0` and `1` so  `userSpaceOnUse` works better for my case.

All in all gradients are no longer an issue for me personally 👍 , I just didn't realise this bit
> I've recently fixed the spec conformance / web compatibility of this.

**Comment by msand** [comment]
@jmarkstevens I have a fix in the develop branch, could you test it out?
yarn add react-native-svg@react-native-community/react-native-svg#2534537

**Comment by jmarkstevens** [comment]
@msand will do shortly

**Comment by jmarkstevens** [comment]
@msand sorry about the delay. Tried again with main branch and same result. Did the yarn add with develop branch and success. Gradient colors showed correctly. Thanks

**Comment by msand** [comment]
I've published a new version now, so I'm closing this. Please comment or reopen if you experience any issues again
