### ISSUE TITLE
LinearGradient opacity is not applied

### ISSUE THREAD

**Issue by kantorm** [react-native-community/react-native-svg#1133]
# Bug

When I'm using `LinearGradient` that should change `stopOpacity` it is not applied

Here is the expected result
<img width="544" alt="Screenshot 2019-10-03 at 15 51 14" src="https://user-images.githubusercontent.com/17920007/66132644-ab961a00-e5f5-11e9-9e05-154f849e4c06.png">

And here is the actual result: 
<img width="544" alt="Screenshot 2019-10-03 at 15 42 32" src="https://user-images.githubusercontent.com/17920007/66132759-dd0ee580-e5f5-11e9-9db8-15f85d7e8fb7.png">

It works on versions before 9.9.7

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 483.49 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - ~/.asdf/shims/node
    Yarn: 1.16.0 - ~/.asdf/shims/yarn
    npm: 6.9.0 - ~/.asdf/shims/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 9.11.0

## Steps To Reproduce
Here is [demo repo](https://github.com/kantorm/SvgFailingGradientOpacity) with reproducible code

## Reproducible sample code

```javascript
      <Svg height={100} width={300}>
        <Defs>
          <LinearGradient id="grad" x1="0" x2="0" y1="0" y2={100}>
            <Stop offset="0%" stopColor="black" stopOpacity={0.5} />
            <Stop offset="90%" stopColor="black" stopOpacity={0} />
          </LinearGradient>
        </Defs>

        <Rect fill="url(#grad)" height={100} width={300} x="0" y="0" />
      </Svg>
```

**Comment by msand** [comment]
Try setting gradientUnits="userSpaceOnUse" on the linearGradient, or alternatively, y2="100%"

**Comment by kantorm** [comment]
@msand it looks that it works. Thanks for the quick response. I'll close the issue.
