### ISSUE TITLE
iOS and Android Svg import is undefined

### ISSUE THREAD

**Issue by CptFabulouso** [react-native-community/react-native-svg#1134]
# Bug

`import Svg from 'react-native-svg'` leads to `Svg` being undefined. I think it's because of [this commit](https://github.com/react-native-community/react-native-svg/commit/2a26a1b3cfaf9cdf695e35bd09cb08da61a35234#diff-f41e9d04a45c83f3b6f6e630f10117fe)

I was firs blaming it on linking, but manual linking gave same result. Also then I discovered name imports like `import { Defs } from 'react-native-svg` are ok. 

## Environment info
react: 16.9.0 => 16.9.0
react-native: 0.61.2 => 0.61.2
react-native-svg: 9.11.1

**Comment by msand** [comment]
Can you make a complete reproduction?

**Comment by CptFabulouso** [comment]
Uh, sorry, missed your comment. Seems like I was the only one with the problem and it does not happen with later versions, closing.
