### ISSUE TITLE
SVG Circle path goes opposite direction on some devices 

### ISSUE THREAD

**Issue by rogerkerse** [react-native-community/react-native-svg#114]
When using <Circle/> and making it look like a round progress bar with those parameters

`strokeDasharray` & `strokeDashoffset`

then on one laptop the path goes clockwise and on another it goes counter clockwise with exactly the same values. What causes this problem?

**Comment by magicismight** [comment]
What svg version did you use in your project?

**Comment by rogerkerse** [comment]
`└── react-native-svg@4.1.1 `

**Comment by msand** [comment]
This is probably an old issue. Closing.
