### ISSUE TITLE
textAlignVertical: center not working

### ISSUE THREAD

**Issue by danipralea** [react-native-community/react-native-svg#1143]
# Bug

I am trying to vertically align the text inside a `Text` component. I tried pretty much everything (```
        textAlignVertical: 'center',
        alignItems:'center',
        alignSelf: 'center',```), but it still doesn't work.
<img width="144" alt="Screenshot 2019-10-12 18 19 54" src="https://user-images.githubusercontent.com/768893/66703775-b3a13880-ed1e-11e9-9366-f2a0f1c3047f.png">

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 225.43 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 0.61.2

## Steps To Reproduce

1. create the componet
2. set its `style`
3. text inside doesn't get vertically aligned

Describe what you expected to happen:

1. text inside to be vertically aligned

## Reproducible sample code

```javascript
// code. pretty much most basic way of doing it
<Text style={styles.Initials}>HO</Text>

// css
Initials: {
        height: 64,
        width: 64,
        borderRadius: 32,
        color: 'white',
        fontWeight: '600',
        fontSize: 18,
        textAlign: 'center',
        textAlignVertical: 'center',
        alignItems:'center',
        alignSelf: 'center',
        backgroundColor: colors.colorPrimary,
        overflow: 'hidden'
    }
```

**Comment by msand** [comment]
How about something like this?
https://snack.expo.io/@msand/centered-text

```jsx
import * as React from 'react';
import { Svg, Rect, Text } from 'react-native-svg';

export default class App extends React.Component {
  render() {
    return (
      <Svg width="100%" height="100%" viewBox="0 0 100 100">
        <Rect x="0" y="0" width="100" height="100" fill="blue" />
        <Text x="50%" y="50%" textAnchor="middle">
          Centered
        </Text>
      </Svg>
    );
  }
}

```

**Comment by danipralea** [comment]
@msand thank you for your reply, but it doesn't work for me. I would rather not add a brand new dependency just for vertically center the text, if possible. do you think this might actually be a bug? or something I'm missing? 🤔

**Comment by msand** [comment]
Hmm, unless you're using react-native-svg, I don't know why you would ask here.

**Comment by danipralea** [comment]
Ah damn. My apologies. I thought it’s the react-native repo
