### ISSUE TITLE
YAxis don't work

### ISSUE THREAD

**Issue by RafaelA977** [react-native-community/react-native-svg#1144]
# Bug

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

Example code with YAxis from https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/horizontal-with-axis.js
...

Describe what you expected to happen:

YAxis works
Problem related with compare scaleBand functions, then always false
<img width="842" alt="Screenshot 2019-10-12 at 21 36 43" src="https://user-images.githubusercontent.com/34536550/66705675-ccb7e280-ed3a-11e9-925e-db9281fe3b0e.png">

## Reproducible sample code
https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/horizontal-with-axis.js

**Comment by msand** [comment]
probably an issue with react-native-svg-charts or the example
