### ISSUE TITLE
Does it support SVG images ? 

### ISSUE THREAD

**Issue by kasback** [react-native-community/react-native-svg#1147]
im trying to import a svg image but iw wouldn't show . 
```

<Image
                    x="50%"
                    y="50%"
                    width="50%"
                    height="90%"
                    preserveAspectRatio="xMidYMid slice"
                    opacity="1"
                    href={require('../assets/images/bell.svg')}
                />
```

**Comment by msand** [comment]
Nope, not at the moment, pull requests are welcome, although I think changing this would require changes to react-native, haven't looked into how the Image component from react-native works internally, but at least making the Image component from react-native-svg support it should be relatively straightforward, using the SvgXml component. Alternatively you can use react-native-svg-transformer instead.

**Comment by msand** [comment]
You can use svg files as components though, check the readme: https://github.com/react-native-community/react-native-svg#use-with-svg-files
