### ISSUE TITLE
react-native-svg Text doesn't work on iOS

### ISSUE THREAD

**Issue by tosygt** [react-native-community/react-native-svg#1148]
# Bug

![Screen Shot 2019-10-15 at 21 59 29](https://user-images.githubusercontent.com/55707321/66861426-b064b180-ef97-11e9-8ad4-80354bfcf264.png)

I'm using pod. I made pod install.  If you look at the bottom of the chart, android works like I wanted and there is a text on it like 'Mat 247' but I got no text in ios. 

## Environment info

****

React native info output:

System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 93.45 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.11.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-link: 4.1.0

Library version: x.x.x

    "react-native-svg": "^9.9.3",
    "react-native-svg-charts": "^5.3.0",

## Steps To Reproduce

1. As you can see in the screenshot, I got a StackedBarChart and got Labels as its child. Labels component got the react-native-svg Text as its child.
2.
...

  ```
import { Text as Text1 } from 'react-native-svg'

.
.
.

const Labels1 = ({ x, y, bandwidth, data }) => {
            return (
                data.map((value, index) => (
                    <View key={index}>

 
                            <View>
                                
                                <Text1
                                    x={x(value.course1) - (x(value.course1) / 2) - 10}
                                    y={y(index) + (bandwidth / 2) - 10}
                                    fontSize={14}
                                    fill={this.state.courses.find(x => x.Id == 0).Selected || this.state.courses.find(x => x.Id == 1).Selected ? 'rgb(255,255,255)' : 'rgb(123,129,148)'}
                                    alignmentBaseline={'middle'}
                                >
                                    Mat
                            </Text1>
                                <Text1
                                    x={x(value.course1) - (x(value.course1) / 2) - 10}
                                    y={y(index) + (bandwidth / 2) + 10}
                                    fontSize={14}
                                    fill={this.state.courses.find(x => x.Id == 0).Selected || this.state.courses.find(x => x.Id == 1).Selected ? 'rgb(255,255,255)' : 'rgb(123,129,148)'}
                                    alignmentBaseline={'middle'}

                                >
                                    {value.course1}
                                </Text1>
                            </View>
.
.
.

```

Describe what you expected to happen:

1. I want it to work like Android and I want a label using react-native-svg Text on my chart.
2.

## Reproducible sample code

You can see my code in screenshot.

**Comment by msand** [comment]
I'm amazed if that would even work in android, how do you get the Text element from react-native-svg to render inside a View element, without wrapping it in a Svg element? 

You shouldn't have any View elements as children of the Svg element, or as parent of the Text element. Only a Svg element and Text / Tspan inside that: 
https://github.com/react-native-community/react-native-svg#text

If you want to group svg elements, you should use the G element.
https://github.com/react-native-community/react-native-svg#g

**Comment by tosygt** [comment]
> I'm amazed if that would even work in android, how do you get the Text element from react-native-svg to render inside a View element, without wrapping it in a Svg element?
> 
> You shouldn't have any View elements as children of the Svg element, or as parent of the Text element. Only a Svg element and Text / Tspan inside that:
> https://github.com/react-native-community/react-native-svg#text
> 
> If you want to group svg elements, you should use the G element.
> https://github.com/react-native-community/react-native-svg#g

Yeah if it didn't work on android I could understand that there is a mistake but how can I see the text without wrapping my react-native-svg Text in a <Svg> or

**Comment by msand** [comment]
Hard to say without a complete reproduction, can you make a snack or a cloneable git repo?

**Comment by mosoakinyemi** [comment]
@tosygt  How were you able to solve this?
