### ISSUE TITLE
Style element

### ISSUE THREAD

**Issue by LuizFBrisighello** [react-native-community/react-native-svg#1149]
# Question
I'm using this [smooth-code](https://www.smooth-code.com/open-source/svgr/playground/) svg to jsx converter to render my svg components. My designer co-worker is sending me the svg files with the **style** element, it looks like this:

`<style>.a{fill:none;}.b{clip-path:url(#a);}.c{clip-path:url(#b);}.d{fill:#fff;}.e{fill:#f8cd2d;}.f{fill:#e2222c;}.g{fill:#14673b;}.h{clip-path:url(#c);}</style>`

[smooth-code](https://www.smooth-code.com/open-source/svgr/playground/) converts them but with this message:

`/* SVGR has dropped some elements not supported by react-native-svg: style */`

And because of that, the svg is fully black when rendered.. I dont know what to say to my co-worker to fix this at his end (He uses Adobe XD), so the workaround I found is to manually add the `fill` prop with the needed color..

Is there a better solution?

**Comment by msand** [comment]
If you enable the svgo option in svgr, then it simplifies away the style element, and resolves them into inline styles instead.

**Comment by msand** [comment]
Also, https://jakearchibald.github.io/svgomg/ can be used for optimizing, or https://github.com/svg/svgo directly

**Comment by LuizFBrisighello** [comment]
> If you enable the svgo option in svgr, then it simplifies away the style element, and resolves them into inline styles instead.

SVGO option at smooth-code converter didnt fully worked, it resolved a couple but not all of them.

I'm exploring https://jakearchibald.github.io/svgomg/ atm but at first glance the result is the same as SVGO option..

I havent tried https://github.com/svg/svgo yet, but I'll get back with a answer in a few hours.

Thanks for the reply @msand !

**Comment by LuizFBrisighello** [comment]
> > If you enable the svgo option in svgr, then it simplifies away the style element, and resolves them into inline styles instead.
> 
> SVGO option at smooth-code converter didnt fully worked, it resolved a couple but not all of them.
> 
> I'm exploring https://jakearchibald.github.io/svgomg/ atm but at first glance the result is the same as SVGO option..
> 
> I havent tried https://github.com/svg/svgo yet, but I'll get back with a answer in a few hours.
> 
> Thanks for the reply @msand !

Just tested https://github.com/svg/svgo. Same result as the others, didnt fully worked.

**Comment by iqqmuT** [comment]
@LuizFBrisighello This would be a great opportunity to test if the pull request fixes this problem:

1. Clone https://github.com/iqqmuT/react-native-svg to TMPDIR and move there
1. Switch to **develop** branch: `git checkout develop`
1. Run `npm install && npm run prepare`
1. Move to your own project directory and install cloned react-native-svg:
`npm install $(npm pack TMPDIR | tail -1)`

You can restore original npm react-native-svg by `npm install react-native-svg@9.11.1`

**Comment by msand** [comment]
There is support for the style element in SvgCss nowadays

**Comment by ajsaule** [comment]
@msand is SvgCss a package that can be imported into a react native project along with 'react-native-svg' ? I can't seem to find information on SvgCss

**Comment by goff-studio** [comment]
does anyone have any approach for XML files? I mean, what should we do if and style element is included in dynamic XMLs

**Comment by myitelekt** [comment]
@goff-studio convert the styles to inline styles. This fixed it for me

**Comment by goff-studio** [comment]
@myitelekt those are dynamic xmls that I receive from the backend. the solution was using SvgCss,
