### ISSUE TITLE
Should expo install cmd for Expo usage

### ISSUE THREAD

**Issue by amandeepmittal** [react-native-community/react-native-svg#1159]
As per [Expo docs](https://docs.expo.io/versions/latest/sdk/svg/), it demands that the library should be installed using `expo install react-native-svg` command.

Currently, the docs state that with Expo, this library is pre-installed. 

Can I submit a PR to amend the docs?

**Comment by msand** [comment]
I guess expo install chooses a compatible version / way of bundling it. A pr would be very welcome!

**Comment by amandeepmittal** [comment]
Thanks @msand 

Yeah, for each SDK version of Expo, I think using their recommended way would install the appropriate version for the library too. I'll submit the PR and refer this issue there. 👍

**Comment by amandeepmittal** [comment]
@msand I added the PR #1161 . Let me know if it the format is acceptable or if any change is required.
