### ISSUE TITLE
Dangerous versioning scheme

### ISSUE THREAD

**Issue by tchayen** [react-native-community/react-native-svg#1164]
Hi!

I'd like to point out a problem with current versioning scheme that I've noticed and learned about it the hard way.

A convention that is getting increasingly common in react-native libraries ecosystem is to avoid submitting native code changes in patch updates, leaving it only for minor and major ones.

This is a convention that Expo follows and, as it turns out, `react-native-svg` is now broken in SDK 35 due to this commit (https://github.com/react-native-community/react-native-svg/commit/c12d66e77923b9d8e5dc99a2fb81a090f0e38129) released in patch [9.9.7](https://github.com/react-native-community/react-native-svg/releases/tag/v9.9.7)

It is not only a problem with Expo, but with any app using CodePush that would also break if it was pinned to a version with `^` or even `~` and somebody would publish an OTA update after `yarn`ing.

**Comment by msand** [comment]
Thanks for pointing this out, haven't noticed or read about this convention anywhere yet, but makes sense in e.g. the expo and codepush use cases for sure. I think minor versions aren't very fitting for this, if it's supposed to communicate that any native code has changes, we should probably stick to major versions, although this will likely make the major version change almost monthly/weekly. Not sure what would be best practise in reality here.

**Comment by msand** [comment]
Then again, if expo allows you to choose react-native-svg version, then they should specify what versions are supported on what sdk, or tell you to build the native bundle yourself. Codepush should have all native dependency versions strictly locked such that you only publish js for the exact version of native deps used. This sounds more like a misconfiguration issue than anything else. The native api isn't promised to stay the same even for patch version changes, only the public api is promised to stay the same / become more spec conformant.

**Comment by msand** [comment]
And, furthermore, the issue in that commit is a change in js, if you put the default props back in the rect jsx component it'll work.

**Comment by tchayen** [comment]
Thanks for fast response, I am really grateful that you took this problem seriously!

Regarding versioning, I agree that from one side it would be preferable to bump major version each time, but as you've said – it would result in rapid growth of that number.

I think that sticking to minor would be a good compromise, but again that wouldn't solve the problem entirely with no exact convention established yet across whole RN community.

I am not sure about the native and public API part you've mentioned. I agree that what you said feels true to semver, but in this case of JavaScript mixed with native code I'd call a change in Java/ObjC a breaking one unless it is tested to be safe no matter if user has newer or the older JS.

I know I can patch it manually in the code, I can as well downgrade the library. It was just a matter of not having to face problems like this in the first place.
