### ISSUE TITLE
Unable to solve module `css-tree` from `../react-native-svg/src/css.tsx`

### ISSUE THREAD

**Issue by dotpegaso** [react-native-community/react-native-svg#1166]
# Bug
Can't run project via Xcode build. I've already removed my `node_modules` and installed it again, the error persist.

## Environment info
System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 49.55 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1
        System Images: android-29 | Google APIs Intel x86 Atom
IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-clean-project: 3.2.4
      react-native-cli: 2.0.1

## React native info output:
```bash
Failed to load bundle with error: (Unable to solve module `css-tree` from `../react-native-svg/src/css.tsx`: Module `css-tree` doest not exist in the Haste module map
```

## Library version: 
```
"react-native": "0.59.9",
"react-native-svg": "^9.13.0"
```

**Comment by murilo-campaner** [comment]
Same problem here...

**Comment by msand** [comment]
Can you try `yarn add css-tree css-select`

**Comment by msand** [comment]
I wonder why it gets imported, it shouldn't attempt to load it unless you use the new SvgCss components, in which case you need css-tree and css-select. Perhaps you have 
```jsx
import * as Svg from 'react-native-svg';
```
or something similar somewhere in your code?

**Comment by dotpegaso** [comment]
@msand I use this lib only to [make react-native-svg-charts](https://github.com/JesperLekland/react-native-svg-charts) work

`yarn add css-tree css-select` solved it for me, thank you!

**Comment by sgrezza** [comment]
Just want to chime in - I was having the same issue and running `yarn add css-tree css-select` fixed it.

**Comment by FullstackJack** [comment]
Why the heck is `npx react-native run-ios` complaining about this? I don't have react-native-svg in this project?! I cleared all the caches and I can't run my project. I should note that this package is used on another project. RN build tools are terrible.
