### ISSUE TITLE
Unable to resolve module ClipPath.tsx

### ISSUE THREAD

**Issue by makarkotlov** [react-native-community/react-native-svg#1168]
There is no extractClipPath.ts in extract folder in v9.13.2. The same in v9.13.0. Works well in v9.12.0

![image](https://user-images.githubusercontent.com/32848434/67465126-43af7e00-f64d-11e9-860c-c66435bcef73.png)
![image](https://user-images.githubusercontent.com/32848434/67465217-65106a00-f64d-11e9-825c-09e8fb11db72.png)

**Comment by lubomyr** [comment]
Same problem

**Comment by msand** [comment]
The file is not needed/used anymore: https://github.com/react-native-community/react-native-svg/search?q=extractClipPath&unscoped_q=extractClipPath

https://github.com/react-native-community/react-native-svg/commit/c3e5dca7755a903671e70c16b0f784c402f7f2f4

**Comment by msand** [comment]
Try either clearing your cache, or deleting node_modules, run yarn and try again.

**Comment by makarkotlov** [comment]
> Try either clearing your cache, or deleting node_modules, run yarn and try again.

Tried already with no luck((

**Comment by msand** [comment]
Did you try this?
```
watchman watch-del-all
rm -fr $TMPDIR/react-*
react-native start --reset-cache
```

**Comment by lubomyr** [comment]
deleting node_modules - not solved problem
but after executing: react-native start --reset-cache
I don't see this error anymore. Thanks

**Comment by makarkotlov** [comment]
> Did you try this?
> 
> ```
> watchman watch-del-all
> rm -fr $TMPDIR/react-*
> react-native start --reset-cache
> ```

react-native start --reset-cache solved the problem. Thank you!
