### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by qyhongfan** [react-native-community/react-native-svg#1169]
# Question

ExceptionsManager.js:126 Unhandled JS Exception: ReferenceError: React is not defined

This error is located at:
    in Svg (at ReportChart.tsx:233)

react-native info:
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 673.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.2.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.3, 26.0.0, 26.0.2, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by qyhongfan** [comment]
@msand   We used typescript

**Comment by bintoll** [comment]
Also have this issue. It is caused with the wrong imports like this:
import React, { Component } from 'react'
should be
import * as React from 'react'
