### ISSUE TITLE
Would love to see stroke-alignment working.

### ISSUE THREAD

**Issue by JBerendes** [react-native-community/react-native-svg#117]
I'm trying to outline a rather small icon but the stroke is on center which is problematic.

Here is a reference to the SVG spec.
https://www.w3.org/TR/svg-strokes/#SpecifyingStrokeAlignment

**Comment by magicismight** [comment]
Thanks for the great suggestion,
this is a very tricky feature.
But I`ll try my best to implement this.

**Comment by dubert** [comment]
👍

Yes, this is definitely very tricky - but it would be incredible to have.

**Comment by carlesnunez** [comment]
Is this implemented?

**Comment by tobq** [comment]
Still unimplemented

**Comment by msand** [comment]
@tobq (and everyone else) Feel free to work on this

**Comment by msageryd** [comment]
It's a really useful feature, but is it really a good idea to put time into this until anyone else implements it (i.e. browsers)?

I'm currently trying to making my react-native-svg drawing library compatible with web-svg so I can draw the same stuff in a browser. It would be really cumbersome if I had made use of a lot of functions in RNSVG which were not available in browsers.

**Comment by harveyconnor** [comment]
So has this been implemented yet?

**Comment by ngima** [comment]
Any update on it?

**Comment by kelvinOfoli** [comment]
Any update?
