### ISSUE TITLE
Is it possible to track touch along a path?

### ISSUE THREAD

**Issue by arun057** [react-native-community/react-native-svg#1172]
# Question

I am trying to reproduce something like what HotelTonight does for confirming a reservation. Whats the best way to confirm a path was followed as a touch / gesture?

**Comment by msand** [comment]
What do you mean? Like implementing a slider? Perhaps check how the built-in slider in react-native is built?

**Comment by arun057** [comment]
More like moving a button around an elliptical path, something along the lines of:

![image](https://i.imgur.com/xmsogSb.png)

**Comment by msand** [comment]
@wcandillon You have any suggestion here? Certainly it's possible to do, not sure how convenient react-native-gesture-handler would be for it though. Might be simplest to implement the math in js with a normal gesture responder.

**Comment by arun057** [comment]
Yeah I have been going down the path of potentially looking at trigonometry to figure out what the arc path of the ellipse would be, but would be interesting to see if someone already made a library of sorts
