### ISSUE TITLE
Rect with Android Expo project causes blank page

### ISSUE THREAD

**Issue by maxwedwards** [react-native-community/react-native-svg#1175]
`Rect` is not working for me in an Expo project on Android.

Works:
```           
<View>
  <Svg height="100" width="100">
    <Circle cx="50" cy="50" r="50" fill="pink" />
  </Svg>
</View>
```

Does not display:

```            
<View>
  <Svg height="100" width="100">
    <Rect x='15' y='15' width='100' height='100' stroke='red' strokeWidth='2' fill='yellow' />
  </Svg>
</View>
```

In fact if I include the `Rect` the navigation header I have in my app doesn't show. I just get a blank page.

## Environment info

Expo SDK Version: 35

Doesn't work using versions: 9.9.2, 9.9.5, 9.13.3

However it does work using version 8.0.11

This has the knock on effect of stopping `react-native-qrcode-svg` from working. See https://github.com/awesomejerry/react-native-qrcode-svg/issues/67

**Comment by jrutley** [comment]
Just wanted to confirm this. The moment I removed the Rect from the "Usage" sample code from https://github.com/react-native-community/react-native-svg, I was able to see the circle.
Expo version is 3.4.1
react-native-svg version is 9.9.9

**Comment by msand** [comment]
Can you try locking react-native-svg to the built in version bundled with expo? https://github.com/react-native-community/react-native-svg/issues/1127#issuecomment-538789743 i.e. version  "9.9.2" exactly

**Comment by msand** [comment]
and verify that there is only one version of rnsvg in use, and that it is that exact version in package.json of the react-native-svg folder.

**Comment by msand** [comment]
@ide @EvanBacon Could you have a look and see why this question keeps coming up when installing react-native-svg to expo? Perhaps the expo docs should be updated?

**Comment by maxwedwards** [comment]
My mistake. Version 9.9.2 does indeed work.

I think I have figured out what is going on. `expo install react-native-svg` adds `~9.9.2` to your package.json. When yarn installs it grabs the latest minor patch being `9.9.9` which doesn't work.

**Comment by JH-32** [comment]
I have same issue, and specifying version of react-native-svg to 9.9.2 in package.json didn't work.

**Comment by msand** [comment]
@JH-32 can you try in a clean / new project?

**Comment by tmartin1** [comment]
Had the same problem here, specifying the `react-native-svg` version to `9.9.2` fixed the issue for me.

**Comment by ni3galave** [comment]
Fixed issue for me too. Thanks :)

**Comment by yannvr** [comment]
Using v9.9.2 didn't work for me, even a clean module install :(

**Comment by oddsson** [comment]
This breaks for me in version 9.9.7, version 9.9.6 works fine.

**Comment by brunopatricio3** [comment]
Like @oddsson referenced, downgrading to version 9.9.6 fixed the problem :)
