### ISSUE TITLE
Android render svg crash app on real device

### ISSUE THREAD

**Issue by vothanhhungit** [react-native-community/react-native-svg#1176]
**Environment**
OS: macOS High Sierra v10.13

**Packages: (installed)**
"react-native-svg": "^9.13.3",
"react-native-svg-transformer": "^0.13.0",
 "react-native": 0.61.3

**Actual Behavior**
I build apk release and running app crash on SVG render (crash on a real device)
Note: when I'm commented SVG then it works fine.
Plz! help me find out the solution to fix this issue! Many Thanks!

**Comment by vothanhhungit** [comment]
@msand 
Just the content of my component :
import React, { Component } from 'react';
```
/* Images */
import SearchIcon from '../../../assets/images/icons/search-icon.svg';
class FilterSearchAreaComponent extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
       <SearchIcon
         width="40"
         height="40"
       />
    )
  }
}

export default (FilterSearchAreaComponent);
```

Here is **search-icon.svg** file:
   https://drive.google.com/file/d/1IqjEZexLba7gkh0clErr9_IZPHlDg7xb/view?usp=sharing

**Comment by msand** [comment]
You fixed the issue?

**Comment by vothanhhungit** [comment]
> You fixed the issue?

Yes, I was mistaken about this:

> Troubleshooting
> Problems with Proguard
> When Proguard is enabled (which it is by default for Android release builds), it causes runtine error To avoid this, add an exception to android/app/proguard-rules.pro:
> 
> -keep public class com.horcrux.svg.** {*;}

**Comment by aliasger-rashid** [comment]
> > You fixed the issue?
> 
> Yes, I was missed about this:
> 
> > Troubleshooting
> > Problems with Proguard
> > When Proguard is enabled (which it is by default for Android release builds), it causes runtine error To avoid this, add an exception to android/app/proguard-rules.pro:
> > -keep public class com.horcrux.svg.** {*;}

This worked for me. Thank you saved my ton of time.

**Comment by CrazyAndy** [comment]
This worked for me too . Save my whole day .Thanks !

**Comment by fkazemi5236** [comment]
> 

how did you do this? can you explain step by step?

**Comment by boodong-rn** [comment]
> > 
> 
> how did you do this? can you explain step by step?

Did you fix it?
You need to input below text in `android/app/proguard-rules.pro`.

`-keep public class com.horcrux.svg.** {*;}`

**Comment by GouravNainwaya** [comment]
> > You fixed the issue?
> 
> Yes, I was missed about this:
> 
> > Troubleshooting
> > Problems with Proguard
> > When Proguard is enabled (which it is by default for Android release builds), it causes runtine error To avoid this, add an exception to android/app/proguard-rules.pro:
> > -keep public class com.horcrux.svg.** {*;}

Thankyou so much bro you save my up coming days
