### ISSUE TITLE
SVGs are rendered completely black

### ISSUE THREAD

**Issue by brandtnewww** [react-native-community/react-native-svg#1177]
# Bug

I receive a few SVGs via a backend and I have to render them within the App. All SVGs I receive from the backend are displayed black.

Here's an example SVG: https://d2c0nxl73e8air.cloudfront.net/public/30/genius_1.svg

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 552.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```

Library version: 9.13.3

## Steps To Reproduce

Render the SvgUri component like this:

<SvgUri
width='100%
height='100%'
uri='https://d2c0nxl73e8air.cloudfront.net/public/30/genius_1.svg'
/>

**Describe what you expected to happen:**

The SVG should be rendered correctly.

Here's the SVG code:
```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 520 520"><defs><style>.cls-1{fill:none;}.cls-2{fill:#ffcb30;}.cls-3,.cls-4,.cls-5{fill:#fff;}.cls-4{stroke:#ffcb30;}.cls-4,.cls-5{stroke-linecap:round;stroke-linejoin:round;stroke-width:6.93px;}.cls-5{stroke:#6a3ed3;}.cls-6,.cls-7{fill:#6a3ed3;}.cls-7{font-size:37.76px;font-family:NeuzeitOffice-Bold, Neuzeit Office;font-weight:700;}.cls-8{fill:#464070;}.cls-9{fill:#ff5656;}.cls-10{fill:#00b4f3;}.cls-11{fill:url(#linear-gradient);}.cls-12{fill:url(#linear-gradient-2);}.cls-13{clip-path:url(#clip-path);}.cls-14{fill:#5f5f9b;}.cls-15{fill:#ffcb02;}.cls-16{fill:#f9b20c;}.cls-17{clip-path:url(#clip-path-2);}.cls-18{clip-path:url(#clip-path-3);}.cls-19{fill:#5f5f99;opacity:0.5;}</style><linearGradient id="linear-gradient" x1="300.7" y1="175.69" x2="222.88" y2="326.81" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#5f5f9b"/><stop offset="1" stop-color="#464070"/></linearGradient><linearGradient id="linear-gradient-2" x1="301.5" y1="188.46" x2="220.17" y2="228.62" gradientUnits="userSpaceOnUse"><stop offset="0.02" stop-color="#00b4f3"/><stop offset="1" stop-color="#009dc8"/></linearGradient><clipPath id="clip-path"><rect class="cls-1" x="200" y="152.9" width="125.61" height="192.73" rx="62.8" ry="62.8"/></clipPath><clipPath id="clip-path-2"><rect class="cls-1" x="259.19" y="295.23" width="19.78" height="27.61" rx="4.72" ry="4.72"/></clipPath><clipPath id="clip-path-3"><rect class="cls-1" x="286.45" y="295.23" width="19.78" height="27.61" rx="4.72" ry="4.72"/></clipPath></defs><title>Genius 1</title><g id="Discipline"><path class="cls-2" d="M485.81,379.78V140.47a19.44,19.44,0,0,0-9.72-16.83L268.84,4a19.43,19.43,0,0,0-19.43,0L42.15,123.64a19.43,19.43,0,0,0-9.71,16.83V379.78a19.42,19.42,0,0,0,9.71,16.83L249.41,516.27a19.43,19.43,0,0,0,19.43,0L476.09,396.61A19.43,19.43,0,0,0,485.81,379.78Z"/><path class="cls-3" d="M450.62,358.73V161.53a20.72,20.72,0,0,0-10.36-17.95L269.48,45a20.73,20.73,0,0,0-20.72,0L78,143.58a20.72,20.72,0,0,0-10.36,17.95v197.2A20.72,20.72,0,0,0,78,376.67l170.78,98.6a20.73,20.73,0,0,0,20.72,0l170.78-98.6A20.72,20.72,0,0,0,450.62,358.73Z"/><line class="cls-4" x1="260.88" y1="94.76" x2="260.88" y2="122.72"/><line class="cls-4" x1="274.85" y1="108.74" x2="246.9" y2="108.74"/><line class="cls-5" x1="382.56" y1="193.18" x2="361.36" y2="189.07"/><circle class="cls-6" cx="374.56" cy="177.7" r="3.46"/><circle class="cls-6" cx="369.49" cy="203.87" r="3.46"/><text class="cls-7" transform="translate(137.43 187.13) rotate(-26.29)">2x</text><path class="cls-8" d="M279.53,381.79a189.31,189.31,0,0,1-37.78-4.13,11.18,11.18,0,0,1-5.45-2.85L220.81,360A11.12,11.12,0,0,1,236.16,344l13.14,12.53c27.45,5.08,61,4.33,72.9-9.28,1.78-2,2.41-3.83,1.88-5.33-1-2.81-6.71-8.28-21.88-11A11.12,11.12,0,1,1,306.1,309c27.83,4.95,36.35,18.09,39,25.48,3.24,9.2,1,19.16-6.09,27.33-7.69,8.82-20.37,15.05-36.66,18A126.16,126.16,0,0,1,279.53,381.79Z"/><path class="cls-9" d="M189.12,211.56l-.38,0a4,4,0,0,1-3.62-4.37c1.72-18.34,11.79-29.1,29.13-31.1a4,4,0,0,1,.93,8c-13.68,1.58-20.69,9.16-22.07,23.87A4,4,0,0,1,189.12,211.56Z"/><path class="cls-9" d="M211.34,181.18a4,4,0,0,1-2.63-1c-3.72-3.23-7.14-3.23-11.44,0a4,4,0,0,1-4.84-6.41c7.31-5.51,15-5.39,21.55.34a4,4,0,0,1-2.64,7.05Z"/><path class="cls-8" d="M172.91,283.71c-15.22,0-31.45-6.78-46.85-20a11.55,11.55,0,0,1,15-17.54c16.11,13.79,31.67,17.86,43.81,11.47,13-6.84,20.29-25.19,18.11-45.64a11.55,11.55,0,0,1,23-2.45c3.23,30.24-8.67,57.14-30.31,68.53A48.39,48.39,0,0,1,172.91,283.71Z"/><circle class="cls-10" cx="133.19" cy="254.16" r="14.88"/><path class="cls-8" d="M351.66,283.71a48.39,48.39,0,0,1-22.74-5.6c-21.64-11.39-33.54-38.29-30.31-68.53a11.55,11.55,0,0,1,23,2.45c-2.18,20.45,5.1,38.8,18.11,45.64,12.14,6.4,27.7,2.32,43.81-11.47a11.55,11.55,0,1,1,15,17.54C383.11,276.93,366.87,283.71,351.66,283.71Z"/><circle class="cls-10" cx="391.38" cy="254.16" r="14.88"/><rect class="cls-11" x="200" y="152.9" width="125.61" height="192.73" rx="62.8" ry="62.8"/><path class="cls-8" d="M248.17,383.63c-14.53,0-27.48-2.31-38.24-6.9-15.83-6.75-26.14-18.15-28.28-31.28-2.52-15.42,7.28-34.14,34.74-38.77a11.12,11.12,0,1,1,3.7,21.93c-11,1.86-17.5,7.07-16.49,13.27,1.8,11.05,24,24.33,65.92,17.75a21.37,21.37,0,0,0,11.94-6.28l8.85-9.14a11.12,11.12,0,1,1,16,15.46l-8.84,9.14A43.71,43.71,0,0,1,273,381.59,159.24,159.24,0,0,1,248.17,383.63Z"/><path class="cls-12" d="M210.08,207.28c0,12.5,6.54,22.63,22.64,22.63,13.74,0,14-15,29.88-15s16.15,15,29.89,15c16.09,0,22.64-10.13,22.64-22.63a22.64,22.64,0,0,0-22.64-22.64H232.72A22.64,22.64,0,0,0,210.08,207.28Z"/><path class="cls-8" d="M250.92,198.26a2,2,0,0,1-1-.25,21.55,21.55,0,0,0-20.86,0,2,2,0,0,1-1.94-3.52,25.54,25.54,0,0,1,24.74,0,2,2,0,0,1-1,3.77Z"/><path class="cls-8" d="M273.18,198.26a2,2,0,0,1-1.76-1,2,2,0,0,1,.79-2.73,25.52,25.52,0,0,1,24.73,0A2,2,0,0,1,295,198a21.57,21.57,0,0,0-20.87,0A2,2,0,0,1,273.18,198.26Z"/><path class="cls-8" d="M246.67,209.41H232.36a2,2,0,1,1,0-4h14.31a2,2,0,1,1,0,4Z"/><path class="cls-8" d="M291.5,209.41H277.19a2,2,0,1,1,0-4H291.5a2,2,0,1,1,0,4Z"/><g class="cls-13"><rect class="cls-9" x="196.39" y="173.35" width="132.83" height="13.77"/><path class="cls-14" d="M220.11,312.09l-3.06-12.69c1.07-.26,83.33-21,120.65-87.16l11.38,6.41c-21.08,37.37-55,60.78-79.78,73.84C242.59,306.58,221,311.87,220.11,312.09Zm-1.53-6.35L217,299.4h0Z"/><path class="cls-14" d="M264.3,290.44a49.81,49.81,0,0,0-7.25-4,167.74,167.74,0,0,1-30.78-19.14c-15.37-12.07-30.55-28.26-45.1-48.13l10.53-7.71c32,43.62,57.49,56.43,71.21,63.32,4.32,2.17,7.44,3.73,9.8,5.72Z"/><rect class="cls-15" x="194.36" y="298.38" width="132.83" height="19.78"/></g><rect class="cls-16" x="259.19" y="295.23" width="19.78" height="27.61" rx="4.72" ry="4.72"/><g class="cls-17"><rect class="cls-15" x="259.19" y="281.42" width="19.78" height="27.61" rx="4.72" ry="4.72"/></g><circle class="cls-16" cx="269.08" cy="305.74" r="1.74"/><rect class="cls-16" x="286.45" y="295.23" width="19.78" height="27.61" rx="4.72" ry="4.72"/><g class="cls-18"><rect class="cls-15" x="286.45" y="281.42" width="19.78" height="27.61" rx="4.72" ry="4.72"/></g><circle class="cls-16" cx="296.34" cy="305.74" r="1.74"/><ellipse class="cls-19" cx="263.6" cy="424.9" rx="47.76" ry="5.46"/></g></svg>```

**Comment by brandtnewww** [comment]
Okay - I just looked into the documentation again and found https://github.com/react-native-community/react-native-svg#css-support

This shortly renders the SVGs but then crashes the App, because of an unrecognized font family is used.

**Comment by avensiafresch** [comment]
I could kiss you, @brandtnewww. 😘

**Comment by yamilelias** [comment]
Sorry for reviving an old closed topic, but I can't find the error with the unrecognized font family. I was already using the `SvgCssUri` component with no success.
