### ISSUE TITLE
requireNativeComponent: "RNSVGLine" was not found in the UIManager.

### ISSUE THREAD

**Issue by sezginriggs** [react-native-community/react-native-svg#1179]
# Bug

When trying to run victory-native on Android I'm getting the following error and app is crashing.

"requireNativeComponent: "RNSVGLine" was not found in the UIManager."

I'm thinking this is related with autolinking on Android. I installed the react-native-svg with `yarn add react-native-svg` and didn't do any linking/configuration.

## Environment info

**Here is my package versions;**
react-native: 0.61.2
react-native-svg: 9.13.3
victory-native: 33.0.0

**React native info output:**

```bash
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 88.74 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.2, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

**Comment by msand** [comment]
Did you rebuild the native bundle?

**Comment by sezginriggs** [comment]
@msand I tried deleting node_modules, yarn install then, also clearing metro caches etc. is there anything else should i try?

**Comment by msand** [comment]
can you try cleaning the build in xcode and android studio, and then run again from there?

**Comment by sezginriggs** [comment]
@msand I forgot to say, it's working fine with iOS.

**Comment by msand** [comment]
I wonder why this would happen. Can you try in a clean project? https://github.com/react-native-community/react-native-svg#unexpected-behavior

**Comment by sezginriggs** [comment]
@msand after upgrading React Native to 0.61.4, it seems problem solved on Android. And working on iOS too.

Thank you very much for your help.

**Comment by AlvaroAquijeDiaz** [comment]
I'm having this issue only on Android development builds, I've tried installing different package versions and even on the latest versions of react-native and expo it still just fails
