### ISSUE TITLE
iOS crash due to CFAutoRelease

### ISSUE THREAD

**Issue by jackw-kounta** [react-native-community/react-native-svg#1181]
# Question

Hi, I'm getting a **Thread 1: EXC_BREAKPOINT** crash when using the library - inside the function `+ (CGGradientRef)RNSVGCGGradient:(id)json { ... }`

The problem code is: 
 - `return (CGGradientRef)CFAutorelease(gradient);`.

I can remedy this by changing it to: 
 - `return (CGGradientRef)gradient;`.

Is there a reason we are still using autorelease? 

Regards,
J

---
React Native: 0.60.5
react-native-svg: 9.13.3

**Comment by msand** [comment]
Can you verify that it's not leaking memory? In that case it should be safe to remove.

**Comment by jackw-kounta** [comment]
@msand 
The root cause of this crash scenario looks like passing in a <Stop> with offset value that is more than 100% (ie 101%) inside a <LinearGradient> component.

As for memory - there seems to be a memory leak with my code with or without the CFAutorelease cast - so I can't confirm it unfortunately.

Possibly the CFAutorelease cast requires something not-null which would lead to the crash
