### ISSUE TITLE
How can add color inside path?

### ISSUE THREAD

**Issue by expouic** [react-native-community/react-native-svg#1182]
How can change the color inside the path of my SVG like image bellow.

<img width="457" alt="Screenshot 2019-11-06 at 10 50 17" src="https://user-images.githubusercontent.com/1051643/68292472-d7d50880-0083-11ea-8bfe-8816d9cefbb9.png">

Original svg:

<img width="533" alt="Screenshot 2019-11-06 at 10 56 23" src="https://user-images.githubusercontent.com/1051643/68292580-15399600-0084-11ea-844a-8cde0135dbee.png">

**Comment by msand** [comment]
Trace out / isolate the pentagons you want to color into separate path elements, and set the fill color.

**Comment by expouic** [comment]
But i load the SVG from file! And don't change the content of SVG!

I want the user click on the object path and color the content with previous selected color.

**Comment by msand** [comment]
Then you need to translate the svg file into a react component, and handle the state changes.

**Comment by msand** [comment]
You can use https://www.smooth-code.com/open-source/svgr/playground/ with the react-native setting to do most of the translation for you. But you probably need to split your svg content into several paths, if you want to color them independently.

**Comment by expouic** [comment]
tks @msand i will try with this example convert my SVG file to react-native component

**Comment by stvdrsch** [comment]
I'm having a similar problem, so is it possible to import an SVG from file and add properties to child paths? I'm trying to automatically add onPress events to childPaths with certain ID's of an imported SVG. I'm using this and `react-native-svg-transformer`. But I'm having problems accessing the 'child' Paths.

**Comment by msand** [comment]
@stvdrsch Maybe the serialize example can give you some inspiration https://github.com/react-native-community/react-native-svg#serialize
But i would recommend converting it to react components instead, and make the attributes depend on the props.
