### ISSUE TITLE
RNSVGLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by hesizhe** [react-native-community/react-native-svg#1184]
我在使用react-native-shadow 与 react-native-svg使用时，在Android上没有问题，但在IOS上出现以下错误：
Invariant Violation: requireNativeComponent: "RNSVGLinearGradient" was not found in the UIManager.

This error is located at:
    in RNSVGLinearGradient (at LinearGradient.tsx:31)
    in LinearGradient (at BoxShadow.js:63)
    in RNSVGDefs (at Defs.tsx:8)
    in Defs (at BoxShadow.js:62)
    in RNSVGGroup (at G.tsx:28)
    in G (at Svg.tsx:170)
    in RNSVGSvgView (at Svg.tsx:157)
    in Svg (at BoxShadow.js:61)
    in RCTView (at BoxShadow.js:60)
    in BoxShadow (at news.js:48)
    in News (at home/index.js:164)
    in RCTView (at home/index.js:159)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1151)
    in ScrollView (at home/index.js:139)
    in RCTView (at home/index.js:115)
    in Index (at SceneView.js:9)
    in SceneView (at createTabNavigator.tsx:67)
    in RCTView (at ResourceSavingScene.tsx:37)
    in RCTView (at ResourceSavingScene.tsx:26)
    in ResourceSavingScene (at createBottomTabNavigator.tsx:157)
    in RCTView (at screens.native.js:101)
    in ScreenContainer (at createBottomTabNavigator.tsx:147)
    in RCTView (at createBottomTabNavigator.tsx:146)
    in TabNavigationView (at createTabNavigator.tsx:228)
    in NavigationView (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:889)
    in RCTView (at StackViewLayout.tsx:888)
    in RCTView (at StackViewLayout.tsx:887)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:17)
    in App (at TopView.js:260)
    in RCTView (at TopView.js:242)
    in PureView (at TopView.js:211)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at TopView.js:210)
    in RCTView (at TopView.js:209)
    in TopView (at TopView.js:259)
    in RootElement (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

getNativeComponentAttributes
    getNativeComponentAttributes.js:30:4
exports.get
    ReactNativeViewConfigRegistry.js:102:25
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
renderApplication
    renderApplication.js:52:52
runnables.appKey.run
    AppRegistry.js:116:10
runApplication
    AppRegistry.js:197:26
callFunctionReturnFlushedQueue
    [native code]:0

version:
  react-native": "0.61.4",
  react-native-svg": "^9.13.3",

**Comment by msand** [comment]
Seems you haven't rebuilt your native code after installing react-native-svg, try running
react-native run-ios
or start an android emulator and
react-native run-android
Or, if that doesn't help, open the project in xcode / android studio, clean the project, and rebuild.

**Comment by TRIPTI-JAIN** [comment]
I think you did not link react-native-SVG properly
if you did it then rebuilt your app and it is working fine

**Comment by i1990jain** [comment]
you need to do 
`cd ios && pod install `
once after installing react-native-svg from npm

**Comment by BadMask121** [comment]
https://github.com/kmagiera/react-native-screens/issues/281

Try this, it solved similar issue I had with core modules

**Comment by phungmaiton** [comment]
I have this issue too, react native 0.74.3. Tried everything I found online but still couldn't fix it.

**Comment by tyawei** [comment]
> I have this issue too, react native 0.74.3. Tried everything I found online but still couldn't fix it.

me too...

**Comment by luis-szn** [comment]
For android, I've solved deleting: 

`android/build`
`android/app/build`
`android/app/.cxx`

After this, restart metro and rebuild the app
