### ISSUE TITLE
svg icon is not rendering properly in ios if SVGO is enabled

### ISSUE THREAD

**Issue by Yandamuri** [react-native-community/react-native-svg#1186]
# Bug

svg icon is not rendering properly in ios if **SVGO** is enabled. If SVGO is disabled, icons gets rendered properly.

in android,

![android](https://user-images.githubusercontent.com/31983789/68526139-b764b280-02fe-11ea-8820-8313542c07c8.png)

in ios,
![ios](https://user-images.githubusercontent.com/31983789/68526142-ba5fa300-02fe-11ea-9b96-c709537af68c.png)

## Environment info

System:
      OS: Windows 10
      CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 6.19 GB / 15.87 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Library version: "9.13.3",

If **SVGO** is enabled in the [SVG converter](https://www.smooth-code.com/open-source/svgr/playground/) then icon is not rendering properly. For the time being i have disabled the **SVGO** which results in lengthy code than converted code.

**Note:** in android icon renders properly no matter wether **SVGO** is enabled or disabled.

**Comment by Yandamuri** [comment]
@msand I tired to reproduce the issue through expo, Surprisingly it's working fine there. But still the icon not rendering properly any of ios devices or emulators,

Please have a look at the following code,

Below is SVGO enabled code which is working fine in android , But not in ios.

    <Svg viewBox="0 0 20 18" width={100} height={100}>
            <G fill={"#000"} fillRule="nonzero" opacity={1}>
              <Path d="M9.792 4.063a.89.89 0 00.89-.89V.946a.89.89 0 00-1.78 0v.445H6.788v1.78h2.114c0                    .492.398.89.89.89zM14.576 4.063a.89.89 0 00.89-.89V.946a.89.89 0 00-1.78 0v.445h-2.114v1.78h2.114c0 .492.399.89.89.89z" />
              <Path d="M18.693 1.392h-2.336v1.78h1.446v2.67H1.78v-2.67h2.337a.89.89 0 001.78 0V.947a.89.89 0 00-1.78 0v.445H.89a.89.89 0 00-.89.89v13.352c0 .492.399.89.89.89h4.573a5.308 5.308 0 01-.836-1.78H1.78V6.733h16.023v8.011h-2.846a5.32 5.32 0 01-.836 1.78h4.572a.89.89 0 00.89-.89V2.282a.89.89 0 00-.89-.89z" />
              <Path d="M11.902 14.16l-1.41-.813a.704.704 0 00-.296-.517v-2.455a.405.405 0 10-.81 0v2.455a.707.707 0 00.704 1.219l1.407.812a.404.404 0 10.405-.7zm-2.11-.447a.304.304 0 11.001-.608.304.304 0 01-.001.607z" />
              <Path d="M9.792 8.958A4.456 4.456 0 005.34 13.41a4.456 4.456 0 004.45 4.45 4.456 4.456 0 004.451-4.45 4.456 4.456 0 00-4.45-4.452zm0 8.092A3.645 3.645 0 016.15 13.41a3.645 3.645 0 013.642-3.641 3.645 3.645 0 013.64 3.64 3.645 3.645 0 01-3.64 3.642z" />
            </G>
          </Svg> 

Below is SVGO not enabled code which is working fine in both android and ios.

      <Svg id="Capa_1" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 47 47" xmlSpace="preserve">
             <G>
		<G id="Layer_1_153_">
		   <G fill={"#000"} fillRule="nonzero" opacity={1}>
			 <Path d="M23.5,11.75c1.18,0,2.137-0.957,2.137-2.136V4.273c0-1.18-0.957-2.137-2.137-2.137c-1.179,0-2.136,0.957-2.136,2.137 v1.068H16.29v4.273h5.074C21.364,10.793,22.32,11.75,23.5,11.75z" />
		        <Path d="M34.982,11.75c1.181,0,2.137-0.957,2.137-2.136V4.273c0-1.18-0.957-2.137-2.137-2.137c-1.178,0-2.135,0.957-2.135,2.137 v1.068h-5.074v4.273h5.074C32.848,10.793,33.803,11.75,34.982,11.75z" />
			<Path d="M44.863,5.341h-5.607v4.273h3.471v6.409H4.273V9.614h5.608c0,1.18,0.957,2.136,2.136,2.136 c1.179,0,2.136-0.957,2.136-2.136V4.273c0-1.18-0.957-2.137-2.136-2.137c-1.179,0-2.136,0.957-2.136,2.137v1.068H2.136 C0.956,5.341,0,6.298,0,7.477v32.045c0,1.181,0.957,2.137,2.136,2.137H13.11c-0.917-1.271-1.604-2.715-2.006-4.273H4.273V18.159 h38.454v19.227h-6.83c-0.403,1.559-1.09,3.002-2.006,4.273h10.973c1.181,0,2.137-0.957,2.137-2.137V7.477 C47,6.297,46.043,5.341,44.863,5.341z" />
		        <Path d="M28.564,35.985l-3.381-1.952c-0.045-0.513-0.312-0.962-0.713-1.242v-5.892c0-0.537-0.435-0.972-0.971-0.972 s-0.971,0.435-0.971,0.972v5.892c-0.439,0.308-0.728,0.815-0.728,1.392c0,0.937,0.763,1.698,1.699,1.698 c0.257,0,0.498-0.062,0.717-0.164l3.377,1.95c0.153,0.088,0.32,0.13,0.485,0.13c0.335,0,0.662-0.174,0.842-0.485 C29.189,36.847,29.029,36.253,28.564,35.985z M23.5,34.91c-0.401,0-0.728-0.327-0.728-0.729c0-0.4,0.327-0.728,0.728-0.728 s0.729,0.327,0.729,0.728C24.229,34.583,23.901,34.91,23.5,34.91z" />
			<Path d="M23.5,23.5c-5.89,0-10.682,4.792-10.682,10.683c0,5.89,4.792,10.682,10.682,10.682c5.891,0,10.682-4.792,10.682-10.682 C34.182,28.292,29.391,23.5,23.5,23.5z M23.5,42.921c-4.819,0-8.739-3.92-8.739-8.74s3.92-8.738,8.739-8.738 c4.818,0,8.738,3.92,8.738,8.738C32.238,39,28.318,42.921,23.5,42.921z" />
			</G>
			</G>
			</G>
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
			<G />
	</Svg>

Here is expo link where i tried to reproduce the issue, But failed
https://snack.expo.io/@syamkishore/svg-icon-rendering-issue

**Comment by Yandamuri** [comment]
@msand Could you let me any update on this? Do i need to provide any more info to proceed for further?

**Comment by msand** [comment]
Seems to work fine for me:

![Simulator Screen Shot - iPhone 11 - 2019-11-14 at 01 09 18](https://user-images.githubusercontent.com/1131362/68812325-672d7d80-067b-11ea-8f49-5126827ac79a.png)

**Comment by msand** [comment]
You probably have old native code running, try cleaning the build, rebuild, and install the new build.

**Comment by Yandamuri** [comment]
@msand Thank you for your solution. It's working fine now.
