### ISSUE TITLE
Text cutout/knockout (background-clip for text)?

### ISSUE THREAD

**Issue by alexandergunnarson** [react-native-community/react-native-svg#119]
Hey — I was just wondering whether this library supports text cutout/knockout like [this example](https://codepen.io/shshaw/pen/sdEaI). I'd like text to be able to be cut out of an SVG shape.

Thanks for your help!

**Comment by magicismight** [comment]
I`m afraid the `mask` element is not supported yet.

**Comment by alexandergunnarson** [comment]
Aw :/ Well thanks for letting me know! What's the roadmap toward getting that functionality?

**Comment by smddzcy** [comment]
Bump: Is this still not supported?

**Comment by msand** [comment]
@smddzcy should work, requires setting x, y, width and height on mask, but otherwise should be fine
https://github.com/react-native-community/react-native-svg/blob/master/README.md#mask
