### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by friederbluemle** [react-native-community/react-native-svg#1191]
This repo contains both a `master` and a `develop` branch. The standard default branch for Git is `master`. It's usually not necessary to have more than one main branch in one repo.

React Native library projects (like most other projects) typically only contain `master`.

Can `master` be fast-forwarded to `develop`, and the `develop` branch removed? It would simplify branch management and won't cause confusion when opening PRs (e.g. which base branch to select).

**Comment by msand** [comment]
Hmm, not sure what standard you are referring to? Can you give a link to this "git standard" you speak of? Gitflow usually has at least a master and a develop branch: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
https://nvie.com/posts/a-successful-git-branching-model/
https://nativebase.io/docs/v0.3.1/contribute#git-flow
https://blog.usejournal.com/react-native-continuous-deployment-628468f2e2f1

Do you have statistics to support your "most other projects" claim?

Have you done much branch management in this repo? Has there been any issues with normal gitflow? What confusion are you talking about? If it's to the wrong one it takes me two seconds to correct.

**Comment by friederbluemle** [comment]
Hi @msand - Thanks for your reply. If you have a strong preference for keeping two main branches in this repo, then by all means, keep them :) Please feel free to close this issue, and sorry for bringing this up.
