### ISSUE TITLE
Interaction with react-native-gesture-handler

### ISSUE THREAD

**Issue by mjmasn** [react-native-community/react-native-svg#1193]
# Question 

I'm using react-native-gesture-handler to wrap an `Svg` view and provide pinch/zoom functionality. That's all working fine, but when I try using any onPress handlers on the `Path`s / `Text`s / `Image`s inside the `Svg`, they don't trigger except occasionally when doing a very light, quick tap. It seems RNGH cancels the touch on the `Svg` immediately, (using `onPressIn` / `onPressOut`, the `onPressOut` is always called immediately after the `onPressIn`).

Replacing the `Svg` / `AnimatedG` with `View` / `Animated.View` and putting a `TouchableOpacity` (the standard one from react-native) inside that works fine, so I guess there is some difference between how `Touchable*`s and the react-native-svg components work.

Is there anything obvious that could be causing this issue? I'm happy to look at implementing a solution if I can be pointed in the right direction :)

Thanks!

**Comment by mjmasn** [comment]
Ah, I think I had misread the code w.r.t. what the Touchable Mixin was actually doing. Looks like setting `onResponderMove={() => {}}` on the elements with `onPress` solves this. Hopefully this helps someone either way!

**Comment by harveyconnor** [comment]
I'm still having this problem.
I have G elements nested within an animated svg and they aren't responding to onPress.

**Comment by sstephans** [comment]
I have the same, though it's very inconsistent behavior. Nested `Circle` components inside an svg. I two gesture handlers surrounding it a pan and a pinch (that zooms). When both have been used, and the zoom has changed the scale of the view that wraps the svg, most of the circle `onPress` events no longer fire. I does seem to be specifically to do with the interaction of the gesture handler and the svg library, I cannot reproduce the bug if the components being panned and zoomed are regular pressables or touchables.
