### ISSUE TITLE
SVG LinearGradient setting to black

### ISSUE THREAD

**Issue by nthegedus** [react-native-community/react-native-svg#1194]
I have a SVG file and its setting to black where should be the LinearGradient.
Here's the image
1 = how should be
2 = how is rendering

![icon](https://user-images.githubusercontent.com/1063383/68881530-07bb8600-06ec-11ea-88dc-902fdae1fb03.png)

that's is the code:

```
<Svg width='121' height='121' viewBox='0 0 121 121' fill='none' xmlns='http://www.w3.org/2000/svg'>
        <Path d='M60.1231 118.446C92.334 118.446 118.446 92.3339 118.446 60.123C118.446 27.9121 92.334 1.79999 60.1231 1.79999C27.9121 1.79999 1.80005 27.9121 1.80005 60.123C1.80005 92.3339 27.9121 118.446 60.1231 118.446Z' fill='#1C3B65' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M0 60.123C0 26.918 26.918 0 60.123 0C93.328 0 120.246 26.918 120.246 60.123C120.246 93.328 93.328 120.246 60.123 120.246C26.918 120.246 0 93.328 0 60.123ZM60.123 3.6C28.9062 3.6 3.6 28.9062 3.6 60.123C3.6 91.3398 28.9062 116.646 60.123 116.646C91.3398 116.646 116.646 91.3398 116.646 60.123C116.646 28.9062 91.3398 3.6 60.123 3.6Z' fill='#00BABC' />
        <Path opacity='0.07' fill-rule='evenodd' clip-rule='evenodd' d='M9.99902 60.123C9.99902 32.4402 32.4403 9.99896 60.123 9.99896C87.8057 9.99896 110.247 32.4402 110.247 60.123C110.247 87.8057 87.8057 110.247 60.123 110.247C32.4403 110.247 9.99902 87.8057 9.99902 60.123ZM60.123 13.599C34.4285 13.599 13.599 34.4285 13.599 60.123C13.599 85.8175 34.4285 106.647 60.123 106.647C85.8175 106.647 106.647 85.8175 106.647 60.123C106.647 34.4285 85.8175 13.599 60.123 13.599Z' fill='#00BABC' />
        <Path d='M16.2961 33.789C22.4248 33.789 27.3931 28.8207 27.3931 22.692C27.3931 16.5633 22.4248 11.595 16.2961 11.595C10.1674 11.595 5.1991 16.5633 5.1991 22.692C5.1991 28.8207 10.1674 33.789 16.2961 33.789Z' fill='#FDFEFF' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M3.39905 22.692C3.39905 15.5692 9.17323 9.79498 16.296 9.79498C23.4189 9.79498 29.193 15.5692 29.193 22.692C29.193 29.8148 23.4189 35.589 16.296 35.589C9.17323 35.589 3.39905 29.8148 3.39905 22.692ZM16.296 13.395C11.1615 13.395 6.99905 17.5574 6.99905 22.692C6.99905 27.8266 11.1615 31.989 16.296 31.989C21.4306 31.989 25.593 27.8266 25.593 22.692C25.593 17.5574 21.4306 13.395 16.296 13.395Z' fill='#00BABC' />
        <Path opacity='0.23' d='M16.2961 30.252C20.4714 30.252 23.8561 26.8673 23.8561 22.692C23.8561 18.5167 20.4714 15.132 16.2961 15.132C12.1208 15.132 8.73608 18.5167 8.73608 22.692C8.73608 26.8673 12.1208 30.252 16.2961 30.252Z' fill='url(#paint0_linear)' />
        <Path d='M15.498 26.791V19.7981H14.5031V18.7889L16.4967 17.791H17.5031V26.791H15.498Z' fill='#00BABC' />
        <Path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='white' />
        <Path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5901 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9658 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2843 74.0956 88.8925C85.1139 83.5007 92.1006 72.3057 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='white' />
        <Path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='url(#paint1_linear)' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M45.8992 30.8077C57.1251 25.3153 70.4989 26.6957 80.3663 34.3653L80.3683 34.3668C82.1716 35.7808 82.4873 38.3889 81.0733 40.1922C79.6597 41.995 77.0526 42.311 75.2494 40.8983C67.8808 35.1889 57.9054 34.17 49.5346 38.2717C41.344 42.2851 36.0865 50.5165 35.8607 59.6015L41.8436 59.577L31.758 69.6626L21.672 59.573L27.5607 59.6012C27.7857 47.3407 34.854 36.2117 45.8992 30.8077ZM79.6287 35.3118C70.1232 27.9242 57.2404 26.5948 46.4265 31.8856C35.6122 37.1767 28.7554 48.1647 28.7551 60.204L28.7551 60.8069L24.5822 60.787L31.7582 67.9654L38.9346 60.789L34.6529 60.8065L34.6531 60.2038C34.656 50.4237 40.2241 41.4975 49.0066 37.1941C57.789 32.8907 68.255 33.96 75.9856 39.9507L75.9883 39.9528C77.2701 40.9579 79.1239 40.7335 80.129 39.4518C81.1338 38.1703 80.9098 36.317 79.6287 35.3118Z' fill='#00BABC' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M46.0352 31.0856C57.1411 25.6519 70.3719 27.0175 80.1338 34.6051L80.1346 34.6057C81.7858 35.9004 82.0748 38.2885 80.7801 39.9397C79.4855 41.5907 77.0978 41.8798 75.4467 40.5856C67.9725 34.794 57.8538 33.7602 49.3628 37.9208C40.9468 42.0447 35.5838 50.5591 35.4867 59.9164L40.9774 59.894L31.7403 69.131L22.5031 59.8905L27.8883 59.9162C27.9833 47.6509 35.0046 36.4825 46.0352 31.0856ZM79.8267 34.9996C70.2156 27.5294 57.1892 26.1849 46.2549 31.5347C35.3206 36.8845 28.3877 47.9945 28.3874 60.1674L28.3873 60.4186L23.7157 60.3963L31.7404 68.4239L39.7653 60.3989L34.9853 60.4185L34.9854 60.1674C34.9882 50.5208 40.4803 41.7165 49.1428 37.4718C57.8054 33.2272 68.1284 34.2819 75.7535 40.1908L75.7546 40.1917C77.1885 41.316 79.2623 41.0651 80.3866 39.6312C81.5108 38.1975 81.26 36.124 79.8267 34.9996Z' fill='#00BABC' />
        <Path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5902 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9659 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2844 74.0956 88.8926C85.1139 83.5008 92.1006 72.3058 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='url(#paint2_linear)' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 50.5834L98.5862 60.6699L92.6974 60.6418C92.4704 72.9006 85.4027 84.0274 74.3594 89.4315C63.1354 94.924 49.7634 93.5463 39.895 85.8808L39.893 85.8792C38.0888 84.4653 37.7724 81.8566 39.1863 80.0524C40.5999 78.2486 43.2078 77.932 45.0119 79.3448C52.38 85.0547 62.3553 86.074 70.7259 81.9721C78.9162 77.9585 84.173 69.7266 84.3976 60.6418L78.4167 60.6698L88.5031 50.5834ZM81.3274 59.4562L85.6052 59.4362L85.6051 60.0391C85.6037 69.8192 80.0363 78.7459 71.254 83.0496C62.4716 87.3533 52.0056 86.2836 44.2755 80.2922L44.273 80.2902C42.9904 79.2851 41.1359 79.51 40.1308 80.7926C39.126 82.0747 39.3505 83.9285 40.632 84.9338C50.1385 92.3177 63.0198 93.6446 73.8319 88.3536C84.6444 83.0625 91.5007 72.0766 91.5031 60.0389L91.5032 59.4361L95.6759 59.456L88.503 52.2806L81.3274 59.4562Z' fill='#00BABC' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 51.0784L97.7373 60.3159L92.352 60.2902C92.255 72.5539 85.2343 83.7202 74.2055 89.1171C63.1015 94.5509 49.8726 93.188 40.1097 85.6044L40.1088 85.6038C38.4568 84.3091 38.1671 81.9203 39.4618 80.2683C40.7563 78.6164 43.1448 78.3266 44.7968 79.6209C52.2704 85.4132 62.3891 86.4472 70.8799 82.2864C79.2957 78.1623 84.658 69.6474 84.7537 60.2902L79.2656 60.3158L88.5031 51.0784ZM80.4784 59.8102L85.2551 59.7878L85.255 60.039C85.2537 69.6856 79.7623 78.4905 71.0999 82.7354C62.4375 86.9803 52.1144 85.9252 44.4899 80.0156L44.4888 80.0148C43.0541 78.8904 40.9796 79.142 39.8553 80.5767C38.731 82.0113 38.9825 84.0856 40.4169 85.21C50.029 92.6761 63.0534 94.0178 73.9857 88.668C84.9183 83.3182 91.8507 72.2103 91.853 60.039L91.8531 59.7878L96.5247 59.8101L88.503 51.7856L80.4784 59.8102Z' fill='#00BABC' />
        <Defs>
          <LinearGradient id='paint0_linear' x1='8.73608' y1='15.132' x2='8.73608' y2='30.252' gradientUnits='userSpaceOnUse'>
            <Stop stop-color='#CEEBEB' />
            <Stop offset='1' stop-color='#00BABC' />
          </LinearGradient>
          <LinearGradient id='paint1_linear' x1='23.1325' y1='28.077' x2='23.1325' y2='68.814' gradientUnits='userSpaceOnUse'>
            <Stop stop-color='#CEEBEB' />
            <Stop offset='1' stop-color='#00BABC' />
          </LinearGradient>
          <LinearGradient id='paint2_linear' x1='38.8816' y1='51.432' x2='38.8816' y2='92.166' gradientUnits='userSpaceOnUse'>
            <Stop stop-color='#CEEBEB' />
            <Stop offset='1' stop-color='#00BABC' />
          </LinearGradient>
        </Defs>
      </Svg>
```

If you try render here https://codepen.io/LeftyDesigner/pen/gLabt there's no problem with the svg

Any ideia about what's happening?

**Comment by nthegedus** [comment]
Updating to latest version and using like this worked fine:

```
import { SvgXml } from 'react-native-svg'

const xml = `<svg width='121' height='121' viewBox='0 0 121 121' fill='none' xmlns='http://www.w3.org/2000/svg'>
<path d='M60.1231 118.446C92.334 118.446 118.446 92.3339 118.446 60.123C118.446 27.9121 92.334 1.79999 60.1231 1.79999C27.9121 1.79999 1.80005 27.9121 1.80005 60.123C1.80005 92.3339 27.9121 118.446 60.1231 118.446Z' fill='#1C3B65'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M0 60.123C0 26.918 26.918 0 60.123 0C93.328 0 120.246 26.918 120.246 60.123C120.246 93.328 93.328 120.246 60.123 120.246C26.918 120.246 0 93.328 0 60.123ZM60.123 3.6C28.9062 3.6 3.6 28.9062 3.6 60.123C3.6 91.3398 28.9062 116.646 60.123 116.646C91.3398 116.646 116.646 91.3398 116.646 60.123C116.646 28.9062 91.3398 3.6 60.123 3.6Z' fill='#00BABC'/>
<path opacity='0.07' fill-rule='evenodd' clip-rule='evenodd' d='M9.99902 60.123C9.99902 32.4402 32.4403 9.99896 60.123 9.99896C87.8057 9.99896 110.247 32.4402 110.247 60.123C110.247 87.8057 87.8057 110.247 60.123 110.247C32.4403 110.247 9.99902 87.8057 9.99902 60.123ZM60.123 13.599C34.4285 13.599 13.599 34.4285 13.599 60.123C13.599 85.8175 34.4285 106.647 60.123 106.647C85.8175 106.647 106.647 85.8175 106.647 60.123C106.647 34.4285 85.8175 13.599 60.123 13.599Z' fill='#00BABC'/>
<path d='M16.2961 33.789C22.4248 33.789 27.3931 28.8207 27.3931 22.692C27.3931 16.5633 22.4248 11.595 16.2961 11.595C10.1674 11.595 5.1991 16.5633 5.1991 22.692C5.1991 28.8207 10.1674 33.789 16.2961 33.789Z' fill='#FDFEFF'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M3.39905 22.692C3.39905 15.5692 9.17323 9.79498 16.296 9.79498C23.4189 9.79498 29.193 15.5692 29.193 22.692C29.193 29.8148 23.4189 35.589 16.296 35.589C9.17323 35.589 3.39905 29.8148 3.39905 22.692ZM16.296 13.395C11.1615 13.395 6.99905 17.5574 6.99905 22.692C6.99905 27.8266 11.1615 31.989 16.296 31.989C21.4306 31.989 25.593 27.8266 25.593 22.692C25.593 17.5574 21.4306 13.395 16.296 13.395Z' fill='#00BABC'/>
<path opacity='0.23' d='M16.2961 30.252C20.4714 30.252 23.8561 26.8673 23.8561 22.692C23.8561 18.5167 20.4714 15.132 16.2961 15.132C12.1208 15.132 8.73608 18.5167 8.73608 22.692C8.73608 26.8673 12.1208 30.252 16.2961 30.252Z' fill='url(#paint0_linear)'/>
<path d='M15.498 26.791V19.7981H14.5031V18.7889L16.4967 17.791H17.5031V26.791H15.498Z' fill='#00BABC'/>
<path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='white'/>
<path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5901 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9658 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2843 74.0956 88.8925C85.1139 83.5007 92.1006 72.3057 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='white'/>
<path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='url(#paint1_linear)'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M45.8992 30.8077C57.1251 25.3153 70.4989 26.6957 80.3663 34.3653L80.3683 34.3668C82.1716 35.7808 82.4873 38.3889 81.0733 40.1922C79.6597 41.995 77.0526 42.311 75.2494 40.8983C67.8808 35.1889 57.9054 34.17 49.5346 38.2717C41.344 42.2851 36.0865 50.5165 35.8607 59.6015L41.8436 59.577L31.758 69.6626L21.672 59.573L27.5607 59.6012C27.7857 47.3407 34.854 36.2117 45.8992 30.8077ZM79.6287 35.3118C70.1232 27.9242 57.2404 26.5948 46.4265 31.8856C35.6122 37.1767 28.7554 48.1647 28.7551 60.204L28.7551 60.8069L24.5822 60.787L31.7582 67.9654L38.9346 60.789L34.6529 60.8065L34.6531 60.2038C34.656 50.4237 40.2241 41.4975 49.0066 37.1941C57.789 32.8907 68.255 33.96 75.9856 39.9507L75.9883 39.9528C77.2701 40.9579 79.1239 40.7335 80.129 39.4518C81.1338 38.1703 80.9098 36.317 79.6287 35.3118Z' fill='#00BABC'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M46.0352 31.0856C57.1411 25.6519 70.3719 27.0175 80.1338 34.6051L80.1346 34.6057C81.7858 35.9004 82.0748 38.2885 80.7801 39.9397C79.4855 41.5907 77.0978 41.8798 75.4467 40.5856C67.9725 34.794 57.8538 33.7602 49.3628 37.9208C40.9468 42.0447 35.5838 50.5591 35.4867 59.9164L40.9774 59.894L31.7403 69.131L22.5031 59.8905L27.8883 59.9162C27.9833 47.6509 35.0046 36.4825 46.0352 31.0856ZM79.8267 34.9996C70.2156 27.5294 57.1892 26.1849 46.2549 31.5347C35.3206 36.8845 28.3877 47.9945 28.3874 60.1674L28.3873 60.4186L23.7157 60.3963L31.7404 68.4239L39.7653 60.3989L34.9853 60.4185L34.9854 60.1674C34.9882 50.5208 40.4803 41.7165 49.1428 37.4718C57.8054 33.2272 68.1284 34.2819 75.7535 40.1908L75.7546 40.1917C77.1885 41.316 79.2623 41.0651 80.3866 39.6312C81.5108 38.1975 81.26 36.124 79.8267 34.9996Z' fill='#00BABC'/>
<path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5902 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9659 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2844 74.0956 88.8926C85.1139 83.5008 92.1006 72.3058 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='url(#paint2_linear)'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 50.5834L98.5862 60.6699L92.6974 60.6418C92.4704 72.9006 85.4027 84.0274 74.3594 89.4315C63.1354 94.924 49.7634 93.5463 39.895 85.8808L39.893 85.8792C38.0888 84.4653 37.7724 81.8566 39.1863 80.0524C40.5999 78.2486 43.2078 77.932 45.0119 79.3448C52.38 85.0547 62.3553 86.074 70.7259 81.9721C78.9162 77.9585 84.173 69.7266 84.3976 60.6418L78.4167 60.6698L88.5031 50.5834ZM81.3274 59.4562L85.6052 59.4362L85.6051 60.0391C85.6037 69.8192 80.0363 78.7459 71.254 83.0496C62.4716 87.3533 52.0056 86.2836 44.2755 80.2922L44.273 80.2902C42.9904 79.2851 41.1359 79.51 40.1308 80.7926C39.126 82.0747 39.3505 83.9285 40.632 84.9338C50.1385 92.3177 63.0198 93.6446 73.8319 88.3536C84.6444 83.0625 91.5007 72.0766 91.5031 60.0389L91.5032 59.4361L95.6759 59.456L88.503 52.2806L81.3274 59.4562Z' fill='#00BABC'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 51.0784L97.7373 60.3159L92.352 60.2902C92.255 72.5539 85.2343 83.7202 74.2055 89.1171C63.1015 94.5509 49.8726 93.188 40.1097 85.6044L40.1088 85.6038C38.4568 84.3091 38.1671 81.9203 39.4618 80.2683C40.7563 78.6164 43.1448 78.3266 44.7968 79.6209C52.2704 85.4132 62.3891 86.4472 70.8799 82.2864C79.2957 78.1623 84.658 69.6474 84.7537 60.2902L79.2656 60.3158L88.5031 51.0784ZM80.4784 59.8102L85.2551 59.7878L85.255 60.039C85.2537 69.6856 79.7623 78.4905 71.0999 82.7354C62.4375 86.9803 52.1144 85.9252 44.4899 80.0156L44.4888 80.0148C43.0541 78.8904 40.9796 79.142 39.8553 80.5767C38.731 82.0113 38.9825 84.0856 40.4169 85.21C50.029 92.6761 63.0534 94.0178 73.9857 88.668C84.9183 83.3182 91.8507 72.2103 91.853 60.039L91.8531 59.7878L96.5247 59.8101L88.503 51.7856L80.4784 59.8102Z' fill='#00BABC'/>
<defs>
<linearGradient id='paint0_linear' x1='8.73608' y1='15.132' x2='8.73608' y2='30.252' gradientUnits='userSpaceOnUse'>
<stop stop-color='#CEEBEB'/>
<stop offset='1' stop-color='#00BABC'/>
</linearGradient>
<linearGradient id='paint1_linear' x1='23.1325' y1='28.077' x2='23.1325' y2='68.814' gradientUnits='userSpaceOnUse'>
<stop stop-color='#CEEBEB'/>
<stop offset='1' stop-color='#00BABC'/>
</linearGradient>
<linearGradient id='paint2_linear' x1='38.8816' y1='51.432' x2='38.8816' y2='92.166' gradientUnits='userSpaceOnUse'>
<stop stop-color='#CEEBEB'/>
<stop offset='1' stop-color='#00BABC'/>
</linearGradient>
</defs>
</svg>
`

<SvgXml width='121' height='121' xml={xml} />
```

**Comment by msand** [comment]
Seems you hadn't converted the attributes to be react compatible e.g. stop-color to stopColor, fill-rule to fillRule, clip-rule to clipRule etc, you can use e.g. https://www.smooth-code.com/open-source/svgr/playground/ for that

**Comment by MichelBahl** [comment]
Use percent instead of pixels and convert as @msand said.

Below is a working sample:

`<Svg width='121' height='121' viewBox='0 0 121 121' fill='none'>
        <Path d='M60.1231 118.446C92.334 118.446 118.446 92.3339 118.446 60.123C118.446 27.9121 92.334 1.79999 60.1231 1.79999C27.9121 1.79999 1.80005 27.9121 1.80005 60.123C1.80005 92.3339 27.9121 118.446 60.1231 118.446Z' fill='#1C3B65' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M0 60.123C0 26.918 26.918 0 60.123 0C93.328 0 120.246 26.918 120.246 60.123C120.246 93.328 93.328 120.246 60.123 120.246C26.918 120.246 0 93.328 0 60.123ZM60.123 3.6C28.9062 3.6 3.6 28.9062 3.6 60.123C3.6 91.3398 28.9062 116.646 60.123 116.646C91.3398 116.646 116.646 91.3398 116.646 60.123C116.646 28.9062 91.3398 3.6 60.123 3.6Z' fill='#00BABC' />
        <Path opacity='0.07' fill-rule='evenodd' clip-rule='evenodd' d='M9.99902 60.123C9.99902 32.4402 32.4403 9.99896 60.123 9.99896C87.8057 9.99896 110.247 32.4402 110.247 60.123C110.247 87.8057 87.8057 110.247 60.123 110.247C32.4403 110.247 9.99902 87.8057 9.99902 60.123ZM60.123 13.599C34.4285 13.599 13.599 34.4285 13.599 60.123C13.599 85.8175 34.4285 106.647 60.123 106.647C85.8175 106.647 106.647 85.8175 106.647 60.123C106.647 34.4285 85.8175 13.599 60.123 13.599Z' fill='#00BABC' />
        <Path d='M16.2961 33.789C22.4248 33.789 27.3931 28.8207 27.3931 22.692C27.3931 16.5633 22.4248 11.595 16.2961 11.595C10.1674 11.595 5.1991 16.5633 5.1991 22.692C5.1991 28.8207 10.1674 33.789 16.2961 33.789Z' fill='#FDFEFF' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M3.39905 22.692C3.39905 15.5692 9.17323 9.79498 16.296 9.79498C23.4189 9.79498 29.193 15.5692 29.193 22.692C29.193 29.8148 23.4189 35.589 16.296 35.589C9.17323 35.589 3.39905 29.8148 3.39905 22.692ZM16.296 13.395C11.1615 13.395 6.99905 17.5574 6.99905 22.692C6.99905 27.8266 11.1615 31.989 16.296 31.989C21.4306 31.989 25.593 27.8266 25.593 22.692C25.593 17.5574 21.4306 13.395 16.296 13.395Z' fill='#00BABC' />
        <Path opacity='0.23' d='M16.2961 30.252C20.4714 30.252 23.8561 26.8673 23.8561 22.692C23.8561 18.5167 20.4714 15.132 16.2961 15.132C12.1208 15.132 8.73608 18.5167 8.73608 22.692C8.73608 26.8673 12.1208 30.252 16.2961 30.252Z' fill='url(#paint0_linear)' />
        <Path d='M15.498 26.791V19.7981H14.5031V18.7889L16.4967 17.791H17.5031V26.791H15.498Z' fill='#00BABC' />
        <Path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='white' />
        <Path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5901 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9658 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2843 74.0956 88.8925C85.1139 83.5007 92.1006 72.3057 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='white' />
        <Path d='M35.2531 60.204C35.2559 50.6528 40.6937 41.9356 49.2705 37.7329C57.8474 33.5302 68.0684 34.5745 75.6181 40.425C77.1606 41.6345 79.3916 41.3645 80.6011 39.822C81.8106 38.2795 81.5406 36.0485 79.9981 34.839C70.3116 27.31 57.1829 25.9549 46.1628 31.3467C35.1427 36.7384 28.1554 47.9356 28.1551 60.204L23.1271 60.18L31.7581 68.814L40.3891 60.183L35.2531 60.204Z' fill='url(#paint1_linear)' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M45.8992 30.8077C57.1251 25.3153 70.4989 26.6957 80.3663 34.3653L80.3683 34.3668C82.1716 35.7808 82.4873 38.3889 81.0733 40.1922C79.6597 41.995 77.0526 42.311 75.2494 40.8983C67.8808 35.1889 57.9054 34.17 49.5346 38.2717C41.344 42.2851 36.0865 50.5165 35.8607 59.6015L41.8436 59.577L31.758 69.6626L21.672 59.573L27.5607 59.6012C27.7857 47.3407 34.854 36.2117 45.8992 30.8077ZM79.6287 35.3118C70.1232 27.9242 57.2404 26.5948 46.4265 31.8856C35.6122 37.1767 28.7554 48.1647 28.7551 60.204L28.7551 60.8069L24.5822 60.787L31.7582 67.9654L38.9346 60.789L34.6529 60.8065L34.6531 60.2038C34.656 50.4237 40.2241 41.4975 49.0066 37.1941C57.789 32.8907 68.255 33.96 75.9856 39.9507L75.9883 39.9528C77.2701 40.9579 79.1239 40.7335 80.129 39.4518C81.1338 38.1703 80.9098 36.317 79.6287 35.3118Z' fill='#00BABC' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M46.0352 31.0856C57.1411 25.6519 70.3719 27.0175 80.1338 34.6051L80.1346 34.6057C81.7858 35.9004 82.0748 38.2885 80.7801 39.9397C79.4855 41.5907 77.0978 41.8798 75.4467 40.5856C67.9725 34.794 57.8538 33.7602 49.3628 37.9208C40.9468 42.0447 35.5838 50.5591 35.4867 59.9164L40.9774 59.894L31.7403 69.131L22.5031 59.8905L27.8883 59.9162C27.9833 47.6509 35.0046 36.4825 46.0352 31.0856ZM79.8267 34.9996C70.2156 27.5294 57.1892 26.1849 46.2549 31.5347C35.3206 36.8845 28.3877 47.9945 28.3874 60.1674L28.3873 60.4186L23.7157 60.3963L31.7404 68.4239L39.7653 60.3989L34.9853 60.4185L34.9854 60.1674C34.9882 50.5208 40.4803 41.7165 49.1428 37.4718C57.8054 33.2272 68.1284 34.2819 75.7535 40.1908L75.7546 40.1917C77.1885 41.316 79.2623 41.0651 80.3866 39.6312C81.5108 38.1975 81.26 36.124 79.8267 34.9996Z' fill='#00BABC' />
        <Path d='M88.503 51.432L79.872 60.063L85.005 60.039C85.0037 69.5902 79.5666 78.3079 70.9899 82.5109C62.4132 86.7138 52.1921 85.6691 44.643 79.818C43.0997 78.6085 40.868 78.8791 39.6585 80.4225C38.449 81.9659 38.7197 84.1975 40.263 85.407C49.9505 92.932 63.0774 94.2844 74.0956 88.8926C85.1139 83.5008 92.1006 72.3058 92.103 60.039L97.131 60.063L88.503 51.432Z' fill='url(#paint2_linear)' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 50.5834L98.5862 60.6699L92.6974 60.6418C92.4704 72.9006 85.4027 84.0274 74.3594 89.4315C63.1354 94.924 49.7634 93.5463 39.895 85.8808L39.893 85.8792C38.0888 84.4653 37.7724 81.8566 39.1863 80.0524C40.5999 78.2486 43.2078 77.932 45.0119 79.3448C52.38 85.0547 62.3553 86.074 70.7259 81.9721C78.9162 77.9585 84.173 69.7266 84.3976 60.6418L78.4167 60.6698L88.5031 50.5834ZM81.3274 59.4562L85.6052 59.4362L85.6051 60.0391C85.6037 69.8192 80.0363 78.7459 71.254 83.0496C62.4716 87.3533 52.0056 86.2836 44.2755 80.2922L44.273 80.2902C42.9904 79.2851 41.1359 79.51 40.1308 80.7926C39.126 82.0747 39.3505 83.9285 40.632 84.9338C50.1385 92.3177 63.0198 93.6446 73.8319 88.3536C84.6444 83.0625 91.5007 72.0766 91.5031 60.0389L91.5032 59.4361L95.6759 59.456L88.503 52.2806L81.3274 59.4562Z' fill='#00BABC' />
        <Path fill-rule='evenodd' clip-rule='evenodd' d='M88.5031 51.0784L97.7373 60.3159L92.352 60.2902C92.255 72.5539 85.2343 83.7202 74.2055 89.1171C63.1015 94.5509 49.8726 93.188 40.1097 85.6044L40.1088 85.6038C38.4568 84.3091 38.1671 81.9203 39.4618 80.2683C40.7563 78.6164 43.1448 78.3266 44.7968 79.6209C52.2704 85.4132 62.3891 86.4472 70.8799 82.2864C79.2957 78.1623 84.658 69.6474 84.7537 60.2902L79.2656 60.3158L88.5031 51.0784ZM80.4784 59.8102L85.2551 59.7878L85.255 60.039C85.2537 69.6856 79.7623 78.4905 71.0999 82.7354C62.4375 86.9803 52.1144 85.9252 44.4899 80.0156L44.4888 80.0148C43.0541 78.8904 40.9796 79.142 39.8553 80.5767C38.731 82.0113 38.9825 84.0856 40.4169 85.21C50.029 92.6761 63.0534 94.0178 73.9857 88.668C84.9183 83.3182 91.8507 72.2103 91.853 60.039L91.8531 59.7878L96.5247 59.8101L88.503 51.7856L80.4784 59.8102Z' fill='#00BABC' />
        <Defs>
          <LinearGradient id='paint0_linear' x1='15%' y1='30%' x2='8%' y2='60%' gradientUnits='userSpaceOnUse'>
            <Stop stopColor='#CEEBEB' />
            <Stop offset='1' stopColor='#00BABC' />
          </LinearGradient>
          <LinearGradient id='paint1_linear' x1='25%' y1='55%' x2='45%' y2='50%' gradientUnits='userSpaceOnUse'>
            <Stop stopColor='#CEEBEB' />
            <Stop offset='1' stopColor='#00BABC' />
          </LinearGradient>
          <LinearGradient id='paint2_linear' x1='60%' y1='80%' x2='60%' y2='100%' gradientUnits='userSpaceOnUse'>
            <Stop stopColor='#CEEBEB' />
            <Stop offset='1' stopColor='#00BABC' />
          </LinearGradient>
        </Defs>
      </Svg>`
