### ISSUE TITLE
Animating SVG's using `useNativeDriver: true`

### ISSUE THREAD

**Issue by segersniels** [react-native-community/react-native-svg#1195]
# Question

I've been trying to do a rather simple pulsating animation using `react-native-svg`.

```js
const [pulseAnim] = useState(new Animated.Value(0));

useEffect(
    () => {
        Animated.loop(
          Animated.sequence([
            Animated.timing(pulseAnim, {
              toValue: 1,
              duration: interval,
              easing: Easing.elastic(1),
            }),
            Animated.timing(pulseAnim, {
              toValue: 0,
              duration: interval,
              easing: Easing.elastic(1),
            }),
          ]),
        ).start();
    },
    [interval, pulse, pulseAnim],
  );

  const interpolatedColor = pulseAnim.interpolate({
    inputRange: [0, 1],
    outputRange: [activeColor, disabledColor],
  });

  const AnimatedG = Animated.createAnimatedComponent(G);

  return (
    <Svg width={width} height={height} viewBox="0 0 24 22">
      <AnimatedG fill={interpolatedColor}>
        <Path d="..." />
        <Path
          opacity="0.5"
          d="..."
        />
      </AnimatedG>
    </Svg>
  );
```

It basically just loops between values 0 and 1 and by using `interpolate` transitioning from one color into another. Everything works rather fine on iOS but it's on Android where it goes completely bonkers. It starts throwing in random colors and flickering instead of nicely transitioning.

So I did some research and found out I could pass everything to the native layer to free up the JS thread, which could have been the reason why Android was acting up. But after seting `useNativeDriver: true` I've been getting errors on both iOS and Android.

Am I doing something wrong or is there in fact an issue between `react-native-svg` and the Animated API from `react-native`? Should be rather easy to reproduce I guess?

### iOS
> JSON value '0' of type NSNumber cannot be converted to NSArray

### Android
> Error while updating property 'fill' of a view managed by: RNSVGGroup
> null
> java.lang.Double cannot be cast to java.lang.String

## Versions
- `react-native-svg`: 9.13.3
- `react-native`: 0.60

**Comment by msand** [comment]
Can you try with this?

```jsx
import React, {useState, useEffect} from 'react';
import {Animated} from 'react-native';
import {Svg, G, Path} from 'react-native-svg';

const AnimatedG = Animated.createAnimatedComponent(G);

export default ({
  interval = 1000,
  activeColor = 'rgba(0,0,0,1)',
  disabledColor = 'rgba(128,128,128,1)',
}) => {
  const [pulseAnim] = useState(new Animated.Value(0));

  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(pulseAnim, {
          toValue: 1,
          duration: interval,
          useNativeDriver: true,
        }),
        Animated.timing(pulseAnim, {
          toValue: 0,
          duration: interval,
          useNativeDriver: true,
        }),
      ]),
    ).start();
  }, [interval, pulseAnim]);

  const interpolatedColor = pulseAnim.interpolate({
    inputRange: [0, 1],
    outputRange: [activeColor, disabledColor],
  });

  return (
    <Svg width={'100%'} height={'100%'} viewBox="0 0 24 22">
      <AnimatedG fill={interpolatedColor}>
        <Path d="M9.792 4.063a.89.89 0 00.89-.89V.946a.89.89 0 00-1.78 0v.445H6.788v1.78h2.114c0 .492.398.89.89.89zM14.576 4.063a.89.89 0 00.89-.89V.946a.89.89 0 00-1.78 0v.445h-2.114v1.78h2.114c0 .492.399.89.89.89z" />
        <Path d="M18.693 1.392h-2.336v1.78h1.446v2.67H1.78v-2.67h2.337a.89.89 0 001.78 0V.947a.89.89 0 00-1.78 0v.445H.89a.89.89 0 00-.89.89v13.352c0 .492.399.89.89.89h4.573a5.308 5.308 0 01-.836-1.78H1.78V6.733h16.023v8.011h-2.846a5.32 5.32 0 01-.836 1.78h4.572a.89.89 0 00.89-.89V2.282a.89.89 0 00-.89-.89z" />
        <Path d="M11.902 14.16l-1.41-.813a.704.704 0 00-.296-.517v-2.455a.405.405 0 10-.81 0v2.455a.707.707 0 00.704 1.219l1.407.812a.404.404 0 10.405-.7zm-2.11-.447a.304.304 0 11.001-.608.304.304 0 01-.001.607z" />
        <Path d="M9.792 8.958A4.456 4.456 0 005.34 13.41a4.456 4.456 0 004.45 4.45 4.456 4.456 0 004.451-4.45 4.456 4.456 0 00-4.45-4.452zm0 8.092A3.645 3.645 0 016.15 13.41a3.645 3.645 0 013.642-3.641 3.645 3.645 0 013.64 3.64 3.645 3.645 0 01-3.64 3.642z" />
      </AnimatedG>
    </Svg>
  );
};

```

I think there might be issues with Easing (at least bounciness) and some color combinations, it can cause overshoot and thus negative or greater than 255 in the rgb values.

**Comment by segersniels** [comment]
The issue doesn't seem to be related to `Easing` as it still crashes with the same errors as above. Even with the example you have provided it still crashes 😔

**Comment by msand** [comment]
Ah, now I see you're using react-native 0.60, v0.61 has my patches to animated included, so you'll need to upgrade that to make it work, or remove / set useNativeDriver: false.

**Comment by segersniels** [comment]
I'll try that. I assume https://github.com/facebook/react-native/pull/18187 is the PR for the patches you are talking about.

**Comment by msand** [comment]
Yes, and https://github.com/facebook/react-native/pull/24177 and https://github.com/facebook/react-native/pull/25256

**Comment by segersniels** [comment]
I'll keep you posted if it fixes the issue or not!

**Comment by msand** [comment]
You can also try the code i posted in a clean / new react-native project, just yarn add react-native-svg and you're done.
