### ISSUE TITLE
<Rect>, <Ellipse> are not rendered if opacity set to 0 on Android

### ISSUE THREAD

**Issue by oleksandr-dziuban** [react-native-community/react-native-svg#1200]
# Bug

Rect, Ellipse and possibly other SVG elements are not rendered if opacity set to 0 on Android.
iOS works fine.
We can detect if element was rendered with onPress handler.
What is interesting, with opacity=0.01 element still doesn't render on Android.
With 0.02 and higher - it is visible and clickable.

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 424.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
```

Library version: 9.13.3

## Steps To Reproduce

1. Render Rect or Ellipse with or opacity=0, opacity=0.01
2. Android app doesn't render element and it's not clickable.

Describe what you expected to happen:

1. Android app should render SVG element with opacity=0 and it should be clickable like on iOS.

## Reproducible sample code

```js
<Svg width={100} height={100} viewBox="0 0 100 100">
  <G>
      <Rect
        x={0}
        y={0}
        width={50}
        height={50}
        opacity={0}
        fill={"red"}
        stroke={"green"}
        onPress={() => { console.log('Press event'); }}
      />
  </G>
<Svg>

```

**Comment by balovbohdan** [comment]
Faced the same problem!

**Comment by oleksandr-dziuban** [comment]
@msand Could you please check this issue for Android, I think it will be quick fix. Thanks a lot

**Comment by oleksandr-dziuban** [comment]
Thanks a lot

**Comment by msand** [comment]
Released in v10 (breaking change wasn't registered correctly by semantic-release and forgot to do dry-run first)
