### ISSUE TITLE
iOS crashes when offset is set to a large number

### ISSUE THREAD

**Issue by mnemanja** [react-native-community/react-native-svg#1201]
I've experienced this by accidentally setting the value of the `offset` property to `750%` and the iOS app would just crash.

```ts
<LinearGradient id="gradient2">
  <Stop offset="50%" stopColor={stepThree} />
  <Stop offset="750%" stopColor={stepFour} />
</LinearGradient>
```

While the value in question is something that would probably never be used for the `offset` I still believe that it should not hard crash the app.

p.s.
I've used the `LinearGradient` in combination with a `Circle`
```ts
<Circle
  r={circleDiameter}
  strokeWidth={strokeWidth}
  strokeDasharray="45 200"
  strokeDashoffset="-55"
  transform={{ rotation: 63 }}
  fill="none"
  stroke="url(#gradient0)"
  strokeLinecap="round"
/>
```

**Comment by msand** [comment]
Released in v10
