### ISSUE TITLE
SVG with uri rendering larger than container and are cropped

### ISSUE THREAD

**Issue by SirCameron** [react-native-community/react-native-svg#1202]
# Bug
SvgUri is rendering the SVG but not containing it within the size specified.

## Environment info
React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.15.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 311.12 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 28
        Build Tools: 22.0.1, 23.0.1, 23.0.3, 25.0.2, 26.0.1, 26.0.3, 28.0.1, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: ^0.59.8 => 0.59.10
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-app-id: 0.0.5
      react-native-git-upgrade: 0.2.7
```

Library version: x.x.x

## Steps To Reproduce
```
<SvgCssUri width="100px" height="100px" uri={source} />
or
<SvgUri width="100px" height="100px" uri={source} />
```

I'd like for the SVG to be contained within the size specified, otherwise what's the point.
Currently the image is cropped. The screenshot below should be of the linux penguin.
<img width="348" alt="Screenshot 2019-11-28 at 08 57 23" src="https://user-images.githubusercontent.com/74608/69787625-34c46a00-11bd-11ea-84d4-405994e91c7b.png">

## Reproducible sample code
see above

**Comment by msand** [comment]
Look up the viewBox attribute in the svg standard, you need to set that to make it scale instead of clip

**Comment by SirCameron** [comment]
This is using a URI, though.

**Comment by SirCameron** [comment]
@msand is there a way to override the width and height of an SVG when using SvgUri?

**Comment by msand** [comment]
@SirCameron Isn't it enough to give it as a prop to SvgUri ?

**Comment by tonuegbu** [comment]
I'm having this issue as well

**Comment by RyanCommits** [comment]
I'm having the same challenge. I can't figure out how to scale down a large svg image to fit a small container. Anyone know how to scale a svg like this? https://upload.wikimedia.org/wikipedia/commons/b/b8/Coat_of_Arms_of_Francisco_Franco_as_Head_of_the_Spanish_State_%28Order_of_Charles_III%29.svg

**Comment by msand** [comment]
Did you try using viewBox?
width="100%" height="100%" viewBox="0 0 662.35413 900.45941"

**Comment by RyanCommits** [comment]
> Did you try using viewBox?
> width="100%" height="100%" viewBox="0 0 662.35413 900.45941"

Sure, that works, but then the smaller SVG's rendered in the same way are too small. Is there a way to dynamically control the viewbox based on each individual SVG? Like somehow detect the height and width metadata and pass in a dynamically generated viewbox?

I'm trying to create a solution that renders any svg in a given container, where small SVG's would retain their size, but large SVG's too big for its container would be scaled down and retain its aspect ratio. The container is 100% width and maxHeight 350px.

**Comment by msand** [comment]
Well, the viewBox (and preserveAspectRatio) attribute is supposed to be defined by the author of the svg file. Would need to wrap the content in a G element and add a onLayout handler to it to find the size of the content, but that wouldn't tell you how much extra space there needs to be for it to look the way the author intended. I see no other way than having a per file viewBox defined by the author.

**Comment by SirCameron** [comment]
> Did you try using viewBox?
> width="100%" height="100%" viewBox="0 0 662.35413 900.45941"

As I mentioned before, this is using a URI, not a local SVG file.

**Comment by msand** [comment]
Well the viewBox attribute is supposed to contain this information, if it doesn't and no width/height information either, it's more of an issue with the file not being possible to render as intended, independent of svg viewer.

**Comment by msand** [comment]
Alternatively, you can measure the size of the content, and decide some arbitrary amount of margin you want, and transform the content to fit inside your default / requested size.

**Comment by vpress-kieran** [comment]
> Alternatively, you can measure the size of the content, and decide some arbitrary amount of margin you want, and transform the content to fit inside your default / requested size.

Hi, I'm also facing a similar issue where the format of the SVG is all over the place, some don't have viewboxes and some do but still get cropped. How would you achieve what you're talking about here. I'm just trying to display an external SVG in a container with some padding so width="100%" and height="100%"

**Comment by laygir** [comment]
Same situation here, I've width/height/viewbox in place but in Android, masked svg visuals are having this issue. It works fine on iOS.

**Comment by almeidapaulooliveira** [comment]
Same situation here! If you're rendering different SVGs with different `viewbox`, sizes, etc. this component is useless.
