### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Druux** [react-native-community/react-native-svg#121]
Hey guys!

I know the svg animations are currently part of the todo list.
Are there some workarounds available though?
I tried to get animations working with react's `AnimatedImplementation` without success.

**Comment by mattvot** [comment]
I've successfully implemented an inefficient SVG animation by using an `Animated.Value` and animating that using the React Native normal Animated methods.

I then hooked into the changing values by adding an event listener to the value. On each value change you set the state with some style properties that allow the re-rendering of the SVG with the new style.

As said this is inefficient, is noticeable on Android (iOS seems find though...) and is definitely not a long term solution.

**Comment by gorangajic** [comment]
Will `Animated.createAnimatedComponent` work?

http://browniefed.com/react-native-animation-book/api/CREATEANIMATEDCOMPONENT.html

**Comment by flaviotobi** [comment]
I didn't work for me :/

**Comment by Introvertuous** [comment]
@mattvot Did you try wrapping the svg with an Animated.View. I have has some success with that.  example (note it is smooth on device, gif is a bit choppy):

```
class Blarg extends React.Component {
  constructor (props) {
    super(props);
    this.state = {
      scale: new Animated.Value(0)
    }
    this.animate = this.animate.bind(this);
  }

  componentDidMount() {
    this.animate();
  }

  animate() {
    Animated.sequence([
      Animated.timing(this.state.scale,
        {
          toValue:1,
          duration:2000
        }),
      Animated.timing(this.state.scale,
        {
          toValue:0,
          duration:2000
        })
    ]).start(this.animate)
  }

  render () {
    return (
      <View>
        <Animated.View style={{transform:[{scale:this.state.scale}]}}>
        <Svg height="100" width="100">
          <Path x='50' y='60' d="M23.70-49.04Q33.40-49.04 39.45-42.10Q45.49-35.16 45.49-23.98Q45.49-12.80 39.45-5.89Q33.40 1.02 23.70 1.02Q13.99 1.02 7.89-5.91Q1.79-12.83 1.79-23.98Q1.79-35.16 7.89-42.10Q13.99-49.04 23.70-49.04M23.70-43.00Q19.76-43.00 17.88-38.34Q16.00-33.68 16.00-23.98Q16.00-14.17 17.86-9.56Q19.72-4.96 23.70-4.96Q27.63-4.96 29.48-9.53Q31.32-14.10 31.32-23.98Q31.32-33.75 29.46-38.37Q27.60-43.00 23.70-43.00Z" stroke="red"/>
        </Svg>
        </Animated.View>
      </View>
    )
  }
}
```
![](https://lh3.googleusercontent.com/MQYstbZgt0nPxWYbc_iXAwtx960kZaZHTri2faTJI_Ib8URekz8jUtTbdZA2fh5laaBax-RJo1mbJvIVUcCLFGwdPvVo4cvC-q54yUAB8XVdqA75Pj__vb_x6JiBlxKrnyzqlFyI5x1b9BYrX4YCQHhH2x3wKRpHGcApYeIHnLhpIl1KKJjJz3MQYeGtkovLn9cUl2OOd80ZxIcJ0KKuHfO751JLkojxzbeqFYHWlIyNK-Th2fM-hN5Ado7s4Djav5s3t1gu3QkEqv_LNUNw-mgz6vjr1WeoIeZLPEk3VZZtf7mRoGSUbA3yV4XAiMR0vt8OQl6Zthm0tf2CPzzQDzzOJVE4MAnecuaIFnuAlNtSSmyWJlS9qnpGHFpj8yuxYLu5zmBBrxf9tUZmRi7fpkXjNjv0OifjUWCFyKzaMnhUiGl_2HXXecztAFAc5bNv-bXoNtXghXN4xKKljCdzCl3QeG62zd0JF6A7jJ6MJ37WhcGZrxhtIGv12lIPkJdWBVB5skxLpEGzoMJZ7psoiOJWDCGPS6U01MNONQSAhJNwC3WvhKAdkihWV6VY5IPeWSpgZnn7wDzzAB_47IgoRkR-O0zjNorWPxGxlqeZFxKqeaas=w956-h200-no)

**Comment by henrikra** [comment]
@Introvertuous Can you reupload that gif? It is not working for me :)

**Comment by Introvertuous** [comment]
That gif is gone I believe but I have better examples that use the same idea. I do not have the source up at the moment but I did make a [blog post](https://medium.com/@introvertuouso/from-stranger-things-to-react-native-f2434b3773a7) about it a while back, and could go into more details if you would like.
![](https://cdn-images-1.medium.com/max/800/1*Oj6tGMBlj1i5LkdIh7UFYg.gif)

**Comment by dannycochran** [comment]
@Introvertuous I can't tell from your blog post how you animate individual SVG elements. the code snippet above wraps the entire SVG container in an Animated.View -- is it possible to wrap things like Rect / Circle, etc?

**Comment by Introvertuous** [comment]
I am not entirely sure if you can but I was able to achieve that animation by just using a single path (or rect, circle, etc) per svg. [Here](https://github.com/Introvertuous/react_native_animated/blob/master/src/sliding_text/index.js) is the source for it.

**Comment by dannycochran** [comment]
@Introvertuous got it - you create an SVG per element and wrap each SVG in an animated view. seems like a decent workaround, thanks!

**Comment by joshuapinter** [comment]
Has anybody figured out how to do this without wrapping in an animated view? 

I'm trying to adjust the radius of a circle (without scaling it via styles) and it's giving me an error. The reason why this is important is that I later want to adjust the start and end points of a Line element, which I can't use style transformations for. 

Here's what I'm currently running into:

```javascript
// var AnimatedCircle = Animated.createAnimatedComponent(Circle); <-- Done before.

<AnimatedCircle cx="250" cy="250" r={this.state.circleRadius} fill="black" />
```

With the following animation on mount:

```javascript
// this.state.circleRadius = 50 <-- Starting value

Animated.spring(
  this.state.circleRadius,
  { toValue: 100, friction: 3 }
).start();
```

And getting the following error: 

![screenshot 2017-03-03 11 00 44](https://cloud.githubusercontent.com/assets/180819/23562678/b1fdeaae-0000-11e7-9d72-5802f79487a1.png)

**Comment by theaidem** [comment]
@joshuapinter the `r` value must be a string, thy this:
```
r={this.state.circleRadius.toString()}
```

**Comment by joshuapinter** [comment]
@theaidem Are you sure? I'm using an decimal value, like`4.5`, when I'm statically setting the `r` prop.

**Comment by theaidem** [comment]
@joshuapinter Just try, I 'am sure 😃

**Comment by joshuapinter** [comment]
@theaidem So, I still couldn't get the `r` value of my circle to be animated, but I did a bit more tinkering and found a very workable solution using `addListener` and `setNativeProps`. A little messy but works none-the-less and is quite performant.

Here's a simplified version of the solution: 

```js
constructor(props) {
  super(props);
  
  this.state = { circleRadius: new Animated.Value(50) };

  this.state.circleRadius.addListener( (circleRadius) => {
    this._myCircle.setNativeProps({ r: circleRadius.value.toString() });
  });

  setTimeout( () => {
    Animated.spring( this.state.circleRadius, { toValue: 100, friction: 3 } ).start();
  }, 2000)
}

render() {
  return(
    <Svg height="400" width="400">
      <AnimatedCircle ref={ ref => this._myCircle = ref } cx="250" cy="250" r="50" fill="black" />
    </Svg>
  )
}
```

And the resulting animation: 

![circle animation with setnativeprops](https://cloud.githubusercontent.com/assets/180819/26133954/58709c78-3a68-11e7-8fb0-26cd7103417f.gif)

And this is being rendered on a very complex component where using `setState` isn't fluid at all.

**Comment by tanaka0x** [comment]
I tried to avoid ```addListener``` and ```setNativeProps```.
My solution is wrapping Components(Rect, Circle) using HOC.
```js
import Svg, { Rect, Circle, } from 'react-native-svg'

const wrap = (Cmp) => {
  return class Wrapped extends Component {
    render() {
      return <Cmp {...this.props} />
    }
  }
}
const AnimRect = Animated.createAnimatedComponent(wrap(Circle))
```

https://gist.github.com/tanaka0x/a614c7e88dc3dda86545120ea7bc9601

This is more simple but is less performant than ```setNativeProps```.

**Comment by octopitus** [comment]
I'm using `setNativeProps` for this animation. The problem is, performance very good on emulator but really terrible on real device.

![](http://i.imgur.com/INUbc2G.gif)

**Comment by msand** [comment]
Hmm, wrapping seems unnecessary at this point. Check e.g. this: https://snack.expo.io/@msand/zoomablesvg-with-childprops,-constrain-and-animation
Or something in the style of this:
```jsx
import React, { Component } from 'react';
import { Dimensions, Animated } from 'react-native';
import { Svg } from 'expo';

const { G, Rect } = Svg;

const { width, height } = Dimensions.get('window');
const AnimatedRect = Animated.createAnimatedComponent(Rect);

class SvgRoot extends Component {
  state = {
    initAnim: new Animated.Value(0),
  };

  componentDidMount() {
    Animated.timing(
      // Animate over time
      this.state.initAnim,
      {
        toValue: 1,
        duration: 3000,
        useNativeDriver: false,
      }
    ).start();
  }

  render() {
    const { initAnim } = this.state;
    const translateRectY = initAnim.interpolate({
      inputRange: [0, 1],
      outputRange: ['0', '50'],
    });
    const { transform } = this.props;
    return (
      <Svg width={width} height={height}>
        <G transform={transform}>
          <AnimatedRect
            y={translateRectY}
            x="5"
            width="90"
            height="90"
            fill="rgb(0,0,255)"
            strokeWidth="3"
            stroke="rgb(0,0,0)"
          />
        </G>
      </Svg>
    );
  }
}
```

**Comment by msand** [comment]
I've added support for animation of transforms using the same syntax as react-native views now: https://github.com/react-native-community/react-native-svg/issues/803#issuecomment-428815111
And also for any number accepting properties. Any help in testing the latest commit in the master branch would be much appreciated!
