### ISSUE TITLE
Make clickable TextPath

### ISSUE THREAD

**Issue by kiril-me** [react-native-community/react-native-svg#1211]
# Question
I have the TextPath in a circle. The `onPressed` works if you press the text counter directly. For example, if I  press inside 'O', it doesn't work. 

How can I get a correct clickable text (like button)? Might extend the clickable zone, one of the problems is that text lies on the path.

Example:
```
<Svg width={325} height={325}>
  <Path id="circle" fill="none"
    d="M 165,325 a 155,155 0 0,1 0,-310a 155,155 0 0,1 0,310Z" />
  <Text fill="red">   
    <TextPath 
      href="#circle"
      startOffset={0}>Click me if you can</TextPath>
  </Text>
</Svg>
```

**Comment by msand** [comment]
i would recommend making a transparent circle behind the content to handle the touchable area by placing the event handler on that, either determine the needed size beforehand, or use onLayout / the bounds apis to find out what size it needs to be.

**Comment by nishaQueppelin** [comment]
I am also facing the same issue
