### ISSUE TITLE
Feature: filter, feFlood and feBlend

### ISSUE THREAD

**Issue by intitec** [react-native-community/react-native-svg#1216]
# Feature: filter, feFlood and feBlend

Hi there, 

I am writting here because I need these features. 
I want to do these, but I would like to be introduced. I don't know the procedures for doing this.
Any help is very useful to me.

**Comment by msand** [comment]
Hello! Thanks for being available to work on this. There are prototypes for ios in the filters branch and the latest version of that is in the filters_rebase branch: https://github.com/react-native-community/react-native-svg/tree/filters_rebase

There's some work done for android as well: https://github.com/react-native-community/react-native-svg/issues/150#issuecomment-542387098

And there are several other react-native libraries to take inspiration from: https://github.com/react-native-community/react-native-svg/issues/150#issuecomment-485544124

There are some other useful links in that thread as well, e.g. to browser implementations, and various apis on android and ios. You can probably start by looking at the diff between the filters_rebase branch, and the master branch: https://github.com/react-native-community/react-native-svg/compare/filters_rebase

And then start creating native components for android. Feel free to ask any questions, no matter if it feels stupid or not, I can give advice and guidance along the way as long as you keep working on it. 

Probably easier to work from the filters_rebase branch, I someone starts working actively on this, then I can handle rebasing it onto the latest developments in the master and develop branch, mostly just adding typescript types to the new svg filter components.

**Comment by Ashalbulk** [comment]
Any updates or plans here?

**Comment by K123Ritesh** [comment]
Is there any chances that these Components will come in react-native-svg package ?? @msand

**Comment by jakex7** [comment]
Hey @K123Ritesh, you can track the filter progress here: https://github.com/software-mansion/react-native-svg/issues/2362, `feFlood` as well as `feBlend` have already been done and are available in newer versions of `react-native-svg`

**Comment by K123Ritesh** [comment]
Okay thanks @jakex7
