### ISSUE TITLE
Enable display svg prop

### ISSUE THREAD

**Issue by morellan** [react-native-community/react-native-svg#1220]
# Feature Request

The SVG spec specifies a `display` prop that is not currently used in `react-native-svg`

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display

## Why it is needed

I'm using SvgCssUri and sometimes the remote SVG comes with a `display="none"` prop that is not handled and is displaying the hidden elements.

Here is an example of the SVG: https://res.cloudinary.com/nivelat-staging/image/upload/v1517432918/vehiculo-parte-freno_iiy2fv.svg

The problematic part of that SVG is this:
```SVG
<g id="Capa_1" display="none">
	<g display="inline">
		<circle fill="none" stroke="#1D1D1B" stroke-width="0.5" stroke-miterlimit="10" cx="50" cy="50" r="50.03"/>
		<rect x="6.474" y="6.474" fill="none" stroke="#1D1D1B" stroke-width="0.5" stroke-miterlimit="10" width="87.053" height="87.053"/>
		<circle fill="none" stroke="#1D1D1B" stroke-width="0.5" stroke-miterlimit="10" cx="50" cy="50" r="43.526"/>
	</g>
</g>
```

Here is how it's displayed on Web
<img src="https://i.ibb.co/0VjHpJz/svg-web.png" width="100" height="100" />

And here is how it's displayed on Mobile
<img src="https://i.ibb.co/MRyZ2nk/svg-mobile.jpg" width="100" height="100" />

## Possible implementation

I fixed it by adding the display prop to the `extractProps` method and returning null when a group has that prop, but I guess it should be implemented on every shape.

https://github.com/morellan/react-native-svg/commit/80c09fcdf0bf0f73290244afdfb5298ef462ecc8

**Comment by msand** [comment]
Can you try with the latest commit from the develop branch?

**Comment by msand** [comment]
Released in v10
