### ISSUE TITLE
Export animation as gif

### ISSUE THREAD

**Issue by Maxoos** [react-native-community/react-native-svg#1224]
# Question

Is there a way to export an SVG what has Native animations (with the animation library) to a gif file? Would rendering include animations?

Thanks!

**Comment by msand** [comment]
If you control the animation, such that you render a specific value/frame of the animation, take a screenshot, change the animated values, take another screenshot, etc. Then you could probably ensure that all frames get rendered correctly and nothing extra. And, then you use some gif encoder to create the actual file.
