### ISSUE TITLE
Text color doesn't work with inlineSize

### ISSUE THREAD

**Issue by codelayerorg** [react-native-community/react-native-svg#1225]
Hi there, I can't get fill color working along side with inlineSize. When I set inlineSize, applied fill color is always black no matter the color I set. Any workaround for this?

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 143.74 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 9.13.6

## Steps To Reproduce

1. Just place a TSpan tag and set inlineSize and fill properties

Sample code

```
<SvgText x={0} y={0} fontSize={20}>
      <SvgTSpan inlineSize={"100%"} fill={"#FF0000"}>
      Testing word-wrap... Testing word-wrap... Testing word-wrap... Testing word-wrap... 
      </SvgTSpan>
</SvgText>
```

Red color should be applied to text. Unfortunately that's not what happens.

**Comment by msand** [comment]
Can you try with the latest commit from the develop branch?

**Comment by msand** [comment]
```jsx
import React from 'react';
import {Svg, Text, TSpan} from 'react-native-svg';

export default () => {
  return (
    <Svg width="100%" height="100%">
      <Text x={0} y={20} fontSize={20}>
        <TSpan inlineSize="100%" fill="#FF0000">
          Testing word-wrap... Testing word-wrap... Testing word-wrap... Testing
          word-wrap...
        </TSpan>
      </Text>
    </Svg>
  );
};

```

**Comment by msand** [comment]
Released in v10

**Comment by shafayeatsumit** [comment]
@msand  the example you gave doesn't work when I try to add text stroke and inline size.
```
  <Svg width="100%" height="100%">
    <SvgText
      x={0}
      y={20}
      fontSize={20}
      fill="white"
      stroke="purple"
      fontWeight="bold"
      textAnchor="middle">
      <TSpan x="10" inlineSize="400">
        {persianText}
      </TSpan>
    </SvgText>
  </Svg>
```
