### ISSUE TITLE
SvgUri TypeError: (0 , _react.useState) is not a function

### ISSUE THREAD

**Issue by Ahmed-Imam** [react-native-community/react-native-svg#1226]
The react-native-svg is working fine with 
```
"react": "16.6.1",
"react-native": "^0.59.0",
"react-native-svg": "^9.13.6",
```
except when I try using the SvgUri 
```
    <SvgUri
       width={20}
       height={30}
       uri="http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg"/>
```

<img width="456" alt="Screen Shot 2019-12-28 at 4 59 33 AM" src="https://user-images.githubusercontent.com/20854551/71532657-5a18d500-292f-11ea-872d-5db6d08fb744.png">

**Comment by msand** [comment]
Can you try with SvgFromUri instead of SvgUri ?

**Comment by Ahmed-Imam** [comment]
> Can you try with SvgFromUri instead of SvgUri ?

I confirm, it is working as expected with SvgFromUri.
