### ISSUE TITLE
createElement to unstable_createElement in react-native-web

### ISSUE THREAD

**Issue by cheekw** [react-native-community/react-native-svg#1228]
## Issue
When attempting to run the web app I got the following error.

Failed to compile.
./node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js
Attempted import error: 'createElement' is not exported from 'react-native-web'.

## Workaround

modified the file:
./node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js

from
```import { createElement } from `react-native-web'```
to
```import { unstable_createElement as createElement } from `react-native-web'```

## Versions
"react": "16.11.0"
"react-native": "0.61.5"
"react-native-svg": "9.13.6",
"react-native-web": "0.12.0-rc.1"

## Reference
https://github.com/necolas/react-native-web/issues/1385

**Comment by yulolimum** [comment]
Here's a patch file for anyone looking to implement the above workaround without forking (to be used with `patch-package`:

Patch file name: react-native-web+0.12.0-rc.1.patch
Patch file contents: 
```
diff --git a/node_modules/react-native-web/dist/index.js b/node_modules/react-native-web/dist/index.js
index 9d7bbb6..7fa016c 100644
--- a/node_modules/react-native-web/dist/index.js
+++ b/node_modules/react-native-web/dist/index.js
@@ -1,4 +1,4 @@
-export { default as unstable_createElement } from './exports/createElement';
+export { default as createElement } from './exports/createElement';
 export { default as findNodeHandle } from './exports/findNodeHandle';
 export { default as processColor } from './exports/processColor';
 export { default as render } from './exports/render';

```

**Comment by msand** [comment]
Ah, great, would you mind making a pr?

**Comment by msand** [comment]
@zoontek @cheekw @yulolimum mind taking a look at this? https://github.com/react-native-community/react-native-svg/issues/1274

**Comment by zoontek** [comment]
@msand Using `import { GestureResponderEvent, unstable_createElement as createElement } from 'react-native';` will drop support for RN-Web < 0.12, but I'm totally OK with that.

**Comment by msand** [comment]
Yeah, can make the semver change a major one, it'll coincidentally make it v12 which aligns relatively nicely with rn-web 0.12

**Comment by msand** [comment]
This has been released, closing.
