### ISSUE TITLE
How can I render QR Code on a PDF?

### ISSUE THREAD

**Issue by iCHAIT** [react-native-community/react-native-svg#1229]
I need to render a QR code on a PDF which my end-user can download. FOr creating the pdf I am using [`react-pdf/renderer`](https://www.npmjs.com/package/@react-pdf/renderer).

Here is my code - 

```javascript
import React from "react";
import {Page, Text, View, Document, StyleSheet, Image} from "@react-pdf/renderer";
import { QRCode } from "react-qr-svg";


export function PdfDocument(props) {
    return (
        <Document>
        <Page size="A4">    
          <View>
            <Text>Section #1</Text>
          </View>
          <View>
            <Text>Section #2</Text>
            <QRCode
                bgColor="#FFFFFF"
                fgColor="#000000"
                level="Q"
                style={{ width: 256 }}
                value="some text"
            />
          </View>
        </Page>
      </Document>
    );
}
```

The above gives me the following error - 

`Error: Invalid element of type rect passed to PDF renderer`

What I am doing wrong? How can I render a QR code on the fly onto a PDF?

**Comment by gino8080** [comment]
why closed? did you solved?

**Comment by msand** [comment]
Wrong repository, that question belongs in react-pdf and/or react-qr-svg

**Comment by ChengLam123** [comment]
Have you solved this issue ? i'm facing this problem now

**Comment by iCHAIT** [comment]
HI @ChengLam123 

I solved it, but I guess there is no native way to solve it. I kind of did a dirty hack.

I laid out the HTML code and used a Qr Code generator ([like this one](http://goqr.me/api/)), to render a QRcode in the HTML itself. Later, I converted the HTML to pdf.

**Comment by msand** [comment]
You can also use toDataUrl to get a png base64 string, and then put that inside a pdf
https://github.com/react-native-community/react-native-svg/issues/855#issuecomment-538351261

**Comment by msand** [comment]
Also here: https://github.com/magicismight/react-native-svg-example/blob/master/examples/Svg.js#L153-L185
