### ISSUE TITLE
"Don't call PropTypes" warning

### ISSUE THREAD

**Issue by boygirl** [react-native-community/react-native-svg#123]
I'm encountering [this warning](https://facebook.github.io/react/warnings/dont-call-proptypes.html). 

This library makes my life a lot easier! I'm happy to take on this issue if it would help you out.

**Comment by dubert** [comment]
👍

**Comment by magicismight** [comment]
This is not active for a long time, I'm closing this now.
It seems like it has been fixed in latest `react-native`.
If this still exists plz feel free to reopen this.
