### ISSUE TITLE
[Web] SvgUri is not exported

### ISSUE THREAD

**Issue by Jekiwijaya** [react-native-community/react-native-svg#1230]
# Bug
https://github.com/react-native-community/react-native-svg/blob/master/src/ReactNativeSVG.web.ts

curerntly there's no class SvgUri is exported like in react native

Library version: react-native-svg@9.13.3:

**Comment by msand** [comment]
It's not completely clear which of the possible processing mode should be used on the web: https://www.w3.org/TR/SVG/conform.html#examples

You can make your own SvgUri.js and SvgUri.web.js , and import SvgUri from there. This way you get to decide what security and interactivity tradeoffs you need for you specific content.

**Comment by msand** [comment]
https://vecta.io/blog/best-way-to-embed-svg
https://www.sitepoint.com/add-svg-to-web-page/

**Comment by Jekiwijaya** [comment]
Thank you, it's worked!
