### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by kopax** [react-native-community/react-native-svg#1234]
Is this lib still maintained ? The example is broken on both Androis/iOS and web.

What is the current way of loading an svg in react-native + web ?

Thanks and best!

**Comment by msand** [comment]
Updated the example a bit, can you try again: https://snack.expo.io/@msand/react-native-svg-example

The best way depends a bit on the use case. It the content is static, then I would recommend using react-native-svg-transformer with plain .svg files. If you need dynamic content, then you can import the elements from react-native-svg and create normal react components. They should work in react-native, react-native-web and plain react-dom (requires aliasing react-native-web to react instead) based projects.

**Comment by kopax** [comment]
Thanks for updating the example. Many of the example from the `README.md`, produce error, such as non existing `SvgCss` `SvgXml` imported from `react-native-svg`. 

I was not able to import from a `.svg` files, even if I did `expo install react-native-svg`. 

What worked the best for me was recreating the svg in react with `Path` from `react-native-svg`.

I have found that `animateTransform` was not existing in the library while I wanted to use my svg for the splash screen and the animation is required to make it spin.

Why are some imports not defined from the main library? If possible I'd like to repair the import so i can do the animation.

**Comment by kopax** [comment]
This is an example of error I have when importing svg on the web:

```
bundle.js:69367 Warning: </static/media/splashScreen.0f923900.svg /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    in /static/media/splashScreen.0f923900.svg (at SplashScreen/index.js:34)
```

**Comment by msand** [comment]
Seems more like it's react-native-svg-transformer related issue, or naming issue. Are you trying to use SvgCss / SvgXml in an Expo web project? They aren't defined for the web yet, as there are several processing modes to choose from, and you can easily implement your own: https://github.com/react-native-community/react-native-svg/issues/1230

**Comment by kopax** [comment]
Yes I was using it for the web. But that was a fallback decision, after I noticed that `Platform.OS` from `react-native-web` in expo sdk36 was always pointing to web, even if started on the expo client from an iPhone or Android. 

Otherwise, if the import of the `.svg` would work for the web, by work I mean importing a `ReactComponent` instead of showing a `path` string.
