### ISSUE TITLE
importing .svg does not work on the web, Warning: </static/media/splashScreen.0f923900.svg /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

### ISSUE THREAD

**Issue by kopax** [react-native-community/react-native-svg#1235]
I have installed in my project `expo install react-native-svg`.

I have exported the svg as a component by doing:

```jsx
import Logo from './logo.svg';
export default Logo;
```

It can render on native but fail on the web.

    bundle.js:69367 Warning: </static/media/splashScreen.0f923900.svg /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

I have followed that configuration https://github.com/react-native-community/react-native-svg#use-with-svg-files

My `metro.config.js` is equal:

```jsx
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

My `app.json` got added 

```diff
{
+    "packagerOpts": {
+      "config": "metro.config.js",
+      "sourceExts": ["js", "jsx", "ts", "tsx", "svg"]
+    },
}
```

- react-native-svg 9.13.3
- react-native-svg-transformer 0.14.3
- SDK: 36 Documentation: https://docs.expo.io/versions/latest/sdk/svg/

**Comment by kopax** [comment]
As soon as I import a svg file, I have a bunch of error when running with jest:

```javascript
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: number.

    Check the render method of `_default`.
        in _default (created by App)
        in View (created by View)
        in View (created by App)
        in App".



      at BufferedConsole.error (node_modules/@jest/console/build/BufferedConsole.js:163:10)
      at BufferedConsole.console.error (node_modules/react-native/Libraries/YellowBox/YellowBox.js:104:22)
      at BufferedConsole.error (node_modules/expo/build/environment/muteWarnings.fx.js:29:17)
      at warningWithoutStack (node_modules/react/cjs/react.development.js:167:32)
      at warning (node_modules/react/cjs/react.development.js:638:27)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2035:5)
      at _default (src/icimatin/Logo/index.js:134:88)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6156:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8690:13)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10058:16)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at parseErrorStack (node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:8:26)
      at createStack (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxWarning.js:113:10)
      at Function.parse (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxWarning.js:28:16)
      at Object.add (node_modules/react-native/Libraries/YellowBox/Data/YellowBoxRegistry.js:110:50)
      at registerWarning (node_modules/react-native/Libraries/YellowBox/YellowBox.js:158:23)

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "The above error occurred in the <_default> component:
        in _default (created by App)
        in View (created by View)
        in View (created by App)
        in App

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.".

      at BufferedConsole.error (node_modules/@jest/console/build/BufferedConsole.js:163:10)
      at BufferedConsole.console.error (node_modules/react-native/Libraries/YellowBox/YellowBox.js:104:22)
      at BufferedConsole.error (node_modules/expo/build/environment/muteWarnings.fx.js:29:17)
      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11958:13)
      at logError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11995:5)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13345:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3728:12)
      at commitUpdateEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3766:7)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3756:3)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12275:11)


```

**Comment by msand** [comment]
@kristerkari Any suggestions?

**Comment by kopax** [comment]
I am currently preparing a reproduction that can be pulled

**Comment by kopax** [comment]
So I did just a blank project with `expo init` (sdk36), following expo instruction you normally don't need to do anything else than `expo install react-native-svg`. But doing this in the blank project didn't work.

I added `metro.config.js` and the jest configuration (without the .svg mocks), and I am not even able to reinstall like I was. It just does not work. I have pushed the blank project here:

- https://github.com/kopax/expo-bug-reports/tree/issue-6660 (this branch was created from a branch called `with-jest` created from `expo init` blank project)
- Branch failing when importing `.svg`: https://www.travis-ci.org/kopax/expo-bug-reports/builds/632083659

**Comment by kopax** [comment]
This is quite blocking for doing web.

I have prepared a reproduction here:

- https://github.com/kopax/expo-bug-reports/tree/issue-6660
- https://www.travis-ci.org/kopax/expo-bug-reports/builds/632112598

There are two issues:

1. web require of svg does not return a component (it return for example `data:image/svg+xml;base64,ICA8c3ZnIGhlaWdodD0iMTAwJSIgd2lkdGg9IjEwMCUiPgogICAgPHJlY3QgZmlsbD0ibGltZSIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgLz4KICA8L3N2Zz4=`)
2. jest unit testing does not return a component (instead an integer and `Platform.OS === 'ios'`)


- jest

**Comment by msand** [comment]
It seems all those issues are related to expo and react-native-svg-transformer, and not a single one of them seems related to this library. You can use the base64 encoded datauri string as the href attribute of e.g. img elements https://css-tricks.com/lodge/svg/09-svg-data-uris/

So just make your Logo.web.js somethine like

```jsx
import logoDataUri from 'test.svg';
export default () => <img href={logoDataUri} />;
```

and your Logo.js

```jsx
import Logo from 'test.svg';
export default Logo;
```

**Comment by kopax** [comment]
That is probably true and thank you for the recommendation.

I know how I can use but I would like to have the same behavior as with `@svgr/webpack`.

This obviously exist and importing a component in the web should follow without tweak. I will use the tweak for the moment. 

Thanks @msand!

**Comment by kopax** [comment]
I have tried to replace `Logo/index.js`:

```jsx
import React from 'react';
import { Platform } from 'react-native';
import Logo from './logo.svg';

export default (props) => Platform.OS === 'web' ?
  <img alt="logo" width="76" height="39" src={Logo} /> :
  <Logo accessibilityLabel="Logo" width="76" height="39" {...props} />;

```
With `Logo/index.js`:

```jsx
import React from 'react';
import Logo from './logo.svg';

export default (props) => <Logo accessibilityLabel="Logo" width="76" height="39" {...props} />;

```

And  `Logo/index.web.js`:
```jsx
import React from 'react';
import Logo from './logo.svg';

export default (props) => <img alt="logo" width="76" height="39" src={Logo} {...props} />;

```

And I still have : 

```
bundle.js:69381 The above error occurred in the </static/media/logo.0e5dcfee.svg> component:
    in /static/media/logo.0e5dcfee.svg (at Logo/index.js:4)
    in Unknown (at SplashScreen/index.js:42)
    in div (created by View)
```

**Comment by msand** [comment]
Seems like a webpack configration issue. Impossible to say without any source or even the actual error message.

**Comment by kopax** [comment]
The whole trace:

```
bundle.js:69381 The above error occurred in the </static/media/logo.0e5dcfee.svg> component:
    in /static/media/logo.0e5dcfee.svg (at Logo/index.js:4)
    in Unknown (at SplashScreen/index.js:42)
    in div (created by View)
    in View (at NativeLinearGradient.web.js:54)
    in NativeLinearGradient (at LinearGradient.js:12)
    in LinearGradient (at SplashScreen/index.js:36)
    in div (created by View)
    in View (at SplashScreen/index.js:30)
    in SplashScreen (at src/index.js:91)
    in div (created by View)
    in View (at src/index.js:89)
    in App (at withExpoRoot.web.js:13)
    in RootErrorBoundary (at withExpoRoot.web.js:12)
    in ExpoRootComponent (at registerRootComponent.web.js:6)
    in RootComponent
    in div (created by View)
    in View (created by AppContainer)
    in div (created by View)
    in View (created by AppContainer)
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, RootErrorBoundary.
console.<computed> @ bundle.js:69381
error @ bundle.js:12210
logCapturedError @ bundle.js:43029
logError @ bundle.js:43066
update.payload @ bundle.js:44433
getStateFromUpdate @ bundle.js:34830
processUpdateQueue @ bundle.js:34953
updateClassInstance @ bundle.js:35707
updateClassComponent @ bundle.js:39606
beginWork$1 @ bundle.js:41372
beginWork$$1 @ bundle.js:46942
performUnitOfWork @ bundle.js:45881
workLoopSync @ bundle.js:45857
performSyncWorkOnRoot @ bundle.js:45456
(anonymous) @ bundle.js:33385
unstable_runWithPriority @ bundle.js:64315
runWithPriority$2 @ bundle.js:33335
flushSyncCallbackQueueImpl @ bundle.js:33380
flushSyncCallbackQueue @ bundle.js:33368
scheduleUpdateOnFiber @ bundle.js:44895
enqueueSetState @ bundle.js:35180
../../../react/cjs/react.development.js.Component.setState @ bundle.js:60372
onFinish @ bundle.js:1621
_callee$ @ bundle.js:12370
tryCatch @ bundle.js:62440
invoke @ bundle.js:62666
prototype.<computed> @ bundle.js:62492
tryCatch @ bundle.js:62440
invoke @ bundle.js:62530
(anonymous) @ bundle.js:62540
Promise.then (async)
invoke @ bundle.js:62539
(anonymous) @ bundle.js:62565
callInvokeWithMethodAndArg @ bundle.js:62564
enqueue @ bundle.js:62587
prototype.<computed> @ bundle.js:62492
../../../regenerator-runtime/runtime.js.exports.async @ bundle.js:62611
_callee @ bundle.js:12313
componentDidMount @ bundle.js:12394
commitLifeCycles @ bundle.js:43287
commitLayoutEffects @ bundle.js:46530
callCallback @ bundle.js:21522
invokeGuardedCallbackDev @ bundle.js:21571
invokeGuardedCallback @ bundle.js:21626
commitRootImpl @ bundle.js:46268
unstable_runWithPriority @ bundle.js:64315
runWithPriority$2 @ bundle.js:33335
commitRoot @ bundle.js:46108
finishSyncRender @ bundle.js:45515
performSyncWorkOnRoot @ bundle.js:45493
scheduleUpdateOnFiber @ bundle.js:44884
updateContainer @ bundle.js:48289
(anonymous) @ bundle.js:48714
unbatchedUpdates @ bundle.js:45619
legacyRenderSubtreeIntoContainer @ bundle.js:48713
render @ bundle.js:48794
renderApplication @ bundle.js:50454
run @ bundle.js:50347
runApplication @ bundle.js:50386
registerRootComponent @ bundle.js:12701
../../../expo/AppEntry.js @ bundle.js:8398
__webpack_require__ @ bundle.js:727
fn @ index.js:70
0 @ bundle.js:73866
__webpack_require__ @ bundle.js:727
(anonymous) @ bundle.js:794
(anonymous) @ bundle.js:797
Show 36 more frames
bundle.js:69381 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/logo.0e5dcfee.svg') is not a valid name.
    at createElement (http://192.168.0.16:19006/static/js/bundle.js:29001:34)
    at createInstance (http://192.168.0.16:19006/static/js/bundle.js:30655:20)
    at completeWork (http://192.168.0.16:19006/static/js/bundle.js:42265:28)
    at completeUnitOfWork (http://192.168.0.16:19006/static/js/bundle.js:45919:16)
    at performUnitOfWork (http://192.168.0.16:19006/static/js/bundle.js:45892:12)
    at workLoopSync (http://192.168.0.16:19006/static/js/bundle.js:45857:22)
    at performSyncWorkOnRoot (http://192.168.0.16:19006/static/js/bundle.js:45456:11)
    at http://192.168.0.16:19006/static/js/bundle.js:33385:24
    at unstable_runWithPriority (http://192.168.0.16:19006/static/js/bundle.js:64315:12)
    at runWithPriority$2 (http://192.168.0.16:19006/static/js/bundle.js:33335:10)
    at flushSyncCallbackQueueImpl (http://192.168.0.16:19006/static/js/bundle.js:33380:7)
    at flushSyncCallbackQueue (http://192.168.0.16:19006/static/js/bundle.js:33368:3)
    at scheduleUpdateOnFiber (http://192.168.0.16:19006/static/js/bundle.js:44895:9)
    at Object.enqueueSetState (http://192.168.0.16:19006/static/js/bundle.js:35180:5)
    at App.../../../react/cjs/react.development.js.Component.setState (http://192.168.0.16:19006/static/js/bundle.js:60372:16)
    at Object.onFinish (http://192.168.0.16:19006/static/js/bundle.js:1621:27)
    at _callee$ (http://192.168.0.16:19006/static/js/bundle.js:12370:29)
    at tryCatch (http://192.168.0.16:19006/static/js/bundle.js:62440:40)
    at Generator.invoke [as _invoke] (http://192.168.0.16:19006/static/js/bundle.js:62666:22)
    at Generator.prototype.<computed> [as next] (http://192.168.0.16:19006/static/js/bundle.js:62492:21)
    at tryCatch (http://192.168.0.16:19006/static/js/bundle.js:62440:40)
    at invoke (http://192.168.0.16:19006/static/js/bundle.js:62530:20)
    at http://192.168.0.16:19006/static/js/bundle.js:62540:13
```

It happen in the browser, I have not touch the webpack configuration and I don't have any. I use expo sdk 36 and I have not ejected. Isn't this supposed to work out of the box with react-native?  

Just to know what I am looking for, may I see your webpack configuration?

**Comment by msand** [comment]
I'm not involved in the development of expo. You should probably ask there instead @EvanBacon ?

react-native doesn't have any support for svg. Therefore this library exists. But, this library doesn't include handling of svg files, merely rendering react-components which consist of svg elements, and strings of xml content. react-native-svg-transformer handles loading .svg files, and requires configuration. It seems you're asking these questions in the wrong places. These are beginner mistakes with react, react-native, expo, webpack etc., not issues or bugs with this library. Please do not burn out open source maintainers with noise which doesn't belong in the specific repositories they maintain.

https://facebook.github.io/react-native/docs/platform-specific-code#platform-specific-extensions

**Comment by msand** [comment]
I'm not using any .svg files in any expo web project at the moment. So I have no such example to show you as I haven't even attempted to do what you're doing. Expo has a default metro / webpack configuration, but it's not my expertise, and completely unrelated to this library.

you can use:
File.js
File.web.js
File.ios.js
File.android.js
File.windows.js
File.native.js
File.future.platform.js
File.custom.test.e2e.js
File.jest.js

and do this in e.g. ExtraFile.js:
```jsx
import File from './file'
export default () => <File with="extra stuff" />
```

and it'll use the platform specific one depending on what you've made available and how you've configured metro / webpack / rollup / other web bundlers you've chosen to use.

**Comment by kristerkari** [comment]
I'm sorry, but I don't have experience of how Expo's Web rendering works. 

There is this SVG example app that I have created, which also has a Webpack config to run the same code in a browser:
https://github.com/kristerkari/react-native-svg-example

**Comment by msand** [comment]
@kopax Here's an example showing how to use react-native-svg-transformer with expo and next.js https://github.com/msand/barboraxuexpo/commit/1001b31587bab230c9f5465ffd1042ea4e269261

**Comment by kopax** [comment]
Wow thanks.

Looking at your example, I already have equal diff for:

- `app.json`
- `metro.config.js`, except with those difference, it is relevant to change or your is a bit older?

```diff
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
+      getTransformOptions: async () => ({
+        transform: {
+          experimentalImportSupport: false,
+          inlineRequires: false,
+        },
+      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

You have a `next.config.js` that I don't have that use `withExpo` and `withTranspileModules`, how can I implement the same in `webpack.config.js` ?

**Comment by msand** [comment]
Well I've shown you how to do it in a project that uses webpack already, and I'm not part of the Expo support team, and certainly it's possible to do with expo already as you can see in that repo. Please study webpack and expo in detail and ask them instead. This discussion does not belong in this repository.

**Comment by msand** [comment]
The fact that you get a uri instead of a react component means that you already have configured how to handle .svg files. You should just use that uri with a export default () => <img href={uri} />

**Comment by kopax** [comment]
> The fact that you get a uri instead of a react component means that you already have configured how to handle .svg files. You should just use that uri with a `export default () => <img href={uri} />`

That's what I am already dont but the api is then different. We can't edit the svg with js.


> Please study webpack and expo in detail and ask them instead. 

Already dis and they do not want to answer

> This discussion does not belong in this repository.

Fair enough, thanks for string to help.

**Comment by pors** [comment]
> The fact that you get a uri instead of a react component means that you already have configured how to handle .svg files. You should just use that uri with a `export default () => <img href={uri} />`

For anyone going this path (like I did), make sure to use `src` instead of `href`.

**Comment by ahmedabosamra1981** [comment]
Please, check the following

https://github.com/expo/expo/issues/6660#issuecomment-573506912

**Comment by jkoutavas** [comment]
Here's how I'm configured to do React Native plus React Native Web .svg file loading, using the `react-native-svg-transformer` and `@svgr/webpack` packages allowing for same import / use on both mobile and web. The SVGs are also resizable and can have their fill color changed (if you do no fill in the .svg)

## metro.config.js

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require('metro-config');

module.exports = async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
};
```

## web pack.config.js (excerpt)

```
...
const svgLoaderConfiguration = {
  test: /\.svg$/i,
  issuer: /\.[jt]sx?$/,
  use: [{ loader: '@svgr/webpack', options: { typescript: true, dimensions: false } }],
};
...
```

## Example use

```
import AppLogo from './assets/AppLogo.svg';
...
<AppLogo fill={'green'} width={100} height={100} />
```

**Comment by YqxLzx** [comment]
> Here's how I'm configured to do React Native plus React Native Web .svg file loading, using the `react-native-svg-transformer` and `@svgr/webpack` packages allowing for same import / use on both mobile and web. The SVGs are also resizable and can have their fill color changed (if you do no fill in the .svg)
> 
> ## metro.config.js
> ```
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> const { getDefaultConfig } = require('metro-config');
> 
> module.exports = async () => {
>   const {
>     resolver: { sourceExts, assetExts },
>   } = await getDefaultConfig();
> 
>   return {
>     transformer: {
>       babelTransformerPath: require.resolve('react-native-svg-transformer'),
>       getTransformOptions: async () => ({
>         transform: {
>           experimentalImportSupport: false,
>           inlineRequires: false,
>         },
>       }),
>     },
>     resolver: {
>       assetExts: assetExts.filter(ext => ext !== 'svg'),
>       sourceExts: [...sourceExts, 'svg'],
>     },
>   };
> };
> ```
> 
> ## web pack.config.js (excerpt)
> ```
> ...
> const svgLoaderConfiguration = {
>   test: /\.svg$/i,
>   issuer: /\.[jt]sx?$/,
>   use: [{ loader: '@svgr/webpack', options: { typescript: true, dimensions: false } }],
> };
> ...
> ```
> 
> ## Example use
> ```
> import AppLogo from './assets/AppLogo.svg';
> ...
> <AppLogo fill={'green'} width={100} height={100} />
> ```

Excuse me , if my project have no webpack.config.js , what should i do ?

**Comment by tomislav-arambasic** [comment]
> Here's how I'm configured to do React Native plus React Native Web .svg file loading, using the `react-native-svg-transformer` and `@svgr/webpack` packages allowing for same import / use on both mobile and web. The SVGs are also resizable and can have their fill color changed (if you do no fill in the .svg)
> 
> ## metro.config.js
> ```
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> const { getDefaultConfig } = require('metro-config');
> 
> module.exports = async () => {
>   const {
>     resolver: { sourceExts, assetExts },
>   } = await getDefaultConfig();
> 
>   return {
>     transformer: {
>       babelTransformerPath: require.resolve('react-native-svg-transformer'),
>       getTransformOptions: async () => ({
>         transform: {
>           experimentalImportSupport: false,
>           inlineRequires: false,
>         },
>       }),
>     },
>     resolver: {
>       assetExts: assetExts.filter(ext => ext !== 'svg'),
>       sourceExts: [...sourceExts, 'svg'],
>     },
>   };
> };
> ```
> 
> ## web pack.config.js (excerpt)
> ```
> ...
> const svgLoaderConfiguration = {
>   test: /\.svg$/i,
>   issuer: /\.[jt]sx?$/,
>   use: [{ loader: '@svgr/webpack', options: { typescript: true, dimensions: false } }],
> };
> ...
> ```
> 
> ## Example use
> ```
> import AppLogo from './assets/AppLogo.svg';
> ...
> <AppLogo fill={'green'} width={100} height={100} />
> ```

Thanks! `dimensions: false` was the key to success.
https://react-svgr.com/docs/options/

**Comment by Imagemapcanned** [comment]
Take a look at this https://csser.space/questions/utilize-an-svg-to-function-as-a-block-level-element
