### ISSUE TITLE
Adding example of using native view with Mask

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/react-native-svg#1237]
# Feature Request

Hi @msand 

I just see the new release, Thanks for that. I just wanted to try the new feature, but I didn't succeed so I should misusing it.

It would be great if you add an example to `Mask` section in ReadMe.md file. 

## Why it is needed

It helps users to understand how it should be used, like the other examples.

### Code sample

here is what I tried

https://snack.expo.io/@saeedzhiany/using-native-view-with-mask

```js
import React from 'react';
import {View, Image, Text} from 'react-native';
import {
  Svg,
  G,
  Circle,
  Defs,
  LinearGradient,
  Mask,
  Rect,
  Stop,
} from 'react-native-svg';

export default () => {
  return (
    <View style={{flex: 1, justifyContent: 'center'}}>
      <Svg height="50%">
        <Defs>
          <LinearGradient
            id="Gradient"
            gradientUnits="userSpaceOnUse"
            x1="0"
            y1="0"
            x2="800"
            y2="0">
            <Stop offset="0" stopColor="white" stopOpacity="0" />
            <Stop offset="1" stopColor="white" stopOpacity="1" />
          </LinearGradient>
          <Mask
            id="Mask"
            maskUnits="userSpaceOnUse"
            x='0'
            y='0'
            width="800"
            height="300">
            <Rect x="0" y="0" width="800" height="300" fill="url(#Gradient)" />
          </Mask>
        </Defs>
        <G mask="url(#Mask)">
          <Circle x={50} y={70} r={65} />
          <G transform="translate(200, 100)">
            <Text>Some Text</Text>
          </G>
        </G>
      </Svg>
    </View>
  );
};
```

**Comment by msand** [comment]
Check here: https://github.com/react-native-community/react-native-svg/issues/1232#issuecomment-570684345

**Comment by SaeedZhiany** [comment]
Can you take a look at this?
https://snack.expo.io/@saeedzhiany/nested-native-view-test

I'm not sure if it's a normal and correct result or not. it seems like #880

**Comment by msand** [comment]
Can you try the latest commit from the develop branch? Btw, I have to open the dev menu for it to rerender correctly on ios. You had used x and y instead of cx and cy on the circle, causing different outputs on ios/android for some reason.

```jsx
import React from 'react';
import {View, Text, Image} from 'react-native';
import {
  Svg,
  G,
  Circle,
  Defs,
  LinearGradient,
  Mask,
  Rect,
  Stop,
} from 'react-native-svg';

export default () => {
  return (
    <View style={{flex: 1, justifyContent: 'center'}}>
      <Svg height="50%">
        <Defs>
          <LinearGradient
            id="Gradient"
            gradientUnits="userSpaceOnUse"
            x1="0"
            y1="0"
            x2="800"
            y2="0">
            <Stop offset="0" stopColor="white" stopOpacity="0.2" />
            <Stop offset="1" stopColor="white" stopOpacity="1" />
          </LinearGradient>
          <Mask
            id="Mask"
            maskUnits="userSpaceOnUse"
            x="0"
            y="0"
            width="800"
            height="300">
            <Rect x="0" y="0" width="800" height="300" fill="url(#Gradient)" />
          </Mask>
        </Defs>
        <G mask="url(#Mask)">
          <Circle cx={50} cy={70} r={65} />
          <G transform="translate(50, 50)">
            <View style={{width: 200, height: 400, flex: 1}}>
              <Image
                style={{width: 200, height: 200}}
                source={{
                  uri: 'https://picsum.photos/200/200',
                }}
              />
            </View>
            <G transform="translate(50, 50)">
              <View style={{transform: []}}>
                <Text style={{color: 'blue'}}>Testing</Text>
                <Text style={{color: 'green'}}>Testing2</Text>
              </View>
            </G>
          </G>
        </G>
      </Svg>
    </View>
  );
};

```

<img width="1680" alt="Screenshot 2020-01-04 at 16 36 04" src="https://user-images.githubusercontent.com/1131362/71767068-54635680-2f10-11ea-92ae-65a52c5df17e.png">

**Comment by msand** [comment]
Oh and these changes aren't available on snack until expo release a new version of their native bundle.

**Comment by msand** [comment]
@SaeedZhiany Would you be interested in attempting to implement foreignObject?
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

It would essentially be the same as the intersection of MaskView and SymbolView, i.e., extends GroupView with the x, y, width and height properties. 

That's actually the way this should be used. Such that we can make it work the same in web and native.

**Comment by msand** [comment]
GroupView already has the correct rendering logic as of now. So it shouldn't require any new algorithms / logic. 

So for js:
 a new .js file (can copy Mask.js to ForeignObject.js and remove the mask specific parts)

android:
a new ForeignObjectView.java (copy MaskView.java, remove mask specific parts), 
add a ViewManager inside RenderableViewManager.java, (copy MaskManager, remove mask specific...)

ios:
a new RNSVGForeignObject.h copy RNSVGMask.h
a new RNSVGForeignObject.m copy RNSVGMask.m
a new RNSVGForeignObjectManager.h copy RNSVGMaskManager.h
a new RNSVGForeignObjectManager.m copy RNSVGMaskManager.m

**Comment by SaeedZhiany** [comment]
@msand 

Just for sure, Have you noticed the output result on iOS has the same problem on #880?

| iOS | Android |
|-----|----------|
| ![image](https://user-images.githubusercontent.com/13766432/71775635-1bbb8f80-2f99-11ea-94e9-1bafb0e37d68.png) | ![image](https://user-images.githubusercontent.com/13766432/71775648-7523be80-2f99-11ea-8e3e-e3e15bbf036f.png)|

Do you want to put this comment on #880 to trace it there?

**Comment by SaeedZhiany** [comment]
@SaeedZhiany Would you be interested in attempting to implement foreignObject?

Yeah, I'll be happy to collaborate with you and your amazing library as much as I can. I'm not so familiar with Objective-C or Swift language (however, I can learn, so no problem) but I'm OK with java, so is there any specific iOS implementation detail that I should know about it in your code?

I'm busy today, so I'll start coding tomorrow.

**Comment by SaeedZhiany** [comment]
@SaeedZhiany Would you be interested in attempting to implement foreignObject?

Yeah, I'll be happy to collaborate with you and your amazing library as much as I can. I'm not so familiar with Objective-C or Swift language (however, I can learn, no problem) but I'm OK with java, so is there any specific iOS implementation detail that I should know about it in your code?

I'm busy today, so I'll start coding tomorrow.
I'll apply everything you said in [this comment](https://github.com/react-native-community/react-native-svg/issues/1237#issuecomment-570793772)

**Comment by SaeedZhiany** [comment]
> @SaeedZhiany Would you be interested in attempting to implement foreignObject?

Yeah, I'll be happy to collaborate with you and your amazing library as much as I can. I'm not so familiar with Objective-C or Swift language (however, I can learn, no problem) but I'm OK with java, so is there any specific iOS implementation detail that I should know about it in your code?

I'm busy today, so I'll start coding tomorrow.
I'll apply everything you said in [this comment](https://github.com/react-native-community/react-native-svg/issues/1237#issuecomment-570793772)

**Comment by msand** [comment]
Oh, I wonder what makes that happen, I guess it calls render on the element more than once, or then react-native / the os calls render on it independently of the code here.
Objective-c shouldn't pose much challenge, might be some quirks in xcode, have to have the correct folder selected when you want to create a new file (right click a file in the folder you want to make it in > new file), for it to be added to the project and filesystem in the correct places.
Objective-c is very similar to c or c++ with a touch of smalltalk added to it.
Main difference in syntax to java is probably that you call methods on (send messages to) objects with what looks a bit like array syntax, so when you would have something like this in java:

```java
    static class SomeSubClass extends SomeSuperClass {
        SomeSubClass(){
            super();
        }

        public void someMethod(SomeType someParameter, AnotherType anotherParameter) {
            // use someParameter and anotherParameter here
        }
    }

    // and use it somewhere like this:
    someObj.someMethod(someArg, anotherArgument);
```

then in obj-c you would do something like this:

```obj-c
@implementation SomeSubClass

+ (void)someMethod:(SomeType)someParameter withAnother:(AnotherType)anotherParameter
{
  // use someParameter and anotherParameter here
}

@end

// and use it somewhere 
[someObj someMethod:someArg withAnother:anotherArgument];
```

So you can have spaces in method names. Message handlers can be overridden at runtime, but that should be avoided whenever possible.

Then there's c-like memory allocation, and automatic reference counting (ARC), no garbage collector. But these shouldn't be too important for most of the code in the library / these types of changes.

**Comment by SaeedZhiany** [comment]
> Oh, I wonder what makes that happen, I guess it calls render on the element more than once, or then react-native / the os calls render on it independently of the code here.

What about Android's result? it seems the nested Text within SVG is disappeared (or even not rendered)
however, I'll test it on my project tomorrow, maybe it because of the library's version on expo as you said.

Also, Thanks for your guidance.

**Comment by SaeedZhiany** [comment]
> a new .ts file (can copy Mask.ts to ForeignObject.ts and remove the mask specific parts, rename / search & replace Mask with ForeignObject)

@msand 
I can't find `Mask.ts` file, are you mean `Mask.tsx`?

**Comment by msand** [comment]
Ah, yeah that's correct

**Comment by SaeedZhiany** [comment]
Also in js side, it extends from `Shape`, not `G`. is it necessary to change it?

**Comment by msand** [comment]
You can change it to G instead yes, good catch!

**Comment by SaeedZhiany** [comment]
For That, We also need to change `G` class to get a generic type and then pass it to `Shape`. I did it but I'm getting some kind of error that I don't know what is saying. I'm going to submit a draft PR to move this discussion there.

**Comment by SaeedZhiany** [comment]
[The PR](https://github.com/react-native-community/react-native-svg/pull/1242) has been created
