### ISSUE TITLE
Invisible Marker

### ISSUE THREAD

**Issue by losh11** [react-native-community/react-native-svg#1239]
Markers are invisible when used at the end of a Path. 

This is what I see... (ignore the grey lines at the back)
<img width="216" alt="Screenshot 2020-01-05 at 12 03 22" src="https://user-images.githubusercontent.com/2608570/71779915-61855180-2fb3-11ea-9df7-63a389c7ca1d.png">

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 185.77 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 9.13.6

## Steps To Reproduce

Using exactly the same as the README for <Marker />

```
<Svg width="400" height="200" viewBox="0 0 4000 2000">
  <Defs>
    <Marker
      id="Triangle"
      viewBox="0 0 10 10"
      refX="0"
      refY="5"
      markerUnits="strokeWidth"
      markerWidth="4"
      markerHeight="3"
      orient="auto"
    >
      <Path d="M 0 0 L 10 5 L 0 10 z" />
    </Marker>
  </Defs>
  <Rect
    x="10"
    y="10"
    width="3980"
    height="1980"
    fill="none"
    stroke="blue"
    strokeWidth="10"
  />
  <Path
    d="M 1000 750 L 2000 750 L 2500 1250"
    fill="none"
    stroke="black"
    strokeWidth="100"
    markerEnd="url(#Triangle)"
  />
</Svg>
```

Describe what you expected to happen:

1. There's meant to be a triangle marker at the end of the line.

**Comment by msand** [comment]
<img width="1680" alt="Screenshot 2020-01-05 at 17 56 25" src="https://user-images.githubusercontent.com/1131362/71782607-b68d8b80-2fe4-11ea-99f9-627299e3d41a.png">

Seems to work fine, are you using the latest version? (v10)
