### ISSUE TITLE
Every component is accessible / focusable on web

### ISSUE THREAD

**Issue by zoontek** [react-native-community/react-native-svg#1244]
# Bug

Hi 👋

After `10.0.0` update, every component on the web version is now `accessible` by default, unless you add `accessible={false}` on each one. It seems extreme and I don't think this is the wanted behavior (if not handled, it makes keyboard navigation a nightmare).

It' probably due to https://github.com/react-native-community/react-native-svg/blob/v10.0.0/src/ReactNativeSVG.web.ts#L104
If `accessible` is not set, it will be equal to `undefined !== false`, which is `true`.

If indeed that's not the wanted behavior, I can create a PR to remove this line or assert `accessible` to a boolean only if it's set.

<img width="1268" alt="Screenshot 2020-01-07 at 18 45 10" src="https://user-images.githubusercontent.com/1902323/71916260-dc9a6380-317d-11ea-8453-ee36dbb2f50a.png">

## Environment info

```bash
"react-native-svg": "10.0.0"
"react-native-web": "0.11.7"
```

Library version: 10.0.0

## Steps To Reproduce

1. Init a project with `create-react-app` and `react-native-web`
2. Add `react-native-svg` `10.0.0` dependency and add a random SVG using it

## What you expected to happen

1. SVG elements should not be accessible and focusable by default.
2. SVG elements should be accessible and focusable if `accessible={true}` is set

**Comment by msand** [comment]
Hello! Yeah, most certainly this was an unintentional regression from copy-pasting too much from react-native-web without thinking enough, a pr would be much appreciated!

**Comment by zoontek** [comment]
@msand Done: https://github.com/react-native-community/react-native-svg/pull/1245
