### ISSUE TITLE
Animated API rotation around the center, just like using originX and originY without animation

### ISSUE THREAD

**Issue by angelos3lex** [react-native-community/react-native-svg#1248]
# Question
 How can i use the animated API to rotate a line around an originX, originY point, just like i would do using:
```
 rotation: angle, originX: someX, originY: someY
```
where angle would be a continuously changing state to act like animation.

I have opened a more detailed question [here in SO](https://stackoverflow.com/questions/59694548/whats-the-equivalent-of-react-native-svg-rotation-with-origins-using-react-nati) , but i didn't have any luck yet.
Any help is really appreciated!

**Comment by msand** [comment]
Can you try these: https://github.com/react-native-community/react-native-svg/issues/857
https://github.com/react-native-community/react-native-svg/issues/940

**Comment by msand** [comment]
This seems to work quite fine: https://snack.expo.io/@msand/vengeful-strawberries

```jsx
import React, { Component } from 'react';
import {
  Text,
  View,
  StyleSheet,
  Animated,
  Platform,
  Dimensions,
} from 'react-native';
import { Svg, Path, Rect, G, Circle } from 'react-native-svg';

const AnimatedPath = Animated.createAnimatedComponent(Path);
const AnimatedG = Animated.createAnimatedComponent(G);
const { width } = Dimensions.get('window');

export class TestLogo extends Component {
  state = {
    rotation: new Animated.Value(0),
    offset: 0,
  };

  componentDidMount() {
    Animated.loop(
      Animated.timing(this.state.rotation, {
        useNativeDriver: true,
        duration: 3000,
        toValue: 1,
      })
    ).start();
  }

  onLayout =
    Platform.OS === 'android'
      ? a => {
          this.setState({ offset: a.nativeEvent.layout.width / 2 });
        }
      : null;

  render() {
    const offsetAndroid = this.state.offset;
    const [pivotX, pivotY] = [25, 25];
    return (
      <Svg
        width="100%"
        height="100%"
        onLayout={this.onLayout}
        viewBox={`0 0 50 50`}>
        <Rect width="50" height="50" />
        <G transform={`translate(${pivotX}, ${pivotY})`}>
          <Circle r="5" fill="white" />
          <AnimatedG
            style={{
              transform: [
                { translateX: -offsetAndroid },
                {
                  rotate: this.state.rotation.interpolate({
                    inputRange: [0, 1],
                    outputRange: ['0deg', '360deg'], // I would like to set pivot point at 25 25
                  }),
                },
                { translateX: offsetAndroid },
              ],
            }}>
            <AnimatedPath
              fill="#FFF"
              d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z"
              transform={`translate(-${pivotX} -${pivotY})`}
            />
          </AnimatedG>
        </G>
      </Svg>
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <TestLogo />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by angelos3lex** [comment]
@msand Thanks a LOT! This is working. I'm trying to understand the reason of translating X and Y by (+-)width / 2 and why this should only be the case on android. Is there some reference to it somewhere?

**Comment by msand** [comment]
I haven't investigated that properly, but has something to do with how react-native makes ios and android behave more similarly, ios has the transform origin in the center of the bounds, while the web and android have it in the top left by default, and the handling of transforms thus has some kind of translation to the center coordinate system, but it seems it only handles the width, not the height. I think it might relate to the layout system as well, at the initial rendering essentially all views (at least with flex and column direction) have zero height, but some finite width. I haven't dug deep enough to discover the actual reason, in that case i probably would have fixed it already.

**Comment by msand** [comment]
I've fixed the issue with the android specific translations in the develop branch? Would you mind testing that?

**Comment by msand** [comment]
@msageryd @wcandillon I guess both of you would be interested in this simplification. Would you mind testing the develop branch?

https://github.com/react-native-community/react-native-svg/pull/1250/commits/db682f87bc8c89f1cf72c7fcdcb4970041679214

**Comment by angelos3lex** [comment]
@msand using the `v9.13.3` in my case it worked without setting the offsets, for both android and ios. I'll update with some code reference for you until friday, just in case it helps you understand better the reason.

**Comment by angelos3lex** [comment]
@msand Sorry for the delay. Below is my code:
```
render() {
        let height = this.state.height;
        let width = this.state.width;
        let [pivotX, pivotY] = [0, 0];
        if (height && width) {
            [pivotX, pivotY] = [width / 2, height / 2];
        }
       return (
            <View
                style={{ flex: 1}}
                onLayout={event => {
                    this.findDimesions(event.nativeEvent.layout); // find height and width dynamically
                }}
            >
                {height !== undefined && width !== undefined && (
                    <Svg height={height} width={width} style={{ alignItems: "center" }}>
                       <G transform={`translate(${pivotX}, ${pivotY})`}>
                            <AnimatedG
                                style={{
                                    transform: [
                                        {
                                            rotate: this.state.angle.interpolate({
                                                inputRange: [0, 360],
                                                outputRange: [`0deg`, `360deg`]
                                            })
                                        }
                                    ]
                                }}
                            >
                                <NeedlePath
                                    transform={`translate(-${pivotX} -${pivotY})`}
                                    d={`M ${width * 0.5} ${height * 0.5} L${width * 0.5 + width * 0.25} ${height * 0.5 + height * 0.25}`}
                                    fill={Colors.black}
                                    stroke={Colors.black}
                                />
                            </AnimatedG>
                        </G>
                    </Svg>
                )}
            </View>
        );
    }
```
And the animation is normally done like this:
```
Animated.timing(this.state.angle, {
            toValue: 240, // degrees
            duration: 1000,
            useNativeDriver: true
        }).start();
```

while NeedlePath and AnimatedG are:
```
const NeedlePath = Animated.createAnimatedComponent(Path);
const AnimatedG = Animated.createAnimatedComponent(G);
```

What is crucial and eliminates the need for `translations`, is the `style={{ alignItems: "center" }}` property. Maybe I'm lucky and this works ok because my pivot point is on the center of the container, so when this gets combined with the above style i have the perfect mix. :P I hope that helps...

**Comment by sueLan** [comment]
These tricky codes are for setting the anchor point or called pivot point of a view. 
    
```js
          translateX: -w / 2
          translateY: -h / 2
          rotateZ
          translateX: w / 2
          translateY: h / 2
```

This means setting the anchor point as (0, 0)
    
```js
          translateX: w / 2
          translateY: h / 2
          rotateZ
          translateX: -w / 2
          translateX: -h / 2
```
This means setting the anchor point as (1, 1)
  
In iOS, it is called anchor point. [About the anchorPoint](http://ronnqvi.st/about-the-anchorpoint) 

```objective-c
layer.anchorPoint = CGPointMake(0, 0)

```

In Android, it is called pivot point. 

```java
  viewToMove.setPivotX(0);
  viewToMove.setPivotX(0);
```

**Comment by msand** [comment]
Correct, in css it's called transform-origin, and the css-transforms module has this to say:

https://www.w3.org/TR/css-transforms-1/#svg-transform-functions
> The SVG transform function rotate with 3 values can not be mapped to a corresponding CSS `<transform-function>`. The 2 optional number values represent a horizontal translation value cx followed by a vertical translation value cy. Both number values get interpreted as CSS <length> types with px units and define the origin for rotation. The behavior is equivalent to an initial translation by cx, cy, a rotation defined by the first number value interpreted as `<angle>` type with deg unit followed by a translation by -cx, -cy.

Svg 2 says amongst other things this:
https://svgwg.org/svg2-draft/coords.html#InitialCoordinateSystem
> 8.4. The initial coordinate system
> For the outermost svg element, the SVG user agent must determine an initial viewport coordinate system and an initial user coordinate system such that the two coordinates systems are identical. The origin of both coordinate systems must be at the origin of the SVG viewport, and one unit in the initial coordinate system must equal one CSS 2.1 px ([CSS2], section 4.3.2) in the SVG viewport. In stand-alone SVG documents and in SVG document fragments embedded (by reference or inline) within parent documents where the parent's layout is determined by CSS [CSS2], the initial viewport coordinate system (and therefore the initial user coordinate system) must have its origin at the top/left of the viewport, with the positive x-axis pointing towards the right, the positive y-axis pointing down, and text rendered with an "upright" orientation, which means glyphs are oriented such that Roman characters and full-size ideographic characters for Asian scripts have the top edge of the corresponding glyphs oriented upwards and the right edge of the corresponding glyphs oriented to the right.

And Svg 1.1 has this:

https://www.w3.org/TR/SVG11/coords.html#TransformAttribute
> `rotate(<rotate-angle> [<cx> <cy>])`, which specifies a rotation by <rotate-angle> degrees about a given point.
> If optional parameters `<cx>` and `<cy>` are not supplied, the rotate is about the origin of the current user coordinate system. The operation corresponds to the matrix [cos(a) sin(a) -sin(a) cos(a) 0 0].
> If optional parameters `<cx>` and `<cy>` are supplied, the rotate is about the point (cx, cy). The operation represents the equivalent of the following specification: **`translate(<cx>, <cy>) rotate(<rotate-angle>) translate(-<cx>, -<cy>)`**.

> If a list of transforms is provided, then the net effect is as if each transform had been specified separately in the order provided. For example,
> 
> ```svg
> <g transform="translate(-10,-20) scale(2) rotate(45) translate(5,10)">
>   
> </g>
> ```
> is functionally equivalent to:
> 
> ```svg
> <g transform="translate(-10,-20)">
>   <g transform="scale(2)">
>     <g transform="rotate(45)">
>       <g transform="translate(5,10)">
>         
>       </g>
>     </g>
>   </g>
> </g>
> ```

**Comment by kumarajay0412** [comment]
here i have explained the solution https://medium.com/@ajay19293/rotate-an-image-around-any-point-in-react-react-native-b882753ce22e
