### ISSUE TITLE
setNativeprops on a View in SVG does not work 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-native-community/react-native-svg#1258]
# Bug
```
<Svg>
    <View ref={ref} />
</Svg>
```
 `ref.setNativeProps()`  was working in v9.5.1 but not working in v11.0.1

**Comment by msand** [comment]
Can you make a full reproduction?

**Comment by mikeaustin** [comment]
I'm trying to use setNativeProps() on a Ellipse, but it doesn't exist. I'm using react-native-web and the latest react-native-svg (12.1). I just noticed this question was about a ref to a View inside Svg, but still curious.

**Comment by noldidrita** [comment]
**setNativeProps** seems not to be support on WebShape (which is the substitute for Shape on Web and that has setNativeProps implemented).

@msand I would gladly help out with implementing it (if help is needed) as I'm interested in getting it to work. However, I'd need some guidance first
