### ISSUE TITLE
Max Width

### ISSUE THREAD

**Issue by tanabs18** [react-native-community/react-native-svg#126]
Is there a max size on the Svg component? I can't seem to get it any larger than 1365, and I was wondering why this is (or if there's anything I can do to get rid of the restriction).

**Comment by iSimonWeb** [comment]
Darn, I found out this bug too right now. Seems there's a critical performance issue with large graphics, even with a simple Circle and its RadialGradient fill (as in my case).

**Comment by louiechristie** [comment]
+1

Defect found on Sony Z3 Android phone.
Defect not present on Samsung S7 phone.

**Comment by jacklj** [comment]
+1  On iOS Simulator

**Comment by msand** [comment]
Use a device with more memory available, or decrease the size of your canvas, the bytes need to be stored somewhere.
