### ISSUE TITLE
gesture not recognition when svg was empty?

### ISSUE THREAD

**Issue by ruandao** [react-native-community/react-native-svg#1260]
# Question

the panResponder: 

    private _panResponder = PanResponder.create({
        // Ask to be the responder:
        onStartShouldSetPanResponder: (evt, gestureState) => true,
        onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
        onMoveShouldSetPanResponder: (evt, gestureState) => true,
        onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

        onPanResponderGrant: (evt, gestureState) => {
        },
        onPanResponderMove: (evt, gestureState) => {
            this.setState({time: new Date().getTime()});         // look here
        },
        onPanResponderTerminationRequest: (evt, gestureState) => false,
        onPanResponderRelease: (evt, gestureState) => {
        },
        onPanResponderTerminate: (evt, gestureState) => {
        },
    });

the render content:

    <Svg viewBox="0 0 2000 2000"
                 {...this._panResponder.panHandlers}
                 onLayout={(event) => {
                     this.setState({layout: event.nativeEvent.layout});
                 }}
                 style={{
                     width: "100%",
                     height: "100%",
                 }}
            >
                <SVGText x={200} y={100}>
                    {JSON.stringify(this.state)}
                </SVGText>
    </Svg>

when i move my finger in `Svg` the `onPanResponderMove` was not fired, 
but if there are some content full fill in the Svg, the  `onPanResponderMove`  can fired

**Comment by msand** [comment]
Can you make a full reproduction?

**Comment by ruandao** [comment]
sorry because my project was ending,  i solve this by other methods, and now i forget the detail of the issue
