### ISSUE TITLE
ForeignObject not working on ios/android

### ISSUE THREAD

**Issue by guiguithub** [react-native-community/react-native-svg#1261]
Hello,

I'm trying to use the ForeignObject component in my expo project but it returns me this error below
I wanted to use this component in order to display non-svg components like Text/TextInput in svg tags.

## React native info output:

![image](https://user-images.githubusercontent.com/43378069/73003929-ba077c00-3e06-11ea-8d38-79a1570379f3.png)

Library version: react-native-svg@11.0.1

## Sample code

here is the code i'm trying to run :

http://pastebin.fr/60472

Is it possible to check why this error is happening ?
Thank you very much for your help

**Comment by msand** [comment]
Not sure if expo has any of the versions including ForeignObject yet.

**Comment by JoBerkner** [comment]
I have the exact same issue with Expo. 
@msand 

> Not sure if expo has any of the versions including ForeignObject yet.

What do you mean by that? The react-native-svg version? I just removed my pm cache, installed react-native-svg again and I can see that in my and the nodes_module's `package.json` file the version is 12.1.0. But I still get the same error as @guiguithub . Not sure what to do...

**Comment by JoBerkner** [comment]
I got it... Somehow instead of importing it this way:
`import { Circle, ForeignObject } from 'react-native-svg';`

I need to import it this way:
`import ForeignObject, { Circle } from 'react-native-svg';`

**Comment by tran-simon** [comment]
> I need to import it this way: `import ForeignObject, { Circle } from 'react-native-svg';`

You are not importing `ForeignObject`, you are importing the default export of `react-native-svg`, which is the `Svg` object

So in your code, `ForeignObject` is just an alias for `Svg`
