### ISSUE TITLE
Android : Path is not rendering in Android version 6.0

### ISSUE THREAD

**Issue by rahulje9** [react-native-community/react-native-svg#1269]
# Bug

I'm making a knob to adjust the heater temperature. There is a dotted ring around the knob which indicates the temperature level using gradient colours. I'm using Path to render that, everything works fine in android version 6.0 above and ios.

Knob with ring
![Screenshot 2020-02-01 at 9 19 48 PM](https://user-images.githubusercontent.com/22475675/73594994-7664ee80-4539-11ea-890f-17664dbfb422.png)
Knob without ring
![Screenshot 2020-02-01 at 9 20 00 PM](https://user-images.githubusercontent.com/22475675/73594995-76fd8500-4539-11ea-9f01-c622cb9c7b80.png)

testing on emulator Nexus 6p 6.0 and Nexus 6p 9.0

## Environment info
I'm using
 "react-native": "0.61.5",
"react-native-svg": "^11.0.1",
Describe what you expected to happen:

1. A ring should appear around the knob
2. Ring not getting rendered around the knob

## Reproducible sample code

    const paths = gradientColors.map((color, index) => (
        <Path
            key={`dot${color}`}
            d={ /*path data points*/ }
            stroke={index < value * gradientColors.length ? color : inactiveColor}
            strokeWidth={DOT_SIZE}
            strokeDasharray={[0, (2 * Math.PI * RADIUS) / gradientColors.length]}
            strokeLinecap="round"
            fill="transparent"
        />

    return (
        <Svg height={size} width={size} viewBox={`0 0 ${VIEWBOX_SIZE} ${VIEWBOX_SIZE}`}>
            {paths}
        </Svg>
    );

**Comment by msand** [comment]
Seems to work fine: https://snack.expo.io/rJfMXr!VI
The example is not nearly sufficient to investigate this properly. Closing.

```jsx
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { Svg, Path } from 'react-native-svg';

const gradientColors = ['green', 'blue'];
const paths = gradientColors.map((color, index) => (
  <Path
    key={color}
    d="M0,0L100,100"
    stroke={color}
    strokeWidth={5}
    strokeDasharray={[0, (2 * Math.PI * 5) / gradientColors.length]}
    strokeLinecap="round"
    fill="transparent"
    style={{ transform: [{ translateY: index * 20 }] }}
  />
));

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg height="100%" width="100%" viewBox={`0 0 100 100`}>
          {paths}
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by rahulje9** [comment]
> Seems to work fine: https://snack.expo.io/rJfMXr!VI
> The example is not nearly sufficient to investigate this properly. Closing.
> 
> ```js-jsx
> import * as React from 'react';
> import { Text, View, StyleSheet } from 'react-native';
> import Constants from 'expo-constants';
> import { Svg, Path } from 'react-native-svg';
> 
> const gradientColors = ['green', 'blue'];
> const paths = gradientColors.map((color, index) => (
>   <Path
>     key={color}
>     d="M0,0L100,100"
>     stroke={color}
>     strokeWidth={5}
>     strokeDasharray={[0, (2 * Math.PI * 5) / gradientColors.length]}
>     strokeLinecap="round"
>     fill="transparent"
>     style={{ transform: [{ translateY: index * 20 }] }}
>   />
> ));
> 
> export default class App extends React.Component {
>   render() {
>     return (
>       <View style={styles.container}>
>         <Svg height="100%" width="100%" viewBox={`0 0 100 100`}>
>           {paths}
>         </Svg>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     justifyContent: 'center',
>     paddingTop: Constants.statusBarHeight,
>     backgroundColor: '#ecf0f1',
>     padding: 8,
>   },
> });
> ```

Hi,
I just tried your example and it is working fine in all devices except in **android 6.0** version, can you please check that and let me know this?
I will attach the screenshot below testing the above code in android 6 device and android 8.0 device

![Screenshot 2020-06-17 at 9 56 16 AM](https://user-images.githubusercontent.com/22475675/84855041-cb387a00-b080-11ea-9235-f877e466e438.png)
