### ISSUE TITLE
PanResponder on Svg element

### ISSUE THREAD

**Issue by chunghe** [react-native-community/react-native-svg#127]
If `console.log(Svg.propTypes)`, you could see all the PanResponder methods are valid methods.

I'm trying to implement a Svg element which allows user to pan to see more content. User should be able to drag everywhere inside the Svg to drag it. So it will be more convenient to bind the PanResponder at the outmost element which is a Svg element.  But try to run following code it won't respond to any touch events:

```
      <Svg
        height="100"
        width="100"
        style={{backgroundColor: '#ccc'}}
        onMoveShouldSetResponder={() => {console.log('onMoveShouldSetResponder')}}
        onResponderGrant={() => {console.log('onResponderGrant')}}
        onResponderMove={() => {console.log('onResponderMove')}}
        onPress={() => {console.log('press')}}
      >
      </Svg>
```

I've tried a top-level G element but it didn't work (probably due to G didn't actually occupy space):
```
      <Svg
        height="100"
        width="100"
        viewBox="0 0 100 100"
        style={{backgroundColor: 'red'}}
      >
        <G
          height="100"
          width="100"
          onMoveShouldSetResponder={() => {console.log('onMoveShouldSetResponder')}}
          onResponderGrant={() => {console.log('onResponderGrant')}}
          onResponderMove={() => {console.log('onResponderMove')}}
          onPress={() => {console.log('press')}}
        />
      </Svg>
```

Is there a way I could get all the bubbling events from the child elements? The closest thing I could come up with is to use a Rect element as the same height/width as the parent Svg element and bind all the PanResponder methods there, but it feels a little bit hacky:

```
      <Svg
        height="100"
        width="100"
        viewBox="0 0 100 100"
        style={{backgroundColor: 'red'}}
      >
        <Rect
          height="100"
          width="100"
          onMoveShouldSetResponder={() => {console.log('onMoveShouldSetResponder')}}
          onResponderGrant={() => {console.log('onResponderGrant')}}
          onResponderMove={() => {console.log('onResponderMove')}}
          onPress={() => {console.log('press')}}
        />
      </Svg>
```

It's more like a question not an issue. Thanks for your hard work.

**Comment by dubert** [comment]
I ran into the same situation and I created a Rect at the very top that handles it the way you do. It _feels_ a bit hacky, but I think it's better than bogging down the SVG props.
