### ISSUE TITLE
Native changes to viewBox? 

### ISSUE THREAD

**Issue by nabati** [react-native-community/react-native-svg#1270]
Let's say you have a simple SVG-drawing which you want to be able to pan and zoom. 

It's fairly simple to set this up with for instance `react-native-gesture-handler`, grabbing the touches coordinates (and what kind of transform they result in), and passing it on to the `<Svg>` component's `viewBox` property, via some component state. 

Unfortunately, this does have a toll on the UI-thread performance, and thus I'm wondering if there's a way to map this touch transformation on the native side in it's entirety. Is this possible?

**Comment by danhanfry** [comment]
Good, I am with the same problem.

There is a drop in fps quickly.

![image](https://user-images.githubusercontent.com/8139751/74436336-8e583e80-4e66-11ea-9cac-3625eefac775.png)

**Comment by msand** [comment]
Maybe one of these could work for you? https://github.com/react-native-community/react-native-svg/issues/1064

**Comment by msand** [comment]
But yeah, viewbox is really the worst performing way to translate/scale the render output dynamically, wrap your content in a G element, and transform that instead.
