### ISSUE TITLE
getScreenCTM in functional component

### ISSUE THREAD

**Issue by stvdrsch** [react-native-community/react-native-svg#1271]
# Question

I'm trying to 'scale' the coördinates of an onPress nativeEvent on a path of an SVG.

![84336013_531706101028029_6714910535248248832_n](https://user-images.githubusercontent.com/8971598/73746847-755cd880-4756-11ea-9dfa-f793f7a9b23e.png)

In the above case the coördinates are correct as the SVG is not scaled. Whenever I DO scale the SVG in order to fit the screen the coördinates of the native onPress event are not scaled accordingly. If I understand [this issue](https://github.com/react-native-community/react-native-svg/issues/997) correctly it the scaling could be done with `.getScreenCTM`. Unfortunately that does not work as I get the an error about `Invariant Violation: Calling synchronous methods on native modules is not supported in chrome`.

```const Damages = ({navigation}) => {

  let _shownSVG = useRef();

  function getCTM() {
    if (_shownSVG.current) {
      const screenCTM = _shownSVG.current.getScreenCTM();
      console.log(screenCTM);
    }
  }

  getCTM();

  return (
    <RootView>
       <Svg ref={_shownSVG} width={'100%'} height={'100%'}>
        <ImportedSVGComponent onPressPart={onSVGPress} width={'100%'} height={'100%'} />
        <OtherOverlaySVGComponent />
      </Svg>
    </RootView>
  );
};
```

Logging what's in `_shownSVG.current` does show me an SVG object with `getCTM` and `getScreenCTM` functions...

I'm finding very little documentation about scaling or the use of the CTM functions.

`react-native-svg`: v11.0.1

**Comment by msand** [comment]
Can you try running without the debugger? Synchronous native methods cannot be used while the javascript is running in v8 inside the browser,  it needs to run on the device for that to work. I'm not sure what you mean by scaling here. Can you make a full reproduction / clone-able git repo?

**Comment by msand** [comment]
These native methods are kind of experimental / barely tested yet, so they might quite possibly contain logic errors.

**Comment by stvdrsch** [comment]
> Can you try running without the debugger? Synchronous native methods cannot be used while the javascript is running in v8 inside the browser, it needs to run on the device for that to work. I'm not sure what you mean by scaling here. Can you make a full reproduction / clone-able git repo?

 By scaling I mean that I'm trying to reduce the size of the car SVG to fit the screen. Inside that SVG there are some paths with an `onPress` property. The coördinates of that onPress.nativeEvent should ideally get scaled equally so I know where to put the bullseye on the car SVG. 

Running without the bugger indeed prevents the error, that's already a step forward. I do just get 
` {"a": undefined, "b": undefined, "c": undefined, "d": undefined, "e": undefined, "f": undefined}` both for `_shownSVG.current.getCTM()` and `_shownSVG.current.getScreenCTM()`

I'll look into making a clone-able git repo, but that will take a while as this is embedded in a much bigger private project.

**Comment by msand** [comment]
You probably call getScreenCTM before the views have been created on the native side, try doing it e.g. in onLayout

**Comment by msand** [comment]
Also, it seems like you should be using viewBox rather than any scaling

**Comment by stvdrsch** [comment]
> You probably call getScreenCTM before the views have been created on the native side, try doing it e.g. in onLayout


```

  let _shownSVG = useRef();

  function getCTM() {
    if (_shownSVG.current) {
      const screenCTM = _shownSVG.current.getScreenCTM();
      console.log(screenCTM);
    }
  }

  return (
    <RootView>
       <Svg ref={_shownSVG} width={'100%'} height={'100%'} onLayout={getCTM()}>
        <ImportedSVGComponent onPressPart={onSVGPress} width={'100%'} height={'100%'} />
        <OtherOverlaySVGComponent />
      </Svg>
    </RootView>
  );
};
```

Also always returns `{"a": undefined, "b": undefined, "c": undefined, "d": undefined, "e": undefined, "f": undefined}`

So you would suggest adjusting the viewbox based on the device width/height instead of defining `height` and `width`?

**Comment by msand** [comment]
Your code looks really confusing to me. Your not giving a callback to onLayout, you call getCTM and give the result as the onLayout handler, you need to add () => to onLayout={() => getCTM()} or remove the () as in onLayout={getCTM}

**Comment by stvdrsch** [comment]
> Your code looks really confusing to me. Your not giving a callback to onLayout, you call getCTM and give the result as the onLayout handler, you need to add () => to onLayout={() => getCTM()} or remove the () as in onLayout={getCTM}

Yes, that's correct (my mistake as I edited the code pasted here). With the callback I still get an object where every value is undefined. `{"a": undefined, "b": undefined, "c": undefined, "d": undefined, "e": undefined, "f": undefined}`

**Comment by msand** [comment]
onLayout seems to work, can you make a reproduction?
https://snack.expo.io/@msand/amused-turkish-delight

```jsx
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { Svg, Path, Rect, G, Circle } from 'react-native-svg';

const log = tag => e => console.log(tag, e.nativeEvent.layout);

export default () => (
  <View style={styles.container}>
    <Svg
      width="100%"
      height="100%"
      onLayout={e => {
        console.log('svg', e.nativeEvent.layout);
      }}
      viewBox={`0 0 50 50`}>
      <Rect width="50" height="50" onLayout={log('rect')} />
      <Circle cx="25" cy="25" r="5" fill="white" onLayout={log('circle')} />
      <Path
        fill="#FFF"
        onLayout={log('path')}
        d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z"
      />
    </Svg>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 8,
    justifyContent: 'center',
  },
});

```
