### ISSUE TITLE
Unable to resolve "./elements/ForeignObject" from "node_modules/react-native-svg/src/ReactNativeSVG.ts"

### ISSUE THREAD

**Issue by Ankur-MoneyKey** [react-native-community/react-native-svg#1273]
I am using SVG version 9.13.3 and while I am using it after loading my app. Its giving me 
Unable to resolve "./elements/ForeignObject" from "node_modules/react-native-svg/src/ReactNativeSVG.ts"

I am using expo-cli for react native app.

Below is my file where in I am using SVG.

import React from 'react';
import ContentLoader, { Rect, Circle } from 'react-content-loader/native';

const ScreenLoader = ()=>{

    return (
        <ContentLoader viewBox="0 0 380 70">
            <Circle cx="30" cy="30" r="30" />
            <Rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
            <Rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
        </ContentLoader>
    )

}

export default ScreenLoader;

**Comment by alexshnur** [comment]
I have the same a problem.
Expo version 36.0.0
React Native version 0.61.4
React Native SVG 9.13.3

`import React from 'react';
import Svg, {Path} from 'react-native-svg';

const HomeIcon = props => {
	const {color, width, height, ...otherProps} = props;
	return (
		<Svg
			width={width}
			height={height}
			viewBox="0 0 41 37"
			fill={color}
			{...otherProps}
		>
			<Path d="M36.9 34.9444V18.5H41L20.5 0L0 18.5H4.1V34.9444C4.1 36.1778 4.92 37 6.15 37H16.4V22.6111H24.6V37H34.85C36.08 37 36.9 36.1778 36.9 34.9444Z"/>
		</Svg>
	);
};

HomeIcon.defaultProps = {
	color: '#475F7B',
	width: '41',
	height: '37'
};

export default HomeIcon;
`

**Comment by CaptainN** [comment]
I'm seeing the same with a fresh app set up, right after init, and adding the module through expo install.

**Comment by CaptainN** [comment]
Okay, I uninstalled `react-native-svg` with `npm un react-native-svg`, then ran expo without using the npm script (not sure if that mattered) with `expo run --ios`, then when if failed to find the `react-native-svg` module, quit that, and re-installed with expo `expo install react-native-svg`, and then again ran Expo with the global package command, not npm `expo run --ios`.

After that I got a useful error message, and found a configuration error:

```
node_modules/react-native-svg/src/ReactNativeSVG.ts: [BABEL] /Users/.../node_modules/react-native-svg/src/ReactNativeSVG.ts: .root is not a valid Plugin property
- Maybe you meant to use
"plugin": [
  ["module-resolver", {
  "root": [
    "./src"
  ],
  "extensions": [
    "ios.js",
    "android.js",
    ".js",
    ".ts",
    ".tsx",
    ".json",
    "jsx"
  ]
}]
]
```

I hadn't wrapped my `module-resolver` with a correct array structure. The point is, after doing those steps I got useful error messages and quickly resolved the issue. I did previously install with `expo install react-native-svg` so I don't know what is different, only that this resolved it for me.

**Comment by alexshnur** [comment]
@CaptainN which configuration file you found?

**Comment by Afrenchrussian** [comment]
I have this as well, a pretty much brand new app

**Comment by Afrenchrussian** [comment]
I think I found my solution, which was that when I loaded my app up earlier I got a warning to change my version of react native svg to 9.13.3 which I did, this is when my app broke. I have reverted my version to ^11.0.1 and my app has started working again just with an expo warning

**Comment by zmathew** [comment]
`expo start --clear` did the trick for me (`--clear` = "Clear the React Native packager cache")

**Comment by msand** [comment]
I guess this can be closed by now
