### ISSUE TITLE
Unable to build application for web using `babel-plugin-react-native-web`

### ISSUE THREAD

**Issue by xdmnl** [react-native-community/react-native-svg#1274]
# Bug

I recently upgraded to react-native-web 0.12.0 and react-native-svg 11.0.1. Unfortunately, it broke my build using metro and babel-plugin-react-native-web (0.12.0).

Downgrading to react-native-svg 10.0.1 and react-natibe-web 0.11.7 fixes the issue.

Looking at the built files, it appears that the published package does not allow the babel plugin for react native web to rewrite the `require` added by #1240:

```js
// In lib/commonjs/ReactNativeSVG.web.js
[...]
var createElement=require('react-native').unstable_createElement||require('react-native').createElement;
[...]
```

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.00 GB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/r_/4htv7dj10zjcpwslc3w0w1sh0000gp/T/yarn--1580943189690-0.6179425353021855/node
    Yarn: 1.16.0 - /var/folders/r_/4htv7dj10zjcpwslc3w0w1sh0000gp/T/yarn--1580943189690-0.6179425353021855/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0
    react-native: ^0.61.5 => 0.61.5
✨  Done in 0.84s.
```

Library version: 11.0.1

## Steps To Reproduce

1. Install metro 
2. Add the babelconfig:
```js
module.exports = {
  // The 'metro-react-native-babel-preset' preset is recommended to match React Native's packager
  presets: ['module:metro-react-native-babel-preset'],
  // Re-write paths to import only the modules needed by the app
  plugins: ['react-native-web']
};
```
3. Run `metro build ./index.ts --platform web --out ./index.web.js`

As long as index.ts uses react-native-svg, the output error is
```
Error: Unable to resolve module `../Components/AccessibilityInfo/AccessibilityInfo` from `node_modules/react-native/Libraries/react-native/react-native-implementation.js`:
```

**Comment by msand** [comment]
I guess we should probably use this instead, and not support older versions of react-native-web anymore:
`import { GestureResponderEvent, unstable_createElement as createElement } from 'react-native';`

**Comment by msand** [comment]
@xdmnl Can you try with the latest version?

**Comment by msand** [comment]
Closing for now.
