### ISSUE TITLE
Override props while building components from AST

### ISSUE THREAD

**Issue by maxkomarychev** [react-native-community/react-native-svg#1276]
# Feature Request

I would like to be able to have a callback on `SvgXml` (and therefore in `SvgUri`) which will allow me intercept and override props in while visiting nodes.

## Why it is needed

I have to deal with SVG images coming from network and render certain shapes which based on configuration should either become clickable (I want to attach `onPress`) and I need to locate these items on screen (attach `onLayout`) or sometimes hide these (change style to become invisible or throw away completely from the tree)

### Code sample

Very basic example:

```jsx

<SvgUri 
  uri="..."
  visitNode=((node: AST) => {
    if (node.props.id === "tap-me") {
      // object returned from visitor is merged into node
      return { props: { onPress: this.onPress } } 
    }
  })
/>

```

Would you consider accepting PR introducing such change?
Thanks

**Comment by msand** [comment]
There is actually already support for middleware: https://github.com/react-native-community/react-native-svg/blob/4375ee676eb862249814f98a2debb4ac355156b6/src/xml.tsx#L537
It is used in e.g. SvgCss https://github.com/react-native-community/react-native-svg/blob/4375ee676eb862249814f98a2debb4ac355156b6/src/css.tsx#L696-L701
Would this cover your use-case?

**Comment by maxkomarychev** [comment]
thanks for quick response,

I did notice the middleware line you reference to in first code block, however there is no code in `xml.tsx` that is calling `parse` with two parameters:

https://github.com/react-native-community/react-native-svg/blob/master/src/xml.tsx#L106
https://github.com/react-native-community/react-native-svg/blob/master/src/xml.tsx#L147

so I am not sure how one can use is via `SvgUri` interface, am I missing something?

**Comment by msand** [comment]
Ah, well you would use SvgAst and parse, instead of SvgUri, similar to SvgCssUri
https://github.com/react-native-community/react-native-svg/blob/4375ee676eb862249814f98a2debb4ac355156b6/src/css.tsx#L695-L715

So something like:


```jsx
export function SvgMiddleware(props: XmlProps) {
  const { xml, override, middleware } = props;
  const ast = useMemo<JsxAST | null>(
    () => (xml !== null ? parse(xml, middleware) : null),
    [xml],
  );
  return <SvgAst ast={ast} override={override || props} />;
}

export function SvgMiddlewareUri(props: UriProps) {
  const { uri, middleware } = props;
  const [xml, setXml] = useState<string | null>(null);
  useEffect(() => {
    uri
      ? fetchText(uri)
          .then(setXml)
          .catch(err)
      : setXml(null);
  }, [uri]);
  return <SvgMiddleware xml={xml} override={props} middleware={middleware} />;
}
```
