### ISSUE TITLE
Error while updating property 'd' of a view managed by: RNSVGPath null For input string: 'v'

### ISSUE THREAD

**Issue by Husky1191997** [react-native-community/react-native-svg#1278]
# Question
Help me.
I updated the react-native from 0.59.9 up to 0.61.5
I used 
         "react-native-svg": "^9.13.3",
          "react-native": "0.61.5"
After updated I delete node_module, yarn install   and restart build metro, clear cache but I have an issue in android.
It is an SVG image in my project: 
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
<path d="M0 0h24v24H0z" fill="none"/>
<path d="M19 10h1a1 1 0 011 1v10a1 1 0 01-1 1H4a1 1 0 01-1-1V11a1 1 0 011-1h1V9a7 7 0 0114 0zm-2 0V9A5 5 0 107 9v1zm-6 4v4h2v-4z" fill="#d9d9d9"/>
</svg>
After build in device Android, i have a issues same image:
![85076107_805823103254572_7897770358499966976_n](https://user-images.githubusercontent.com/39523424/74079069-f2dd5d00-4a64-11ea-98eb-135cd14ff083.jpg)

Please, If you have any information about this error. Hope you share and help me.
Thanks !!!

**Comment by Husky1191997** [comment]
it is an SVG image in my project:
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 10h1a1 1 0 011 1v10a1 1 0 01-1 1H4a1 1 0 01-1-1V11a1 1 0 011-1h1V9a7 7 0 0114 0zm-2 0V9A5 5 0 107 9v1zm-6 4v4h2v-4z" fill="#d9d9d9"/></svg>

**Comment by Husky1191997** [comment]
It is an SVG image in my project:
<img width="1184" alt="Screen Shot 2020-02-08 at 11 27 57 AM" src="https://user-images.githubusercontent.com/39523424/74079158-22409980-4a66-11ea-8907-db22765c14a2.png">

**Comment by msand** [comment]
Screenshots are painful / useless, if you want help, provide a repro or at least copy paste-able content.

**Comment by vinayvnvv** [comment]
Same Error Here, any solution?

**Comment by msand** [comment]
Does it look like it? Please provide a reproduction if you want progress on this. One more useless comment and I'll close this issue.

**Comment by msand** [comment]
No reproduction provided. Closing.
