### ISSUE TITLE
Not Display SVG File shadow in Device

### ISSUE THREAD

**Issue by sunilprajapati714** [react-native-community/react-native-svg#1280]
```
import Go_BG_Icon from '../../../assets/resources/img_go_icon.svg'

<Go_BG_Icon />
```

I'm added img_go_icon svg  in my project which is contain shadow. But unfortunately not display SVG shadow in device when run app.

Configure react-native-svg step-by-step. SVG is display but their shadow is not dropping in device.

**Comment by msand** [comment]
Can you provide a complete reproduction? Almost impossible to know otherwise.
