### ISSUE TITLE
error: bundling failed: SyntaxError: /node_modules/react-native-svg/src/elements/Shape.tsx: Identifier 'SVGMatrix' has already been declared (100:13)

### ISSUE THREAD

**Issue by jadeirving9** [react-native-community/react-native-svg#1285]
<img width="503" alt="Screenshot 2020-02-14 at 00 11 55" src="https://user-images.githubusercontent.com/32270767/74489875-9fcd3500-4ebe-11ea-8d33-eb70adfdc5af.png">

# Bug

Bug is shown in screenshot, appears when trying to run using npx react-native run-android command.

I have tried:
creating a clean project
removing node modules folder and running npm i again
cd android && gradle clean

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
    Memory: 70.30 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.4 => 0.61.4
```

Library version: x.x.x

## Steps To Reproduce

npx react-native run-android

Describe what you expected to happen:

1. app to run as it normally does

**Comment by jadeirving9** [comment]
If I do a gradle clean before executing react-native run-android, I get a different error (as shown in screenshot) 
<img width="485" alt="Screenshot 2020-02-14 at 00 21 18" src="https://user-images.githubusercontent.com/32270767/74490311-0ef75900-4ec0-11ea-9b1e-7a209e42df0c.png">

**Comment by dabhitapan** [comment]
@jadeirving9 Did you find any solution or workaround?

**Comment by mengbimao** [comment]
+1
