### ISSUE TITLE
No stops in gradient

### ISSUE THREAD

**Issue by mydesweb** [react-native-community/react-native-svg#1292]
I receive this Warning: No stops in gradient -- the SVG is loaded from file and it is displayed fine. The warning is coming from RNSVGPainter.m 

Any suggestion about how to fix this in the SVG file?.. or it is safe if I just ignore the warning?

**Comment by mydesweb** [comment]
I solved by importing the wrong SVG in another software and after exporting again as SVG..

**Comment by kimkimchichi** [comment]
What the app do you use?

**Comment by tuanngocptn** [comment]
I have the same trouble.
I solved this warning after import and validate file in "https://validator.w3.org/#validate_by_upload".
After that, I try to fix all error appear. => open svg with vscode and fix that.
Refresh the simulator and warning is disappear :D
