### ISSUE TITLE
RNSVGCircle error on Android

### ISSUE THREAD

**Issue by DzmitrySakalouski** [react-native-community/react-native-svg#1293]
# Issue

Hello.
Currently I have an error on Android (see attachment)
For iOS there is no error, but nothing renders
![iwgzAnDoXQk](https://user-images.githubusercontent.com/55082507/75194495-4dff9700-5769-11ea-8b15-d0eb6b1e2992.jpg)
![image](https://user-images.githubusercontent.com/55082507/75194529-5e177680-5769-11ea-9d89-42fe160baa4a.png)

RN: 0.61.5
RNSVG: 11.0.1

Thanks.

**Comment by msand** [comment]
Seems like a linking error. Can you try cleaning the build, rebuild and run again?
