### ISSUE TITLE
Custom image round : borderRadius

### ISSUE THREAD

**Issue by minh-dai** [react-native-community/react-native-svg#1297]
# Feature Request

This issue should serve for you to present or pitch an idea to the maintainers - but remember that it would be better if you were to submit a PR instead 🤗

## Why it is needed

Please tell us a bit more of why you want this feature to be added, what's its origin

## Possible implementation

It really helps if you could describe from a technical POV how this new feature would work, which code it rely on, etc

### Code sample

Please show how the new code could work, if doable

**Comment by msand** [comment]
?
