### ISSUE TITLE
What does the`react-native` field in package.json file do? 

### ISSUE THREAD

**Issue by BeckyWu220** [react-native-community/react-native-svg#1305]
Hi! Thanks for maintaning the great library. I encountered an issue while trying to use `react-native-svg-charts` lib with `react-native-svg`. `react-native-svg-charts` library has a dependency on `react-native-svg`, however, since its implementation doesn't involve any iOS or Android native code, I was trying to use it in a React JS project. 

While testing, I encountered `Failed to compile` errors in `react-native-svg-charts` components while importing `Path` component from `react-native-svg`. 

![image (2)](https://user-images.githubusercontent.com/16603120/76038478-82f4b200-5efe-11ea-80be-e3e3d64234f1.png)
As the screenshot above, the `react-native-svg` module is always mapped to `react-native-svg/src/index`, which is corresponding to the value of `react-native` field in `package.json` file.

There are also `main` and `module` field in package.json file with different paths.  
<img width="560" alt="image" src="https://user-images.githubusercontent.com/16603120/76037985-4e342b00-5efd-11ea-9cb9-a86b18c2deb4.png">

**My question is how does the library detect which path to take while running?**

Thanks ahead of time. Look forward to your reply.

**Comment by msand** [comment]
Hello! Thanks for the nice words. The package actually isn't in control of that. In the case of normal react-native projects, it's metro handing that responsibility. On the web, it's usually webpack or a similar tools that handles it. I'm not sure if the preview in your ide actually shows the correct configuration dependant path, would be very impressive if it did.
In webpack you need to add the extensions for it to resolve them: https://gist.github.com/srikanthsunkari/64377454251739266ee5cd092209018e#file-updated-webpack-config-js-L85

**Comment by BeckyWu220** [comment]
Hi! @msand Thanks for the rapid reply. Your response inspired me to explore webpack config instead of focusing on the `react-native-svg` dependant path. It turns out that I need to explicitly include `react-native-svg` in the `node_modules` folder in the webpack config to compile. 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/16603120/76107978-93ed0400-5f8e-11ea-975b-bde2b18a7bf4.png">


Two other helpful links that solved my problem in case someone else is facing the same issue:

- https://github.com/webpack/webpack/issues/2031
- https://stackoverflow.com/questions/51289261/babel-does-not-transpile-imported-modules-from-node-modules
