### ISSUE TITLE
[ANDROID] App has stopped to working after install react-native-svg

### ISSUE THREAD

**Issue by limamauricio** [react-native-community/react-native-svg#1308]
# Question

After run `yarn add react-native-svg` and `npx react-native run-android 0027139588`, the app has stopped.

"react-native": "0.61.5",
"react-native-svg": "^12.0.3",

**Comment by msand** [comment]
reproduction?

**Comment by limamauricio** [comment]
Step-by-Step
1 . npx react-native init MyTSProject --template react-native-template-typescript
2 . yarn add react-native-svg
3. npx react-native run-android
4. App has stopped.

**Comment by limamauricio** [comment]
Resolved:
rm -rf node_modules
yarn
react-native start --reset-cache
