### ISSUE TITLE
react-native-svg/ios/Utils/RCTConvert+RNSVG.m:108:48: No known class method for selector 'UIFont:withFamily:size:weight:style:scaleMultiplier:'

### ISSUE THREAD

**Issue by tuckerconnelly** [react-native-community/react-native-svg#131]
When I try to compile on iOS :/

**Comment by magicismight** [comment]
related with #124 .
Will get this fixed after 0.33.0 is released.

**Comment by tuckerconnelly** [comment]
Yusssss thanks :D

**Comment by joncursi** [comment]
*poke*

0.33.0 is out :)

**Comment by RichardLindhout** [comment]
Got this error after updating to 0.33.0....

**Comment by magicismight** [comment]
@RichardLindhout try to update to @4.3.0

**Comment by RichardLindhout** [comment]
Yes it does work now!

Op 13 sep. 2016 04:53 schreef "Horcrux" <notifications@github.com>:

**Comment by eitangenis** [comment]
I am on react-native .34 and still getting this error
