### ISSUE TITLE
Support for custom fonts

### ISSUE THREAD

**Issue by oroafrica** [react-native-community/react-native-svg#1310]
# Feature Request

This issue should serve for you to present or pitch an idea to the maintainers - but remember that it would be better if you were to submit a PR instead 🤗

## Why it is needed

Please tell us a bit more of why you want this feature to be added, what's its origin

## Possible implementation

It really helps if you could describe from a technical POV how this new feature would work, which code it rely on, etc

### Code sample

Please show how the new code could work, if doable

**Comment by msand** [comment]
Custom fonts are support. Try the search function before you open an issue next time.
https://github.com/react-native-community/react-native-svg/search?q=Custom+fonts&type=Issues
