### ISSUE TITLE
Uncaught Error: Error while updation property 'fill' of a view managed by: RNSVGPath

### ISSUE THREAD

**Issue by LuHugo** [react-native-community/react-native-svg#1320]
[expo svg example](https://snack.expo.io/HySDrjHmI) is not work.

Same error in my project

**Comment by matthewjj** [comment]
Hi, did you manage to get by this error? Im getting it too. Im using expo

**Comment by skasyn** [comment]
Same issue on my project on a fresh install of expo / react-native-svg.

I used a component generated by https://react-svgr.com/playground/?native=true
heres the code : 

```js
import * as React from "react"
import Svg, { Path } from "react-native-svg"

function Icon(props) {
    return (
        <Svg width={87} height={112} viewBox="0 0 87 112" fill="white" {...props}>
            <Path
                d="M73.695 109.352l2.145-2.574c1.486 1.229 3.042 2.007 4.929 2.007 1.486 0 2.381-.589 2.381-1.557v-.046c0-.922-.566-1.394-3.325-2.102-3.325-.85-5.47-1.772-5.47-5.053v-.046c0-2.997 2.405-4.981 5.779-4.981 2.404 0 4.457.756 6.13 2.101l-1.887 2.74c-1.461-1.016-2.9-1.629-4.292-1.629s-2.121.638-2.121 1.44v.046c0 1.085.706 1.44 3.56 2.173 3.348.873 5.235 2.078 5.235 4.959v.045c0 3.281-2.5 5.125-6.059 5.125-2.502-.003-5.026-.878-7.005-2.648zM16.44 95.299H0v3.283h16.44V95.3zM16.44 101.889H0v3.283h16.44v-3.283zM16.44 108.476H0v3.284h16.44v-3.284zM85 0H0v16.978h85V0zM85 34.074H0v16.978h85V34.074zM85 68.135H0v16.978h85V68.135zM71.99 101.889H55.55v3.283h16.44v-3.283zM29.783 106.462l-.262-.391a5.578 5.578 0 003.526-5.191c0-1.01-.27-1.96-.74-2.778a5.57 5.57 0 00-5.148-2.793h-4.161v-.01H19.72v16.461h3.277v-5.298h2.828l3.56 5.283h3.954l-3.557-5.283zm-2.31-7.872a2.288 2.288 0 01.087 4.576l.01.015h-4.572v-4.585h4.475v-.006zM52.041 95.299H48.98v.01h-.36l-4.572 6.909-4.569-6.91h-.362v-.01h-3.277v16.462h3.277v-11.051l2.965 4.484 1.966 2.972 1.966-2.972 2.966-4.484v11.051h3.28V95.299h-.218zM71.99 95.299H55.55v3.283h16.44V95.3zM71.99 108.476H55.55v3.284h16.44v-3.284z"
                fill="#fff"
            />
        </Svg>
    )
}

export default Icon

```

## Version
- expo 3.15.5
- react-native-svg 12.0.3


I put some console.log all around the react-native-svg source code and the `fill` property is extracted just as expected.

More stacktrace :
```
Error while updating property 'fill' of a view managed by: RNSVGPath

null

java.lang.Double cannot be cast to java.lang.String
```

**Comment by msand** [comment]
You need to use `expo install react-native-svg` to get the version of react-native-svg that is prebuilt into the expo version you are using. Or alternatively, use plain react-native / eject from expo.

**Comment by msand** [comment]
Is there anything we could improve in our docs to make this more obvious?

https://github.com/react-native-community/react-native-svg#with-expo-cli

https://docs.expo.io/versions/latest/sdk/svg/

Seems this issue keeps coming up. Have any of you read the documentation? Or what's the reason this keeps occuring?

**Comment by skasyn** [comment]
Installing with expo obviously solved the problem.

The documentation needs no change ! Coming from React, there plenty of hard habits and installing package with npm without thinking is one of them. My bad on this one, I guess I should have spent more time on the docs 😅

I would argue that I found `react-native-svg` on a stackoverflow thread that did not mentioned expo. Maybe this issue keeps occuring because many react-native newcomers coming from React (as me) have trouble thinking with expo and that obvious things as this are not mentioned on stackoverflow ?

Anyway, thanks for the quick reply 👍

**Comment by LuHugo** [comment]
@msand I follow the document to use expo install the package but still got this error.
my project dependencies is 
```json
"dependencies": {
    "@react-native-community/datetimepicker": "^2.3.0",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.7",
    "class-validator": "^0.12.0-rc.0",
    "expo": "~36.0.0",
    "expo-av": "^8.1.0",
    "expo-barcode-scanner": "^8.1.0",
    "expo-camera": "^8.0.0",
    "expo-sqlite": "^8.0.0",
    "mobx": "^5.15.4",
    "mobx-react": "^6.1.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-appearance": "^0.3.3",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-sqlite-storage": "^4.1.0",
    "react-native-svg": "^12.0.3",
    "react-native-unimodules": "~0.7.0",
    "react-native-web": "~0.11.7",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.2.24"
  }
```

**Comment by msand** [comment]
Remove/uninstall the previous version first. And run expo install react-native-svg again, or just change ^12.0.3 to the version bundled in your expo version, i.e. 9.13.3 in your case. The latest bundled version is 11.0.1 in Expo 37 which was released hours ago. It was v9.13.3 before that, in Expo 36 which your package.json suggests you are using. https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json#L63
https://github.com/expo/expo/blob/master/CHANGELOG.md#3700

**Comment by LuHugo** [comment]
@msand Thank you very much, it is indeed a matter of version incompatibility. After downgrading to version 9.x everything is fine.
