### ISSUE TITLE
Is it possible to calculate svg height or read the inside of downloaded svg file?

### ISSUE THREAD

**Issue by schmru** [react-native-community/react-native-svg#1322]
Hello, I am trying to load image from link. For it I am using: 
```
<SvgCssUri
  style={{width: imageWidth, height: 176}}
   key={Math.random()}
    uri={source}
 />
```
Is there a way to then get the actual xml code from it, so that I would get the dimensions of the image, or is it possible to load image without setting height?
I am doing the same thing with image: 

```
export function OnlineImage({source, imageWidth}){
    const [imgHeight, setImgHeight] = useState(0);
    useEffect(() => {
            const image = <Image
                width={imageWidth}
                source={{uri: source}}
                key={Math.random()}
            />;
            Image.getSize(source, (width, height) => {
                setImgHeight(height * (image.props.width / width))
            }, null);
    }, [])

    return(
            <Image
                style={{width: imageWidth, height: imgHeight}}
                source={{uri: source}}
                key={Math.random()}
            );
}
```
This way I calculate the right height for image based on width.

**Comment by soroushm** [comment]
@schmru Hey

you can add `babel-plugin-inline-import'` and import actual xml from svg like 
 then get anything you want from them 
    ```
import sample from './samle.svg'

render() {
  <SvgXml
        xml={sample}
        width={width ? width : this.size()}
        height={height ? height : this.size()}
        fill={this.color()}
        style={style}
      />
```
```
[
      'babel-plugin-inline-import',
      {
        extensions: ['.svg'],
      },
    ],
```

**Comment by schmru** [comment]
@soroushm Hello, the problem is that my svg is an online source. Sadly svgxml doesn't support link.

**Comment by soroushm** [comment]
@schmru give us a sample

**Comment by schmru** [comment]
@soroushm This is the one I am trying to resize: https://storage.googleapis.com/jp-strapi/media/FDB_EN3.svg

**Comment by soroushm** [comment]
:)) service is not available in my location
<img width="774" alt="Screen Shot 2020-03-28 at 14 50 21" src="https://user-images.githubusercontent.com/1031663/77820921-8517ee00-7103-11ea-965a-c21661437869.png">

so you need somethings like this but I'm not sure you can download from another domain because of access origin
```
async componentDidMount() {
const svg = await fetch('https://storage.googleapis.com/jp-strapi/media/FDB_EN3.svg');
this.setState({svg})
}
```

**Comment by msand** [comment]
Did you try this? https://github.com/react-native-community/react-native-svg#use-with-content-loaded-from-uri

**Comment by msand** [comment]
And you might be interested in this https://github.com/react-native-community/react-native-svg/issues/1306

**Comment by msand** [comment]
This gives much better performance though: https://github.com/react-native-community/react-native-svg#use-with-svg-files

**Comment by schmru** [comment]
@msand The first solution your offered I am already using as seen in my question, but I have to preset the height which I don't want to, since I don't know it. 
The second solution doesn't fit, since the svg is online.

**Comment by schmru** [comment]
@soroushm Thank you for suggestion, but even if I download file with fetch, it doesn't contain data about height or width, neither the viewBox. Looks like I'll have to think some other way to get that info.

**Comment by schmru** [comment]
@soroushm So I ended up using [this](https://stackoverflow.com/a/45205120/1241217), this way I get parts of the svg that I need, it is ugly, but it works :)
