### ISSUE TITLE
how to use js to modify an SvgUri component

### ISSUE THREAD

**Issue by asinning** [react-native-community/react-native-svg#1334]
# Question

We're trying to re-use SVGs across native and browser applications, so we're using SvgUri to pull in a ready-made SVG. As the user pans and zooms within the SVG, we need to hide and show certain elements.  In the browser we can do this by simply changing the css-class of the parent, and the css-selector does the rest. Unfortunately, there are no css-classes in RN.

I assume that I could do this by introspecting the rendered RNSVGSvgView's tree and using plain-old js to change a style, but I'm not sure how, and it doesn't seem like a very React way.

Thanks for any insight!

**Comment by msand** [comment]
I'd recommend using svgr to convert the svg to a react component (it has better performance as well), and use state to create state dependent behaviour.

**Comment by asinning** [comment]
I don't understand how that is going to help me with the RN implementation. HTML5 SVGs don't run in RN, so I still need to convert it to an RNSVG. I'm obviously missing a key point of understanding. This is our first RN project.

**Comment by msand** [comment]
https://react-svgr.com/playground/

**Comment by msand** [comment]
And, click the checkbox for "React Native"

**Comment by asinning** [comment]
Thanks! This looks very straightforward if I'm dealing with just a few svgs, but we're going to have about 1,000 of them and they are going to change from time to time.  I'm hoping you can help me understand what the data-flow would be.  

Let's say the functionality is that we Text elements with classes "inner_1" and "inner_2". At some state I want all of the .inner_1 Text elements to transition from hidden to visible.  With css this is easy. I just set the class of the outer-most Svg element to "outer_1", and my css-selector ".outer_1 Text .inner_1" takes care of the rest.

How would I do this in RN?

**Comment by msand** [comment]
You might want to create a build script which uses svgr and a codemod, to apply a transform to the abstract syntax tree, to get optimal performance. Alternatively, you can do it with much worse performance at runtime, by resolving css, and doing the actual class changes you mention. Copy the code from here, and do additional changes before/after the inlineStyles middleware:
https://github.com/react-native-community/react-native-svg/blob/e66e87a5b5c090509d5e2127237963f83e60f1e9/src/css.tsx#L695-L702

The codemod solution will provide significant performance improvement in comparison.
There's many ways to design the state dependence, one of the simplest that come to mind would be keeping track of the visible classes:
https://snack.expo.io/@msand/arrogant-marshmallows

```jsx
import * as React from 'react';
import { Circle, G, Svg } from 'react-native-svg';

export default class SvgExample extends React.Component {
  state = { inner_1: true };

  toggler = type => () => {
    this.setState(state => ({ ...state, [type]: !state[type] }));
  };

  toggle1 = this.toggler('inner_1');
  toggle2 = this.toggler('inner_2');
  toggle3 = this.toggler('inner_3');

  style = visible => ({ display: visible ? '' : 'none' });

  render() {
    const { state, style } = this;
    const { toggle1, toggle2, toggle3 } = this;
    const { inner_1, inner_2, inner_3 } = state;
    return (
      <Svg width="100%" height="100%" viewBox="0 0 100 100">
        <G transform="translate(0, 0)" style={style(inner_1)}>
          <Circle r={30} fill="red" />
          <Circle r={20} fill="green" />
          <Circle r={10} fill="blue" />
        </G>
        <G transform="translate(50, 0)" style={style(inner_2)}>
          <Circle r={30} fill="red" />
          <Circle r={20} fill="green" />
          <Circle r={10} fill="blue" />
        </G>
        <G transform="translate(0, 50)" style={style(inner_3)}>
          <Circle r={30} fill="red" />
          <Circle r={20} fill="green" />
          <Circle r={10} fill="blue" />
        </G>
        <G transform="translate(50, 50)">
          <Circle r={30} fill="red" onPress={toggle1} />
          <Circle r={20} fill="green" onPress={toggle2} />
          <Circle r={10} fill="blue" onPress={toggle3} />
        </G>
      </Svg>
    );
  }
}

```

**Comment by asinning** [comment]
Thanks again Mikael, this is so helpful, and I think the latter is quite a practical solution. However, being new to RN, I don't quite understand how I will be able to dynamically load these components from a url. 

Can svgr create a component at runtime? 

If not, this post suggests that they would need to be bundled with the native app <https://stackoverflow.com/questions/52392318/load-component-dynamically-to-react-native-app-from-external-url>

Here's an interesting blog <https://www.storyblok.com/tp/react-dynamic-component-from-json> on how to dynamically create a component from json.  Since our project is generating the data server-side from raw data, I'm wondering if it might not be just as practical to have a json-version of the SVG structure, and simply build the component tree at run-time.

**Comment by msand** [comment]
Thanks, you're welcome! If you're generating it from data, I'd very strongly recommend to send the original data, or a smaller byte count representation of it to the client, and calculate the needed svg representation inside a react component directly in javascript, and have any logic depend directly on the data and any relevant correlations in it.

You can't use svgr at runtime no, for that you should copy the logic of the SvgCss component, and create an extension to the inlineStyles middleware function, and do any needed transforms either directly on the xml representation, the parsed xml tree, the ast with css/styles inlined, or the actual jsx tree.

This is essentially equivalent to svgr, except done at run-time every time it loads, rather than only once at build time. It's possible to hook into each stage of the parsing/processing at runtime, feel free to read the code in css.tsx and xml.tsx and copy/paste/override in any way you need inside your project, all the important parts should be exported already for easy reuse/extension.

**Comment by asinning** [comment]
I appreciate that you spent all this time to help me decide to do approximately what I had already thought I would need to do in the first place, only now I am even more confident, and I have gained valuable insights! I hope you have something to do other than work during this quarantine. We're having early spring in Minneapolis, so people are out walking, some with masks, others without. Crazy times!

**Comment by msand** [comment]
Well, I've spent two or so years working 15-18h days 6-7 days per week getting our startup going. A bit surprised that what has become my normal is considered quarantine by others, quite frankly haven't noticed much difference, except for some colleagues who have kids in school and things related to that. Hopefully I'll get time for something else then work soon enough.
