### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to BOOL

### ISSUE THREAD

**Issue by selimhancakir** [react-native-community/react-native-svg#1339]
I am getting this error when I change the page in my react native app. Help please...

JSON value '<null>' of type NSNull cannot be converted to BOOL

+[RCTConvert BOOL:]
    RCTConvert.m:23
-[RNGestureHandler configure:]
-[RNPanGestureHandler configure:]
-[RNGestureHandlerManager createGestureHandler:tag:config:]
__58-[RNGestureHandlerModule createGestureHandler:tag:config:]_block_invoke
__55-[RNGestureHandlerModule uiManagerWillPerformMounting:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.489
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by msand** [comment]
Seems your issue is related to RNGestureHandler  / https://github.com/software-mansion/react-native-gesture-handler rather than react-native-svg
