### ISSUE TITLE
[Help] Positioning object

### ISSUE THREAD

**Issue by FlaviooLima** [react-native-community/react-native-svg#134]
Hi, i'm trying to change the position(x,y) of the object, the problem is that if i change the position in G component the image will be cut, and i already try to change the position of svg component with origin="300, 0"  and x="300" y="0"  props,   but no success. 

React-native: 0.31.0V
react-native-svg: 4.1.5V

```
<Svg height={90} width={90} viewBox="0 0 1000 1000" >
    <G id="XMLID_2_" scale={this.props.scale} rotate={this.props.rotate}  x={0} y={0}   /></Svg>
```

Result:
![objectnotcut](https://cloud.githubusercontent.com/assets/13239857/18246852/5c8b3364-7366-11e6-968d-c3ff1e06e11b.png)

```
<Svg height={90} width={90} viewBox="0 0 1000 1000" >
    <G id="XMLID_2_" scale={this.props.scale} rotate={this.props.rotate} x={300} y={0} /></Svg>
```

Result:
![objectcut](https://cloud.githubusercontent.com/assets/13239857/18246858/6597267a-7366-11e6-8456-2561dd979d44.png)

**Comment by msand** [comment]
Could you try again with the latest version, there's been lots of related changes since 4.1.5

**Comment by msand** [comment]
Closing because of no response.
