### ISSUE TITLE
Why do I have a weird margin / padding around my icon?

### ISSUE THREAD

**Issue by dhuber666** [react-native-community/react-native-svg#1341]
# Question

Hi guys,

I searched through through stackoverflow but I can't find a solution.

I have a SVG Element. When I import it using `react-native-svg` the icon has a weird margin / padding around, altough it's not padding or marging according to the inspector. 

Here is the svg:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="80" height="80" viewBox="0 0 80 80">
  <defs>
    <linearGradient id="linear-gradient" x1="0.23" y1="0.126" x2="0.834" y2="0.93" gradientUnits="objectBoundingBox">
      <stop offset="0" stop-color="#f857c3"/>
      <stop offset="1" stop-color="#e0139c"/>
    </linearGradient>
    <filter id="Ellipse_8" x="0" y="0" width="80" height="80" filterUnits="userSpaceOnUse">
      <feOffset dy="7" input="SourceAlpha"/>
      <feGaussianBlur stdDeviation="4.5" result="blur"/>
      <feFlood flood-color="#f456c3" flood-opacity="0.471"/>
      <feComposite operator="in" in2="blur"/>
      <feComposite in="SourceGraphic"/>
    </filter>
  </defs>
  <g id="Button" transform="translate(-139.5 -702.5)">
    <g transform="matrix(1, 0, 0, 1, 139.5, 702.5)" filter="url(#Ellipse_8)">
      <circle id="Ellipse_8-2" data-name="Ellipse 8" cx="26.5" cy="26.5" r="26.5" transform="translate(13.5 6.5)" fill="url(#linear-gradient)"/>
    </g>
    <g id="add" transform="translate(167.309 723.309)">
      <g id="Gruppe_15" data-name="Gruppe 15" transform="translate(11.404)">
        <g id="Gruppe_14" data-name="Gruppe 14">
          <path id="Pfad_77" data-name="Pfad 77" d="M236.32,0a1,1,0,0,0-1,1V23.81a1,1,0,1,0,2,0V1A1,1,0,0,0,236.32,0Z" transform="translate(-235.318 0)" fill="#fff" stroke="#fff" stroke-width="3"/>
        </g>
      </g>
      <g id="Gruppe_17" data-name="Gruppe 17" transform="translate(0 11.404)">
        <g id="Gruppe_16" data-name="Gruppe 16">
          <path id="Pfad_78" data-name="Pfad 78" d="M23.81,235.318H1a1,1,0,1,0,0,2H23.81a1,1,0,1,0,0-2Z" transform="translate(0 -235.318)" fill="#fff" stroke="#fff" stroke-width="3"/>
        </g>
      </g>
    </g>
  </g>
</svg>
`

I import it like this: `import AddLogo from '../assets/icons/add_icon.svg';`

And then I use it in my component like so: `<AddLogo />`

This is how it looks like, see the box around?

![sc1](https://user-images.githubusercontent.com/15130832/78792163-13685b80-79b1-11ea-85cc-f14ccac7d3d7.PNG)

Why is that? Is is a problem with the package or a problem with the svg? I just exported it with adobe xd and sticked it into my assets. 

This makes it very hard for me to position it precisely. 

Thx guys!

**Comment by msand** [comment]
It's because of the viewBox you have, try this:
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  width="80"
  height="80"
  viewBox="13.5 6.5 53 53"
  style="overflow: visible;"
>
  <defs>
    <linearGradient
      id="linear-gradient"
      x1="0.23"
      y1="0.126"
      x2="0.834"
      y2="0.93"
      gradientUnits="objectBoundingBox"
    >
      <stop offset="0" stop-color="#f857c3"></stop>
      <stop offset="1" stop-color="#e0139c"></stop>
    </linearGradient>
    <filter
      id="Ellipse_8"
      x="0"
      y="0"
      width="80"
      height="80"
      filterUnits="userSpaceOnUse"
    >
      <feOffset dy="7" input="SourceAlpha"></feOffset>
      <feGaussianBlur stdDeviation="4.5" result="blur"></feGaussianBlur>
      <feFlood flood-color="#f456c3" flood-opacity="0.471"></feFlood>
      <feComposite operator="in" in2="blur"></feComposite>
      <feComposite in="SourceGraphic"></feComposite>
    </filter>
  </defs>
  <g id="Button" transform="translate(-139.5 -702.5)">
    <g filter="url(#Ellipse_8)" transform="matrix(1, 0, 0, 1, 139.5, 702.5)">
      <circle
        id="Ellipse_8-2"
        data-name="Ellipse 8"
        cx="26.5"
        cy="26.5"
        r="26.5"
        transform="translate(13.5 6.5)"
        fill="url(#linear-gradient)"
      ></circle>
    </g>
    <g id="add" transform="translate(167.309 723.309)">
      <g id="Gruppe_15" data-name="Gruppe 15" transform="translate(11.404)">
        <g id="Gruppe_14" data-name="Gruppe 14">
          <path
            id="Pfad_77"
            data-name="Pfad 77"
            d="M236.32,0a1,1,0,0,0-1,1V23.81a1,1,0,1,0,2,0V1A1,1,0,0,0,236.32,0Z"
            transform="translate(-235.318 0)"
            fill="#fff"
            stroke="#fff"
            stroke-width="3"
          ></path>
        </g>
      </g>
      <g id="Gruppe_17" data-name="Gruppe 17" transform="translate(0 11.404)">
        <g id="Gruppe_16" data-name="Gruppe 16">
          <path
            id="Pfad_78"
            data-name="Pfad 78"
            d="M23.81,235.318H1a1,1,0,1,0,0,2H23.81a1,1,0,1,0,0-2Z"
            transform="translate(0 -235.318)"
            fill="#fff"
            stroke="#fff"
            stroke-width="3"
          ></path>
        </g>
      </g>
    </g>
  </g>
</svg>

```

**Comment by dhuber666** [comment]
Holy shit that's it. I don't get svg's. How are you getting this values? Are they calculated from width and height? Some guide or link where I can read about it ? :) 

Thx man!

**Comment by msand** [comment]
I took it from the circle you've drawn:

```svg
      <circle
        id="Ellipse_8-2"
        data-name="Ellipse 8"
        cx="26.5"
        cy="26.5"
        r="26.5"
        transform="translate(13.5 6.5)"
        fill="url(#linear-gradient)"
      ></circle>
```

Specifically: translate(13.5 6.5) and 2 * 26.5 = 53

Maybe these can help:
https://svgwg.org/svg2-draft/coords.html#ViewBoxAttribute
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
https://alligator.io/svg/svg-viewbox/
https://www.sarasoueidan.com/blog/svg-coordinate-systems/

Also, preserveAspectRatio  is useful to understand in relation to viewBox: https://svgwg.org/svg2-draft/coords.html#ExamplePreserveAspectRatio

**Comment by dhuber666** [comment]
Thx you are a SVG god. /closed
