### ISSUE TITLE
No ViewManager defined for class RNSVGGroup

### ISSUE THREAD

**Issue by af7** [react-native-community/react-native-svg#135]
I get the following error (red)...

"No ViewManager defined for class RNSVGGroup"

...when running my RN Android app with the **react-native-svg** package:

*"react-native link react-native-svg"*

Not sure if the problem is related to the following issuse:
When I use this...
**react-native link react-native-svg**

...I get this:
![image](https://cloud.githubusercontent.com/assets/7850073/18253450/6f45cc9e-739d-11e6-89ab-4082c97b02ff.png)

It appears the the links have been completed though.
I am using Windows 10.

Any ideas why I get the above message? Thank you.

**Comment by ezsper** [comment]
Getting the same issue, but my output didn't throw any errors whatsoever.

    $ rnpm link react-native-svg
    rnpm-link info Linking react-native-svg android dependency 
    rnpm-link info Android module react-native-svg has been successfully linked 
    rnpm-link info Linking react-native-svg ios dependency 
    rnpm-link info iOS module react-native-svg has been successfully linked 

But still getting similar error

![screenshot_20160906-115854](https://cloud.githubusercontent.com/assets/798804/18279577/69dae674-742c-11e6-8dff-dde36c69cd50.png)

This doesn't happen on iOS, only on the android.

**Comment by magicismight** [comment]
It seems like you failed to link the native code
try
```
rnpm unlink react-native-svg
rnpm link react-native-svg
```

**Comment by ezsper** [comment]
Nop. I did what you said, but I already knew the results, still the same thing. Remember I did this to a new project. So I can replicate this by simply starting a new project from the cli and adding react-native-svg to package.json like I showed above, and trying to using the library on index.android.js

    $ rnpm unlink react-native-svg
    rnpm-link info Unlinking react-native-svg android dependency 
    rnpm-link info Android module react-native-svg has been successfully unlinked 
    rnpm-link info Unlinking react-native-svg ios dependency 
    rnpm-link info iOS module react-native-svg has been successfully unlinked 
    $ rnpm link react-native-svg
    rnpm-link info Linking react-native-svg android dependency 
    rnpm-link info Android module react-native-svg has been successfully linked 
    rnpm-link info Linking react-native-svg ios dependency 
    rnpm-link info iOS module react-native-svg has been successfully linked

**Comment by af7** [comment]
If this helps (I am the OP), I also use **Android** (not iOS), so could it be an issue with Android? I hope this can be addressed soon as I cannot use the library at all. Thanks!

(also, the error messages in "react-native link" could be due to my Windows environment?

**Comment by magicismight** [comment]
maybe duplicated with #83

**Comment by ezsper** [comment]
It doesn't seem to be the same issue, as the module is definitely been linked properly, couldn't it be an issue in `4.2.1`? Could you replicate the issue with the `package.json` above?

**Comment by af7** [comment]
@ezsper Do you use Windows? Because I also have this problem: https://github.com/facebook/react-native/issues/9787 (which may be the reason for non-appropriate linking)

**Comment by ezsper** [comment]
No, I'm using Mac.

**Comment by af7** [comment]
@ezsper So, this is a general problem, it needs to be addressed as even with manual linking the error appears.

**Comment by darvishzadeh** [comment]
Same problem here. Developing android in windows.

**Comment by magicismight** [comment]
Could you check the MainApplication.java file?
In MainApplication.java add the following import:

```
import com.horcrux.svg.RNSvgPackage;
```
and add the RNSvgPackage to the getPackages method like this:

```
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
        ... other packages ...
        new RNSvgPackage()
    );
}
````

**Comment by darvishzadeh** [comment]
Now it works, thanks.

But it's interesting because I've tried your suggestion in the past and I was getting a compilation error when running `react-native run-android`.

**Comment by magicismight** [comment]
I'm closing this now.
It's the native code linking problem.

**Comment by paulsoh** [comment]
For people using react-native-svg>5.1.5 (I'm not quite sure when exactly the changes were made), note that `RNSvgPackage` is now changed to `SvgPackage`. So the proper way to add it to MainApplicatoin.java would be

```java
import com.horcrux.svg.SvgPackage;
...
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
        ... other packages ...
        new SvgPackage()
    );
}
```

**Comment by ShepelE** [comment]
Thanks, paulsoh. In my case there was no 'new SvgPackage()' or 'new RNSvgPackage()' at all, so I just added 'new SvgPackage()'. Now it works

**Comment by tetogomez** [comment]
Thanks @paulsoh !!

**Comment by GANESHSHARMA1** [comment]
# Can Anyone help.

I'm getting this error during the Implementation of React Navigation.
I checked all dependencies and Many YT Videos to solve this issue but didn't get any solution..

![image](https://github.com/user-attachments/assets/baa1a2c5-f2b9-4006-8f58-39ef175402d3)

**Comment by YahyaNamir** [comment]
Delete AVD from Android Studio and re-install lastest phones version, it worked for me 100%🌟

**Comment by GANESHSHARMA1** [comment]
@YahyaNamir Thanks! I will try this.

**Comment by YahyaNamir** [comment]
> @YahyaNamir Thanks! I will try this.

Tell me what u found when you finish!

**Comment by vedantroy** [comment]
I am getting this error now. I'm not sure what `com.horcrux.svg.SvgPackage` is.

**Comment by devlopermitesh** [comment]
bro do you solve this error?
