### ISSUE TITLE
[NSURLResponse allHeaderFields]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by Malikkhoja** [react-native-community/react-native-svg#1351]
Hi,

We have been using this library for quite a while now and it just works amazing. Recently we are facing an issue "[NSURLResponse allHeaderFields]: unrecognised selector sent to instance" when we render few of the SVG's on RN 0.62.2. However earlier the same set of libraries used to work perfectly.

Is there anything that we are doing wrong? Or it's due to the lib updates or RN0.62.

Any help?

Thanks in advance

**Comment by Phecda** [comment]
Hi, this may be caused by a base64 uri, see https://github.com/facebook/react-native/issues/28583 and https://github.com/facebook/react-native/issues/28589. You can try to upgrade Flipper to 0.37.0 in `Podfile`

**Comment by Malikkhoja** [comment]
Bingo.. this worked thanks a lot @Phecda .

For any future visitor, Kindly update you all can upgrade Flipper to 0.37.0 in Podfile.

Thanks again @Phecda
