### ISSUE TITLE
Android is slow/broken (Skipping frames)

### ISSUE THREAD

**Issue by gorangajic** [react-native-community/react-native-svg#137]
I have svg map with like ~100 elements and when clicking and updating only that one, app freeze and do not update element. Is there a way to optimize this?

This is the logs from my Galaxy S6 Edge

```
09-09 18:46:20.281 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.281 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.281 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.291 15172-15172/? I/art: Alloc partial concurrent mark sweep GC freed 140(5KB) AllocSpace objects, 14(108MB) LOS objects, 9% free, 144MB/160MB, paused 385us total 10.488ms
09-09 18:46:20.301 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.301 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.301 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.311 15172-15172/? I/art: Alloc partial concurrent mark sweep GC freed 149(6KB) AllocSpace objects, 16(124MB) LOS objects, 11% free, 128MB/144MB, paused 378us total 10.545ms
09-09 18:46:20.311 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.321 15172-15172/? I/art: WaitForGcToComplete blocked for 10.156ms for cause Alloc
09-09 18:46:20.321 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.331 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.341 15172-15172/? I/art: WaitForGcToComplete blocked for 9.913ms for cause Alloc
09-09 18:46:20.341 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.341 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.351 15172-15172/? I/art: WaitForGcToComplete blocked for 9.940ms for cause Alloc
09-09 18:46:20.351 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.361 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.381 15172-15172/? I/art: WaitForGcToComplete blocked for 12.629ms for cause Alloc
09-09 18:46:20.381 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.391 15172-15172/? I/art: Waiting for a blocking GC Alloc
09-09 18:46:20.401 15172-15172/? I/art: WaitForGcToComplete blocked for 8.350ms for cause Alloc
09-09 18:46:20.401 15172-15172/? I/art: Starting a blocking GC Alloc
09-09 18:46:20.601 15172-15172/? D/ViewRootImpl: ViewPostImeInputStage processPointer 1
09-09 18:46:20.601 15172-15172/? I/Choreographer: Skipped 98 frames!  The application may be doing too much work on its main thread.
```

didn't test on iPhone but in simulator everything is fine.

**Comment by gorangajic** [comment]
After some digging in the code, I have figured how we can improve the performance of the android part.

* call `hitTest` method only on elements that have events(onPress..) attached. hitTest method is called for all elements in the svg three it does not matter if someone is listening for the event or not. There is `isResponsible` method not sure why it's not used ? 

* try to cache `hitTest` method or bitmap. If you have too many elements it will go and redraw every element to figure out if it's pressed or not. And that can make application not responsive and skip frames

**Comment by magicismight** [comment]
Thanks for reporting this.
We have to run `hitTest` for every element in SVG util find a correct target element,
because for some case like this:
![image](https://cloud.githubusercontent.com/assets/7693239/18502782/d57ac9de-7a8b-11e6-92fc-5eae7f349edf.png)
If you just bind an `onPress` callback on the circle but do not run the hitTest method for the Rect element.
The onPress callback will be called when press on the Rect area inside circle.

I'll try to improve this later, I'm working on the Text elements refactoring those days.

**Comment by gorangajic** [comment]
What do you think is it possible to improve the current code? And how would you do it ? Maybe you can guide me and I will try something until you have time to tackle it yourself.

**Comment by magicismight** [comment]
1. calculate and cache the boundingBox for every elements inside SVG.
2. test if the touch point is inside boundingBox before run the test on bitmap.

**Comment by weixingsun** [comment]
hi there, 
the original hitTest method is too heavy to run on a cellphone, 
so i replaced RNSVGPathShadowNode.hitTest as following(it's working for me, but there maybe something wrong with other scenarios) :
    @Override
    public int hitTest(Point point, View view, @Nullable Matrix matrix) {
        RectF rectF = new RectF();
        mPath.computeBounds(rectF, true);
        Region region = new Region();
        region.setPath(mPath, new Region((int) rectF.left, (int) rectF.top, (int) rectF.right, (int) rectF.bottom));
        if (region.contains(point.x, point.y)) {
            return view.getId();
        }else{
            return -1;
        }
    }

**Comment by evollu** [comment]
I find there is a pull to react native arc that tries to improve performance.
https://github.com/facebook/react-native/pull/9486
He claims that using TextView instead of Canvas will boost the performance. I don't know any android but may be this is useful?

**Comment by gorangajic** [comment]
Hi @evollu did you test that pull request on ReactNativeArt?

**Comment by evollu** [comment]
no

**Comment by petermikitsh** [comment]
I'm seeing perf issues on Android with a large SVG as well (~200 `Path` elements). The app runs slowly in the emulator. I've also observed my app crashing once I get to the scene containing the SVG, however I haven't checked the stacktrace to confirm that the crash is directly rated to `react-native-svg`.

**Comment by davidbonnet** [comment]
The current version of `react-native-svg` is terribly slow on Android devices. We built an app with a single view containing an SVG with a path rendering a list of points generated from a finger stroke. On a Galaxy Tab Active and a Galaxy S4, the latency goes up to several seconds seconds and/or drops many touch locations.

On the other hand, this same app behaves smoothly on iOS devices, as old as an iPhone 5.

Are there any Android performance enhancements planned?

**Comment by msand** [comment]
@stowball I've attempted some performance optimization in my latest PR, can you test that and see if it helps? https://github.com/react-native-community/react-native-svg/pull/596

**Comment by stowball** [comment]
👍

**Comment by msand** [comment]
I think rewriting to use VectorDrawable would be more work than just re-inventing their wheel and adding a bitmap cache per shadow node, or perhaps only on the G nodes. But, i'm not sure if it's worth the memory / computational cost tradeoff. Would need better performance tests and measurements to base that kind of decisions on. Would you have any available?

**Comment by msand** [comment]
As @evollu is suggesting we should merge the changes from here: https://github.com/facebook/react-native/pull/9486
And, we could add a cached attribute to the G element, to allow opt-in bitmap caching of subtrees, so use-case dependent memory/computation tradeoffs can be tailored for.

**Comment by msand** [comment]
Actually, I now realize that the Svg element is probably the correct place for a texture/bitmap cache.

**Comment by msand** [comment]
I've ported the changes from the PR to ReactNativeART, to use a TextureView in Android https://github.com/react-native-community/react-native-svg/pull/596/commits/f3ea54cd26676013254ce133dd355f2ff1a3d57d
Any help in testing would be much appreciated 💃

**Comment by stowball** [comment]
Awesome. Will try and test it over the next few days

**Comment by msand** [comment]
The TextureView was causing issues, I reset the branch to point before the commit for the PR. I think the other optimisations seem stable/functional.

**Comment by derekbar90** [comment]
@msand I've recently hit these issues as well and saw your commit here and thought this could help a ton: https://github.com/react-native-community/react-native-svg/commit/f3ea54cd26676013254ce133dd355f2ff1a3d57d

But then saw your most recent comment. 

Can you provide any more insight into how I can fix performance on Android. My issues are due to animations and the Bitmap class causing memory issues as it builds each frame creating back pressure against the messaging queue on the react-native bridge.

**Comment by RichardLindhout** [comment]
+1

**Comment by msand** [comment]
There is support for animation with useNativeDriver now and the code has been optimized for unitless numbers instead of strings, try using that, and if you have static parts in the animation, split it up into three different svgs, a static background, animated layer and a static foreground, such that the animated parts are as computationally small and few as possible. And utilize shouldComponentUpdate / PureComponent where possible. These principles should enable relatively smooth animations for most usecases. Also, you probably want to upgrade javascriptcore in android, I've seen massive speedups from that.

**Comment by msand** [comment]
If you're still having performance issues, you should probably profile your code and find your bottlenecks and attempt to optimize those. There's not much to be done here without specific problematic cases. Closing...
