### ISSUE TITLE
How to use ClipPath?

### ISSUE THREAD

**Issue by DanielApt** [react-native-community/react-native-svg#138]
I've noticed there's a [ClipPath element](https://github.com/react-native-community/react-native-svg/blob/master/elements/ClipPath.js), but I can't find any documentation on it.

I have tried using:

```js
<Svg width={this.props.width} height={this.props.height}>
      <Defs>
        <ClipPath id="myClip">
            <Circle cx="30" cy="30" r="20" fill="red"/>
            <Circle cx="70" cy="70" r="20" fill="red"/>
        </ClipPath>
      </Defs>

      <Rect width="100%" height="100%" clip-path="url(#myClip)" fill="blue"/>
</Svg>
```

Nothing happens. Help is appreciated.

**Comment by magicismight** [comment]
You can find the example [here](https://github.com/react-native-community/react-native-svg/blob/master/Example/examples/Clipping.js)

**Comment by DanielApt** [comment]
Thanks! So I was using the wrong attribute. One should use `clipPath` not `clip-path`.
