### ISSUE TITLE
Rendered Image color change to black

### ISSUE THREAD

**Issue by theromie** [react-native-community/react-native-svg#1388]
I am react-native-svg-transformer lib to conver svg as component but some of image color change to black

# Bug
Black color is producing

Library version

> "react-native-svg": "^12.1.0",
> "react-native-svg-transformer": "^0.14.3",

Describe what you expected to happen:

1. Image should show as it is in actual

Attached Screenshots
Expected - [https://www.flaticon.com/free-icon/megaphone_1292779?term=3d%20Megaphone&page=1&position=2](Url)

Output - [https://ibb.co/PCCQ530](Url)

**Comment by aliyev-avaz** [comment]
Hİ:
I was getting the same error. This is the solution.
The problem is not in the library. photoshop linearGradient was turning wrong. It disappeared after opening and fixing the SVG file.
Video link: https://youtu.be/RpudYZ_n0-0

**Comment by Harukisatoh** [comment]
> Hİ: I was getting the same error. This is the solution. The problem is not in the library. photoshop linearGradient was turning wrong. It disappeared after opening and fixing the SVG file. Video link: https://youtu.be/RpudYZ_n0-0

The video doesn't exist anymore, do you remember the solution?
