### ISSUE TITLE
How to re-create (re-render) SVG element?

### ISSUE THREAD

**Issue by proteye** [react-native-community/react-native-svg#142]
Hello.
I have created <Rect /> element. Then I have got touch event and changed Rect width property. But Rect was not re-drawn at the render() function was called.
New elements were drawn, but old elements were not re-drawn with new properties.
But if these elements will have hided before they are re-draw - they will be shown successful.
What can I do?

**Comment by proteye** [comment]
I have found a method to resolve this problem. I have added increasing the KEY parameter:
<Svg width={width} height={height} key={this.k++}>

**Comment by kelset** [comment]
Thanks @proteye for your workaround, it worked for me too.
But I have a feeling it should not be necessary... @magicismight is there an explanation for the `SVG` component to not re-render when state or props is updated (on old elements)?

**Comment by JCMais** [comment]
Having this same question.

**Comment by msand** [comment]
I have a PR open fixing this: https://github.com/react-native-community/react-native-svg/pull/596

**Comment by saad277** [comment]
thanks @proteye
