### ISSUE TITLE
onPress event lost after nested rotations

### ISSUE THREAD

**Issue by fauno** [react-native-community/react-native-svg#143]
Hi!  I have a `<G>` component with an onPress action that works.  It also works when I rotate it.  But when I rotate the `<G>` that contains it, the onPress action is lost:

To make myself clear, this works:

``` jsx
<G>
  <G onPress={}></G>
</G>
```

And this:

``` jsx
<G rotate="90">
  <G onPress={}></G>
</G>
```

And this:

``` jsx
<G>
  <G rotate="-90" onPress={}></G>
</G>
```

But not this:

``` jsx
<G rotate="90">
  <G rotate="-90" onPress={}></G>
</G>
```

What could be happening?

**Comment by fauno** [comment]
I solved it by using an intermediate <G> component:

```jsx
<G rotate="90">
  <G onPress={}>
    <G rotate="-90"></G>
  </G>
</G>
```

**Comment by msand** [comment]
Press handling with transforms should be working correctly now.
