### ISSUE TITLE
Text component not rendering on latest React Native

### ISSUE THREAD

**Issue by alexfaber2011** [react-native-community/react-native-svg#1438]
# `Text` component not rendering on latest React Native

The `Text` svg component is not rendering.  Other components like `Rect` are.

#### Preview
<img width="463" alt="image" src="https://user-images.githubusercontent.com/2359612/90195658-ac5c1880-dd8f-11ea-948f-8c8153ca7a82.png">

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 224.96 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/alexfaber/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/alexfaber2011/reactnativesvgtest
2. cd reactnativesvgtest
3. yarn
4. yarn ios
5. yarn android
6. ...

Describe what you expected to happen:

1.  Open app and notice you see a grey square, but not any text below

**Thank you all for your amazing work on this amazing project**

**Comment by Foggyhazel** [comment]
Have you tried setting fill color on Text? I had similar issue after upgrading RNSVG from v11 to 12.

**Comment by alexfaber2011** [comment]
That was precisely problem: missing `fill` prop on `Text`.  Thank you @Foggyhazel for suggesting that.
