### ISSUE TITLE
App crash when installing react-native-svg

### ISSUE THREAD

**Issue by gandarain** [react-native-community/react-native-svg#1450]
# Question

Hello,
I try to show svg file in my react native project with this library.
But after I install this library via npm (npm install react-native-svg), my app force close. I dont why, I cant found the error.
Any solution to fix this ?

react-native : 0.61
react-native-svg: ^12.1.0

**Comment by KieranO547** [comment]
Believe I'm having the same issue, for me the crash occurs when I try to import an SVG, there's no error messages being produced it just force closes - not sure if there's a way to get a log out or anything. I've setup in an expo bare workflow project.

**Comment by luifermoron** [comment]
Same.
I solved it by switching to "New build system"(not sure if it could affect some other library in future, but it works now). Also I noticed my credentials needed updated, so I set passwords again.

**Comment by Neel97** [comment]
Hey @gandarain, I also faced the same issue found the solution in the below link:

https://github.com/react-native-community/react-native-svg/issues/689#issuecomment-389382265

I had to add the following code in android/app/build.gradle -> inside dependencies
```
compile(project(':react-native-svg')) {
    exclude group: 'com.facebook.react', module: 'react-native'
}
```

Hope so, this works for you too.

**Comment by gandarain** [comment]
Thanks for your solution,
My problem solve, after I install 
- react-native-svg
- react-native-svg-transformer

and setup my metro.config.js

````
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
````
