### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGRect

### ISSUE THREAD

**Issue by iammilaad** [react-native-community/react-native-svg#1466]
i'm using last version of react-native-svg and my application build success in IOS but i have Tried to register two views with the same name RNSVGRect error.

**Comment by SopoB** [comment]
@iammilaad How did you resolved it?

**Comment by raymondjacobson** [comment]
@iammilaad How did you resolved it?

**Comment by JacobDel** [comment]
Any updates on this?
