### ISSUE TITLE
zoom plan?

### ISSUE THREAD

**Issue by weixingsun** [react-native-community/react-native-svg#147]
as we known svg is vectorial, so it'll be super cool to support zooming, right?

**Comment by Introvertuous** [comment]
Until animations are implemented you can achieve something similar with the react native [animated](https://facebook.github.io/react-native/docs/animations.html) library. example (note it is smoother than it appears): ![](https://lh3.googleusercontent.com/MQYstbZgt0nPxWYbc_iXAwtx960kZaZHTri2faTJI_Ib8URekz8jUtTbdZA2fh5laaBax-RJo1mbJvIVUcCLFGwdPvVo4cvC-q54yUAB8XVdqA75Pj__vb_x6JiBlxKrnyzqlFyI5x1b9BYrX4YCQHhH2x3wKRpHGcApYeIHnLhpIl1KKJjJz3MQYeGtkovLn9cUl2OOd80ZxIcJ0KKuHfO751JLkojxzbeqFYHWlIyNK-Th2fM-hN5Ado7s4Djav5s3t1gu3QkEqv_LNUNw-mgz6vjr1WeoIeZLPEk3VZZtf7mRoGSUbA3yV4XAiMR0vt8OQl6Zthm0tf2CPzzQDzzOJVE4MAnecuaIFnuAlNtSSmyWJlS9qnpGHFpj8yuxYLu5zmBBrxf9tUZmRi7fpkXjNjv0OifjUWCFyKzaMnhUiGl_2HXXecztAFAc5bNv-bXoNtXghXN4xKKljCdzCl3QeG62zd0JF6A7jJ6MJ37WhcGZrxhtIGv12lIPkJdWBVB5skxLpEGzoMJZ7psoiOJWDCGPS6U01MNONQSAhJNwC3WvhKAdkihWV6VY5IPeWSpgZnn7wDzzAB_47IgoRkR-O0zjNorWPxGxlqeZFxKqeaas=w956-h200-no).

**Comment by ridwan85** [comment]
Based on your code. manage to made an example of [this](https://snack.expo.io/B1dKQ83YW)

**Comment by msand** [comment]
I've made a library for zoom-and-pan https://github.com/msand/zoomable-svg
Similar logic could be used to add https://svgwg.org/svg2-draft/interact.html#ZoomAndPanAttribute
