### ISSUE TITLE
No ViewManager defined for class RNSVGCircle

### ISSUE THREAD

**Issue by abeikverdi** [react-native-community/react-native-svg#148]
This is the error I got after installing the package and linking it with android:
![capture](https://cloud.githubusercontent.com/assets/5679568/18821410/c3dc3128-83e0-11e6-899e-93ff9f6dcaf1.JPG)

**Comment by vance-liu** [comment]
the same +1

**Comment by vance-liu** [comment]
It's the native code linking problem. just look at [#135](https://github.com/react-native-community/react-native-svg/issues/135), follow and work well.

**Comment by legg** [comment]
Works for me with 
    "react": "15.3.2",
    "react-native": "0.33.1",
    "react-native-svg": "4.3.1"

I can replicate the error with react-native@0.34.1

**Comment by iqbalshirol** [comment]
I just created my activity as a sub-class of `ReactActivity` and it fixed this problem.

**Comment by lai32290** [comment]
I'm having this issue for `react-native@0.52.2`

**Comment by iqbalshirol** [comment]
@lai32290 I have fixed it for the version (0.52.1) using the `ReactActivity`. Please let me know if you have imported the correct SVGPackage.

**Comment by lai32290** [comment]
@iqbalshirol , do you mean to `android/app/src/main/com/my-project/MainActivity.java` extend `ReactActivity`? My project is already extending it.
The process what I did is:
```
$ react-native init myProject
$ cd myProject
$ npm install react-native-svg --save
$ react-native link react-native-svg
```

**Comment by lai32290** [comment]
@msand  it's working for me, finally, thanks for your help!
