### ISSUE TITLE
Text origin is wrong compared to web browsers

### ISSUE THREAD

**Issue by julienfouilhe** [react-native-community/react-native-svg#151]
Hi,
First of all, thanks a lot for this library to everyone involved!

Compared to web browsers, text is not rendered the same.
If I take this svg:

``` html
<svg>
  <rect x="10" y="10" fill="red" width="100" height="100"></rect>
  <text x="10" y="10">text</text>
</svg>

```

It renders like this in web browsers (text is above rect):

<img width="111" alt="screen shot 2016-10-01 at 8 34 06 pm" src="https://cloud.githubusercontent.com/assets/867741/19016324/8392f496-8816-11e6-8c9c-37b324e5fd87.png">

Wheras it renders like this using React Native Svg (text is inside):

``` html
<View>
  <Svg width="200" height="200">
      <Rect x="10" y="10" fill="red" width="100" height="100"></Rect>
      <Text x="10" y="10" fill="black">text</Text>
  </Svg>
</View>
```

<img width="108" alt="screen shot 2016-10-01 at 8 43 06 pm" src="https://cloud.githubusercontent.com/assets/867741/19016360/af4f6082-8817-11e6-8ce0-1651b20946e5.png">

Is there a way to have the same behaviour as web browsers?

Thanks

**Comment by magicismight** [comment]
We will refactor the transform system in the next major version.
And try to implement the same behavior as web do.

**Comment by msand** [comment]
I think this should be fixed in the latest versions, @julienfouilhe can you double check?
