### ISSUE TITLE
parity with web svg and usage with React Native Web

### ISSUE THREAD

**Issue by faceyspacey** [react-native-community/react-native-svg#155]
Hey everyone, I'm working on a React Native Web project and am porting various vectors I made in React Native using this package to _React Native Web_, and the thing is my simple vectors almost port perfectly. 

What I first did was create a package that renames standard HTML components provided by React to uppercaseFirst versions, eg:

```
export const Svg = 'svg';
export const Circle = 'circle';
export const Path = 'path';
```

So, as I said, my vectors are pretty simple. The first challenge I ran into was that instead of `scale={1.5}` it needs to be `transform="scale(1.5)"`, which is exceedingly small of a an interface change. So I'm wondering why `react-native-svg` didn't try to preserve the web's interface? And, if there are any attempts to do so or what hurdles people see in making it happen??

For my small svgs, I can pretty much wrap  _react-native-svg_ and give it the same interface as you have in the web. Given the large number of _properties_, I'm assuming at some point, achieving feature parity becomes burdensome. I'm wondering if anyone has gone this route or thought about this and where the breakdown is? From where I'm currently standing it seems like an achievable goal and one that should happen, whether in this package or another.

**Comment by 3rd-Eden** [comment]
To combat this we've had to write a wrapper for svg, that exported exactly the same interface as react-native-svg. Easy stuffs, but still pointless boiler plate code if it just followed the same API's

**Comment by talarari** [comment]
im running into issues using this with react-native-web as well. 
https://github.com/necolas/react-native-web/issues/390

are there plans of supporting react-native-web platform?

**Comment by 3rd-Eden** [comment]
https://github.com/godaddy/svgs

It's a project I wrote to work around this limitation. It uses the same syntax for syntax that react-native-svg uses for web. This allows you to use one module (in this case svgs) for both react and react-native based svgs.

**Comment by talarari** [comment]
Awesome, ill give it a try soon, thanks!

**Comment by msand** [comment]
It now supports the transform attributes and is much more spec conformant. But there are lots of features in the spec, with varying support in the ever-green browsers, but missing from react-native-svg still. PRs very welcome 😄
