### ISSUE TITLE
Error when component return null

### ISSUE THREAD

**Issue by gorangajic** [react-native-community/react-native-svg#159]
This code should not throw error

``` jsx
class Example extends React.Component {
    render() {
        return null;
    }
}

class Main extends React.Component {
    render() {
        return (<Svg>
            <Example />
        </Svg>);
    }
}
```

work around this is to instead of using `return null` to use `return <G />`

**Comment by mienaikoe** [comment]
+1
Still Seeing this in December. 
Error I'm seeing:
```React.createElement: type shuld not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).```

**Comment by magicismight** [comment]
Can you provide more information?
The component renders null works fine in Example here:
https://github.com/magicismight/react-native-svg-example/blob/master/examples/Svg.js#L108

**Comment by msand** [comment]
Yeah, seems to work fine. Will close for now.
