### ISSUE TITLE
"_OBJC_CLASS_$_RCTFont" Symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by edo1493** [react-native-community/react-native-svg#160]
Hello, 
I am getting this error in Xcode with react-native 0.33.1 and react-native-svg 4.3.1. I think it's related to this (https://github.com/react-native-community/react-native-svg/pull/124/commits/8bd66fc2b09a5fb2a8b4b3727fadb7cf8e696879), but I am not sure how to fix it. 

Has anyone seen this?

**Comment by julienfouilhe** [comment]
Hi @edo1493, are you using cocoapods to integrate react native in an existing ios app? I remember having a similar issue, here is what the line for react native svg looks like in my Podfile:

```
pod 'React', :path => 'path/node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
    'RCTNetwork',
  ]
```

**Comment by edo1493** [comment]
@julienfouilhe, Yes, I am and I thought that could have been my problem.

**Comment by msand** [comment]
This is probably an outdated issue, for reference check e.g. https://github.com/msand/SVGPodTest
