### ISSUE TITLE
svg does not response on event onPress while running on devices with 3d Touch(eg:iPhone6s)

### ISSUE THREAD

**Issue by xiankuncheng** [react-native-community/react-native-svg#161]
I'm developing an app with svg to draw the seat site of an theater for users to buy the tickets left. It works fine on devices without 3d touch(eg: iphone 5). Unfortunately, it falls out on devices with 3d touch(eg: iphone 6s).

Any idea how to fix this or did i get something wrong?

**Comment by gorangajic** [comment]
maybe it's related to #157 my [quick fix](https://github.com/gorangajic/react-native-svg/commit/f71196c4f39bf87229e19be86a05c5b5685cd8b6) for that was to ignore the move event

**Comment by jacktionary** [comment]
@gorangajic thank you very much. what you mentioned save me tons of time.

**Comment by edo1493** [comment]
I am re-opening this cause I am having the same issue. iPhone 6 vs 7. I was wondering why the quick fix wasn't merged and if someone tested it properly. Thanks.

**Comment by edo1493** [comment]
@jacktionary Have you seen this? thanks.

**Comment by jacktionary** [comment]
@edo1493 I fixed this by changing my local code. Maybe this quick fix hasn't be merged yet.

**Comment by oakis** [comment]
You could also wrap your SVG in a TouchableOpacity. That solved my problem.

```
<TouchableOpacity onPress={() => doStuff()}>
    <Svg />
</TouchableOpacity>
```

**Comment by cristian-milea** [comment]
the TouchableOpacity is not a good workaround. I want to click only an element of the svg.

how can i achieve that without triggering move on device?

**Comment by msand** [comment]
Could you try again with the latest commit in the master branch? I've fixed several related issues and might have fixed this at the same time.

**Comment by msand** [comment]
I think I have (gesture) interactions between native animated transforms and normal svg transforms working correctly now as well: https://github.com/react-native-community/react-native-svg/commit/8c05da043dea3f8d04420c2d7c9c11733e22258b

**Comment by msand** [comment]
I think this should be fixed now, closing until further notice.

**Comment by msand** [comment]
I think this should be fixed now, closing until further notice.

**Comment by vadermemo** [comment]
Closed? really? This is a huge bug!

**Comment by msand** [comment]
@vadermemo Are you able to reproduce this issue with the latest version? E.g. inside this project: https://github.com/msand/react-native-svg-e2e

I don't have access to any iPhone, so it's a bit hard for me to test this in any way, and therefore quite hard to fix in case there are issues remaining. But, at least if you can make a reproducible demo e.g. fork the e2e test repo, then we should certainly reopen this.
