### ISSUE TITLE
Path d= value not working with generated D3 shape.line()

### ISSUE THREAD

**Issue by MarvinAmador7** [react-native-community/react-native-svg#164]
Hey Guys I'm using D3 shape module to generate a line path 

```
 const lineShape = d3.shape.line()
    .x((d) => xScale(xAccessor(d)))
    .y((d) => yScale(yAccessor(d)));
```

Then later in react native : 

```
<Path d={lineChartConfig.path} strokeWidth={1.5} stroke={color} fill={'none'}/>
```

This is working ok in IOS but not in android 
![image](https://cloud.githubusercontent.com/assets/13001660/19565162/340e3a48-96a3-11e6-9295-0d081792c143.png)

And this is the code that D3 generate for the d= prop

```
M0,270.64L47.22444810939556,161.72L94.44669466413696,19.920000000000016L141.67114277353252,64.68L188.89283893961033,243.07999999999998L236.4464194698052,163.07999999999998L284,271.08
```

I have tested it here https://naiksoftware.github.io/svg.html and it works well

**Comment by magicismight** [comment]
We have moved the `d` serialization to native side.
And in `react-native-svg@4.6.1`  this works fine.
![image](https://cloud.githubusercontent.com/assets/7693239/21853575/ab487f1a-d852-11e6-86ba-a17a19a3d5d9.png)
