### ISSUE TITLE
No component found for view with name "RNSVGPath"

### ISSUE THREAD

**Issue by FreshFlesh** [react-native-community/react-native-svg#165]
Hi,

Sorry for polluting the issue tracker but i can't manage to get it working..
I have this very simple component:

```
import React, { Component } from 'react';
import Svg, { Polygon } from 'react-native-svg';

class GoodIndicator extends Component {

  constructor(props) {
    super(props);
  }

  render() {
    return (
        <Svg width="14" height="12">
            <Polygon
              fill="#FFFFFF"
              points="347,113636 22,3787205 346 23,5553156 350,454545 28,261696 360 18,1765951 358,886364 17 350,454545 25,9085058"
            />
        </Svg>
    );
  }

}

export default GoodIndicator;
```

Yet i have the following error:
`No Component found for view with name "RNSVGPath"`

rnpm says it is correcty linked:
```
rnpm-install info Android module react-native-svg is already linked
rnpm-install info iOS module react-native-svg is already linked
```
and i also check manually in the XCode project.

Any idea?

"react": "15.3.2",
"react-native": "0.35.0"

**Comment by gorangajic** [comment]
You have the problem with a linking component, `rnpm` is merged into react-native so you should link native component using `react-native link react-native-svg`

**Comment by FreshFlesh** [comment]
Hi, thanks for your help!

I actually linked it with the command you mention, i exactly followed what is in the README.

How can i check if the lib is properly linked?

I checked in the Xcode project, i have:
* `RNSVG.xcodeproj` in "Libraries"
* `libRNSVG.a` in "Link Binary With Libraries"
* `$(SRCROOT)/../node_modules/react-native-svg/ios` in "Header Search Paths"

**Comment by gorangajic** [comment]
Did you run the project again after linking?
Maybe stupid question because I have just tried and it works for me. 

```
react-native init TestProject
npm install react-native-svg
react-native link react-native-svg
react-native run-ios
```

**Comment by FreshFlesh** [comment]
i tried what you did, copying my source files to the new project and it worked.
I don't know what happened with the linking... thanks!
