### ISSUE TITLE
Automatic linking broken on Android

### ISSUE THREAD

**Issue by Etheryte** [react-native-community/react-native-svg#170]
Not sure if I should report the issue here or on the RN main repo.  

**Versions:**
react-native: 0.36.0
react-native-svg: 4.3.1

**What I did:**
On an existing project, that already has other dependencies which have been linked manually:
```zsh
npm install react-native-svg --save
react-native link react-native-svg
```
Then included a sample SVG from the readme of this project in the code as appropriate, after which:

```zsh
cd android && ./gradlew assembleRelease
```

**What I expected to happen:**
The build to succeed.

**What happened instead:**
```zsh
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/etheryte/GitHub/project/android/app/build.gradle' line: 141

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-svg' could not be found in project ':app'.
```

**The problem:**
The file `./android/app/build.gradle` was modified correctly:

```gradle
dependencies {
    compile project(':react-native-svg')
    ...
}
```
However the file `./android/settings.gradle` was **not modified**.

**The solution:**
Adding the appropriate lines in `./android/settings.gradle` as if doing the linking manually solves the problem.

```gradle
include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
```

**Further details:**
I haven't tested if the issue occurs on a vanilla set-up without any other linked modules added. The automatic linking works fine for iOS.  
The automatic linking **reported** to have succeeded for both platforms.

**Comment by theseansy** [comment]
Thanks for documenting this, helped me out with the temporary solution

**Comment by magicismight** [comment]
This had been fixed in the latest react-native version.
I'm closing this now.
