### ISSUE TITLE
viewConfig is not defined

### ISSUE THREAD

**Issue by tuckerconnelly** [react-native-community/react-native-svg#171]
Was getting this when trying to render a `Animated.createAnimatedComponent(Circle)` within an `Svg`. Think it was broken by [this commit](https://github.com/facebook/react-native/commit/c9960817eea008b2703657066212002557e0d939) on Oct 12.

Was able to fix it in my fork by adding:

```
    componentDidMount() {
        this.viewConfig = this.root.viewConfig;
    }
```

to `Shape`.

**Comment by magicismight** [comment]
This seems like has been fixed in latest react-native version.
I'm closing this now. feel free to reopen this if the problem still exists
