### ISSUE TITLE
lodash problem

### ISSUE THREAD

**Issue by swb2016** [react-native-community/react-native-svg#172]
When I use this plugin, my app create a red box which contains some words like "_lodash2.default.isNil is not a function. (In '_lodash2.default.isNil(a)', '_lodash2.default.isNil' is undefined)". Can you tell me how to solve this problem?

**Comment by swb2016** [comment]
./lib/Matrix2D.js

```
setTransform = function(a, b, c, d, tx, ty) {
        // don't forget to update docs in the constructor if these change:
        this.a = _.isNil(a) ? 1 : a;
        this.b = b || 0;
        this.c = c || 0;
        this.d = _.isNil(d) ? 1 : d;
        this.tx = tx || 0;
        this.ty = ty || 0;
        return this;
    };
```

These code may help you to solve.

**Comment by gorangajic** [comment]
you have an older version of the `lodash` installed

```
npm install lodash@4
```
