### ISSUE TITLE
Is it possible to resize an SVG?

### ISSUE THREAD

**Issue by kelset** [react-native-community/react-native-svg#173]
As in the title, by reading the [README.md](https://github.com/react-native-community/react-native-svg/blob/master/README.md) I'm not able to figure out if there is a simple way to have the SVG resized without having to manually change the various parameters.

The use case is this: I want to have an SVG image as a component (let's call it `Draw`), and a screen component in which I want to import it (let's call it `App` ). But I can't know for sure the size of the View in which my `Draw` element will be placed, but I'd like to see the full image resized - the same way an `Image` would be resized.
Is there a simple way to handle it?

The only "workaround" I managed to think of it the one I've implemented in this [demo](https://github.com/kelset/react-native-svg-testing) - basically, I ask the View component that will contain the SVG its dimensions and set them as the width and height of the various elements.
But it seems a bit too complex, and error-prone.

**Comment by gorangajic** [comment]
Not sure what you want to accomplish but you can use [viewBox](https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox) to resize svg component

https://rnplay.org/apps/CdJI3w
```jsx
<Svg style={{ width: 100, height: 100 }} viewBox="0 0 50 50">
    <Circle r="25" fill="red" x={25} y={25} />
</Svg>
```
circle will be 50 units because element width/height is two times bigger than viewBox width/height

**Comment by kelset** [comment]
Hey @gorangajic, thanks for the hint! (tbh it should be added to the readme, it is quite huge! - Maybe I'll do a PR this weekend)

That said, adding viewBox was not enough for what I wanted to achieve - but it put me on the right track so now it does (you can check the code [here](https://github.com/kelset/react-native-svg-testing/blob/master/src/Draw.js)).
To give you an use case: let's say my SVG draws an icon that will appear in different screens of my app. I don't want to have N versions of the same SVG picture where the only difference is in the SVG height and width: moreover, since we are in the mobile realm, it is not optimal to have something with fixed dimensions, given the huge amount of screen sizes and resolutions.

**Comment by gorangajic** [comment]
Not sure but first think that get to my mind is that you can use something like `onLayout` and create `ResizableSvg` component something like this

```jsx
class ResizableSvg extends React.Component {
    constructor(props) {
	      super(props);
   		  this.state = {
       	    width: 0,
        	  height: 0,
		    };
    }
 
    render() {
        const { width, height } = this.state;
	    const isSet = width !== 0 && height !== 0;
        return (<View 
                style={this.props.style}
                onLayout={(e) => 
                    this.setState({
                        height: e.nativeEvent.layout.height,
                        width: e.nativeEvent.layout.width
                    })
                }
            >
              {isSet &&
            <Svg style={{ width, height }} viewBox={this.props.viewBox}>
                {this.props.children}
            </Svg>}
        </View>);
    }
}
```

and then use it something like this
```jsx
<ResizableSvg style={{ flex: 1 }} viewBox={"0 0 100 100"}>
    <Circle r={50} x={50} y={50} fill="green"/>
</ResizableSvg>
```

demo => https://rnplay.org/apps/MUlcbw

**Comment by kelset** [comment]
That's what I did in my demo I linked earlier ;)
(I think the issue can be closed tbh)

**Comment by gorangajic** [comment]
Sorry didn't saw your demo, only first time when you open up the issue.

btw I don't have access to close issues, you can do it. I am just subscribed because I want to keep track of updates to this lib

**Comment by kelset** [comment]
Oh you are right - anyway thanks for the help provided :)
