### ISSUE TITLE
Element drop shadow / blur

### ISSUE THREAD

**Issue by julesmoretti** [react-native-community/react-native-svg#176]
Hello Everyone:

Having a drop shadows and blurs would be really really appreciated :)

@brentvatne @chengyin @MoOx @mattapperson @gorangajic 

Thank you.

Jules

**Comment by mattapperson** [comment]
Could you explain your request a little more?

**Comment by MoOx** [comment]
Can you stop poking me? I don't understand why you poke me as I never really used this module.

**Comment by mattapperson** [comment]
@MoOx he is poking every contributor...

**Comment by MoOx** [comment]
According to this https://github.com/react-native-community/react-native-svg/graphs/contributors I am not really a contributor... Anyway, this is not a good idea :)

**Comment by mattapperson** [comment]
hahah yea, but I was just playing captain obvious :)

**Comment by chengyin** [comment]
Please stop at people unless for direct reasons. Don't mass spam the contributors for feature requests, or your bug reports. This is a common courtesy.

**Comment by julesmoretti** [comment]
@MoOx I poke every contributors to modules that are not very responsive in getting back to issues. I work at a large product company now and we would love this module to work efficiently for our future pipline's ;)...

Therefore,

@mattapperson Currently the SVG module does not offer any form of drop shadow integretion (feGaussianBlur) nor things like transform-origin (which is another issue but hey...). So it would be great if an element like a Rect, Circle, Path and so on... could have a drop shadow with the ability to set and x y offset, drop shadow color, drop shadow opacity, drop shadow radius and so on... and ideally have the feGaussianBlur integration too in order to blur the entire svg Polypath.

@chengyin - I would love to, but then please suggest a more efficient methodology to getting solutions/responses quicker ;)

Cheers all!

**Comment by mattapperson** [comment]
@julesmoretti For faster response, submit pull requests :)
Open source projects like this are a labor of love by contributors, we offer what little free time we have to the community as part of a sharing culture. While we find it EXTREMELY cool that a company like Frog Design would want to use this project... please keep in mind that we contributors help maintain this project for free. Typically features are added when someone needs it that has the ability to add the feature and they then submit a pull request, not just on-demand when users ask.
If however you need faster response times, or particular features added quickly, those of us that own agencies such as myself are more then happy to offer paid support and SLAs on these and other modules that would give you the level of support and response times you seem to need. If that interests you, please feel free to reach out to me via email at matt@appersonlabs.com.

**Comment by msand** [comment]
Work on filters tracked here: https://github.com/react-native-community/react-native-svg/issues/150
