### ISSUE TITLE
OnPress Android - onPress event not always detected

### ISSUE THREAD

**Issue by maxg7** [react-native-community/react-native-svg#178]
I have a view with a series of circles within an svg view that each have their own onPress event. When running in iOS on the emulator or on an iPhone the onPress events are fired as expected and immediately. When running on an Android device directly I'm finding that on almost every onPress event nothing is happening. If I double- or triple-click on the circle sometimes that'll get it to work. 

Is this a known issue or are there any known culprits for this behavior? 

Cheers.

**Comment by gorangajic** [comment]
duplicated https://github.com/react-native-community/react-native-svg/issues/157

**Comment by maxg7** [comment]
Yep, looks like a duplicate. I had even searched before submitting but thanks for linking. I'll close this one.
