### ISSUE TITLE
crash from compile in android.

### ISSUE THREAD

**Issue by jjhesk** [react-native-community/react-native-svg#182]
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

**Comment by armres** [comment]
1. what version gradle, node.js, react-native and react?
2. "npm cache clear", try to remove "node_modules\react-native-svg\android\build" and re-build

**Comment by djcsdy** [comment]
I have this problem with:

 * Gradle 2.4 (via the Gradle wrapper installed by `react-native init`).
 * node.js 6.9.1
 * react 15.4.1
 * react-native 0.39.0

```ps
npm cache clear
rm -rf node_modules android/build android/app/build
npm install
react-native run-android
```

eventually yields the same error as pasted by the OP.

**Comment by djcsdy** [comment]
(In my previous comment I determined my Gradle version by running `./android/gradlew.bat --version`, does that answer your question? I don't have Gradle installed globally on my system, I'm only using the Gradle wrapper.)

**Comment by djcsdy** [comment]
It seems that the cause of this problem is that `react-native init` adds the following dependency in `android/app/build.gradle`:

```groovy
    compile "com.android.support:appcompat-v7:23.0.1"
```

`react-native-svg` also depends on this library and so it gets included in the build twice, which causes the above error.

To be honest I am confused about why this happens. I thought that Gradle was supposed to notice when two modules depend on the same library, and only include that library once. I am not really sufficiently familiar with Gradle to know what the correct solution is.

For now I have worked round the problem by removing the dependency on `appcompat-v7` from my project. That seems to get things working, but it doesn't feel like the correct solution.

**Comment by djcsdy** [comment]
I found a better workaround.

In `android/app/build.gradle`, I changed:

```groovy
    compile project(':react-native-svg')
```

to read:

```groovy
    compile(project(':react-native-svg')) {
        exclude group: "com.android.support", module: "appcompat-v7"
    }
```

Thus excluding the extra copy of appcompat-v7 from the build.

For anyone else needing to work round this problem: you will probably also need to delete the following directories to force gradle to rebuild everything:

 * `android/build`
 * `android/app/build`
 * `node_modules/react-native-svg/android/build`

**Comment by activelogic** [comment]
@djcsdy - Thanks this worked for me as well.

**Comment by magicismight** [comment]
@djcsdy Thanks for answering this.
