### ISSUE TITLE
Image loading progress

### ISSUE THREAD

**Issue by DannyvanderJagt** [react-native-community/react-native-svg#183]
First off, great library!

Got a question: Would it be possible to create `onLoad`, `onLoadStart` and/or `onLoadEnd` events?

I would be a nice addition to `Image` and it would for example allow for a nice fade-in transition when the image is loaded. 

Let me know if it is possible and maybe I can help.

**Comment by magicismight** [comment]
I don't think a fade-in transition in SVG is a right choice.
But the events would be great.

**Comment by DannyvanderJagt** [comment]
@magicismight I agree, what I meant is that you can let the SVG fade-in once the image is loaded.

**Comment by magicismight** [comment]
Oh, I see.
But I have some trouble to add those features on iOS.
I don't know how to add listeners to those events.
I just used ` _image = CGImageRetain([RCTConvert CGImage:src]);` to get the image

**Comment by koswarabilly** [comment]
this onload instance will be really great

**Comment by msand** [comment]
Closing this until someone comes up with an idea how to implement.
