### ISSUE TITLE
<Text> from react-native-svg and from react-native 

### ISSUE THREAD

**Issue by armres** [react-native-community/react-native-svg#185]
I used <Text> from react-native, but i need text and from react-native-svg. But conflict arises when they are added through imports. Whether it is possible to rename the <Text> from react-native-svg in <TextSvg> or <Svg.Text>?

**Comment by gorangajic** [comment]
```jsx
import { Text as SvgText } from 'react-native-svg';
```

**Comment by magicismight** [comment]
Thanks @gorangajic for answering this.
I'm closing this now.
