### ISSUE TITLE
Crashed while building for android

### ISSUE THREAD

**Issue by raviteja83** [react-native-community/react-native-svg#187]
react-native  version : **'^0.33.0'**
react-native-svg : tried with **4.3.0,4.3.1,4.3.2,4.3.3**
gradle distribution:**2.11**
gradle version in android: **2.1.0**
android build tools : **23.0.2**

node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/**RNSVGSvgViewShadowNode.java:64**: error: setReactTag(int) is not public in ReactShadowNode; cannot be accessed from outside package
        
`:react-native-svg:compileReleaseJavaWithJavac `FAILED

**Comment by limpbrains** [comment]
@raviteja83 how have you fixed this ?

**Comment by raviteja83** [comment]
try the following.i don't know what exactly fixed the issue.
run `./gradlew clean`
`npm uninstall react-native-svg`
`npm install react-native-svg@4.3.1`
also try to do the same for react-native
