### ISSUE TITLE
RN 0.38.0 causes issues with createReactNativeComponentClass (again)

### ISSUE THREAD

**Issue by rogchap** [react-native-community/react-native-svg#188]
RN 0.38.0 has a peer-dependancy of react@~15.4.0-rc.4 which removes `createReactNativeComponentClass` from `react/lib/createReactNativeComponentClass`

Not sure if this is the correct fix but I solved by updating references to `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass`

**Comment by farwayer** [comment]
I think using `requireNativeComponent()` is more correct way. It is public API.

**Comment by kelset** [comment]
Thanks for the workaround @rogchap. 
It took me a bit to clearly understand how to implement it, so for the noobs like me, basically it means to go in `/node_modules/react-native-svg/elements` and in all the *.js files where the line:

`import createReactNativeComponentClass from 'react/lib/createReactNativeComponentClass';`

is presented substitute it with:

`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass';`

That said, @farwayer with using `requireNativeComponent()` you mean that all the elements using `createReactNativeComponentClass` should be modified to be similar to `Svg.js`?

**Comment by farwayer** [comment]
@kelset Yes, this component was broken several times already because of using internal `createReactNativeComponentClass()`.
But `requireNativeComponent()` automatically adds `RCTView` props to [`validAttributes`](https://github.com/facebook/react-native/blob/3683beb88ab3233038ac32b9c33112d537478088/Libraries/ReactNative/requireNativeComponent.js#L64). This may be a problem. @magicismight ?

**Comment by neiker** [comment]
This is ready to be merged?

**Comment by Kerumen** [comment]
@pablocarrillo Maybe you forgot to create the PR?

**Comment by pablocarrillo** [comment]
PR is now submitted #193. Sorry forgot to send after testing in our app.

**Comment by AlbertBrand** [comment]
My guess is that this change won't be backwards compatible for RN 0.37 and lower.
