### ISSUE TITLE
How to use custom fonts for text

### ISSUE THREAD

**Issue by ramneekhanda** [react-native-community/react-native-svg#189]
`<Text` key={i} x='0' y='0' fontSize='24' `fontFamily='somefont'>&#xE050;</Text>`

Seems it uses the default font

**Comment by ramneekhanda** [comment]
anyone? sorry for spam but this is kind of urgent..

**Comment by rgoldiez** [comment]
Did you look at https://github.com/react-native-community/react-native-svg/issues/122

**Comment by ramneekhanda** [comment]
@rgoldiez it seems like only ios was implemented there? Any clues on how to do it with android?

**Comment by anhtuank7c** [comment]
I have one custom font: [Kingsman](https://drive.google.com/file/d/0ByAlYbrjOCRybTVDRVFRSUVXcXM/view?usp=sharing)

I do place font in `project_folder/src/fonts/Kingsman.tff` then edit `packages.json` like this:
```
    "rnpm": {
        "assets": ["./src/fonts/"]
    }
```

Next, i do link fonts to Android/iOS:
```
react-native link
```

Fonts copied to 2 android and ios project

Then i try to display Text to make sure i do correctly:
```
import { Text} from 'react-native'

...component code

render() {
    return <Text style={{ fontFamily: 'Kingsman', fontSize: 20}} >Demo</Text>;
}
```
=> Display correct font as expected.

## Problem on `Android ONLY`

```
import Svg, {Text} from 'react-native-svg';

...component code

render() {
    return (
        <View style={{flex: 1}}>
            <Svg height={100} width={100}>
                <Text fontFamily="Kingsman" fontSize="22" x="10" y="10">Demo</Text>
            </Svg>
        </View>
    );
}
```

==> Doesn't make scene on Android device, iOS working good.

**Comment by pengfeiyan** [comment]
I got the same issue. 

How to use custom fonts for text on Android device?

**Comment by carlesnunez** [comment]
Same here

**Comment by msand** [comment]
You can try my fork, it has support for custom fonts on Android, and various other fixes.
https://github.com/msand/react-native-svg/tree/TextOnAPathLayoutRulesConformance

You can see how to set a font in here: https://github.com/msand/RNSvgTextBug/commit/3b47667fbca150857297880cb7ae27728de5fc0f

Just remember to use the exact PostScript name of the font you want to use, the syntax might be different from ios. If Kingsmen doesn't work, then try "Kingsmen Regular" and "Kingsmen-Regular", if this still doesn't help, then try renaming the file to Kingsmen-Regular.otf

**Comment by StribMaxMarti** [comment]
@msand any chance of getting a PR for the font fix?

**Comment by msand** [comment]
@StribMaxMarti This pull request now contains almost all the fixes from android ported to ios as well: https://github.com/react-native-community/react-native-svg/pull/430

**Comment by macrozone** [comment]
does this also work on expo? I can't get custom fonts to work both on ios and android

**Comment by msand** [comment]
@macrozone  Once it's merged into master, published on npm, and Expo makes a new version of their fork of RN + other deps, then all my fixes will be available from there as well. I don't know if they support custom fonts at the moment, but at least in theory it's fully possible.

**Comment by darkrift** [comment]
Is this being looked at ?

**Comment by msand** [comment]
@darkrift Its available since v6.0.0 and up, should work fine. Expo hasn't updated yet though.

**Comment by darkrift** [comment]
@msand My bad then, I'll have a try with a later version that what I have then. Maybe the issue should be closed then if it's been merged. The Expo problem should probably be tracked elsewhere. Are there other issues that could be closed for which you have submitted pull request to solve them ?

**Comment by msand** [comment]
@darkrift  I would expect a sizeable fraction, if not the majority, of issues are close-able. Or not even actual issues with the library at all, but rather lack of knowledge of the svg spec, react-native and the react life-cycle. I just haven't put any time into closing old issues. I've mostly fixed things I need for work, some of my own itches and any issues others have which would bite myself sooner or later anyway, and the rest just for fun and learning :) At least I have custom fonts working in production with the latest versions, so I'll go ahead and close this for now.
