### ISSUE TITLE
Android build crash

### ISSUE THREAD

**Issue by jurajkrivda** [react-native-community/react-native-svg#190]
RN 0.33, react-native-svg latest. I am getting this error during the building process:

node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RNSVGSvgViewShadowNode.java:62: error: method does not override or implement a method from a supertype
    @Override
    ^
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RNSVGSvgViewShadowNode.java:64: error: setReactTag(int) is not public in ReactShadowNode; cannot be accessed from outside package
        super.setReactTag(reactTag);

**Comment by limpbrains** [comment]
I have the same error on Ubuntu

**Comment by limpbrains** [comment]
react-native-svg@4.3.0 work fine, 4.3.2 and 4.3.3 - don't

**Comment by magicismight** [comment]
You can try to update the react-native version
