### ISSUE TITLE
import createReactNativeComponentClass link has been moved

### ISSUE THREAD

**Issue by michaelkclements** [react-native-community/react-native-svg#192]
Upgrading to the latest in React, React-Native and other packages, it shown that react-native-svg broke because the `createReactNativeComponentClass` had been moved.

I managed to fix it on my own version by changing the links from
`import createReactNativeComponentClass from 'react/lib/createReactNativeComponentClass';`
to
`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass';`

**Comment by Kerumen** [comment]
Dupe of https://github.com/react-native-community/react-native-svg/issues/188

**Comment by michaelkclements** [comment]
Apologies.
