### ISSUE TITLE
How to use Pattern

### ISSUE THREAD

**Issue by 329379172** [react-native-community/react-native-svg#194]

**Comment by magicismight** [comment]
Pattern element is not supported yet

**Comment by mariotacke** [comment]
Any plans on supporting this?

**Comment by fendorio** [comment]
Any plans for this? I'm trying to implement having a circle with an image backround

**Comment by chrisheninger** [comment]
I landed here looking to use Pattern– figured I'd share my solution for shapes w/ images w/o pattern.

```
<Svg height="200" width="200" viewBox="0 0 300 300">
  <Defs>
    <ClipPath id="hexagon">
      <Polygon points="150,300 20,225 20,75 150,0 280,75 280,225" />
    </ClipPath>
  </Defs>

  <Image
    x="0"
    y="0"
    width="100%"
    height="100%"
    preserveAspectRatio="xMidYMid slice"
    href={artwork.src} {/* my artwork.src is a data-uri… you can also require('./path/to/img.jpg') here too */}
    clipPath="url(#hexagon)"
  />
</Svg>
```

**Comment by wcandillon** [comment]
Thanks @chrisheninger really appreciate your solution. It works very well!

**Comment by finnfiddle** [comment]
Reviving an old thread here bit any plans on supporting this yet?

**Comment by msand** [comment]
@finnfiddle I haven't looked into it at least, and haven't had any need for it. Honestly I didn't even know it existed or seen it in use anywhere yet. Would you be interested in working on it?

**Comment by finnfiddle** [comment]
@msand pattern fills are really useful for datavis purposes. See some examples [here](https://riccardoscalco.github.io/textures/). I would be happy to help but the on the native side I don't have much clue what is going on :/ - maybe if you could give me some pointers about how to approach it I could have a crack though

**Comment by msand** [comment]
I would recommend reading the spec for paint servers at the very least https://svgwg.org/svg2-draft/pservers.html and then look at how e.g. gradients and symbols have been implemented, there will be quite a lot of similarities. Essentially a new element will need to be defined, so a react component and the attribute handling in js, and a shadow node / view implementation in objective-c and java, and a bit of view manager logic to glue them together. 

The Pattern specific part just needs the repetition of the pre defined pattern according to the language in the spec. That seems very straight forward at least, a double loop on the visible part of the canvas, and clipping using either the fill or stroke of the graphics element which references the pattern should suffice: 

> 14.4. Patterns
> 
> A pattern is used to fill or stroke an object using a pre-defined graphic object which can be replicated ("tiled") at fixed intervals in x and y to cover the areas to be painted. Patterns are defined using a ‘pattern’ element and then referenced by properties fill and stroke on a given graphics element to indicate that the given element shall be filled or stroked with the pattern.
> 
> Attributes ‘x’, ‘y’, ‘width’, ‘height’ and ‘patternUnits’ define a reference rectangle somewhere on the infinite canvas. The reference rectangle has its top/left at (x, y) and its bottom/right at (x + width, y + height). The tiling theoretically extends a series of such rectangles to infinity in X and Y (positive and negative), with rectangles starting at (x + m*width, y + n* height) for each possible integer value for m and n.

https://svgwg.org/svg2-draft/pservers.html#Patterns

**Comment by msand** [comment]
But yeah, the pattern element seems really useful, and I can probably help out more, just ask and I'll give clues or help with the boilerplate. I'll probably be shifting projects from working full time + building a company, to just building a company in the end of the month, and won't have any RN project as main focus for some time. So I'm not sure how it'll affect my contributions, the startup will be my main focus, but shifting from two jobs to one might give me more time for open source as well. Lets see how things go 😃

**Comment by msand** [comment]
@questionablequestion @finnfiddle I've implemented basic support for patterns here: https://github.com/react-native-community/react-native-svg/pull/757/commits/fc63635f3cb6c03de22fb8c7eb973b08e0147b1b
Any help in testing is much appreciated!

**Comment by msand** [comment]
Closing this as Pattern is implemented now.
