### ISSUE TITLE
4.4.0 Runtime error

### ISSUE THREAD

**Issue by mattotodd** [react-native-community/react-native-svg#196]
After upgrading from version 4.3.2 to 4.4.0 I get the following crash at runtime 

![screen shot 2016-12-01 at 3](https://cloud.githubusercontent.com/assets/1211438/20815925/e7c3823a-b7ed-11e6-90d7-8eee957c1057.png)

Spent a good deal of time thinking it was related to [react-native/4968](https://github.com/facebook/react-native/issues/4968), but after reverting back to 4.3.2 the issue resolved itself.

**Comment by magicismight** [comment]
Please update react-native to 0.38.0 and react to 15.4.0, or using react-native-svg@4.3.x instead.
react-native-svg has a peerDependencies as followed:
* react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
* react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
* react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
* react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >=15.4.0
