### ISSUE TITLE
 How to use gradientUnits and gradientTransform

### ISSUE THREAD

**Issue by kopecsrk** [react-native-community/react-native-svg#199]
LinearGradient

**Comment by ronal2do** [comment]
+ 1

**Comment by magicismight** [comment]
They are not supported yet.

**Comment by msand** [comment]
LinearGradient works to some extent now, gradientTransform is still missing. Is anyone working on this? Or does anyone know what it would entail?

**Comment by msand** [comment]
I've made an implementation that works in Android now: https://github.com/react-native-community/react-native-svg/pull/357

**Comment by msand** [comment]
@iKettles not sure if you got any update from the previous comment, as you only liked my first comment, and you don't show up as an participant... Thought you might want to try my solution out ;)

**Comment by msand** [comment]
I've added support for Image transform as well now. In our case we now have support for everything we need, i.e., Illustrator svg output cross-platform rendering support (web compatiblity using https://github.com/godaddy/svgs ), We merely have to collect all gradients/definitions and put them inside of a Defs tag. (Still only tested in android)

**Comment by msand** [comment]
I've made a gist with some instructions and code for converting Illustrator output into svgs / react-native-svg compatible form: https://gist.github.com/msand/4b37d3ce04246f83cb28fdbfe4716ecc

**Comment by jpls93** [comment]
@msand hello. sorry for being slow. so how do we exactly convert a `gradientTransform` attribute now?

For example, if I have something like
```
<linearGradient {...} gradientTransform="matrix(1 0 0 1 0 706)">
```
 what does it convert to?
