### ISSUE TITLE
rotate bug on iOS

### ISSUE THREAD

**Issue by sjgtongji** [react-native-community/react-native-svg#201]
I use the circle component to draw arc , but there is a bug about rotate on ios , below is my code
`                                               <Circle
								origin="150, 150"
								rotate={0}
								cx="150"
								cy="150"
								r="20"
								stroke="blue"
								strokeWidth="40"
								fill="none"
								strokeDasharray={[ 20 * PI, 40 * PI]}
						/>
						<Circle
								origin="150, 150"
								rotate={180}
								cx="150"
								cy="150"
								r="20"
								stroke="red"
								strokeWidth="40"
								fill="none"
								strokeDasharray={[20 * PI , 40 * PI]}
						/>`

this is the result on android 
<img width="110" alt="2016-12-12 4 53 59" src="https://cloud.githubusercontent.com/assets/6083671/21093237/b0be1b82-c08b-11e6-92db-50caac445e69.png">

but this is the result on iOS
<img width="93" alt="2016-12-12 4 55 48" src="https://cloud.githubusercontent.com/assets/6083671/21093264/d5c65c82-c08b-11e6-9d22-23fa875aeffd.png">

I found when the rotate prop is one of '90 , 180 , 270' , the rotate prop has no effect on iOS.

**Comment by benhowes** [comment]
We've also seen this, the only thing to add is that it works on Android

**Comment by msand** [comment]
Could you try again with the new correct transform parser and the spec conformant syntax? I think this should be working correctly already.
