### ISSUE TITLE
alignmentBaseline prop support

### ISSUE THREAD

**Issue by almirfilho** [react-native-community/react-native-svg#204]
Is there any plan do support the `alignment-baseline` SVG attribute?
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

Thanks!

**Comment by masonk** [comment]
Same question

**Comment by betko** [comment]
@almirfilho Did you get answer for this question?

**Comment by almirfilho** [comment]
@betko nope..

**Comment by msand** [comment]
@almirfilho @masonk @betko I've implemented it in Android, and possibly in iOS as well, needs more testing, can you try my fork? 
https://github.com/react-native-community/react-native-svg/pull/430
https://github.com/msand/react-native-svg
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67
yarn add react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67

**Comment by nico1510** [comment]
hey @msand thank you for this great pull request which has landed in version 6.0.0. The `alignmentBaseline` prop is now working for me on android. On iOS it doesn't seem to work though ? I'm using the iPhone Simulator to test since I don't own an iPhone...

**Comment by mchen37** [comment]
@nico1510 Hey could you show how to use this prop? I couldn't find any documentation for it since it's new. Here is my snack where I've tried to get it working but it doesn't seem to make a difference no matter where I put it: https://snack.expo.io/HykPKRiEf

**Comment by msand** [comment]
@nico1510 I'm not sure what version they have in Expo right now, it might not have those commits yet. I'll try to get a new release done this wekk. You can see an example here: https://github.com/msand/react-native-svg-example/blob/SpecTests/src/components/baseline.js

**Comment by msand** [comment]
http://bl.ocks.org/eweitnauer/7325338

**Comment by msand** [comment]
I'll be closing this as it works in react-native-svg. Expo needs an update still.
