### ISSUE TITLE
Using multiple translates in a transform

### ISSUE THREAD

**Issue by getnashty** [react-native-community/react-native-svg#205]
I'm new to SVG's - and I have one being generated from [Sketch](https://www.sketchapp.com/), which includes multiple translates in the transform property:

`
transform="translate(4.961222, 11.000000) scale(-1, 1) rotate(90.000000) translate(-4.961222, -11.000000)`

Can anyone tell me what properties these would map to (or if this would even be supported)?
I've been playing around with origin for a couple hours, but haven't had much success.

**Comment by garbo-a** [comment]
same issue

**Comment by AlbertBrand** [comment]
Might be possible with nested Group (G) elements.

Op 30 dec. 2016 12:38 p.m. schreef "Oleksander Garbovskiy" <
notifications@github.com>:

**Comment by getnashty** [comment]
@garbo-a I've actually figured this out for the most part... what I do is take the SVG from whatever sketch file its in, and put it in a new sketch file, with its own artboard. You'll see even in an empty sketch file it might have X & Y values for some reason. So I try to make it as "vanilla" as possible, then export this svg. This gets rid of multiple transforms for me, but if it doesn't I can see what they map to in sketch, and remove them.

Has worked successfully so far.

**Comment by msand** [comment]
@getnashty @garbo-a @AlbertBrand This should be working correctly in the latest version :)
