### ISSUE TITLE
After upgrading RN 0.37 ~> 0.39 svg fails to build

### ISSUE THREAD

**Issue by drewwells** [react-native-community/react-native-svg#206]
I'm seeing this issue for all of our svg icons.

"Child already has a parent, it must be removed first.(lldb) "

react-native-svg 4.4.1
react-native 0.39.2
react 15.3.1

**Comment by laznrbfe** [comment]
package.json
```
"dependencies": {
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-svg": "^4.4.1"
  },
```

**Comment by magicismight** [comment]
It seems like this had been fixed in the latest version.
I'm closing this now, feel free to reopen this if the problem still exists in the latest version
