### ISSUE TITLE
SVG as Background in Multiple Scenes

### ISSUE THREAD

**Issue by activelogic** [react-native-community/react-native-svg#208]
I'm using the RadialGradient Ellipse to create a spotlight effect as a background to multiple scenes using the code below.  For managing my scenes and routing, I'm using react-native-router-flux.

When I navigate between scenes with this background SVG, I'm getting increasing lag each subsequent transition and then eventually the app crashes with an OutOfMemoryError on Android.  If I remove this SVG entirely as a background, I don't have lag issues or crashing.

Is there a way I can create an SVG and use it as a background image without leaking memory?  

```
import React from 'react';
import { StyleSheet, Dimensions, View } from 'react-native';
import { Svg, Defs, RadialGradient, Stop, Ellipse } from 'react-native-svg';

export default (props) => {
  const { height, width } = Dimensions.get('window');

  return (
    <Svg
      height={height}
      width={width}
      style={styles.svg}
    >
      <Defs>
        <RadialGradient
          id="grad"
          cx={width / 2}
          cy={height / 4}
          rx={width * 2}
          ry={height}
          fx={width / 2}
          fy="100"
        >
          <Stop
            offset="0.1"
            stopColor="#121317"
            stopOpacity="0.05"
          />
          <Stop
            offset="0.4"
            stopColor="#121317"
            stopOpacity="0.9"
          />
        </RadialGradient>
      </Defs>
      <Ellipse cx={width / 2} cy="0" rx={width} ry={height * 1.5} fill="url(#grad)" />
    </Svg>
  );
};

const styles = StyleSheet.create({
  svg: {
    position: 'absolute',
    top: 0,
    left: 0
  }
});

```

**Comment by AlbertBrand** [comment]
You might want to try setting renderToHardwareTexture on the parent and see
if that helps.

Op 20 dec. 2016 10:20 a.m. schreef "activelogic" <notifications@github.com>:

**Comment by activelogic** [comment]
Thanks for the suggestion.  I've tried putting the 'renderToHardwareTextureAndroid' prop onto the <Svg> component, that didn't help.  I also want to avoid increasing the Android heap size.

I suspect the constant re-rendering of the SVG is what's causing the issue.  Is there any way to generate the SVG and only have it re-render explicitly?  Essentially, I'd like to generate the SVG once, re-use it in all my scenes,  and only re-render on device rotation.

**Comment by magicismight** [comment]
You can cache the `BASE64` data for the Svg, and use it in Image component.
```
svgRef. toDataURL((base64) => {
    // console.log("The base64 data for the svg:", base64);
});
```
