### ISSUE TITLE
Event does not work on G, Rect, Text

### ISSUE THREAD

**Issue by tigerinus** [react-native-community/react-native-svg#210]
I've tried add onLongPress/onPress to either G, Rect and Text in the code below. But nothing happens when pressing on these shapes. Please help.
`
    getMemberElements() {
        return this.props.list.map(
            function (other) {
                let otherOnRadar = this.getCoordinateOnRadar(this.props.mine, other);
                return (
                    <G
                        key={other.name}
                        onLongPress={() => alert(other.name)}
                        >
                        <Rect
                            x={otherOnRadar.x - 2}
                            y={otherOnRadar.y - 2}
                            width="4"
                            height="4"
                            stroke="red"
                            strokeWidth="1"
                            fill="yellow"
                            />
                        <Text
                            x={otherOnRadar.x}
                            y={otherOnRadar.y + 3}
                            textAnchor="middle"
                            fontSize="8"
                            >
                            {other.name}:{otherOnRadar.distance.toFixed(2)}km
                        </Text>
                    </G>
                );
            }, this)
    }
`

**Comment by ababba15** [comment]
`onPressIn` worked for me, but not onPress for some reason

**Comment by onpaws** [comment]
[Me too](https://github.com/react-native-community/react-native-svg/issues/592).
For my project`<Circle>` is working but not `<G>`.
I experimented with re-ordering elements but no luck so far.

**Comment by maxkomarychev** [comment]
Issue with `<G>` (and also `<Use>`) is supposed to be fixed by https://github.com/react-native-community/react-native-svg/pull/650 - those elements didn't respond to touches on native side. However issue `onPress` vs `onPressIn` is still relevant.

**Comment by msand** [comment]
I think I've fixed the issues with onPress/in/Out now, can you try with the latest commit from the master branch?

**Comment by msand** [comment]
I think I have (gesture) interactions between native animated transforms and normal svg transforms working correctly now as well: https://github.com/react-native-community/react-native-svg/commit/8c05da043dea3f8d04420c2d7c9c11733e22258b
