### ISSUE TITLE
Error com.horcrux.svg does not exist on Windows/Android

### ISSUE THREAD

**Issue by mihaben** [react-native-community/react-native-svg#211]
Hi,

I'm trying to install the **react-native-svg** package but I have not been able to do it yet.

I followed the instructions in the Readme (npm install and link code), but I have the following error when I execute `react-native run-android`

```
C:\rnative-projects\memoshape\android\app\src\main\java\com\memoshape\MainApplication.java:7: error: package com.horcrux.svg does not exist
import com.horcrux.svg.RNSvgPackage;
                      ^
C:\rnative-projects\memoshape\android\app\src\main\java\com\memoshape\MainApplication.java:29: error: cannot find symbol
            new RNSvgPackage()
                ^
  symbol: class RNSvgPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I´m developing with Windows 10.

and...

```
"dependencies": {
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-svg": "^4.4.1"
  }
```

Thank you for your help!

**Edit:**

Same problem with

```
"dependencies": {
    "react": "15.4.0",
    "react-native": "0.38",
    "react-native-svg": "4.4.0"
  }
```

**Comment by mihaben** [comment]
I found the problem, the installer was not adding the depedence in **build.gradle**, to fix the problem I added the compile code inside dependences{}, I also excluded the appcompat-v7 to avoid conflicts:

```
dependencies {
    compile(project(':react-native-svg')) {
        exclude group: "com.android.support", module: "appcompat-v7"
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by joncursi** [comment]
I am getting this same issue on mac OS after upgrading from RN 0.39.2 -> 0.40.0. I have cleared out the cache with gradle as suggested in other issue trackers but no luck.

```
/Users/jcursi/Sites/joncursi/redbirdNative/android/app/src/main/java/com/redbirdnative/MainActivity.java:10: error: cannot find symbol
import com.horcrux.svg.RNSvgPackage;
                      ^
  symbol:   class RNSvgPackage
  location: package com.horcrux.svg
/Users/jcursi/Sites/joncursi/redbirdNative/android/app/src/main/java/com/redbirdnative/MainApplication.java:18: error: cannot find symbol
import com.horcrux.svg.RNSvgPackage;
                      ^
  symbol:   class RNSvgPackage
  location: package com.horcrux.svg
/Users/jcursi/Sites/joncursi/redbirdNative/android/app/src/main/java/com/redbirdnative/MainApplication.java:49: error: cannot find symbol
          new RNSvgPackage(),
              ^
  symbol: class RNSvgPackage
3 errors
:app:compileReleaseJavaWithJavac FAILED
```

**Comment by seacloud9** [comment]
I have this same issue. "react-native": 0.40 newest version works for iOS android appears to have issues.  Tried to unlink and link again.

**Comment by magicismight** [comment]
The package name in android has been changed in 4.6.0, sorry about that

**Comment by joncursi** [comment]
Thanks @seacloud9 , that got me past this issue, but now I am stuck on https://github.com/yonahforst/react-native-permissions/issues/59

Likely another RN 0.40.0 compatibility bug?

**Comment by joncursi** [comment]
thanks @seacloud9 !

**Comment by jorge8989** [comment]
@mihaben 's solution worked for me, 
I'm using Windows 10 on my current project,
my dependencies are
` {
  "react": "~15.4.0-rc.4",
  "react-native": "0.40.0",
   "react-native-svg": "^4.4.1",
}
` 
I had to run `cd android && ./gradlew clean` after the changes

**Comment by demonhunterunderdarkness** [comment]
change package name works for me , thx @seacloud9 !

**Comment by wkrause13** [comment]
I believe the name may have changed again.

To make this compile I needed to import
`import com.horcrux.svg.RNSvgPackage;`
instead of 
`import com.horcrux.svg.SvgPackage;`

And then make the corresponding change in the package list
```
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNSvgPackage(),
...
```

**Comment by anwari32** [comment]
Hello, I also found the same error like this.

> MainApplication.java:27: error: cannot find symbol
>             new RNSvgPackage()
>                 ^
>   symbol: class RNSvgPackage
> 2 errors
> :app:compileDebugJavaWithJavac FAILED

So I renamed several lines at the code. At first it looked like 

`import com.horcrux.svg.RNSvgPackage;`

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNSvgPackage()
      );
    }

```
and I changed them into 

`import com.horcrux.svg.SvgPackage;`

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new SvgPackage()
      );
    }

```
After that I could run `react-native run-android` again. I just installed the svg today so I assumed I have the latest version.

**Comment by xTMNTxRaphaelx** [comment]
This error is still coming to me. I have tried a lot. Someone help me please Why?

**Comment by hlerenow** [comment]
@xTMNTxRaphaelx  Just do this:
added the compile code inside dependences{}, I also excluded the appcompat-v7 to avoid conflicts:

dependencies {
    compile(project(':react-native-svg')) {
        exclude group: "com.android.support", module: "appcompat-v7"
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
like @mihaben

**Comment by sujitpk-perennial** [comment]
@xTMNTxRaphaelx  Have you found solution for this ?

**Comment by linuxgg** [comment]
please follow this:

https://github.com/react-native-community/react-native-svg

**Comment by zhushichuan** [comment]
> @joncursi尝试：
> 
> import com.horcrux.svg.SvgPackage;
> 
> 和
> 
> ```
>  return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new SvgPackage()
>             new ReactNativeConfigPackage()
>       );```
> 
> looks like they changed the name.
> ```

but ，I still have the same problem.
"react": "~15.4.0-rc.4",
		"react-dom": "^16.1.1",
		"react-native": "0.40.0",
		"react-native-svg": "^4.4.1",
		"react-native-svg-uri": "^1.2.3",

**Comment by Shehzad121** [comment]
check duplication of package import also face same error but on debug got import com.horcrux.svg.SvgPackage; twise

**Comment by CurtisTD** [comment]
If you're using expo, try ```expo install react-native-svg```
