### ISSUE TITLE
Execution failed for task ':app:dexDebug' (react-native-svg)

### ISSUE THREAD

**Issue by umaire313** [react-native-community/react-native-svg#213]
after adding following lib 

npm install react-native-pathjs-charts --save
react-native link react-native-svg 

from  https://www.npmjs.com/package/react-native-pathjs-charts

i got this error
FAILURE: Build failed with an exception.

* What went wrong:

- Execution failed for task ':app:dexDebug'.
-  com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_112\bin\java.exe'' finished with non-zero exit value 2

**Comment by Noor0** [comment]
im having the same issue

:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)

Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe'' finished with non-zero exit value 2

**Comment by Crash--** [comment]
Can you try to clean your project `cd android && ./gradlew clean` and rebuilt it with `react-native run-android`.

**Comment by Crash--** [comment]
Take a look at this issue #174 ;)

**Comment by Noor0** [comment]
yes, thank you I had already found the solution on stackoverflow but forgot to post it on the github issue glad that you've found it and thanks once again for your courtesy of mailing me the solution. ?

**Comment by mrbarde** [comment]
@crash Thanks!
