### ISSUE TITLE
Android: Error while updating property 'd' in shadow node

### ISSUE THREAD

**Issue by thedjinn** [react-native-community/react-native-svg#219]
Hi! I updated react-native-svg from 4.0.0 to 4.6.1 and now get the following error when running on Android:

`Error while updating property 'd' in shadow node of type: RNSVGPath`

The SVG I want to render is this one: (originally it had more properties but I removed them to the minimal SVG document required to trigger the issue)

```
<Svg height={100} width={100}>
    <Path d="M 50.39973979582424,55.194348826112666 5.2001026093465175,62 2.947046320824673,27.892750153167036 2,9.59734992518333 46.661191716201934,2 47.528660937587134,13.099602868974927 49.61184768800117,42.72842194869662 50.39973979582424,55.194348826112666 z" />
</Svg>
```

Here is the output from `adb logcat` showing a stack trace of the error: https://gist.github.com/thedjinn/c94191b1cee47887d60a2e03597047b5

Everything worked fine on the previous version. What could be the problem here?

**Comment by magicismight** [comment]
That's weird.
Try to clean up the packager?
It seems like the JS code and the native code are not matched.

**Comment by magicismight** [comment]
Please check out the `node_modules/react-native-svg/elements/Path.js` see if the code matches: https://github.com/react-native-community/react-native-svg/blob/master/elements/Path.js

**Comment by thedjinn** [comment]
That resolved the issue. Thanks!

**Comment by Mattk14** [comment]
Encountering this issue on Android only

**Comment by hasLandon** [comment]
Also experiencing this on android. React-native 0.42.3 and react-native-svg 5.1.7

**Comment by bijeshp** [comment]
Any one found any solutions?

**Comment by markflorisson** [comment]
I get this issue with RN 0.44 and react-native-svg 5.1.8. Any ideas?

**Comment by richardgorman** [comment]
I ALSOthis issue with RN 0.44 and react-native-svg 5.1.8

**Comment by dwilt** [comment]
I'm also having this issue as well. @thedjinn how were you able to resolve this?

**Comment by thedjinn** [comment]
@dwilt see my comment above and the one before it :)

**Comment by dwilt** [comment]
@thedjinn I don't understand how you solved it - that's why I'm asking. If you ran `npm install` and have the latest, how is it that your `node_modules/react-native-svg/elements/Path.js` file could be different than what's up on Github?

**Comment by thedjinn** [comment]
@dwilt Well in my case npm did not update that file after upgrading the package, so it was different.

**Comment by hasLandon** [comment]
My `Path.js` file matches what is in master, but I'm still having this problem with react-native-svg 5.2.0

**Comment by josephbuchma** [comment]
@hasLandon can you please be more specific ? How exactly you've fixed this issue ?

**Comment by msand** [comment]
@josephbuchma Try cleaning the native builds and your packager cache. Delete node_modules. Then yarn or npm install. Rebuild your native projects and run again.

**Comment by msand** [comment]
And, the classic, try turning your computer off and on again ;)

**Comment by msand** [comment]
Or, what error messages can you see?

**Comment by josephbuchma** [comment]
@msand for now I just commented out code that uses rn svg. I'll be back when runtime will hit those lines again :)

**Comment by Alifarmand** [comment]
## I am facing the following issue with this setup:

Error while updating property 'strokeWidth' in shadow node of type: RNSVGRect
TypeError: expected dynamic type 'double' but had type 'string'. 
 
```
"react-native": "0.52.0",
"react-native-svg": "^6.3.1",
```

I have the issue only on Android device, not on iOS simulator.
I've tried applying stroke='none' to the elements, since I don't need it, but I still get same error.

Anyone has a solution for this yet?

**Comment by AdamLenda** [comment]
+1

**Comment by AlexBrasileiro** [comment]
Hey guys, SVG Path on Android does not accept NULL values. Perhaps it is the case to resolve with something similar to:

**!this.state.somethingThatEnsuresThatThereAreNoNULLValues** `? '' : <Svg><Path d={'M' + 'yourNonNullValues'} /></Svg>`

**Comment by Vizlij** [comment]
d={props.d} 
=>
d={props.d || ''}
=
profit

**Comment by Vizlij** [comment]
![Снимок экрана от 2019-07-05 17-01-25](https://user-images.githubusercontent.com/49515898/60727588-ef21af00-9f46-11e9-96a1-74e74a90cafa.png)

**Comment by emmyprinso** [comment]
I removed the version in my project using
yarn remove react-native-svg
then I ran
yarn add react-native-svg@9.13

***that solved my issue
