### ISSUE TITLE
After updating to react-native 0.40 and react-native-svg 4.6.1 strokeWidth property no longer default to 1

### ISSUE THREAD

**Issue by ying-huang** [react-native-community/react-native-svg#222]
After updating to react-native 0.40 and react-native-svg 4.6.1 strokeWidth property no longer default to 1.  Have to add a strokeWidth='1' to each Svg component.

**Comment by magicismight** [comment]
We will fix that in next version

**Comment by magicismight** [comment]
Fixed in 5.x
