### ISSUE TITLE
No component found for view with name "RNSVGREct"

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/react-native-svg#225]
I believe this question was asked here before, but I am unable to fix this using any of the solutions already here.

React native v 0.40
react-native-svg v4.6.1

svg library was installed in already existing project that had some dependencies linked before. These are the steps of installation

1)  Terminal / browser / xCode / simulator were all completely quit
2) `yarn add react-native-svg`
3) `react-native link react-native-svg`
4) Got output about successfully linking these
5) `react-native run-ios`

After launching the application I get following error
---
![Imgur](http://i.imgur.com/xIRx455.png)
---

Also checked my xCode project and Library seems to be in place

**Comment by IljaDaderko** [comment]
**Update:** I believe this issue can be somehow linked to workspace? i.e. for some libraries `react-native link` creates a projectName.workspace file and output in console says to use it from now on.

**Comment by magicismight** [comment]
It seems like this only happenes while using yarn as installation?
#217 This issue also use yarn.
I cannot reproduce this issue while I'm using npm.

**Comment by IljaDaderko** [comment]
@magicismight any ideas on what could be causing this? As react-native team are now pushing towards yarn, would be good time to fix this, I'll do a bit of research, but currently have no idea how they differ.

**Comment by magicismight** [comment]
I don't know what's happening.
I'm so not familiar with yarn and the namespace system in XCode project.
I need some help here.

**Comment by pcompassion** [comment]
I'm having the sam problem with npm install..

     "react": "16.0.0-alpha.12",
     "react-native": "0.45.0",
     "react-native-svg": "5.2.0"

**Comment by msand** [comment]
This looks like the linking process has failed. Try linking manually.
