### ISSUE TITLE
Circular path is strangely misshapen

### ISSUE THREAD

**Issue by hounsellal** [react-native-community/react-native-svg#228]
Code for Path:
<Path stroke="#FF6E6C" strokeWidth={30} fill='none' 
            d={`M ${startCoord.x} ${startCoord.y} A ${r} ${r} 0 ${value>180?1:0} 1 ${endCoord.x} ${endCoord.y}`} >    
          </Path>

Used to be nicely circular. Now after upgrading react native to 0.40.0 and upgrading react-native-svg, the path appears really weirdly shaped.

<img width="328" alt="screen shot 2017-01-13 at 9 41 41 pm" src="https://cloud.githubusercontent.com/assets/1194814/21951716/5184575a-d9d9-11e6-8a99-93a5d6247297.png">

**Comment by magicismight** [comment]
fixed in 5.0.2

**Comment by hounsellal** [comment]
I'm actually using 5.0.2. Same problem. I did:
react-native unlink react-native-svg
npm remove react-native-svg --save
Closed Xcode, server, etc.
npm install react-native-svg --save (5.0.2 was installed)
react-native link react-native-svg

**Comment by magicismight** [comment]
Can you post your code? I'll test this tomorrow

**Comment by magicismight** [comment]
And it happens on iOS or android?or both? I have refactored the path element recently.Maybe cause something wrong

**Comment by hounsellal** [comment]
`<Svg ref="canvas" onLayout={this.onLayout} width={width} height={height} style={{alignItems:'center',justifyContent:'center'}} {...this._panResponder.panHandlers}>
          
              <Circle cx={cx} cy={cy} r={r} stroke='#FFE6E6' strokeWidth={40} fill='none'   />
              <Circle cx={cx} cy={cy} r={r+30} stroke="#999" fill="none" strokeWidth={5} strokeDasharray={[tickWidth,tickSpace]}  />
              <Circle cx={cx} cy={cy} r={r+25} stroke="#FF9897" fill="none" strokeWidth={3}  />
              <G x={cx} y={height/3.5}>
                  {
                    this.props.textValue ? 
                    <Text textAnchor="middle" fill={textColor} fontSize={r/1.1} fontWeight={"bold"} letterSpacing={0}>{Math.floor(this.props.textValue/6)+''}</Text>
                    :
                    <Text textAnchor="middle" fill={textColor} fontSize={r/1.1} fontWeight={"bold"} >{(Math.floor(value/6)).toString()}</Text>
                  }
                  <Text y={r.toString()} fontSize={r/5} fill="#999" textAnchor="middle">Minutes</Text>
              </G>

            <Path stroke="#FF6E6C" strokeWidth={30} fill='none' 
              d={`M${startCoord.x} ${startCoord.y} A ${r} ${r} 0 ${value>180?1:0} 1 ${endCoord.x.toString()} ${endCoord.y}`} >    
            </Path>

          <G x={endCoord.x-7.5} y={endCoord.y-7.5} >
            <Circle cx={7.5} cy={7.5} r={15} fill="#FF6E6C" />    
          </G>   
        </Svg>`

The above is my code. Here are all of the issues:

1) On iOS but not Android the circular path is strangely shaped.
2) On Android, when I update endCoord and value, the "Circle" at the end of the path moves:

Circle:
`<G x={endCoord.x-7.5} y={endCoord.y-7.5} >
            <Circle cx={7.5} cy={7.5} r={15} fill="#FF6E6C" />    
          </G>`

But the Text and Path do not change:

Text:
`<Text textAnchor="middle" fill={textColor} fontSize={r/1.1} fontWeight={"bold"} >{(Math.floor(value/6)).toString()}</Text>`

Path:

`<Path stroke="#FF6E6C" strokeWidth={30} fill='none' 
              d={`M${startCoord.x} ${startCoord.y} A ${r} ${r} 0 ${value>180?1:0} 1 ${endCoord.x.toString()} ${endCoord.y}`} >    
            </Path>`

On iOS, the Circle, Text and Path all change when the parent component passes in a new value and endCoord, but on Android, only the Circle moves to the correct endCoord.

**Comment by magicismight** [comment]
Thanks for the detailed information.
I have fixed this in 5.1.0.
