### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by neiker** [react-native-community/react-native-svg#232]
It's a bit annoying having releases so often. Can you wait to have a couple of commits to release a new version?
When everything's important, nothing is.

![image](https://cloud.githubusercontent.com/assets/688444/21986067/9a93cf70-dbdc-11e6-8581-3446f43442ab.png)

**Comment by magicismight** [comment]
OK. I got that.

**Comment by neiker** [comment]
@magicismight nice! awesome work anyway 👍

**Comment by sibelius** [comment]
Just keep bumping!
