### ISSUE TITLE
Unlink issue

### ISSUE THREAD

**Issue by zabojad** [react-native-community/react-native-svg#235]
Hi ! 

I'm trying to unlink this module with `react-native unlink react-native-svg` but I get: 
```
rnpm-install ERR! It seems something went wrong while unlinking. Error: Cannot read property 'config' of undefined 

Cannot read property 'config' of undefined
```

How to fix that?

**Comment by magicismight** [comment]
It seems like a bug in rnpm.

**Comment by braco** [comment]
Getting this with another package, this is currently the only Google result.
