### ISSUE TITLE
Error: The file name must end with .xml or .png

### ISSUE THREAD

**Issue by thienanle** [react-native-community/react-native-svg#239]
Trying to build onto Android device and I get the error below. Anyone know how this can be fixed?
```
Execution failed for task ':app:mergeDebugResources'.
> /path/to/project/android/app/src/main/res/drawable-mdpi/app_shared_assets_icons_acknowledge.svg: Error: The file name must end with .xml or .png
```

**Comment by lappalj4** [comment]
+1

**Comment by liuliangsir** [comment]
+1

**Comment by brancooo1** [comment]
@liuliangsir does this work on android?

**Comment by justindachille** [comment]
As the error states, you can only have .png or .xml files in your /drawable folders

**Comment by adamski** [comment]
Adding `android.disableResourceValidation=true` got me past the build error.

**Comment by adamski** [comment]
> gradle.properties (Project Properties)

**Comment by vivekagarwal277** [comment]
Not working. also I stored my mp3 file in drawable/raw folder, still it did not build

**Comment by SatishMavani** [comment]
+1

**Comment by marcosmartinez7** [comment]
+1

**Comment by ivan-jorge001** [comment]
+1

**Comment by msand** [comment]
This library isn't meant for reading .svg files, but for creating react components which render svg. There are other libraries which read svg files and render them using this library.

**Comment by msand** [comment]
https://github.com/react-native-community/react-native-svg/issues/12

**Comment by msand** [comment]
Docs have been updated: https://github.com/react-native-community/react-native-svg#use-with-svg-files
With react-native-svg-transformer you can now do this:
```jsx
import Logo from "./logo.svg";
const myApp = () => <Logo width={120} height={40} />
export default myApp
```

**Comment by langson6502** [comment]
After I add 'android.disableResourceValidation=true' to gradle.properties, I got the following warning message while syncing:

WARNING: The option setting 'android.disableResourceValidation=true' is experimental and unsupported.
The current default is 'false'.

I use Android Studio 3.4

**Comment by mrigo** [comment]
Any update on this?
Is android.disableResourceValidation=true the only way to solve this?

**Comment by msqar** [comment]
Need help about this error. 
`android.disableResourceValidation=true didn't work. `

**Comment by msand** [comment]
Remove the svg files from the drawable folders

**Comment by msqar** [comment]
@msand thanks for replying, i did it but now it throws this:

```
Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/marian-mac/Documents/dev/myapp/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/marian-mac/Documents/dev/myapp/node_modules/jest-haste-map/build/index.js:691:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  mockPath1: 'package.json',
  mockPath2: 'android/app/src/main/res/raw/package.json' }
```

There's always errors, errors, errors don't know what to do.
