### ISSUE TITLE
"RCTConvert(RNSVG) CGPath:" exception  in react-native-code-push because of 4.6.1 version  of react-native-svg 

### ISSUE THREAD

**Issue by yasemincidem** [react-native-community/react-native-svg#240]
When i used  `4.4.1` version of `react-native-svg`,app was launching properly that i made code push through `react-native-coe-push`.However , when i updated version from `4.4.1` to `4.6.1`,app crashed  and it throws exception an error like following  in `code push crash log`.
```
RCTConvert(RNSVG) CGPath:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x1708783c0'
```
The reason of error is not `code-push` because other third party plugins will work properly when i made code push.Why does this error throw in version of `4.6.1`. What is your opinion about this error?

**Comment by msand** [comment]
This is probably because of a change in the api between javascript and native. If the api of the bridge communication changes, you need to make a new native build instead of only code-push the new javascript.
