### ISSUE TITLE
Conflict between ART and react-native-svg

### ISSUE THREAD

**Issue by ilya4544** [react-native-community/react-native-svg#246]
I'm using this package with ART.

When I'm trying to initialize ART object (e.g. `Shape`), app is crushing and I'm getting this error:

`[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayI length]: unrecognized selector sent to instance 0x131a20af0'`

I had to delete and unlink `react-native-svg` in order to make ART work.

Please have a look at issue with the same problem
https://github.com/oblador/react-native-progress/issues/40#issue-200216423

**Comment by Davidmeteor** [comment]
Blocked by the same issue with [https://github.com/capitalone/react-native-pathjs-charts](https://github.com/capitalone/react-native-pathjs-charts
)
[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0
2017-02-19 20:37:00.389 TWFinTech[2883:44690] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x600000657be0'

Any update on this one? Thanks!

**Comment by nuravdhiman** [comment]
Blocked by the same issue. Can anyone please help on this.

**Comment by arnavyagnik** [comment]
Thanks @marzolfb for the reference, it actually solved the problem by downgrading the react-native-svg to 4.5.x . @magicismight  : any update on this or is the issue in  roadmap for next release?

**Comment by magicismight** [comment]
5.1.6 has fixed this

**Comment by lwansbrough** [comment]
@magicismight I'm getting `NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector` in the latest version which is causing my app to crash. Appears to be happening when I transition away (using 

```
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-svg": "^5.2.0",
    "react-navigation": "^1.0.0-beta.11",
```

Application throws here:

```
- (instancetype) initWithPathString:(NSString *)d
{
    if (self = [super init]) {
        NSRegularExpression* decimalRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"(\\.\\d+)(?=\\-?\\.)" options:0 error:nil];
        _originD = d;
---->   _d = [decimalRegularExpression stringByReplacingMatchesInString:d options:0 range:NSMakeRange(0, [d length]) withTemplate:@"$1,"];
        _pathRegularExpression = [[NSRegularExpression alloc] initWithPattern:@"[a-df-z]|[\\-+]?(?:[\\d.]e[\\-+]?|[^\\s\\-+,a-z])+" options:NSRegularExpressionCaseInsensitive error:nil];
    }
    return self;
}
```
