### ISSUE TITLE
Any sort of edge smoothing?

### ISSUE THREAD

**Issue by joecaraccio** [react-native-community/react-native-svg#255]
This is less of an issue and more of just a question but is there any sort of edge smoothing in this?

IN Particular something like shhape-rendering="crispEdges" from W3's svg library

**Comment by msand** [comment]
No support for shape-rendering as of yet.

**Comment by ManigandanRaamanathan** [comment]
@msand when will we have the shape rendering support? @joecaraccio did you find your solution?

**Comment by msand** [comment]
Try increasing the size of your viewBox perhaps? Do you want sharper/crisper edges or faster rendering? Can you post a reproduction showing issues?

**Comment by ManigandanRaamanathan** [comment]
@msand I want to make the edges smooth. On the real device the edges are crisp. 

This below is my code for svg:-

`
<Svg width={mask.width + 20} height={window.height/2.3}>
                                {/* <Path
                                    fill={mask.bgColor}
                                    d={`M375,51.1V-0.4c-46,24.8-113.2,40.5-188,40.5c-74.3,0-141-15.4-187-40v51H375z`}
                                    // d={`M 0 0 L 0 ${mask.height} L ${mask.width} ${mask.height} L ${mask.width} 0 A ${mask.width / 2} ${mask.height / 2} 0 0 1 ${mask.width / 3} ${mask.height / 3} A ${mask.width / 2} ${mask.height / 2} 0 0 1 0 0 z `} 
                                />  */}
                                <Defs>
                                    <LG id="grad" x1="0%" y1="0%" x2="0%" y2="100%">
                                        <Stop offset="80%" stopColor={colors.curvedViewGradient[0]} stopOpacity="1" />
                                        <Stop offset="100%" stopColor={colors.curvedViewGradient[1]} stopOpacity="1" />
                                    </LG>
                                </Defs>
                                <Circle cx={mask.width / 2} cy={`-${window.height - (window.height/2.3) + 2}`} r={window.height} fill="url(#grad)" 
                                    stroke="black"
                                    strokeLinejoin="round"
                                    strokeWidth="3"
                                    strokeLinecap="round"
                                />
                            </Svg>
`

**Comment by ManigandanRaamanathan** [comment]
@msand the above is the code I'm using

**Comment by SrBrahma** [comment]
@msand any news about `shape-rendering`? In web, it fixed an issue I was having:

![image](https://user-images.githubusercontent.com/28177550/123567022-984abb00-d797-11eb-85f1-10b35b830625.png)
Without it

![image](https://user-images.githubusercontent.com/28177550/123567225-08f1d780-d798-11eb-9072-31318f8df377.png)
With `shape-rendering="crispEdges"`.

This blue rect is a 100% width svg, relative to the pink component below.

I am having a pain to deal with it.
