### ISSUE TITLE
RNSVGBrushConverter deleted but still used

### ISSUE THREAD

**Issue by julienfouilhe** [react-native-community/react-native-svg#259]
Hi, this commit: 9b62d500ce7166d312a100aab21dae173b8db449 has deleted the `RNSVGBrushConverter` class but it is still being used in `ios/Brushes/RNSVGBrush.m` for instance

Cc @magicismight

**Comment by julienfouilhe** [comment]
Fixed in PR #253

**Comment by EuAndreh** [comment]
@julienfouilhe This can be closed, now :)

**Comment by ElvisChiang** [comment]
fixed in 5.1.6 but is not yet published to npm

**Comment by magicismight** [comment]
Just released 5.1.6

**Comment by Snorlock** [comment]
Could you remember to make the realases here on github aswell @magicismight
