### ISSUE TITLE
Some SVG files are not rendering. Throws error "Error while updating property 'd'

### ISSUE THREAD

**Issue by chitezh** [react-native-community/react-native-svg#262]
See screenshot

https://cloud.githubusercontent.com/assets/865596/18410885/418664e8-7781-11e6-85df-7f3555e95f7f.png

File [see gist](https://gist.github.com/chitezh/ce5d782fbe9f934e94667a6b9cc3fc09)

**Comment by JunhyeokHeo** [comment]
i've got same problem.

**Comment by chitezh** [comment]
@JunhyeokHeo, I was actually trying to load network svg images using `react-native-svg-uri` which uses this library. It worked on some and throws the error on others.

I ended up using React Native WebView. My approach is extracted in https://github.com/chitezh/react-native-svg-image

**Comment by joshjconlin** [comment]
I have this problem as well

**Comment by richardgorman** [comment]
@chitezh Would this method work with relative file paths?

**Comment by chitezh** [comment]
@richardgorman You can look at the package, the approach would work.

You need to just get the content of your svg file into the WebView

**Comment by richardgorman** [comment]
@chitezh Okay I will try it. Does creating a separate WebView for each icon not cause a performance issue?

**Comment by chitezh** [comment]
WebViews are usually less performant than native rendering. Nevertheless, I had to use it as a workaround.

**Comment by msand** [comment]
The gist includes css style and js script tags. I wouldn't expect it to work in RN. You can inline the css and limit yourself to the supported components. Then it should work.
