### ISSUE TITLE
Stroke on Text and Path not working on Android

### ISSUE THREAD

**Issue by oakis** [react-native-community/react-native-svg#263]
I tried the Text example from the documentation and it does not work, it just shows up as plain white text.
What I can see is that fill is behaving like stroke on Path's.

"react": "15.4.2",
"react-native": "0.40.0",
"react-native-svg": "^4.6.1"

**Comment by oakis** [comment]
Solved by updating to react-native-svg 5.1.3 and running ./gradlew clear

**Comment by oakis** [comment]
Path is indeed working, but since I had scale 0.1 it was paper thin and hard to see.

**Comment by pushpendramishra660** [comment]
<Line
         x1 = "230"
         y1 = "193.5"
         x2 = "327.8"
         y2 = "127.5"
        stroke="none"
        id="line1"  
        />
