### ISSUE TITLE
Reuse on Web?

### ISSUE THREAD

**Issue by timscott** [react-native-community/react-native-svg#265]
I have created a graph using react-native-svg and D3. Is there a simple way to to reuse it for web, in an HTML page?

If not, how hard would it be to add this capability?

**Comment by RangerMauve** [comment]
The best way would be to go to the `elements` folder and create web versions of each of those components by using `React-DOM`.

For example the [G](https://github.com/react-native-community/react-native-svg/blob/master/elements/G.js) component could look like:

```javascript
export default class extends Shape{
    static displayName = 'G';

    static propTypes = pathProps;

    render() {
        let {props} = this;

        return <g
            {...extractProps(props, this)}
        >
            {props.children}
        </g>;
    }
}
```

In this example, I've replaced the `RNSVGGroup` component with the HTML tag `g` which is a tag that's supported out of the box.

**Comment by ndbroadbent** [comment]
[react-native-web](https://github.com/necolas/react-native-web) support would be awesome. Like @RangerMauve said, it would just require `*.web.js` versions of each component. This shouldn't be too hard, since this is just a subset of SVG, and it's just rendering XML tags.

I might start working on some of this, but I don't know if I'll do everything. Right now I'm just using SVG to add an outline to some text, so I'll get that working first. I'll post a link to my branch when I'm finished, if anyone wants to take over and finish everything.

**Comment by timscott** [comment]
@ndbroadbent - Let me know how it goes. I might be able to jump in at some point. 

Regarding PR, are you saying it would need to take a dependency on ```react-native-web```? Maybe it could be done without such a dependency?

**Comment by RangerMauve** [comment]
@ndbroadbent Worst case, you can have this be a separate project (call it `react-native-svg`, maybe?), and then people can alias `"react-native-svg": "react-native-svg-web"` in their projects

**Comment by ndbroadbent** [comment]
@timscott Hi, no there would be no dependency on `react-native-web`, the only thing we need to do is create the `*.web.js` versions and then it will just work. But I was just saying that the `web` platform is not really officially supported by React Native, so the maintainers of this library might only want to support Android and iOS. But it would be cool if they would agree to merge in web support.

**Comment by sibelius** [comment]
you should check what https://github.com/FormidableLabs/victory-native does

**Comment by msand** [comment]
You can also use https://github.com/godaddy/svgs instead, svgs is a compatiblity layer between svg and react-native-svg

**Comment by timscott** [comment]
@msand, Sweet. That looks perfect. I'll try it out. Thanks!

**Comment by msand** [comment]
@timscott Great, thanks :) You can check out https://github.com/msand/RNSvgTextBug if you wanna see an example of how to combine https://github.com/zeit/next.js for the web part and react-native for mobile using a single codebase ;)
