### ISSUE TITLE
No ViewManager defined for RNSVG on Android

### ISSUE THREAD

**Issue by Jperrin42** [react-native-community/react-native-svg#276]
Hello, 
before i explain i have to say that i already tried #135 

So, i installed RNSVG, linked using react-native link react-native-svg.
Then i checked my MainApplication.java and tried to include import com.horcrux.svg.SvgPackage (already done by the link) and import com.horcrux.svg.RNSvgPackage; (for version < 5.1.5 but still tried) and add them to the getPackage method (both and one by one).

I checked about the manual installation and everything seems to be done properly.

But i still have the issue and i don't know what to do next since it seems to have solved the problem for other people.

am I missing something ?
Thanks in advance.

**Comment by jayesbe** [comment]
Had the same issue. Was missing the compile line in build.grade after the react-native link.

After I added that, used android-studio to rebuild. 
Restarted the package manager, and hit reload on the app. 
Working now.

**Comment by Tonacatecuhtli** [comment]
Hi I checked the build.gradel but everything seems to be fine still having this issue. how about you @Jperrin42 ?

**Comment by lakeoffaith** [comment]
i have the same issue

**Comment by lakeoffaith** [comment]
my problem is solved,i solve the android studio problem as 
his version of Android Studio is incompatible with the Gradle Plugin used. Try disabling Instant Run 
it work now

**Comment by ayberkanilatsiz** [comment]
+1

**Comment by ayberkanilatsiz** [comment]
I found solution for me. I use wix (Navigation https://wix.github.io/react-native-navigation) on my project. It's linking different. Look this => https://github.com/wix/react-native-navigation/pull/1245

**Comment by nhducit** [comment]
It doesn't work for me even instant run is disabled

**Comment by prgpascal** [comment]
The following steps solved the issue for me:
- `react-native link react-native-svg` 
- manually delete the  `/android/app/build` directory
- `npm start -- --reset-cache`
- Run the packager for Android

**Comment by msand** [comment]
Closing this.

**Comment by vedantroy** [comment]
@jayesbe What exactly is the compile line? I'm guessing I need to manually add it to my build.gradle.
