### ISSUE TITLE
iOS React headers need to be manually added from Pods

### ISSUE THREAD

**Issue by ferologics** [react-native-community/react-native-svg#277]
## Background

Hybrid iOS / React Native app with CocoaPods. Here's the project structure:

root
├── index.ios.js
├── ios
├── jsconfig.json
├── node_modules
├── package.json
├── src
└── yarn.lock

3 directories, 4 files

./ios
├── Archived Code
├── Simulator
├── App-Info.plist
├── App.entitlements
├── App.xcodeproj
├── App.xcworkspace
├── AppDev\ Tests
├── AppDev-Info.plist
├── Dev.entitlements
├── Libraries
├── Podfile
├── Podfile.lock
├── Pods
├── README.md
├── Uncrustify
└── iOS-Components

9 directories, 7 files

## Problem
Every time I reinstall my node module it makes the `header search paths` reset.
The project is linked but it fails to build with error: 

> `Lexical or Preprocessor Issue` ⬇️
> ➡️ `'React/UIView+React.h' file not found`

<img width="256" alt="error_react" src="https://cloud.githubusercontent.com/assets/5576161/23747407/d43c2ebe-04bf-11e7-9400-2832d48b398d.png">

## Solution

Providing a path inside the `react-native/React` node module doesn't work. 
The fix is to add header search path for the the Pods directory.

<img width="515" alt="header_search_paths" src="https://cloud.githubusercontent.com/assets/5576161/23747067/a9e41394-04be-11e7-9fdb-c66cfa83847a.png"> 
&nbsp;
^^^^^^^^^^^^^^^^^^^^^^^ ⚠️ change it to recursive ⚠️ ^^^^^^^^^^^^^^^^^^^^^^^
&nbsp;

Path text - `$(SRCROOT)/../../../ios/Pods`

**Comment by itchingpixels** [comment]
Same here!

**Comment by ferologics** [comment]
@itchingpixels you can check my fork for example - https://github.com/ferologics/react-native-svg

**Comment by itchingpixels** [comment]
@ferologics managed to solve this by using Cocoapods itself to include the native dependencies of RNSVG -  try adding this to your Podfile:
pod 'RNSVG', :path => 'src/node_modules/react-native-svg' (this may be not where you have it)

**Comment by ferologics** [comment]
🎳 @itchingpixels , thank you 👍

**Comment by pcompassion** [comment]
doc says to do 

     react-native link react-native-svg

is it the same as 

    pod 'RNSVG', :path => 'src/node_modules/react-native-svg'  

?
