### ISSUE TITLE
[Question] Any plans to support morph animations between svg's?

### ISSUE THREAD

**Issue by alpfilho** [react-native-community/react-native-svg#285]
I really would like to have a chance to use that feature

**Comment by msand** [comment]
There are other libraries available for this. Closing.

**Comment by buitrbao222** [comment]
hi @msand, can you suggest some libraries for morphing Svg that is compatible with react-native-svg? as of 2025 neither react-native-svg, or the native Animated API, or react-native-reanimated supports morphing SVG paths
