### ISSUE TITLE
Parse Issue - Expected a type

### ISSUE THREAD

**Issue by Snorlock** [react-native-community/react-native-svg#288]
In RNSVGPattern i get a parse issue when building.
It is saying Expected a type on this line:
Where the xcode arrow is pointed is marked with (^)

`- (void)paint:(CGContextRef)context opacity:(CGFloat)opacity brushConverter:((^)RNSVGBrushConverter *)brushConverter;`

Any idea what his might be? And how can the compiling crash on a library that supposadly should work

**Comment by NoilPaw** [comment]
This is fixed in #259 and will be included in v 5.1.6.
