### ISSUE TITLE
Does project have changelog or release notes?

### ISSUE THREAD

**Issue by vovkasm** [react-native-community/react-native-svg#290]
5.1.6 just released to npm, but I can't see clearly what changed:
1. https://github.com/react-native-community/react-native-svg/releases - shows 5.1.3 as last release
2. Latest tag in this repo is 5.1.3
3. No CHANGELOG.md or alternatives in repo
4. Repo has branch 5.1.6, but it is totally mess to see what changed with it.
5. How to determine exact commit that relate to npm package version?

**Comment by msand** [comment]
I tried to keep tags in git in sync with npm versions now. Should be slightly clearer. Also making some release notes in here: https://github.com/react-native-community/react-native-svg/releases

**Comment by n1ru4l** [comment]
@msand There is literally no description provided for the last releases...

**Comment by msand** [comment]
@n1ru4l Yeah.  Well, I'm just doing this for fun on my freetime and am building a company more than full time. While choosing between building functionality, fixing issues and writing release notes I've put lower priority on notes, as the commit log is there to read. Please feel free to summarize it and I'll post release notes. Or would you prefer an empty but up to date release log?

**Comment by msand** [comment]
@n1ru4l v7.0.0 and release notes available for the past versions.

**Comment by n1ru4l** [comment]
@msand Thank you so much for your effort!

**Comment by neiker** [comment]
And what about this?

![image](https://user-images.githubusercontent.com/688444/48500006-8d2a0300-e818-11e8-88a3-5b2348b80372.png)

![image](https://user-images.githubusercontent.com/688444/48500020-95823e00-e818-11e8-89c5-5b4a900d1025.png)

**Comment by neiker** [comment]
I just update from v6.4.0 to v8.0.8, it's broken and its really hard to know where start to looking for solutions

https://github.com/react-native-community/react-native-svg/compare/v6.4.0...v8.0.7

**Comment by msand** [comment]
@neiker The commit messages have summaries of the changes, haven't had time to write release notes yet. What kind of issues do you have? Any description/replication?

**Comment by Nhacsam** [comment]
Thank you @msand for so much effort. Your library is very great.

But I agree with this topic. I have to do an upgrade of 3 majors release to fix #967 and I am very worried of having unseen regression. There is a lot of svg included via your library in my application.

If you don't have time for release note, can you, at least, just provide the breaking changes for the major releases ?

There is also some tools for to generate a changelog from commit mesages. Like [Commitizen](https://github.com/commitizen/cz-cli) with [conventional-changelog](https://github.com/conventional-changelog/standard-version). I recommend you to use one of theses.

**Comment by msand** [comment]
Yea, I fully agree we should have a proper changelog. I'm sorry for not having taken time for it. Automating it would certainly be necessary for this to have a good chance of improving, with my current time constraints. There's some cooperation going on in react-native-community to streamline these kinds of things. If you can, it would be greatly appreciated if you would make a pr to add some automation for this. I'm relatively busy at the moment and mainly been fixing bugs when reported. 

There shouldn't be any really major breakages, mostly improved spec conformance and the removal of proptupes in sync with react-native. I've made major version bumps just to be on the safe side, such that people can try changing major version to isolate the cause of issues, to report them/ask for help. At least for now, the latest version should have all known regressions from earlier major version bumps fixed, afaik.
