### ISSUE TITLE
Using svg@5.1.5 on Android, Unfortunately, app has stopped

### ISSUE THREAD

**Issue by shengzihong** [react-native-community/react-native-svg#291]
I am using svg@5.1.5 recently on Android. I was trying to dynamically create path with PanResponder. It works perfectly on IOS but Android. Every time I tried to draw a line, it crashed unexpectedly. It says Unfortunately, app has stopped. Is there anyone has the same problem on Android.

**Comment by magicismight** [comment]
Thanks for reporting this.
But can you provide more information about this?

**Comment by msand** [comment]
Insufficient info, closing...
