### ISSUE TITLE
[bug] Rotated gradient rendering incorrectly

### ISSUE THREAD

**Issue by kruczy** [react-native-community/react-native-svg#292]
In a simplified scenario:
```js
<Defs>
  <LinearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
    <Stop
      offset="0"
      stopColor="white"
    />
    <Stop
      offset="1"
      stopColor="red"
    />
  </LinearGradient>
</Defs>

<G x="10" y="10" rotate="45">
  <Rect
    width="100"
    height="10"
    fill="url(#gradient)"
  />
</G>

<G x="30" y="10" rotate="0">
  <Rect
    width="100"
    height="10"
    fill="url(#gradient)"
  />
</G>
```
the result:
<img width="89" alt="screen shot 2017-03-24 at 9 49 57 am" src="https://cloud.githubusercontent.com/assets/1475512/24288952/361a846a-1077-11e7-9b42-5d313e6bba5e.png">

the rotated `Rect` gradient renders rotated but starts and ends in wrong places, it looks like it fills a rectangle that would fit the rotated one

**Comment by msand** [comment]
Could you try this with the latest version? I think it might be fixed. Can this be closed?

**Comment by msand** [comment]
Closing because of no response.
