### ISSUE TITLE
Svg doesn't resize with viewbox. App crash if prop viewbox change to viewBox.

### ISSUE THREAD

**Issue by YanaKopyshchyk** [react-native-community/react-native-svg#301]
I try to make svg with diffenrent size. It's default size is width="30", height="28". When using viewbox="0 0 100 100" svg doesn't change it width and height to 50, 50. It is possible to resize svg like that? 
```javascript
render() {
    return ( 
        <Svg width="50" height="50" viewbox="0 0 100 100">
            <Path fill={ color } d="..." </Path>
        </Svg>
    );
}
```
And app crash if prop viewbox change to viewBox.

**Comment by joemckie** [comment]
I'm having problems with the viewBox prop after upgrading to `^5.0.0`, too.

**Comment by kirillpisarev** [comment]
related [react-native-svg-uri/issues/33](https://github.com/matc4/react-native-svg-uri/issues/33)

**Comment by markallancourtney** [comment]
I was experiencing this on Android while using
"react-native-svg": "^4.3.1"

After upgrading to
"react-native-svg": "5.1.7"
the Svg component resizes correctly in Android when the Svg height and width props changes.

**Comment by msand** [comment]
Can you try with the latest version or my PR https://github.com/react-native-community/react-native-svg/pull/596
Viewbox is definitely working at least.
