### ISSUE TITLE
"Expected a component class, got [object Object]" error #244

### ISSUE THREAD

**Issue by anitalanet** [react-native-community/react-native-svg#302]
Tabbar Page where i am binding the diffrent class view but got above mention error

**TabbarPage**
'use strict';

var React = require('react');
var ReactNative = require('react-native');
var {
    StyleSheet,
    TabBarIOS,
    Text,
    View,
} = ReactNative;

var base64Icon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAQAAACSR7JhAAADtUlEQVR4Ac3YA2Bj6QLH0XPT1Fzbtm29tW3btm3bfLZtv7e2ObZnms7d8Uw098tuetPzrxv8wiISrtVudrG2JXQZ4VOv+qUfmqCGGl1mqLhoA52oZlb0mrjsnhKpgeUNEs91Z0pd1kvihA3ULGVHiQO2narKSHKkEMulm9VgUyE60s1aWoMQUbpZOWE+kaqs4eLEjdIlZTcFZB0ndc1+lhB1lZrIuk5P2aib1NBpZaL+JaOGIt0ls47SKzLC7CqrlGF6RZ09HGoNy1lYl2aRSWL5GuzqWU1KafRdoRp0iOQEiDzgZPnG6DbldcomadViflnl/cL93tOoVbsOLVM2jylvdWjXolWX1hmfZbGR/wjypDjFLSZIRov09BgYmtUqPQPlQrPapecLgTIy0jMgPKtTeob2zWtrGH3xvjUkPCtNg/tm1rjwrMa+mdUkPd3hWbH0jArPGiU9ufCsNNWFZ40wpwn+62/66R2RUtoso1OB34tnLOcy7YB1fUdc9e0q3yru8PGM773vXsuZ5YIZX+5xmHwHGVvlrGPN6ZSiP1smOsMMde40wKv2VmwPPVXNut4sVpUreZiLBHi0qln/VQeI/LTMYXpsJtFiclUN+5HVZazim+Ky+7sAvxWnvjXrJFneVtLWLyPJu9K3cXLWeOlbMTlrIelbMDlrLenrjEQOtIF+fuI9xRp9ZBFp6+b6WT8RrxEpdK64BuvHgDk+vUy+b5hYk6zfyfs051gRoNO1usU12WWRWL73/MMEy9pMi9qIrR4ZpV16Rrvduxazmy1FSvuFXRkqTnE7m2kdb5U8xGjLw/spRr1uTov4uOgQE+0N/DvFrG/Jt7i/FzwxbA9kDanhf2w+t4V97G8lrT7wc08aA2QNUkuTfW/KimT01wdlfK4yEw030VfT0RtZbzjeMprNq8m8tnSTASrTLti64oBNdpmMQm0eEwvfPwRbUBywG5TzjPCsdwk3IeAXjQblLCoXnDVeoAz6SfJNk5TTzytCNZk/POtTSV40NwOFWzw86wNJRpubpXsn60NJFlHeqlYRbslqZm2jnEZ3qcSKgm0kTli3zZVS7y/iivZTweYXJ26Y+RTbV1zh3hYkgyFGSTKPfRVbRqWWVReaxYeSLarYv1Qqsmh1s95S7G+eEWK0f3jYKTbV6bOwepjfhtafsvUsqrQvrGC8YhmnO9cSCk3yuY984F1vesdHYhWJ5FvASlacshUsajFt2mUM9pqzvKGcyNJW0arTKN1GGGzQlH0tXwLDgQTurS8eIQAAAABJRU5ErkJggg==';
import firstPage from './VC/Home/TabbarVC1';
import LoginPage from './VC/Home/TabbarVC1'

//import vw_tabbar_2 from './VC/Home/TabbarVC_2';
//import vw_tabbar_3 from './VC/Home/TabbarVC_3';
//import vw_tabbar_4 from './VC/Home/TabbarVC_4';

class HomeVC extends React.Component {
    static title = '<TabBarIOS>';
    static description = 'Tab-based navigation.';
    static displayName = 'TabBarExample';

    state = {
        selectedTab: 'redTab',
        notifCount: 0,
        presses: 0,
    };

    _renderContent = (color: string, pageText: string, num?: number) => {
        return (
            <View style={[styles.tabContent, {backgroundColor: color}]}>
                <Text style={styles.tabText}>{pageText}</Text>
                <Text style={styles.tabText}>{num} re-renders of the {pageText}</Text>

            </View>
        );
    };
    _firstPage()
    {
        return(
            <View style={[styles.tabContent, {backgroundColor: 'pink'}]}>
                <firstPage/>
            </View>
        );
    }

    render() {
        return (
            <TabBarIOS
                unselectedTintColor="darkgray"
                tintColor="white"
                unselectedItemTintColor="green"
                barTintColor="darkslategrey">
                <TabBarIOS.Item
                    selected={this.state.selectedTab === 'Contact'}
                    systemIcon="contacts"
                    onPress={() => {
                    this.setState({
                        selectedTab: 'Contact',
                    });
                }}>
                    {this._firstPage()}

                </TabBarIOS.Item>

            </TabBarIOS>
        );
    }
}

var styles = StyleSheet.create({
    tabContent: {
        flex: 1,
        alignItems: 'center',
    },
    tabText: {
        color: 'white',
        margin: 50,
    },
});

module.exports = HomeVC;

**Render Page**

'use strict';

var React = require('react');
var ReactNative = require('react-native');

var {
    StyleSheet,
} = ReactNative;

var {
    View,
    Text,
    Component
} = React;

var styles = StyleSheet.create({
    description: {
        fontSize: 20,
        textAlign: 'center',
        color: '#FFFFFF'
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    }
});

class TabbarVC_1 extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.description}>
                    This could be your second tab
                </Text>
            </View>
        );
    }
}

module.exports = TabbarVC_1;

**Comment by msand** [comment]
Seems like an old issue, closing...
