### ISSUE TITLE
Load images from URI

### ISSUE THREAD

**Issue by lschmierer** [react-native-community/react-native-svg#310]
I need the possibility to render images from URI, especially images from the local filesystem.

Is this currently possible?

**Comment by lschmierer** [comment]
I have looked into the source (at least for android) and wonder wether this should work.
The android implementation uses Fresco and it should work with any kind of URI (local or from network).
However, It didn't worked when I tried it.

The Todo list of the README states "Load Image from URL.". What is meant by that? What I want to accomplish or loading actual SVGs?

**Comment by lschmierer** [comment]
It works. The accident was with me.
Forgot to start URL with "file://".

**Comment by henrikra** [comment]
Can you provide example code for this?

**Comment by lschmierer** [comment]
Just use Image with href="file://path/to/local/file.svg"
