### ISSUE TITLE
Image iOS render wrong origin

### ISSUE THREAD

**Issue by lschmierer** [react-native-community/react-native-svg#312]
Image rendering on iOS seems to be not quite right.

Following code
```
<Svg width="100" height="100">
  <Image
    x="0"
    y="0"
    width="200"
    height="200"
    href={this.props.image}
  />
</Svg>
```
produces
<img width="487" alt="screen shot 2017-04-21 at 10 07 38" src="https://cloud.githubusercontent.com/assets/2204708/25268799/6d9a3502-267a-11e7-9c13-c1cf9f99994e.png">

while following is expected:
<img width="487" alt="screen shot 2017-04-21 at 10 07 53" src="https://cloud.githubusercontent.com/assets/2204708/25268818/77acf020-267a-11e7-8435-080644cde517.png">

Setting the `y` property to `-50`, however, makes it render correctly:
```
<Svg width="100" height="100">
  <Image
    x="0"
    y="-50"
    width="200"
    height="200"
    href={this.props.image}
  />
</Svg>
```

I did not quite understand yet what is the rational of the number `-50` here.
The issue seems to be with the origin, the image is rendere, somehow.

On Android, everything seems to be correct.

**Comment by msand** [comment]
@lschmierer Is this still in issue with the latest version?

**Comment by lschmierer** [comment]
@msand I have no idea... switched to Flutter long time ago...

**Comment by msand** [comment]
@LRNZ09 Can you try with the latest v7? Or even better, this branch: https://github.com/react-native-community/react-native-svg/compare/SVGLength

**Comment by msand** [comment]
v8 has been released, this issue has like been fixed in https://github.com/react-native-community/react-native-svg/pull/763 which is available since v7 up.
