### ISSUE TITLE
Image cropped itself when y over 100

### ISSUE THREAD

**Issue by isener** [react-native-community/react-native-svg#313]
I don't understand what happened. 
When I place Text property to svg, it works like charm,
But when I place Image same logic, it brokes image.

<img width="464" alt="screenshot at apr 23 19-43-57" src="https://cloud.githubusercontent.com/assets/10687714/25315425/3dd94d1e-285d-11e7-895a-278ba1319d35.png">

**Comment by lschmierer** [comment]
Seems to be related to #312

**Comment by isener** [comment]
It's not actual solution.there is something wrong on rendering image

**Comment by LRNZ09** [comment]
This issue is still happening on iOS with version `6.3.1`

**Comment by msand** [comment]
Please try with the latest version, or provide a full replication. Closing until then.
