### ISSUE TITLE
react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.

### ISSUE THREAD

**Issue by fengjr-tech** [react-native-community/react-native-svg#314]
"react": "16.0.0-alpha.6",
  "react-native": "0.43.4",

react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.

**Comment by VincentFTS** [comment]
duplicate of #305

**Comment by magicismight** [comment]
Fix in 5.1.8

**Comment by getreup** [comment]
That did not fix it since the dependency is now on react-native@0.44.0
