### ISSUE TITLE
Create Family tree

### ISSUE THREAD

**Issue by codesinghanoop** [react-native-community/react-native-svg#315]
This is not an issue and thanks for the good work you did.

I found this library very useful and I expect the construction of family tree would be possible using this library, so please guide me through.

Any help would be appreciated.

**Comment by msand** [comment]
Not sure what you mean here. You can use e.g. d3.js to transform some data about a set of individual and their ancestry to some geometric data, then visualize that using svg. Very much depends on the data and the visualization wanted. I'll go ahead and close this as it probably fits better in e.g. the stackoverflow format.
