### ISSUE TITLE
SvgView.java can not find symbol UNSET

### ISSUE THREAD

**Issue by chetankotkar** [react-native-community/react-native-svg#324]
am getting new error in the file SvgView.java  can not find symbol TouchEvent.UNSET. In this file it also shows compile time error at   TouchEvent.obtain(
                mTargetTag,
                type,
                ev,
                mGestureStartTime,
                ev.getX(),
                ev.getY(),
                mTouchEventCoalescingKeyHelper));

Anyone can guide on this issue.

**Comment by jmeyers91** [comment]
I ran into the same issue and fixed it (temporarily) by changing my react-native-svg version from `^5.1.7` to `5.1.7`. The issue appears to be related to [this commit](https://github.com/react-native-community/react-native-svg/commit/2fd178da2872a169e13100308e0cff524197e26a).

**Comment by magicismight** [comment]
5.1.8 only support react-native>=0.44.0

**Comment by kytwb** [comment]
Semver much?

**Comment by kytwb** [comment]
@magicismight semver much?
