### ISSUE TITLE
Svg width/height change and preserveAspectRatio='xMidYMid meet'

### ISSUE THREAD

**Issue by grassias** [react-native-community/react-native-svg#335]
I have created a <Svg> component with some initial dimensions, a fixed viewBox and preserveAspectRatio='xMidYMid meet'. When I try to dynamically change its dimensions later (e.g. when the device orientation changes), part of my scene gets cropped out instead of rerendered with the correct recalculations that preserveAspectRatio dictates. On the other hand, when I change some of its children attributes (e.g. Rect), the rerendering works as expected. Can anyone else reproduce it as well?

**Comment by cowlingj** [comment]
looks like the width and height are fixed as props, see [here](https://github.com/react-native-community/react-native-svg/blob/master/elements/Svg.js#L72)

**Comment by msand** [comment]
I have an open PR fixing this now https://github.com/react-native-community/react-native-svg/pull/596
