### ISSUE TITLE
Crashes app when container element has display set to none with error width and height must be > 0

### ISSUE THREAD

**Issue by redpandatronicsuk** [react-native-community/react-native-svg#337]
Setting `display: 'none'` style on the container element crashes the app, for example:
```
<View style={{display: 'none'}}>
  <Svg width={100} height={100}>
    ...
  </Svg>
</View>
```
Shows a red screen with the error message: width and height must be > 0

**Comment by NingYuanLee** [comment]
I ran into the same problem, and I gave up using "display"

**Comment by colinbr96** [comment]
Bump. This is an annoying issue that shouldn't cause a crash.

**Comment by ivansifrim** [comment]
+1

**Comment by ThomasLabstep** [comment]
+1

**Comment by codler** [comment]
+1

**Comment by cbsorrilha** [comment]
+1 here.

We "solved" this using conditional rendering instead of `display:none` .

**Comment by msand** [comment]
This seems to work fine now.
