### ISSUE TITLE
YogaNodeAPI error in android using react-native@0.45.0-rc.0

### ISSUE THREAD

**Issue by ayunawani** [react-native-community/react-native-svg#340]
**Description**

I am getting the following error on android.

```
MyProject/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:17: error: cannot find symbol
import com.facebook.yoga.YogaNodeAPI;
                        ^
  symbol:   class YogaNodeAPI
  location: package com.facebook.yoga
MyProject/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:34: error: cannot find symbol
                YogaNodeAPI node,
                ^
```

**Dependency Version:**
```
    "react-native": "0.45.0-rc.0",
    "react-native-svg": "5.1.8"
```

**Suggested Solution**

In Yoga latest release **v1.5.0**, they have renamed **YogaNodeAPI** to **YogaNode**.
After renaming it in **SvgViewManager.java**, i am able to run my app.

 **Reference** : 

- https://github.com/facebook/yoga/releases/tag/1.5.0
- https://github.com/facebook/yoga/commit/1b3e9715495142b7500a02adf563243ad0d0b642

**Comment by pranavrajsinghchauhan** [comment]
we too facing the same issue, can you please accept the raised [PR](https://github.com/react-native-community/react-native-svg/pull/350).

Many thanks in advance for the same

**Comment by fabien-h** [comment]
Is it the issue that produces Execution failed for task `:react-native-svg:compileReleaseJavaWithJavac'.` ?

**Comment by ayunawani** [comment]
@fabien-h  yes, it is the same issue by` :react-native-svg:compileReleaseJavaWithJavac`

**Comment by farwayer** [comment]
React Native 0.45 just released so we need to merge PR and release new version quickly.

**Comment by Rohit221990** [comment]
I have tried to update the 'react-native-svg' package version and @8.0.9 works for me
