### ISSUE TITLE
node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:50: 错误: 找不到符号     private long mGestureStartTime = TouchEvent.UNSET;  ^   符号:   变量 UNSET   位置: 类 TouchEvent

### ISSUE THREAD

**Issue by hpu-spring87** [react-native-community/react-native-svg#342]
`node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:50: 错误: 找不到符号
    private long mGestureStartTime = TouchEvent.UNSET;
                                               ^
  符号:   变量 UNSET
  位置: 类 TouchEvent
`

**Comment by hpu-spring87** [comment]
when i use the least react-native, compile 'com.facebook.react:react-native:+'

I found the error:

Should remove all use  variable mGestureStartTime

like this : mGestureStartTime = TouchEvent.UNSET;

**Comment by hpu-spring87** [comment]
one commit cause the error,please fix the bug

**Comment by foyarash** [comment]
Just update to latest version of RN
