### ISSUE TITLE
[Android] Display View inside SVG

### ISSUE THREAD

**Issue by foyarash** [react-native-community/react-native-svg#345]
Hey,

I have an issue on Android for displaying a view nested in the Svg component.

I have a structure like this:

`
<Svg>
  <Path .../>
  <Circle .../>
  <View>
  // this view is displayed below the SVG
  </View>
</Svg>
`

This perfectly works on iOS, my View is shown inside the Svg component.

How can I fix this?

**Comment by marcioadr88** [comment]
I have the same issue on Android too. It works on iOS.

**Comment by ljunb** [comment]
Same issue!

**Comment by dustinsavery** [comment]
Pretty sure this is a fluke that it works in iOS. Putting a `View` inside an SVG component is not supported: https://github.com/react-native-community/react-native-svg#supported-elements

**Comment by msand** [comment]
Closing this for now. PRs welcome.

**Comment by msand** [comment]
@foyarash @marcioadr88 @ljunb @dustinsavery I have a PR with support for this now, can you test it and see if it behaves as you expect?
https://github.com/react-native-community/react-native-svg/pull/596
