### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by SteveIb** [react-native-community/react-native-svg#348]
Hi I got the following error when I build my app.

Yesterday it was working fine.. but today not.!
any clue?

react-native run-android
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-svg'.
      > Could not resolve all dependencies for configuration ':react-native-svg:_debugPublishCopy'.
         > Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
           Required by:
               AppName:react-native-svg:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.568 secs

**Comment by naelbw** [comment]
Same problem here

**Comment by arunkumarrmrj** [comment]
"com.atlassian.mobile.video" is not avaible on maven right now. To run your project you need to update it 

Update your react and react-native version to in your package.json file 

    "react": "16.0.0-alpha.3",
    "react-native": "0.43.1",

Then remove `node_modules` and do a `npm install` again

Let me know if it works for you

**Comment by SteveIb** [comment]
I updated react native 2 days ago.. and everything was fine. Thanks.
I didn't need to reinstall the svg again.
