### ISSUE TITLE
rn-v0.46.0 support

### ISSUE THREAD

**Issue by pranavrajsinghchauhan** [react-native-community/react-native-svg#360]
In upcoming rn-v0.46.0 the path to react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass to now changed to react-native/Libraries/Renderer/shims/createReactNativeComponentClass or Node Module ReactNativeFiber

In most of react-native-svg source we are referring to the same due to which it is throwing error. Can you please provide support for upcoming rn-v0.46.0

**Comment by crazypixel** [comment]
still not working with the latest react native

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
It is not just with `Rect.js`
`createReactNativeComponentClass` error is thrown in all files of `elements` folder of react-native-svg


Replace the `createReactNativeComponentClass` import statement to 
`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js';`

**Comment by magicismight** [comment]
Plz update to 5.3.x

**Comment by SupriyaKalghatgi** [comment]
@magicismight I am not having react-native-svg in my package.json

This is from the dependencies of Rn and other packages.

**Comment by aaronbuchanan** [comment]
upgrading to `5.4.1` worked for me
