### ISSUE TITLE
Remove react-native from dependencies

### ISSUE THREAD

**Issue by farwayer** [react-native-community/react-native-svg#361]
I think it was added to package.json in latest release (5.2.0) by mistake.

**Comment by wschurman** [comment]
Removing `node_modules` folder and re-running `yarn` or `npm install` fixed this for me.

**Comment by NielsLindberg** [comment]
Yup, was destroying my build :p, since i had ^5.1.8 which then went to 5.2.0 which then installed RN 0.45.1 instead of 0.44.3 breaking my app.

**Comment by farwayer** [comment]
@NielsLindberg keep in mind 5.2.0 version is for react-native >= 0.45 only

**Comment by NielsLindberg** [comment]
@farwayer yeah i guess the problem is that I was using ^ prefix on my packages and since RN makes major upgrades in 0.xx, it updates with breaking changes... Changing my prefixes to ~ solved my issue.

**Comment by rmevans9** [comment]
Same here - was killing my build because this package updated and ended up with react-native in node_modules within react-native-svg which made haste a very very unhappy camper. Downgraded to 5.1.8 and the problem went away.
