### ISSUE TITLE
Text path rendering bug in react-native-svg

### ISSUE THREAD

**Issue by msand** [react-native-community/react-native-svg#362]
Minimal reproduction of text path rendering bug in react-native-svg: https://github.com/msand/RNSvgTextBug

Renders correctly in web / next.js, the text is on top of the path referenced in textpath

Renders incorrectly in native, text is below path (at least android, haven't tried ios)

To test android:

`react-native run-android`

To test web:

`npm run dev`

**Comment by msand** [comment]
![image](https://user-images.githubusercontent.com/1131362/27012951-efe3a9ae-4ee2-11e7-8ab2-a70521f47183.png)

**Comment by msand** [comment]
![image](https://user-images.githubusercontent.com/1131362/27015801-492b570e-4f20-11e7-9884-1e5dad492b8d.png)

**Comment by ssssssssssss** [comment]
Try to use my pull request.

**Comment by msand** [comment]
@ssssssssssss Actually, my fork is based on your fork for gradientTransforms, I've made them work in java already, still some work in obj-c. It also had some of the code from your text fork, but that seems to have caused the moving in y direction of the text in the toap01.svg example, and did nothing to the textpath around the circle, it is still inside the path when it should be outside.

At least, taking the extractText logic from the master branch / 5.1.8 version; moves the text on native closer to where it should be in the toap example. But it is still a bit off, compared to the reference from rendering the web version on chrome.

![image](https://user-images.githubusercontent.com/1131362/27077165-da9c9e7e-5037-11e7-969f-5b7d130c5bff.png)

**Comment by msand** [comment]
Also, it seems the the dx and dy values translate relative to the viewport instead of relative to the textpath.

**Comment by ssssssssssss** [comment]
@msand I see. I just fixed my use case and doesn't test textpath yet. Thanks for the tip.

**Comment by msand** [comment]
![image](https://user-images.githubusercontent.com/1131362/27142071-ae39b726-5132-11e7-9599-b16c46461946.png)

**Comment by msand** [comment]
I've added the rest of the examples from https://www.w3.org/TR/SVG11/text.html now as well, such that there is more to test with.

**Comment by msand** [comment]
I wonder, why aren't the android.graphics.Canvas.drawText(char[] text, int index, int count, float x, float y, Paint paint) and android.graphics.Canvas.drawTextOnPath(char[] text, int index, int count, Path path, float hOffset, float vOffset, Paint paint) methods utilized?

https://developer.android.com/reference/android/graphics/Canvas.html#drawText(char%5B%5D,%20int,%20int,%20float,%20float,%20android.graphics.Paint)

https://developer.android.com/reference/android/graphics/Canvas.html#drawTextOnPath(char%5B%5D,%20int,%20int,%20android.graphics.Path,%20float,%20float,%20android.graphics.Paint)

**Comment by msand** [comment]
And how the come svg acid test compliant https://github.com/BigBadaboom/androidsvg/ isn't used?

**Comment by msand** [comment]
I've just pushed a new branch, fixing most of my issues and most of the conformance with the examples from the spec page.
https://github.com/msand/react-native-svg/tree/TextOnAPathLayoutRulesConformance
