### ISSUE TITLE
ios build fails: library not found for -lRNSVG-tvOS

### ISSUE THREAD

**Issue by whiskeyseven** [react-native-community/react-native-svg#366]
Build is failing for ios only, configuration seems to work fine on android.

There seems to be a failed ref to RNSVG-tvOS.

React Native v 0.45.1

My installation steps were:
npm install react-native-svg --save
react-native link
react-native run-ios

react-native link output looked successful. when i re-run, the output is:
```
rnpm-install info Android module react-native-svg is already linked 
rnpm-install info iOS module react-native-svg is already linked 
```

build fails mid-way, result is:
```
ld: library not found for -lRNSVG-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by listatt** [comment]
I have the same issue! After the error "linker is failed" I have the error ":CFBundleIdentifier", Does Not Exist. But Android works fine

**Comment by vccabral** [comment]
I just received this error. I was re-linking my app this morning from a fresh install. It is possible this was introduced in the past couple of days.

**Comment by whiskeyseven** [comment]
If it helps anyone, I was able to get the build to work by removing the reference to RNSVG-tvOS, found in the last line of the PBXBuildFile section of my project.pbxproj file (ios/<projectname>/<projectname>.xcodeproj/project.pbxproj)

Once I removed that line, the build worked as normal.

Not the ideal fix, but a workaround if anyone is blocked by this issue.

**Comment by listatt** [comment]
Downgrade my react-native app and react-native-svg works for me

**Comment by yspychala** [comment]
I also removed the reference to RNSVG-tvOS in the project.pbxproj and it worked (react-native@0.45.1), thanks @whiskeyseven!

**Comment by mcavaliere** [comment]
I tried @whiskeyseven's approach, but for me it didn't work until I removed all references to libRNSVG in the project.pbxproj file. That got the build to succeed.

**Comment by wung-s** [comment]
Tried @whiskeyseven's solution and while the build was successful, I ended up with this error   `ReactNative: 0.44.3`
I tried the suggested solution that comes with the error message, but that has helped. 

![screen shot 2017-06-25 at 9 49 37 pm](https://user-images.githubusercontent.com/5159585/27517829-47ffa7e2-59f0-11e7-8a33-ea9c62b78896.png)

**Comment by wung-s** [comment]
Ah ! Never mind, I got it working finally. Turns out I had installed mismatching version of `react-native`, `react` and `react-native-svg`    

I've got the following  
`"react-native-svg": "^5.1.8"`  
`"react": "16.0.0-alpha.6",`  
`"react-native": "0.44.3",`  
and it's all good now

**Comment by AlanFoster** [comment]
Confirming that the above approach worked as expected

There's further details on the react-native-svg [readme](https://github.com/react-native-community/react-native-svg#notice)

> - react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
> - react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
> - react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
> - react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >= 15.4.0
> - react-native-svg >= 4.5.0 only supports react-native >= 0.40.0 and react >= 15.4.0
> - react-native-svg >= 5.1.8 only supports react-native >= 0.44.0 and react == 16.0.0-alpha.6
> - react-native-svg >= 5.2.0 only supports react-native >= 0.45.0 and react == 16.0.0-alpha.12
> - react-native-svg >= 5.3.0 only supports react-native >= 0.46.0 and react == 16.0.0-alpha.12

**Comment by magicismight** [comment]
duplicated with: #387

**Comment by msand** [comment]
This is caused by a bug in react-native link, fix will be merged soon: https://github.com/facebook/react-native/issues/13783
