### ISSUE TITLE
Android: Can't nest Svg in Text

### ISSUE THREAD

**Issue by redpandatronicsuk** [react-native-community/react-native-svg#369]
On iOS this works fine, but nesting Svg inside Text, e.g:
```
<Text>
  Foo <Svg>...</Svg> bar
</Text>
```
Gives red screen on Android:
<img width="308" alt="screen shot 2017-06-15 at 13 35 31" src="https://user-images.githubusercontent.com/8609582/27181447-8cf4c2e8-51cf-11e7-94bc-ebaf18a884ba.png">

**Comment by ronal2do** [comment]
+ 1

**Comment by oriharel** [comment]
I was actually trying the opposite on Android, <Svg><Text/></Svg> - also doesn't work...
