### ISSUE TITLE
No component found for view with name “ RNSVGViewBox ”

### ISSUE THREAD

**Issue by haifaGh** [react-native-community/react-native-svg#371]
i just followed the documentation and installed victory native (to be able to generate charts ) following this link https://github.com/FormidableLabs/victory-native

I also installed react-native-svg and linked it.

I keep getting this error although i'm following this https://formidable.com/open-source/victory/docs/native and i just started by the first example. According to the documentation
<img width="747" alt="screen shot 2017-06-16 at 01 38 21" src="https://user-images.githubusercontent.com/15948361/27207422-a2f123ae-5236-11e7-8842-84e864b6b5db.png">
and since i'm using react native 0.42.0 and react 15.4.2 so i installed react-native-svg 4.5.0 but it's not working and i get this
<img width="369" alt="screen shot 2017-06-16 at 01 13 37" src="https://user-images.githubusercontent.com/15948361/27207436-ba0a4b4c-5236-11e7-88fe-6244a2490ad4.png">
I tried to uninstall it and unlink it and i changed to the newer version but still getting the same error.

Maybe this is not a react-native-svg issue and it's a victory-native issue .. So can you please help me fix this issue ... thanks :)

**Comment by jinxac** [comment]
Can you clean the project and try building it again? I was facing same issue when i just linked and reloaded the code from my device. After building again it works fine.

**Comment by Elijen** [comment]
Having the same problem while using `react-native-svg` in Expo.io via `react-native-svg-uri`

**Comment by adamski** [comment]
I had the issue due to two installation of `react-native-svg`, one in my package.json and an older version as part of `react-native-svg-uri`

**Comment by tastycode** [comment]
Getting this with `react-native-svg` v5.3.0 and react 16.0.0-alpha.6 with react-native 0.44 

On inspecting the error in xcode, i can see that `_componentDataByName` includes other `RNSVG*` namespaced objects. It just happens to be missing the object for `RNSVGViewBox`

![image](https://user-images.githubusercontent.com/809953/28988861-d4052bea-7926-11e7-95ba-609704c3f8a9.png)
![image](https://user-images.githubusercontent.com/809953/28988867-dac993a8-7926-11e7-9e39-dcc6b82a30c4.png)

Following up to where `_componentDataByName` gets called

![image](https://user-images.githubusercontent.com/809953/28988898-07b307fa-7927-11e7-99a2-c54c5b208e08.png)

```
(lldb) po _bridge.moduleClasses
<__NSArrayI 0x7fcf62535160>(
RCTWebSocketExecutor,
RCTStatusBarManager,
RCTSourceCode,
RCTAlertManager,
RCTExceptionsManager,
RCTAsyncLocalStorage,
RCTViewManager,
RCTProgressViewManager,
RCTSwitchManager,
RCTActivityIndicatorViewManager,
RCTDatePickerManager,
RCTScrollContentViewManager,
RCTPerfMonitor,
RCTScrollViewManager,
RCTTabBarManager,
JSCSamplingProfiler,
RCTAccessibilityManager,
RCTDevLoadingView,
RCTTiming,
RCTAppState,
RCTJSCExecutor,
RCTDevSettings,
RCTDevMenu,
RCTSliderManager,
RCTClipboard,
RCTNavItemManager,
RCTPlatform,
RCTKeyboardObserver,
RCTI18nManager,
RCTTabBarItemManager,
RCTWebViewManager,
RCTSegmentedControlManager,
RCTPickerManager,
RCTRefreshControlManager,
RCTRedBox,
RCTEventDispatcher,
RCTModalHostViewManager,
RCTUIManager,
RCTNavigatorManager,
RCTDeviceInfo,
RNSVGNodeManager,
RNSVGRenderableManager,
RNSVGTextManager,
RNSVGCircleManager,
RNSVGLinearGradientManager,
RNSVGRectManager,
RNSVGClipPathManager,
RNSVGSvgViewManager,
RNSVGPathManager,
RNSVGRadialGradientManager,
RNSVGImageManager,
RNSVGLineManager,
RNSVGEllipseManager,
RNSVGSymbolManager,
RNSVGGroupManager,
RNSVGTextPathManager,
RNSVGTSpanManager,
RNSVGUseManager,
RNSVGDefsManager,
RCTNativeAnimatedModule,
RCTActionSheetManager,
RCTLocationObserver,
RCTImageStoreManager,
RCTImageViewManager,
RCTGIFImageDecoder,
RCTImageLoader,
RCTImageEditingManager,
RCTLocalAssetImageLoader,
RCTLinkingManager,
RCTFileRequestHandler,
RCTDataRequestHandler,
RCTNetInfo,
RCTNetworking,
RCTHTTPRequestHandler,
RCTSettingsManager,
RCTTextManager,
RCTRawTextManager,
RCTTextFieldManager,
RCTTextViewManager,
RCTVibration,
RCTWebSocketModule,
RCTFBSDKShareDialog,
RCTFBSDKAppEvents,
RCTFBSDKGraphRequestManager,
RCTFBSDKAccessToken,
RCTFBSDKMessageDialog,
RCTFBSDKGameRequestDialog,
RCTFBSDKInitializer,
RCTFBSDKLoginButtonManager,
RCTFBSDKAppInviteDialog,
RCTFBSDKLikeControlManager,
RCTFBSDKShareButtonManager,
RCTFBSDKShareAPI,
RCTFBSDKLoginManager,
RCTFBSDKSendButtonManager,
ReactNativeConfig,
RNCookieManagerIOS,
RNDeviceInfo,
RNGooglePlaces
)


(lldb) 
```

From here, i don't know where else to look. I've removed `node_modules` `watchman watch-del-all` and restarted the packager with `npm start -- --reset-cache`. I've unlinked, relinked, cleaned `ios/build` and re-`run-ios`'d  many times and get the same error back every time. I've also verified the RNSVG* libraries are in the 3 appropriate places (search paths, link binary with libraries, and the presence of `RNSVG.xcodeproj` in `/Libraries`)

**Comment by tastycode** [comment]
It would be helpful to know how to continue to debug this, i'm pretty tired of fiddling with my dependencies/versions and would actually like to fully understand this error so i can plow through it if i encounter it.

**Comment by iLeonelPerea** [comment]
@tastycode did you fixed it? because i have the same problema..

**Comment by tastycode** [comment]
@iLeonelPerea without input from the maintainers on how to continue debugging, i had to abandon the library and use `react-native-svg-image` for now

**Comment by msand** [comment]
Try this:
npm install react-native-svg@https://github.com/msand/react-native-svg.git#fee0d7d

**Comment by msand** [comment]
@tastycode @iLeonelPerea my 5.1.7.1 version contains my latest fixes:
https://github.com/msand/react-native-svg/tree/5.1.7.1

Otherwise, try installing v5.1.7 of the original, as 5.1.8 is the first version which requires react 16+

But victory-native probably requires a bit more fixes still. Some of the issues are tracked here: https://github.com/react-native-community/react-native-svg/issues/377

**Comment by msand** [comment]
Try with the latest released version. Should be working as long as you only have a single react-native-svg in your dependency tree. Closing for now, reopen if you still have issues.

**Comment by wshenglong** [comment]
please try this:
`react-native link react-native-svg`
