### ISSUE TITLE
Flex

### ISSUE THREAD

**Issue by adrianboimvaser** [react-native-community/react-native-svg#383]
How can I get The ``<Svg/?`` element to use all the available space (or at least width) in the container ``<View/>``?

**Comment by msand** [comment]
You can check out https://github.com/msand/RNSvgTextBug/blob/master/src/index.android.js#L18-L28 to see how to get full width of the viewport, and adjust the relative height of elements. Essentially you need to measure the number of pixels available, set the width and height of the root svg element in px, and use the viewBox and preserveAspectRatio attributes to scale the content coordinate-system accordingly.

**Comment by msand** [comment]
https://www.w3.org/TR/SVG/images/coords/PreserveAspectRatio.svg

**Comment by awreese** [comment]
@msand Can you update your answer as it seems you've factored your android code into a generic native.js file and the line numbers no longer make sense as a reference?  Thanks.

**Comment by msand** [comment]
@awreese Sure. (btw, the last commit in the repository before the comment you refer to is this: https://github.com/msand/RNSvgTextBug/tree/3b47667fbca150857297880cb7ae27728de5fc0f which you could've used to find the referenced code, or just look inside the native.js file of the current commit and read the code)

Current commit:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/native.js#L23
Here I get the width of the viewport window.
`const { width, height } = Dimensions.get("window");`

Here I pass the the width on:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/native.js#L34-L40
```
        <All
          View={View}
          width={width}
          height={height}
          native={true}
          shadow={shadow}
        />
```

Which I then pass on here to all the example components:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/components/all.js

And then some examples of how to use it:
Full width square viewbox
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/components/anchor.js

Full width scaled height:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/components/request.js

Full width, scaled height, translated viewBox:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/components/request2.js

Full size, without preserving aspect ratio (stretches if you change width or height):
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/src/components/ViewBox.js

For the spec of preserveAspectRatio and viewBox check here:
https://www.w3.org/TR/SVG11/coords.html#PreserveAspectRatioAttribute
https://www.w3.org/TR/SVG11/coords.html#ViewBoxAttribute

Examples
https://www.w3.org/TR/SVG11/images/coords/ViewBox.svg
https://www.w3.org/TR/SVG11/images/coords/PreserveAspectRatio.svg

Btw, I use the same "All" component in the web/next.js version:
https://github.com/msand/RNSvgTextBug/blob/5a9f555db69b3bd22ead882479bce08653bb6415/pages/index.js
```
  <All
    View={props => <div {...props} />}
    width={980}
    native={false}
    shadow="/static/shadow-min.png"
  />;
```

**Comment by scriptfans** [comment]
@msand Thanks very much.
