### ISSUE TITLE
ld: library not found for -lRNSVG-tvOS

### ISSUE THREAD

**Issue by 12343954** [react-native-community/react-native-svg#387]
![image](https://user-images.githubusercontent.com/1804003/27576039-3c38876c-5b4e-11e7-8c3c-dc7e5dfc2e59.png)
![image](https://user-images.githubusercontent.com/1804003/27576120-92b6f830-5b4e-11e7-81da-c41500d673b3.png)
![image](https://user-images.githubusercontent.com/1804003/27576152-ac546e44-5b4e-11e7-92f9-640240c950c0.png)

**Comment by 12343954** [comment]
solved！ 
remove “libRNSVG-tvOS.a”

**Comment by cjbutcher** [comment]
Thank you I needed this 🙏

**Comment by Katherine-Marschner** [comment]
I have been fighting the same problem as #279.   I don't understand the solution.  am I supposed to take all lines referencing libRNSVG-tvOS.a in my project.pbxproj file.  I am am fairly new at mobile apps, so I need more specific solution.

**Comment by jeantimex** [comment]
Thank you @12343954!!

**Comment by magicismight** [comment]
Fix will land on 5.3.1

**Comment by MatBusch** [comment]
Legend!  @12343954!! Deleting it worked perfectly.

**Comment by brunolemos** [comment]
Waiting for npm release about this one as well! :)

**Comment by ggepenyan** [comment]
Hi everyone, @12343954 sorry, but from which file I have to remove libRNSVG-tvOS.a ???
@magicismight we have to do it manually? There is no another solution?
I don't know from where remove that file, Help please anybody

**Comment by rodrigoreis22** [comment]
@ggepenyan remove from your XCode project, using the XCode UI.. select the lib and then click on the (-) sign.

**Comment by msand** [comment]
This is caused by a bug in react-native link, fix will be merged soon: https://github.com/facebook/react-native/issues/13783

**Comment by tetogomez** [comment]
Thanks @12343954 I deleted libRNSVG-tvOS.a as you said and it worked for me!! awesome man

**Comment by xe4me** [comment]
https://stackoverflow.com/questions/37658957/no-component-found-for-view-with-name-artshape 
Solved my issue
