### ISSUE TITLE
Apple Match-O Linker Error when building on iOS 

### ISSUE THREAD

**Issue by cecampos** [react-native-community/react-native-svg#388]
After running the followings commands:
- npm install
- react-native link react-native-svg
The xcode projects throws an "Apple Match-O Linker Error" error message.
My package.json uses:
- react-native: "0.45.1"
- react-native-svg: "5.2.0"
- react: "16.0.0-alpha12"

The problem appears when using react-native link for the react-native-svg folder, I can build when I unlink that very same folder.
Any help would be appreciated.

**Comment by alexwasner** [comment]
In Link Binary with Library, try removing the -tvOS.a file. Thats what I did and got it to build

**Comment by ansierras** [comment]
I am having this same issue. @alexwasner can you be a little bit more specific on your solution? I don't understand... THX!

**Comment by OssamaZ** [comment]
@ansierras in the build phases of your project, open **Link Binary With Libraries**, select **libRNSVG-tvOS.a** and click **-** to remove it.

**Comment by ansierras** [comment]
Perfect. This solved the problem for me! :D

**Comment by magicismight** [comment]
duplicated with: #387

**Comment by skjangid** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBSDKHashtag", referenced from:
      objc-class-ref in libRCTFBSDK.a(RCTConvert+FBSDKSharingContent.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


I don't have -tvOS.a file in the binary list, so how i can resolve this error ?

**Comment by bhaskartalluri999** [comment]
while building react-native project in xcode following errors are occured,
clang: error: unknown argument: '-no_deduplicate' 

clang: error: no such file or directory: '/Users/pradeepkrish/Library/Developer/Xcode/DerivedData/projectname-bcvkbiqlzwpsqadbqmrlcqgqzvzz/Build/Intermediates.noindex/projectname.build/Debug-iphonesimulator/InnovaZones.build/Objects-normal/x86_64/InnovaZones_lto.o'

 clang: error: no such file or directory: '2' 
clang: error: no such file or directory: '/Users/pradeepkrish/Library/Developer/Xcode/DerivedData/projectname-bcvkbiqlzwpsqadbqmrlcqgqzvzz/Build/Intermediates.noindex/projectname.build/Debug-iphonesimulator/projectname.build/Objects-normal/x86_64/projectname_dependency_info.dat'

how can i solve this.Any suggestion?

**Comment by fazeelzama20** [comment]
@OssamaZ I am not having any libRNSVG-tvOS.a in the link library. I am having libRNSVG.a only. Any help?

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/questions/39545880/apple-mach-o-linker-ditto-error-xcode-8
