### ISSUE TITLE
Semicircle

### ISSUE THREAD

**Issue by EstebanBP** [react-native-community/react-native-svg#390]
Is there any possibility to create shapes like this one?

![image](https://user-images.githubusercontent.com/23704234/27948380-ee29aae8-62f9-11e7-878a-091dab8197c2.png)

kind of semicircle line

Thanks in advance

**Comment by AlbertBrand** [comment]
This is done via a Path.

Op 7 jul. 2017 09:53 schreef "EstebanBP" <notifications@github.com>:
