### ISSUE TITLE
Duplicate module name 

### ISSUE THREAD

**Issue by farid-ouachrar** [react-native-community/react-native-svg#392]
Hello guys, 
thanks for this great library, I seem to have a problem that is giving me a headache now, I've seen an issue opened similar to this one but the solution given wasn't helping. the problem basically is that the dependencies are conflicting and when you get rid of one by removing it from the package.json , another one or more pops up 

![image](https://user-images.githubusercontent.com/20015003/27979818-c1fdcb3a-6370-11e7-9cea-8de45b9bfa85.png)

**Comment by magicismight** [comment]
Fix in 5.3.0
