### ISSUE TITLE
Image transform scale property

### ISSUE THREAD

**Issue by dk0r** [react-native-community/react-native-svg#394]
Setting the transform scale property in react-native-svg@5.2.0 does not appear to have any effect.

`           Note that the following **Image** component is imported from react-native-svg (**not** react):

          <Image
              x="20"
              y="20"
              width="50%"
              height="50%"
              href={require('./image.png')}
              transform="scale(0.5, 0.5)"          
          />

**Comment by 0mkara** [comment]
Did you try
`transform={{scale:'0.5, 0.5'}}`

**Comment by awreese** [comment]
Agreed, testing with drawing circles of radius 10 at random positions with transform matrix [1,0,0,1,rand.x,rand.y] yields circles of radius 10 but at origin (0,0), and using transform matrix [4,0,0,4,rand.x,rand.y] yields exactly the same, circles of radius 10 at origin.  Neither matrix translated or scaled the graphics objects.  Shame really.  I dug through the code to see if I could pass it through to the underlying device libs, but I'm new to RN and have never coded for Android or iOS before a month ago.

**Comment by msand** [comment]
Try my fork/pull request: https://github.com/react-native-community/react-native-svg/pull/430

**Comment by msand** [comment]
@dk0r @0mkara @awreese I've now ported almost all the fixes from android to ios here: #430
npm i -s react-native-svg@https://github.com/msand/react-native-svg.git#13d5157

**Comment by msand** [comment]
New version published with support for this.
