### ISSUE TITLE
"Maximum call stack size exceeded" when "react-native link"

### ISSUE THREAD

**Issue by theinvensi** [react-native-community/react-native-svg#396]
Hello,

Somebody can help me, please?

![image](https://user-images.githubusercontent.com/4583856/28049662-bd19492a-65c6-11e7-800c-881f9c95da59.png)

My current environment...

![image](https://user-images.githubusercontent.com/4583856/28049749-5477bde2-65c7-11e7-9978-5773294cdf4e.png)

![image](https://user-images.githubusercontent.com/4583856/28049769-7c7a9d32-65c7-11e7-8370-47a0196dc8be.png)

![image](https://user-images.githubusercontent.com/4583856/28049763-6b59a5a2-65c7-11e7-99d7-ea0bcab56151.png)

Thanks!

**Comment by theinvensi** [comment]
Sorry, I forget the image.... here is...
![image](https://user-images.githubusercontent.com/4583856/28049662-bd19492a-65c6-11e7-800c-881f9c95da59.png)

**Comment by theinvensi** [comment]
My current environment...

![image](https://user-images.githubusercontent.com/4583856/28049749-5477bde2-65c7-11e7-9978-5773294cdf4e.png)

![image](https://user-images.githubusercontent.com/4583856/28049758-5c1243ce-65c7-11e7-9418-77609fc64868.png)

![image](https://user-images.githubusercontent.com/4583856/28049763-6b59a5a2-65c7-11e7-99d7-ea0bcab56151.png)

**Comment by magicismight** [comment]
Unlink and retry?
Or just link it manually.

**Comment by magicismight** [comment]
I'm closing this now.
This should be a  bug for `react-native link` tool, not this library.
Thanks for reporting this anyway

**Comment by jaxatto** [comment]
@theinvensi Did you find a solution? I'm having the same issue right now.
