### ISSUE TITLE
Touch through transparent areas of svg

### ISSUE THREAD

**Issue by doomsower** [react-native-community/react-native-svg#399]
I'm trying to implement tutorial view which will focus user attention on certain elements, like on this screenshot:
![image](https://user-images.githubusercontent.com/12031673/28084061-2db50c82-6680-11e7-8a0b-448ba2a9c546.png)
This is fullscreen overlay `View` with absolute position and svg inside it. Other elements (text with description and dismiss button) should be placed inside this view above svg. Only touches inside the 'hole' should pass through to underlying views.
This is how my code looks like:
```jsx
<View style={styles.overlay} pointerEvents="box-none">
  <Svg width={width} height={height}>
    <Defs>
      <ClipPath id="clip">
        <G>
          <Rect width="100%" height="100%" />
          <Circle cx={this._cx} cy={this._cy} r={this._radius} />
        </G>
      </ClipPath>
    </Defs>
    <Rect
      onPress={() => console.log('Press')}
      width="100%"
      height="100%"
      fill="rgba(255, 0, 0, 0.5)"
      clipPath="url(#clip)"
      clipRule="evenodd"
    />
  </Svg>
</View>
```

`onPress` works as expected, logs to console when I press on red area and does nothing when I press inside the hole. The problem is that underlying view does not receive touch events.

I checked `react-native-svg` android sources and it seems that there is no easy way to fix this. `ViewGroup` that contains `SvgView` determines if view should receive touch event based its bounds, so `SvgView` will always consume touch event. 

Am I wrong? Any ideas on how this can be done?

**Comment by dk0r** [comment]
I'm also interested in this..

**Comment by nuttylord** [comment]
try messing around with pointerEvents. you might need to create multiple <SVG> elements wrapped in <View>'s

**Comment by msand** [comment]
Use the gesture responder system and the grant/responder termination request logic https://facebook.github.io/react-native/docs/gesture-responder-system.html
