### ISSUE TITLE
Error: Can't resolve Rect.js ( in react-native-svg ) 

### ISSUE THREAD

**Issue by ev1stensberg** [react-native-community/react-native-svg#401]
I'm getting watchman error when trying to use one of the modules. Running on Google Pixel XL remote. Any suggestions on why this is happening? Everything is properly set up!

**Comment by lionel95200x** [comment]
Same error @ev1stensberg Have you found a solution ?

**Comment by ev1stensberg** [comment]
I can try to debug it if its an pressing issue?

**Comment by lionel95200x** [comment]
Yes if you can

**Comment by dguillamot** [comment]
Also seeing this issue atm

**Comment by dguillamot** [comment]
It looks like it is from importing createReactNativeComponentClass

`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass';`

**Comment by dguillamot** [comment]
Ah, I believe it is an issue with react-native-svg-uri using older react-native-svg.

**Comment by mikearche** [comment]
Go to `node_modules/react-native-svg-uri/node_modules/react-native-svg/elements/Rect.js`

Edit line 3 to
`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass';`

I had to restart the packager afterwards and run
`npm start --reset-cache`

**Comment by SupriyaKalghatgi** [comment]
It is not just with `Rect.js`
`createReactNativeComponentClass` error is thrown in all files of `elements` folder of react-native-svg

**Comment by SupriyaKalghatgi** [comment]
Replace the `createReactNativeComponentClass` import statement to 
`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js';`

**Comment by magicismight** [comment]
```
npm ls react-native
npm ls react
npm ls react-native-svg
```

Make sure module versions are matched to [this table](https://github.com/react-native-community/react-native-svg#notice).
If not, remove the `^` before the version name in package.json and install.

Like this:
```
	"dependencies": {
		"react": "^16.0.0-alpha.12",
		"react-native": "^0.46.4",
		"react-native-svg": "^5.3.0"
	},
```

====> 
```
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.4",
		"react-native-svg": "5.3.0"
	},
```

**Comment by developer239** [comment]
I created pull request https://github.com/react-native-community/react-native-svg/pull/411 this should work @SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
@magicismight I am not having `react-native-svg` in my `package.json`

This is from the dependencies of Rn and other packages.

**Comment by j2l** [comment]
I have the same issue on Win10 with both native-base and antd-mobile-samples:

![screenshot_2017-07-24-14-21-58](https://user-images.githubusercontent.com/65325/28523185-7c4019aa-707b-11e7-8de2-fe6b14cc3b5d.png)

createReactNativeComponentClass is not foundable in node_modules, global?

**Comment by tuneZola** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
@j2l @tuneZola I dont find `native-base` in the error screenshot

If you exclude `native-base` from your `node_modules` and run it again, that might clear your misconception.

**Comment by developer239** [comment]
@SupriyaKalghatgi I created pull request it still does not work. Npm somehow made it. Yarn is returning red screen.

**Comment by SupriyaKalghatgi** [comment]
@developer239 I have not gone through your PR actually

**Comment by j2l** [comment]
update with native-base (using the same component as antd-mobile):
![screenshot_2017-07-25-15-31-27](https://user-images.githubusercontent.com/65325/28574517-83664e88-714e-11e7-9361-e91924455517.png)

**Comment by tuneZola** [comment]
@SupriyaKalghatgi I am not using `native-base`, I was trying your `createReactNativeComponentClass` change and that didn't work for me.

**Comment by SupriyaKalghatgi** [comment]
@tuneZola @j2l From the above [comment](https://github.com/react-native-community/react-native-svg/issues/401#issuecomment-316303616), did you find `createReactNativeComponentClass` in path `react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js`?

**Comment by j2l** [comment]
@magicismight Here's my setup:
WIN10
Expo XDE 2.19.3 (updated today)
Android 5.1.1 (real device, not emulator)
Expo 1.18.4 (updated today)

At first I had this:
```
npm ls react react-native react-native-svg
NativebaseKitchenSink@2.2.1 E:\NativeBase-KitchenSink-CRNA
+-- expo@18.0.9
| `-- react-native-svg@5.2.0
+-- react@16.0.0-alpha.12
+-- react-native@0.46.3
+-- react-native-scripts@0.0.19
| `-- xdl@34.0.0
|   `-- react@15.6.1
`-- react-native-svg@5.3.1  extraneous

npm ERR! extraneous: react-native-svg@5.3.1 E:\NativeBase-KitchenSink-CRNA\node_modules\react-native-svg
```
Reading this, I understand that RNS is hardcoded in expo 18 package.json! So I changed :
`"react-native-svg": "https://github.com/expo/react-native-svg/archive/5.2.0-exp.0.tar.gz",`
to
`"react-native-svg": "https://github.com/react-native-community/react-native-svg/archive/v5.3.2.tar.gz",` 
`npm i`
I noted that some npm update don't go through, I prefer to uninstall and install again:
```
npm un react-native
```
Changed Native-Base package json to:
`    "react-native": "0.46.4",`
`npm i  react-native@0.46.4`

Now have:
```
+-- expo@18.0.9
| `-- react-native-svg@5.3.1
+-- react@16.0.0-alpha.12
+-- react-native@0.46.4
+-- react-native-scripts@0.0.19
| `-- xdl@34.0.0
|   `-- react@15.6.1
`-- react-native-svg@5.3.1  extraneous
npm ERR! extraneous: react-native-svg@5.3.1 E:\NativeBase-KitchenSink-CRNA\node_modules\react-native-svg
```
It is WORKING now!
No need to change `import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass';` for me (but it doesn't hurt).



Why ERR extraneous?
Note that 5.3.2 is not taken in account, why?

I'm happy I've learned a few things today :)

**Comment by markentingh** [comment]
This is also happening to me...

**Comment by luco** [comment]
I had to put `import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass.js';` instead of import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shims/createReactNativeComponentClass.js';

**Comment by agungjk** [comment]
this is working for me, as same as @luco say #431
