### ISSUE TITLE
Build failed in RN 0.46.3 (iOS)

### ISSUE THREAD

**Issue by sajjadrad** [react-native-community/react-native-svg#403]
I'm using a package that using react-native-svg. iOS build fails after linking react-native-svg and build success if unlink it. 

Build error:
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

[More info ](https://github.com/capitalone/react-native-pathjs-charts/issues/169)

**Comment by magicismight** [comment]
duplicated with: #387

**Comment by magicismight** [comment]
Fix will be land on 5.3.1
