### ISSUE TITLE
how to  make html svg To this Svg

### ISSUE THREAD

**Issue by doudoukang** [react-native-community/react-native-svg#410]
transform="matrix(1 0 0 -1 0 0)"

how to  make html svg To this Svg

**Comment by msand** [comment]
Try using my fork from here: https://github.com/msand/react-native-svg/tree/5.3.0-conformance
so something like:
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#5.3.0-conformance
Or a specific commit:
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#3825bbd

**Comment by msand** [comment]
This syntax works now. Closing.
