### ISSUE TITLE
crash after setting react-native-svg

### ISSUE THREAD

**Issue by hasancanozkan** [react-native-community/react-native-svg#412]
Hi All, 
after building my new app with SVG, I am getting this error, I checked other similar issues and tried them to solve my issue but they didnt work.  I need a hand on this one, any ideas why?  

:react-native-svg:compileReleaseJavaWithJavac
:react-native-svg:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\----\----\sensor-app\sensorProject\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\SvgPackage.java:23: **error: SvgPackage is not abstract and does not override abstract method createJSModules() in ReactPackage**
public class SvgPackage implements ReactPackage {
       ^
1 error
:react-native-svg:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.993 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

btw I tried both automatic and manual linking.

**Comment by WynnLin** [comment]
same issues for me just minutes ago

**Comment by JSafaiyeh** [comment]
+1 got the same issue upgrading

**Comment by huanghaiyang** [comment]
+1

**Comment by hasancanozkan** [comment]
i think enniel made a good point on #414 , i tried and it works,
