### ISSUE TITLE
image transforms not working

### ISSUE THREAD

**Issue by redpandatronicsuk** [react-native-community/react-native-svg#417]
Translations on images don't work as expected. I have an image inside a group that is being transformed. For all elements in the group the transform works as expected, i.e. they translate, but the image is just getting cropped instead: 
![rnsvg-transform-bug](https://user-images.githubusercontent.com/8609582/28789487-8d93763c-761d-11e7-9f71-eee76c241562.gif)

Transforms also don't seem to work when directly applied to image. For instance
```javascript
<Svg 
     width={this.props.scale * 704.2}
     height={this.props.scale * 692.8} 
     x="0px" y="0px" viewBox="0 0 704.2 692.8"
     style={{backgroundColor: 'grey'}}>
	<Image x="0" y="0" width="200" height="333" href={HEAD_IMG}/>
</Svg>
```
doesn't show the image at all:
<img width="80" alt="screen shot 2017-07-31 at 18 41 37" src="https://user-images.githubusercontent.com/8609582/28790171-edce68fc-761f-11e7-8ae2-c072194f3ddb.png">
```javascript
<Svg 
     width={this.props.scale * 704.2}
     height={this.props.scale * 692.8} 
     x="0px" y="0px" viewBox="0 0 704.2 692.8"
     style={{backgroundColor: 'grey'}}>
	<Image x="100" y="100" width="200" height="333" href={HEAD_IMG}/>
      </Svg>
```
gives: 
<img width="85" alt="screen shot 2017-07-31 at 18 41 07" src="https://user-images.githubusercontent.com/8609582/28790236-2bfd0cfa-7620-11e7-90e5-bc1123ca6e08.png">
```javascript
<Svg 
     width={this.props.scale * 704.2}
     height={this.props.scale * 692.8} 
     x="0px" y="0px" viewBox="0 0 704.2 692.8"
     style={{backgroundColor: 'grey'}}>
	<Image x="0" y="0" translateX="100" translateY="100" width="200" height="333" href={HEAD_IMG}/>
      </Svg>
```
produces: 
<img width="81" alt="screen shot 2017-07-31 at 18 45 20" src="https://user-images.githubusercontent.com/8609582/28790301-71aaa668-7620-11e7-8fdc-3b4ebaa9ca33.png">
```javascript
<Svg 
     width={this.props.scale * 704.2}
     height={this.props.scale * 692.8} 
     x="0px" y="0px" viewBox="0 0 704.2 692.8"
     style={{backgroundColor: 'grey'}}>
	<Image x="100" y="100" width="300" height="433" href={HEAD_IMG}/>
      </Svg>
```
(adding 100 to width and height parameters too) produces:
<img width="80" alt="screen shot 2017-07-31 at 18 50 37" src="https://user-images.githubusercontent.com/8609582/28790511-53c0855e-7621-11e7-9dbb-4ed823c7361c.png">
 
By tweaking the height and width parameters, through trial and error, I managed to get the image into the correct position in the gif example above, but then when the group the image is in is transformed the image only gets cropped.

To reproduce the issue use the code above and any image with dimensions 200x333 should do.
RN: 0.46.4
RN-svg: 5.3.2
Same behaviour on iOS and Android.

**Comment by msand** [comment]
You could try using my fork: https://github.com/msand/react-native-svg/tree/5.3.0-conformance
I have a pull request in process here: https://github.com/react-native-community/react-native-svg/pull/406
To try it out you can:

1. (kill the React packager)
2. install the fork
3. rebuild your android/java bundle
4. start your packager

```
yarn add react-native-svg@https://github.com/msand/react-native-svg.git#5.3.0-conformance
cd android
gradlew build (or ./gradle build)
cd ..
react-native start
```

**Comment by redpandatronicsuk** [comment]
Thanks @msand ! When I try to translate the image by setting the x and y parameters, the image still gets cropped, but wrapping it in a group and transforming the group works. I hope your PR gets merged soon!

**Comment by msand** [comment]
@redpandatronicsuk There is now a new version and pull request, with some of the fixes from android ported to ios: https://github.com/react-native-community/react-native-svg/pull/430

**Comment by msand** [comment]
This should be working correctly now. Closing.
