### ISSUE TITLE
onPressOut only works on first element

### ISSUE THREAD

**Issue by yunda** [react-native-community/react-native-svg#418]
If more than one element uses onPressOut it only works on the first one. On the rest of them onPressOut fires immediately after onPressIn.

Let's take your HoverExample and repeat it 4 times like this:

```
<View>
    <HoverExample />
    <HoverExample />
    <HoverExample />
    <HoverExample />
 </View>
```
On the first one I would see it working, for the rest no.

I tried putting console.log in the handler:
```
toggle = () => {
    console.log(this.state.hover);
    this.setState({hover: !this.state.hover});
};
```
When I press and hold on the first star it would show:
```
false
```
And after pressing out 
```
true
```

For the others if I press and hold it would output:
```
false
true
```
And no visual effect.

**Comment by yunda** [comment]
Sharing my latest findings on this. Seems like the workaround could be setting hitSlop property to value which would cover the whole area with all touchable elements. In my case its:
```
const HITSLOP = {top: 100, left: 100, right: 400, bottom: 400};
```
The starting point is the first element on which pressIn pressOut works normally.

**Comment by msand** [comment]
Press handling has been improved, and there no code/replication here to test. Closing.
