### ISSUE TITLE
strokeDashArray percentages not working

### ISSUE THREAD

**Issue by entropitor** [react-native-community/react-native-svg#424]
When passing a percentage to strokeDashArray, the library crashes with a `JSON value '<null>' of type NSNull cannot be converted to NSNumber`

**Comment by msand** [comment]
Currently, when the extractStroke function is given a string in the strokeDasharray prop, it will split the string by (possibly white-space surrounded) commas, and maps the resulting sub-strings to numbers:
https://github.com/react-native-community/react-native-svg/blob/ba4c649ebce6333c34c1857b30b7abc27a85a235/lib/extract/extractStroke.js#L33

Thus any string with a percentage sign would become NaN, as you can test in the browser console by typing `+'1%';`

The code currently expects numbers, and percentages are not supported the way they are defined in the svg spec. The map to numbers should be removed and support for units and percentages relative to the diagonal of the viewport should be implemented.
https://www.w3.org/TR/SVG/painting.html#StrokeDasharrayProperty
https://developer.mozilla.org/en/docs/Web/SVG/Attribute/stroke-dasharray

And the split regex should be changed to allow for white-space separated lists:
Lists within SVG's XML attributes can be either comma-separated, with optional white space before or after the comma, or white space-separated.
comma-wsp  ::= (wsp+ ","? wsp*) | ("," wsp*)
wsp        ::= (#x20 | #x9 | #xD | #xA)
https://www.w3.org/TR/SVG/types.html#WSP

**Comment by msand** [comment]
Can you try this? I'll close for now.
