### ISSUE TITLE
Expo demo link doesn't work

### ISSUE THREAD

**Issue by esidegallery** [react-native-community/react-native-svg#429]
"No experience found at ...."

**Comment by ExNexu** [comment]
Doesn't load for me either.

**Comment by mike-marcacci** [comment]
The expo app says:

```
Error while loading: Experience "@rncommunity/react-native-svg-examples" for platform "ios" and release channel "default" was not published recently enough to be used on this client. The author will need to publish a new version.." (code 400)
```

**Comment by dustinsavery** [comment]
I have not seen this before. I will take a look

**Comment by mdkess** [comment]
I get an SDK error for this - demo uses 10.0, Expo uses 17.0

**Comment by msand** [comment]
Published https://github.com/peterlazar1993/react-native-svg-example
here: https://expo.io/@msand/svgexample
and updated readme.
