### ISSUE TITLE
right-to-left language support

### ISSUE THREAD

**Issue by TiraO** [react-native-community/react-native-svg#439]
Per https://github.com/capitalone/react-native-pathjs-charts/issues/181 it seems there is an issue with rendering right-to-left languages (at least on Android). Specifically in Persian, words are backwards and letters are not cursive-joined.

Here is an example that reproduces the issue:

```jsx
import Svg,{ G, Path, Text } from 'react-native-svg'
...
render(){
    let persianText = "الفبای فارسی‎‎";
    return (
      <View>
        <Svg width={200} height={200}><G><Text>{persianText}</Text></G></Svg>
      </View>
    )
}
```

**Comment by msand** [comment]
Proper text chunk handling and the Unicode BiDi algorithm is missing. 
http://unicode.org/reports/tr9/

The relevant attributes:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/writing-mode
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction
https://www.w3.org/TR/SVG2/text.html#DirectionProperty

The node icu-bidi package binds to the ICU (55.1) library in order to provide an implementation of the Unicode BiDi algorithm.
https://www.npmjs.com/package/icu-bidi

This possibly makes sense to implement in javascript, just reorder the characters such that it becomes only left-to-right text, and rearrange any char dependent attribute value lists to take this into consideration (x, y, dx, dy, rotate attributes). Otherwise:

Servo has an implementation in Rust:
https://github.com/servo/unicode-bidi
Java also has one:
https://docs.oracle.com/javase/7/docs/api/java/text/Bidi.html
And Apple, Windows etc. have ther own.

**Comment by hotmanhh** [comment]
i have this issue too

**Comment by msand** [comment]
@hotmanhh Would you be interested in attempting to implement it?

**Comment by hotmanhh** [comment]
Yes I would

**Comment by msand** [comment]
@hotmanhh I've done some initial work here: https://github.com/react-native-community/react-native-svg/pull/724
But have barely any insight into any right-to-left or top-to-bottom script and language systems. So I'm very much in need of assistance from native speakers/writers to get this further. What languages are you in need of? Persian/Farsi as well? Could you test and see if its good enough? And try to find the correct font feature settings to get the ligatures/cursive joins working as they should.

**Comment by msand** [comment]
https://docs.microsoft.com/en-us/typography/script-development/arabic
https://en.wikipedia.org/wiki/List_of_typographic_features
https://www.w3.org/TR/SVG2/text.html#DirectionProperty

**Comment by alirezarzna** [comment]
A workaround to fix this issue for Persian texts (probably Arabic texts too). 
use this tool:
[awebfont.ir/convert](http://awebfont.ir/convert/)

**Comment by matinzd** [comment]
Any update on this issue?! I've been searching a lot and I found lang scripts for arabic and persian texts.
I tried font features here but non worked! 
https://docs.microsoft.com/en-us/typography/script-development/arabic

**Comment by matinzd** [comment]
> A workaround to fix this issue for Persian texts (probably Arabic texts too).
> use this tool:
> [awebfont.ir/convert](http://awebfont.ir/convert/)
> 
> ![image](https://user-images.githubusercontent.com/38705618/58380027-00c77c80-7fc1-11e9-8526-57f275756fa6.png)

What about dynamic data?!

**Comment by BatDroid** [comment]
any one can tell what awebfont.ir/convert is exactly doing to the passed text. if we find out then we can find a util for it to do it for us to use it for dynamic data as well as static ones

**Comment by matinzd** [comment]
> any one can tell what awebfont.ir/convert is exactly doing to the passed text. if we find out then we can find a util for it to do it for us to use it for dynamic data as well as static ones

Exactly what I am looking for!!!

**Comment by msand** [comment]
If the normal react-native Text element is working correctly, then it might be a good idea to take inspiration from how it's handled there, and adapt the logic to the text rendering algorithm here.

**Comment by BatDroid** [comment]
> > any one can tell what awebfont.ir/convert is exactly doing to the passed text. if we find out then we can find a util for it to do it for us to use it for dynamic data as well as static ones
> 
> Exactly what I am looking for!!!

it is a `Persian Glyphs Converter`. couldn't use any of the packages that i found to fix it.

**Comment by BatDroid** [comment]
> If the normal react-native Text element is working correctly, then it might be a good idea to take inspiration from how it's handled there, and adapt the logic to the text rendering algorithm here.

i haven't seen the text part of `react-native` for android but i assume that it should use the android default native text without doing anything special to it. not sure.

**Comment by msand** [comment]
Perhaps you can use the relatively recently implemented inlineSize attribute then:

```jsx
import * as React from "react";
import { View, Text } from "react-native";
import { Svg, G, Text as SvgText, TSpan } from "react-native-svg";

let persianText = "الفبای فارسی‎‎";

export default () => (
  <View>
    <Text>{persianText}</Text>
    <Svg
      width="100%"
      height="100%"
      style={{ borderWidth: 1, borderColor: "black" }}
    >
      <SvgText>
        <TSpan y={15} fontSize={14} inlineSize="100%" textAnchor="start" >
          {persianText}
        </TSpan>
        <TSpan y={30} fontSize={14} inlineSize="100%" textAnchor="middle" >
          {persianText}
        </TSpan>
        <TSpan y={45} fontSize={14} inlineSize="100%" textAnchor="end" >
          {persianText}
        </TSpan>
      </SvgText>
    </Svg>
  </View>
);

```

![Screenshot_1566845476](https://user-images.githubusercontent.com/1131362/63715040-a81bb000-c84b-11e9-9b6a-b4c08a32406a.png)

**Comment by msand** [comment]
inlineSize also does line-breaking, so you can have multiple lines of text without having to position the lines manually

**Comment by rosswaycaster** [comment]
When I set `inlineSize` on a `TSpan` I lose the `fill` color specified. Is this a known bug?

**Comment by msand** [comment]
I haven't noticed that no, thanks for reporting

**Comment by YazeedAsaad** [comment]
did anyone find a solution to this issue

**Comment by matinzd** [comment]
This issue is not resolved!

**Comment by Farzin-Firoozi** [comment]
same issue!

**Comment by amiinous** [comment]
anyone who wants a package which acts like [awebfont.ir/convert](http://awebfont.ir/convert) to handle dynamic texts can use this repo https://github.com/font-store/persian-reshaper

**Comment by MohammadAzimi** [comment]
> anyone who wants a package which acts like [awebfont.ir/convert](http://awebfont.ir/convert) to handle dynamic texts can use this repo https://github.com/font-store/persian-reshaper

its works as a workaround

**Comment by cyber-ai-dep** [comment]
I have two SVG files, one of which contains an outline-like path, where each closed shape is represented as a single continuous path. I want to generate a new path that accurately follows the centerline of each shape and fills it accordingly. The desired result should match the red path shown in the reference image. Do you have any suggestions for achieving this automatically using software applications or by writing a custom program?


![Image](https://github.com/user-attachments/assets/70a250bc-7b51-404d-8604-e1c0af95ec0e)
