### ISSUE TITLE
Element not rendering if it's a component

### ISSUE THREAD

**Issue by sergiferran** [react-native-community/react-native-svg#44]
If you have something like:

```
<Svg>
   <Rect .../>
   <Text .../>
  <MyComponent .../>
</Svg>
```

And `MyComponent` renders an element, for instance `Circle`, the render method is called but you can't see the new component if the state is updated.

**Comment by dubert** [comment]
It would make sense that you can't render a react component inside a SVG component. `<Svg>` doesn't have all the DOM diffing, et cetera that a react component does.

**Comment by steveliles** [comment]
I don't have problems rendering components inside the Svg hierarchy provide they don't return null or false (see  #84). 

Even state/props changes resolve correctly and trigger re-renders just fine (I am able to animate deeply nested components using state changes) so as far as I can tell diffing and reconciliation are working correctly.

**Comment by msand** [comment]
Not sure if this used to be an issue in some old version, but works fine now at least. Will close this for now.
