### ISSUE TITLE
Crash on Android when svg is large

### ISSUE THREAD

**Issue by macrozone** [react-native-community/react-native-svg#440]
I have a large svg which can be paned.

When i scale it up, android crashes with

java.lang.RuntimeException: Canvas: trying to draw too large(128261340bytes) bitmap.

any idea how to fix it and keep the quality? (I can scale down the svg and use a transform on the parent view, but then it gets blurry)

**Comment by Danushka50** [comment]
Any solution for this....??????

**Comment by msand** [comment]
Use at most screen size for the width and height, and use svg transform instead of rn transform to get fully sharp vector rendering. Or buy a phone with more memory.

**Comment by hnagarkoti** [comment]
Why it is closed. didn't understand. what is the proper solution.

**Comment by msand** [comment]
Make the svg small enough, such that it can fit in the memory / constraints of the device used.
