### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by prabhu** [react-native-community/react-native-svg#441]
Are there any? So scary to see such an important library existing with no tests or am I blind?

**Comment by msand** [comment]
@prabhu 
I have some manual / visual acceptance tests here: https://github.com/msand/RNSvgTests
Which I've used to compare the ios and android output to all the evergreen browsers, and fixed all the text and text on a path, matrix transforms, viewbox, ligatures, kerning, etc. related issues I've found.

There are several collections of unit tests for the various SVG spec versions. What is needed, is to implement and expose the proper getters, setters, and methods, of the DOM, which are required for the unit tests to compare the actual values to the expected values in the assertions.

In practice, the tests I've collected into that repo, require almost all parts relating to text rendering to be implemented correctly, as almost everything is both tested in isolation, and in ways such that all the properties depend on each other, and affect the output together. This even allowed me to discover that only Edge renders text on a path according to spec, all other ever-green browsers implement something which is nowhere to be found in the spec.
https://github.com/w3c/svgwg/issues/337
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13518804/
The Edge team wants it to be handled by the w3c, I haven't contacted the other browser vendors yet.

Also, Adobe Illustrator has invented their own interpretation of startOffset, where the percentage value p gives p = ( m / n ) , where m is the m:th control point in the bezier curve, and n is the number of control points, while everybody else calculates a percentage of the total pathLength of the entire curve.

If you're interested in fixing and helping with the unit tests, you can look at the SVG DOM api spec, and just implement the getters required by the tests you consider most important. This would allow many thousands of the existing unit tests to be run already. Then, implementing the other missing methods and we should be golden. What do you think?
