### ISSUE TITLE
Build Error: errors in Linking react-native-svg to existing native iOS app

### ISSUE THREAD

**Issue by tubhatia1309** [react-native-community/react-native-svg#442]
I am trying to integrate react-native svg into an existing native iOS app.
I tried manually linking the library following the link:
https://facebook.github.io/react-native/docs/linking-libraries-ios.html
(1.Added  RNSVG.xcodeproj to the project
2. libRNSVG.a in "Link Binary With Libraries"
3. $(SRCROOT)/../node_modules/react-native-svg/ios in "Header Search Paths")
I am getting this error:
clang: error: no such file or directory: '/Users/.........../Build/Products/Debug-iphonesimulator/libRNSVG.a'

Any idea ?

Thanks in advance!

**Comment by tubhatia1309** [comment]
fixed by importing RNSVG pod, which wasn't documented
pod 'RNSVG', :path => '{path to lib}'

**Comment by mchambaud** [comment]
I have a similar issue but the `libRNSVG.a` is actually in the build folder under `RNSVG/libRNSVG.a`

**Comment by gomezmark** [comment]
I encountered same issue.
please help me out.

![image](https://user-images.githubusercontent.com/19304789/107621890-ef8d3a80-6c91-11eb-8355-b760ebbccd2b.png)
