### ISSUE TITLE
How to use Network image in react-native-svg

### ISSUE THREAD

**Issue by SunSet1219** [react-native-community/react-native-svg#444]
I am going to use network image in SVG.
ex: https://crack-mind.s3.amazonaws.com/69832935-78f8-a766-8325-a1517119f566IMG_0005.JPG
it is working when I use local image "href={require("../images/post.png")}"
But I can not use network image.

**Comment by Ketn** [comment]
Looking for the solution for the above as well. Anyone got an answer?

**Comment by dotansimha** [comment]
same here

**Comment by msand** [comment]
Use fetch to download resources over http(s).
