### ISSUE TITLE
Get element position/size

### ISSUE THREAD

**Issue by icewind** [react-native-community/react-native-svg#445]
Hi.
I wonder if there is any way to get the size or position of the element? I'm using `jsx` to represent svg like this
```javascript
<G>
  <Path ref='element1' onPress={() => handlePress(1)} fill='#C4C4C4' d='...' />
  <Path ref='element2' onPress={() => handlePress(2)} fill='#C4C4C4' d='...' />
  <Path ref='element3' onPress={() => handlePress(3)} fill='#C4C4C4' d='...' />
</G>
```
And I would like to place another element on top of clicked one. And the new element should be located exactly at the center and has the same size.
I tried `onLayout` method with no luck. `this.refs.element1.measure` doesn't work either. 

I parsed contents of `d` prop and made an array of vertices so I can use some sort of Convex hull algorithm or find a minimum bounding rectangle. But this seems to me as a common task. Maybe I missed a way to achieve this faster and simpler? Maybe something like [getBoundingClientRect](https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect) but for react-native?

Also for position I can use a combination of data from `viewBox` and `transform` and origin. So the biggest question is in finding bounding box or dimensions

Thanks.

**Comment by deantes** [comment]
Did you have any luck with this?

**Comment by maxkomarychev** [comment]
Facing same problem, @icewind any chance you found a solution for that?

**Comment by maxkomarychev** [comment]
I added support for `onLayout` in this PR https://github.com/react-native-community/react-native-svg/pull/651

**Comment by HighSoftWare96** [comment]
@maxkomarychev the onLayout callback gives the current position or just the initial position of the element? I have to know the last position of the element...

**Comment by msand** [comment]
@HighSoftWare96  It gives the most recently reported size, communication over the bridge is async, so if you're animating it might already have changed. Otherwise it should stay up to date for each re-render.
