### ISSUE TITLE
iOS Installation Instructions Missing

### ISSUE THREAD

**Issue by dk0r** [react-native-community/react-native-svg#446]
**Issue**: There is no [reference](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) or description of how to install on iOS

**Solution**: To install `react-native-svg` on iOS visit the link referenced above or do the following:

1.  Open your project in XCode and drag the `RNSVG.xcodeproj` file (located in `.../node_modules/react-native-svg/ios`) into the **Libraries** directory shown in XCode.
2. Expand the `RNSVG.xcodeproj` file you just added to XCode until you see: `libRNSVG.a` (located in **RNSVG.xcodeproj** > **Products** )
3. Drag `libRNSVG.a` into the **Link Binary With Libraries** section (located in **Build Phases** which may be found at the top of the XCode window)

**Comment by adeacetis** [comment]
Hey,
Thank you!
We tried this with a colleague of mine and it's working perfectly.
Maybe it is worth mentioning we had to build the project with XCode first before running react-native run-ios command in terminal.
Will some care to create a PR for this ?
Cheers,
A

**Comment by a-r-d** [comment]
Hey @dk0r I tried this steps and I'm still having some issues. Is there anything that I could be missing you think? I'm pretty new to iOS native development so any pointers would help. I added screenshots to show what I have done so far. 

![linked-libs](https://user-images.githubusercontent.com/1312019/33784378-45c1b58e-dc26-11e7-895a-51c15b3130ab.png)

![screen shot 2017-12-08 at 2 42 07 pm](https://user-images.githubusercontent.com/1312019/33784374-413abf7e-dc26-11e7-9147-bd351c971cd2.png)

**Comment by dustinsavery** [comment]
There's no need to manually drag over the project. All you need to do is run `react-native link react-native-svg` and the library will be accessible in your project. Once it's there, be sure the library is referenced in the Linked Frameworks and Libraries (only the `libRNSVG.a`, not the `libRNSVG-tvos.a`)

**Comment by ulisinn** [comment]
Hi - 

I'm working on an example based on:
<https://www.raywenderlich.com/136047/react-native-existing-app>

Is it possible to add the library to the pod file?
Or do I have to link manually?

Thank you for your help!

Uli

**Comment by a-r-d** [comment]
@ulisinn I also got the project working using cocoapods by reffing the podspec file included in the project, however if you do it this way there are many many compiler errors to fix. It seems like that is too much trouble because you will need to fix those compiler errors every time you NPM update. 

@dustinsavery got it thanks. The problem I had was that I was using a static library output for the pod libraries and not a framework, that meant that the linker could't link in the static RNSVG library with the static react library at a later time. So, I changed my main podspec to use frameworks instead and then it worked.

**Comment by ulisinn** [comment]
@a-r-d thank you! just noticed that there are quite a few problems. including this: https://github.com/adamwulf/PerformanceBezier/issues/5

I don't have a Libraries directory in my '.xcworkspace' (or in the corresponding .xcodeproj).
Any suggestions for that? Thx!

**Comment by msand** [comment]
I've published a new version without native dependencies, and updated the readme. I have it working fine with cocoapods at least.
