### ISSUE TITLE
<ForeignObject> support

### ISSUE THREAD

**Issue by cronco** [react-native-community/react-native-svg#447]
Forgive me if this is covered, but I've searched the documentation and the issues and see no reference to this.

Is `<foreignObject>` supported or on the roadmap?

**Comment by ssssssssssss** [comment]
What's the use case of a foreignObject?  Does it work if wrapping a RN <View/> as foreignObject?

**Comment by cronco** [comment]
Handling rich-text in SVG is really difficult, so some people embed HTML elements in `foreignobject` to be able to represent richly-formatted text in a hassle-free way.

As for the second question, I wouldn't know, I'm a RN neophyte (though I do have some experience with react) looking into this particular use-case atm.

**Comment by msand** [comment]
You can use a WebView instead, almost the same functionality/end-result. SVG 2 supports multi line and shape-inside line-breaking. So when the layout algorithm for that is properly implemented, it should be much better. I've already started it, and just a few things to do left and then it can be integrated: https://github.com/msand/react-native-svg/blob/6.0.0/android/src/main/java/com/horcrux/svg/TextLayoutAlgorithm.java

**Comment by msand** [comment]
Otherwise, just position view and svg elements absolutely.

**Comment by wesleyguirra** [comment]
does it have support now?

**Comment by msand** [comment]
I would recommend splitting your svg into a foreground and background layer, and place a native view with what ever you need in between. This will be more performant (reuses the resulting bitmaps of the svgs) than using the svg rendering logic to make bitmaps of other native components (rerendering all of it on any change in the foreignobjects) + handling hit testing and gestures etc.
Or what would be your use case?

**Comment by msand** [comment]
I realized that clipping and masking of native content might be useful, and once we have filter support, that could also be used for all kinds of purposes. Reopening this.

**Comment by msand** [comment]
[12.5. The ‘foreignObject’ element](https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement)
‘foreignObject’

Categories:

[Graphics element](https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement), [renderable element](https://svgwg.org/svg2-draft/render.html#TermRenderableElement), [structurally external element](https://svgwg.org/svg2-draft/struct.html#TermStructurallyExternalElement)

Content model:

Any elements or character data.

Attributes:

*   [aria attributes](https://svgwg.org/svg2-draft/struct.html#TermARIAAttribute) — ‘[aria-activedescendant](https://www.w3.org/TR/wai-aria-1.1/#aria-activedescendant)’, ‘[aria-atomic](https://www.w3.org/TR/wai-aria-1.1/#aria-atomic)’, ‘[aria-autocomplete](https://www.w3.org/TR/wai-aria-1.1/#aria-autocomplete)’, ‘[aria-busy](https://www.w3.org/TR/wai-aria-1.1/#aria-busy)’, ‘[aria-checked](https://www.w3.org/TR/wai-aria-1.1/#aria-checked)’, ‘[aria-colcount](https://www.w3.org/TR/wai-aria-1.1/#aria-colcount)’, ‘[aria-colindex](https://www.w3.org/TR/wai-aria-1.1/#aria-colindex)’, ‘[aria-colspan](https://www.w3.org/TR/wai-aria-1.1/#aria-colspan)’, ‘[aria-controls](https://www.w3.org/TR/wai-aria-1.1/#aria-controls)’, ‘[aria-current](https://www.w3.org/TR/wai-aria-1.1/#aria-current)’, ‘[aria-describedby](https://www.w3.org/TR/wai-aria-1.1/#aria-describedby)’, ‘[aria-details](https://www.w3.org/TR/wai-aria-1.1/#aria-details)’, ‘[aria-disabled](https://www.w3.org/TR/wai-aria-1.1/#aria-disabled)’, ‘[aria-dropeffect](https://www.w3.org/TR/wai-aria-1.1/#aria-dropeffect)’, ‘[aria-errormessage](https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage)’, ‘[aria-expanded](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded)’, ‘[aria-flowto](https://www.w3.org/TR/wai-aria-1.1/#aria-flowto)’, ‘[aria-grabbed](https://www.w3.org/TR/wai-aria-1.1/#aria-grabbed)’, ‘[aria-haspopup](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup)’, ‘[aria-hidden](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden)’, ‘[aria-invalid](https://www.w3.org/TR/wai-aria-1.1/#aria-invalid)’, ‘[aria-keyshortcuts](https://www.w3.org/TR/wai-aria-1.1/#aria-keyshortcuts)’, ‘[aria-label](https://www.w3.org/TR/wai-aria-1.1/#aria-label)’, ‘[aria-labelledby](https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby)’, ‘[aria-level](https://www.w3.org/TR/wai-aria-1.1/#aria-level)’, ‘[aria-live](https://www.w3.org/TR/wai-aria-1.1/#aria-live)’, ‘[aria-modal](https://www.w3.org/TR/wai-aria-1.1/#aria-modal)’, ‘[aria-multiline](https://www.w3.org/TR/wai-aria-1.1/#aria-multiline)’, ‘[aria-multiselectable](https://www.w3.org/TR/wai-aria-1.1/#aria-multiselectable)’, ‘[aria-orientation](https://www.w3.org/TR/wai-aria-1.1/#aria-orientation)’, ‘[aria-owns](https://www.w3.org/TR/wai-aria-1.1/#aria-owns)’, ‘[aria-placeholder](https://www.w3.org/TR/wai-aria-1.1/#aria-placeholder)’, ‘[aria-posinset](https://www.w3.org/TR/wai-aria-1.1/#aria-posinset)’, ‘[aria-pressed](https://www.w3.org/TR/wai-aria-1.1/#aria-pressed)’, ‘[aria-readonly](https://www.w3.org/TR/wai-aria-1.1/#aria-readonly)’, ‘[aria-relevant](https://www.w3.org/TR/wai-aria-1.1/#aria-relevant)’, ‘[aria-required](https://www.w3.org/TR/wai-aria-1.1/#aria-required)’, ‘[aria-roledescription](https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription)’, ‘[aria-rowcount](https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount)’, ‘[aria-rowindex](https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex)’, ‘[aria-rowspan](https://www.w3.org/TR/wai-aria-1.1/#aria-rowspan)’, ‘[aria-selected](https://www.w3.org/TR/wai-aria-1.1/#aria-selected)’, ‘[aria-setsize](https://www.w3.org/TR/wai-aria-1.1/#aria-setsize)’, ‘[aria-sort](https://www.w3.org/TR/wai-aria-1.1/#aria-sort)’, ‘[aria-valuemax](https://www.w3.org/TR/wai-aria-1.1/#aria-valuemax)’, ‘[aria-valuemin](https://www.w3.org/TR/wai-aria-1.1/#aria-valuemin)’, ‘[aria-valuenow](https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow)’, ‘[aria-valuetext](https://www.w3.org/TR/wai-aria-1.1/#aria-valuetext)’, ‘[role](https://svgwg.org/svg2-draft/struct.html#RoleAttribute)’
*   [core attributes](https://svgwg.org/svg2-draft/struct.html#TermCoreAttribute) — ‘[id](https://svgwg.org/svg2-draft/struct.html#IDAttribute)’, ‘[tabindex](https://svgwg.org/svg2-draft/struct.html#SVGElementTabindexAttribute)’, ‘[lang](https://svgwg.org/svg2-draft/struct.html#LangAttribute)’, ‘[xml:space](https://svgwg.org/svg2-draft/struct.html#XMLSpaceAttribute)’, ‘[class](https://svgwg.org/svg2-draft/styling.html#ClassAttribute)’, ‘[style](https://svgwg.org/svg2-draft/styling.html#StyleAttribute)’
*   [conditional processing attributes](https://svgwg.org/svg2-draft/struct.html#TermConditionalProcessingAttribute) — ‘[requiredExtensions](https://svgwg.org/svg2-draft/struct.html#RequiredExtensionsAttribute)’, ‘[systemLanguage](https://svgwg.org/svg2-draft/struct.html#SystemLanguageAttribute)’
*   [global event attributes](https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers) — ‘[oncancel](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oncanplay](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oncanplaythrough](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onchange](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onclick](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onclose](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oncuechange](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondblclick](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondrag](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragend](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragenter](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragexit](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragleave](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragover](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondragstart](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondrop](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ondurationchange](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onemptied](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onended](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onerror](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onfocus](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oninput](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oninvalid](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onkeydown](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onkeypress](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onkeyup](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onload](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onloadeddata](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onloadedmetadata](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onloadstart](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmousedown](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmouseenter](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmouseleave](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmousemove](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmouseout](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmouseover](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmouseup](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onmousewheel](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onpause](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onplay](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onplaying](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onprogress](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onratechange](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onreset](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onresize](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onscroll](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onseeked](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onseeking](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onselect](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onshow](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onstalled](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onsubmit](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onsuspend](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ontimeupdate](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[ontoggle](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onvolumechange](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onwaiting](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’
*   [document element event attributes](https://html.spec.whatwg.org/multipage/webappapis.html#documentandelementeventhandlers) — ‘[oncopy](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[oncut](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onpaste](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’
*   [graphical event attributes](https://svgwg.org/svg2-draft/interact.html#EventAttributes) — ‘[onfocusin](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’, ‘[onfocusout](https://svgwg.org/svg2-draft/interact.html#EventAttributes)’
*   [presentation attributes](https://svgwg.org/svg2-draft/styling.html#TermPresentationAttribute) —

Geometry properties:

*   [x](https://svgwg.org/svg2-draft/geometry.html#XProperty)
*   [y](https://svgwg.org/svg2-draft/geometry.html#YProperty)
*   [width](https://svgwg.org/svg2-draft/geometry.html#Sizing)
*   [height](https://svgwg.org/svg2-draft/geometry.html#Sizing)

DOM Interfaces:

*   [SVGForeignObjectElement](https://svgwg.org/svg2-draft/embedded.html#InterfaceSVGForeignObjectElement)

SVG is designed to be compatible with other XML languages for describing and rendering other types of content. The ‘[foreignObject](https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement)’ element allows for inclusion of elements in a non-SVG namespace which is rendered within a region of the SVG graphic using other user agent processes. The included foreign graphical content is subject to SVG transformations, filters, clipping, masking and compositing. Examples include inserting a [MathML](https://www.w3.org/TR/2003/REC-MathML2-20031021/) expression into an SVG drawing \[[MathML3](https://svgwg.org/svg2-draft/refs.html#ref-mathml3)\], or adding a block of complex CSS-formatted HTML text or form inputs.

The HTML parser treats elements inside the ‘[foreignObject](https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement)’ equivalent to elements inside an HTML document fragment. Any `svg` or `math` element, and their descendents, will be parsed as being in the SVG or MathML namespace, respectively; all other tags will be parsed as being in the HTML namespace.

SVG-namespaced elements within a ‘[foreignObject](https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement)’ will not be rendered, except in the situation where a properly defined SVG fragment, including a root ‘[svg](https://svgwg.org/svg2-draft/struct.html#SVGElement)’ element is defined as a descendent of the ‘[foreignObject](https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement)’.

**Comment by Victorien-Tardif** [comment]
Hi, do we have progress / workaround on this?
Thanks

**Comment by msand** [comment]
There is experimental support for foreignObject in the develop branch now: https://github.com/react-native-community/react-native-svg/pull/1242#issuecomment-573347807
Many thanks to @SaeedZhiany

**Comment by msand** [comment]
Also, for multi-line text, you can use the inlineSize attribute on TSpan elements, and it will cause line-breaks to ensure the text fits inside that width

**Comment by youssefali424** [comment]
This library is so awesome and have a good support as well, i have a problem with ForeignObject as it doesn't render transform is style on View, anyone have the same issue or only me?

**Comment by youssefali424** [comment]
This library is so awesome and have a good support as well, i have a problem with ForeignObject as it doesn't render transform is style on View, anyone have the same issue or only me? , is it ok as well to ask this question here or should i ask it on a new issue? thank you in advance.

**Comment by SaeedZhiany** [comment]
@youssefali424 

Please open a new issue with more detail and a reproducible example (preferably an expo project to see the problem quickly).

Thanks

**Comment by kenodek** [comment]
@msand Could you provide an example of inlineSize. I try to use it but without any effect
