### ISSUE TITLE
transform doesn't works in Rect

### ISSUE THREAD

**Issue by GianniGM** [react-native-community/react-native-svg#448]
I must convert an svg rectangle from <rect> to <Rect>

`
<Rect x="8.128" y="4.912" transform="matrix(-0.7072 -0.707 0.707 -0.7072 7.7779 30.721)" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" width="4.243" height="17.676"/>
`

but instead of a rotated rectangle like this:
![rect0](https://user-images.githubusercontent.com/5739601/30120665-d12bb796-9329-11e7-9bee-2a7bc86cd773.png)

I see just this:
![rect](https://user-images.githubusercontent.com/5739601/30120676-d7cddb1a-9329-11e7-8f0e-e3e527643e17.png)

What am I doing wrong?

**Comment by icewind** [comment]
I don't think transform matrix is supported by react-native-svg. But you can use separate transformations to achieve the same result like `transform={{ translate: 'x, y', scale: 'x, y', rotate: 'point, x, y' }}`(not tested)

**Comment by GianniGM** [comment]
it works if i use this props, it's hard because all matrix values changes

`x='?' y='?' rotate='?' scale='?' origin='?, ?' originX=? originY=?`

**Comment by msand** [comment]
You can use my fork/pull request, it supports matrix transforms in both ios and android
https://github.com/react-native-community/react-native-svg/pull/430
