### ISSUE TITLE
Weird gestures behavior when svg is scaled down

### ISSUE THREAD

**Issue by koloff** [react-native-community/react-native-svg#449]
Hello! 
I have the following issue: There is a parent View that wraps 2 children views - left and right panels.

When I move finger across the screen I animate the width of the left panel and scale its content.
That content has one SVG circle. I want to be able capture the onPress event of the SVG circle. 

But when I press on the circle WHILE SCALED DOWN, the animation flickers. If you open the console you can see that the **velocity** of the gesture is **much bigger** when the press is on the SCALED circle.

If the svg is **not scaled** down, it works as expected.
If the svg does **not have onPress event or panResponders** it also works.

Here it is my snack: https://snack.expo.io/r1fp9Fy5b. The issue appears on physical android devices, so scan the QR code.

Is this behavior of the scaled gestures expected or it is a bug? And how to fix it?

Thanks in advance!

**Comment by msand** [comment]
Can you try with the latest version?

**Comment by msand** [comment]
This seems to work fine in the latest expo: https://snack.expo.io/@msand/dW5uYW
