### ISSUE TITLE
Doesn't work with RN 0.48.3

### ISSUE THREAD

**Issue by dsvgit** [react-native-community/react-native-svg#452]
I updated RN to 0.48.3 and react-native-svg doesn't work
![d5f365d577](https://user-images.githubusercontent.com/9424830/30406647-d7ae30bc-98fb-11e7-841c-e37a5c2ca182.jpg)

**Comment by MarvinAmador7** [comment]
Same here

![rnsvgtspan m 2017-09-26 11-47-28](https://user-images.githubusercontent.com/13001660/30875413-b3551dde-a2b0-11e7-932d-f8b929a70234.png)

```
"react": "16.0.0-alpha.12",
"react-dom": "16.0.0-alpha.12",
"react-native": "0.48.4",
"react-native-svg": "^6.0.0-rc1",
```

**Comment by samratshekhar** [comment]
Check #401, #360 and #386 of react-native-svg

**Comment by scerelli** [comment]
did you fix it? i've the same error

**Comment by msand** [comment]
@scerelli check https://github.com/react-native-community/react-native-svg/issues/460#issuecomment-332441043 or https://github.com/react-native-community/react-native-svg/issues/460#issuecomment-332444813

**Comment by bramus** [comment]
Fixed with commit be8797be5239085d5d09eec90a926ae8da7a8583, awaiting new release.

**Comment by samanthacampisi** [comment]
@bramus does anyone know when is it going to be released?

**Comment by bramus** [comment]
@samanthacampisi I have no idea either (I'm not a maintainer) :-/

**Comment by brunolemos** [comment]
@magicismight please do a new npm release to include https://github.com/react-native-community/react-native-svg/commit/be8797be5239085d5d09eec90a926ae8da7a8583, thank you :)

**Comment by msand** [comment]
New versions are available. Closing.
