### ISSUE TITLE
Image fit circle

### ISSUE THREAD

**Issue by EstebanBP** [react-native-community/react-native-svg#453]
I need some help to achieve an easy task. I just want to fit an image inside the circle.

	<Svg height={this.props.height} width={this.props.width}>
		{this._renderCircles()}/*render some other elements*/
		<Defs>
			<ClipPath id="clip">
				<Circle cx="50%" cy="50%" r={this.innerSpace / 2 }/>
			</ClipPath>
		</Defs>
		<Image
			x="0"
			y="0"
			height="100%"
			width="100%"
			preserveAspectRatio="xMinYMin meet"
			href={{uri: url, __packager_asset: true}}
			clipPath="url(#clip)"
		/>
	</Svg>

The image does not resize to fit the circle. I should not modify main Svg. What am I doing wrong?
Thanks in advance

**Comment by dotansimha** [comment]
Same here. @EstebanBP you found a solution?

**Comment by EstebanBP** [comment]
@dotansimha I couldn't do it. I had to use an Image within a View (React-native components) with position absolute.

**Comment by msand** [comment]
I think you probably need to set the viewbox attribute, have you tried that?
