### ISSUE TITLE
SVG view works on simulator but freezes on real device

### ISSUE THREAD

**Issue by ahaus** [react-native-community/react-native-svg#454]
I created an SVG element within a View holding a PanResponder for drawing an SVG Path. 
Everything works well in simulators (Debug mode and Release Mode). 

However if I run the app in Release mode on the simulator the response and drawing is much slower/laggy compared to the Debug mode. But it works.

If a run the app on the real device (iOS 10.3 - iphone 5, ipad 2, Android 7.1) the app/view freezes and comes back after about 10 seconds. Nothing is drawn. The strange thing is that if I run the app in Debug mode on the real devices it works fine.

Any idea what the problem might be? Thanks.

**Comment by ahaus** [comment]
Forgot to mention:
react-native: 0 .46.4
react: 16.0.0-alpha.12
react-native-svg: 5.4.1
ios: 10.3, Android: 7.x

Same happens with react-native 0.47

**Comment by aish1550** [comment]
Hiya, have you found a solution to this?
I'm having the exact same issue. 
Exact same version of packages and react native.

**Comment by MiracleChrisC** [comment]
I have the same issue.
sometimes it run very slow and block all touch input.

Simulator seems work fine and android work well.

**Comment by ahaus** [comment]
I switched to https://github.com/keshavkaul/react-native-sketch-view since I need only drawing this time.

**Comment by msand** [comment]
Please provide a full replication, closing until then.
