### ISSUE TITLE
Image in svg render with bug if width and height equal 

### ISSUE THREAD

**Issue by theGABS** [react-native-community/react-native-svg#455]
If i set width and height in pixels equal image render very strangely.

Image addition translate to x,y.

if i set x=100, y=100, width=200, height=200 - part(bottom right) of the image is cut off.
but if i set width=200, height=201 - everything ok. 
if i set x,y great then width and height - the picture will not be visible at all

**Comment by msand** [comment]
You need to set a correct viewBox attribute value:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
http://tutorials.jenkov.com/svg/svg-viewport-view-box.html

**Comment by fxhereng** [comment]
+1 Can't find a solution, in dev it works fine setting + 1 to the height but in production it doesn't work. Nothing appears.

**Comment by msand** [comment]
Can you try the latest version, should be fixed.
