### ISSUE TITLE
Unexpected behavior: Svg icons render completely filled

### ISSUE THREAD

**Issue by jamesvphan** [react-native-community/react-native-svg#456]
I have various Svg icons I want to render. Some are fine, but then I've encountered some icons where the entire icon is filled when I only want to keep the stroke intact. See images below. First is the intended svg, but second image is the actual result. I tried increasing the height and width, thinking the stroke width was too large even at the default value of 1, but the icon is still filled.

<img width="123" alt="screen shot 2017-09-19 at 4 03 39 pm" src="https://user-images.githubusercontent.com/19373025/30612894-25a8a822-9d54-11e7-84da-1636a84c6917.png">
<img width="106" alt="screen shot 2017-09-19 at 4 03 26 pm" src="https://user-images.githubusercontent.com/19373025/30612895-25a8affc-9d54-11e7-8b25-32f280dc0011.png">

This is my code to render:
```
<Svg height="30" width="30" viewBox="0 0 53 47.64">
          <Circle cx="12.8" cy="29.7" r="11.3"/>
          <Path d="M18.7 28.3a7.2 7.2 0 0 1-7.2 7.2"/>
          <Circle cx="35.3" cy="29.7" r="11.3"/>
          <Path d="M3.1 23.9 10.4 6.2A7 7 0 0 1 17 1.5h7V28.3"/>
          <Path d="M44.9 23.9 37.6 6.2A7 7 0 0 0 31 1.5H24V28.3"/>
          <Line x1="19.2" y1="11.9" x2="28.8" y2="11.9"/>
</Svg>
```

**Comment by msand** [comment]
Have you tried my fork / pull request https://github.com/react-native-community/react-native-svg/pull/430
Try installing the currently latest commit:
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67
yarn add react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67

**Comment by jamesvphan** [comment]
@msand so ran npm install for the latest commit as you suggested, but had no effect. Svg icons are being filled in unintentionally.
