### ISSUE TITLE
react-native-svg is not working

### ISSUE THREAD

**Issue by gitpayal** [react-native-community/react-native-svg#459]
I want to use svg images in place of png icons because the quality of icons rendered by png is not good.I have folloing specifications 

 "react-native": "^0.42.3",
 "react-native-svg": "4.3.0",
"react": "^15.4.1"

After "npm install" ,When I import react-native-svg in my project, it throws following errors

ERROR in ./node_modules/react-native-svg/lib/SvgTouchableMixin.js
Module not found: Error: Can't resolve 'react-native/Libraries/Components/Touchable/Touchable' in '/home/payalverma/Projects/caro-mobile/node_modules/react-native-svg/lib'
 @ ./node_modules/react-native-svg/lib/SvgTouchableMixin.js 1:296-360
 @ ./node_modules/react-native-svg/elements/Shape.js
 @ ./node_modules/react-native-svg/elements/Rect.js
 @ ./node_modules/react-native-svg/index.js
 @ ./app/components/common/DrawerContent.js
 @ ./app/components/Home.js
 @ ./app/components/routes/Navigation.web.js
 @ ./app/index.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:5000 webpack/hot/dev-server ./index.web.js

Anyone has similar issues or can help me with he same.Am I missing dependencies
?

**Comment by msand** [comment]
https://github.com/react-native-community/react-native-svg#notice

NOTICE:

react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >= 15.4.0
react-native-svg >= 4.5.0 only supports react-native >= 0.40.0 and react >= 15.4.0
react-native-svg >= 5.1.8 only supports react-native >= 0.44.0 and react == 16.0.0-alpha.6
react-native-svg >= 5.2.0 only supports react-native >= 0.45.0 and react == 16.0.0-alpha.12
react-native-svg >= 5.3.0 only supports react-native >= 0.46.0 and react == 16.0.0-alpha.12

**Comment by gitpayal** [comment]
I tried with 
"react-native": "^0.42.3",
"react-native-svg": "4.5.0",
"react": "15.4.1" yesterday 

Still same issue

**Comment by msand** [comment]
Try these https://github.com/msand/RNSvgTests/blob/latest_stable_dependency_versions/package.json

**Comment by gitpayal** [comment]
Thanks msand for help. Following works for me in case anyone looking for it.

"react": "^15.4.1",
"react-native": "^0.42.3",
"react-svg": "^2.1.21"

**Comment by msand** [comment]
@gitpayal Great, happy I could help! Seems you had forgot to run "npm install" or "yarn" after changing the version number, or was there some further issue?

**Comment by mobitinker** [comment]
Hi, I may be having the same problem but version numbers now have advanced even further.

  "react": "^16.0.0",
    "react-native": "^0.48.4",
    "react-native-svg": "^5.4.2",
    
Are these known to work? I get the following bundling error when I try to add some simple svg output to my app.

error: bundling failed: "Unable to resolve module `react-native-svg` from `/Users/mark/workspace/pourview/node_modules/victory-native/lib/components/victory-primitives/arc.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
