### ISSUE TITLE
No visible @interface for 'UIBezierPath' declares the selector 'length'

### ISSUE THREAD

**Issue by diruuu** [react-native-community/react-native-svg#460]
Hi, I got this error when trying to manually install react-native-svg on ios project. Automatic linking corrupted my project files. Any solution?

React: v16.0.0-alpha.12
React Native: v0.48.4
React Native SVG: v5.4.0

![30875413-b3551dde-a2b0-11e7-932d-f8b929a70234](https://user-images.githubusercontent.com/6884679/30896200-67437e3a-a379-11e7-8866-2083d0a856eb.png)

**Comment by lxooxl** [comment]
pathLength = [_path pathLength];

**Comment by msand** [comment]
Alternatively you can use 
https://github.com/msand/react-native-svg/tree/6.0.0
or https://github.com/msand/react-native-svg/tree/cocoapods
Something seems to have broken when merging my pull request or the commits after, original still works.
I think the second latest commit in this upstream repo 6.0.0 branch should work as well:
https://github.com/react-native-community/react-native-svg/commit/d5923bb4fe175d941517bf0e59fbc036c9e9fe1f

**Comment by therahuls1ngh** [comment]
Still Facing the same issue

**Comment by diruuu** [comment]
@lxooxl solution works for me.

**Comment by bramus** [comment]
Fixed with commit be8797be5239085d5d09eec90a926ae8da7a8583, awaiting new release.

**Comment by rodrigoxavier** [comment]
@bramus comment about the new commit solve to me. A just change:

`pathLength = [_path length];`

to 

`pathLength = [_path pathLength];`

**Comment by therahuls1ngh** [comment]
Thanks it worked

**Comment by msand** [comment]
I've just released 6.0.1-rc.2 which removes PerformanceBezier and QuartzBookPack. Can you please test it?
@diruuu 
@lxooxl 
@therahuls1ngh 
@bramus 
@rodrigoxavier

**Comment by msand** [comment]
This is fixed now, closing.
