### ISSUE TITLE
Marker is unsupported

### ISSUE THREAD

**Issue by corradio** [react-native-community/react-native-svg#461]
Any plans for supporting the Marker element?

**Comment by msand** [comment]
It is fourth in the TODO list , at least I don't know anyone working on it, feel free to start implementing :D
https://github.com/react-native-community/react-native-svg#todo

**Comment by pedromrb** [comment]
Hey guys, any news on this?

**Comment by msand** [comment]
@pedromrb Please feel free to work on it if you have a need for it.

**Comment by msand** [comment]
I've made a first attempt at implementing marker element support now. 

Could you help testing it? https://github.com/react-native-community/react-native-svg/pull/1122 

It's available from the develop branch: https://github.com/react-native-community/react-native-svg/tree/develop

**Comment by SaeedZhiany** [comment]
@msand 

How can I use it with `Path` component?

in React we can use it like this: 

```
<Svg>
        <Defs>
          <Marker id={id} markerWidth="13" markerHeight="13" refX="2" refY="6" orient="auto">
            <Path d="M2,1 L2,10 L10,6 L2,2" fill={color}/>
          </Marker>
        </Defs>

        <Path d={line} style={{markerMid: `url(#${id})`}}/>
        <Path key={`transparent ${id}`} d={transparentLine}/>
</Svg>
```

Is there any correspond prop to marker(Start/Mid/End) in react-native-svg?

**Comment by SaeedZhiany** [comment]
@msand 

How can I use it with `Path` component?

in React we can use it like this: 

```
<Svg>
        <Defs>
          <Marker id={id} markerWidth="13" markerHeight="13" refX="2" refY="6" orient="auto">
            <Path d="M2,1 L2,10 L10,6 L2,2" fill={color}/>
          </Marker>
        </Defs>

        <Path d={line} style={{markerMid: `url(#${id})`}}/>
        <Path key={`transparent ${id}`} d={transparentLine}/>
</Svg>
```

Is there any correspond prop to `marker(Start/Mid/End)` in react-native-svg?
