### ISSUE TITLE
Ambiguous resolution

### ISSUE THREAD

**Issue by schneck** [react-native-community/react-native-svg#463]
Hello,

after upgrading react-native to the latest RC, bundling fails together with react-native-svg:
```
Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/Users/so/Documents/workspace/my-app/index.android.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `/Users/so/Documents/workspace/my-app/node_modules/react-native-svg/node_modules/react-native/package.json`
  * `/Users/so/Documents/workspace/my-app/node_modules/react-native/package.json`

```

Versions:

```
react-native-cli: 1.0.0
react-native: 0.48.4
react-native-svg: 6.0.0-rc1
```

Any idea?

**Comment by louuysison** [comment]
Getting the same error using react-native-svg: 5.2.0 and react-native: 0.48.2

**Comment by vlad-zhukov** [comment]
Try `yarn start --reset-cache`

**Comment by schneck** [comment]
Yep, that works. Thanks!

**Comment by endel** [comment]
Just a small correction: to pass `--reset-cache` via `yarn`, you need to pass the a separator first, otherwise `node` will be called without the argument.

```
yarn start -- --reset-cache
...
node node_modules/react-native/local-cli/cli.js start --reset-cache
```

**Comment by jcurtis** [comment]
@endel That's no longer necessary in the latest version of yarn.

**Comment by RuiDamiao** [comment]
I´m getting a similar error:

Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `D:\PORTAL.MOBILE\PortalMobile\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `D:\PORTAL.MOBILE\PortalMobile\node_modules\react-native-view-more-text\node_modules\react-native\package.json`
  * `D:\PORTAL.MOBILE\PortalMobile\node_modules\react-native\package.json`

I've already tried this comands:
'yarn start --reset-cache'
'node node_modules/react-native/local-cli/cli.js start --reset-cache'
'rm -rf node_modules && npm install'

Any idea?

**Comment by perzect** [comment]
@RuiDamiao ,restart your mac will resolve this problem.Works for me.

**Comment by nonameolsson** [comment]
I've restarted my Mac, and I have tried with `yarn start -- --reset-cache`. Any other idea? This hapened when I added Podfile and started using Pods.

**Comment by RuiDamiao** [comment]
@perzect I've already tried. The problem is that this path 'D:\PORTAL.MOBILE\PortalMobile\node_modules\react-native-view-more-text\node_modules\react-native\package.json' doesn't exist. I don't know what to do. 
I cloned the project again and the first time worked well, I've installed another module and I got this error again and now even when I clone the project (again) I get this error.

**Comment by perzect** [comment]
@RuiDamiao Yep! Delete node_modules will not resolve this Pro. Maybe the key is 'npm uninstall '.I'll try this next time.

**Comment by vladdnepr1991** [comment]
I had the same problem. Any solution did not help but cloning project in new folder solve this.

**Comment by kaderhussain** [comment]
if these doesn't work
yarn start -- --reset-cache
check manually if there is another node_module inside the project.I had the same issue bcoz I duplicated the same project inside the project.

**Comment by futurechallenger** [comment]
I fixed this by removing all Pod stuff and reinstall them

**Comment by PavanGangireddy** [comment]
@allanjsx  Its throwing algorithm' file not found

**Comment by rgkobashi** [comment]
@allanjsx you can find the issue (currently opened) for the algorithm error [here](https://github.com/facebook/yoga/issues/711), in one of the solution/comments I found [this](https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578) gist to fix many issues coming from cocoapods

**Comment by xe4me** [comment]
I had to delete the node_module and Pods folder. and `npm i` and then `pod update` `pod install` .

This is because initially I started the project and in the podfile there was no React mentioned.
It was working, then I added another library ( fast-image) and that needed the React to be inside the podfile and then after that it got confused.

**Comment by aleczadikian** [comment]
@allanjsx 's solution worked for me, except I also had to delete the existing React pod in the ios dir. 

Strange that React Native will let this problem occur by default. Lots of packages end up creating a duplicate React pod if you don't force it to use the one from `node_modules`; I encountered it with the `react-native-camera` package.

**Comment by Uzairrrr** [comment]
@allanjsx 's solution worked

**Comment by shoorkaii** [comment]
there are two different versions of react-native in your package.json files.

**Comment by Kielan** [comment]
Most likely you have react native being provided as a variable from the ios pods/React/package.json file, as well as from the base package.json file. Please confirm if this is the case.

**Comment by Asleepace** [comment]
Similar to @xe4me solution, this worked for me:
```
rm -rf node_modules && yarn
pod deintegrate
pod install
```

**Comment by gaoxing964** [comment]
Unfortunately, l encountered this annoying problem too. l have resolved this problem by cloning this project in a new dir.

**Comment by gaoxing964** [comment]
l have resolved this problem in two ways. one is you clone your project in a new dir and another is execute  
`yarn start -- --reset-cache `

**Comment by githubhuwenpeng** [comment]
> l have resolved this problem in two ways. one is you clone your project in a new dir and another is execute
> `yarn start -- --reset-cache `

I have the same problem  but  yarn start -- --reset-cache  can't solve my problem

**Comment by matthew-dean** [comment]
Also wasn't resolvable for me with a cache reset, FWIW.

**Comment by jqn** [comment]
I had react-native-cookies and @react-native-community/cookies in my package.json, so it would be a good idea to check for duplicate packages.
