### ISSUE TITLE
svgRef.toDataURL() crash on Android 

### ISSUE THREAD

**Issue by tnyavdc** [react-native-community/react-native-svg#464]
toDataURL is working on iOS but crashing on Android. 

**RN version :** 0.47.0
**react-native-svg version :** 5.4.1
**react version :** 16.0.0-alpha.12

**Code :**
`test(svgRef) { if (svgRef) {  svgRef.toDataURL(base64 => { }) }}`

`<Svg
              width={this.props.width}
              height={this.props.height}
              ref={ref => {
                if (this.state.released) {
                  this.test(ref);
                }
              }}
            > ... </Svg>`

**Error :** `undefined is not an object (evaluating RNSVGSvgViewMAnager.toDataURL)`

**Comment by koxen** [comment]
@msand was this fixed since?

**Comment by msand** [comment]
I don't remember testing recently, will have to check.

**Comment by msand** [comment]
At least seems to work with the latest code, I think Expo still hasn't upgraded, probably worth asking in their repo.

**Comment by jaimebiernaski** [comment]
Hi, some news about this? I'm facing the same problem... Just with Android... on iOS it is OK.

**Comment by msand** [comment]
Seems to work fine, please provide a full replication. Closing until then.
