### ISSUE TITLE
Error retrieving parent from item

### ISSUE THREAD

**Issue by Michdo93** [react-native-community/react-native-svg#465]
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by sriraman** [comment]
@Michdo93  I'm also facing the same issue.  Did you get any clue?

**Comment by burdiuz** [comment]
Make sure you have same versions for 
```
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
```
and 
```
compile "com.android.support:appcompat-v7:25.0.0"
```
As described here https://stackoverflow.com/a/42144590

**Comment by Michdo93** [comment]
@burdiuz 
It doesn't change anything. I changed all to version 25.0.0. Then I tried it with 23.0.0. Nothing helped. I also changed react-native from 0.48.4 to 0.46.0. Nothing really helped. Should I use an older Android version and an older React Native version?

**Comment by Michdo93** [comment]
@burdiuz 
Can you show me your package.json, the settigs.gralde and the app.gradle file? And maybe the other needed files. Thank you. But it really doesn't work. I can't figure out why

**Comment by fenicento** [comment]
+1

**Comment by PaitoAnderson** [comment]
I ended up solving this by doing this in my build.gradle:

```
compile(project(':react-native-svg')) {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by amestsantim** [comment]
@PaitoAnderson Your solution is the only one that worked for me. Can you explain what it does?

**Comment by thibault12** [comment]
@PaitoAnderson Worked for me as well thank you very much!!

**Comment by blinkstu** [comment]
@PaitoAnderson you are right! thank you!!!!

**Comment by dustinsavery** [comment]
I've added this to the README here: #547

**Comment by Metroxe** [comment]
@PaitoAnderson  Thanks, worked for me, but can you explain what the code does?

**Comment by PaitoAnderson** [comment]
@amestsantim @Metroxe 

I am no expert here, but I believe it's because React Native currently expects you to use `appcompat-v7:23.0.1` and this project specifies `appcompat-v7:25.3.1` in it's [/android/build.gradle](../blob/master/android/build.gradle#L38), so I am just overriding that and it will use the version specified in your `/android/app/build.gradle` instead which is likely 23.0.1.

**Comment by dustinsavery** [comment]
This is causing another issue too. Going to try and lower the `appcompat` setting and see if it fixes this.

**Comment by pravinraut809** [comment]
where to write this code ,, cuz m getting syntax error

**Comment by msand** [comment]
@pravinraut809 Try this: https://github.com/react-native-community/react-native-svg/blob/2aec32e39b405a4f4fa3f1e9dcb24ee0ea6339e6/README.md#android

Insert the following lines inside the dependencies block in **android/app/build.gradle**:

compile(project(':react-native-svg')) {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}

**Comment by msand** [comment]
Alternatively, upgrade the versions in your project as shown here: https://github.com/msand/AwesomeProject/commit/fe0e96874f9c9efbbb7bd3d61d57e6afcdfc2b65

5  [android/app/build.gradle](https://github.com/msand/AwesomeProject/commit/fe0e96874f9c9efbbb7bd3d61d57e6afcdfc2b65#diff-dc46f9f5dfe204e394fb41395ccd03cfR97)
```
 @@ -94,8 +94,7 @@ def enableSeparateBuildPerCPUArchitecture = false
  def enableProguardInReleaseBuilds = false
  
  android {
 -    compileSdkVersion 23
 -    buildToolsVersion "23.0.1"
 +    compileSdkVersion 27
  
      defaultConfig {
          applicationId "com.awesomeproject"
 @@ -139,7 +138,7 @@ android {
  dependencies {
      compile project(':react-native-svg')
      compile fileTree(dir: "libs", include: ["*.jar"])
 -    compile "com.android.support:appcompat-v7:23.0.1"
 +    compile "com.android.support:appcompat-v7:27.0.2"
      compile "com.facebook.react:react-native:+"  // From node_modules
  }
```
  

4  [android/build.gradle](https://github.com/msand/AwesomeProject/commit/fe0e96874f9c9efbbb7bd3d61d57e6afcdfc2b65#diff-7ae5a9093507568eabbf35c3b0665732R6)
```
 @@ -3,9 +3,10 @@
  buildscript {
      repositories {
          jcenter()
 +        google()
      }
      dependencies {
 -        classpath 'com.android.tools.build:gradle:2.2.3'
 +        classpath 'com.android.tools.build:gradle:3.0.1'
  
          // NOTE: Do not place your application dependencies here; they belong
          // in the individual module build.gradle files
 @@ -20,5 +21,6 @@ allprojects {
              // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
              url "$rootDir/../node_modules/react-native/android"
          }
 +        google()
      }
  }
```

3  [android/gradle/wrapper/gradle-wrapper.properties](https://github.com/msand/AwesomeProject/commit/fe0e96874f9c9efbbb7bd3d61d57e6afcdfc2b65#diff-8c020fe060099cf8b2a337de2c45efb8R6)
```
@@ -1,5 +1,6 @@
 +#Mon Jan 29 13:59:51 EET 2018
  distributionBase=GRADLE_USER_HOME
  distributionPath=wrapper/dists
  zipStoreBase=GRADLE_USER_HOME
  zipStorePath=wrapper/dists
 -distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
 +distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

**Comment by pravinraut809** [comment]
Heyy , can u get me any code for react native phone authentication.. all on
internet is not working for me

**Comment by msand** [comment]
@pravinraut809 This seems quite unrelated. Please try google and stackoverflow etc.

**Comment by msand** [comment]
I've remove all dependencies and aligned the versions with react-native init. This shouldn't be an issue anymore.
