### ISSUE TITLE
SVG view larger than 8192px stops rendering

### ISSUE THREAD

**Issue by julienfouilhe** [react-native-community/react-native-svg#468]
I wonder if this is a react-native-svg problem or an iOS limitation, but I thought I would still warn you about it.

If I take this code from the README file, everything works fine:

```
<Svg height="100" width="100">
    <Circle cx="50" cy="50" r="45" stroke="blue" strokeWidth="2.5" fill="green" />
    <Rect x="15" y="15" width="70" height="70" stroke="red" strokeWidth="2" fill="yellow" />
</Svg>
```

Now if I only change the width to 8193 (it works up until 8192, at least in my simulator), it stops rendering the Circle and the Rect (the view itself seems to be rendered, since if I put a background color to the Svg component, the color appears):

```
<Svg height="100" width="8193">
    <Circle cx="50" cy="50" r="45" stroke="blue" strokeWidth="2.5" fill="green" />
    <Rect x="15" y="15" width="70" height="70" stroke="red" strokeWidth="2" fill="yellow" />
</Svg>
```

I'm guessing this is some sort of overflow, but I'm not sure if it comes from RNSVG.

**Comment by aish1550** [comment]
Hiya, did you find a fix for this?

**Comment by julienfouilhe** [comment]
@aish1550 Nope, using a very dirty trick, where I have this fixed width SVG, and I translate it with the scrollView, and I do the reverse translation on the content on the SVG... Not ideal but at least it works.

**Comment by lisbakke** [comment]
@julienfouilhe could you share the trick you used? I'm seeing this issue, as well.

To be more specific, **2048 pixel width is FINE**. Anything greater, e.g. 2049 pixel width, does not render.

**Comment by dustinsavery** [comment]
Weird, I'm seeing the issue, but at 5461px width (fine) and 5462px (missing). I don't believe this library uses ART.

**Comment by lisbakke** [comment]
@dustinsavery Maybe it has to do with device size? The width of the device I'm using I'm pretty sure is 360px. How about you?

**Comment by lisbakke** [comment]
For anyone that wants a workaround for this you can draw your surface twice and make it appear that it's one surface. e.g.

```          <RN.View style={[styles.subContainer, {height, width: FULL_WIDTH}]}>
            <RN.ART.Surface width={FOUR_WIDTH} height={height} style={{backgroundColor: 'transparent'}}>
              <RN.ART.Group x={0} y={0}>
                <RN.ART.Shape
                  d={linePath}
                  strokeWidth={0}
                  fill={fill}
                />
              </RN.ART.Group>
            </RN.ART.Surface>
            <RN.ART.Surface width={SCREEN_WIDTH * 3} height={height} style={{backgroundColor: 'transparent'}}>
              <RN.ART.Group x={-FOUR_WIDTH} y={0}>
                <RN.ART.Shape
                  d={linePath}
                  strokeWidth={0}
                  fill={fill}
                />
              </RN.ART.Group>
            </RN.ART.Surface>```

**Comment by msageryd** [comment]
I have found that using a very large Svg element takes up a lot of memory. It seems that Svg takes almost double the amount of memory it takes to show a jpg image of the same size. On top of that there is a nasty leak in RNSVG #278. 

The Svg not rendering is probably memory related. The same thing happens when you try to render very large images.

I'm now using a screen sized Svg element and transform my content to match the scroll position. It works great.
