### ISSUE TITLE
No component found for view with name "RNSVGPath"

### ISSUE THREAD

**Issue by TuKDoan** [react-native-community/react-native-svg#470]
I've been troubleshooting for hours with no luck.

With clean installs I receive this error while building :
 The following build commands failed:
```
CompileC /Users/tukdoan/equinox/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGTSpan.o Text/RNSVGTSpan.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
These are the lines I'm running 
```
import { VictoryBar } from "victory-native";

....

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <VictoryBar/>
      </View>
    );
  }
}
```

And this in the debugger : 

![image](https://user-images.githubusercontent.com/32083324/31262464-be4b3b8e-aa20-11e7-99cd-2c49460cd8b4.png)

This only happens after I do react-native link react-native-svg , before that it builds fine.

I have tried moving the RNSVG xcode file to every possible library, I have done tons of reinstalls. 

I can't just seem to get it to work.
Versions:
react-native-cli: 2.0.1
react-native: 0.49.1

Thank you.

**Comment by chris-mcleod** [comment]
downgraded to 5.4.1 for now

**Comment by nicolas-yaros** [comment]
apparently react-native link adds all targets to the ios target even if they are meant for tvOS

to get your app running remove the -tvOS.a file from link binary with libraries 

Source: https://github.com/oblador/react-native-vector-icons/issues/461

worked for me

**Comment by ziyafenn** [comment]
@nicolas-yaros  i don't even have it in my linked libraries, still getting the error
![screenshot 2017-10-17 14 47 33](https://user-images.githubusercontent.com/314302/31665747-3422bb66-b34a-11e7-8a09-b9396dfee4a8.png)

**Comment by msand** [comment]
@ziyafenn have you run react-native link ? Otherwise, try linking manually

**Comment by ziyafenn** [comment]
@msand yes sure! It was working previously, but now when i run it, doesn't work. 

Here i'm getting this error in my console:

`Warning: Native component for "RNSVGSvgView" does not exist`

**Comment by msand** [comment]
@ziyafenn Hmm, I can't see libRNSVG.a in your linked libraries, are you using cocoapods?

**Comment by ziyafenn** [comment]
Nope, i use react-native-svg-uri

**Comment by ziyafenn** [comment]
Nope, no cocoapods...

**Comment by ziyafenn** [comment]
i went to the git and downloaded the old xcode project, there i had it... Dunno how it got removed. I'll try again with the old xcode file

**Comment by ziyafenn** [comment]
Okay, somehow this library it was not in xcode project. Uninstalling packages and deleting "build" folder from ios helped solving issue

**Comment by oliviachang29** [comment]
I have libRNSVG.a in my linked libraries but no -tvOS.a. Still getting the error: 
![screen shot 2017-10-27 at 4 14 38 pm](https://user-images.githubusercontent.com/15709895/32128368-f463b1ac-bb31-11e7-934c-2328b32930fe.png)
I'm trying to use victory-native as well.

**Comment by msand** [comment]
@oliviachang29 Do you have $(SRCROOT)/../node_modules/react-native-svg/ios in "Header Search Paths" in recursive mode? And have you rebuilt your native bundle after linking the library?

**Comment by oliviachang29** [comment]
@msand I have react-native-svg in my header search paths, and I deleted the build folder and ran `react-native run-ios` again. Still didn't work.

**Comment by samrose3** [comment]
Getting the same error as well no matter if I am using Victory UI or just React Native SVG.
I don't have a -tvOS.a binary, but nor am I seeing a libRNSVG.a binary in my project (even after linking `react-native link react-native-svg` explicitly).

Also tried re-linking and rebuilding `ios/build`. No luck ☹️ 

<img src="https://user-images.githubusercontent.com/11774595/32699480-8c7d624a-c784-11e7-8e4a-d878a92e3f19.png" width="400" />

**Comment by wbattel4607** [comment]
Same issue. `No component found for view with name "RNSVGPath"` on a fresh install & link.

react 16.0.0
react-native 0.50.4
react-native-svg 6.0.0

```
import Svg, { Path } from 'react-native-svg';
```

```
<Svg width={500} height={75}>
    <Path stroke="none" fill="rgb(255, 255, 255)" d="M 500,20 L 500,75 0,75 0,20 C 0,8.95 111.93,-0 250,-0 388.07,-0 500,8.95 500,20 Z M 500,20" />
</Svg>
```

**Comment by Yalaouf** [comment]
What did you changed with NPM and Cocoapods to make it work ? I have the same problems with RNSVGView et RNSVGPath... Still can't solve the problem...

**Comment by Salinn** [comment]
Ran into this issue as well with a brand new project. Using React: 16, RN: 0.51.0, victory-native: 0.16.1 and react-native-svg: 6.0.1-rc.1.

**Comment by dustinsavery** [comment]
@wbattel4607 any additional information you can provide with regards to your "fiddling" would be helpful. I have seen the reports on this, but it doesn't appear to happen consistently.

**Comment by wbattel4607** [comment]
@dustinsavery I downgraded from 6.0.0 to 5.5.1, reinstalled my node modules, deintegrated cocoapods, reinstalled cocoapods, and re-linked everything.

The README suggests you can use 6.0.0 with RN 0.50.4, which may be true but also may have been the problem- I'm not sure.

**Comment by dustinsavery** [comment]
hmm. so it sounds like the fix was to downgrade. I've used `6.0.0` on a clean project (which was using `0.50.2` and it seemed to work for me using the example code. Not sure what I did differently though. I'll try again on a new project and see if I have issues.

**Comment by msand** [comment]
I've tried this multiple times but can't replicate. Please provide a full replication. Closing for now.

**Comment by gwenf** [comment]
I had to manually link `libRNSVG.a` in Xcode:

<img width="724" alt="screen shot 2018-04-09 at 9 46 47 pm" src="https://user-images.githubusercontent.com/10039233/38531796-bc4b2e8c-3c3f-11e8-8595-dabbfd2e790f.png">

Then I closed everything, re-ran `react-native run-ios`, and then it worked.

**Comment by AtNovember** [comment]
I got the same trouble for android

tryed to do this way https://stackoverflow.com/questions/47672941/invariant-violation-native-component-for-rnsvgsvgview-does-not-exist?rq=1

but successless =(

**Comment by omarqe** [comment]
@gwenf Thanks, that works!

**Comment by OKNoah** [comment]
Just sharing my mistake: I was linking my `*.a` files in the `*.xcodeproj`s under Libraries. Didn't realize I should put them in the main project's "Link Binary With Libraries" section. Silly mistake :P

**Comment by frogThanos** [comment]
I know this issue is closed but I solved it by doing `cd ios/`, I deleted my `Podfile.lock` and then ran `pod install`. After that `pod 'RNSVG', :path => '../node_modules/react-native-svg'` appeared in my `Podfile`. I also tried running `react-native link react-native-svg` but that just didn't work for me.

 "react": "^16.3.2"
 "react-native": "0.55.3"
  "react-native-svg": "^9.4.0"

Good Luck! 😃

**Comment by AtesDANIS** [comment]
> I know this issue is closed but I solved it by doing `cd ios/`, I deleted my `Podfile.lock` and then ran `pod install`. After that `pod 'RNSVG', :path => '../node_modules/react-native-svg'` appeared in my `Podfile`. I also tried running `react-native link react-native-svg` but that just didn't work for me.
> 
> "react": "^16.3.2"
> "react-native": "0.55.3"
> "react-native-svg": "^9.4.0"
> 
> Good Luck! 😃

thnx man, worked
