### ISSUE TITLE
PerformanceBezier/PerformanceBezier.h not found

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-svg#471]
Xcode doesn't build on release mode.

![image](https://user-images.githubusercontent.com/619186/31263481-e0c870d8-aa38-11e7-8907-0a292f86d348.png)

react-native-svg v6.0.0-rc1

**Comment by brunolemos** [comment]
Turns out `yarn` doesn't support submodules (yarnpkg/yarn#1488),
so running `npm install` instead of `yarn` did the trick.

**Comment by dk0r** [comment]
I used yarn exclusively to build RC1 into a fresh project without any issue:
However, I didn't use xcode to build directly:
 
```
$: react-native init test
$: cd test
$: yarn add react-native-svg
$: react-native link
$: react-native run-ios
``` 
 
The build tested fine on both android and iOS.

**versions**:
`xcode@9.0`
`yarn@1.1.0`
`react-native-svg@6.0.0-rc1`
`macOS@10.13`

**Comment by brunolemos** [comment]
@dk0r did you test on release build? I didn't get the error on debug build.
PS: I'm using xcode 9.1 beta.
