### ISSUE TITLE
Anyone using RN 0.49 / should I just ignore the errors?

### ISSUE THREAD

**Issue by hugows** [react-native-community/react-native-svg#472]
Hi ,

I'd like to understand if you folks are just using the latest react with svg and ignoring errors (unmet peer dependecy etc), or if I really, really  should stay in react-native 0.46.0 with 16.0.0-alpha.12 ?

I ask because I'm always expecting new versions of RN with speed improvements, etc.

TIA

**Comment by vlad-zhukov** [comment]
I am using v5.4.1 with `react-native@0.49` just fine.

**Comment by msand** [comment]
If it doesn't crash and renders correctly it's probably fine ;)
