### ISSUE TITLE
Create big size SVG

### ISSUE THREAD

**Issue by agungjk** [react-native-community/react-native-svg#474]
Can i create big size svg so element not cropped ?
like 
width = 4096 
and
height= 1024

**Comment by msageryd** [comment]
Yes, you can. But I'd advice against it. Your large svg will eat a lot of memory (more than the same sized jpg would eat). As of now there is also a bug so you won't get that memory back when you unmount your view. (#278)

Why do you need such large svg? I think that you can accomplish very much with a screen sized svg and working with transforms (scale and translate) to show the portion of your "virtual" large svg that you want.

I've been in many svg rabbit holes. The "very large svg"-hole was no success. The only use for a very large svg is when I need to generate a large sized png with good resolution. When I do this I need to care about not having a lot of other stuff in memory, i.e. no images (especially no transparent pngs)
