### ISSUE TITLE
cannot find symbol import android.support.v4.graphics.PaintCompat;

### ISSUE THREAD

**Issue by john1jan** [react-native-community/react-native-svg#476]
react-native-svg/android/src/main/java/com/horcrux/svg/TSpanShadowNode.java:23: error: cannot find symbol
import android.support.v4.graphics.PaintCompat;
                                  ^
  symbol:   class PaintCompat
  location: package android.support.v4.graphics

**Comment by adamwan92** [comment]
I am also facing this issue. Did you figure it out?

**Comment by john1jan** [comment]
no..i could not

**Comment by msand** [comment]
Have you tried building in android studio? seems you're missing this from your gradle configuration https://github.com/react-native-community/react-native-svg/blob/master/android/build.gradle#L38
And what SDK version are you using, have you tried 25? https://github.com/react-native-community/react-native-svg/issues/511#issuecomment-344567146

**Comment by msand** [comment]
I've removed appcompat from the dependencies, shouldn't be an issue anymore.

**Comment by suhabaobaid** [comment]
I am having the same problem still. 

package.json:
"react": "16.3.1",
"react-native": "0.55.2",
"react-native-svg": "^6.1.0"

android build.gradle:
compileSdkVersion 23
buildToolsVersion "23.0.1"

The error is in the TSpanShadowNode.java where it can't find that import package.

**Comment by suhabaobaid** [comment]
@john1jan were u able to overpass this issue?

**Comment by msand** [comment]
@suhabaobaid Can you try upgrading? The latest version shouldn't even have the dependency.
