### ISSUE TITLE
Feature request : UWP

### ISSUE THREAD

**Issue by sm2017** [react-native-community/react-native-svg#478]
Please add support for react-native-windows

Similar project https://github.com/liuhong1happy/react-native-windows-svg has many bugs like

https://github.com/liuhong1happy/react-native-windows-svg/issues/3
https://github.com/liuhong1happy/react-native-windows-svg/issues/5

**Comment by sm2017** [comment]
Any idea?

**Comment by msand** [comment]
Feel free to provide a PR, closing for now.
