### ISSUE TITLE
no view manager defined for class RNSVGPath

### ISSUE THREAD

**Issue by iiitmanikanta** [react-native-community/react-native-svg#479]
tried this basic example and getting this issue "No ViewManager defined for class RNSVGPath"
did the `react-native link react-native-svg` so many time,  and every time re build the app too.
```jsx
import React from 'react'
import Svg, {
  Path
} from 'react-native-svg'

export default class SvgExample extends React.Component {
  render() {
    return (
      <Svg height="100" width="100">
        <Path d="M 40 60 A 10 10 0 0 0 60 60" stroke="black" />
      </Svg>
    )
  }
}

```

additional info 
```json
     "react": "16.0.0-alpha.12",
    "react-native": "0.47.0",
    "react-native-svg": "^6.0.0-rc1"
```
`react-native-cli: 2.0.1`

![screenshot_2017-10-13-13-15-22-609_com graphs](https://user-images.githubusercontent.com/10682255/31535565-2c2741c2-b019-11e7-8200-e5043a18d3bc.png)

**Comment by ZeroZipZilch** [comment]
I'm gettomg the same errpr, using the following versions

```
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-svg": "^6.0.0-rc1",
```

**Comment by franckmaurin** [comment]
Same here.

**Comment by franckmaurin** [comment]
I resolved the same issue by using the version 5.4.2 of react-native-svg

**Comment by iqbalshirol** [comment]
I just created my activity as a sub-class of `ReactActivity` and it fixed this problem.

**Comment by msand** [comment]
This is failed linking issues, follow the manual linking instructions.
