### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by amorenew** [react-native-community/react-native-svg#483]
I wonder if there is RTL support like in android there is "`android:autoMirrored`" ?

**Comment by msand** [comment]
@amorenew I've done a bit of work on implementing the text layout algorithm from svg 2.0, which supports bidi text, but not currently working on it: https://github.com/react-native-community/react-native-svg/blob/6.0.0/android/src/main/java/com/horcrux/svg/TextLayoutAlgorithm.java
https://www.w3.org/TR/SVG2/text.html#TextLayoutAlgorithm
There is actually not that much left to it, only a few parts where the spec needs to be translated/expressed as code, and then taken into use in https://github.com/react-native-community/react-native-svg/blob/6.0.0/android/src/main/java/com/horcrux/svg/TSpanShadowNode.java

**Comment by amorenew** [comment]
@msand the text SVG could be png images but the main thing is mirroring the shapes to right

**Comment by msand** [comment]
If you want to mirror something, you can use transform translate and scale(-1,1) as in:



<svg width="100" height="100">
    <g transform="translate(50,0) scale(-1,1)">
        <rect width="5" height="5" />
        <text><tspan y="15" >abc</tspan></text>
    </g>
</svg>

https://jsfiddle.net/yeuj98au/
