### ISSUE TITLE
Limits file not found

### ISSUE THREAD

**Issue by akantsevoi** [react-native-community/react-native-svg#484]
Hi.
I've installed RNSVG via cocoapods. Also I've installed Folly library.
And in that case Folly has "Math.h" file and RNSVG linked on "math.h" file and I RNSVG tries wrong path. 
In RNSVGPathParser.m file I've changed `#import "math.h"` to `#import <math.h>`
And it works.
Could you explain is it a my bug or you should change this file?

Thank you.

**Comment by dustinsavery** [comment]
@akantsevoi Have you added the path to your Header Search Paths in Xcode? This would solve it without the need to change it to a framework import.

**Comment by msand** [comment]
Not sure about this really, will close this for now. Reopen if its still an issue.

**Comment by CusProjects** [comment]
@dustinsavery what exactly i must add to the Header Search Paths ?

**Comment by dustinsavery** [comment]
You need to make sure that all paths that have header files you're trying to use are listed. When Xcode compiles, it looks in all the paths specified, as well as the default library paths, and attempts to resolve all references made. So be sure that you have all RNSVG and Folly header paths listed in your Header Search Paths and it should compile just fine.

**Comment by CusProjects** [comment]
<img width="697" alt="screen shot 2018-04-03 at 12 32 07 pm" src="https://user-images.githubusercontent.com/14632593/38268343-188c1846-373b-11e8-8682-c0ad0673f913.png">
That's all my Header Search Paths, did i miss something?

**Comment by dustinsavery** [comment]
Depends, are you also using Folly like the OP? If so, you'd need that in there as well.

**Comment by oferRounds** [comment]
hey @dustinsavery could you please share what to add and where?
