### ISSUE TITLE
Rotation in iOS

### ISSUE THREAD

**Issue by renso3x** [react-native-community/react-native-svg#487]
Hi I have an issue with regards the rotation of the circle. I wanted it to be on the top to start with but rotation is not working on my end. 

Here is my gist for it.
https://gist.github.com/renso3x/38e4b120404bd7f57fa2dc90951978fc

Here's what it looks like.
![screen shot 2017-10-19 at 4 32 37 pm](https://user-images.githubusercontent.com/16775150/31761923-36fb8dec-b4ec-11e7-84a0-76749f540886.png)

**Comment by mikearche** [comment]
The property is called rotate not rotation.

**Comment by msand** [comment]
Rather, use the standard svg transform attribute and the rotate transform definition. Such as here e.g. https://github.com/magicismight/react-native-svg-example/pull/7/commits/e5616d29fc707da68ea895d02a633bf78a4dd495#diff-b241035fb407e61e7ec1900126acf94cR23
