### ISSUE TITLE
Is there an ETA for 6.0.0?

### ISSUE THREAD

**Issue by adrianboimvaser** [react-native-community/react-native-svg#488]

**Comment by msand** [comment]
You can install it using:
`npm i -S react-native-svg@6.0.0-rc1`
or
`npm i -S react-native-svg@https://github.com/react-native-community/react-native-svg.git#6.0.0`
or
`npm i -S react-native-svg@https://github.com/react-native-community/react-native-svg.git#be8797b`

Installation using yarn does not work, as there is a git submodule required now and only npm installs those.

**Comment by HilSny** [comment]
The current RNSVG has a submodule but its just the example so it still builds for me with yarn. It looks like that is similar for 6.0 unless I'm mistaken.

The biggest roadblock I see is that the buildsdk for android is set to 25 when most apps are at 23 (react native specifies 23.0 here under the tab "building your project with native code": https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by msand** [comment]
@HilSny I'm referring to the 6.0.0 branch and the PerformanceBezier library, which you can see here: https://github.com/react-native-community/react-native-svg/blob/6.0.0/.gitmodules#L5-L7

The SDK works fine with 25 and can even be upgraded to 26. 

If you have many dependencies you might even need to do it for all of them, and upgrade the gradle android build tools, and appcompat at the same time. 

This has given the best compatibility and stability for us so far, and significantly faster native build times (especially combined with the latest android studio preview version and beta/rc of gradle and build tools etc). Which is great for e.g. native debugging & bugfixing.

As long as you keep minSdkVersion at 16 its fine and you can make that higher as well if your user-base is on newer versions. The sdk mostly opens up new things, upgrade some others, and makes some changes to the permissions model, nothing to fear.

**Comment by HilSny** [comment]
Ah ok. I had unintentional consequences when I upgraded to target 23 because the way permissions were obtained changed. I have been wary every since but it looks like things work. 

For anyone else: I used this script for yarn and was able to get the submodules to install
```
"postinstall": "grep url node_modules/react-native-svg/.gitmodules | sed 's/.*= //' | while read url; do (cd node_modules/react-native-svg; git clone $url); done"
```

Now I just have the build failing on IOS with `mobile/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGTSpanManager.o ViewManagers/RNSVGTSpanManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

**Comment by adrianboimvaser** [comment]
@msand thanks, I was able to install 6.0.0-rc1, but I was expecting transformations to work in 6.0.0 (https://github.com/react-native-community/react-native-svg/pull/320) but it doesn't seem to be working.

This is how the SVG should look:
![image](https://user-images.githubusercontent.com/1104728/32071158-cb8a7860-ba64-11e7-89d2-d7728288b8ed.png)
This is how the SVG looks in my React Native app:
![image](https://user-images.githubusercontent.com/1104728/32071172-d7a3f05e-ba64-11e7-9e30-69cff161c455.png)
Is this just not implemented or am I missing something?
Thank you.

**Comment by msand** [comment]
@adrianboimvaser There might be bugs with it still, can you try using svgs (universal wrapper around react-native-svg and web svg), and make sure it renders correctly in an evergreen web browser at least, with the same dom structure and attribute values as you're using now. 

Especially, I suspect multiple transform definitions in one transform attribute might be broken at least and possibly related. The tests I have in https://github.com/msand/newproject/ and https://github.com/msand/react-native-svg-example seem to be working correctly.

**Comment by brunolemos** [comment]
This is happening after latest commits on 6.0.0 branch:

`Cannot read property 'children' of undefined`
![image](https://user-images.githubusercontent.com/619186/32506924-09aed750-c3cd-11e7-9df2-56222fa80b55.png)

**Comment by magicismight** [comment]
6.0.0 has been released.
