### ISSUE TITLE
`<Stop>` 'offset' prop must be string

### ISSUE THREAD

**Issue by FireyFly** [react-native-community/react-native-svg#491]
The `<Stop>` element has a prop `offset`, which appears to currently have to be a string (containing a number or percentage)--allowing a pure number value for the prop (as with e.g. `opacity`) makes a lot of sense to me, especially with prop values computed on-the-fly.

I currently work around the problem with a `.toString()`, but that feels a bit ugly. The problem is the invocation of the `percentToFloat` helper, which assumes the input is a string (reasonable) but is invoked regardless of whether the prop value is a number or string (a number should probably just be assigned directly). See https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractGradient.js#L21. Should be easy to fix, but being unfamiliar with the codebase and busy with other projects it'd be great if someone more familiar with the code could make the change and make sure nothing breaks. :)

**Comment by msand** [comment]
Fixed in master.
