### ISSUE TITLE
Image not resized properly when importing filesystem asset on Android.

### ISSUE THREAD

**Issue by tgevaert** [react-native-community/react-native-svg#494]
Hi All,  Thanks for working on this Library!

I struggled finding a proper title for this issue.  I'm relatively new to react-native & svg so bare with me if I'm making an obvious mistake.

I'm trying to do a simple image resize and circle crop.  I followed the [example](https://github.com/react-native-community/react-native-svg#image) quite closely.  

```javascript
const CircleOverlay = ({size, uri}) => {
    const height = size;
    const width = size;
    const cp = height / 2;
    const r = cp - 2;
    return (
      <Svg
        height={height}
        width={width}
      >
        <Defs>
          <ClipPath id="circleclip">
            <Circle
              cx={cp}
              cy={cp}
              r={r}
            />
          </ClipPath>
        </Defs>
        <Image
          width={width}
          height={height}
          href={{uri}}
          preserveAspectRatio="xMidYMid slice"
          clipPath="url(#circleclip)"
        />
        <Circle
          cx={cp}
          cy={cp}
          r={r}
          fillOpacity="0"
          stroke="white"
          strokeWidth="2.5"
        />
      </Svg>
    );
  };
```

The problem is that the image gets resized, but the aspect ratio is not preserved.  For reference:

Input image:

![9a5fb588-743a-4c79-bf65-f2cde41f30c7](https://user-images.githubusercontent.com/99748/32298369-8ef2c8c6-bf28-11e7-91f4-3c8d6ebd2388.jpg)

Resized and circle cropped version:
![screenshot_1509571317](https://user-images.githubusercontent.com/99748/32298672-4708357c-bf29-11e7-93b3-0abfff0d0569.png)

Note that the Green Square ends up as a rectangle.  If you measure the distortion, it turns out that the output image is distorted by a factor of the input image's aspect ratio.  

While trying to debug this problem, I tried every combination of viewBox and height/width and preserveAspectRatio values I could think of.

I believe the problem stems from how the image location is handled.  The `uri` I pass is formed like `file:///some/local/path.jpg` and works fine with the native Image component.

In [ImageShadowNode](https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/ImageShadowNode.java#L80) the `setSrc` function expects to find `height` and `width` values in the `src` map.  If they're not included, the `mImageRatio` property gets set to `0f`.

When the `doRender` function is called, if `mImageRatio` is `0f`, the ensuing transform doesn't take into account the original Image's aspect ratio.

If I patch the [RNSVGImage](https://github.com/react-native-community/react-native-svg/blob/master/elements/Image.js#L54) component to explicitly return an image size from `resolveAssetSource` like so:
`src={Object.assign({width: 640, height:480}, resolveAssetSource(props.href))}`

I end up with the proper aspect ratio in my generated SVG image:
![screenshot_1509572844](https://user-images.githubusercontent.com/99748/32299679-d8ea455e-bf2c-11e7-8dcf-adc3d8ddd63b.png)

I don't know how to go about fixing this behaviour when I don't know the original image's aspect ratio beforehand.

Thanks for your time!
-Tim

**Comment by tgevaert** [comment]
As an update: if I explicitly set the height and width of the image in the href property, the resulting SVG has the correct aspect ratio.  Perhaps it would help to document this in case others are stumped.

**Comment by msand** [comment]
Can you try with the latest version and see if its fixed?

**Comment by msand** [comment]
Haven't seen this issue myself, and there's no response nor replication. Closing.
