### ISSUE TITLE
undefined is not an object (evaluating 'validAttributes[propKey]')

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-svg#498]
Facing this on `6.0.0-rc12`:
`undefined is not an object (evaluating 'validAttributes[propKey]')`
`Cannot read property 'children' of undefined`

<div>
<img src="https://user-images.githubusercontent.com/619186/32507861-c377954e-c3cf-11e7-9224-edfa0b789f41.png" width="300" />
<img src="https://user-images.githubusercontent.com/619186/32506924-09aed750-c3cd-11e7-9df2-56222fa80b55.png" width="300" />
</div>

react-native 0.48.2

**Comment by pietro909** [comment]
Same error, I found that it happens using `LinearGradient`, `RadialGradient`, `Ellipse`.

**Comment by brunolemos** [comment]
Upgrading to react native 0.50.1+ seems to fix it for me. @pietro909 can you confirm?

**Comment by pietro909** [comment]
Upgrading is not an option, for now, we switched back to 5.4.2 and it works.

I have the feeling that it would fix it, though.

**Comment by brunolemos** [comment]
@serratus did we introduce this with #486? :(

**Comment by serratus** [comment]
@brunolemos I guess the fallback is not working properly for everyone using RN < 0.50. Do you have a different idea how to tackle that?

**Comment by brunolemos** [comment]
Checkin it

**Comment by brunolemos** [comment]
By bad, fixed on https://github.com/react-native-community/react-native-svg/pull/499
