### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'props.href.match') 

### ISSUE THREAD

**Issue by trinadhkoya** [react-native-community/react-native-svg#500]
TypeError: undefined is not an object (evaluating 'props.href.match') This error is located at: in Use

**Comment by msand** [comment]
Can you post a replication of this? Or did you resolve the issue? Can this be closed?

**Comment by Husak93** [comment]
the same, I covert svg to `react-native-svg` view, but original file has `<mask>` tag and I can't woth withoute that element. And some issue with xmlns:xlink...

**Comment by xtrycatchx** [comment]
The problem is due to href props not being passed. Fix i use in my case is like this:

from
```JSX
export default () => (
  <Svg xmlnsXlink="http://www.w3.org/1999/xlink" width={134} height={134}>
    ...
      <G strokeLinecap="round">
        <Use fill="#000" filter="url(#c)" xlinkHref="#d" />
        <Use stroke="#FFF" strokeWidth={6} xlinkHref="#d" />
      </G>
    ...
  </Svg>
)
```

to
```jsx
export default () => (
  <Svg xmlnsXlink="http://www.w3.org/1999/xlink" width={134} height={134}>
    ...
      <G strokeLinecap="round">
        <Use fill="#000" filter="url(#c)" href="#d"  xlinkHref="#d" />
        <Use stroke="#FFF" strokeWidth={6} href="#d" xlinkHref="#d" />
      </G>
    ...
  </Svg>
)
```

**Comment by pascaloliv** [comment]
@winghouchan Definitely ! 👏  I'm pretty hyped by your last answer with the potential diff. Could be a great thing if you open a PR to cover the issue #500 !

**Comment by msand** [comment]
@winghouchan Sounds good, looking forward to your PR 😄

**Comment by VincentCATILLON** [comment]
Looking for your PR too ;)
