### ISSUE TITLE
Incorrect code published to npm as 6.0.0

### ISSUE THREAD

**Issue by dantman** [react-native-community/react-native-svg#505]
According to the commit log, rnsvg's version was bumped to 6.0.0 (https://github.com/react-native-community/react-native-svg/commit/dcf0e5af2bc7375a340681ce2d9f60ab14c5da84) **after** the fix for RN 0.50 that bumped the `color` dependency from `^0.11.1` to `^2.0.1` (https://github.com/react-native-community/react-native-svg/commit/416105aca819d15e145fc8fec61e473de5f73964).

However the `6.0.0` on npm appears to still depend on the `0.11.1` version of `color` that breaks react-native 0.50.

```shell
cd /tmp
$ npm i react-native-svg
...

+ react-native-svg@6.0.0
added 77 packages in 6.215s
$ npm list color
/private/tmp
└─┬ react-native-svg@6.0.0
  └── color@0.11.4 
```

The git repo appears to be correct.
```
$ rm -rf node_modules/ package-lock.json
$ npm i https://github.com/react-native-community/react-native-svg.git
...

+ react-native-svg@6.0.0
added 78 packages in 4.453s
$ npm list color
/private/tmp
└─┬ react-native-svg@6.0.0 (git+https://github.com/react-native-community/react-native-svg.git#dcf0e5af2bc7375a340681ce2d9f60ab14c5da84)
  └── color@2.0.1 
```

We need a `6.0.1` release with this bug fix included.

**Comment by msand** [comment]
New versions have been released. Closing this.
