### ISSUE TITLE
Progress on loading image from URL?

### ISSUE THREAD

**Issue by sejr** [react-native-community/react-native-svg#510]
I would like to use this library to load SVG resources I have already designed. Is that possible yet?

**Comment by dustinsavery** [comment]
It should be. Have you run into issues?

**Comment by sejr** [comment]
@dustinsavery  No, I just couldn't find the API for it. What prop would I use? `src`?

**Comment by dustinsavery** [comment]
Sorry, I misunderstood. This library is specifically for creating SVG components, not loading in from external sources. On projects I've worked on with extensive SVG files, I run them through a build script I created to convert them into react components that use the types from this library.

**Comment by msand** [comment]
@sejr Try this https://github.com/matc4/react-native-svg-uri

**Comment by sejr** [comment]
@dustinsavery Are you able to share that build script? @msand I saw this but I am using CRNA and I have not ejected from the Expo container stuff, so I can't link that library at this point.

**Comment by dustinsavery** [comment]
@sejr Possibly, I'll have to see if I can piece together the parts that do it. It's currently in an automated system

**Comment by msand** [comment]
@dustinsavery 
react-native-svg-image seems to work with Expo https://snack.expo.io/@msand/test-svg-image (uses a webview)
while react-native-svg-uri seems to crash with a Device: (2:771) Requiring unknown module "react-native-svg-uri". https://snack.expo.io/@msand/test-svg-uri
@brentvatne you know why Expo doesn't work with this pure javascript module?

**Comment by msand** [comment]
@sejr I patched it a bit and got react-native-svg-uri working with Expo now as well: https://snack.expo.io/@msand/test-svg-uri-patch

**Comment by msand** [comment]
I'll go ahead and close this for now. There is also https://github.com/target/react-native-svg-parser available.

**Comment by alvaroTech911** [comment]
Is there a way to load external images? I tried using react-native-svg-uri but that only works with svgs.
