### ISSUE TITLE
6.0.0 version in pod have lots mistake for ARC

### ISSUE THREAD

**Issue by glj0209** [react-native-community/react-native-svg#515]
This is the 'podfile':
pod 'RNSVG', :path => './RN/react-native-svg'

There are lots mistake for ARC, like
[bezierPathByFlatteningPath release];
[_bezierPathByFlatteningPath retain];

**Comment by ulisinn** [comment]
does an older version work? I can't get it to work at all when with cocoa pods.

**Comment by dustinsavery** [comment]
I use it with cocoa pods and swift with no issues. Can you be more specific about the issues? You are still allowed to call `retain` and `release` with ARC, they just aren’t required. But there are times when you don’t want the reference to be destroyed.

**Comment by msand** [comment]
@glj0209 I have a pull request fixing these issues: https://github.com/react-native-community/react-native-svg/pull/558

**Comment by msand** [comment]
Fixes have been published. Closing this now.
