### ISSUE TITLE
Scale prop doesn't work with ClipPath on Android only

### ISSUE THREAD

**Issue by mikeygee** [react-native-community/react-native-svg#517]
```
<Svg height="80" width="80">
    <Defs>
        <ClipPath id="clip">
            <Rect x="0" y="0" width="100%" height="100%" />
            <Path scale="2" d={somePath} />
        </ClipPath>
    </Defs>
    <Rect
        x="0"
        y="0"
        width="100%"
        height="100%"
        clipPath="url(#clip)"
        fill="#fff"
    />
</Svg>
```
On iOS, this scales up the path.
![image](https://user-images.githubusercontent.com/885069/32915599-47053380-cace-11e7-80a4-40d9abc5206d.png)

On Android, there is no effect.
![image](https://user-images.githubusercontent.com/885069/32915608-50caff62-cace-11e7-9ff3-bc87f9252f82.png)

Outside of ClipPath, it works fine.

**Comment by ispiropoulos** [comment]
Same here. iOS works fine, android does not scale inside ClipPath

**Comment by Daavidaviid** [comment]
I encountered the same issue on the last version and the solution I found in my case was to put everything in a G component like this : <G scale={DESIRED_SCALE}> ... </G>
