### ISSUE TITLE
OutOfMemoryError 

### ISSUE THREAD

**Issue by justTalk** [react-native-community/react-native-svg#518]
I drew a lot of using SVG graphs, when I once all loading chart, can appear very to probability OutOfMemoryError, how can I optimize it

**Comment by szakhlypa** [comment]
Not sure if this is your case, but I also use a lot of text svg  elements, and in iOS after upgrade to 6.0.0 I got memory leaks. I have no experience in Objective-C, but with Instruments I traced leaks to https://github.com/react-native-community/react-native-svg/blob/master/ios/Text/RNSVGTSpan.m#L852 where there are "attrString" and "line" created, but not released. So I added this two strings before every return in that method and leaks are gone:
CFRelease(attrString);
CFRelease(line);

**Comment by msand** [comment]
@szakhlypa Great catch, my fault, I had no earlier experience in Obj-c either and put that together in a hurry. Would you like to set up a pull request?

**Comment by szakhlypa** [comment]
@msand Done, sorry for delay.
@justTalk Please check if this fix #521 resolves your problem and if not - please give more information about your case.
Also big thanks to all contributors of react-native-community

**Comment by dustinsavery** [comment]
This is fixed by #521. Closing this issue

**Comment by justTalk** [comment]
I found every SVG last drawing into the bitmap, and then draw to the real life, in the View of on the ordinary mobile phones, the size of a picture about 3 m, a total of 18 a page picture, so the memory problems, don't know if we can avoid the generation of bitmap in the implementation, because the bitmap is too of memory

**Comment by justTalk** [comment]
![1](https://user-images.githubusercontent.com/12739850/33759376-08063c1c-dc3d-11e7-80b5-6533e1f5c7af.PNG)
![2](https://user-images.githubusercontent.com/12739850/33759377-084192da-dc3d-11e7-9125-220928137a8a.PNG)
![3](https://user-images.githubusercontent.com/12739850/33759378-0873a20c-dc3d-11e7-9db1-56aafc63bcab.PNG)
I have modified the source code Canceled the draw on the bitmap this step, but I don't know whether this will be the problems

**Comment by ma-pe** [comment]
I am experiencing similar problems as @justTalk, also on Android. This issue shouldn't be closed. It was an Android Issue from the beginning (java.lang.OutOfMemoryError).

The provided fix is an iOS fix.

**Comment by lazaronixon** [comment]
Same here on android.
```
java.lang.OutOfMemoryError: 
 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
 
  at android.graphics.Bitmap.nativeCreate (Native Method)
 
  at android.graphics.Bitmap.createBitmap (Bitmap.java:975)
 
  at android.graphics.Bitmap.createBitmap (Bitmap.java:946)
 
  at android.graphics.Bitmap.createBitmap (Bitmap.java:913)
 
  at com.horcrux.svg.SvgViewShadowNode.drawOutput (SvgViewShadowNode.java:130)
 
  at com.horcrux.svg.SvgViewShadowNode.onCollectExtraUpdates (SvgViewShadowNode.java:120)
 
  at com.facebook.react.uimanager.ReactShadowNodeImpl.dispatchUpdates (ReactShadowNodeImpl.java:411)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:968)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:959)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:959)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:959)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:959)
 
  at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive (UIImplementation.java:959)
 
  at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy (UIImplementation.java:700)
 
  at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates (UIImplementation.java:654)
 
  at com.facebook.react.uimanager.UIManagerModule.onBatchComplete (UIManagerModule.java:665)
 
  at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete (NativeModuleRegistry.java:134)
 
  at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete (CatalystInstanceImpl.java:145)
 
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
 
  at android.os.Handler.handleCallback (Handler.java:739)
 
  at android.os.Handler.dispatchMessage (Handler.java:95)
 
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
 
  at android.os.Looper.loop (Looper.java:148)
 
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:192)
 
  at java.lang.Thread.run (Thread.java:818)
```

**Comment by andrewzey** [comment]
I too am getting a lot of these errors and crashes, and only on Android:

```
OutOfMemoryError
Failed to allocate a 69196812 byte allocation with 16777216 free bytes and 56MB until OOM
dalvik.system.VMRuntime in newNonMovableArray
android.graphics.Bitmap in nativeCreate
android.graphics.Bitmap in createBitmap at line 977
android.graphics.Bitmap in createBitmap at line 948
android.graphics.Bitmap in createBitmap at line 915
com.horcrux.svg.SvgViewShadowNode in drawOutput at line 115
com.horcrux.svg.SvgViewShadowNode in onCollectExtraUpdates at line 105
com.facebook.react.uimanager.ReactShadowNodeImpl in dispatchUpdates at line 325
com.facebook.react.uimanager.UIImplementation in applyUpdatesRecursive at line 968
com.facebook.react.uimanager.UIImplementation in applyUpdatesRecursive at line 95917
com.facebook.react.uimanager.UIImplementation in updateViewHierarchy at line 700
com.facebook.react.uimanager.UIImplementation in dispatchViewUpdates at line 654
com.facebook.react.uimanager.UIManagerModule in onBatchComplete at line 663
com.facebook.react.bridge.NativeModuleRegistry in onBatchComplete at line 136
com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback in onBatchComplete at line 145
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 751
android.os.Handler in dispatchMessage at line 95
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 31
android.os.Looper in loop at line 154
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3 in run at line 194
java.lang.Thread in run at line 762
```


```
OutOfMemoryError
Failed to allocate a 69196812 byte allocation with 16777216 free bytes and 56MB until OOM
dalvik.system.VMRuntime in newNonMovableArray
android.graphics.Bitmap in nativeCreate
android.graphics.Bitmap in createBitmap at line 977
android.graphics.Bitmap in createBitmap at line 948
android.graphics.Bitmap in createBitmap at line 915
com.horcrux.svg.SvgViewShadowNode in drawOutput at line 115
com.horcrux.svg.SvgViewShadowNode in onCollectExtraUpdates at line 105
com.facebook.react.uimanager.ReactShadowNodeImpl in dispatchUpdates at line 325
com.facebook.react.uimanager.UIImplementation in applyUpdatesRecursive at line 968
com.facebook.react.uimanager.UIImplementation in applyUpdatesRecursive at line 95917
com.facebook.react.uimanager.UIImplementation in updateViewHierarchy at line 700
com.facebook.react.uimanager.UIImplementation in dispatchViewUpdates at line 654
com.facebook.react.uimanager.UIManagerModule in onBatchComplete at line 663
com.facebook.react.bridge.NativeModuleRegistry in onBatchComplete at line 136
com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback in onBatchComplete at line 145
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 751
android.os.Handler in dispatchMessage at line 95
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 31
android.os.Looper in loop at line 154
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3 in run at line 194
java.lang.Thread in run at line 762
```

**Comment by akshgods** [comment]
same issue:
com.horcrux.svg.SvgView.drawOutput
SvgView.java, line 248
java.lang.OutOfMemoryError: Failed to allocate a 1949844 byte allocation with 1068416 free bytes and 1043KB until OOM

Stack traces:

dalvik.system.VMRuntime.newNonMovableArray VMRuntime.java
android.graphics.Bitmap.nativeCreate Bitmap.java
android.graphics.Bitmap.createBitmap Bitmap.java:879
android.graphics.Bitmap.createBitmap Bitmap.java:856
android.graphics.Bitmap.createBitmap Bitmap.java:823
com.horcrux.svg.SvgView.drawOutput SvgView.java:248
com.horcrux.svg.SvgView.onDraw SvgView.java:104
android.view.View.draw View.java:17120
android.view.View.updateDisplayListIfDirty View.java:16102
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ViewGroup.recreateChildDisplayList ViewGroup.java:3792
android.view.ViewGroup.dispatchGetDisplayList ViewGroup.java:3772
android.view.View.updateDisplayListIfDirty View.java:16065
android.view.ThreadedRenderer.updateViewTreeDisplayList ThreadedRenderer.java:656
android.view.ThreadedRenderer.updateRootDisplayList ThreadedRenderer.java:662
android.view.ThreadedRenderer.draw ThreadedRenderer.java:770
android.view.ViewRootImpl.draw ViewRootImpl.java:2883
android.view.ViewRootImpl.performDraw ViewRootImpl.java:2691
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2298
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1306
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:6579
android.view.Choreographer$CallbackRecord.run Choreographer.java:871
android.view.Choreographer.doCallbacks Choreographer.java:683
android.view.Choreographer.doFrame Choreographer.java:619
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:857
android.os.Handler.handleCallback Handler.java:751
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:154
android.app.ActivityThread.main ActivityThread.java:6316
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:872
com.android.internal.os.ZygoteInit.main ZygoteInit.java:762

Most affected devices
P9 lite
23.8%
Galaxy A5(2016)
19.0%
Moto G(4) Plus
4.8%
Others

Most affected OS
7.0
52.4%
6.0.1
28.6%
6.0
9.5%

**Comment by isaachinman** [comment]
Also seeing OOMs on Android. Why was this issue closed without resolution?
