### ISSUE TITLE
transform="rotate(a, x, y)" is not supported

### ISSUE THREAD

**Issue by AlgoTrader** [react-native-community/react-native-svg#519]
transform rotate may get either one or three parameters:

> rotate(a [x y])
> This transform definition specifies a rotation by a degrees about a given point. If optional parameters x and y are not supplied, the rotate is about the origin of the current user coordinate system. 
> ...
> If optional parameters x and y are supplied, the rotate is about the point (x, y). The operation represents the equivalent of the following transform definitions list: translate(x, y) rotate(a) translate(-x, -y).

the lib currently supports concise form of rotate with the single param and ignores the x and y

![image](https://user-images.githubusercontent.com/1556262/32946198-a40e33cc-cba7-11e7-8f74-bc36372559a1.png)

Unfortunately, there are plenty of SVGs that use the "full" form, especially produced by SVG optimizers like svgo. Now I have pain of fixing such the cases manually

**Comment by AlgoTrader** [comment]
I have to go into some math. For simple case matrix is following

![image](https://user-images.githubusercontent.com/1556262/32947193-b2e297a4-cbab-11e7-87c8-2f6da0bf92b4.png)

For the three parameters case, the matrix is somewhat more complex:

![image](https://user-images.githubusercontent.com/1556262/32947088-444ae602-cbab-11e7-88e5-0bcd7139995b.png)

The code may be fixed to handle two cases:
if (transLst.length === 4) {
retval.matrix = [];
} else if(transLst.length === 2) {
}

**Comment by AlgoTrader** [comment]
I have added rotate(a x y) support

before fix
![image](https://user-images.githubusercontent.com/1556262/32950919-2654e8c4-cbb9-11e7-9e95-dbd73c055f9e.png)

after fix
![image](https://user-images.githubusercontent.com/1556262/32950933-2dcb9102-cbb9-11e7-81c2-ec861d5133d7.png)

**Comment by msand** [comment]
Rotate support has been published. Thanks for the work and PR anyway! I'll go ahead and close this.
