### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by dantman** [react-native-community/react-native-svg#522]
Is there anyone left to maintain this library?

react-native-svg has been broken in the latest react-native for over a week (npm publishing mistake, OOM errors, and color conversion error) and there hasn't been any response to issues or emails.

We need at least someone in the community who can merge PRs and publish fixes to npm.

**Comment by dustinsavery** [comment]
There are a few of us, yes. If you'd like to help, see this post: https://github.com/react-native-community/react-native-svg/pull/486#issuecomment-342358990

**Comment by AlgoTrader** [comment]
I have switched to own fork as I can fix it asap, the reaction to bugs and PRs is rather slow.

**Comment by dustinsavery** [comment]
@algotrader Apologies, we’re trying to get more help. This is a community repo, so we depend on community help.

**Comment by AlgoTrader** [comment]
I understand. I have decent JS skills and Android. I can help with JS code and resolving Android issues

**Comment by dustinsavery** [comment]
That would be much appreciated! Please see [this post](https://github.com/react-native-community/react-native-svg/pull/486#issuecomment-342358990)

**Comment by dustinsavery** [comment]
Ok, went through outstanding PRs and got quite a few of them merged. @dantman Going to close this now that we have some traction going forward :)
