### ISSUE TITLE
TextPath render wrong position with Chinese.

### ISSUE THREAD

**Issue by ljunb** [react-native-community/react-native-svg#525]
Thanks for such a good component!
I try to render a component that similar to the dashboard, and there are some text contents. But I got the follow issue:

![bad](https://user-images.githubusercontent.com/13927749/33119103-e49bcdbe-cfa8-11e7-99e9-f50a83951ea0.jpeg)

Obviously the text '有钱任性' has render in wrong position, it confuse me when I try to render other characters, because it is all right everything:

![normal](https://user-images.githubusercontent.com/13927749/33119407-dfc12694-cfa9-11e7-85fe-937a7311840e.jpeg)

So, how do I fix it?☕️☕️ 

Other informations:
react-native: 0.50.3
Platform: iOS 11
react-native-svg: 6.0.0

**Comment by ljunb** [comment]
Perhaps is the '任' character causes this issue. 😶😶

![bad2](https://user-images.githubusercontent.com/13927749/33120296-9ae72200-cfac-11e7-9ed1-1304e694d7df.jpeg)

**Comment by dustinsavery** [comment]
Apologies, I'm not understanding your issue.

**Comment by msand** [comment]
@ljunb seems it might be a kerning related issue. A workaround might be to wrap the problematic character in <tspan dx="10px">任</tspan>

**Comment by ljunb** [comment]
@msand Just as you said, use `TSpan` can fix this issue, thx!!

**Comment by msand** [comment]
@ljunb I found an issue in the handling of ligatures on ios, and suspect this issues might have been related. We're you having issues on both platforms or only one? Could you try my pull request and see if you can remove the workaround now? https://github.com/react-native-community/react-native-svg/pull/558

**Comment by ljunb** [comment]
@msand ok, I will try it tonight with your suggestion

**Comment by ljunb** [comment]
@msand I have tried your PR, but each version of the performance is still different: 
![demo](https://user-images.githubusercontent.com/13927749/34476574-e30ea9dc-efcc-11e7-85e4-db2370e3cc97.jpeg)
only happen on iOS.

**Comment by msand** [comment]
I figure, on iOS at least, the kerning table lookup still uses the non-ligature glyphs, might be related to that. But quite strange that it is version dependent, seems it could be a native iOS CoreText issue.

**Comment by windhost** [comment]
Use 5.5.1

**Comment by benevbright** [comment]
The same problem occurs with using Korean letters on iOS only.

react-natve-svg ver: 6.3.1
react-native: 0.55.4

**Comment by benevbright** [comment]
Thanks @windhost 
5.5.1 is working fine for workaround.
