### ISSUE TITLE
Svg not show after change page

### ISSUE THREAD

**Issue by abaddonGIT** [react-native-community/react-native-svg#526]
If i load application on first time all svg images show good, but if a go to next page or back to the home page svg not showing or show but it is incorrect and this happens in real device on virtual device all work good. 

"react": "16.0.0",
"react-native": "0.50.4",
"react-native-svg": "^6.0.0"

Android api 4.4

Test svg component:
`
const Logo = props => (
<Svg width={props.width || 51.06} height={props.height || 56.97} viewBox="0 0 51.06 56.97">
  <Path fill={props.color || 'green'} class="cls-1" d="M18.52 57h3.22l.06-6.05A57.17 57.17 0 0 0 18.52 57zM21.81 18.75A76.23 76.23 0 0 0 12.18 33h3.44a60.27 60.27 0 0 1 6.19-8.68zM21.81 28.31c-.64.85-2.76 3.86-3.19 4.67h3.12c.06-.08.07-4.67.07-4.67zM21.81 10.78H0V33h9.7a80.46 80.46 0 0 1 12.1-16.53zM3.44 57h1.93a91.6 91.6 0 0 1 8.94-21.85h-3.25A77.78 77.78 0 0 0 3.44 57zM8.06 57h2.25c2.37-7.14 5.37-15 10.31-21.87h-3.31C12.87 42.18 10.19 50 8.06 57zM0 57h.3c.82-5 4.18-14.8 8.2-21.85H0zM12.66 57h3.28a127.42 127.42 0 0 1 5.86-11.54v-7.29c-4.2 6.05-6.88 13.17-9.14 18.83zM38.25 8.48l-.83-.31c-1.49 1.14-3.25 2.56-3.25 2.56h-2.68c2.82-3.32 9.17-8 12.57-10.43l-.73-.3C36.93 4.25 30 9 24 16.31v5.37a92.13 92.13 0 0 1 14.25-13.2zM47.32 8.65l-.95-.24a21.22 21.22 0 0 0-3.45 2.32h-2.47c.92-1.14 5.31-3.89 5.31-3.89l-1-.42A84.4 84.4 0 0 0 24 25.43v4.87A85.72 85.72 0 0 1 47.32 8.65zM30.58 8.44L29.66 8s-2.17 1.7-3.31 2.74H24v3.48a45.93 45.93 0 0 1 6.58-5.78zM48.44 18.1l-.65-.83-2.08 1.56V15c.87-.71 2.85-2.19 4.41-3.21l-1-.49C40.17 17.06 31 25.12 25.55 33h5.59a79.83 79.83 0 0 1 17.3-14.9zM49.64 24.19c-1.16.69-2.78 2-3.83 2.82l-.05-1.69s3.29-2.47 5.31-3.71l-.46-.77A105.45 105.45 0 0 0 35.44 33h5.28c3.24-3 5.81-5.65 9.15-8zM49 29.81l-.73-.73c-1.3 1.25-2.85 2.73-4.13 3.91h1.79A19.64 19.64 0 0 1 49 29.81zM23.93 35.14v7a59.56 59.56 0 0 1 5.43-7zM24 47.34v9.52c3.38-7.14 8.81-15.74 14.85-21.73h-5.31A96.54 96.54 0 0 0 24 47.34zM42.19 35.13C35.93 42.17 30.64 49.24 27.4 57h18.36V35.12c.04-.07-3.57.01-3.57.01z"/>
</Svg>
);
`
Please help!

**Comment by dustinsavery** [comment]
This looks possibly related to #516. Can you confirm if there are any similarities with your setup?

**Comment by abaddonGIT** [comment]
Yes, but i see this problem on android, and I also use React native navigation:
"react-navigation": "1.0.0-beta.15"

**Comment by dustinsavery** [comment]
I see you're on Android. What I think is happening is platform agnostic. I'm going to tag this issue in there and close this one as a dupe. Something tells me react-native-navigation is causing some sort of issue. Thanks for adding your findings!

**Comment by MrLoh** [comment]
@abaddonGIT can you confirm wether you are using React Navigation or React native navigation, there seems to be some confusion about that here.

**Comment by abaddonGIT** [comment]
I use react-navigation not React native navigation.

**Comment by dustinsavery** [comment]
ok, good to know, that would appear to be unrelated to the other issue. Thanks for updating.

**Comment by msand** [comment]
Please provide a full replication. Closing until that's made available.
