### ISSUE TITLE
help with <Image>

### ISSUE THREAD

**Issue by ulisinn** [react-native-community/react-native-svg#532]
Hi - 

not sure whether this is the appropriate forum to ask, but I am not able to reproduce the following snippet. Is this possible? 
Would I be better off to explore this in react-native-canvas?

In particular aligning the smaller image to the upper left and scaling it to it's correct size and translating the group. 

Thank you in advance for your help!
Uli

                <svg width='399' height='232' viewBox={'0 0 399 232'}>
                    <defs>
                        <clipPath>
                            <rect width='16' height='20' x='0' y='0'/>
                        </clipPath>
                    </defs>

                    <g>
                        <image xlinkHref={tpt} x='0' y='0' width='399' height='232'/>
                    </g>
                    <g transform='translate(182.5, 87)'>
                        <image clipPath='url(#valveClip)' xlinkHref={valve}
                               x='0' y='0' opacity='1'
                               width='16' height='20'
                        />
                </svg>

**Comment by dustinsavery** [comment]
Need a bit more context. Are you trying to render the above as an external SVG file or are you trying to paste that into a react component?

**Comment by ulisinn** [comment]
Hi - 

The above is coming from a react web component.

The idea was: compose a trumpet body an the three valves and then animate the valve y position so it gets pushed down in the clipping path. The three valves all have internally a 0/0 origin for image and clipping path and get moved by translating the group. So changing the position of the valve would be as simple as setting y from 0 to e.g. 16. And those coordinates stay the same independent of device rotation.

But several things behaved rather unexpectedly:

import React from 'react';
import { View } from 'react-native';
import { Svg, G, Image } from 'react-native-svg';

const tpt = require('./assets/TrumpetSmall.png');
const valve = require('./assets/ValveSmall.png');
const valveTinted = require('./assets/ValveSmallTinted.png');

const TrumpetSvg = ( svgStyle ) => {
    return <View
        style={{
            width: 399,
            height: 232,
        }}
    >
        <Svg height='232'
             width='399'
             viewBox={'0 0 399 232'}
             preserveAspectRatio='xMinYMin slice'
        >
            <G>
                <Image href={tpt}
                       x='0'
                       y='0'
                       width='100%'
                       height='100%'
                       preserveAspectRatio='xMinYMin'
                       transformOrigin
                />
            </G>
            {/*DOES NOT RENDER AT ALL*/}
            <G>
                <Image href={valve}
                       x='0'
                       y='0'
                       width='16'
                       height='20'
                />
            </G>
            {/*PLACED AND SCALED UNEXPECTEDLY*/}
            <G transform={'translate(-100,0)'}>
                <Image href={valveTinted}
                       x='0'
                       y='30'
                       width='70%'
                       height='70%'
                       transformOrigin={'0 0 0'}
                       preserveAspectRatio='xMinYMin meet'
                />
            </G>

        </Svg>
    </View>;
};

export default TrumpetSvg;
![trumpetsvg](https://user-images.githubusercontent.com/156169/33519029-5b64d5c4-d753-11e7-8cc9-72142316b014.png)

**Comment by ulisinn** [comment]
` <Svg height='232'
             width='399'
             viewBox={'0 0 399 232'}
             preserveAspectRatio='xMinYMin slice'
        >
            <G>
                <Image href={tpt}
                       x='0'
                       y='0'
                       width='100%'
                       height='100%'
                       preserveAspectRatio='xMinYMin'
                       transformOrigin
                />
            </G>
            {/*DOES NOT RENDER AT ALL*/}
            <G>
                <Image href={valve}
                       x='0'
                       y='0'
                       width='16'
                       height='20'
                />
            </G>
            {/*PLACED AND SCALED UNEXPECTEDLY*/}
            <G transform={'translate(-100,0)'}>
                <Image href={valveTinted}
                       x='0'
                       y='30'
                       width='70%'
                       height='70%'
                       transformOrigin={'0 0 0'}
                       preserveAspectRatio='xMinYMin meet'
                />
            </G>

        </Svg>`

**Comment by dustinsavery** [comment]
What version of `react-native-svg` are you using? I believe some of those transform issues were corrected in `6.0.1-rc.0`. Also, is there any way that I can see more of the code? Not really enough to get a clear picture of what's going on with the above.

**Comment by ulisinn** [comment]
const TrumpetSvg = () => {
    return <View
        style={{
            width: 399,
            height: 232,
        }}
    >
        <Svg height='232'
             width='399'
             viewBox={'0 0 399 232'}
             preserveAspectRatio='xMinYMin slice'
        >
            <G>
                <Image href={tpt}
                       x='0'
                       y='0'
                       width='100%'
                       height='100%'
                       preserveAspectRatio='xMinYMin'
                       transformOrigin
                />
            </G>
            {/*DOES NOT RENDER AT ALL*/}
            <G>
                <Image href={valve}
                       x='0'
                       y='0'
                       width='16'
                       height='20'
                />
            </G>
            {/*PLACED AND SCALED UNEXPECTEDLY*/}
            <G transform={'translate(-100,0)'}>
                <Image href={valveTinted}
                       x='0'
                       y='0'
                       width='70%'
                       height='70%'
                       transformOrigin={'0 0 0'}
                       preserveAspectRatio='xMinYMin meet'
                />
            </G>

        </Svg>
    </View>;
};

**Comment by ulisinn** [comment]
{
  "name": "rn_svg_6",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-svg": "^6.0.1-rc.0"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "prop-types": "^15.6.0",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by dustinsavery** [comment]
@ulisinn Not much to go on, but here are a few thoughts:
- Not sure why the last image is `70%` for both width and height. Since that's the tinted valve, that might explain why it's pixelated and blown out (I'm assuming that's a raster image?)
- Not sure why everything is in groups, there's not really a need. Groups are so you can control lots of SVG items, here you have no need to do that. Not really hurting, just one less layer of complexity.
- I would take your layers and go back to rudimentary background colors/some other way of uniquely identifying their boundaries. That way, you can see exactly where everything exists and what manipulating the different values gives you. That's what I would be doing in your shoes as a first step. Once you've done that, you should have a better idea of exactly where the problem lies. Once you try that, snap a screen shot and post it if you would. The next step would be to get the source files from you so I can play with it.

**Comment by ulisinn** [comment]
Abstract formulation of my problem:
- place 2 or more bitmaps of arbitrary sizes on the canvas
- display them at correct absolute or relative sizes to each other
- position them at arbitrary coordinates on the canvas

The above is where I ran into problems.

Ideally the next steps for me would be:
- move the smaller image with a clipping path into <Defs>
- place them on the canvas with a translated <G>
- add animation to the image behind the clipping path

**Comment by msand** [comment]
There definitely seems to be some bugs with the image positions and viewbox handling. I made a small expo test https://snack.expo.io/@msand/image-test @ulisinn could you try making one like that?
At least the offset handling is off, the x-axis behaves strange, and if the viewbox on the root element is set to non-zero min-x or min-y, then it incorrectly affects the image ancestor as well.

**Comment by ulisinn** [comment]
possible workaround is to nest the images as svg.
![trumpetsvgnested](https://user-images.githubusercontent.com/156169/33565953-6f6b696c-d8d3-11e7-87fa-0616019336e4.png)

**Comment by ulisinn** [comment]
`import React from 'react';
import { View, StyleSheet } from 'react-native';
import { Svg, G, Image } from 'react-native-svg';

const tpt = require('./assets/TrumpetSmall.png');
const valve = require('./assets/ValveSmall.png');
const valveTinted = require('./assets/ValveSmallTinted.png');

const TrumpetSvg = () => {
    return <View
        style={{
            width: 399,
            height: 232,
        }}
    >
        <Svg style={[styles.svg, { left: 100, top: 50 }]}
             width='399'
             height='232'
             viewBox={'0 0 399 232'}>
            <Image href={tpt} x='0' y='0' width='100%' height='100%' preserveAspectRatio='xMinYMin'/>


            <Svg style={[styles.svg, styles.valve_1]}
                 width='16'
                 height='20'
                 viewBox={'0 0 16 20'}>
                <Image href={valveTinted} x='0' y='0' width='100%' height='100%'/>
                <Image href={valve} x='0' y='0' width='100%' height='100%' opacity={0}/>
            </Svg>

            <Svg style={[styles.svg, styles.valve_2]}
                 width='16'
                 height='20'
                 viewBox={'0 0 16 20'}>
                <Image href={valveTinted} x='0' y='0' width='100%' height='100%' opacity={0}/>
                <Image href={valve} x='0' y='0' width='100%' height='100%' opacity={1}/>
            </Svg>

            <Svg style={[styles.svg, styles.valve_3]}
                 width='16'
                 height='20'
                 viewBox={'0 0 16 20'}>
                <Image href={valveTinted} x='0' y='0' width='100%' height='100%' opacity={0}/>
                <Image href={valve} x='0' y='0' width='100%' height='100%' opacity={1}/>
            </Svg>
        </Svg>
    </View>;
};

const styles = StyleSheet.create({
    svg: {
        position: 'absolute',
    },
    valve_1: {
        top: 87,
        left: 182.5,
    },
    valve_2: {
        top: 81,
        left: 199,
    },
    valve_3: {
        top: 75,
        left: 214,
    },
});


export default TrumpetSvg;
`

**Comment by stefvw93** [comment]
Any news on this?

**Comment by dustinsavery** [comment]
No news yet. With rc.1 had a fix for transforms, but not sure if that would solve this or not. @ulisinn have you tried upgrading? If it still doesn’t fix it, I’ll have to dig down into the lower levels. I’m not as familiar with that portion of the code yet, so it’ll take some time.

**Comment by msand** [comment]
@ulisinn @stefvw93  @dustinsavery  I have a new pull request with some fixes for image positioning and other improvements, could you test it? https://github.com/react-native-community/react-native-svg/pull/558

**Comment by stefvw93** [comment]
Oh nice! Hmm but I don't really have the time this month. Maybe later. Let me know if there's nobody to Q&A this.

**Comment by msand** [comment]
@ulisinn Are you still having any issues relating to this? I'll go ahead and close now. Reopen if you have any bugs to report.
