### ISSUE TITLE
Radial gradient has a slightly darker border compared to Stop color

### ISSUE THREAD

**Issue by andresfcamacho** [react-native-community/react-native-svg#535]
Hi. I'm wanting to use the RadialGradient for an Ellipse where the Stop color is the same as the background color containing the SVG. When doing this its seems like there is a darkish border that doesn't match the background color (even though they are the same):

React native: 0.48.3
React native svg: 5.4.1

```
            <Svg
              height="150"
              width="300"
            >
              <Defs>
                <RadialGradient gradientUnits="userSpaceOnUse" id="grad" cx="150" cy="75" rx="85" ry="55" fx="150" fy="75">
                  <Stop
                    offset="0"
                    stopColor="white"
                    stopOpacity="1"
                  />
                  <Stop
                    offset="1"
                    stopColor="#00a9a4"
                    stopOpacity="1"
                  />
                </RadialGradient>
              </Defs>
              <Ellipse cx="150" cy="75" rx="85" ry="55" fill="url(#grad)" />
            </Svg>
```

So the background for the container is same as the Stop color (#00a9a4) but there seems to be a darker color outlining the ellipse. I would expect it to seamlessly blend in since the colors are the same.

![screen shot 2017-12-06 at 4 39 00 pm](https://user-images.githubusercontent.com/237486/33693130-d1b98d00-daa5-11e7-8496-4c80b6884a23.jpg)

**Comment by dustinsavery** [comment]
Hmm, not sure why it would do that. Is there any chance you can upgrade to the latest `react-native-svg` and see if it still happens? there have been a number of fixes added since the version you're on.

**Comment by msand** [comment]
Closing until a replication showing how the behavior differs from other svg renderers is made available.
