### ISSUE TITLE
Change README

### ISSUE THREAD

**Issue by 6axter82** [react-native-community/react-native-svg#536]
Hello,

there was an issue in a library  [react-native-shadow](https://github.com/879479119/react-native-shadow/issues/18) which I have resolved by looking into the RadialGradient. Since the commit ff2395bcc26957a8cf1d04a4c0f3aa0277a8aede you didn't change the README file, stating the RadialGradient uses `%` and not numbers any longer. Please, can you update? Thank you.

**Comment by dustinsavery** [comment]
It actually allows for both. If a percentage is applied, it uses a relative layout to draw it. If a float is provided, it uses an absolute layout to draw it.

**Comment by 6axter82** [comment]
The author has left the floats and it broke the view... hence, the request. But now it made more questions than answers to the author. Thanks for your reply, though
