### ISSUE TITLE
How to display the original color?

### ISSUE THREAD

**Issue by XHTeng** [react-native-community/react-native-svg#538]
![image](https://user-images.githubusercontent.com/17663111/33804080-6ec3dc9c-ddd8-11e7-9055-c5d1f194f4c5.png)

I have a SVG file like this , have the effect of gradual change.
If I do not pass a parameter to the fill property, it is always black.
How can I do it to display the original color of the SVG file?

The following is the SVG file:
https://github.com/XHTeng/svg/blob/master/icon_collection.svg

**Comment by stowball** [comment]
Sketch doesn't really produce suitable SVGs. Your `<linear-gradient>`s need to be defined in `<defs>`. A tool such as [Affinity Designer](https://affinity.serif.com/en-gb/designer/) does this out of the box.

**Comment by dustinsavery** [comment]
Well it would need a fill right? If there’s no fill, it returns to black. If you created a filled and I filled style definitions, that would allow you to toggle between them. Does that work for your use?

I use sketch for svg export, it can _occasionally_ have issues, but the above is perfectly valid.

**Comment by XHTeng** [comment]
@stowball  YES! It works that use Affinity Designer export svg. Thanks~!

**Comment by dustinsavery** [comment]
@xhteng Good to know and glad it worked! Could you post the xfinity output so we can compare? I’m curious what caused it.
