### ISSUE TITLE
Compiling iOS 6.0.1-rc.1 do not work

### ISSUE THREAD

**Issue by evaldsurtans** [react-native-community/react-native-svg#539]
Errors after linking and pod install.
react-native run-ios
`QuartzBookPack.framework/Headers/Drawing-Gradient.h:21:1: error: duplicate interface definition for class 'Gradient'
@interface Gradient : NSObject`
`QuartzBookPack.framework/Headers/Drawing-Gradient.h:22:47: error: property has a previous declaration
@property (nonatomic, readonly) CGGradientRef gradient;`

**Comment by dustinsavery** [comment]
Is this on a new project or an existing project?

**Comment by stefanoeb** [comment]
Same issue, on my case, an existing project (6.0.1-rc.0 was failing with a PerformanceBezier error).
`react-native@0.50.4`

**Comment by stefanoeb** [comment]
downgrading to `5.5.1` works tho

**Comment by evaldsurtans** [comment]
In my case it is a new project.

**Comment by elailai94** [comment]
When I compile on iOS, I am getting this error: Duplicate interface definition for class 'BezierElement'. Are there any updates on this issue?

**Comment by elailai94** [comment]
I manage to resolve this issue by removing the RNSVG folder from the Development Pods folder and the line for RNSVG pod installation in the Podfile. Instead, I added RNSVG.xcodeproj to Libraries folder and libRNSVG.a to Link Binary to Libraries under Build Phases. Hope this helps.

**Comment by dustinsavery** [comment]
That would work, but it's surprising that you'd have to resort to that. Using `react-native-link` should allow you to link in the library without any issue.

**Comment by msand** [comment]
@evaldsurtans @dustinsavery @stefanoeb @elailai94  I have a pull request removing both QuartzBookPack and PerformanceBezier, resolving this and some other issues. Could you try it and help verify it works correctly? https://github.com/react-native-community/react-native-svg/pull/558

**Comment by kesha-antonov** [comment]
Hello guys! Waiting for the fix! Please merge PR above.

**Comment by elailai94** [comment]
@msand I am so sorry for the late reply. I have tried your fix and can verify that it works correctly. Thanks again for the fix!

**Comment by msand** [comment]
I've just released 6.0.1-rc.2 which removes PerformanceBezier and QuartzBookPack. Can you please test it?

**Comment by msand** [comment]
Everything should be working fine now. Closing this.
