### ISSUE TITLE
Spreadmethod not supported for lineargradient

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-community/react-native-svg#541]
LinearGradient doesn't allow to specify the `spreadMethod` property, making it impossible to repeat/reflect the gradient.

**Comment by dustinsavery** [comment]
@kbrandwijk that functionality is not currently implemented. Feel free to submit a PR if you'd like to see it integrated.

**Comment by kbrandwijk** [comment]
Sure, more than happy to. Just having a bit of trouble figuring out how to compile locally. Do you have a CONTRIBUTING.md somewhere hidden, or at least instructions on how to build locally?

**Comment by dustinsavery** [comment]
I don't believe so, but it's something I've wanted to work on. What sort of problems are you running into locally?

**Comment by HyopeR** [comment]
Do you plan to add this support in future versions of the package?
