### ISSUE TITLE
Asking for overlay permission

### ISSUE THREAD

**Issue by softwaregal** [react-native-community/react-native-svg#543]
after adding the **react-native-svg** library my app asks for **permission to overlay over other apps**.This calls for a scary user experience. And i do not require to overlay over other apps.Is this intended behaviour? If not how can i fix this?

**Comment by dustinsavery** [comment]
I assume you’re referring to Android. As far as I know, that’s a react-native development “feature”. Perhaps [this](https://medium.com/react-native-development/fixing-problems-in-react-native-caused-by-new-permission-model-on-android-1e547f754b8) might help?
