### ISSUE TITLE
 crashes on iOS launch: "undefined is not an object"

### ISSUE THREAD

**Issue by RieLo** [react-native-community/react-native-svg#545]
*the iOS release-mode app crashes at launch time if anywhere in code is importing 'react-native-svg'.
*Using: 
      React Native 0.50.2
      react-native-svg 5.5.1
*The console error message: "undefined is not an object"

It turns out to be a problem related to color, color-string, color-convert. 
Here's a similar issue: https://github.com/GeekyAnts/NativeBase/issues/1348

**Comment by dustinsavery** [comment]
Do you have anything more from the stack trace? Is this causing an RSOD? Also, have you tried upgrading to `6.0.x`?

**Comment by RieLo** [comment]
I believe it is not a problem of react-native-svg. It worked nice after I upgraded some of the packages in node_modules. Specifically, "color_converter" and "metro-bundler". The issue is now closed!
