### ISSUE TITLE
Animation in path

### ISSUE THREAD

**Issue by codesinghanoop** [react-native-community/react-native-svg#546]
I was trying to animate stroke of the path so i was unable to achieve that. Below is the code i used for it. What i'm actually trying to achieve is a running line. someone please help me, any help would be appreciated.

const AnimatedPath = Animated.createAnimatedComponent (Path);
constructor (props) {
    super (props);
    this.state = {
      animatedValue: new Animated.Value (0),
    };
  }

var animatedColor = this.state.animatedValue.interpolate ({
      inputRange: [0, Number.MAX_VALUE],
      outputRange: ['rgba(0, 0, 0, 0.8)', 'rgba(0, 0, 0, 0)'],
    });

<AnimatedPath
              strokeOpacity={lineStrokeOpacity}
              strokeDasharray={showDashedLine ? lineStrokeDashArray[i] : ''}
              key={i}
              d={data}
              fill={fillArea ? (Color[i] ? animatedColor : '#000') : 'none'}
              stroke={Color[i] ? animatedColor : '#000'}
              strokeWidth={lineWidth}
 />

react-native -v = 0.47.1
react-native-svg = 5.4.1

**Comment by dustinsavery** [comment]
I don’t have a huge amount of experience with the react native animation, but have you tried upgrading react-native and react-native-svg?

**Comment by codesinghanoop** [comment]
No success. @dustinsavery thanks for the suggestion.

**Comment by msand** [comment]
@codesinghanoop Check here e.g. https://github.com/msand/SVGPodTest/blob/a74a600818e496efaa78298291b63107295064bf/App.js#L14-L57

**Comment by codesinghanoop** [comment]
Thanks for helping however i implemented this. Hey check this out https://github.com/codesinghanoop/react-native-d3multiline-chart

**Comment by msand** [comment]
Very cool, looks great!
