### ISSUE TITLE
Compiling 6.0.0 fails on PerformanceBezier (iOS via CocoaPods)

### ISSUE THREAD

**Issue by adamski** [react-native-community/react-native-svg#549]
Lots of errors related to this set of classes, see screenshot.

I started trying to fix but thought better to report it here first. Installing via CocaoPods.  

<img width="994" alt="screen shot 2017-12-19 at 16 04 18" src="https://user-images.githubusercontent.com/14980/34166378-a34c8d24-e4d6-11e7-868d-75061f053e78.png">

**Comment by dustinsavery** [comment]
What version is being installed via cocoa pods? Haven’t seen these errors when installing through npm

**Comment by adamski** [comment]
I had to update the podspec to include the XCTest framework, change a few of the import statements to use relative paths instead of <>, set ARC to false, and finally, because the XCTest framework is not built with bitcode had to disable it in my project. 

Now I have a load of duplicate symbol errors I'm not sure how to solve... 
e.g.
```
duplicate symbol _FontWeight in:
    <path-to-app>/Builds/iOS/Build/Products/Debug-iphoneos/RNSVG/libRNSVG.a(FontData.o)
    <path-to-app>/Builds/iOS/Build/Products/Debug-iphoneos/RNSVG/libRNSVG.a(GlyphContext.o)
```
I've tried clean and rebuild - any ideas?

I'm planning to send a PR once its all working, but in the interests of time I might have to switch back to 5.5 for now.

**Comment by dustinsavery** [comment]
That might be the best option for now. I don't know what would be causing that atm.

**Comment by anonrig** [comment]
I'm having the same exact issue after I installed react-native-svg with cocoapods

**Comment by msand** [comment]
@adamski @dustinsavery @anonrig I have a pull request removing both dependencies. It should fix your issues.

**Comment by glacjay** [comment]
@msand still got duplicate symbol errors :(

**Comment by msand** [comment]
Try adding this to your Podfile: https://github.com/msand/SVGPodTest/blob/fe45f88a936181e6ecaddeb68268d33268b56121/ios/Podfile#L66-L70

**Comment by glacjay** [comment]
@msand It works for me, thanks.

**Comment by msand** [comment]
These issues should be resolved, closing for now.
