### ISSUE TITLE
Text positioning is inconsistent in iOS and Android

### ISSUE THREAD

**Issue by karloluis** [react-native-community/react-native-svg#551]
The following code is producing inconsistent behavior in mobile. Specifically the `y` axis positioning. On iOS it seems to be lower than Android which is behaving properly as I would expect it.

```
<Svg height="65" width="60" >
    <Circle cx="50%" cy="35" r="30" stroke="transparent" strokeWidth="0" fill="blue" />
    <Text
      fill="#ffffff"
      fontSize="12"
      fontFamily="Helvetica"
      x="49%"
      y="50%"
      textAnchor="middle"
    >
      Text
    </Text>
  </Svg>
```

**Comment by ryanhomer** [comment]
For me, on iOS, the text positioning is higher. The baseline of the text is at the y-position.
For Android OS, yes, it works as expected.

**Comment by msand** [comment]
Version? Have you tried latest?

**Comment by ryanhomer** [comment]
I'm on `6.0.0`. I've not tried `6.0.1-rc.3` yet.

**Comment by msand** [comment]
Seems to work fine: https://snack.expo.io/@msand/eager-bubblegum
