### ISSUE TITLE
how to draw 1px wide line in iOS?

### ISSUE THREAD

**Issue by wangweijia** [react-native-community/react-native-svg#554]
`<Line x1={15} y1={0} x2={15} y2={200} stroke="black" strokeWidth={1}/>`

this line is 2px in ios (iphone6),but set  `strokeWidth={0.5}`not working,how to draw 1px wide line in iOS?

**Comment by msand** [comment]
You need to have a viewbox which makes a unit in user space correspond to a pixel on the device. And then use percentages in your coordinates instead. Or, calculate the number of units per pixel and use that in your strokeWidth.
