### ISSUE TITLE
No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

### ISSUE THREAD

**Issue by danna88** [react-native-community/react-native-svg#555]
"react": "16.0.0",
"react-native": "0.51.0",

when i Run the command：react-native run-android ，I got that error。

**Comment by NikiLee2016** [comment]
me too, the same error

**Comment by YeXunSzeTo** [comment]
https://stackoverflow.com/questions/32092511/resource-error-in-android-studio-after-update-no-resource-found

**Comment by dustinsavery** [comment]
Looks like that was added recently. Going to lower the `appcompat` and try it.

**Comment by msand** [comment]
I've remove appcompat from the dependencies, this shouldn't be an issue anymore.
