### ISSUE TITLE
How to change the svg attribute by calling them on onPress function?

### ISSUE THREAD

**Issue by fazeelzama20** [react-native-community/react-native-svg#557]
<Path onPress={this.front_left}id= "front_left" fill="red" stroke="#000000" stroke-miterlimit="10" d="M416.149,36.583v6.074c0,0-23.136-0.639-23.668,0.703
                    c-0.533,1.343-1.073,5.31-12.058,6.267c-10.983,0.957-0.499,0.376-0.499,0.376s-14.932-0.102-35.894,121.739
                    c0,0-17.652,8.394-19.181,20.743c-1.528,12.349-0.535,0.663-0.535,0.663l-13.738-2.064c0,0-1.691-91.893,4.262-107.571
                    c0,0-2.711-31.206,32.987-39.191c0,0,1.365-2.564,6.021-2.694c4.651-0.132,12.963-1.844,16.036-2.476
                    c3.072-0.63,5.956-1.225,5.956-1.225s9.198,1.341,15.576-0.376C397.794,35.833,416.149,36.583,416.149,36.583z"/>
                  
front_left = () => {
    var isFilled = Svg.attr('fill');
}

i have to change the colour of fill attribute using onPress function.

**Comment by msand** [comment]
Check this e.g. https://github.com/magicismight/react-native-svg-example/blob/cfb788461efae0de367c97aadcc829cdeb959a8d/examples/TouchEvents.js#L46-L85
