### ISSUE TITLE
on drag

### ISSUE THREAD

**Issue by alexcittadini** [react-native-community/react-native-svg#559]
I've created a chart using this library. The user can select different data points on the chart to return the value. Is there a way to allow the value to change during a press and drag, ie not just onPressIn and onPressOut

**Comment by msand** [comment]
@alexcittadini You can use https://facebook.github.io/react-native/docs/panresponder.html for that. Can get a bit of inspiration or this perhaps: https://github.com/msand/zoomable-svg/blob/9e6f73fee9b12cd11809712edb72d5ab6c156f48/index.js#L106-L148

**Comment by msand** [comment]
https://github.com/facebook/react-native/blob/master/RNTester/js/PanResponderExample.js
