### ISSUE TITLE
Text Support

### ISSUE THREAD

**Issue by tanabs18** [react-native-community/react-native-svg#56]
Hi, this is a fantastically helpful component! I was wondering when you anticipated adding more text features.

Thanks!

**Comment by magicismight** [comment]
Text features are the most tricky ones. especially on iOS.
but I`ll try my best to acheive those features.
Now Text supports basic props and path prop.

**Comment by magicismight** [comment]
I have finished the `TextPath` support and `TSpan` support.
Will be released in this weekend.
![image](https://cloud.githubusercontent.com/assets/7693239/21891608/76084f58-d90e-11e6-8b15-b0451a3f951e.png)

**Comment by magicismight** [comment]
Those features are ship within 5.0.0.
