### ISSUE TITLE
React-native link doesn't work when you have CocoaPods in your project

### ISSUE THREAD

**Issue by xanderberkein** [react-native-community/react-native-svg#563]
> Note: If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link library using Podfile.

Source: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-2

The automatic linking with `react-native link react-native-svg` doesn't work however if you have a Podfile in your project. I get errors like  
`Warning: Native component for "RNSVGSvgView" does not exist `   
or  
`No component found for view with name "RNSVGPath"`  
when I try to render svgs.

When I manually link the react-native-svg packages, by following the first two stepts here (https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking), the errors go away and everything works fine.

**Comment by anonrig** [comment]
I'm experiencing the same exact problem.

**Comment by msand** [comment]
I've just released 6.0.1-rc.2 which removes PerformanceBezier and QuartzBookPack. Can you please test it?

**Comment by xanderberkein** [comment]
Seems to fix the issue for me, thanks!

**Comment by petrogad** [comment]
I just hit this on build `"react-native-svg": "^6.3.1"`; any chance there was regression here?

**Comment by emilefleming** [comment]
@petrogad I just ran into this as well, adding `pod 'RNSVG', :path => '../node_modules/react-native-svg'` to my podfile and letting CocoaPods handle it solved it for me.

**Comment by petrogad** [comment]
@emilefleming I did try doing that, however then my pod file tried to install react which created a dupe since all that for me is managed in my package.json at the JS layer.

How did you get around that?

**Comment by emilefleming** [comment]
@petrogad Try adding this to the end of your Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
