### ISSUE TITLE
How to achieve transform([{rotateZ:'0.78rad'}])

### ISSUE THREAD

**Issue by bestcoder0** [react-native-community/react-native-svg#567]
Is there a way to achieve similar effect in svg elements.

**Comment by msand** [comment]
You can use the [transform attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) with the `rotate(<a> [<x> <y>])` transform definition, e.g. 
```jsx
const rotate90DegTransform = contentToRotate => (
  <G transform="rotate(90)">
    {contentToRotate}
  </G>
)
```

**Comment by bestcoder0** [comment]
Does rotate occur only on x and y axis .. or can be done on zaxis too? Or Can we simulate z-axis rotation by combining x,y axis rotation and may be skewing?

**Comment by msand** [comment]
Only 2D rotation transform is supported for now, rotateZ that is. The 3D transforms rotateX/Y only work on react-native view elements. Generic 3D transforms require a 3x4 matrix, while we're sending a 2x3 matrix for now.

**Comment by msand** [comment]
I'll go ahead and close this for now.
