### ISSUE TITLE
console.error : ERROR SVG

### ISSUE THREAD

**Issue by Kcrong** [react-native-community/react-native-svg#571]
Runtime error I guess?

## My Environment
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4

## Screenshot
![image](https://user-images.githubusercontent.com/13450715/34809366-f2671060-f6d7-11e7-9b14-de515b3ff76a.png)

## Error code
line 64794 is as follows.
```javascript
var inputSVG = this.state.svgXmlData.substring(this.state.svgXmlData.indexOf("<svg "), this.state.svgXmlData.indexOf("</svg>") + 6);
```

## Xcode Log
```
2018-01-11 14:39:07.672 [error][tid:com.facebook.react.JavaScript] 'ERROR SVG', { [TypeError: this.state.svgXmlData.indexOf is not a function. (In 'this.state.svgXmlData.indexOf("<svg ")', 'this.state.svgXmlData.indexOf' is undefined)]
  line: 64794,
  column: 85,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
```

**Comment by msand** [comment]
Looks like you're giving incorrect data to react-native-svg-uri.

**Comment by prabhu73** [comment]
The same issue is happening in android also. 
Issue: E/ReactNativeJS: 'ERROR SVG', { [TypeError: Network request failed] line: 140, column: 2655, sourceURL: 'index.android.bundle' }

Could you please help me in resolving the issue?

**Comment by msand** [comment]
Seems your network is unreliable, or the the response doesn't contain valid svg
