### ISSUE TITLE
pod file: works with 5.5.1, fails with 6.0.1-rc.1

### ISSUE THREAD

**Issue by ulisinn** [react-native-community/react-native-svg#572]
when including cocoa pods with existing swift file.

my pod file:

  use_frameworks!

  pod 'RNSVG', :path => '../js/node_modules/react-native-svg'
  pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTAnimation',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  pod "yoga", :path => "../js/node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => '../js/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../js/node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../js/node_modules/react-native/third-party-podspecs/Folly.podspec'

**Comment by ulisinn** [comment]
Ugh, so close!!! 

see attachment. I can dismiss the error and the display is correct. 
I don't get that error with 6.0.1, only the earlier version.

Is this something I can fix myself? Help is greatly appreciated!

Uli
![screen shot 2018-01-12 at 2 33 00 pm](https://user-images.githubusercontent.com/156169/34898008-b94573c0-f7a5-11e7-9aaa-b0322a83e203.png)

**Comment by msand** [comment]
I've just released 6.0.1-rc.2 which removes PerformanceBezier and QuartzBookPack. Can you please test it?

**Comment by ulisinn** [comment]
![screen shot 2018-01-19 at 12 04 24 pm](https://user-images.githubusercontent.com/156169/35169314-f3c97918-fd10-11e7-8a30-50a5d3cfe531.png)

**Comment by ulisinn** [comment]
Showing All Issues
ld: 97 duplicate symbols for architecture x86_64

seems to be all Font/Text related:

duplicate symbol _FontStyle in:
    FontData.o
    FontStyle.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    FontVariantLigatures.o
duplicate symbol _FontWeight in:
    FontData.o
    FontWeight.o
duplicate symbol _FontWeight in:
    FontData.o
    GlyphContext.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    GlyphContext.o
duplicate symbol _TextAnchor in:
    FontData.o
    GlyphContext.o
duplicate symbol _TextDecoration in:
    FontData.o
    GlyphContext.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    GlyphContext.o
duplicate symbol _FontStyle in:
    FontData.o
    GlyphContext.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGClipPath.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGClipPath.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGClipPath.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGClipPath.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGClipPath.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGClipPathManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGClipPathManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGClipPathManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGClipPathManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGClipPathManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGGroup.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGGroup.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGGroup.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGGroup.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGGroup.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGGroupManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGGroupManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGGroupManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGGroupManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGGroupManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGNode.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGNode.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGNode.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGNode.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGNode.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGSymbol.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGSymbol.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGSymbol.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGSymbol.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGSymbol.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGSymbolManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGSymbolManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGSymbolManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGSymbolManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGSymbolManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGText.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGText.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGText.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGText.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGText.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGText.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGTextManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGTextManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGTextManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGTextManager.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGTextManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGTextManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGTextPath.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGTextPath.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGTextPath.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGTextPath.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGTextPath.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGTextPath.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGTextPathManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGTextPathManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGTextPathManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGTextPathManager.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGTextPathManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGTextPathManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGTSpan.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGTSpan.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGTSpan.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGTSpan.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGTSpan.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGTSpan.o
duplicate symbol _TextLengthAdjust in:
    RNSVGTSpan.o
    RNSVGTSpanManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGTSpanManager.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGTSpanManager.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGTSpanManager.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGTSpanManager.o
duplicate symbol _TextPathSpacing in:
    RNSVGTSpan.o
    RNSVGTSpanManager.o
duplicate symbol _AlignmentBaseline in:
    AlignmentBaseline.o
    RNSVGTSpanManager.o
duplicate symbol _TextPathMidLine in:
    RNSVGTSpan.o
    RNSVGTSpanManager.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGTSpanManager.o
duplicate symbol _TextPathSide in:
    RNSVGTSpan.o
    RNSVGTSpanManager.o
duplicate symbol _TextPathMethod in:
    RNSVGTSpan.o
    RNSVGTSpanManager.o
duplicate symbol _FontWeight in:
    FontData.o
    RNSVGUse.o
duplicate symbol _FontVariantLigatures in:
    FontData.o
    RNSVGUse.o
duplicate symbol _TextAnchor in:
    FontData.o
    RNSVGUse.o
duplicate symbol _TextDecoration in:
    FontData.o
    RNSVGUse.o
duplicate symbol _FontStyle in:
    FontData.o
    RNSVGUse.o
duplicate symbol _TextAnchor in:
    FontData.o
    TextAnchor.o
duplicate symbol _TextDecoration in:
    FontData.o
    TextDecoration.o
duplicate symbol _TextLengthAdjust in:
    RNSVGTSpan.o
    TextLengthAdjust.o
duplicate symbol _TextPathMethod in:
    RNSVGTSpan.o
    TextPathMethod.o
duplicate symbol _TextPathMidLine in:
    RNSVGTSpan.o
    TextPathMidLine.o
duplicate symbol _TextPathSide in:
    RNSVGTSpan.o
    TextPathSide.o
duplicate symbol _TextPathSpacing in:
    RNSVGTSpan.o
    TextPathSpacing.o
ld: 97 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ulisinn** [comment]
same as above for: 6.0.1-rc.2

**Comment by ulisinn** [comment]
Holy Cow!!!

it works!

**Comment by ulisinn** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TrumpetFingering' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly

  pod 'RNSVG', :path => '../js/node_modules/react-native-svg'

  pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTAnimation',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]


  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../js/node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../js/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../js/node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../js/node_modules/react-native/third-party-podspecs/Folly.podspec'


end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'yoga'
            # Workaround: react-native v0.52 bug issue #17274
            # node_modules/react-native/ReactCommon/yoga/yoga/YGNodePrint.cpp:208:46: Implicit conversion loses integer
            # precision: 'size_type' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int')
            # https://github.com/facebook/react-native/issues/17274#issuecomment-356363557
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
            end
        end
        if target.name == "RNSVG"
            target.build_configurations.each do |config|
                config.build_settings['GCC_NO_COMMON_BLOCKS'] = 'NO'
            end
        end
    end
end

**Comment by ulisinn** [comment]
![screen shot 2018-01-19 at 12 38 35 pm](https://user-images.githubusercontent.com/156169/35170609-b41b6f92-fd15-11e7-9a93-2730b55d98f1.png)

**Comment by ulisinn** [comment]
This runs inside of a swift based project successfully.

![screen shot 2018-01-19 at 12 39 29 pm](https://user-images.githubusercontent.com/156169/35170652-d69d8d70-fd15-11e7-8113-385d419593f6.png)

**Comment by msand** [comment]
Great! Is the code available anywhere?

**Comment by ulisinn** [comment]
Hi -

I pushed it to: <https://github.com/ulisinn/react_native_swift_integration>

Thank you for your help!

Uli

**Comment by msand** [comment]
The latest version doesn't have the duplicate symbol issue anymore, I recommend upgrading :)
