### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [react-native-community/react-native-svg#581]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by msand** [comment]
How about this? https://github.com/react-native-community/react-native-svg/pull/582

**Comment by pacamara** [comment]
@msand Thanks! #582 looks good.

**Comment by msand** [comment]
Published 6.0.1-rc.3 now. Please try it out.

**Comment by pacamara** [comment]
It works!
* git clone https://github.com/status-im/status-react.git
* in package.json change react-native-svg entry to: `"react-native-svg": "6.0.1-rc.3",`
* also upgrade status-react to `compileSdkVersion 27`
* build as usual
* there are no warnings relating to react-native-svg in the logs
:beers:

**Comment by jskidd3** [comment]
```
FAILURE: Build failed with an exception.

* Where:
Build file '..\node_modules\react-native-svg\android\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-svg'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Any ideas, guys?

**Comment by msand** [comment]
Hmm, what version of Android studio are you using? Can you try building using the latest?

**Comment by jskidd3** [comment]
@msand Built using command line, used latest version with a fresh RN project and can't get past this

**Comment by msand** [comment]
Do you have Android Studio installed? Try installed the latest of that: https://developer.android.com/studio/index.html

**Comment by jskidd3** [comment]
@msand Just done a fresh install, version 1.5.1 still the same

**Comment by pacamara** [comment]
Hi guys, I just checked and a RN project freshly generated with `react-native init FooProj` has
```
        classpath 'com.android.tools.build:gradle:2.2.3'
```
in its `android\build.gradle`. So that's the problem I guess.

**Comment by jskidd3** [comment]
@pacamara Yes mine has that same version. Could you let me know what it needs to be?

**Comment by pacamara** [comment]
@jskidd3 Sure, here's the diff of the changes I needed for a fresh project:
```
FooProj $ git diff
diff --git a/android/build.gradle b/android/build.gradle
index eed9972..965bebb 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -2,10 +2,11 @@
 
 buildscript {
     repositories {
+        google()
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:3.0.1'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
diff --git a/android/gradle/wrapper/gradle-wrapper.properties b/android/gradle/wrapper/gradle-wrapper.properties
index dbdc05d..bf1b63c 100644
--- a/android/gradle/wrapper/gradle-wrapper.properties
+++ b/android/gradle/wrapper/gradle-wrapper.properties
@@ -2,4 +2,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

**Comment by jskidd3** [comment]
@pacamara Thanks so much!

**Comment by pacamara** [comment]
@jskidd3 You're welcome! :beers:

**Comment by jskidd3** [comment]
@pacamara Experiencing a similar issue in a fresh project on OSX. Mind lending a hand? https://github.com/react-native-community/react-native-svg/issues/584

**Comment by msand** [comment]
@jskidd3 Have you tried these changes? https://github.com/react-native-community/react-native-svg/issues/581#issuecomment-359201096

**Comment by jskidd3** [comment]
@msand Yes I implemented them without any problem yesterday on Windows but am just having the same problem on Mac now. The difference is this time that my build.gradle already looks like what @pacamara suggested. This is the current one:

```
buildscript {
    repositories {
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 27

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenLocal()
    jcenter()
    maven {
        // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$projectDir/../../../node_modules/react-native/android"
    }
    google()
}

dependencies {
    api "com.android.support:appcompat-v7:27.0.2"
    //noinspection GradleDynamicVersion
    api 'com.facebook.react:react-native:+'
}
```

**Comment by msand** [comment]
I think you're looking at appName/node_modules/react-native-svg/android/build.gradle rather than appName/android/app/build.gradle

**Comment by sibelius** [comment]
you can do this on user land, no need to do this right now, as react native is not using gradle 3 yet

**Comment by pacamara** [comment]
Agree with @sibelius , better to wait for react native itself to upgrade. Apologies @msand  @jskidd3  for causing you extra work here

**Comment by msand** [comment]
@dlimx  lepouya How come FBSDK uses SDK 26 and appcompat 27.0.2
https://github.com/facebook/react-native-fbsdk/blame/master/android/build.gradle

While react-native uses these? @jpshelley @grabbou 
    compileSdkVersion 23
    minSdkVersion 16
    targetSdkVersion 22
    appcompat 23.0.1
and old gradle versions?

Perhaps I should make a PR upgrading them all to the latest stable versions?

Google has this to say about targetSdkVersion:

To maintain your application along with each Android release, you should increase the value of this attribute to match the latest API level, then thoroughly test your application on the corresponding platform version.
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd

https://developer.android.com/training/basics/supporting-devices/platforms.html#sdk-versions

**Comment by msand** [comment]
Made a PR https://github.com/facebook/react-native/pull/17747

**Comment by lepouya** [comment]
@msand It's the same versions as why facebook-android-sdk uses

**Comment by msand** [comment]
I think I just found a more than good enough reason for upgrade: [Path Traversal Vulnerability](https://support.google.com/faqs/answer/7496913)

**Comment by msand** [comment]
@pacamara @sibelius I guess meanwhile the PR is open, we could revert these changes. But, should we change them to align with the latest stable react-native init, or revert to the previous versions, what do you think?

**Comment by msand** [comment]
Although, now that I think about it. The latest changes have semver pre-release identifiers, and the other changes have been there for some time already. Perhaps best to wait and see for a bit more response on the PR.

https://semver.org/#spec-item-9
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes.

**Comment by pacamara** [comment]
@msand Thanks for filing facebook/react-native#17747!  

> should we change them to align with the latest stable react-native init, or revert to the previous versions, 

The only argument I can think of for aligning them with current react-init values is users wouldn't have to install as many versions of SDK Build Tools. Seems like a slim advantage, so reverting to the previous versions seems safer.

**Comment by msand** [comment]
I've released a new version, which aligns with react-native init, to make it as easy as possible for newcomers. Anyone with needs to upgrade any versions to anything different from that, will hopefully learn how to change them in their dependencies in the process as well. Lets see if they upgrade any versions, now that a PR exists. Can release a new version to align with that when they do.
