### ISSUE TITLE
Build failing with 'Could not find method google() for arguments [] on repository container'

### ISSUE THREAD

**Issue by jskidd3** [react-native-community/react-native-svg#584]
Message shown in console after `react-native run-android`:

```
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jskidd3/Desktop/Apps/AppName/node_modules/react-native-svg/android/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-svg'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I installed the plugin in a fresh project on OSX. Versions:

```
react-native-cli: 2.0.1
react-native: 0.52.0
Android Studio: 3.0.1
```

My package.json looks like this:

```
{
  "name": "AppName",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-svg": "^6.0.1-rc.3",
    "react-native-vector-icons": "^4.5.0"
  },
  "devDependencies": {
    "babel-jest": "22.1.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.1.4",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Any ideas as to how I can fix this?

**Comment by jskidd3** [comment]
@msand Sorry for the newbie question but where do I find those within the project?

**Comment by msand** [comment]
No worries. You can find it in appName/android/app/build.gradle where appName is the root of your project.

**Comment by msand** [comment]
Oh sorry, appName/android/build.gradle the on in the app folder is different.

**Comment by jskidd3** [comment]
@msand Here's what that file looks like:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by msand** [comment]
Try changing to this:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}
```

**Comment by jskidd3** [comment]
@msand That gives me this:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/joelkidd/Desktop/Apps/MyApp/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'MyApp'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by msand** [comment]
Make sure you have v4.1 of the gradle wrapper as well:
https://github.com/msand/SVGPodTest/blob/master/android/gradle/wrapper/gradle-wrapper.properties

```
#Thu Jan 18 18:05:34 EET 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

**Comment by msand** [comment]
Opening the project in the latest Android studio, would ask if you want it to make these upgrades for you when you open/build the project.

**Comment by jskidd3** [comment]
Now I get:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s
54 actionable tasks: 54 execute
```

**Comment by msand** [comment]
Can you try cleaning and rebuilding the project? Preferably in android studio, as it gives better error messages and helpful automation for these things.

**Comment by jskidd3** [comment]
Output from Gradle Build within Android Studio:

```
Information:Gradle tasks [clean, :app:assembleDebug, :react-native-maps:assembleDebug, :react-native-svg:assembleDebug]
Warning:The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Warning:The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
/Users/jskidd3/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/59539aab2a9f3f2996f368b98efa0b8b/res/values-v26/values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/Users/jskidd3/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/59539aab2a9f3f2996f368b98efa0b8b/res/values/values.xml
Error:(252, 5) error: resource android:attr/fontStyle not found.
Error:(252, 5) error: resource android:attr/font not found.
Error:(252, 5) error: resource android:attr/fontWeight not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/jskidd3/Desktop/Apps/MyApp/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
/Users/jskidd3/Desktop/Apps/MyApp/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Error:(171) resource android:attr/fontStyle not found.
Error:(171) resource android:attr/font not found.
Error:(171) resource android:attr/fontWeight not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 4s
```
Appreciate the fast responses whilst trying to sort this by the way 👍

**Comment by msand** [comment]
Now its probably the app specific build.gradle file:
android/app/build.gradle
```
@@ -94,12 +94,12 @@ def enableSeparateBuildPerCPUArchitecture = false
 def enableProguardInReleaseBuilds = false
 
 android {
-    compileSdkVersion 25
+    compileSdkVersion 27
 
     defaultConfig {
         applicationId "com.svgpodtest"
         minSdkVersion 16
-        targetSdkVersion 25
+        targetSdkVersion 27
         versionCode 1
         versionName "1.0"
         ndk {
@@ -138,7 +138,7 @@ android {
 dependencies {
     compile project(':react-native-svg')
     compile fileTree(dir: "libs", include: ["*.jar"])
-    compile "com.android.support:appcompat-v7:25.4.0"
+    compile "com.android.support:appcompat-v7:27.0.2"
     compile "com.facebook.react:react-native:+"  // From node_modules
 }
```

**Comment by jskidd3** [comment]
@msand Still getting errors so going to create a new project and start and build from Android Studio to see if it resolves. Just to confirm I should be using version v6.0.1-rc.2 right?

**Comment by msand** [comment]
The last changes, the ones in the app specific build.gradle are for rc-3, everything else should work fine with rc-2 as well.

**Comment by jskidd3** [comment]
@msand Sorted by installing rc-3 and following instructions again, built successfully after https://github.com/react-native-community/react-native-svg/issues/584#issuecomment-359261019

**Comment by jskidd3** [comment]
@msand Created a separate issue at https://github.com/react-native-community/react-native-svg/issues/585. Couldn't continue with these hacks as conflicted with other plugins so started a fresh and reverted to last major version

**Comment by laurindo** [comment]
I had the same problem and I've resolved change the version of my **"react-native-svg": "^6.0.1-rc.1"** to **"react-native-svg": "6.0.1-rc.1"** and run again **npm install** .

**My react-native-svg module had the version:** [Error]
![error-react-native-svg](https://user-images.githubusercontent.com/2501144/35370450-1188ec64-0175-11e8-9e36-d7e3fdab2c7b.PNG)

**Comment by msand** [comment]
@laurindo  Did you try making the required changes to these three files? https://github.com/react-native-community/react-native-svg/issues/583#issuecomment-360156905

**Comment by derekbar90** [comment]
Thanks for solving this but doesn't updating the API to 25-27 make the apps using this module limited to supporting only 5% of the android market?

**Comment by msand** [comment]
It should mostly make it so that newer android version don't need to run in backwards compatibility mode. The minSdkVersion 16 set the minimum sdk support level and decided how old versions it works with.
https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd

https://developer.android.com/training/basics/supporting-devices/platforms.html#sdk-versions

To maintain your application along with each Android release, you should increase the value of this attribute to match the latest API level, then thoroughly test your application on the corresponding platform version.
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

**Comment by nikolas7892** [comment]
same issue

**Comment by msand** [comment]
@nikolas7892 Check this: https://github.com/react-native-community/react-native-svg/issues/465#issuecomment-361230241

**Comment by KalaiselvanMahendran** [comment]
@msand What is the final solution for this issue? am also face the same issue.

**Comment by msand** [comment]
@KalaiselvanMahendran Have you tried making the changes mentioned in the previous linked comment? https://github.com/react-native-community/react-native-svg/issues/465#issuecomment-361230241

**Comment by msand** [comment]
@KalaiselvanMahendran Those instructions are for the latest version, seems you're trying to build an older one? Can you paste your package.json?

**Comment by wassgha** [comment]
I am getting the same error
`
Could not find method api() for arguments [com.android.support:appcompat-v7:27.0.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
`
did anyone fix it?

**Comment by msand** [comment]
Seems you're using an older version of gradle. Make sure you have v4.1 in:
android/gradle/wrapper/gradle-wrapper.properties

@@ -1,5 +1,6 @@
 +#Mon Jan 29 13:59:51 EET 2018
  distributionBase=GRADLE_USER_HOME
  distributionPath=wrapper/dists
  zipStoreBase=GRADLE_USER_HOME
  zipStorePath=wrapper/dists
 -distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
 +distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by msand** [comment]
@wassgha I've released a new version, which aligns all versions with react-native init. Please try with that.

**Comment by gokujy** [comment]
I am getting the same error:
Could not find method google() for arguments [] on repository container
Solve: I'm working on firebase crud and i installed angularfire2 and firebase plugin both.
So i uninstall firebase and error solved, i mean this error coming because conflict.

**Comment by volov157** [comment]
I got the same error when I use  react-native-sqlite-storage , only this website solve my problem , 
https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md

**Comment by kaszona** [comment]
Just delete the whole android folder and run a command to add.

**Comment by steve721** [comment]
> Can you check that you have google() in both of these?
> https://github.com/msand/SVGPodTest/blob/master/android/build.gradle#L6
> https://github.com/msand/SVGPodTest/blob/master/android/build.gradle#L24

![Screenshot_1](https://user-images.githubusercontent.com/85344739/126031939-e34e7bf1-6bed-4123-9e5c-9d65eea2fed0.png)

I Got an error that 

 Could not find method google() for arguments [] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

and my build.gradle looks like this 


buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "+"
        googlePlayServicesAuthVersion = "17.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
        firebaseMessagingVersion = "+"
    }
    repositories
        google()
        mavenCentral()
        jcenter()


    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }


allprojects {
    repositories {
        google()
        mavenCentral()
        //jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url "https://sdk.smartlook.com/android/release"
        }
        google()
        //jcenter()
        maven { url 'https://www.jitpack.io' }

        
    }
}

would you please help me it fix this
