### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by jskidd3** [react-native-community/react-native-svg#585]
Created fresh 0.52 RN project and installed plugin at last major release 6.0.0 and received the following error upon `react-native run-android` after following readme instructions:

```
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest
:app:processDebugResources
/Users/jskidd3/Desktop/Apps/TestSVG/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/jskidd3/Desktop/Apps/TestSVG/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/jskidd3/Desktop/Apps/TestSVG/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/jskidd3/Desktop/Apps/TestSVG/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by jskidd3** [comment]
Duplicate of https://github.com/react-native-community/react-native-svg/issues/511 (which fixed my issue)

**Comment by msand** [comment]
Try this changeset:
 android/app/build.gradle
```
@@ -94,13 +94,12 @@ def enableSeparateBuildPerCPUArchitecture = false
 def enableProguardInReleaseBuilds = false
 
 android {
-    compileSdkVersion 23
-    buildToolsVersion "23.0.1"
+    compileSdkVersion 25
 
     defaultConfig {
         applicationId "com.svgpodtest"
         minSdkVersion 16
-        targetSdkVersion 22
+        targetSdkVersion 25
         versionCode 1
         versionName "1.0"
         ndk {
@@ -139,7 +138,7 @@ android {
 dependencies {
     compile project(':react-native-svg')
     compile fileTree(dir: "libs", include: ["*.jar"])
-    compile "com.android.support:appcompat-v7:23.0.1"
+    compile "com.android.support:appcompat-v7:25.4.0"
     compile "com.facebook.react:react-native:+"  // From node_modules
 }
```
 
android/build.gradle
```
@@ -3,9 +3,10 @@
 buildscript {
     repositories {
         jcenter()
+        google()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:3.0.1'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
@@ -20,5 +21,6 @@ allprojects {
             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
             url "$rootDir/../node_modules/react-native/android"
         }
+        google()
     }
 }
```

android/gradle/wrapper/gradle-wrapper.properties
```
@@ -1,5 +1,6 @@
+#Thu Jan 18 18:05:34 EET 2018
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

**Comment by jskidd3** [comment]
@msand Thanks again, changing the versions up from 23 to 25 fixed it

**Comment by qingjiaowochengzd** [comment]
what do you mean clean ?
i build success ,second get the same error

**Comment by SrinivasanSelvam** [comment]
Changing the version may resolve the problem.  But it cannot run on API 23 of Android i.e Marshmallow right.  When you launch the created android app.  It only support Nougat and after versions.

**Comment by mangguoaidami** [comment]
@qingjiaowochengzd ,i same as build success, and second run has same error.

**Comment by Jturpijn** [comment]
@msand  I've tried your solution with the changeset, after performing ```cd android && ./gradlew clean``` and then going back to try ```react-native run-android``` I get the same error, but a little shorter: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
15 actionable tasks: 11 executed, 4 up-to-date
Could not install the app on the device, read the error above for details.
```
Do you have more advice or insights?

**Comment by usman1579** [comment]
> @msand I've tried your solution with the changeset, after performing `cd android && ./gradlew clean` and then going back to try `react-native run-android` I get the same error, but a little shorter:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Failed to execute aapt
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s
> 15 actionable tasks: 11 executed, 4 up-to-date
> Could not install the app on the device, read the error above for details.
> ```
> Do you have more advice or insights?

did u find solution?

**Comment by atitpatel** [comment]
I could fix the issue by adding following code in android/build.gradle

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27     //do this in android/app/build.gradle too
                buildToolsVersion '27.0.3'  //do this in android/app/build.gradle too
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        // maven { url 'https://maven.google.com' }
        google()
    }
}
```

**Comment by tolgayildiz37** [comment]
react-native run-android --no-jetifier

worked for me.

**Comment by snehakalvitkar** [comment]
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1115 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
70 actionable tasks: 2 executed, 68 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Unable to delete directory 'C:\Users\Supriya\Jute\android\app\build\generated\not_namespaced_r_class_sources\debug\r\com\facebook\flipper\plugins' after 10 attempts

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Unable to delete directory 'C:\Users\Supriya\Jute\android\app\build\generated\not_namespaced_r_class_sources\debug\r\com\facebook\flipper\plugins' after 10 attempts

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (C:\Users\Supriya\Jute\node_modules\execa\index.js:174:9)
    at C:\Users\Supriya\Jute\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\Supriya\Jute\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Supriya\Jute\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by snehakalvitkar** [comment]
Anyone can solve this error

**Comment by VINAY322** [comment]
hi
cd into android and run " gradlew clean  ".
and run npx react-native run-android, worked for me it should for you also.

**Comment by fsifl** [comment]
@VINAY322 ,
Thanks, I got same problem as @snehakalvitkar described,  you save me a day!

**Comment by udokaokoye** [comment]
> hi
> cd into android and run " gradlew clean ".
> and run npx react-native run-android, worked for me it should for you also.

Thanks, it solved my problem

**Comment by slimanej4c** [comment]
hi
if gradlew clean not working 
maybe the problem is aapt.exe can't write in R.txt
check if aapt.exe in list blocked in  anti virus avast and   make it in allowed  list 
https://stackoverflow.com/questions/61788014/android-studio-aapt-error-failed-writing-to-r-txt-the-data-is-invalid
