### ISSUE TITLE
currentcolor fill support

### ISSUE THREAD

**Issue by ctgardner** [react-native-community/react-native-svg#589]
In the web browser, setting the `fill` of an SVG element (path, etc.) instructs the element to inherit its `color` from the parent of the SVG. Attempting this with a `react-native-svg` `Svg.Path` element currently results in the following warning: `"currentcolor" is not a valid color or brush`.

Could we add support for `currentcolor` fills? I have provided the example code and the stack trace below.

```js
  <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
    <Svg.G fill="none" fill-rule="evenodd">
      <Svg.Path d="M-4-4h24v24H-4z" />
      <Svg.Path
        fill="currentcolor"
        fill-rule="nonzero"
        d="M16 7H3.83l5.59-5.59L8 0 0 8l8 8 1.41-1.41L3.83 9H16z"
      />
    </Svg.G>
  </Svg>
```

<img width="234" alt="screen shot 2018-01-29 at 7 37 06 am" src="https://user-images.githubusercontent.com/10970827/35486834-ef7f84d8-04c7-11e8-88a2-990c7ea85c5b.png">

**Comment by msand** [comment]
Didn't know about this one. I think it should be possible. At least the parts from the css color spec should be relatively easy, just check the color prop on the current element, take that, or it it says 'inherit' traverse upwards until you find an actual color value, either on a svg element or some other react-native element, with fallback to default black perhaps? As the spec says that Initial: depends on user agent
https://www.w3.org/TR/css-color-3/#color0

Not sure how to get the current color of the containing (non-svg) element though, you have any idea?

https://www.w3.org/TR/css-color-3/#currentColor-def
4.4. ‘currentColor’ color keyword

CSS1 and CSS2 defined the initial value of the ‘border-color’ property to be "the value of the ‘color’ property" but did not define a corresponding keyword. This omission was recognized by SVG, and thus SVG 1.0 introduced the ‘currentColor’ value for the ‘fill’, ‘stroke’, ‘stop-color’, ‘flood-color’, and ‘lighting-color’ properties. CSS3 extends the color value to include the ‘currentColor’ keyword to allow its use with all properties that accept a <color> value. This simplifies the definition of those properties in CSS3. 

**currentColor**
    The value of the ‘color’ property. The used value of the ‘currentColor’ keyword is the computed value of the ‘color’ property. If the ‘currentColor’ keyword is set on the ‘color’ property itself, it is treated as ‘color: inherit’. 

https://www.w3.org/TR/SVG/painting.html#SpecifyingPaint
**currentColor**
    Indicates that painting is done using the current animated value of the color specified by the ‘color’ property. This mechanism is provided to facilitate sharing of color attributes between parent grammars such as other (non-SVG) XML. This mechanism allows you to define a style in your HTML which sets the ‘color’ property and then pass that style to the SVG user agent so that your SVG text will draw in the same color.

https://css-tricks.com/currentcolor/

**Comment by msand** [comment]
Only the Text element has partial inheritance support
https://facebook.github.io/react-native/docs/text.html#limited-style-inheritance

And, we can't put svg elements inside of them. Only text elements have the color style prop, Views do not. So I think this can only be supported inside the svg content.
https://facebook.github.io/react-native/docs/text.html#style

**Comment by ctgardner** [comment]
> (Developer) React components are designed with strong isolation in mind: You should be able to drop a component anywhere in your application, trusting that as long as the props are the same, it will look and behave the same way. Text properties that could inherit from outside of the props would break this isolation.

It seems supporting `currentcolor` might violate one of the tenets of `react-native`. What do you think, @msand?

**Comment by msand** [comment]
Well, svg content as produced by spec conformant user agents do contain and depend on inheritance to render other parts of the content correctly. In this case, unless the components are used with the svgs and react-native-web packages, it shouldn't matter that much if the color doesn't cross from the react-native view backed components to the react-native-svg backed ones, while it would in web version where it would be html and normal svg content following the css spec. I'm not sure how much this property is used though? Do you have much content depending on it?

**Comment by ctgardner** [comment]
It's more of a convenience. I could refactor to explicitly pass the `fill` color via props.

In a web browser, a `svg` will scale proportionally to fill the smallest dimension of the parent. This behavior in conjunction with `currentcolor` means the rendering of the SVG can be defined entirely in terms of its parent; there's no need to pass any props into the SVG itself. Without the need for props, the SVG doesn't need to be a React component at all. This was my goal.

**Comment by msand** [comment]
@ctgardner You can have a single G element in the root of your svg content, wrapping all of it, allowing the child elements in the subtree to inherit the colors from that already.

I made an example with that + a onLayout pattern to make an Svg component (which takes a width and height property) and fills the available space in its parent: https://snack.expo.io/@msand/demonstrate-onlayout-to-fill-parent-and-inheritance-of-fill-color-props.

 Similarly you could use context to provide system/app wide defaults. https://reactjs.org/docs/context.html

**Comment by ctgardner** [comment]
> You can have a single G element in the root of your svg content, wrapping all of it, allowing the child elements in the subtree to inherit the colors from that already.

An interesting suggestion, I might try this.

> I made an example with that + a onLayout pattern to make an Svg component (which takes a width and height property) and fills the available space in its parent: https://snack.expo.io/@msand/demonstrate-onlayout-to-fill-parent-and-inheritance-of-fill-color-props.

Sorry, this doesn't seem to work. (Experience Not Found)

As an aside, I have a `react` project and a `react-native` project which share the same SVGs. Currently, I am duplicating the SVGs as they need to be wrapped as `react`/`react-native` components. It would be better if the SVGs were not duplicated and existed as `.svg` files only. Is this possible? (Using something such as `Svg.fromFile("./foobar.svg")`)

**Comment by msand** [comment]
Are you running the latest version of Expo?
You can have a build step, which generates the react-native components from the .svg files using something like: https://www.npmjs.com/package/svg-to-react-native-cli
or alternatively something like this: https://github.com/vault-development/react-native-svg-uri/issues/12#issuecomment-283671157

**Comment by msand** [comment]
You might want to pre-process your svg content with something like this: https://gist.github.com/msand/4b37d3ce04246f83cb28fdbfe4716ecc
If your content is not rendering the same in native as the web e.g. because of css related things.

**Comment by ctgardner** [comment]
Thanks for the help, @msand. Much appreciated!

**Comment by dohomi** [comment]
I am running into this issue on newest expo and react-native. Is there a solution for
```
color={'currentcolor'}
```
without throwing a console warning?

**Comment by leabaertschi** [comment]
`fill="currentColor"` is not working for me. This is what I tried:

```
<Text style={{color: 'white'}}>
  <Svg>
    <Circle id="Ellipse_1336" data-name="Ellipse 1336" cx={2} cy={2} r={2} fill="currentColor" />
  </Svg>
</Text>
```

Is this supposed to work or do I need to change something?
