### ISSUE TITLE
onPress doesn't seem to work for iPhone8/X but works for iPhone6/7

### ISSUE THREAD

**Issue by ewalti** [react-native-community/react-native-svg#592]
I've been seeing some odd behaviour with `onPress` on `Path`, `Rect`, `Circle`, etc. when using iPhone8/X in the iOS simulator. I had originally crafted some nice pie charts, but have since reverted to using a simple scene to test:

```
class TestScreen extends Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Svg
          height="100"
          width="100"
          onPress={ () => console.log('svg') }
      >
          <Circle
              cx="50"
              cy="50"
              r="45"
              stroke="blue"
              strokeWidth="2.5"
              fill="green"
              onPress={ () => console.log('circle') }
          />
          <Rect
              x="15"
              y="15"
              width="70"
              height="70"
              stroke="red"
              strokeWidth="2"
              fill="yellow"
              onPress={ () => console.log('rect') }
          />
      </Svg>
      </View>
    )
  }
}
```

I am unable to see any of these `console.log`s on an iPhone8/X but can see them just fine on iPhone6/7 in simulator. I assume maybe the collisions calculations are off on these devices? Has anyone experienced anything similar to this?

I'll start digging through the native code tomorrow, if anyone can point me in the right direction.

Cheers.

**Comment by ewalti** [comment]
I just spun up a brand-new react-native project with only `react-native-svg` installed, with the given code above, and I can get `console.log('rect')` to intermittently fire when clicking randomly, but to no reproducible affect.

**Comment by msand** [comment]
I don't have any iPhones available, so unfortunately I can't help with testing. But, I might be able to give some amount of guidance, if you have any specific questions :)

**Comment by ewalti** [comment]
Cool. I was able to get it working on simulator for iPhone 8/X but supposedly it doesn't work on device. I don't currently have one to test against, so I may have to loop back to this after some other features finish. I'll give you a ping when I get back to it and can submit a PR if I can solve the issue. Cheers.

**Comment by henriquemacedo** [comment]
Same here! Works fine on iPhone 5s but on X doesn't work. On simulator I think everything works well. Any solution?

**Comment by ewalti** [comment]
I've been tasked with figuring this out in the coming weeks, I just need to get my hands on a device first. I'll keep you updated.

**Comment by kenyonj** [comment]
I've seen some issues where `onPress` will work fine on the simulator but not consistently on the device and it's been due to force touch issues. Changing it to `onPressIn` will catch the touch regardless of the amount of pressure (do `Circle` and `Rect` support `onPressIn`?)

**Comment by msand** [comment]
These are probably related:
https://github.com/react-native-community/react-native-svg/issues/433
https://github.com/react-native-community/react-native-svg/issues/376
https://github.com/react-native-community/react-native-svg/issues/363
https://github.com/react-native-community/react-native-svg/issues/157
We should probably use/copy the gesture handling logic from the React-Native touchables.

**Comment by msand** [comment]
More related issues: https://github.com/react-native-community/react-native-svg/issues/482
https://github.com/react-native-community/react-native-svg/issues/473
https://github.com/react-native-community/react-native-svg/issues/264
https://github.com/FormidableLabs/victory-native/issues/25

**Comment by Yanjing123** [comment]
@kenyonj for my test Path support onPressIn but Circle not

**Comment by onpaws** [comment]
In my case, the `<Circle>` element works fine with `onPress` and `onPressIn`.
However, the `<G>` element doesn't for whatever reason. I'm finding it baffling.

**Comment by maxkomarychev** [comment]
@onpaws Issue with `<G>` (and also `<Use>`) is supposed to be fixed by https://github.com/react-native-community/react-native-svg/pull/650 - those elements didn't respond to touches on native side. However issue `onPress` vs `onPressIn` is still relevant.

**Comment by vjsingh** [comment]
Thanks @kenyonj!! Your fix works.

Also noting that this is still an issue. Took quite a while to figure out what was going on

**Comment by msand** [comment]
I don't have access to any iPhone at the moment, so I can't really troubleshoot or verify any solutions to this issue at all. Any help in getting this closed would be much appreciated!

**Comment by msand** [comment]
@ewalti I think I've fixed most of the issues now. Could you try this code with the latest commit in the master branch:

```jsx
import React, { Component } from 'react';
import { View } from 'react-native';

import Svg, { Rect, Circle } from 'react-native-svg';

export default class touchesMove extends Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Svg height="100%" width="100%" viewBox="0 0 100 100">
          <Circle
            cx="50"
            cy="50"
            r="45"
            stroke="blue"
            strokeWidth="2.5"
            fill="green"
            onPress={() => console.log('circle')}
          />
          <Rect
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
            onPress={() => console.log('rect')}
          />
        </Svg>
      </View>
    );
  }
}

```
Adding the onPress on the Svg element seems to have inconsistent behaviour still, on Android it logs for the root element, on iOS for the innermost hit target.

**Comment by msand** [comment]
Seems Android requires rejectResponderTermination on the inner elements, if you want the inner element to respond instead of the outer one.

**Comment by alburdette619** [comment]
The work around for this is now causing unwanted side effects for me.  Changing to `onPressIn` worked great, but now I have to wrap things in a `ScrollView` which is fine, but when scrolling from a touch point, the point activates immediately and doesn't seem to be able to be altered by gesture functions (could be wrong about this last point).

**Comment by msand** [comment]
I think I have (gesture) interactions between native animated transforms and normal svg transforms working correctly now as well: https://github.com/react-native-community/react-native-svg/commit/8c05da043dea3f8d04420c2d7c9c11733e22258b

**Comment by msand** [comment]
Closing this until further notice.
