### ISSUE TITLE
Text TextShadowNode 

### ISSUE THREAD

**Issue by s349856186** [react-native-community/react-native-svg#594]
`<Svg  >
       <Text x="100" y="75"  >SVGTEXT</Text>
</Svg>`
"react-native": "0.51.0",
"react-native-svg": "^6.0.1-rc.2",

import Svg, { Text, Path, line, G, Image, Circle} from "react-native-svg";

**parent without a measure function  trying add TextShadowNode to  LayoutShadowNode**
how to fix it

**Comment by msand** [comment]
Hmm, haven't seen this before, Could you post a complete replication/snack/repo?

**Comment by s349856186** [comment]
`<View style={styles.container}>
      <Svg style={styles.welcome} >

                    <Text x="100" y="75" stroke="#600" fill="#600" textAnchor="middle" >PV </Text>
                    <Image x="75%" y="5%"  style={styles.inverter} href={require('../image/cyj.png')} />
    />
</View>`
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'TextShadowNode' to a 'LayoutShadowNode')
addChildAt
    ReactShadowNodeImpl.java:199
addChildAt
    ReactShadowNodeImpl.java:54
setChildren
    UIImplementation.java:482
setChildren
    UIManagerModule.java:448
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

OS: android

**Comment by msand** [comment]
I think you're probably adding a React-Native Text element instead of a react-native-svg Text element inside of the Svg subtree in your render function. Impossible to say without a complete reproduction, this only gives a fraction of the required information.

**Comment by msand** [comment]
You can use `as ImportedBinding` in your ImportSpecifier, that is, rename or give an alias to the exports with colliding names from react-native and react-native-svg.
In expo, as it is exposed as the Svg export, you can assign to new variable names in a destructuring assignment like this instead: https://snack.expo.io/HyfwCmHLf
```jsx
import React, { Component } from 'react';
import { Text as NativeText, View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';
const { Text: SvgText } = Svg;

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <NativeText>
          Text outside svg
        </NativeText>
        <Svg width="100" height="100">
          <SvgText>Text inside svg</SvgText>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by s349856186** [comment]
@msand thank you very much.
