### ISSUE TITLE
Incorrect git tag matching when pod install

### ISSUE THREAD

**Issue by Matan** [react-native-community/react-native-svg#595]
Hi, a recent commit : https://github.com/react-native-community/react-native-svg/commit/d5a5e97b38e7f3e5b463fe63d3f7b2a2de1f3f14 : has made it impossible to install some versions with tags prefixed with a `v` e.g. `v6.1.3`.

**Comment by msand** [comment]
@Matan Thanks for reporting this! I've pushed a 6.1.3 tag to the release commit, can you verify it works? https://github.com/react-native-community/react-native-svg/releases/tag/6.1.3

**Comment by Matan** [comment]
Thanks for the quick response! It's working now! You'll need to stick a single tagging convention going forward :)
