### ISSUE TITLE
PanResponder inside Nested SVG Component doesn't work

### ISSUE THREAD

**Issue by renganatha10** [react-native-community/react-native-svg#597]
I am using react-native-svg: 6.1.3
I have copied the code of [react-native-circular-slider](https://github.com/bgryszko/react-native-circular-slider) and modified its transform parser to support the latest version of react-native-svg

But the Panresponder on  `G` tag is not working? 
Couldn't understand this 
Older version of react-native-svg works but not the latest one

Any workaround ?

**Comment by msand** [comment]
Could it be related to this? https://github.com/react-native-community/react-native-svg/pull/293 Can you try reverting this change and see if it helps?

**Comment by rijn** [comment]
I tried reverting this change and it worked.

**Comment by msand** [comment]
Is this still an issue?

**Comment by msand** [comment]
Please provide a full reproduction if this is still an issue. Closing until then.
