### ISSUE TITLE
onPress area for Path/Polyline

### ISSUE THREAD

**Issue by mchen37** [react-native-community/react-native-svg#599]
I am using Path to display a line and if clicked on, it triggers something. It is being triggered even if the user clicks on the "area" of the Path. I tried using Polyline instead and even though it is not drawing correctly because I haven't correctly converted the points yet, it still seems like the Polyline has an "area" that is still triggering the onPress as well.

Is there a way to make onPress only trigger when the line is pressed?

**Comment by msand** [comment]
@mchen37  Can you provide a full replication?

**Comment by msand** [comment]
I think this is fixed in the latest version. Please reopen if you still have issues.

**Comment by kev71187** [comment]
I still run into this problem on the current version
