### ISSUE TITLE
Add RNSVG.podspec

### ISSUE THREAD

**Issue by mrozbarry** [react-native-community/react-native-svg#60]
It would be great to be able to use this in my Podfile so I don't have to mess with project settings in xcode every time I use this in a project.

Not a huge priority, but it would help alleviate simple issues.

**Comment by maluramichael** [comment]
@mrozbarry there is a podspec file now https://github.com/react-native-community/react-native-svg/blob/master/RNSVG.podspec

**Comment by mrozbarry** [comment]
It's too bad I finished the project, but I'm definitely sure this will help some other people. Thank you sir!
