### ISSUE TITLE
Centering text with multiple TSpan child element isn't right

### ISSUE THREAD

**Issue by darkrift** [react-native-community/react-native-svg#600]
This is on an Android.

Environment :
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-svg": "6.1.3",

This is also related to https://stackoverflow.com/questions/48695503/how-to-vertically-and-horizontally-center-svg-text-with-different-font-size

It seems that rendering Text with TSpans underneath centers the text according to the first TSpan instead of the whole text

I don't know what tool to use as "source of truth" to determine which implementation is right but my Chrome version 64.0.3282.140 renders the following centered :
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 104 57.8" style="enable-background:new 0 0 104 57.8;" xml:space="preserve">
<style type="text/css">
	.st0{fill:rgb(242, 103, 36);}
</style>
<g id="XMLID_200_">
	<g id="XMLID_337_">
		<path id="XMLID_340_" class="st0" d="M-0.1,57.8h85c19.1,0,19.5-13.9,19.1-17.9L97.8,0H0.1L-0.1,57.8z"/>
	</g>
</g>
  <text x="52" y="28.9" dy="0.33em" font-size="44" text-anchor="middle" font-family="Swiss721BT-Bold">
    <tspan>T</tspan><tspan font-size="32">ext</tspan>
  </text>
</svg>    
```

![tab-center-text](https://user-images.githubusercontent.com/544998/36078456-89f5fa0c-0f44-11e8-8541-8f50a8cf5406.png)

While react-native-svg centers the text according to the first TSpan
```
import React from 'react';
import Svg, { G, Path } from 'react-native-svg';
import { Text, TSpan } from 'react-native-svg';

export default ({ height, width, children, fill='rgb(242, 103, 36)' }) => (
  <Svg height={height} width={width} viewBox="0 0 104 57.8">
    <G><G>
      <Path d="M0,57.8h85c19.1,0,19.5-13.9,19.1-17.9L97.8,0H0.1L0,57.8z" fill={fill}/>
    </G></G>
    <Text x={52} y={28.9} dy="0.33em" textAnchor={'middle'} fontSize={44} fontFamily={"Swiss721BT-Bold"}>
      <TSpan>T</TSpan><TSpan fontSize={32}>ext</TSpan>
    </Text>
  </Svg>
)
```

![react-native-svg-6 1 3-center-tspan](https://user-images.githubusercontent.com/544998/36078475-c83bcada-0f44-11e8-9a9d-672a31742237.png)

**Comment by msand** [comment]
Chrome renders closer to spec here definitely. The easiest way to get this working correctly is probably to finish the SVG 2.0 text layout algorithm. I've started implementing it here: https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/TextLayoutAlgorithm.java
And then porting it to obj-c as well of-course. The text-anchor middle should essentially shift the first character of an anchored chunk in a line by half the extent of the all the (anchored) text in the chunk or the sub-tree of the Text element. PRs very welcome!

**Comment by henricazottes** [comment]
Any update on this @msand  ? Still having the issue. If it's not too complicated for a beginner I'll check what you started

**Comment by msand** [comment]
@henricazottes I haven't had any time to look at this. Feel free to work on it. A simpler workaround might be to implement another method on the Text elements, which gets the sum of advances of all the anchored text inside the sub-tree, and using that value to shift the text. Should be much more straightforward than implementing the entire svg 2.0 text layout algorithm.

**Comment by msand** [comment]
This can probably be worked around for now by using a onLayout handler on the root Text element, and translating the group as a whole, a bit like in this: https://github.com/react-native-community/react-native-svg/issues/907

**Comment by msand** [comment]
I think I might have fixed this for iOS now
![simulator screen shot - iphone xr - 2019-02-09 at 22 06 34](https://user-images.githubusercontent.com/1131362/52525754-01106600-2cb7-11e9-94a7-7efcc13df244.png)

**Comment by msand** [comment]
Shouldn't be too hard to port the changes to android either.

**Comment by msand** [comment]
I think i've fixed this now. Can you try with the text-anchor-subtree-calculation branch? https://github.com/react-native-community/react-native-svg/tree/text-anchor-subtree-calculation
