### ISSUE TITLE
ios/Text/** contains unprefixed, global symbols, preventing vendoring of the library in Expo

### ISSUE THREAD

**Issue by terribleben** [react-native-community/react-native-svg#603]
There's at least one in Util as well.

**Comment by msand** [comment]
Hmm, can you be more specific?

**Comment by terribleben** [comment]
Sure! Sorry I didn't provide more info before. (didn't think somebody would look at this right away. 😅  )

Everything (as far as I can see) under here: https://github.com/react-native-community/react-native-svg/tree/master/ios/Text doesn't have the `RN*` prefix on any of the classes, enums, macros, headers, or other symbols that live in the global objective-c namespace. The rest of the iOS code uses the `RN*` prefix.

Since there's no namespace on any of these symbols, we can't disambiguate different versions of this code (which is required to work with Expo, since we support several versions of rn-svg).

See: [This nice article](http://nshipster.com/namespacing/) and the [Apple recommendation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html).

**Comment by msand** [comment]
Could you make a PR fixing this?

**Comment by terribleben** [comment]
Yeah, I or somebody else at Expo can submit a PR for this at some point. I may not have time in the next few days so I opened this just to keep track of the issue.
