### ISSUE TITLE
Missing RNSVGBezierElement.m in 6.20

### ISSUE THREAD

**Issue by msageryd** [react-native-community/react-native-svg#605]
After upgrading to 6.20 I got this:
`clang: error: no such file or directory: '/.../ios/Utils/RNSVGBezierElement.m'`

Maybe I have missed something during the upgrade?
I've tried a lot of tricks..
- I closed the bundler
- ..start --reset-cache
- Cleaned the project from Xcode
- rm -rf ios/build
- react-native unlink react-native-svg
- react-native link react-native-svg (had to manually remove tv-os as usual

**Comment by msand** [comment]
Hmm, are you using cocoapods? Have you run pod install? Was working when I did some quick tests this morning, I'll have to double check.

**Comment by msageryd** [comment]
No, I keep a healthy distance to pods. They have given me nothing but trouble.

I went back to 6.1.4 and it works now. I'll give the upgrade a new shot and get back here with the outcome. The reason for my eager upgrade was that I suddenly cant run my app in release mode. It crashes without any information.

**Comment by msand** [comment]
Alright, seems there was a problem with the paths, was working with cocoapods, and of course I didn't test in a fresh project, thought the one I tried should be enough of validation. Now it (v6.2.1) works in a fresh react-native init + link + manually remove libRNSVG-tvOS.a + run-ios

**Comment by msageryd** [comment]
Thanks 6.2.1 works for me.
