### ISSUE TITLE
iOS/Android differences in onPress propagation

### ISSUE THREAD

**Issue by adrianboimvaser** [react-native-community/react-native-svg#611]
When a section is pressed it the color changes to orange (selected).
![image](https://user-images.githubusercontent.com/1104728/36504698-27490b76-1730-11e8-83d9-fa1df29aff61.png)

In Android I had to render a transparent selection layer after/over the image, because pressing on a `<Text>` component doesn't propagate to the `<Path>` component under it. In iOS the selection layer doesn't get the presses. I removed it and it turns out pressing on a `<Text>` component does propagate to the `<Path>` component under it.

**Comment by adrianboimvaser** [comment]
Figured out a change to the selection layer that fixed the problem with it:
Instead of:
``
<Path
  key={index}
  fill="none"
  onPress={() => console.log(index + ' was pressed')}/>
``
Did:
``
<Path
  key={index}
  fill="#FFF"
  fillOpacity={0}
  onPress={() => console.log(index + ' was pressed')}/>
``
So, it looks like on iOS `onPress` is not handled on elements with `fill="none"`.

**Comment by Amnesthesia** [comment]
I'm having a similar issue - except for me, it works flawlessly on iOS with transparent elements, but not at all on Android (not with fill, opacity, or stroke)

**Comment by msand** [comment]
Can you provide a full replication? Closing until that.
