### ISSUE TITLE
Load image from URL to the Image svg

### ISSUE THREAD

**Issue by AndreiCalazans** [react-native-community/react-native-svg#612]
I'm trying to load an image to the Image component but without luck.

I saw many issues opened about this and there was no clear solution nor a stance saying that this is not possible.

The question is.
**Is it possible to load an image from an URL to the Image svg?**

if yes how?

Issues related.

#510 
#347 
#310

**Comment by AndreiCalazans** [comment]
Sorry I just noticed the Todo in the README. 
Then I guess we can close this since this is a feature to be implemented.

**Comment by msand** [comment]
@AndreiCalazans Check here https://snack.expo.io/@msand/image-from-uri-inside-svg

**Comment by msand** [comment]
Another example here with react-native-fetch-blob and a file cache: https://github.com/react-native-community/react-native-svg/issues/347#issuecomment-368862343
