### ISSUE TITLE
Decorators with multiple data sets for bar charts

### ISSUE THREAD

**Issue by zzorba** [react-native-community/react-native-svg#613]
I've been trying to use decorators with a multiple data set BarChart (since I want the bars to be different colors).  It seems like the decorator only gets called for the first data item (data[0]).

Is this the expected behavior?  If I want a decorator per bar would the best option be to use a parallel extras array?

**Comment by msand** [comment]
Is this the correct repo to post this issue? I suspect it belongs in some Chart library?

**Comment by zzorba** [comment]
Sorry, wrong repo
