### ISSUE TITLE
react-native-zebra-bt-printer plugin is working in android but it is not working in ios phone? 

### ISSUE THREAD

**Issue by shivaraj-profecia** [react-native-community/react-native-svg#614]
Hi,
I am using react-native-zebra-bt-printer plugin for printing and its working fine in android but its not working in ios app, Even i had given printer serial number and also mac address but still it is not working in iphone so please help me out.
Any help would be appreciated.

Thank you

**Comment by msand** [comment]
Unrelated to this library.

**Comment by MAsad-Nawaz** [comment]
I need help in react-native-zebra-bt-printer plugin. how can i use ? can you share any example code?
