### ISSUE TITLE
Text Overlapping 

### ISSUE THREAD

**Issue by BonnieMilian** [react-native-community/react-native-svg#622]
Something goes wrong with the Text when in the String is a pattern "fl" + any character, seems overlapped the 'l' and the next character.
Try to fix it with letterSpacing but is not working.

Is something with the rendering.
See a example with the Text "Hello fla fle fli flo flu".
![img-20180310-wa0000](https://user-images.githubusercontent.com/10040635/37245135-4bc780f0-2459-11e8-836f-2ee54414f536.jpg)

That occurs on Android with the font "Sharp Sans Bold". I don't know if is occurring in ios or other fonts.

**Comment by msand** [comment]
This is probably related to ligatures, the font probably has a ligature for 'fl' in addition to the normal 'fi' ligature, and it either has the incorrect advance width, or it's not accounted for correctly. On what version is this? And can you post a reproduction rather than a screenshot?

**Comment by BonnieMilian** [comment]
Version: 5.4.1

```
import Svg,{
    LinearGradient as LinearSvg,
    Line,
    Text as TextSvg,
    Defs,
    Stop,
    G,
} from 'react-native-svg';
...
    let color1 = this.props.color1 || "#ff00a8"
    let color2 = this.props.color2 || "#ff000c"
    let {customExtraHeight} = this.props
    if ( !customExtraHeight ){
      customExtraHeight = 2
    }
return(
      <View  style={this.props.style}>

      <Svg height={this.props.size +customExtraHeight}  width={width}>
         <Defs>
          <LinearSvg id="grad" x1="0" y1="0" x2="170" y2="0">
            <Stop offset="0" stopColor={color1} stopOpacity="1" />
            <Stop offset="1" stopColor={color2} stopOpacity="1" />
          </LinearSvg>
       </Defs>

         <TextSvg fill="url(#grad)" fontSize={this.props.size - 1}
           style={{fontFamily:Config.SharpBold}}
           fontWeight="bold" >{this.props.text}</TextSvg>
       </Svg>
    </View>
    )
...
```

**Comment by BonnieMilian** [comment]
If the 'fi' is a normal ligature, you can try it with other fonts right?

**Comment by msand** [comment]
Ah, can you try with the latest version? Pre v6.0.0 doesn't support ligatures

**Comment by BonnieMilian** [comment]
I tried the Latest but is worst doesn't even appear the text, just little lines.
![img-20180312-wa0000](https://user-images.githubusercontent.com/10040635/37313273-19685294-2614-11e8-9fe8-e0cfe8c1ec52.jpg)

**Comment by BonnieMilian** [comment]
Tried to downgrade to Version 5.5.1.
The Text appear, 'fi' ligature dont overlap but has too much space, and the other ligatures still overlapping ('fl'+any char)

**Comment by mwalkerwells** [comment]
The happens for me for all fonts on version 6.2.2 only for Android. Have you two sense figured this out?

**Comment by msand** [comment]
Tried to replicate it but I don't have the specific font available, after setting a proper viewBox and x,y coordinates it seems to work with the system fonts at least: https://snack.expo.io/SyfGuRx3G
```jsx
import React, { Component } from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { Constants, Svg } from 'expo';
const { Defs, LinearGradient, Stop, Text, Rect } = Svg;
const { width, height } = Dimensions.get('window');

export default class App extends Component {
  render() {
    let color1 = this.props.color1 || '#ff00a8';
    let color2 = this.props.color2 || '#ff000c';
    return (
      <View style={styles.container}>
        <Svg height={height} width={width} viewBox="0 0 170 60">
          <Defs>
            <LinearGradient id="grad" x1="0" y1="0" x2="170" y2="0">
              <Stop offset="0" stopColor={color1} stopOpacity="1" />
              <Stop offset="1" stopColor={color2} stopOpacity="1" />
            </LinearGradient>
          </Defs>
          <Rect x="0" y="0" width="170" height="60" fill="none" stroke="red" strokeWidth="0.3"></Rect>
          <Text x="0" y="17" fill="url(#grad)" fontSize="20" fontFamily="normal" fontWeight="bold">
            Hello fla fle fli flo flu
          </Text>
          <Text x="0" y="37" fill="url(#grad)" fontSize="20" fontFamily="serif" fontWeight="bold">
            Hello fla fle fli flo flu
          </Text>
          <Text x="0" y="57" fill="url(#grad)" fontSize="20" fontFamily="monospace" fontWeight="bold">
            Hello fla fle fli flo flu
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});
```

![snack expo io_syfgurx3g](https://user-images.githubusercontent.com/1131362/38779343-89949aac-40cf-11e8-8430-0b557ad1b0c1.png)

**Comment by mwalkerwells** [comment]
Hard to show it on iOS, but this is the issue on Android: https://snack.expo.io/SyfGuRx3G 

I'm using Roboto on both platforms. Looks like I can resolve the issue (I think / haven't tried yet) by scaling up the viewbox, but I was just surprised it rendered differently across iOS and Android.

![screen shot 2018-04-17 at 3 54 16 pm](https://user-images.githubusercontent.com/16157429/38903001-c5d5818c-4257-11e8-9cf4-954afb2516bf.png)

**Comment by liuqiang1357** [comment]
+1

**Comment by liuqiang1357** [comment]
Same issue with Chinese character.

**Comment by yanush** [comment]
I have the same issue but with the letters "ae"
Is there a fix for that? letterSpacing is not working for me

**Comment by msand** [comment]
Is this still an issue? Can you provide a full replication?

**Comment by msand** [comment]
@yangyi @liuqiang1357  Could you provide a small code snippet to demonstrate the issue you had?
