### ISSUE TITLE
Merging library

### ISSUE THREAD

**Issue by koswarabilly** [react-native-community/react-native-svg#623]
First off, i am sorry for matc4. You created a dependency that is great which is [react-native-svg-uri](https://github.com/vault-development/react-native-svg-uri) that allow user to require svg image like using `<Image>` tag. but i suggest to merge it with this parent library because it will be easier to maintain and easier to install. 

what do you think? will it be possible?

**Comment by msand** [comment]
Sure, could be done. Would you be willing to make a PR @koswarabilly or are you up for it @matc4 ?
