### ISSUE TITLE
Trouble touch area for Image of png format

### ISSUE THREAD

**Issue by ducNgbk** [react-native-community/react-native-svg#624]
Hi
I want to use `Image` as a button; however, onPress event is not triggered every time I hit it.
Here is its source.
![combined shape 287 3x](https://user-images.githubusercontent.com/30441868/37339469-58d44aa8-26ed-11e8-93a8-f00e2e098c85.png)

I tried to increase its `width` and `height` props, but it did help.
So any idea or trick to deal with this problem?
My code:
```
<Svg width={screenWidth} height={300}>
        <Image
          onPress={this.doSomeThing}
          href={require("./Images/navBarLeftIcon.png")}
          width={48}
          height={48}
        />
</Svg>
```
I am using:
```
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-svg": "^6.2.2",
    "react-native-vector-icons": "^4.5.0"
```
Testing on Iphone 6s (11.2) and stimulator of Iphone 6 (11.2)

Looking for any help. Thank you

**Comment by msand** [comment]
If you only have an image and want onPress, then you can simply use TouchableHighlight and Image from React Native, e.g.  like this: https://snack.expo.io/Bk6Cq9SKG

```jsx
import React, { Component } from 'react';
import { View, StyleSheet, TouchableHighlight, Image } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight onPress={() => alert('Do something!')}>
          <Image
            style={styles.logo}
            source={require('./assets/expo.symbol.white.png')}
          />
        </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  logo: {
    backgroundColor: '#056ecf',
    height: 128,
    width: 128,
  },
});
```

**Comment by msand** [comment]
That's of course just a temporary workaround, and this issue probably needs more investigation.

**Comment by sanealytics** [comment]
Adding to this, if you really want to use Image from svg (my use case because I want to freely position them), use a group <G> to draw a rectangle along with the image, pass onPress to that.

**Comment by msand** [comment]
Press handling has been improved a lot. Please try with the latest commit from the master branch. Closing until further notice.
