### ISSUE TITLE
Shadow solution

### ISSUE THREAD

**Issue by rareslupascu** [react-native-community/react-native-svg#635]
Hi everyone

I read almost all the opened and closed issues related to dropping shadows ...
They are pretty old so is there any recommended way to do this? if not how would one go about doing that?

thanks

**Comment by msand** [comment]
Currently filters aren't supported, thus drop shadows don't work either. I've just used raster shadows as a workaround for now.

**Comment by ntomallen** [comment]
If one was to look into creating a PR to support shadows, where would they begin? As outlined in many previous issues, this would be a great feature!

**Comment by msand** [comment]
It would require implementing the filter attribute, filter element and the filter primitives, or at least feGaussianBlur, feOffset, feMerge and feMergeNode. 
https://www.w3.org/TR/SVG/filters.html#AnExample

**Comment by msand** [comment]
Work on filters tracked here: #150

**Comment by terrorpixel** [comment]
My solution was to use foreignobject inside my SVG object:
[https://github.com/react-native-community/react-native-svg#foreignobject](https://github.com/react-native-community/react-native-svg#foreignobject)

With foreignobject you can place a <View> and use a regular shadow style.

**Comment by sa8ab** [comment]
@terrorpixel Can you provide an example please?

**Comment by Ayush6543** [comment]
I think this should work
shadowColor: "#000",
shadowOffset: {
	width: 0,
	height: 2,
},
shadowOpacity: 0.25,
shadowRadius: 3.84,
I think this should work

**Comment by jstheoriginal** [comment]
> I think this should work
> 
> ```
> shadowColor: "#000",
> shadowOffset: {
> 	width: 0,
> 	height: 2,
> },
> shadowOpacity: 0.25,
> shadowRadius: 3.84,
> ```
> 
> The above code can be used to implement the box shadow property in react native.

These 4 properties only work on iOS, in case anyone sees this. Android only supports `elevation`, which is a number and no color/other options.

**Comment by yamankatby** [comment]
> My solution was to use foreignobject inside my SVG object:
> https://github.com/react-native-community/react-native-svg#foreignobject
> 
> With foreignobject you can place a View with a regular shadow style.

But the shadow will not take the shape of the `SVG`

**Comment by sayan-wholewave** [comment]
const AnimatedCircle2 = Animated.createAnimatedComponent(Circle);

<AnimatedCircle2
          cx={100}
          cy={100}
          r={24}
          stroke='rgba(0,0,0,0.3)'
          strokeWidth={4}
          strokeLinecap="round"
          fill="rgba(0,0,0,0.3)"
          opacity={1}
        />
        <AnimatedCircle2
          cx={100}
          cy={100}
          r={22}
          stroke='#fff
          strokeWidth={1}
          strokeLinecap="round"
          fill="#fff"
          opacity={1}
        />

create two separate same shapes and then overlap with each other. this is the current solution.
