### ISSUE TITLE
<Use> cannot take numeric width/height

### ISSUE THREAD

**Issue by msageryd** [react-native-community/react-native-svg#637]
I'm not really sure if this is supposed to work. But I use numeric values on other element types with success. It would be great if this worked everywhere.

This works:
```
<Use href={'#MySymbol'} x={0} y={0} width={'100'} height={'100'} />
```

This does not work:
```
<Use href={'#MySymbol'} x={0} y={0} width={100} height={100} />
```

![image](https://user-images.githubusercontent.com/4483085/38269790-c84fbf80-3781-11e8-98ba-345747eccfbe.png)

**Comment by msand** [comment]
Can you test with this one? https://github.com/msand/react-native-svg/commit/5e1bb859fc281d89feac37dcc3459fcd078e0f91

**Comment by msageryd** [comment]
It works great!
