### ISSUE TITLE
ERROR : Native component for "RNSVGLinearGradient" does not exist

### ISSUE THREAD

**Issue by mohammad-goldast** [react-native-community/react-native-svg#639]
Hello everyone, when i use `react-native-shadow` with `react-native-svg` , i got same error like this :

>>Invariant Violation: Native component for "RNSVGLinearGradient" does not exist

>>This error is located at:
>>in RNSVGLinearGradient (at LinearGradient.js:29)
>>in LinearGradient (at BoxShadow.js:63)
>>in RNSVGDefs (at Defs.js:8)
>>in Defs (at BoxShadow.js:62)
>>in RNSVGSvgView (at Svg.js:94)
>>in Svg (at BoxShadow.js:61)
>>in RCTView (at View.js:112)
>>in View (at BoxShadow.js:60)
>>in BoxShadow (at Card.js:18)
>>in Card (at loginForm.js:12)
>>in LoginForm (at authPage.cmp.js:90)
>>in RCTView (at View.js:112)
>>in View (at authPage.cmp.js:72)
>>in AuthPage (created by Connect(AuthPage))
>>in Connect(AuthPage) (at Navigation.js:83)
>>in Provider (at Navigation.js:82)
>>in _class2 (at renderApplication.js:35)
>>in RCTView (at View.js:112)
>>in View (at AppContainer.js:102)
>>in RCTView (at View.js:112)
>>in View (at AppContainer.js:122)
>>in AppContainer (at renderApplication.js:34)

I installed this package by : `npm i --save react-native-shadow` and `npm i --save react-native-svg`.

Here is my code :
`const Card = ({style, children}) => { const shadowOpt = { width:100, height:100, color:"#000", border:2, radius:3, opacity:0.2, x:0, y:3, style:{marginVertical:5} } return( <BoxShadow setting={shadowOpt}> <View style={[styles.cardStyle, style]} > { children } </View> </BoxShadow> ) }`

Also maybe need these information :
`"react": "16.0.0", "react-native": "0.51", "react-native-shadow": "^1.2.2", "react-native-svg": "^6.3.1",`

**Comment by danielland85** [comment]
i have same issue.

**Comment by artemgrygor** [comment]
Same here

**Comment by msand** [comment]
Have you linked it? https://github.com/react-native-community/react-native-svg/blob/master/README.md#installation

2. Link native code

react-native link react-native-svg

**Comment by vineonardo** [comment]
I've the same issue, and I'm yet to find a solution.

**Comment by jgiovanni** [comment]
same here, it is happening with other libraries depending on this.

**Comment by javalong** [comment]
i have the same issue

**Comment by marshallamey** [comment]
Having the same issue using 'react-native-chart-kit'
Linked native code manually per the instructions
I can see a related file in my build folder, but the native component is still missing.
...\android\app\build\generated\source\r\debug\com\horcrux\svg\R.java

**Comment by msand** [comment]
Has anyone found a solution? Or could someone make a minimal replication?

**Comment by HengCC** [comment]
Same problem ,  i've linked native code through `react-native link react-native-svg` 

it's still throw an error: 

```
Invariant Violation: requireNativeComponent: "RNSVGLinearGradient" was not found in the UIManager.
```

**Comment by SM-Wistful** [comment]
Oh, this was miserable! I don't really remember how I fixed it, besides messing with the source code and recompiling for a few hours :/ 

In terms of linking this is by far the worst library I have had to deal with. When I Archive my Xcode project for submission to the app store, I have to quickly drag RNSVG.a into the build folder manually or else it fails. Euch.

**Comment by tuluffy** [comment]
I have solve this error(must be manual linking, otherwise it will go wrong). 
The steps are as follows：
1.drag RNSVG.xcodeproj into Libraries directory in XCode.
2.add libRNSVG.a into <Link Binary With Libraries>
3.rnpm link react-native-svg

restart project in IOS simulator,it's OK

**Comment by msand** [comment]
So, this is probably just linking issues, not a problem with the library, closing...

**Comment by heraldia** [comment]
react-native link react-native-svg DOES solve the problem for me :)

**Comment by ffMathy** [comment]
I am also having this issue.

**Comment by j0nd0n7** [comment]
In my case, I linked and run-android, the app launched, however I didn't realize gradle was downloading dependencies and got the error. So check that

**Comment by jackw-kounta** [comment]
When running link, you make changes to the native build files - so a simple refresh/reload will not make it work. 

I ran link, reopened Xcode and ran again with no issues.

**Comment by CipherAlo** [comment]
I've followed the instructions in the manually section of the documentation and started working. 

https://github.com/react-native-community/react-native-svg/blob/master/README.md#installation

hope this works for some of you.

**Comment by danipralea** [comment]
I'm also having this issue. Even after manually linking, installing the pods etc.

**Comment by xiaoliukuibu** [comment]
> `react-native link react-native-svg` dont solve the problem for me
> :(

pod install

**Comment by mrtkprc** [comment]
Following instructions worked for me. (React Native 0.62)
1. Stop command ``npm run start`` or ``yarn start``.
2. Execute command ``react-native link react-native-svg``
3. Uninstall application from emulator and close emulator.
4. Re-run ``npm run start`` or ``yarn start`` and you can start your emulator.

**Comment by boerdjamin** [comment]
Same issue on "react-native": "0.61.5" (Should be linked automatically). Android only

**Comment by cupid20103** [comment]
when I am using Expo, how to solve this problem?
