### ISSUE TITLE
Error running on Android v 6.1.0

### ISSUE THREAD

**Issue by jarrx** [react-native-community/react-native-svg#642]
Trying to run an app that uses SVG on android but keep getting error:
**Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.**

react-native: ^0.49.3
react-native-svg: ^6.1.0

Using another library that is dependent of react-native-svg v. 6.1.0 so I can't use an older version of svg.

Any suggestions on how to solve this?

**Comment by szuwest** [comment]
/Users/west/Documents/workspace/react-native/VprScene/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:23: 错误: 找不到符号
import com.facebook.react.uimanager.ReactShadowNodeImpl;
                                   ^
  符号:   类 ReactShadowNodeImpl
  位置: 程序包 com.facebook.react.uimanager
/Users/west/Documents/workspace/react-native/VprScene/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:109: 错误: 找不到符号
        ReactShadowNodeImpl node = getShadowNode();
        ^
  符号:   类 ReactShadowNodeImpl
  位置: 类 SvgView
/Users/west/Documents/workspace/react-native/VprScene/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:115: 错误: 找不到符号
                    ReactShadowNodeImpl nodeChild = node.getChildAt(j);
                    ^
  符号:   类 ReactShadowNodeImpl
  位置: 类 SvgView
3 个错误
:react-native-svg:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by sibelius** [comment]
we can close this
