### ISSUE TITLE
android fill image not suppert

### ISSUE THREAD

**Issue by LightningVII** [react-native-community/react-native-svg#644]
import resolveAssetSource from 'resolveAssetSource'
import { ART } from 'react-native'

const pattern = new ART.Pattern(
      resolveAssetSource(require('../../../static/images/img.jpeg')),
      10,
      20,
      40,
      20
    )

<ART.Surface width={width + triangle.width} height={height}>
              <ART.Shape
                d={path}
                fill={pattern}
                strokeWidth={0}
              />
            </ART.Surface>

Error
Error while updating property 'fill' in shadow node of type: ARTShape java.lang.String cannot be cast to java.lang.Double

help me!!!!!

**Comment by LightningVII** [comment]
![62cb3682b0975f25a9ad0dab5f29a611](https://user-images.githubusercontent.com/13807519/38466787-e635e94c-3b60-11e8-84ee-28229f13d11f.jpg)

**Comment by msand** [comment]
Not related to this library.
