### ISSUE TITLE
'XCTest/XCTest.h' file not found

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-svg#647]
### Problem

Trying to run an react-native 0.55 app using cocoa pods, it builds the other dependencies but fails on react-native-svg due to this error:

`node_modules/react-native-svg/ios/PerformanceBezier/PerformanceBezierTests/PerformanceBezierClockwiseTests.m:9:9: 'XCTest/XCTest.h' file not found`

`node_modules/react-native-svg/ios/PerformanceBezier/PerformanceBezierTests/PerformanceBezierAbstractTest.m:9:9: 'XCTest/XCTest.h' file not found`

![image](https://user-images.githubusercontent.com/619186/38700021-1ffe74ac-3e70-11e8-829f-ec36d9b249a8.png)

**Comment by brunolemos** [comment]
### Solution

Add `RCTTest` to your `Podfile`:

```diff
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
+    'RCTTest',
  ]
```

**Comment by michaeldebarros** [comment]
I have the same issue, but I am not running CocoaPods.
