### ISSUE TITLE
Error while updating property 'strokeWidth' in shadow node of type: RNSVGPath

### ISSUE THREAD

**Issue by Alifarmand** [react-native-community/react-native-svg#653]
I get this error only on Android, and the weird part is that I am not using any strokes at all. 
Can anyone help with this?

It also says TypeError: expected dynamic type 'double', but had type 'string'

Everything is working fine on the iOS simulator, so I don't know what to try to do from here.
I am using the following version: 
```
"react": "16.2.0",
"react-dom": "^16.3.1",
"react-native": "0.52.0",
"react-native-svg": "6.3.1",
```

**Comment by msand** [comment]
Try rebuilding your native bundle

**Comment by Alifarmand** [comment]
@msand How do you mean?
I did try yarn start --clear-cache

**Comment by Alifarmand** [comment]
@msand I haven't build the application yet, so I don't have such folder. I am scanning the QR code of expo with my android phone and running an iOS simulator.

**Comment by msand** [comment]
Ahaa, then, upgrade expo, and remove the dependency on react-native-svg or sync the version with the expo bundled one, it comes pre-built inside expo and the javascript of it needs to have the same api for the data it sends over the bridge as the native part on the other side of it. Going from v5 to v6 has a breaking change, thus the major semver change.

**Comment by vivekkadu** [comment]
.

**Comment by msand** [comment]
Upgrade to the latest Expo version, and remove react-native-svg from your dependencies (its comes with batteries included in Expo), instead import it from expo like this:

```js
import { Svg } from 'expo';
const {
  Circle,
  Ellipse,
  G,
  Text,
  TSpan,
  TextPath,
  Path,
  Polygon,
  Polyline,
  Line,
  Rect,
  Use,
  Image,
  Symbol,
  Defs,
  LinearGradient,
  RadialGradient,
  Stop,
  ClipPath,
  Pattern,
  Mask,
} = Svg;
```

**Comment by msand** [comment]
Seems like an issue with an old version in an old expo. Closing...
