### ISSUE TITLE
Line with transparent fill

### ISSUE THREAD

**Issue by jfrense** [react-native-community/react-native-svg#655]
I have been trying to get a 'hollow' line to display in the sense that the stroke color only applies to the border and the fill is transparent. I have many of the component options but none seem to work. Is it possible what i am trying to do?

```
<Line
        x1="30"
        y1="15"
        x2={this.state.position}
        y2="15"
        stroke="blue"
         //fill="white"
         //fillRule="nonzero"
        fillOpacity={1}
        strokeWidth="15"
        strokeLinecap="round"
        
    />
```

**Comment by msand** [comment]
Are you looking for fill="none" perhaps?
