### ISSUE TITLE
can't load image from outer source

### ISSUE THREAD

**Issue by yassir1994** [react-native-community/react-native-svg#660]
i am trying to load image from http source and image was not loaded?
`      <Image
                    x="0" y="0"
                    width="50"
                    height="40"
                    href={{uri: 'https://fluent-panda.appspot.com.storage.googleapis.com/dumbbell.svg'}}
                />`

**Comment by corasan** [comment]
were you able to solve this?

**Comment by msand** [comment]
Docs have been updated: https://github.com/react-native-community/react-native-svg#use-with-svg-files
With react-native-svg-transformer you can now do this:
```jsx
import Logo from "./logo.svg";
const myApp = () => <Logo width={120} height={40} />
export default myApp
```

**Comment by msand** [comment]
Oh this question was for urls, well, docs have been updated for that as well: https://github.com/react-native-community/react-native-svg#use-with-content-loaded-from-uri
```jsx
import * as React from 'react';
import SvgUri from 'react-native-svg-uri';

export default () => (
  <SvgUri
    width="200"
    height="200"
    source={{
      uri: 'http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg',
    }}
  />
);
```

**Comment by SirCameron** [comment]
@msand 
```
<SvgUri
    width="200"
    height="200"
    uri="http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg"
  />
```
