### ISSUE TITLE
How to get <Text> width?

### ISSUE THREAD

**Issue by shuijinliuxi** [react-native-community/react-native-svg#666]
I want to draw backgournd for a Text, but I can not get the width and height for Text.

**Comment by mcihan** [comment]
I have the same problem, are there any solution ?

I tried calculate text width using below javascript code convert to React-Native, but React.createElement() didn't work.

```
function getTextWidth(text, font) {
    var canvas = getTextWidth.canvas || (getTextWidth.canvas = document.createElement("canvas"));
    var context = canvas.getContext("2d");
    context.font = font;
    var metrics = context.measureText(text);
    return metrics.width;
}
```

**Comment by msand** [comment]
You can use onLayout to get the dimensions, or UIManager.measure
