### ISSUE TITLE
Why are the width and height properties required for the SVG in the Typescript definition file?

### ISSUE THREAD

**Issue by betko** [react-native-community/react-native-svg#667]
In the `index.d.ts` file the width and the height properties of the `SVG` component are mandatory. But in the JavaScript implementation these props are optional.  

In my application I use flex to scale the SVG component to a proper size so I don't want to set the height and width, but in the newer version I am not able to skip setting the concrete sizes. 

May I ask for a short explanation why did you changed the optional props to required?

Currently I use the following versions:

```
"react": "16.3.2",
"react-native": "0.55.3",
"react-native-svg": "6.3.1",
```

**Comment by msand** [comment]
Please feel free to provide a PR to change this. Not sure why this would've changed.
