### ISSUE TITLE
Type Definitions: Make <Use/> width/height optional

### ISSUE THREAD

**Issue by seanadkinson** [react-native-community/react-native-svg#670]
Latest typescript definitions are requiring width/height on a `<Use/>` element.  I wasn't providing these before, and it was working just fine.  Should they be required?  Or can they go back to being optional?

Current def:
```
export interface UseProps extends CommonPathProps {
  href: string,
  width: string,
  height: string,
}
```

Possibly should change to:
```
export interface UseProps extends CommonPathProps {
  href: string,
  width?: string,
  height?: string,
}
```

Happy to put up a PR if this is the desired change.  Thanks!

**Comment by msand** [comment]
This change has already been made, closing.
