### ISSUE TITLE
Linking is broken for React 0.55.3

### ISSUE THREAD

**Issue by narciero** [react-native-community/react-native-svg#671]
Linking via `react-native link react-native-svg` does not work using the latest version of React (0.55.3).

Steps to reproduce:
- Create a new react native project `react-native init MyProject`
- `npm install --save react-native-svg`
- `react-native link react-native-svg`

Output will say linking was successful. In `App.js` i have sample code:

```
import { Svg, Rect } from 'react-native-svg';

export default class App extends Component {
   render() {
      return (
         <View style={styles.container}>
            <Svg
               width="200"
               height="60">
               <Rect
                  x="25"
                  y="5"
                  width="150"
                  height="50"
                  fill="rgb(0,0,255)"
                  strokeWidth="3"
                  stroke="rgb(0,0,0)" />
            </Svg>
         </View>
      );
   }
}
```

When running with `react-native run-ios` i get the following error:
![simulator screen shot - iphone 6 - 2018-04-28 at 17 28 55](https://user-images.githubusercontent.com/9964211/39401011-b387f5fe-4b09-11e8-8f0f-5096184471c0.png)

**Comment by remigallego** [comment]
I have the same issue with react-native 0.55.1

**Comment by kdenz** [comment]
Same issue here

**Comment by msand** [comment]
Linking issue, not issue with the library.
