### ISSUE TITLE
Using <Text> and/or <Tspan> causes Crash

### ISSUE THREAD

**Issue by oceanminded** [react-native-community/react-native-svg#672]
Everything else works but rendering Text and TSpan elements cause my react-native application to crash in Expo. I used create-react-native-app and have the following relevant versions:

    "react": "16.0.0",
    "react-native": "0.50.x",

I've tried using react-native-svg 6.0.0, 6.2.0, and 6.3.1 and it consistently crashes.

**Comment by ishouty** [comment]
Why is this closed? Has any one found a solution for this...

**Comment by SuperThinking** [comment]
Please post the solution.

**Comment by SuperThinking** [comment]
@ishouty Instead of using numbers for example => fontSize={70}, use fontSize="70".
It prevented all the crashes for me.
