### ISSUE TITLE
use svg as mask

### ISSUE THREAD

**Issue by rareslupascu** [react-native-community/react-native-svg#676]
Hi

did anyone try or tried to ever build an svg mask for a view for ex?
let's assume u have a custom shape built using react-native-svg and u want to fill it with content (View, Text or Image)

anyone tried to achieve this? does it sound too SF?

thanks

**Comment by msand** [comment]
You can position the svg absolutely on top of the content, until we have foreignObject support: https://github.com/react-native-community/react-native-svg/issues/447
