### ISSUE TITLE
iOS allows Svg width height at 100% 100% for auto-scaling, Android does not

### ISSUE THREAD

**Issue by ericjames** [react-native-community/react-native-svg#677]
iOS allows setting Svg to 100% 100% for auto-scaling, meaning the SVG will automatically scale to the container dimensions.  Android can't deal with this and requires actual pixel dimensions.  

However the error that actually came up was thrown by a RNSvgPath saying the strokeWidth expected a double but got a string.   I had to deconstruct my SVG down to its bits to figure this out.

**Comment by msand** [comment]
This is fixed in at least v8 and v7, probably the latest v6 as well
