### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by sanealytics** [react-native-community/react-native-svg#682]
Hi there,

I am painting many SVG Images into an SVG. They overlap each other in the order they were rendered.
I would love to know:

-  Is it possible to change the attribute of an existing SVGImage element's z-index so that it comes to top (e.g when I touch it, I can enlarge it but it still 'hides' behind newer elements.
- Is it possible to make an element that is ALWAYS on top?

Thanks

**Comment by msand** [comment]
React-Native supports zIndex https://facebook.github.io/react-native/docs/layout-props#zindex try using it either on the root Svg element or wrap that in a View and set it on that. Its something you should probably avoid, and just use the document order if possible.
