### ISSUE TITLE
Touch enents on Android phone don't work but work in the emulator

### ISSUE THREAD

**Issue by sanealytics** [react-native-community/react-native-svg#683]
Hi there,

I am following your pinch and zoom example with some tweaks. I'd like to let the individual elements that were painted respond to touch if they are individually touched.

To do that, I had modified some entries for PanResponder. These settings work on android simulator, but do not with the phone :(

```
this._panResponder = PanResponder.create({
      onPanResponderGrant: () => {},
      onPanResponderTerminate: () => {},
      onMoveShouldSetPanResponder: () => true,
      onStartShouldSetPanResponder: () => false,
      onShouldBlockNativeResponder: () => true,
      onPanResponderTerminationRequest: () => true,
      onMoveShouldSetPanResponderCapture: () => true,
      onStartShouldSetPanResponderCapture: () => false,
      onPanResponderMove: evt => somefunc1()
      onPanResponderRelease: () => somefunc2()
}
```

I realize this isn't strictly a react-svg question but looking for guidance or where I should I should ask.

Thanks

**Comment by ShaMan123** [comment]
jumping in => Are you getting touch fired on polylines?

**Comment by sanealytics** [comment]
I'm sorry, I don't know what polylines are.
For example, I want the pinch events to be handled by the panresponder (to allow zoom via translate), but allow folks to click on the individual SVG groups underneath (Images in my case). This all works in simulator, just not on the actual device.

**Comment by msand** [comment]
Is this still an issue with the latest version? In that case, please provide a full replication.
