### ISSUE TITLE
[Animated] useNativeDriver is not supported for most all components.

### ISSUE THREAD

**Issue by ATShiTou** [react-native-community/react-native-svg#684]
I'd like to use the `useNativeDriver` option on `Animated.event` to improve its performance. But it does not work.

Any suggestions ?

**Comment by dapicester** [comment]
@ATShiTou can you post your a solution to the issue?

**Comment by ATShiTou** [comment]
It does not support.

**Comment by msand** [comment]
I've added support for animation of transforms using the same syntax as react-native views now: https://github.com/react-native-community/react-native-svg/issues/803#issuecomment-428815111
And also for any number accepting properties. Any help in testing the latest commit in the master branch would be much appreciated!
