### ISSUE TITLE
Android jumbled text.

### ISSUE THREAD

**Issue by swanie42** [react-native-community/react-native-svg#686]
"react-native-svg": "^6.3.1"

Everything works great on iOS.  For some reason the text gets jumbled in android.

Here is my code and some screenshots for comparison

<img width="95" alt="screen shot 2018-05-13 at 3 34 26 pm" src="https://user-images.githubusercontent.com/1048176/39971982-31ada734-56c3-11e8-84dc-dda858cec423.png">
<img width="84" alt="screen shot 2018-05-13 at 3 31 05 pm" src="https://user-images.githubusercontent.com/1048176/39971983-31bd5de6-56c3-11e8-864d-efcb3fb4b106.png">

 <View style={{marginRight:10, justifyContent:'center', alignItems:'center'}}>
    <Svg
        height="105"
        width="105"
        justifyContent="center"
        alignItems="center"
    >
     <Circle
            cx="53"
            cy="53"
            r="50"
            stroke="black"
            strokeWidth="2"
            fillOpacity="0"
        />
        <Circle
            cx="53"
            cy="53"
            r="35"
            stroke="black"
            strokeWidth="2"
            fillOpacity="0"
        />
         <G y="53" x="53">
         
         <Path id="CityPath"
               d="M 0,1 C -0.5523, 1   -1, 0.5523    -1,0 C -1, -0.5523 -0.5523, -1 0,-1 C 0.5523, -1 1, -0.5523 1,0 C 1, 0.5523 0.5523, 1 0,1"
                stroke="none" fill="none" scale="35,35" strokeWidth="0.1"/>
          <Text fill="black" fontSize = "0.37" textAnchor="middle" fontFamily = "helvetica"  >
          <TextPath textAnchor="middle" startOffset="50%"  scale="38,38" href="#CityPath">{cityNameMod}</TextPath>
          </Text>
          <Path id="SBPath"
              d="M -1,0 C -1, 0.5523  -0.5523, 1  0,1 C 0.5523,1  1,0.5523  1,0"
               stroke="none" fill="none" scale="50,50" strokeWidth="0.1"/>
          <Text fill="black" fontSize = "0.30" textAnchor="middle" fontFamily = "helvetica"  >
            <TextPath textAnchor="middle" startOffset="50%"  scale="49,49" href="#SBPath">{displayLevel}</TextPath>
          </Text>
          
          </G>
       
    </Svg>
    <Image source={sbIconGreen} style={styles.sbIconGreen} />
    </View>

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
