### ISSUE TITLE
E/ReactNativeJS: Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by habeebrahmanpt** [react-native-community/react-native-svg#690]
E/ReactNativeJS: Tried to register two views with the same name RNSVGPath

react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by sakuramoon0203** [comment]
I have meet the same question, how do yo solve this problem?

**Comment by NJQter** [comment]
I have meet the same question, how do yo solve this problem?

**Comment by ankitjaiswal1994** [comment]
I have meet the same question, how do yo solve this problem?

**Comment by raymondjacobson** [comment]
I have meet the same question, how do yo solve this problem?
