### ISSUE TITLE
Android Image:imageUrl has changed, but it is not rendered correctly, always rendering the previous imageUrl.

### ISSUE THREAD

**Issue by CleverMod** [react-native-community/react-native-svg#691]
<Svg
                    height={this.length * 4}
                    width={this.props.width}
                >
                    <Defs>
                        <ClipPath id="clip">
                            <Polygon points={polygonPoint}
                                     fill="lime"
                                     stroke="purple"
                                     strokeWidth="1"/>
                        </ClipPath>
                    </Defs>
                    <Image
                        x="0%"
                        y="0%"
                        width="100%"
                        height="100%"
                        preserveAspectRatio="xMidYMid slice"
                        opacity="1"
                        href={this.props.imageUrl}
                        clipPath="url(#clip)"
                    />
                 </Svg>

iOS is work,but Android have this problem

**Comment by adam-s** [comment]
The Image is cached and doesn't rerender if the shallow compare of the component is the same. In this case { uri: '' } and {uri: 'https:image.jpg'} don't trigger a rerender. The solution is to add a dynamic key to the component to let React know to rerender.

````
          <Image
            y="0"
            x="0"
            width={sideLength}
            height={sideLength}
            href={{
              uri: imageUri,
            }}
            preserveAspectRatio="xMidYMid slice"
          />
````
becomes
````
          <Image
            key={imageUri}
            y="0"
            x="0"
            width={sideLength}
            height={sideLength}
            href={{
              uri: imageUri,
            }}
            preserveAspectRatio="xMidYMid slice"
          />
```

**Comment by KingDragonRao** [comment]
I had add a dynamic key  but doesn't work...

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
