### ISSUE TITLE
Lazy loading with SVG

### ISSUE THREAD

**Issue by jgfidelis** [react-native-community/react-native-svg#694]
We have a component with many SVG icons, for example, 11 icons.

On Android, when pressed to navigate to that screen, because of the animations and rendering, the app could freeze for seconds. To fix this we tried doing:

```
class LazySVGIcon extends React.PureComponent<Props> {
  state = {
    shouldRender: false,
  };

  setShouldRender = () => {
    this.setState({
      shouldRender: true,
    });
  };

  componentDidMount() {
    InteractionManager.runAfterInteractions(this.setShouldRender);
  }

  render() {
    if (!this.state.shouldRender) return <ShimmerPlaceHolder autoRun={true} visible={false} height={30} width={30} />;
    return <SVGIcon {...this.props} />;
  }
}
```

This way, at least the animations runs smoothly. But after the animations are done and shouldRender is set to true, the placeholder component stops animating, becomes a blank square and keeps like this while the SVG is rendering.

Any one has a better pattern/solution?

**Comment by msand** [comment]
Render both elements (icon and placeholder), add onLayout to the svg element, (add to state and) set hidePlaceholder to true, and only render the icon when this is the case.
