### ISSUE TITLE
prerender svg

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-svg#697]
We have some huge svg, and it takes a lot of time to render it on android

how can we prerender svg, so we can make it faster?

**Comment by msand** [comment]
You could use headless chrome (if you're using svgs) to render a big enough png and transform it to look the same as the vector version will output, alternatively use an emulator and one of the screenshot libs like e.g. https://github.com/gre/react-native-view-shot this could even be made into a server side raster pre rendering thing with proper caching if needed.

**Comment by msand** [comment]
Alternatively the toDataURL base64 output could be used, move the svg offscreen and use something like this in the background before the output is needed and then use a react native image 
https://github.com/magicismight/react-native-svg-example/blob/master/examples/Svg.js#L163

**Comment by msageryd** [comment]
@msand Could it be possible that `toDataURL` is broken in the latest version? I think I got it right, but I get the following red screen. I haven't tried this with an earlier version yet. Should I try with an earlier RNSVG version, or do you have any clue of what could be wrong?

I'm calling `toDataURL` in `componentDidUpdate`. At this stage in the lifecycle everything should be ready, shouldn't it?

![image](https://user-images.githubusercontent.com/4483085/46830095-f513a680-cd9f-11e8-9d27-952660ed6837.png)

**Comment by msand** [comment]
Could you try doing it in onLayout? I haven't tested toDataUrl for a long time

**Comment by msageryd** [comment]
It works in onLayout. Thanks a bunch!
