### ISSUE TITLE
Touch events in Polyline fire only when clicking the component's fill

### ISSUE THREAD

**Issue by ShaMan123** [react-native-community/react-native-svg#701]
I've been playing around with this module (in android AVD), hoping it will answer my app's needs.
My app uses polylines to highlight stuff. Then the user touches the highlights for an action to take place.
So... the problem is that the touch event is emitted only from the fill of the polyline/path component, but not from the stroke. This makes sense when dealing with polygons, circles, rects etc. BUT makes no sense when dealing with <Polyline>/<Path>.
I tested to see if it is a matter a stroke width not being able to capture the touch - it isn't. Size doesn't matter ;)
The only workaround I can think of svg-wise is to group (<G>) lots of circles to create a line, but this stinks.
Any suggestions?
By the way, the HTML svg library does emit touch events correctly only from the stroke of the element.

-----
I read through the issues hoping to find an answer. I've found issuses regarding touch emittion bugs - is this related in any way?

Thanks!

**Comment by msand** [comment]
Can you post a full replication? I've made some changes to the touch handling in the most recent commit, so it might have been fixed with that as well.

**Comment by ShaMan123** [comment]
```
<Svg
    height="100"
    width="100"
>
    <Polyline
        points="10,10 20,12 30,20 40,60 60,70 95,90"
        fill="none"
        stroke="black"
        strokeWidth="3"
        onPress={()=>{ console.log('Polyline press on contour or fill?')}}
    />
</Svg>

```

**Comment by msand** [comment]
I think I've fixed the issue now, please try again with the latest commit from the master branch and e.g. this code:
```jsx
import React from "react";
import { Button, Dimensions, StyleSheet, View } from "react-native";
import Svg, { Polyline } from "react-native-svg";

const { width, height } = Dimensions.get("window");

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg height={height} width={width} viewBox="0 0 100 100">
          <Polyline
            points="10,10 20,12 30,20 40,60 60,70 95,90"
            fill="none"
            stroke="black"
            strokeWidth="10"
            onPress={() => {
              console.log("Polyline press on contour or fill?");
            }}
          />
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "beige",
  },
});

```

**Comment by msand** [comment]
I've improved touch handling further now, can you test this branch: https://github.com/react-native-community/react-native-svg/compare/SVGLength

**Comment by msand** [comment]
If you want hitSlop, then you can wrap the svg root in a TouchableOpacity or something similar, the onPress handlers inside the svg root require exact match with either the stroke or the fill of something visible.

**Comment by ShaMan123** [comment]
It's been a long time sine I've tried this out.
Seems that once again this is an issue, `v12.1.0`
