### ISSUE TITLE
getNativeElement() is undefined

### ISSUE THREAD

**Issue by ShaMan123** [react-native-community/react-native-svg#702]
When trying to setNativeProps on a <Polyline> or <Polygon> I get an error:
`undefined is not a function (evaluating this.root.getNativeElement())`

I went to the source files and found that both <Polyline> and <Polygon> have this function in the  `setNativeProps` function but couldn't understand where it is defined.

Tried switching this: 
`setNativeProps = (...args) => {
        //noinspection JSUnresolvedFunction
        this.root.getNativeElement().setNativeProps(...args);
    };`

with this: 
`setNativeProps = (...args) => {
        //noinspection JSUnresolvedFunction
        this.root.setNativeProps(...args);
    };`

No luck :( It didn't update the points.

**Comment by ShaMan123** [comment]
It works with <Path>.... but a bit slow

**Comment by ShaMan123** [comment]
It works with `<Path>` ... but is slow

**Comment by ShaMan123** [comment]
Found the problem - there is no conversion made from `<Polyline>` or `<Polygon>` `points` prop to `d` prop of `<Path>`. Meaning that passing a valid `d` prop to `setNativeProps()` does the work.... would love suggestions on making it more responsive!
I will add a PR

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
