### ISSUE TITLE
[Android] Arc Path is incorrect on Android

### ISSUE THREAD

**Issue by ATShiTou** [react-native-community/react-native-svg#706]
A strange issue on Android.
 I'm trying to draw an arc path by this code:

```
<Svg width={400} height={200}>
    <Path
          d="M200 50A50 50 90 0 0 200 150 L200 100Z"
          fill="red"
          stroke="white"
          strokeWidth={1}
        />
<Path
          d="M200 150A50 50 270 0 0 247.55282581475768 84.54915028125261 L200 100Z"
          fill="green"
          stroke="white"
          strokeWidth={1}
        />
<Path
          d="M247.55282581475768 84.54915028125261A50 50 378 0 0 200 50 L200 100Z"
          fill="blue"
          stroke="white"
          strokeWidth={1}
        />
</Svg>
```

It works well on iOS, but a strange issue on Android. Just like this:
![2018-06-06 10 05 30](https://user-images.githubusercontent.com/38748693/41013621-2e60ce9c-6971-11e8-972d-2c6c3f934a28.png)

Environment:
Dev System: Mac 10.13.4 (17E202)
react: 16.3.1
react-native: 0.55.3
react-native-svg: 6.3.1
Android System: 7.1.2  8.0
Android Dev: both real-devices and simulator.

**Comment by ATShiTou** [comment]
I have tried my arc path arguments on a svg editor, there is no problem.

**Comment by douo** [comment]
I think i found a solution. 

![image](https://user-images.githubusercontent.com/743074/41037679-8e87a444-69c6-11e8-8def-4a6299c0ceca.png)

**Comment by ATShiTou** [comment]
How did you do that?

**Comment by ATShiTou** [comment]
I will use victory-native instead.

**Comment by douo** [comment]
There is a bug in [PropHelper. PathParser](https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/PropHelper.java)

**Comment by douo** [comment]
There is already a pr #704  to fix this problem

duplicate issue #325

**Comment by ATShiTou** [comment]
Thank you very much!
