### ISSUE TITLE
Error: You are setting the style `{ rotation: ... }` as a prop. You should nest it in a style object.

### ISSUE THREAD

**Issue by designingSparks** [react-native-community/react-native-svg#714]
With reference to [this](https://github.com/react-native-community/react-native-svg/issues/180) thread, I have successfully implemented the animation based on the comment by msand on 5 March 2018. However, when I attempt to animate the rotation property using the same technique, I get the following error:

```
<AnimatedCircle
            cx="50"
            cy="50"
            r="10"
            stroke="blue"
            strokeWidth="1"
            fill="white"
            rotation="-10" // {strokeWidth}, an animated value, causes an error!
            origin="100, 50"
 />
```

**Error:** You are setting the style `{ rotation: ... }` as a prop. You should nest it in a style object.

What could be the problem?

**Comment by msand** [comment]
The rotation attribute isn't standard, the transform attribute has the rotation transform, which ends up affecting the transform matrix which is sent over the native bridge, but the matrices aren't currently animatable, except by normal state transitions, or using setNativeProp with matrices. Animating these would require refactoring to use the react-native matrices and style property handling, or some changes to react-native. As a workaround, you can wrap the parts you want to animate in separate View wrapped Svg components, (and if need be, a foreground and background Svg component), layer and position them appropriately, and, animate these using the plain react-native Animated api with View styles and transforms.

**Comment by msand** [comment]
I've added support for animation of transforms using the same syntax as react-native views now: https://github.com/react-native-community/react-native-svg/issues/803#issuecomment-428815111
And also for any number accepting properties, please try again.
