### ISSUE TITLE
Apple mach-O linker error when building react-native project in xcode

### ISSUE THREAD

**Issue by bhaskartalluri999** [react-native-community/react-native-svg#715]
while building react-native project in xcode following errors are occured,
Apple mach-O linker error:
clang: error: unknown argument: '-no_deduplicate'

clang: error: no such file or directory: '/Users/pradeepkrish/Library/Developer/Xcode/DerivedData/projectname-bcvkbiqlzwpsqadbqmrlcqgqzvzz/Build/Intermediates.noindex/projectname.build/Debug-iphonesimulator/InnovaZones.build/Objects-normal/x86_64/InnovaZones_lto.o'

clang: error: no such file or directory: '2'
clang: error: no such file or directory: '/Users/pradeepkrish/Library/Developer/Xcode/DerivedData/projectname-bcvkbiqlzwpsqadbqmrlcqgqzvzz/Build/Intermediates.noindex/projectname.build/Debug-iphonesimulator/projectname.build/Objects-normal/x86_64/projectname_dependency_info.dat'

how can i solve this.Any suggestion?

**Comment by msand** [comment]
Seems unrelated to this library.
