### ISSUE TITLE
Can't set color width opacity

### ISSUE THREAD

**Issue by littleeason** [react-native-community/react-native-svg#721]
`<Svg width="100" height="100">`
 `                           <Defs>`
  `                              <LinearGradient id="grad" x1="0" y1="0" x2="170" y2="0">`
   `                                 <Stop offset="0" stopColor="rgba(0,0,0,0)" stopOpacity="0" />`
  `                                  <Stop offset="1" stopColor="rgba(0,0,0,1)" stopOpacity="1" />`
  `                              </LinearGradient>`
 `                           </Defs>`
 `                           <Rect `
 `                               x="0"`
 `                               y="0"`
 `                               width="100"`
 `                               height="100"`
  `                              fill="url(#grad)"`
  `                          />`
  `                      </Svg>`

![image](https://user-images.githubusercontent.com/37935039/41887234-6a198066-7932-11e8-81b2-be4399c38c28.png)
it is not really has opacity。It is mix width a white background。

I try fill color width fillOpacity，but I failed again。
`<Svg style={{width:100,height:100}}>`
`         <Rect `
`                 x="0"`
`                 y="0"`
 `                width="100"`
  `               height="100"`
   `              fill="#000"`
  `               fillOpacity=".5"`
 `           />`
`</Svg>`

I need to use it to cover on an image and set LinearGradient fill width opacity widthout a white background.
 
What should I do？

**Comment by msand** [comment]
Can't understand/interpret this. Please elaborate if you want help.
