### ISSUE TITLE
Are there any way get witdh of <Text>,  or get any text width in React? 

### ISSUE THREAD

**Issue by mcihan** [react-native-community/react-native-svg#734]
I want to draw background by Text so i must have width of text.
Are there any way get witdh of <Text> in react-native-svg ?

Other hand,
I tried calculate text width using below javascript code convert to React-Native, but React.createElement() didn't work.

```
function getTextWidth(text, font) {
     var canvas = getTextWidth.canvas || (getTextWidth.canvas = document.createElement("canvas"));
     var context = canvas.getContext("2d");
     context.font = font;
     var metrics = context.measureText(text);
     return metrics.width;
}
```

**Comment by cao1034** [comment]
Can you solve this problem? 
I am also troubled by this, 
the online methods are based on the html5 solution getBBox

**Comment by mcihan** [comment]
No I can't.  

Someone added support for onLayout in last comment of this issue #89 for getBBox,
but it didn't work for me

**Comment by maxkomarychev** [comment]
`onLayout` returns screen (against top-left corner of `svg` component) coordinates of an element.
also it only works as a callback because screen coordinates of an element are unknown until it's rendered.
afaik there's currently no way to get coordinates of an element within `svg` space.

**Comment by mcihan** [comment]
@maxkomarychev 
Hi, how i can calculate some text width in react-native , similar below js code, 
I can't create canvas element with React.createElement()
This code is enough for me.

```
function getTextWidth(text, font) {
    var canvas = getTextWidth.canvas || (getTextWidth.canvas = document.createElement("canvas"));
    var context = canvas.getContext("2d");
    context.font = font;
    var metrics = context.measureText(text);
    return metrics.width;
}

 getTextWidth("hello there!", "bold 12pt arial"); 
```

**Comment by msand** [comment]
Have you tried using onLayout and something like this? http://bl.ocks.org/nitaku/8745933/8660a5f46547c04afc2362788910773c56c16642

**Comment by kdenz** [comment]
For me what worked is to calculate the width of the background rectangle dynamically based on text string length, so example:
`<Rect
                x={20}
                y={20}
                height="20"
                width={textString.length * 10}
              />`

**Comment by yanush** [comment]
> For me what worked is to calculate the width of the background rectangle dynamically based on text string length, so example:
> `<Rect x={20} y={20} height="20" width={textString.length * 10} />`

but if the font you are using is not mono-space then every char has a different width

**Comment by msand** [comment]
You can use UIManager.measure or onLayout, closing.

**Comment by aprilmintacpineda** [comment]
give props `onLayout={callback}`, then on the callback, do `console.log(event.nativeEvent.layout);` it will have `height: number, width: number, x: number, y:number`

**Comment by suwu150** [comment]
> give props `onLayout={callback}`, then on the callback, do `console.log(event.nativeEvent.layout);` it will have `height: number, width: number, x: number, y:number`

The obtained value is not accurate
```
        <Text
            textAnchor={textAnchor}
            fill={fill || colors.gray3}
            fontFamily="DINPro-Regular, DINPro"
            fontSize={p(20)}
            onLayout={(event) => {
              console.log('onLayout Text', event.nativeEvent.layout)
            }}
          >
            <TSpan
            onLayout={(event) => {
              console.log('onLayout', event.nativeEvent.layout)
            }}
              x={20}
              y={20}
            >
              {342432}
            </TSpan>
          </Text>
```

<img width="562" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/20339760/9513e334-9233-40a5-bfae-e5e54f72fbea">
