### ISSUE TITLE
[bug] Clipped shape filled with gradient shows incorrectly

### ISSUE THREAD

**Issue by ujeenator** [react-native-community/react-native-svg#738]
What I expect:
<img width="210" alt="screen shot 2018-07-19 at 11 14 10 pm" src="https://user-images.githubusercontent.com/1893760/42967821-1df64c48-8baa-11e8-8e0b-b99b8fc4853b.png">

What I get:
![img_0551](https://user-images.githubusercontent.com/1893760/42967860-3a53de50-8baa-11e8-9e28-453331dd6d76.PNG)

Code:
```
<Svg width={200} height={200}>
  <Defs>
    <RadialGradient id='gradient' r='50%' cx='50%' cy='50%' fx='50%' fy='50%'>
      <Stop offset='0' stopColor='red' stopOpacity='1' />
      <Stop offset='1' stopColor='red' stopOpacity='0' />
    </RadialGradient>
    <ClipPath id='cut-off-bottom'>
      <Rect x='0' y='0' width='200' height='100' />
    </ClipPath>
  </Defs>
  <Circle
    cx='100'
    cy='100'
    r='100'
    clipPath='url(#cut-off-bottom)'
    fill='url(#gradient)'
  />
</Svg>
```

**Comment by msand** [comment]
I have a fix available, could you test it? https://github.com/msand/react-native-svg/commit/11a57526fc9f226733dc374e16e22012ed0791aa
