### ISSUE TITLE
`textAnchor` `left` throws fatal error on Android through Expo

### ISSUE THREAD

**Issue by dextermb** [react-native-community/react-native-svg#742]
### What is the problem?
When using `textAnchor` and setting it to `left` it throws a fatal error when testing through expo.

### When does it happen?
I assume it is whenever a axis (I'm using `YAxis`) is mounted with `textAnchor` set to `left`.

### What platform?

* [ ] iOS 
* [x] Android

I do not seem to get the issue when testing on an iOS simulator.

React Native version: `0.54.0`

### Code to reproduce

```javascript

// Usage with svg charts
<YAxis
	data={[ 'a', 'b' ]}
	contentInset={{ top: 20, bottom: 20, marginRight: 20 }}
	svg={{
		fill:       'grey',
		fontSize:   10,
		textAnchor: 'left',
		x:          0
	}}
	numberOfTicks={5}
	formatLabel={label => `${label}`}
/>

// Source for YAxis's text

<SVGText
	originY={ y(value) }
	textAnchor={ 'middle' }
	x={ '50%' }
	alignmentBaseline={ 'middle' }
	{ ...svg }
	key={ index }
	y={ y(value) }
>
	{formatLabel(value, index)}
</SVGText>
```

### Stacktrace (if crash)
```
Uncaught Error: No enum constant
abi26_0_.host.exp.exponent.modules.api.components.svg.TextAnchor.left
```

This might be an expo issue, but I'd like to confirm that here before referencing this post elsewhere

---

Reference [react-native-svg-charts/203](https://github.com/JesperLekland/react-native-svg-charts/issues/203)

**Comment by dextermb** [comment]
Seems like within the source it is _start_ not _left_ but I haven't found why it does not crash on iOS.

```
package com.horcrux.svg;

enum TextAnchor
{
    start,
    middle,
    end
}
```

[Source for TextAnchor.java](https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/TextAnchor.java#L5)

**Comment by fogg4444** [comment]
Changing 'left' to 'start' worked for me. Wish that was in the docs! :)
