### ISSUE TITLE
When to upgrade to support for react-native `0.56.0`

### ISSUE THREAD

**Issue by colorfulberry** [react-native-community/react-native-svg#744]

**Comment by thitemple** [comment]
I just came by to see if react-native 0.56 was supported, I guess it's not...  :(

**Comment by maxkomarychev** [comment]
hey, are you using most recent version? one was published less than 24 hours ago: https://github.com/react-native-community/react-native-svg/pull/729

**Comment by thitemple** [comment]
I was not, but I will try again

**Comment by colorfulberry** [comment]
@maxkomarychev 
@thitemple 
  Thanks

**Comment by thitemple** [comment]
It did not work, now I'm seeing this error:

* Where:
Build file 'C:\Users\thiago\Documents\projects\publicUserApp\node_modules\react-native-svg\android\build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':react-native-svg'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ammichael** [comment]
I'm also having the exactly same issue @thitemple is having. The problem affects only Android build.

**Comment by msand** [comment]
It requires upgrading gradle, there's an open pr to revert that change, I'll probably merge and release a patch version today

**Comment by msand** [comment]
Can you try again with 6.5.1?

**Comment by thitemple** [comment]
It works!
