### ISSUE TITLE
Invariant Violation: requireNtiveComponent: "RNSVGRect" was not found in the UIManager

### ISSUE THREAD

**Issue by berpcor** [react-native-community/react-native-svg#749]
Hello.

`react-native link react-native-svg` - **done.**
`react-native link` - **done.**
`yarn cache clean` - **done.**
reinstalling of react-native-svg - **done.**
`react-native run-ios` after every action - **done.**

**Manual linking:** 
> To install react-native-svg on iOS visit the link referenced above or do the following:
> 
> Open your project in XCode and drag the RNSVG.xcodeproj file (located in .../node_modules/react-native-svg/ios) into the Libraries directory shown in XCode.
> Expand the RNSVG.xcodeproj file you just added to XCode until you see: libRNSVG.a (located in RNSVG.xcodeproj > Products )
> Drag libRNSVG.a into the Link Binary With Libraries section (located in Build Phases which may be found at the top of the XCode window)

**DONE.**

![scr](https://user-images.githubusercontent.com/1884568/43545300-b83802f6-95ff-11e8-9f28-441c6c0fe908.png)

**Versions:** 

_"react-native-svg": "^6.5.1",
"react-native": "0.56.0",_

Code block that causes error:

 ```
<Svg height={this.state.maskedElHeight} width={this.state.maskedElWidth} style={{ position: "absolute", top: 0, left: 0, }}>

    <Defs>

        <ClipPath id="clip">

            <Rect x="0" y="0" width="100%" height="100%" />
            <Polygon x="0" y="0" points={`
                ${Math.round(this.state.maskedElWidth / 2)},0 
                0,${Math.round(this.state.maskedElHeight * 0.25)}
                0,${Math.round(this.state.maskedElHeight * 0.75)} 
                ${Math.round(this.state.maskedElWidth / 2)},${Math.round(this.state.maskedElHeight)} 
                ${Math.round(this.state.maskedElWidth)},${Math.round(this.state.maskedElHeight * 0.75)} 
                ${Math.round(this.state.maskedElWidth)},${Math.round(this.state.maskedElHeight * 0.25)} 
                `} 
            />
        </ClipPath>

    </Defs>

    <Rect
        x="0"
        y="0"
        width="100%"
        height="50%"
        fill="#FF187C"
        opacity="1"
        clipPath="url(#clip)"
    />

    <Rect
        x="0"
        y="50%"
        width="100%"
        height="50%"
        fill="white"
        opacity="1"
        clipPath="url(#clip)"
    />
    
</Svg>
```
Android is ok, but iOS shows me the error.

![scr2](https://user-images.githubusercontent.com/1884568/43545369-eb35aff0-95ff-11e8-8d39-320fcf333be5.png)

Update:
When running project via xcode, I get:

![err](https://user-images.githubusercontent.com/1884568/43546420-cb745402-9602-11e8-8c41-0b2221ba85a0.png)

What's happening?

**Comment by AndrewHenderson** [comment]
@berpcor I just ran into the same issue with the `LinearGradient`.

<img width="375" alt="screen shot 2018-08-01 at 1 48 53 pm" src="https://user-images.githubusercontent.com/1031565/43547957-a1e6b038-9591-11e8-8c6c-a993c3eb42a6.png">

**Comment by hemith** [comment]
check manual linking process.
$ react-native link react-native-svg ---> sometimes done incompletely.

**Comment by barjas** [comment]
react-native link is missing the last step. it is not adding "`new SvgPackage()`" 
 
Open up `android/app/src/main/java/[...]/MainApplication.java
**Add new SvgPackage() to the list returned by the getPackages() method. Add a comma to the previous item if there's already something there.**

i think this is a bug and need to be fixed.

**Comment by zhangwen9229** [comment]
> react-native link is missing the last step. it is not adding "`new SvgPackage()`"
> 
> Open up `android/app/src/main/java/[...]/MainApplication.java
> **Add new SvgPackage() to the list returned by the getPackages() method. Add a comma to the previous item if there's already something there.**
> 
> i think this is a bug and need to be fixed.

![image](https://user-images.githubusercontent.com/5137377/49068366-7eecd580-f261-11e8-8eef-ffb494b230d0.png)
![image](https://user-images.githubusercontent.com/5137377/49068508-e145d600-f261-11e8-9dfd-8427f657b52e.png)

I had added new SvgPackage() .Also has error.  Any other solution,please.

**Comment by zhangwen9229** [comment]
Android， I had added new SvgPackage(),same error. Some solution？

IOS is ok.

**Comment by msand** [comment]
These are issues with react-native link, please post them in the RN repo.

**Comment by lanlanlittle** [comment]
android clean

**Comment by ThakurKarthik** [comment]
> Android， I had added new SvgPackage(),same error. Any other solutions？
> 
> IOS is ok.

is this solved?

**Comment by msand** [comment]
@ThakurKarthik At least it's working fine both locally, and in TravisCI with the latest versions: https://github.com/msand/react-native-svg-e2e/blob/master/.travis.yml
https://travis-ci.org/msand/react-native-svg-e2e/builds/504814136
https://app.bitrise.io/build/1cf98115859f41bf

**Comment by tomfinney** [comment]
Had this issue for iOS, managed to "fix" it by removing by unlinking `react-native-svg` and removing it from my dependencies and then subsequently adding it again as a dependency and re-linking it. 😬

**Comment by fisherwise** [comment]
it supports autolink now just ```cd ios``` and do ```pod install```

**Comment by CyrusZei** [comment]
and remember to kill your metro server and rebuild the project

**Comment by sushrut-desora** [comment]
ejected from expo sdk 36 to bare workflow. sdk 36 is based on react native 0.61. Still had to manually do  ```react-native link react-native-svg``` to fix this issue. I am using react-native-svg 9.13.3

**Comment by cyb3rsalih** [comment]
Only restart metro bundler is not enough. You should rebuild app.

**Comment by wulcat** [comment]
> it supports autolink now just `cd ios` and do `pod install`

On ios 11.4.1 installing pods works smoothly. Make sure you restart metro and build again.

**Comment by sabaoonbedar** [comment]
cd ios 
pod install 

does the trick for me. remember from your root folder you have to go through above commands.

**Comment by pxl-live** [comment]
> Only restart metro bundler is not enough. You should rebuild app.

Delete App and run react-native run-ios to reinstall worked fine for me. Thanks

**Comment by ardentcricket** [comment]
> it supports autolink now just cd ios and do pod install

🤦 Forgot to run `pod install` after installing the packages. Thanks @aiden0w0

**Comment by Princejain21** [comment]
> Android， I had added new SvgPackage(),same error. Any other solutions？
> 
> IOS is ok.

Hey have you resolved it for android?
