### ISSUE TITLE
Dynamically generated SVG

### ISSUE THREAD

**Issue by kennetpostigo** [react-native-community/react-native-svg#75]
Hello,

I'm working on a library [`component-kit`](https://github.com/kennetpostigo/component-kit) which is made to help made data driven dashboards really fast and easy. I want to be able to use it in react-native, however it generates SVG dynamically based on input that changes overtime. `component-kit` is powered by D3 under the hood. I would like to know if somehow this would work in tandem with `component-kit`. Heres some code to give you an idea of what D3 is doing: https://github.com/kennetpostigo/component-kit/blob/master/src/visualization/AreaChart.js

**Comment by WaiSiuKei** [comment]
Hi @kennetpostigo, I think you should discard d3 and manipulate the attrs of elements directly.
I have create a demo to load data then generate the chart:
[https://github.com/WaiSiuKei/react-native-nila](https://github.com/WaiSiuKei/react-native-nila)
