### ISSUE TITLE
Compatibility with UWP for windows 10 app

### ISSUE THREAD

**Issue by paulbx81** [react-native-community/react-native-svg#751]
Hello, can you do something for react-native-windows users ?

Currently when we try to use a library who need react-native-svg (like react-native-svg-chart for exemple) we have some errors like : " NATIVE COMPONENT FOR RNSVGLine does not exist ".

We really need react-native-svg for windows  👍 

@magicismight @msand

**Comment by msand** [comment]
@paulbx81  Feel free to work on this.

**Comment by msand** [comment]
Well alright, but it seems unlikely to get worked on before a complete rewrite to a cross-platform rendering backend.
