### ISSUE TITLE
Any reason why this lib can't read files?

### ISSUE THREAD

**Issue by Sam-DevZ** [react-native-community/react-native-svg#753]
Apparently, there is still no good solution for reading SVG files? 

I created my own script to deal with this for now (https://github.com/SM-Wistful/react-native-svg) but it's messy and written in Python. Why doesn't this library just read the file and use a bit of regex to convert it into a format that react-native-svg can understand? 

I would have tried to make my project into a react-native library but I'm still learning the framework. Is it even being considered to add this?

**Comment by rodrigoelp** [comment]
Hi @SM-Wistful, I guess the guys maintaining this library are still trying to wrap up the foundation of svg in order to support other features (such as reading svg directly)

If you read the `README.md` file, it states quite clearly (at the bottom):

> **TODO:**
> 1. Add Native methods for elements.
> 2. Pattern element.
> 3. Mask element.
> 4. Marker element.
> 5. Load Image from URL.

Point 5 is the one you are talking about.

That would explain why they haven't generated a parser to translate svg files into react-native-svg (they need the native support first in order to make things smoother)

**Comment by msand** [comment]
I haven't properly evaluated https://github.com/target/react-native-svg-parser and https://github.com/vault-development/react-native-svg-uri
One of these could possibly be integrated.
Ideally it would be a babel plugin, allowing to import svg files, converting them to use react and react-native-svg, and allowing it be chained with e.g. https://babeljs.io/docs/en/babel-plugin-transform-react-inline-elements.html and https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements/
Such that the parsing and conversion can be done only once at buildtime, or alternatively, some runtime cache could be used for it. But, at least, the static nature of svg files should be optimised for.
At the moment, a script to convert .svg to .js/.jsx and importing that is probably the best performing way achieve this. Like this approach: https://github.com/SM-Wistful/react-native-svg
So, if someone could write a babel-plugin, then I would fully endorse that approach at least. These existing ones would probably make sense to document as workarounds for now as well.

**Comment by maxkomarychev** [comment]
How would babel plugin help reading svg dynamically from arbitrary http url?

**Comment by msand** [comment]
But then again, keeping this functionality separate from the main rendering logic probably still makes sense. Some people won't need the svg dom parsing, hence its (imho) better to keep the core rendering logic module as small as possible.

**Comment by msand** [comment]
Well, for loading svg from url you'll need the parser available at runtime, so then your requirements demand to bundle it, but otherwise it would be unused code included into every project which depends on the renderer.

**Comment by stowball** [comment]
I wrote my own remote SVG parser because I wasn't happy with the other options out there, and while it works, it is quite slow on real iOS devices, but the simulators are perfect.

For Android, we integrated a native SVG module and wrote another remote bridge, so that actually renders all SVG natively now

**Comment by msand** [comment]
Found another option: https://github.com/smooth-code/svgr
Has node api: https://github.com/smooth-code/svgr/tree/master/packages/core
also cli, webpack loader, rollup plugin, and a web gui: https://svgr.now.sh/
but no babel plugin what I can find

**Comment by msand** [comment]
https://github.com/airbnb/babel-plugin-inline-react-svg/blob/master/src/index.js has most of the necessary logic, porting the logic (from svgr) for the differences between web svg and react-native-svg to the babel-plugin-inline-react-svg  or making a babel version of svgr would give a complete solution.
@neoziro @ljharb Has either one of you planned anything like this?

**Comment by neoziro** [comment]
I would like to do it but babel plugin must be synchronous. As SVGR has built-in support for SVGO, it is actually the blocker to create a babel plugin: https://github.com/svg/svgo/issues/1015

I could make it by disabling SVGO.

**Comment by msand** [comment]
@neoziro Actually, svgo has the _optimizeOnce method, it takes a callback but in reality is synchronous and gets called before optimizeonce returns.

**Comment by neoziro** [comment]
@msand I can't rely on internal method that takes a callback and that is technically synchronous. SVGO team doesn't want to do any effort. If I had time I would like to create a new SVGO based on [unified](https://unifiedjs.github.io/). If someone is interested!

**Comment by msand** [comment]
@neoziro How is progress / your current thinking on this?

**Comment by neoziro** [comment]
@msand In finally decided to use the internal method. SVGR now exposes a synchronous method, not yet a Babel plugin, but it is technically possible to implement one.

**Comment by msand** [comment]
@neoziro I've added docs for using svg files now: https://github.com/react-native-community/react-native-svg#use-with-svg-files

.babelrc
```json
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["babel-plugin-inline-import", {
      "extensions": [
        ".svg"
      ]
    }]
  ]
}
```

App.js
```jsx
import * as React from 'react';
import SvgUri from 'react-native-svg-uri';
import testSvg from './test.svg';
export default () => (
  <SvgUri
    width="200"
    height="200"
    svgXmlData={testSvg}
  />
);
```

Can svgr be given the .svg content, and output a function, rather than source code?
Either way, a babel plugin to do it only in development / at compile-time when the source changes, rather than every render or each startup at runtime, or at the very least caching it by filename/uri, would be needed for proper performance.

**Comment by msand** [comment]
@neoziro Seems like @kristerkari has done the work for us ❤️ https://github.com/kristerkari/react-native-svg-transformer 
https://github.com/kristerkari/react-native-svg-example/blob/master/rn-cli.config.js

**Comment by msand** [comment]
https://medium.com/@prathik_63905/using-svg-in-latest-react-native-version-0-57-e04aa8ea7dd8

**Comment by msand** [comment]
Updated docs: https://github.com/react-native-community/react-native-svg/blob/master/README.md#use-with-svg-files

**Comment by msand** [comment]
@brentvatne @ide Would it be possible to get react-native-svg-transform into Snack? Such that one could import an .svg file and use it as a component? 
https://github.com/kristerkari/react-native-svg-transformer#step-3-configure-the-react-native-packager

```jsx
import Logo from "./logo.svg"
const MyApp = () => <Logo width={120} height={40} />
export default MyApp
```

**Comment by msand** [comment]
I guess this issue could probably be closed at this point, as both remote and local svg files can be handled in multiple ways now.

**Comment by msand** [comment]
SvgXml and SvgUri are exposed by react-native-svg nowadays, in case some stumbles upon this issue.

**Comment by douglassoldan** [comment]
`import {WithLocalSvg} from 'react-native-svg';

const FileName = require('.../.../file.svg');

<WithLocalSvg
   asset={FileName}
   width={100}
   height={100}
/>
`
