### ISSUE TITLE
Login form error react native 

### ISSUE THREAD

**Issue by alooosh** [react-native-community/react-native-svg#758]
Hello everyone I am new to react native i tried to make login form but i can get password value but not user name 
this is my code app.js : 

import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, TextInput, View } from 'react-native';
import { Container, Header, Content, Left, Body, Right, Button, Icon, Title, Form, Textarea, Item, Input, Toast } from 'native-base';

import Header1 from './components/Header_sec.js'

export default class App extends React.Component {

  constructor(props) {
    super(props);
    this.state = { username: '', Password: '' };
  }
 // updateState = (myState) => this.setState({ myState })

 // updateusername = (username1) => this.setState({ username : username1 });
 // updatePassword = (Password1) => this.setState({ Password : Password1 });
  render() {
    return (
      <Container>
        <Header1 />
        <Content padder>
          <Form>
            <Text style={styles.login}>login</Text>
            
            <Item>
              <Input onChangeText={(username1) => this.setState({ username : username1 })} placeholder="Username" value={this.state.username} />
              <Text>{this.state.username}</Text>
            </Item>
            <Item>
              <Input onChangeText={(Password1) => this.setState({ Password : Password1 })} placeholder="Password" value={this.state.Password} />
              <Text>{this.state.Password}</Text>
            </Item>
            <Button block onPress= {this.myloing.bind(this.state.username,this.state.Password)} >
              <Text>تسجيل الدخول</Text>
            </Button>
          </Form>
        </Content>

      </Container>
    );
  }
  
 myloing(username,Password)
 {
   try
   {
    if (username == "" || Password == "")
    {
     alert("not allow empty");
      return;
    }else
    {
      
     alert(username);
      alert(Password);
    }
   }catch(exc)
   {
    alert(exc.Text);
   }
   
  
 };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
 
    justifyContent: 'center',
  },
  login:
  {

    fontSize: 80,
    fontWeight: 'bold',
   
    color: 'red',
    
  }
});

**Comment by msand** [comment]
Unrelated to this repo, please ask on stackoverflow or something.
