### ISSUE TITLE
Using Macaw for iOS

### ISSUE THREAD

**Issue by keshavkaul** [react-native-community/react-native-svg#759]
There's a popular SVG library for iOS called Macaw - https://github.com/exyte/Macaw
Have we thought about using this library? And more generally have we thought of using popular native SVG libraries for iOS and Android and provide an interface in React Native?

**Comment by msand** [comment]
@stowball has mentioned using some native module for android https://github.com/react-native-community/react-native-svg/issues/753#issuecomment-413825722 Is that available somewhere? Perhaps that could be combined with Macaw or something similar.

I was looking into doing the same about a year ago but decided to improve the spec conformance of this library instead. But, it might still be worth it to have more than one approach available as an option. 

You might want to look at these:

https://github.com/frostney/react-native-create-library
https://github.com/peggyrayzis/react-native-create-bridge

https://blog.botreetechnologies.com/how-to-build-a-react-native-android-bridge-4166e114a990
https://blog.pixielabs.io/react-native-bridge-modules-for-ios-be0f4cec0435

https://facebook.github.io/react-native/docs/native-modules-android
https://facebook.github.io/react-native/docs/communication-ios

https://hackernoon.com/first-experiences-with-react-native-bridging-an-ios-native-module-for-app-authentication-7a20b7180fc9
https://shellmonger.com/2018/01/19/creating-a-react-native-bridge-library/
