### ISSUE TITLE
Support for "currentColor" and "inherit" color values.

### ISSUE THREAD

**Issue by mike-marcacci** [react-native-community/react-native-svg#764]
I have a use case where I want to define a symbol with certain inherited values, and reference it within different contexts:

```svg
<svg width="256" height="256">
  <symbol id="foo">
    <circle cx="128" cy="128" r="64" fill="inherit" />
  </symbol>
  <g fill="orange">
    <use href="#foo" />
  </g>
  <g fill="pink">
    <use href="#foo" />
  </g>
</svg>
```

However, it appears that the `inherit` and `currentColor` values are not currently supported.

It seems like this could be supported on the js side by using React context, and resolving to "final" values before the bridge. However, I did see that there is already a native context for inheritance of text properties.

What would your preference be on how to implement this: introduce react context, or build off of the existing native context?

This is related to #589.

**Comment by mike-marcacci** [comment]
As I'm looking more into the implementation here, I think there are a few sub-issues or things that would need to be changed:

1. In general inheritance is supported more broadly than I initially saw on the native side, so that probably answers my question. Instead, the explicit "inherit" value should be allowed but ignored where it's already the default. I believe this is the current behavior, except that is isn't listed in `propTypes` so it warns.
2. Add support for `color` in the context, and the ability to access it with the `currentColor` value.
3. Ensure that an instance of `Use` applies its context to inherited properties of its `Symbol`

**Comment by msand** [comment]
Using plain js and react context you can implement this without any changes to react-native-svg. And I would prefer not to introduce context unless the situation really calls for it. It would be nice to have support for currentColor as per spec though. View doesn't support color, and I think Android didn't support rendering images/bitmaps/svg inside text elements (at least using react-native). At least color emoji is possible to render inside text in native Android, so it should be possible to get it working. But it might require a pull request to react-native as well, and I remember reading some discussions about dropping support for Images inside Text on iOS as well. But, getting native support for this would be nice indeed.

**Comment by msand** [comment]
I think we could support the color attribute on the svg root element in circumstances like this:
```jsx
import { Svg, Path } from 'swgs';

export default props => (
  <Svg
    title="pencil"
    x="0px"
    y="0px"
    width="20px"
    height="20px"
    color="white"
    style={{ margin: 5 }}
    viewBox="0 0 512 512"
    {...props}
  >
    <Path
      fill="currentColor"
      d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
    />
  </Svg>
);
```
This would allow overriding the color if needed

**Comment by msand** [comment]
Closing this for now, as inheritance seems to be working and color is supported
