### ISSUE TITLE
On Android bitmap images with <Image/> do not load if requested from remote source and cached on disk.

### ISSUE THREAD

**Issue by adam-s** [react-native-community/react-native-svg#765]
On Android using the <Image/> component, if the image has been requested from a remote source it will work, if the image is loaded a second time and cached in memory it will work, however, it will not load if the image has been requested and the memory is cleared by closing the app. The next attempt to load the image is from the disk cache and it will not show. However, it is cached in memory when loaded from disk cache and will show subsequent times from memory until either the image is removed from memory because by the os or the app memory is cleared by closing out.

I used the method `Image.queryCache()` to see where the image has been stored in cache.

**Comment by adam-s** [comment]
I think this code
````
    @Override
    public void draw(final Canvas canvas, final Paint paint, final float opacity) {
        if (!mLoading.get()) {
            final ImageSource imageSource = new ImageSource(getThemedContext(), uriString);

            final ImageRequest request = ImageRequestBuilder.newBuilderWithSource(imageSource.getUri()).build();
            if (Fresco.getImagePipeline().isInBitmapMemoryCache(request)) {
                tryRender(request, canvas, paint, opacity * mOpacity);
            } else {
                loadBitmap(request, canvas, paint, opacity * mOpacity);
            }
        }
    }
````
needs to include checking for the image in the disk cache before loading the bitmap in memory cache.

see http://frescolib.org/docs/caching.html

**Comment by adam-s** [comment]
I found a hacky work around. `Image.getSize()` will move the image from disk to memory cache before the component is rendered.

````
    // Might as well start fetching the image
    const noop = () => {};
    Image.prefetch({ uri: venueImage });
    Image.getSize(venueImage, noop, noop);
````

**Comment by msand** [comment]
I guess this is resolved then? If you find a nice place / set of conditions to put that logic then it would be great if you could open a pull request. Closing this for now.

**Comment by msand** [comment]
@adam-s this is probably a bug in fresco actually, the default settings for a ImageRequest allow even fetching, and only if we have it in bitmap cache do we have a fast path. The 
```java
ImageRequestBuilder.newBuilderWithSource(imageSource.getUri()).build();
```
causes
```java
  private RequestLevel mLowestPermittedRequestLevel = RequestLevel.FULL_FETCH;
```
to be used.

https://frescolib.org/docs/image-requests.html
**Lowest Permitted Request Level**
The image pipeline follows a definite sequence in where it looks for the image.

1. Check the bitmap cache. This is nearly instant. If found, return.
2. Check the encoded memory cache. If found, decode the image and return.
3. Check the “disk” (local storage) cache. If found, load from disk, decode, and return.
4. Go to the original file on network or local file. Download, resize and/or rotate if requested, decode, and return. For network images in particular, this will be the slowest by a long shot.

The setLowestPermittedRequestLevel field lets you control how far down this list the pipeline will go. Possible values are:

- BITMAP_MEMORY_CACHE
- ENCODED_MEMORY_CACHE
- DISK_CACHE
- FULL_FETCH

This is useful in situations where you need an instant, or at least relatively fast, image or none at all.
