### ISSUE TITLE
`Region.Op.REPLACE` is deprecated in API level 28

### ISSUE THREAD

**Issue by WoodyWoodsta** [react-native-community/react-native-svg#766]
When trying to use a clip path on an element, the use of `Region.Op.REPLACE` is causing an exception `Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed`. This is due to REPLACE being deprecated as per https://developer.android.com/reference/android/graphics/Canvas.html#clipPath(android.graphics.Path,%20android.graphics.Region.Op)

I would love to PR but I'm not clear on how to resolve this to be honest.

**Comment by msand** [comment]
If you need a quick fix then you can just remove the second argument: https://github.com/msand/react-native-svg/commit/a1097b85942c559ebcef6b93fa2ce601434d9c50#diff-633cc935907e7685222b28cf9a0d7696L268
That's more spec conformant anyway.

**Comment by WoodyWoodsta** [comment]
@msand Great stuff - this appears to work quite well. Will leave open until this is included upstream.
