### ISSUE TITLE
Image is not shown on iOS

### ISSUE THREAD

**Issue by shukiAnavi** [react-native-community/react-native-svg#768]
Hi!

I've got a problem displaying an image on iOS.

Everything works fine on Android devices but not on iOS.

Here is an example of the problem:

https://snack.expo.io/rJje0fvwQ

Importent details:
* react-native: 0.55.4
* react-native-svg: 6.4.1
* In my actual code I'm trying to display an image from my assets folder but it either not working in both cases (using require(...) or uri:'http:\\image-path')

Someone managed to solve this in some way?

**Comment by N1ghtly** [comment]
We are having this problem as well. Works fine on Android, while iOS shows nothing. We are using PNG images.

**Comment by jon64digital** [comment]
Not sure whether I;m having exactly the same problem but I am trying to embed an image inside an svg. All is working fine on Android but not on iOS.

`
<Svg width="40" height="40" viewBox="0 0 40 40">
    <Image 
    href={{ uri: 'absolute-path-to-image-folder-on-cloudinary/' + this.props.message.player.playerId + '.jpg' }}
        height="40" 
        width="40"
    />
</Svg>
`

**Comment by msand** [comment]
Seems to work fine on ios for me. Can you please provide a full reproduction? Or verify that it works with the latest versions of react-native and react-native-svg? Closing for now.
