### ISSUE TITLE
TextPath not working on Android

### ISSUE THREAD

**Issue by davidgithub1980** [react-native-community/react-native-svg#769]
Hi, my dev:

"expo": "^29.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"

```
import { Svg } from 'expo';
const { Text, TextPath, Line } = Svg;

<Svg width={500} height={500}>
  <Line
    id="line"
    x1="100"
    y1="100"
    x2="300"
    y2="300"
    stroke="red"
    strokeWidth="2"
  />

  <Text fill="blue" fontSize="20">
    <TextPath href="#line">
      Some random text
    </TextPath>
  </Text>
</Svg>
```

This appears to be a bug as the code above **works perfectly on iPhone** but the **text within the _TextPath_ element is not visible at all on an Android phone**. Only the _Line_ element is displayed on an Android phone. The text along the path is missing completely.

**Comment by davidgithub1980** [comment]
Since I am quite new in Github waters, does a long inactivity inside a reported issue mean that the project,  generally, is not that familiar and widely used to make somebody resolve it?

**Comment by msand** [comment]
Well, as no one receives monetary compensation for working on this repo, I'm not sure if it's possible to make any conclusions from inactivity on one specific issue. Except perhaps that others probably aren't experiencing the same issue. I suspect the library has a significant amount of use, at least from looking at how many repos on github depend on it, and the number of monthly downloads.

In general, the way to be a good open source citizen is to attempt to solve ones own issues and share the solution with others, or at least describe what troubleshooting has already been done.

In this case, it seems Android only supports referring to a Path element in the TextPath href attribute. If you replace the Line with a Path with d="M100,100 L300,300" it should work also in Expo

  <Svg width={500} height={500}>
    <Defs>
      <Path id="line" d="M100,100 L300,300" stroke="red" strokeWidth="2" />
    </Defs>
    <Use href="#line" fill="blue" />
    <Text fill="blue" fontSize="20" x="0">
      <TextPath href="#line">Some random text</TextPath>
    </Text>
  </Svg>

Or, you can use plain react-native / eject from expo, and use the latest commit here: https://github.com/react-native-community/react-native-svg/commit/35597ed7720ef01abe1c111e22308468e605cf01
