### ISSUE TITLE
Support for setNativeProps for all elements

### ISSUE THREAD

**Issue by agenthunt** [react-native-community/react-native-svg#77]
Would it be possible to support setNativeProps for all Svg Elements. At present, it seems that it is present only on the Svg Element.

**Comment by tanabs18** [comment]
AgentHunt, how did you get nativeProps working on the Svg element?! This would be a huge help to my project.

**Comment by tanabs18** [comment]
I would also love to see this implemented!

**Comment by msand** [comment]
This should work an all elements now. Closing.
