### ISSUE TITLE
FontWeight bug?

### ISSUE THREAD

**Issue by vjsingh** [react-native-community/react-native-svg#770]
How come the font weight is different for a Text View vs an SVG Text?

Text view on top, SVG text on bottom, both font weight 100:
<img width="328" alt="screenshot 2018-09-05 09 31 52" src="https://user-images.githubusercontent.com/318312/45096520-b75f9600-b0ee-11e8-8949-423a5cd2eeb5.png">

Snack: https://snack.expo.io/@vjsingh/svgtext-font-weight

This was motivated by wanting a thinner font weight in my project.

Thank you!

**Comment by msand** [comment]
@vjsingh Try removing the stroke and setting the fill instead:

```jsx
            <Svg.Text
              fill="blue"
              fontSize={56}
              fontWeight="100"
              textAnchor="middle"
              x="50%"
              y="50">
              lazy dog
            </Svg.Text>
```

**Comment by vjsingh** [comment]
@msand brilliant! Thank you, that did it
