### ISSUE TITLE
Require circle between extractText.js and TSpan.js

### ISSUE THREAD

**Issue by Kennytian** [react-native-community/react-native-svg#773]
require.js:168 Require cycle: node_modules/react-native-svg/lib/extract/extractText.js -> node_modules/react-native-svg/elements/TSpan.js -> node_modules/react-native-svg/lib/extract/extractText.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

![circle_require](https://wx2.sinaimg.cn/mw1024/77c29b23ly1fv0ofmqur0j20ol022q3h.jpg)

**Comment by serzh-f** [comment]
Hi! I used 
React 16.5.0 
React-native 0.57.1
React-native-svg ^7.0.3 and warning is showing

Can you check it ?
Or how can i fix it ? 

http://joxi.ru/eAO6RPqI9wV932.jpg

Thx

**Comment by Falconiere** [comment]
Same problem, how can i fix it ?

**Comment by msand** [comment]
Is it causing any issues?
If you really want to get rid of it, then you can refactor the code to use the inversion of control pattern as I've described for a similar issue two years ago: https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem#content-39
https://stackoverflow.com/a/44226565
And open a pr with the changes.

**Comment by msand** [comment]
I've merged https://github.com/react-native-community/react-native-svg/pull/813 to master now, you can either use the latest commit from the master branch, or wait until the next release and use that.

**Comment by msand** [comment]
Published fix in v8
