### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by fjsun123** [react-native-community/react-native-svg#775]
:app:compileDebugJavaWithJavac                 
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:6: 错误: 程序包com.horcrux.svg不存在
import com.horcrux.svg.SvgPackage;             
                      ^
C:\Users\Administrator\Desktop\react native 8.1\git_BDX\BDX\android\app\src\main\java\com\bdx\MainApplication.java:28: 错误: 找不到符号
            new SvgPackage(),
                ^
  符号: 类 SvgPackage
2 个错误
Incremental compilation of 1 classes completed in 0.521 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by msand** [comment]
Try:
react-native unlink react-native-svg 
and then:
react-native link react-native-svg

**Comment by zhushichuan** [comment]
你是怎么解决的，我还是不行

**Comment by lfabl** [comment]
Please run this and then test again:
```
yarn remove react-native-svg
```
or
```
npm uninstall react-native-svg
```
