### ISSUE TITLE
end to end testing of react-native-svg components using testID

### ISSUE THREAD

**Issue by phosphene** [react-native-community/react-native-svg#776]
I don't see much mention of testing and it looks like testID, supported by react-native components, is not used as a prop. I'm looking in to implementing this. Are others doing so or is there an existing open issue that addresses the testing of react-native-svg components?

**Comment by msand** [comment]
@phosphene I would love to have any kind of testing available, your contributions would be more than welcome! ❤️Ideally we would run tests with most of the files from https://github.com/web-platform-tests/wpt/tree/master/svg on each commit. A bit more info:
https://github.com/w3c/svgwg/wiki/Testing

**Comment by phosphene** [comment]
Great. The first order of business for end to end testing is to either add the testID prop to react-native-svg components or to add a  "one-off prop pass-through" for testID. Or we can pass "the entire props through". The second option "is more extensible for any future props that are desired" but could open us to other issues.

I'm having trouble right now passing through testID. I can investigate what the issue is with that. Or perhaps you see the solution/issue right away?

testID is supported core react-native components. 
https://facebook.github.io/react-native/docs/view#testid


https://github.com/peacechen/react-native-modal-selector/pull/48

**Comment by phosphene** [comment]
To clarify. Here is another project that implemented prop pass through, so this pull request may serve as an example. 
https://github.com/peacechen/react-native-modal-selector/pull/48

**Comment by phosphene** [comment]
Hey there. I'm sorry to say I've been engaged in other work.

**Comment by msand** [comment]
Alright, no worries. Anyway, would be great to get some regression tests, and perhaps even compare against the reference images used by firefox and chrome etc. If anyone is interested, already investigating other react-native modules how they do testing of their iOS and Android native code and documenting it here would be great. Then there would be a clear path forwards as soon as someone has time to look at this.

I guess the expo and react-native codebases might be the main ones to look at. But, at least hopefully, someone knows about some well tested native module and can suggest/link to it here. Ideally something showing a ci setup running unit, integration and acceptance tests for native code in both android and ios. And if someone knows about a provider who gives this for free to open-source projects, that would certainly simplify things, alternatively perhaps someone could sponsor it? I would assume this library has provided its fair share of value to various native app stakeholders. I wonder what it would take to get them to provide even a bit monetary compensation for more stability and reliability in a relatively critical component. Especially when it would go straight to running costs of providing automated testing.

**Comment by msand** [comment]
I tried setting up some end-to-end tests here in case you're interested: https://github.com/msand/react-native-svg-e2e

**Comment by phosphene** [comment]
thanks! I will check it out.

**Comment by msand** [comment]
Having a bit of trouble getting e2e test to work on android in travis-ci and bitrise. Works fine locally on both android and ios. And, now I think I found a workaround for travis at least: https://travis-ci.org/msand/react-native-svg-e2e/builds/501950972
But haven't got android tests to work on bitrise a single time yet. Also opened an issue in the detox repo: https://github.com/wix/Detox/issues/1194

**Comment by phosphene** [comment]
Interesting.

**Comment by msand** [comment]
Managed to get x86 and x86_64 android images running on travis using the latest android emulator canary, which now works in headless mode without hardware acceleration / kvm support: https://travis-ci.org/msand/test_emulators/builds/502382369

**Comment by msand** [comment]
Got android working on bitrise now as well: https://app.bitrise.io/build/c31c1a40907cd137

**Comment by galkahana** [comment]
Hi, I think that i'm looking to do what @phosphene was looking to do. here with Appium, so testID is good for ios but i guess accesibilityLabel would fit on android. properties that exist on RN Views or TouchableOpacities, but not on the native SVG elements. Any hint on how to achieve a good extension? i see that there are mixins with Touchable all around, could this be used to help?

**Comment by galkahana** [comment]
ok. so ios side is not too difficult:
https://github.com/galkahana/react-native-svg/tree/feature/add-appium-detox-testID-support
but on android these are not even views...it's a canvas. wonder how i can orchestrate things like contentDescription and viewTag to match RN interpretations of testID and accessibilityLabel

**Comment by galkahana** [comment]
Did the android part as well.
PR is here - https://github.com/react-native-community/react-native-svg/pull/1359
Hopefully i got the invalidation part right. not sure it's required in this case, would love a note on this. I mean i'm sure it's not harmful, but not sure if actually required.

**Comment by galkahana** [comment]
Created a new PR to extend the previous one - https://github.com/react-native-community/react-native-svg/pull/1372
This one takes care of something that was problematic when using svg elements on android in appium. you couldn't interact or see the elements in appium desktop or secript.
The PR sets the right accessibility values to correct this.
