### ISSUE TITLE
Execution failed for task ':react-native-svg:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by angel-rs** [react-native-community/react-native-svg#779]
**Build fails for android:**

> Task :react-native-svg:compileDebugJavaWithJavac FAILED
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/GroupShadowNode.java:20: error: cannot find symbol
import android.support.annotation.RequiresApi;
                                 ^
  symbol:   class RequiresApi
  location: package android.support.annotation
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/GroupShadowNode.java:143: error: cannot find symbol
                @RequiresApi(api = Build.VERSION_CODES.KITKAT)
                 ^
  symbol: class RequiresApi
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RenderableView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

I removed these lines:

/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/GroupShadowNode.java:20
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/GroupShadowNode.java:143

And then it worked.

I'm running on:
```
"dependencies": {
    "react": "16.0.0",
    "react-native": "^0.55.3",
    "react-native-svg": "^7.0.1",
  },

```
**[Expected behaviour]:**

Me able to run react-native-svg without removing anything.

**Comment by angel-rs** [comment]
Thank you very much, now it's working perfectly!

**Comment by PrincewillIroka** [comment]
I used this to solve the error: 
cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug

**Comment by lfabl** [comment]
Please run this and then test again:
```
yarn remove react-native-svg
```
or
```
npm uninstall react-native-svg
```
