### ISSUE TITLE
[android] bug: text-decoration not supported

### ISSUE THREAD

**Issue by Rowandjj** [react-native-community/react-native-svg#782]
The following flags has no effect at all, because we use `paint#getTextPath()` to draw text instead of `canvas#drawText()`. Maybe we should draw text-decoration ourselves.

```
 paint.setUnderlineText(underlineText);
 paint.setStrikeThruText(strikeThruText);
```

**Comment by msand** [comment]
True, could you try implementing it?

**Comment by Rowandjj** [comment]
I'll t ry

**Comment by songzhw** [comment]
just a comment: iOS also has the same issue, "textDeocration" does not work

**Comment by sheshnathiicmr** [comment]
I am new to react-native, will see if I can fix with given info
