### ISSUE TITLE
「iOS」use svg to render background unsuccessful，the view show white screen

### ISSUE THREAD

**Issue by huangdaxiaEX** [react-native-community/react-native-svg#785]
Hello, 

When I use rnsvg to render a gradient background  not render success. like this picture. 😖
![11939](https://user-images.githubusercontent.com/13418292/45687614-df84d580-bb81-11e8-896a-fc36dc76e0f5.jpg)

I don't know how to solve this problem. This problem is not inevitable. 
Work fine on Android.

React Native version is 0.51,  RNSVG version is 5.5.1

Thank you for your time.

**Comment by msand** [comment]
Can you try with v8.0.8?

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
