### ISSUE TITLE
Element type is invalid - Check the render method

### ISSUE THREAD

**Issue by YoshiYo** [react-native-community/react-native-svg#787]
Hi guys,

I have a problem using the react-native-svg package. 

RN : ~0.55.4
React : 16.3.1
RNSVG : ^7.0.2
Expo : ^29.0.0

I have this following error : 
![screen shot 2018-09-19 at 12 09 56](https://user-images.githubusercontent.com/8858857/45747036-f7ea0400-bc04-11e8-9709-37b573c15f27.png)

I used a correct linking, provided from expo, with this import : 
`import { Svg } from 'expo';`

This is an exemple of a code I using. 
```
<Svg
                width="12"
                height="12"
                xmlns="http://www.w3.org/2000/Svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
              >
                <Svg.Defs>
                  <Svg.Path
                    d="M7 12.25a5.25 5.25 0 1 1 0-10.5 5.25 5.25 0 0 1 0 10.5zm0-1.167a4.083 4.083 0 1 0 0-8.166 4.083 4.083 0 0 0 0 8.166zm-2.625-3.5a.292.292 0 0 1 .583 0c0 .785.9 1.459 2.042 1.459 1.143 0 2.042-.674 2.042-1.459a.292.292 0 1 1 .583 0c0 1.15-1.19 2.042-2.625 2.042-1.434 0-2.625-.893-2.625-2.042zm.292-1.166a.583.583 0 1 1 0-1.167.583.583 0 0 1 0 1.167zm4.666 0a.583.583 0 1 1 0-1.167.583.583 0 0 1 0 1.167z"
                    id="a"
                  />
                </Svg.Defs>
                <Svg.G transform="translate(-1 -1)" fill="none" fillRule="evenodd">
                  <Svg.Path d="M0 0h14v14H0z" />
                  <Svg.Mask id="b" fill="#fff">
                    <Svg.Use xlinkHref="#a" />
                  </Svg.Mask>
                  <Svg.Use fill="#FFF" xlinkHref="#a" />
                  <Svg.G mask="url(#b)" fill="#383A3B">
                    <Svg.Path d="M0 0h14v14H0z" />
                  </Svg.G>
                </Svg.G>
              </Svg>
```

I tried to convert 2 svg to Svg for RN, but  there is nothing to do here.
It doesn't work.

Do you have a solution for this ?
Best Regards,
Guillaume.

**Comment by msand** [comment]
The Mask element was introduced in v7 and Expo still uses 6.2.2 or something like that I think. You'll need to eject or use plain react-native.

**Comment by YoshiYo** [comment]
Hi @msand 
Thanks you for your answer. I opened an issue on Expo to ask for an update. 
You're right, I will follow the issue on Expo.
