### ISSUE TITLE
'RNSVGPattern.h' file not found

### ISSUE THREAD

**Issue by rendomnet** [react-native-community/react-native-svg#791]
After updating from 6.5.2 to 7.0.3
I have this error in ios build
'RNSVGPattern.h' file not found'

**Comment by msand** [comment]
Can you try re-linking react-native-svg? https://github.com/react-native-community/react-native-svg/issues/795

**Comment by msand** [comment]
If any problems remain, or if you have problems because of XCode 10, you can uncheck "Parallelize builds" for RNSVG: https://github.com/react-native-community/react-native-svg/issues/817#issuecomment-432323509
