### ISSUE TITLE
Building react-native-svg@7.0.3 with iOS 12 and XCode10 failed

### ISSUE THREAD

**Issue by evaleirasclapps** [react-native-community/react-native-svg#796]
Hi, I'm trying to build my app and XCode is throwing the following:
```
Showing Recent Messages
:-1: Build input file cannot be found: '/PATH/node_modules/react-native-svg/ios/Brushes/RNSVGPattern.m'
```

### **Relative versions:**
- react-native@0.56.0
- react@16.4.1
- react-native-svg@7.0.3
- @babel/core@7.0.0-beta.47
- babel-core@7.0.0-bridge.0
- babel-preset-react@^6.24.1
- babel-preset-react-native@5.0.2

**Comment by evaleirasclapps** [comment]
After ran:
```
react-native unlink react-native-svg
react-native link react-native-svg
```

Still not working!

**Comment by msand** [comment]
Very strange, can you try
rm -rf node_modules
And run yarn / npm

**Comment by msand** [comment]
If any problems remain, or if you want an alternative solution to the legacy build system, you can uncheck "Parallelize builds" for RNSVG: https://github.com/react-native-community/react-native-svg/issues/817#issuecomment-432323509
