### ISSUE TITLE
Invariant Violation: Native component for RNSVGPath does not exist

### ISSUE THREAD

**Issue by Carey678** [react-native-community/react-native-svg#798]
I can't use svg file, the error is Invariant Violation: Native component for RNSVGPath does not exist. I relink again, still does't work

"react": "16.2.0", 
"react-native": "0.53.0",
"react-native-svg": "^7.0.3",

and Xcode Version 8.2 (8C38)

**Comment by Tino-F** [comment]
I have an Samsung Galaxy S8 and I'm getting the same error message. I have also tried relinking, reinstalling, resetting the cache when starting npm, manually linking the library, and none of it has worked.

**Comment by herdsothom** [comment]
Getting the same problem on android, searched for about 8 hours for a solution today, none of the manual linking fixes it. I've tried different versions, nothings working.

**Comment by lau-sam** [comment]
Same problem here. "react": "16.3.1", "react-native": "0.55.4", "react-native-svg": "^6.5.2". 

`
blob:http://localhos…-7fc25d1b849c:16015 Invariant Violation: Native component for "RNSVGPath" does not exist

This error is located at:
    in RNSVGPath (at Path.js:25)
    in Path (at svgs.js:65)
    in RNSVGGroup (at G.js:25)
    in G (at svgs.js:64)
    in RNSVGSvgView (at Svg.js:92)
    in Svg (created by SvgIcon)
    in SvgIcon (at Icon.js:5)
`

**Comment by Ajaykumar02** [comment]
HI Team,I too had the same issue, and its critical please take it high priority.

**Comment by msand** [comment]
Please provide a full replication. This works fine in a clean project and the issue is probably unrelated to this library.
