### ISSUE TITLE
G-SVG doesnt show my Image inside it - react-native

### ISSUE THREAD

**Issue by smemamian** [react-native-community/react-native-svg#800]
I'm using `react-native-svg`. I want to show my image inside it but `G` doesnt show it:

     <G x={endCoord2.x-widthHeight} y={endCoord2.y-widthHeight}>
              <Image resizeMode='stretch' style={{width:50,height:50,margin:4}} source={{uri: 'https://javacupcake.com/wp-content/uploads/2017/07/IceCreamConeCupcakes_0307.jpg'}} />
     </G>

where is my wrong?

**Comment by smemamian** [comment]
any solution?

**Comment by msand** [comment]
Are you using Image from react native? That doesn't work inside svg components. You need to import from react-native-svg like here: https://github.com/react-native-community/react-native-svg/blob/master/README.md#image

**Comment by tanasin-vivitvorn** [comment]
I got the same problem with the code that render 2 complicate SVG.
The complicate render fine but the Image from SVG is not show.
Here is the code that not rendering.

`<Svg
                        viewBox="0 0 100 100"
                        height="100"
                        width="100"
                    >
                        <SvgImage
                            onPress={() => alert('press on Image')}
                            x="0"
                            y="0"
                            height="100"
                            width="100"
                            href={require('../images/logo.jpg')}
                            opacity="1.0"
                        />
                    </Svg>`

But this rendering OK

`<Svg id="Header" viewBox="0 0 350 80" height="100%" width="100%">
                                <Defs>
                                    <LinearGradient id="linearGradient" x1="0.165" x2="0.907" y2="1.165" gradientUnits="objectBoundingBox">
                                        <Stop offset="0" Stop-color="#152a73" Stop-opacity="0.729" />
                                        <Stop offset="1" Stop-color="#666c83" Stop-opacity="0.729" />
                                    </LinearGradient>
                                    <ClipPath id="clip-path">
                                        <Rect id="Mask" fill="url(#linearGradient)" width="350" height="80" rx="14" />
                                    </ClipPath>
                                    <LinearGradient id="linearGradient3" x1="0.5" y1="-0.021" x2="0.5" y2="0.921" gradientUnits="objectBoundingBox">
                                        <Stop offset="0" Stop-color="#5d76cb" />
                                        <Stop offset="1" Stop-color="#0c1a49" />
                                    </LinearGradient>
                                    <LinearGradient id="linearGradient4" x1="0.5" x2="0.5" y2="0.98" gradientUnits="objectBoundingBox">
                                        <Stop offset="0" Stop-color="#333f65" Stop-opacity="0.659" />
                                        <Stop offset="1" Stop-color="#0f1d4f" Stop-opacity="0.659" />
                                    </LinearGradient>
                                </Defs>
                                <G id="Rectangle_4_Rectangle_4_Rectangle_4_bicycle-1838605_1280_Mask" data-name="Rectangle 4 + Rectangle 4 + Rectangle 4 + bicycle-1838605_1280 Mask">
                                    <G id="Rectangle_4_Rectangle_4_Rectangle_4_Mask" data-name="Rectangle 4 + Rectangle 4 + Rectangle 4 Mask">
                                        <Rect id="Mask-2" data-name="Mask" fill="url(linearGradient)" width="350" height="80" rx="14" />
                                        <G id="Rectangle_4_Rectangle_4_Rectangle_4_Mask-2" data-name="Rectangle 4 + Rectangle 4 + Rectangle 4 Mask" clipPath="url(#clip-path)">
                                            <Rect id="Bitmap" opacity="0.205" fill="none" width="316" height="425.495" transform="matrix(0.391, -0.921, 0.921, 0.391, -143.57, 56.159)" />
                                            <Path id="Rectangle_4" data-name="Rectangle 4" opacity="0.569" fill="{url(linearGradient3)}" d="M0,165.51c0-28.916,39.8-41.671,56.61-18.141h0c36.982-16.555,82.854-49.6,97.8-54.181,17.933-5.5,50.818,27.7,69.2,22.628,17.878-4.936,43.244-75.553,60.23-75.553,26.009,0,45.176,43.6,59.364,38.525,17.46-6.243,33.751-61.724,48.567-74.088h0c16.374-5.585,36.249,8.636,36.249,25.935V135.7a32,32,0,0,1-32,32H32a32,32,0,0,1-32-32Z" transform="translate(-63.663 -67.404) rotate(7)" />
                                            <Path id="Rectangle_4-2" data-name="Rectangle 4" opacity="0.698" fill="{url(#linearGradient4)}" d="M0,173.817a32,32,0,0,1,45.98-28.785l8.211,3.988c25.467-6.743,37.894-32.065,64.1-43.154,18.14-7.676,42.51,17.1,60.948,16.836,21.258-.308,40.261-65.311,64.629-72.986s38,33.828,64.614,26.158C354.881,62.5,351.939,10.359,386.067,0H396a32,32,0,0,1,32,32V143.824a32,32,0,0,1-32,32H32a32,32,0,0,1-32-32Z" transform="translate(-62.691 -75.535) rotate(7)" />
                                        </G>
                                    </G>
                                </G>
                                <G id="Group_3" data-name="Group 3" transform="translate(19 18)">
                                    <Text id="Today" fontSize="24" fill="#f2f2f2" fontFamily="Helvetica" transform="translate(1 35)"><TSpan x="0" y="5">{this.state.searchDate}</TSpan></Text>
                                    <Text id="Events_will_happen" data-name="Events will happen" fontSize="14" fill="#f2f2f2" fontFamily="Helvetica" transform="translate(0 11)"><TSpan x="0" y="0">Events will happen</TSpan></Text>
                                </G>
                                <G id="Group_297" data-name="Group 297" transform="translate(289 22)">
                                    <Path id="Stroke_287" data-name="Stroke 287" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M8.78,7.113C7.153,8.74,0,10,0,10S1.26,2.848,2.887,1.22A4.167,4.167,0,0,1,8.78,7.113Z" transform="translate(0 27)" />
                                    <Path id="Stroke_291" data-name="Stroke 291" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M.048,13H0A7.906,7.906,0,0,0,1.2,3.33L7.389,0C9.324,5.583,6.605,13,.048,13Z" transform="translate(11 23)" />
                                    <Path id="Stroke_293" data-name="Stroke 293" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M13,.607,9.694,6.792A7.9,7.9,0,0,0,0,8C0,1.413,7.419-1.325,13,.607Z" transform="translate(0 17)" />
                                    <Path id="Stroke_295" data-name="Stroke 295" fill="#fff" d="M0,30l0,0,3.172-5.918,3.237-6.062c.3-.461,7.436-11.337,10.957-14.858C18.951,1.576,22.3.8,24.833.43A43.324,43.324,0,0,1,30,0a.075.075,0,0,1,0,.019,44.123,44.123,0,0,1-.431,5.148c-.371,2.532-1.145,5.882-2.727,7.464C23.408,16.066,13.185,22.8,12.031,23.558l-6.11,3.269L0,30Zm18.948-22.1A3.158,3.158,0,1,0,22.1,11.053,3.162,3.162,0,0,0,18.948,7.895Z" transform="translate(6)" />
                                </G>
                            </Svg>`

So strange!

This issue is impact me a lot. Any help would be greatly appreciated.

**Comment by lachtos** [comment]
I also had a problem with Image not showing. I worked around it by using the new Pattern definition, not sure how impactful it is performance/memory-wise.

**Comment by lachtos** [comment]
It's likely. It worked on 6.5.2 and I used clipping for the Image component.

**Comment by msand** [comment]
This seems to work in both iOS and Android with the latest commit from the master branch at least:
```jsx
import * as React from 'react';
import { Svg, Image, Rect } from 'react-native-svg';
import { View, StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg viewBox="0 0 100 100" width={width} height={height}>
          <Rect
            fill="black"
            x="0"
            y="0"
            width="100"
            height="100"
            onPress={() => alert('press')}
          />
          <Image
            x="0"
            y="0"
            width="100"
            height="100"
            href={require('./1131362.jpeg')}
            onPress={() => alert('press')}
          />
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
});
```

**Comment by msand** [comment]
Perhaps you we're using clipping? The implementation has changed to be more spec conformant (and there was a regression as well until 8.0.6, you might need to move your clipRule attribute to the ClipPath elements from the elements where you have the clipPath attribute.
