### ISSUE TITLE
[Rect] width not being animated via createAnimatedComponent and interpolate

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/react-native-svg#803]
I have simple animation interpolation going on for `<Rect />` element, however I see no changes on my ui, as if width is staying 0.

I manually added my end value to the component as `width={149.12}` and it displayed it correctly, hence I am a bit confused now to why it is not picking up same value from animation?

**react-native@0.57.1**
**react-native-svg@7.0.3**
**iOS**

Here is full implementation, in essence a mana and health bar that take in current value and total value i.e. 50 and 100 should display half width for the rect. (Example uses typescript)

```js
import * as React from 'react'
import { Animated } from 'react-native'
import Svg, { Defs, LinearGradient, Rect, Stop } from 'react-native-svg'
import { deviceWidth } from '../services/Device'

const barWidth = deviceWidth * 0.3454
const barHeight = barWidth * 0.093
const AnimatedRect = Animated.createAnimatedComponent(Rect)

/**
 * Types
 */
export interface IProps {
  variant: 'MANA' | 'HEALTH'
  currentValue: number
  totalValue: number
}

export interface IState {
  width: Animated.Value
}

/**
 * Component
 */
class HealthManaBar extends React.Component<IProps, IState> {
  state = {
    width: new Animated.Value(0)
  }

  rectangleRef = React.createRef()

  componentDidMount() {
    const { currentValue, totalValue } = this.props
    this.animate(currentValue, totalValue)
  }

  componentDidUpdate({ currentValue, totalValue }: IProps) {
    this.animate(currentValue, totalValue)
  }

  animate = (current: number, total: number) =>
    Animated.timing(this.state.width, {
      toValue: current !== 0 ? current / total : 0,
      duration: 400,
      useNativeDriver: false
    }).start()

  render() {
    const { variant } = this.props
    const { width } = this.state

    return (
      <Svg width={barWidth} height={barHeight}>
        <Defs>
          <LinearGradient
            id={`HeathManaBar-gradient-${variant}`}
            x1="0"
            y1="0"
            x2="0"
            y2={barHeight}
          >
            <Stop
              offset="0"
              stopColor={variant === 'HEALTH' ? '#EC561B' : '#00ACE1'}
              stopOpacity="1"
            />
            <Stop
              offset="0.5"
              stopColor={variant === 'HEALTH' ? '#8D1B00' : '#003FAA'}
              stopOpacity="1"
            />
            <Stop
              offset="1"
              stopColor={variant === 'HEALTH' ? '#9F3606' : '#007C97'}
              stopOpacity="1"
            />
          </LinearGradient>
        </Defs>
        <AnimatedRect
          x="0"
          y="0"
          rx="3"
          ry="3"
          width={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth]
          })}
          height={barHeight}
          fill={`url(#HeathManaBar-gradient-${variant})`}
        />
      </Svg>
    )
  }
}

export default HealthManaBar
```

NOTE: this is based on following example https://github.com/msand/SVGPodTest/blob/a74a600818e496efaa78298291b63107295064bf/App.js#L14-L57

Only difference I see is that it uses strings `'0'` and `'50'`, which I also tried, but got react native error saying that `NSString can't be converted to Yoga Value`. However, when I pass width to my `<Rect />` as an integer it works correctly, so I assume this shouldn't matter as much in v7?

**Comment by IljaDaderko** [comment]
I also tried changing interpolation to `setNativePropos` approach that updates rect width during animation, but same result.

**Comment by msand** [comment]
This seems to work fine at least:
https://snack.expo.io/@msand/animate-rect-width
```jsx
import React, { Component } from 'react';
import { View, StyleSheet, Dimensions, Animated } from 'react-native';
import { Svg } from 'expo';

const { Rect } = Svg;

const { width, height } = Dimensions.get('window');
const AnimatedRect = Animated.createAnimatedComponent(Rect);
const AnimatedSvg = Animated.createAnimatedComponent(Svg);

class SvgRoot extends Component {
  state = {
    initAnim: new Animated.Value(0),
  };

  componentDidMount() {
    Animated.timing(
      // Animate over time
      this.state.initAnim,
      {
        toValue: 1,
        duration: 3000,
        useNativeDriver: false,
      }
    ).start();
  }

  render() {
    const { initAnim } = this.state;
    let animateWidth = initAnim.interpolate({
      inputRange: [0, 1],
      outputRange: ['0', '80'],
    });
    return (
      <AnimatedSvg width={width} height={height} viewBox="0 0 100 100">
        <AnimatedRect
          y="10"
          x="10"
          height="80"
          width={animateWidth}
        />
      </AnimatedSvg>
    );
  }
}

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <SvgRoot />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by IljaDaderko** [comment]
@msand I'm not sure, but isn't expo still on v6 of react-native-svg?

Also
```js
    let animateWidth = initAnim.interpolate({
      inputRange: [0, 1],
      outputRange: ['0', '80'],
    });
```

You used strings here for output range, which in rn 0.57.x yields error

```
NSString can't be converted to Yoga Value
```

I think with v7 we can use numbers as well?

**Comment by msand** [comment]
Do you have useNativeDriver: false?

**Comment by IljaDaderko** [comment]
@msand I didn't, but added it just in case and tested, same result. I added it to code in my question to reflect current state. I think `useNativeDriver ` should be "undefined" by default anyway however.

I also tried animating width of `Svg` element instead of rect, no luck there either :/ 

I'm not sure if it helps at all, but I added ref to my `AnimatedRect` its width doesn't seem to be a number or string, rather animated interpolation function, not sure if this is causing issue possibly?

<img width="685" alt="screenshot 2018-10-09 at 14 56 01" src="https://user-images.githubusercontent.com/3154053/46667867-93064600-cbd3-11e8-87cd-6b4672cbf278.png">

**Comment by IljaDaderko** [comment]
Small update, if I just use `<Rect />` instead of `<AnimatedRect />` I get typescript error

> [ts]
> Type 'AnimatedInterpolation' is not assignable to type 'string | number | undefined'.
>   Type 'AnimatedInterpolation' is not assignable to type 'number'.
> index.d.ts(254, 3): The expected type comes from property 'width' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RectProps, any, any>> & Readonly<{ children?: ReactNode; }> & Readonly<RectProps>'
> (JSX attribute) width: Animated.AnimatedInterpolation

If I use animated component, this goes away

**Comment by msand** [comment]
Please try with the latest commit from the master branch, it should work both with and without native driver now, at least this code seems to work fine:
```jsx
import React from "react";
import { Dimensions, Animated } from "react-native";
import Svg, { Defs, LinearGradient, Rect, Stop } from "react-native-svg";

const { width, height } = Dimensions.get("window");

const barWidth = width * 0.3454;
const barHeight = barWidth * 0.093;
const AnimatedRect = Animated.createAnimatedComponent(Rect);

/**
 * Component
 */
class HealthManaBar extends React.Component {
  state = {
    width: new Animated.Value(0),
  };

  rectangleRef = React.createRef();

  componentDidMount() {
    const { currentValue, totalValue } = this.props;
    this.animate(currentValue, totalValue);
  }

  componentDidUpdate({ currentValue, totalValue }) {
    this.animate(currentValue, totalValue);
  }

  animate = (current, total) =>
    Animated.timing(this.state.width, {
      toValue: current / total,
      duration: 4000,
      useNativeDriver: true,
    }).start();

  render() {
    const { variant } = this.props;
    const { width } = this.state;

    return (
      <Svg width={barWidth} height={barHeight}>
        <Defs>
          <LinearGradient
            id={`HeathManaBar-gradient-${variant}`}
            x1="0"
            y1="0"
            x2="0"
            y2={barHeight}
          >
            <Stop
              offset="0"
              stopColor={variant === "HEALTH" ? "#EC561B" : "#00ACE1"}
              stopOpacity="1"
            />
            <Stop
              offset="0.5"
              stopColor={variant === "HEALTH" ? "#8D1B00" : "#003FAA"}
              stopOpacity="1"
            />
            <Stop
              offset="1"
              stopColor={variant === "HEALTH" ? "#9F3606" : "#007C97"}
              stopOpacity="1"
            />
          </LinearGradient>
        </Defs>
        <AnimatedRect
          x="0"
          y="0"
          rx="3"
          ry="3"
          rectwidth={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
          width={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
          height={barHeight}
          fill={`url(#HeathManaBar-gradient-${variant})`}
        />
      </Svg>
    );
  }
}

export default function App() {
  return <HealthManaBar totalValue={100} currentValue={50} variant="HEALTH" />;
}

```

**Comment by adam-s** [comment]
I'm having the same problem with props x, y on the Text, G, and TSpan components.

**Comment by msand** [comment]
It requires replicating these changes to those components and properties:

ios: https://github.com/react-native-community/react-native-svg/commit/7c012a9fe37aad146e7794a35a4238481b7d4703

android: 
the changes in 
android/src/main/java/com/horcrux/svg/RectShadowNode.java
and
android/src/main/java/com/horcrux/svg/RenderableViewManager.java
https://github.com/react-native-community/react-native-svg/commit/e307eeee57b72401fe1b13c75f9642b56ccced69#diff-f992420cdd73af55d1a573a979adec6eR16

@adam-s Could you attempt making the changes and open a pr?

**Comment by msand** [comment]
@adam-s I realized it requires some other changes in the js side as well: https://github.com/react-native-community/react-native-svg/commit/2a43579404b35db6b6b9613c05076170e02203e3
Now I have support for animation of transforms, x, y etc on G, Text and TSpan at least with useNativeDriver: false
Try something like this:
```jsx
import React from "react";
import { Dimensions, Animated } from "react-native";
import Svg, { Defs, LinearGradient, Rect, Stop, Text, TSpan, G } from "react-native-svg";

const { width, height } = Dimensions.get("window");

const barWidth = width * 0.5;
const barHeight = barWidth * 0.5;
const AnimatedRect = Animated.createAnimatedComponent(Rect);
const AnimatedText = Animated.createAnimatedComponent(Text);
const AnimatedTSpan = Animated.createAnimatedComponent(TSpan);
const AnimatedG = Animated.createAnimatedComponent(G);

/**
 * Component
 */
class HealthManaBar extends React.Component {
  state = {
    width: new Animated.Value(0),
  };

  rectangleRef = React.createRef();

  componentDidMount() {
    const { currentValue, totalValue } = this.props;
    this.animate(currentValue, totalValue);
  }

  componentDidUpdate({ currentValue, totalValue }) {
    this.animate(currentValue, totalValue);
  }

  animate = (current, total) =>
    Animated.timing(this.state.width, {
      toValue: current / total,
      duration: 4000,
      useNativeDriver: false,
    }).start();

  render() {
    const { variant } = this.props;
    const { width } = this.state;

    return (
      <Svg width={barWidth} height={barHeight}>
        <Defs>
          <LinearGradient
            id={`HeathManaBar-gradient-${variant}`}
            x1="0"
            y1="0"
            x2="0"
            y2={barHeight}
          >
            <Stop
              offset="0"
              stopColor={variant === "HEALTH" ? "#EC561B" : "#00ACE1"}
              stopOpacity="1"
            />
            <Stop
              offset="0.5"
              stopColor={variant === "HEALTH" ? "#8D1B00" : "#003FAA"}
              stopOpacity="1"
            />
            <Stop
              offset="1"
              stopColor={variant === "HEALTH" ? "#9F3606" : "#007C97"}
              stopOpacity="1"
            />
          </LinearGradient>
        </Defs>
        <AnimatedRect
          x="0"
          y="0"
          rx="3"
          ry="3"
          rectwidth={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
          width={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
          height={barHeight}
          fill={`url(#HeathManaBar-gradient-${variant})`}
        />
        <AnimatedG
          x={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
        >
          <AnimatedText y={width.interpolate({
            inputRange: [0, 1],
            outputRange: ['0', `${barHeight}`],
          })}
          >
            <AnimatedTSpan x={width.interpolate({
              inputRange: [0, 2],
              outputRange: ['0', `${barWidth}`],
            })}
            >
            Test
            </AnimatedTSpan>
          </AnimatedText>
        </AnimatedG>
      </Svg>
    );
  }
}

export default function App() {
  return <HealthManaBar totalValue={100} currentValue={50} variant="HEALTH" />;
}
```

**Comment by adam-s** [comment]
There is a PanResponder in a different component with a class that contains a lot of D3 logic. All I'm looking for is the text to be on the same x coordinate as the touch event. It works with Circle, Line, Animated.View, and Animated.Text.

````
import React from 'react';
import PropTypes from 'prop-types';
import { Animated } from 'react-native';
import { Text } from 'react-native-svg';

import CCColors from '../../common/components/CCColors';

const AnimatedText = Animated.createAnimatedComponent(Text);

const textStyle = {
  fill: CCColors.slate,
  fontFamily: "'Gill Sans', 'Gill Sans MT', 'Seravek', 'Trebuchet MS', sans-serif",
  fontSize: 14,
  letterSpacing: 'normal',
  stroke: 'transparent',
  textAnchor: 'middle',
};

const propTypes = {
  addListener: PropTypes.func.isRequired,
  removeListener: PropTypes.func.isRequired,
};
const defaultProps = {};

class HistoricalTooltip extends React.Component {
  constructor(props) {
    super(props);
    this.callback = this.callback.bind(this);
  }
  componentDidMount() {
    const { addListener } = this.props;
    addListener(this.callback);
  }
  componentWillUnmount() {
    const { removeListener } = this.props;
    removeListener(this.callback);
  }
  setRef(ref) {
    this.ref = ref;
  }
  callback(data) {
    const { x } = data;
    this.ref.setNativeProps({ x });
  }
  render() {
    return (
      <AnimatedText
        ref={ref => this.setRef(ref)}
        x={100}
        y={100}
        textAnchor="middle"
        text="hello"
      />
    );
  }
}

HistoricalTooltip.propTypes = propTypes;
HistoricalTooltip.defaultProps = defaultProps;

export default HistoricalTooltip;
````

**Comment by msand** [comment]
Now with support for useNativeDriver with transform styles using the same syntax as for react-native views: https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5
```jsx
import React from "react";
import { Dimensions, Animated } from "react-native";
import Svg, { Text, TSpan, G } from "react-native-svg";

const { width, height } = Dimensions.get("window");

const AnimatedG = Animated.createAnimatedComponent(G);

class NativeAnimGTransform extends React.Component {
  state = {
    anim: new Animated.Value(0),
  };

  componentDidMount() {
    this.animate(this.props.value);
  }

  componentDidUpdate({ value }) {
    this.animate(value);
  }

  animate = value =>
    Animated.timing(this.state.anim, {
      useNativeDriver: true,
      duration: 4000,
      toValue: value,
    }).start();

  render() {
    const { anim } = this.state;

    return (
      <Svg width={width} height={height}>
        <AnimatedG
          style={{
            transform: [
              {
                translateY: anim.interpolate({
                  inputRange: [0, 1],
                  outputRange: [0, 100],
                }),
              },
            ],
          }}
        >
          <Text>
            <TSpan>Test</TSpan>
          </Text>
        </AnimatedG>
      </Svg>
    );
  }
}

export default function App() {
  return <NativeAnimGTransform value={1} />;
}

```

**Comment by msand** [comment]
@adam-s Try something like this (with the latest commit from the master branch):
```jsx
  callback(data) {
    this.ref.setNativeProps({ positionX: data.x });
  }
```

**Comment by IljaDaderko** [comment]
@msand I tried this with latest master and it is now working, thank you! :)

Few caveats that I think are worth mentioning, in your example here you have `useNativeDriver: true` in my case when its true animation is not working, I need to either set it to false or not include it.
That said, I am not using `rectwidth` on my `<Rect />` element, just width.

Do I need to use `rectwidth` or can it be omitted?

**Comment by msand** [comment]
The rectwith is needed if you want the native animation to work, the width and height properties have a naming collision with the same property name, so they have the element name prepended on the native side, and Animated needs the native name to be able to animate it. Hopefully the naming collision could be avoided somehow, and the correct name would be sufficient.

**Comment by msand** [comment]
I would actually expect that we can get rid of the {use,mask,image,bb,pattern,rect}{width,height} attributes and just use width and height instead, as I've been able to override the transform
https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5#diff-50f7e7f8735df31a6ac08ae41511a2a6R262
https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5#diff-ba367d8c1ef85007a13efc389f1b0608R156
view property handlers in the view managers, it should be possible to do the same with them as well.

**Comment by IljaDaderko** [comment]
> I would actually expect that we can get rid of the {use,mask,image,bb,pattern,rect}{width,height} attributes and just use width and height instead, as I've been able to override the transform
> [fb4e877#diff-50f7e7f8735df31a6ac08ae41511a2a6R262](https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5#diff-50f7e7f8735df31a6ac08ae41511a2a6R262)
> [fb4e877#diff-ba367d8c1ef85007a13efc389f1b0608R156](https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5#diff-ba367d8c1ef85007a13efc389f1b0608R156)
> view property handlers in the view managers, it should be possible to do the same with them as well.

If thats achievable, it definitely sounds less confusing and easier to get going with, I wonder how many people will skip setting `useNativeDriver` to true however since in general rn doesn't support it for width, only transitions and opacity atm I think? If skipped, will it cause any errors?

**Comment by msand** [comment]
@IljaDaderko I've simplified the handling in the way I thought should be possible: https://github.com/react-native-community/react-native-svg/commit/445780c121dbc5d8a683a7d33437ce84520f7583
Now use can skip rectwidth and simply use width instead both with and without useNativeDriver:
```jsx
import React from "react";
import { Dimensions, Animated } from "react-native";
import Svg, {
  LinearGradient,
  Defs,
  Rect,
  Stop,
  Text,
} from "react-native-svg";

const { width } = Dimensions.get("window");

const barWidth = width * 0.5;
const barHeight = barWidth * 0.5;
const AnimatedRect = Animated.createAnimatedComponent(Rect);
const AnimatedText = Animated.createAnimatedComponent(Text);

class HealthManaBar extends React.Component {
  state = {
    width: new Animated.Value(0),
  };

  componentDidMount() {
    const { currentValue, totalValue } = this.props;
    this.animate(currentValue, totalValue);
  }

  componentDidUpdate({ currentValue, totalValue }) {
    this.animate(currentValue, totalValue);
  }

  animate = (current, total) =>
    Animated.timing(this.state.width, {
      toValue: current / total,
      duration: 4000,
      useNativeDriver: false,
    }).start();

  render() {
    const { variant } = this.props;
    const { width } = this.state;

    return (
      <Svg width={barWidth} height={barHeight}>
        <Defs>
          <LinearGradient
            id={`HeathManaBar-gradient-${variant}`}
            x1="0"
            y1="0"
            x2="0"
            y2={barHeight}
          >
            <Stop
              offset="0"
              stopColor={variant === "HEALTH" ? "#EC561B" : "#00ACE1"}
              stopOpacity="1"
            />
            <Stop
              offset="0.5"
              stopColor={variant === "HEALTH" ? "#8D1B00" : "#003FAA"}
              stopOpacity="1"
            />
            <Stop
              offset="1"
              stopColor={variant === "HEALTH" ? "#9F3606" : "#007C97"}
              stopOpacity="1"
            />
          </LinearGradient>
        </Defs>
        <AnimatedRect
          x="0"
          y="0"
          rx="3"
          ry="3"
          width={width.interpolate({
            inputRange: [0, 1],
            outputRange: [0, barWidth],
          })}
          height={barHeight}
          fill={`url(#HeathManaBar-gradient-${variant})`}
        />
        <AnimatedText
          x={width.interpolate({
            inputRange: [0, 2],
            outputRange: [0, barWidth],
          })}
          y={width.interpolate({
            inputRange: [0, 2],
            outputRange: [0, barHeight],
          })}
        >
          Test
        </AnimatedText>
      </Svg>
    );
  }
}

export default function App() {
  return <HealthManaBar totalValue={100} currentValue={50} variant="HEALTH" />;
}

```

**Comment by msand** [comment]
The difference between useNativeDriver: false and true, is that when false: the animation is driven by javascript calling setNativeProps on the animated element; when true: the animation is serialised and sent over the bridge to be driven by the native animation driver events, without any further processing from js, which is much faster in essentially every case and doesn't get blocked by long running js computations. The main reason one would disable the native driver is if the properties one needs to animate aren't supported.

But, my commits from the past two days should be relatively good inspiration for how to get support for all the remaining properties. To get js driven (useNativeDriver: falsy) animation, the js property extraction logic needs to be run in the setNativeProps handler of the svg elements, and to get useNativeDriver: true support, the property setters in the native view managers need to change their input parameter type to Dynamic (java) / id (obj-c) and the appropriate transformation done from the values provided by the native driver to the types expected by the shadow nodes / native views.

These would be excellent first issues / PRs for anyone interested in contributing to wider animation support. ❤️

**Comment by adam-s** [comment]
I'm having luck using Victory Native primitives which wrap the react-native-svg elements. https://github.com/FormidableLabs/victory-native/tree/master/lib/components/victory-primitives

**Comment by msand** [comment]
Now with useNativeDriver animation support for all number accepting properties: https://github.com/react-native-community/react-native-svg/commit/864d7610d3aaea2b4e4f722f04ea52ddf292aae7

**Comment by msand** [comment]
Reading the code now, I noticed that percentage values in strokeDashArray can't possibly be working correctly in iOS as it just takes the floatValue of the string.

**Comment by IljaDaderko** [comment]
@msand gotcha, I wasn't using `%` values, just had to stringily numbers in the array when I pass them to `setNativeProps`. It works fine that way 👍 

Thank you for clarification. One final side question regarding this whole issue: Do you have approximate eta when changes on master might go up to npm?

**Comment by msand** [comment]
Great. Yeah, just thought I would mention the % issue as I noticed it's not spec conformant, more a note to self for later.

Well, I would love to have a bit more testing of it before releasing. But as things usually go, the only way to get significant amounts of testing is to make a new release, most people don't live on the bleeding edge of the master branch. I could probably merge some PRs and cut a new release today, to speed up the process. People can always downgrade to whatever version worked the best previously and open issues to report any problems.

**Comment by msand** [comment]
Published v7.1.0 now

**Comment by IljaDaderko** [comment]
So far works fine on my end, I will close this issue as its concern was addressed with this release. Thank you for amazing support!

**Comment by msand** [comment]
You're welcome, happy we got it fixed 🎉 
I've simplified the property handling in the javascript side now, as the view managers can handle both string and number types with the recent changes: https://github.com/react-native-community/react-native-svg/commit/1e25870f5d04b91112e7167240dd1a7d4958815f
