### ISSUE TITLE
Invalid viewBox prop

### ISSUE THREAD

**Issue by mlwilkerson** [react-native-community/react-native-svg#809]
Looks like a recent change flipped the logic on the validation of the viewBox prop in `lib/extract/extractViewBox.js`.

Formerly, a viewBox prop of "0 0 640 512" was valid. Now it's not (as of v7.1.1,and starting somewhere between 7.0.3 and 7.1.1)

Getting a console warning (and this might be causing some other things to break as well, but I'm still debugging other rendering differences after upgrading to 7.1.1)
```
  console.warn node_modules/react-native-svg/lib/extract/extractViewBox.js:35
    Invalid `viewBox` prop:0 0 640 512
```

Will post a PR shortly to propose a fix.

**Comment by msand** [comment]
This came in v7.1.1 while doing some cleanup and fixing an unused param warning: https://github.com/react-native-community/react-native-svg/commit/6f256f1da142b6ab4eb0bd1422883aae5db5e3f3#diff-c9ec180f3cc5aa90652568270487b6caL34
Thanks for the PR!

What other issues are you experiencing?

**Comment by mlwilkerson** [comment]
I'm using the new Mask feature and my tests and example app is now broken when trying to render one, since upgrading from `7.0.3`. Still investigating the cause...

This is what's choking:

https://github.com/FortAwesome/react-native-fontawesome/blob/a57d41f0f24bc792b042adefab70e888cc3d8436/examples/Hello/App.js#L40

With this error:

```
JSON value '0' of type NSNumber cannot be converted to NSString

+[RCTConvert NSString:]
    RCTConvert.m:56
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.158
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.162
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2
RCTPerformBlockWithLogFunction
RCTPerformBlockWithLogPrefix
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke
__37-[RCTComponentData setProps:forView:]_block_invoke
-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
-[RCTComponentData setProps:forView:]
__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.463
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.540
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

**Comment by mlwilkerson** [comment]
Pretty sure my remaining issues just had to with needing to do a clean re-build. Eventually, the problems went away.
