### ISSUE TITLE
NPE in RenderableShadowNode

### ISSUE THREAD

**Issue by mars-lan** [react-native-community/react-native-svg#811]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.graphics.Path.computeBounds(android.graphics.RectF, boolean)' on a null object reference
com.horcrux.svg.RenderableShadowNode.draw (RenderableShadowNode.java:322)
com.horcrux.svg.RenderableShadowNode.render (RenderableShadowNode.java:305)
com.horcrux.svg.GroupShadowNode$1.run (GroupShadowNode.java:88)
com.horcrux.svg.VirtualNode.traverseChildren (VirtualNode.java:389)
com.horcrux.svg.GroupShadowNode.drawGroup (GroupShadowNode.java:79)
com.horcrux.svg.GroupShadowNode.draw (GroupShadowNode.java:70)
com.horcrux.svg.RenderableShadowNode.render (RenderableShadowNode.java:305)
com.horcrux.svg.GroupShadowNode$1.run (GroupShadowNode.java:88)
com.horcrux.svg.VirtualNode.traverseChildren (VirtualNode.java:389)
com.horcrux.svg.GroupShadowNode.drawGroup (GroupShadowNode.java:79)
com.horcrux.svg.GroupShadowNode.draw (GroupShadowNode.java:70)
com.horcrux.svg.RenderableShadowNode.render (RenderableShadowNode.java:305)
com.horcrux.svg.SvgViewShadowNode$3.run (SvgViewShadowNode.java:232)
com.horcrux.svg.SvgViewShadowNode.traverseChildren (SvgViewShadowNode.java:330)
com.horcrux.svg.SvgViewShadowNode.drawChildren (SvgViewShadowNode.java:227)
com.horcrux.svg.SvgViewShadowNode.drawOutput (SvgViewShadowNode.java:184)
com.horcrux.svg.SvgView.onDraw (SvgView.java:84)

**Comment by mars-lan** [comment]
react-native-svg 7.1.2

**Comment by msand** [comment]
Can you try with the latest commit from the master branch?

**Comment by msand** [comment]
or, if that doesn't help, then the plain-views branch https://github.com/react-native-community/react-native-svg/commit/0bdca66e2de07bd964f917fb04d4c60b9d3c0b0e

**Comment by msand** [comment]
if neither one of those fixes it, then please provide a reproduction, which can be run straight away by a simple copy-paste, or as a clone-able repo.

**Comment by msand** [comment]
Closing until a full replication is provided.
