### ISSUE TITLE
 Attempt to invoke virtual method 'android.graphics.Rect com.horcrux.svg.SvgViewShadowNode.getCanvasBounds()' on a null object reference

### ISSUE THREAD

**Issue by skymax406** [react-native-community/react-native-svg#819]
Hello i have many issue with the lib, one of them is following : 

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect com.horcrux.svg.SvgViewShadowNode.getCanvasBounds()' on a null object reference
>        at com.horcrux.svg.VirtualNode.getCanvasWidth(VirtualNode.java:344)
>        at com.horcrux.svg.VirtualNode.relativeOnWidth(VirtualNode.java:324)
>        at com.horcrux.svg.RectShadowNode.getPath(RectShadowNode.java:72)
>        at com.horcrux.svg.RenderableShadowNode.draw(RenderableShadowNode.java:311)
>        at com.horcrux.svg.RenderableShadowNode.render(RenderableShadowNode.java:301)
>        at com.horcrux.svg.GroupShadowNode$1.run(GroupShadowNode.java:87)
>        at com.horcrux.svg.VirtualNode.traverseChildren(VirtualNode.java:379)
>        at com.horcrux.svg.GroupShadowNode.drawGroup(GroupShadowNode.java:78)
>        at com.horcrux.svg.GroupShadowNode.draw(GroupShadowNode.java:69)
>        at com.horcrux.svg.RenderableShadowNode.render(RenderableShadowNode.java:301)
>        at com.horcrux.svg.SvgViewShadowNode$3.run(SvgViewShadowNode.java:220)
>        at com.horcrux.svg.SvgViewShadowNode.traverseChildren(SvgViewShadowNode.java:318)
>        at com.horcrux.svg.SvgViewShadowNode.drawChildren(SvgViewShadowNode.java:215)
>        at com.horcrux.svg.SvgViewShadowNode.drawOutput(SvgViewShadowNode.java:172)
>        at com.horcrux.svg.SvgView.onDraw(SvgView.java:98)
>        at android.view.View.draw(View.java:18397)
>        at android.view.View.draw(View.java:18301)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:18400)
>        at android.view.View.draw(View.java:18301)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:18400)
>        at android.view.View.buildDrawingCacheImpl(View.java:17682)
>        at android.view.View.buildDrawingCache(View.java:17543)
>        at android.view.View.updateDisplayListIfDirty(View.java:17356)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:18400)
>        at android.view.View.updateDisplayListIfDirty(View.java:17375)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at android.view.View.draw(View.java:18400)
>        at android.widget.ScrollView.draw(ScrollView.java:2654)
>        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:382)
>        at android.view.View.updateDisplayListIfDirty(View.java:17375)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at android.view.View.draw(View.java:18400)
>        at android.view.View.updateDisplayListIfDirty(View.java:17375)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at android.view.View.draw(View.java:18400)
>        at android.support.v4.view.ViewPager.draw(ViewPager.java:2426)
>        at android.view.View.updateDisplayListIfDirty(View.java:17375)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:18400)
>        at android.view.View.updateDisplayListIfDirty(View.java:17375)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.View.draw(View.java:18159)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:3968)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3754)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:17370)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
>        at android.view.View.updateDisplayListIfDirty(View.java:17338)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
>        at android.view.View.updateDisplayListIfDirty(View.java:17338)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
>        at android.view.View.updateDisplayListIfDirty(View.java:17338)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
>        at android.view.View.updateDisplayListIfDirty(View.java:17338)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3952)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3932)
>        at android.view.View.updateDisplayListIfDirty(View.java:17338)
>        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:722)
>        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:728)
>        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:836)
>        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3168)
>        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2964)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2552)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:734)
>        at android.view.Choreographer.doFrame(Choreographer.java:670)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6776)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

According to firebase, this exception happen on SVG display. Randomly. It often work, and sometime it crash, i dont know why ... An idea ? I have the last version of react-native and react-native-svg

Thank You

**Comment by msand** [comment]
Are you sure you have the latest version? V8.0.1 is the current one. That exception shouldn't be possible, the method shouldn't even exist.

**Comment by skymax406** [comment]
oO Ho sorry when when this error has occured my version was the latest .
But I did not see that there was a new version since 2 days  ... So i dont have latest version . I will test that Monday at job and I will tell you

**Comment by skymax406** [comment]
Hello, i have upgraded my react-native-svg version and this issue has apparently gone but was replaced by the following : 

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Matrix.mapRect(android.graphics.RectF)' on a null object reference
>        at com.horcrux.svg.GroupView.setupGlyphContext(GroupView.java:46)
>        at com.horcrux.svg.GroupView.draw(GroupView.java:74)
>        at com.horcrux.svg.RenderableView.render(RenderableView.java:312)
>        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:268)
>        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:221)
>        at com.horcrux.svg.SvgView.onDraw(SvgView.java:89)
>        at android.view.View.draw(View.java:19187)
>        at android.view.View.updateDisplayListIfDirty(View.java:18137)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:19190)
>        at android.view.View.updateDisplayListIfDirty(View.java:18137)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at android.view.View.draw(View.java:19190)
>        at android.widget.ScrollView.draw(ScrollView.java:1777)
>        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:382)
>        at android.view.View.updateDisplayListIfDirty(View.java:18137)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at android.view.View.draw(View.java:19190)
>        at android.support.v4.view.ViewPager.draw(ViewPager.java:2426)
>        at android.view.View.updateDisplayListIfDirty(View.java:18137)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.draw(View.java:19190)
>        at android.view.View.updateDisplayListIfDirty(View.java:18137)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.View.draw(View.java:18915)
>        at android.view.ViewGroup.drawChild(ViewGroup.java:4288)
>        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4074)
>        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
>        at android.view.View.updateDisplayListIfDirty(View.java:18128)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4272)
>        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4252)
>        at android.view.View.updateDisplayListIfDirty(View.java:18096)
>        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
>        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
>        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
>        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3080)
>        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2884)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2437)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1441)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7171)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
>        at android.view.Choreographer.doFrame(Choreographer.java:726)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
>        at android.os.Handler.handleCallback(Handler.java:789)
>        at android.os.Handler.dispatchMessage(Handler.java:98)
>        at android.os.Looper.loop(Looper.java:164)
>        at android.app.ActivityThread.main(ActivityThread.java:6710)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)


Any idea ?

**Comment by msand** [comment]
Could you post a small replication?

**Comment by skymax406** [comment]
I can't, it arrive randomly, often when navigation change ( I use react-navigation ) and a SVG is present on new page. I can't tell more

**Comment by msand** [comment]
Could you post a small replication?

**Comment by msand** [comment]
@skymax406 Can you try this one: https://github.com/react-native-community/react-native-svg/commit/13b91aab39481eb708a580a87d7118c6180d0e23

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
