### ISSUE TITLE
JSON value '50' of type NSString cannot be converted to a YGValue

### ISSUE THREAD

**Issue by tovesson** [react-native-community/react-native-svg#820]
Hi!

I'm using version 7.2.0 of react-native-svg. When doing something as simple as this:
`<Rect height="50" width="1640.96" fill="#acd6ea" x="-232.39" y="-289.21" />`
I get the following error: **JSON value '50' of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?** It seems like I need to specify height and width as follows:
`<Rect height={50} width={1640.96} fill="#acd6ea" x="-232.39" y="-289.21" />`
Is this really how it supposed to be? The readme file with instructions clearly tells that it should be a string, not and int.

**Comment by tovesson** [comment]
I got it working using the Xcode legacy build system

**Comment by msageryd** [comment]
I had this problem as well, but it went away when I upgraded from RNSVG 7 to 8.

**Comment by david-cako** [comment]
I was having issues where it wasn't converting strings to numbers.  Many hours spent, many combinations of RNSVG and victory-native (what I was using it with), clean builds all along the way, and I even bumped from react-native 0.55.4 to 0.57.3.  Nothing worked.

I started screwing with the order of libraries in my xcode project and that seemed to fix it.  One thing I remember doing specifically was putting cocoapods first in Linked Libraries and Frameworks.

I'd recommend if anyone is having issues with value conversion that they try putting RNSVG/cocoapods first.  I think there's something going on where another library I'm using is stomping on RNSVG's RCTConvert implementation.

**Comment by david-cako** [comment]
I was having issues where it wasn't converting strings to numbers.  Many hours spent, many combinations of RNSVG and victory-native (what I was using it with), clean builds all along the way, and I even bumped from react-native 0.55.4 to 0.57.3.  Nothing worked.

I started screwing with the order of libraries in my xcode project and that seemed to fix it.  One thing I remember doing specifically was putting cocoapods first in Linked Libraries and Frameworks.

I'd recommend if anyone is having issues with value conversion that they toy with the order of their linked libraries.  I think there's something going on where another library I'm using is stomping on RNSVG's RCTConvert implementation.

**Comment by david-cako** [comment]
I was having issues where it wasn't converting strings to numbers. Many hours spent, many combinations of RNSVG and victory-native (what I was using it with), clean builds all along the way, and I even bumped from react-native 0.55.4 to 0.57.3. Nothing worked.

I started screwing with the order of libraries in my xcode project and that seemed to fix it. One thing I remember doing specifically was putting cocoapods first in Linked Libraries and Frameworks.

I'd recommend if anyone is having issues with value conversion that they toy with the order of their linked libraries. I think there's something going on where another library I'm using is stomping on RNSVG's RCTConvert imports/implementation.

**Comment by mdere-unbound** [comment]
Has anyone confirmed @david-cako 's suggestion? I was doing this and no luck so far.

Should RNSVG.a be above Javascript core?

**Comment by msand** [comment]
The order shouldn't matter afaik. Can you make a clonable git repo with a reproduction?

**Comment by shouse** [comment]
I'm using `react-native-svg` ^9.4.0 - got this message with `<SVG height="30">` but it was fixed using the OP's suggestion `<SVG height={30}>` .  Oddly `<Rect />` and `<Polygon />` elements under the SVG component using quotes are still functional.  Adding this in case it helps anybody.  RN v0.55.4, FWIW
