### ISSUE TITLE
TouchableOpacity inside SVG not clickable

### ISSUE THREAD

**Issue by sebastijandumancic** [react-native-community/react-native-svg#826]
Hello all,

I have an issue where `TouchableOpacity` doesn't trigger `onPress` events when it's nested inside `svg` element. For same feature, I have different implementation where `TouchableOpacity` on Android is outside `svg` element and it registers tap just fine. As soon as it's inside header it just stops working. 

`react-native-svg: "7.0.3."`

Any ideas? Thanks!

**Comment by msand** [comment]
I don't think we've had support for that yet. Would be nice to have though. You can use onPress directly on the svg elements for now, or isolate the part you want touchable to animate in a separate svg root which you wrap with touchable. This will allow it to just change the opacity of the already rendered svg, rather than re-render its content each frame of the animation.

**Comment by sebastijandumancic** [comment]
Thanks for the answer @msand. So I should stop trying to get it to work, it won't until Touchable is outside Svg completely?

**Comment by msand** [comment]
Yeah, I haven't tested or tried to make it work until now at least, so I would expect it not to work. Not sure exactly what it would require either, haven't looked into what touchable requires of its children to animate them, or to understand their size/position on screen.

**Comment by sebastijandumancic** [comment]
Ok, thanks for the answer. Bump the thread if you ever get to work on it and thanks for everything else.

**Comment by mileslow2** [comment]
Has this svg problem been fixed?

**Comment by sebastijandumancic** [comment]
afaik no. I think I have overlayed button over svg in the end, since I couldn't get it to click inside SVG.

**Comment by msand** [comment]
Check here: https://github.com/react-native-community/react-native-svg/issues/645#issuecomment-453683513

**Comment by msand** [comment]
@sebastijandumancic @mileslow2 If either one of you is up for it, feel free to make the TouchableOpacityG code available as a package on github/npm, perhaps TouchableSvg would be a fitting name?

**Comment by chialuka** [comment]
Hello @msand, any update on this?
