### ISSUE TITLE
Accept a numeric type for the property offset

### ISSUE THREAD

**Issue by fabianhoward** [react-native-community/react-native-svg#827]
Here https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractGradient.js#L32 only accepts offsets of type string. It seems perfectly reasonable to me and indeed desirable that just like positional coordinates the offsets could be specified as floats.

Note I am talking only about when the offset is a numerical string not when it is a percentage.

**Comment by msand** [comment]
Yeah, I've actually already added support in the current work-in-progess branch: filters, you can try that if you want it asap.
