### ISSUE TITLE
Making build.gradle extensible

### ISSUE THREAD

**Issue by rajeshlifeon24** [react-native-community/react-native-svg#829]
Hello!
I've recently integrated react-native-svg in my app. I, however, found that the build.gradle is using hardcoded values for compile SDK, tools SDK, target SDK and min SDK. Here's the snippet:
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

That makes it very hard because this file is autogenerated and my android app is using different set of versions. So, I'm wondering if you would consider making the build.gradle more extensible like below:

def DEFAULT_COMPILE_SDK_VERSION = 26
def DEFAULT_BUILD_TOOLS_VERSION = "26.0.3"
def DEFAULT_TARGET_SDK_VERSION = 26
def DEFAULT_MIN_SDK_VERSION = 16

android {
compileSdkVersion 27
buildToolsVersion '27.0.3'

defaultConfig {
    minSdkVersion rootProject.hasProperty('minSdkVersion') ? rootProject.minSdkVersion : DEFAULT_MIN_SDK_VERSION
    targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
    versionCode 1
    versionName "1.0"
}

**Comment by msand** [comment]
Seems you're using an old version of the library, it currently uses the standard react-native way of setting the library versions: 

https://github.com/react-native-community/react-native-svg/blob/349c3b33675e761ece177884da35cebcd8fc82c0/android/build.gradle#L1-L3

https://github.com/facebook/react-native/blob/2a349f87f78a75163bc5cfd5e5233bfe00524676/local-cli/templates/HelloWorld/android/build.gradle#L4-L10
