### ISSUE TITLE
A problem occurred evaluating project ':react-native-svg'. > Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by zhushichuan** [react-native-community/react-native-svg#830]
A problem occurred evaluating project ':react-native-svg'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by FibreFoX** [comment]
@zhushichuan Which Gradle version do you use, and which version of the android-plugin?

**Comment by kapil708** [comment]
same issue here.
i am using 
classpath 'com.android.tools.build:gradle:2.2.3'
and RN:0.55.3

**Comment by kapil708** [comment]
solve it. by

from this
    implementation 'com.facebook.react:react-native:+'
to this
    compile 'com.facebook.react:react-native:+'

**Comment by FibreFoX** [comment]
@kapil708 your configured gradle-wrapper is just to old, try to have a more up2date version of it (like 4.6).

**Comment by zhushichuan** [comment]
> @ kapil708你配置的gradle-wrapper只是旧的，试着有更多的up2date版本（比如4.6）。

我试试

**Comment by zhushichuan** [comment]
> @ kapil708你配置的gradle-wrapper只是旧的，试着有更多的up2date版本（比如4.6）。

ok,Let me try

**Comment by FibreFoX** [comment]
This issue should get closed, as this is not the fault of this RN module, but the project-setup of the using app-project.

**Comment by Xiaojiju** [comment]
and u guys knows the lastest version?
