### ISSUE TITLE
Can any one guide me how to create arc shape

### ISSUE THREAD

**Issue by tarunmehta-quovantis** [react-native-community/react-native-svg#831]
I want to create arc shape , if any one can help me as I didn't find any arc shape here.
I want to build similar like below url

https://github.com/doc-ai/react-native-arc-progress

**Comment by msand** [comment]
Lmgtfy https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands
http://www.pindari.com/svg-arc.html
http://xahlee.info/js/svg_path_ellipse_arc.html

**Comment by msand** [comment]
You might get some inspiration from this as well: https://github.com/react-native-community/react-native-svg/issues/845#issuecomment-439592694
