### ISSUE TITLE
Pattern doesn't work

### ISSUE THREAD

**Issue by Chooster** [react-native-community/react-native-svg#832]
The error I'm getting is: `Invariant Violation: Native component for "RNSVGPattern" does not exist`

```
<Svg>
    <G>
        <Defs>{this.pattern}</Defs>
        <Path
        onPress={this.onPress}
        d={this.hexD}
        strokeWidth={this.strokewidth}
        {...this.dasharray}
        stroke={
          'black'
        }
        fill={`url(#bg${this.randomBG})`}
      />
    </G>
</Svg>
```
```
pattern = (
    <Pattern id={`url(#bg${this.randomBG})`} x={0} y={0} width={1} height={1}>
      <Rect
        x={0}
        y={0}
        width={this.width}
        height={this.fullH}
        stroke={this.arrayBackground[0]}
        fill={this.arrayBackground[0]}
      />
      <Rect
            x={this.width / 2}
            y={0}
            width={this.width}
            height={this.fullH}
            stroke={this.arrayBackground[1]}
            fill={this.arrayBackground[1]}
          />
    </Pattern>
  )
```

**Comment by msand** [comment]
Try clearing caches, relinking the library and make a clean build.

**Comment by TheSoma300** [comment]
Can we please reopen this issue as I am experiencing infuriating amounts of problem trying to add images for backgrounds for slices in a pie chart. tried clearing caches, relinking nothing worked.

**Comment by msand** [comment]
Why open an issue about the pattern element if you have problems with the image element?

**Comment by TheSoma300** [comment]
It's not the Image element. Just having an empty or with a standard triangle Path within the <Patter> tag causes error:

'''
        <Svg.Defs>
                <Svg.Pattern
                    id="TrianglePattern"
                    patternUnits="userSpaceOnUse"
                    x="0"
                    y="0"
                    width="100"
                    height="100"
                    viewBox="0 0 10 10"
                  >
                           

<Svg.Path d="M 0 0 L 7 0 L 3.5 7 z" fill="red" stroke="blue" />
                  </Svg.Pattern>
       </Svg.Defs>
'''
<img width="499" alt="screenshot 2019-03-04 at 15 21 51" src="https://user-images.githubusercontent.com/32512129/53742801-665c0f00-3e91-11e9-94ba-1c5900425c3f.png">

**Comment by msand** [comment]
Can you provide a complete reproduction?
