### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager

### ISSUE THREAD

**Issue by brendonhc** [react-native-community/react-native-svg#834]
**Project:**
```
    "d3-shape": "^1.2.2",
    "fbjs": "^1.0.0",
    "native-base": "^2.8.1",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-circular-progress": "^1.0.1",
    "react-native-firebase": "^5.0.0",
    "react-native-svg": "^8.0.8",
    "react-native-svg-charts": "^5.2.0",
    "react-navigation": "^2.18.2"
```

**Printscreen:**

![image](https://user-images.githubusercontent.com/25843486/47887793-03ddfe00-de20-11e8-84d4-a5f46ec734b0.png)

**Error details:**

> Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager.
> 
> This error is located at:
>     in RNSVGPath (at Path.js:17)
>     in Path (at animated-path.js:72)
>     in AnimatedPath (at progress-circle.js:108)
>     in RNSVGGroup (at G.js:23)
>     in G (at progress-circle.js:94)
>     in RNSVGGroup (at G.js:23)
>     in G (at Svg.js:109)
>     in RNSVGSvgView (at Svg.js:90)
>     in Svg (at progress-circle.js:92)
>     in RCTView (at View.js:44)
>     in ProgressCircle (at Main.js:61)
>     in RCTView (at View.js:44)
>     in Card (at connectStyle.js:384)
>     in Styled(Card) (at Main.js:48)
>     in RCTView (at View.js:44)
>     in AnimatedComponent (at DeckSwiper.js:300)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in DeckSwiper (at connectStyle.js:384)
>     in Styled(DeckSwiper) (at Main.js:45)
>     in RCTView (at View.js:44)
>     in Form (at connectStyle.js:384)
>     in Styled(Form) (at Main.js:43)
>     in RCTView (at View.js:44)
>     in Container (at connectStyle.js:384)
>     in Styled(Container) (at Main.js:40)
>     in Main (at SceneView.js:9)
>     in SceneView (at StackViewLayout.js:478)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in AnimatedComponent (at screens.native.js:58)
>     in Screen (at StackViewCard.js:42)
>     in Card (at createPointerEventsContainer.js:26)
>     in Container (at StackViewLayout.js:507)
>     in RCTView (at View.js:44)
>     in ScreenContainer (at StackViewLayout.js:401)
>     in RCTView (at View.js:44)
>     in StackViewLayout (at withOrientation.js:30)
>     in withOrientation (at StackView.js:49)
>     in RCTView (at View.js:44)
>     in Transitioner (at StackView.js:19)
>     in StackView (at createNavigator.js:57)
>     in Navigator (at createKeyboardAwareNavigator.js:11)
>     in KeyboardAwareNavigator (at createNavigationContainer.js:376)
>     in NavigationContainer (at SceneView.js:9)
>     in SceneView (at SwitchView.js:12)
>     in SwitchView (at createNavigator.js:57)
>     in Navigator (at createNavigationContainer.js:376)
>     in NavigationContainer (at app/index.js:22)
>     in RCTView (at View.js:44)
>     in App (at renderApplication.js:34)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in AppContainer (at renderApplication.js:33)
> 
> This error is located at:
>     in NavigationContainer (at SceneView.js:9)
>     in SceneView (at SwitchView.js:12)
>     in SwitchView (at createNavigator.js:57)
>     in Navigator (at createNavigationContainer.js:376)
>     in NavigationContainer (at app/index.js:22)
>     in RCTView (at View.js:44)
>     in App (at renderApplication.js:34)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in AppContainer (at renderApplication.js:33)
> 
> This error is located at:
>     in NavigationContainer (at app/index.js:22)
>     in RCTView (at View.js:44)
>     in App (at renderApplication.js:34)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in AppContainer (at renderApplication.js:33)
> getNativeComponentAttributes
>     getNativeComponentAttributes.js:29:4
> <unknown>
>     requireNativeComponent.js:26:33
> get
>     ReactNativeViewConfigRegistry.js:104:25
> createInstance
>     ReactNativeRenderer-dev.js:4019:53
> completeWork
>     ReactNativeRenderer-dev.js:12051:12
> completeUnitOfWork
>     ReactNativeRenderer-dev.js:14179:10
> performUnitOfWork
>     ReactNativeRenderer-dev.js:14383:30
> workLoop
>     ReactNativeRenderer-dev.js:14395:41
> renderRoot
>     ReactNativeRenderer-dev.js:14492:15
> performWorkOnRoot
>     ReactNativeRenderer-dev.js:15450:17
> performWork
>     ReactNativeRenderer-dev.js:15347:24
> performSyncWork
>     ReactNativeRenderer-dev.js:15304:14
> batchedUpdates$1
>     ReactNativeRenderer-dev.js:15572:21
> batchedUpdates
>     ReactNativeRenderer-dev.js:2675:31
> _receiveRootNodeIDEvent
>     ReactNativeRenderer-dev.js:2770:17
> receiveEvent
>     ReactNativeRenderer-dev.js:2790:26
> __callFunction
>     MessageQueue.js:349:47
> <unknown>
>     MessageQueue.js:106:26
> __guard
>     MessageQueue.js:297:10
> callFunctionReturnFlushedQueue
>     MessageQueue.js:105:17
>

**Comment by brendonhc** [comment]
Comment on closing: I linked the dependency as requested in README.md and recompiled the application and the error stopped happening.

**Comment by barjas** [comment]
react-native link is missing the last step. it is not adding "new SvgPackage()"

Open up `android/app/src/main/java/[...]/MainApplication.java
Add new SvgPackage() to the list returned by the getPackages() method. Add a comma to the previous item if there's already something there.

this is a bug and need to be fixed.

**Comment by aravind1078** [comment]
my MainApplication.java has the line new SvgPackage() but still getting the same error

**Comment by msand** [comment]
@aravind1078 Are you getting the error on iOS or Android? Can you make a reproduction?

**Comment by aravind1078** [comment]
@msand  on Android

**Comment by serdarosmanonur** [comment]
> my MainApplication.java has the line new SvgPackage() but still getting the same error

same here

**Comment by Abhi-Tech9** [comment]
> > my MainApplication.java has the line new SvgPackage() but still getting the same error
> 
> same here

Did you got solution for this?

**Comment by dayaki** [comment]
Thanks @creative-git I got it working by adding new SvgPackage()

**Comment by Abhi-Tech9** [comment]
I got it working by manually performing linking step for iOS

**Comment by okechukwu0127** [comment]
I solved the issue on mine by adding 
packages.add(new SvgPackage());

TO => ...android\app\src\main\java\com\ramesh2\MainApplication.java
react-native version: 0.60.0

![image](https://user-images.githubusercontent.com/23473673/61746587-f1cc3300-ad93-11e9-9766-440fc92d8305.png)

**Comment by nperon** [comment]
Getting the same error after updating to react-native 0.60.4 while everything was fine with version 0.59.10. I haven't found any solution to it yet.

**Comment by lucasousi** [comment]
Getting the same error... packages.add(New SvgPackage()) don't work;

**Comment by okechukwu0127** [comment]
I guess I forgot to add the version of react-native-svg that I installed.

Before installation kindly go through the version list and which react-native versions they
Can be compatible with.

I installed mine using this command.

npm install react-native-svg@9
Which is compatible with my react native v 0.60

Hope this solves your problems.

**Comment by DrobyshevAlex** [comment]
"react-native": "0.60.4",
"react-native-svg": "^9.6.2",

not working on android

**Comment by nguyenduy2392** [comment]
> I solved the issue on mine by adding
> packages.add(new SvgPackage());
> 
> TO => ...android\app\src\main\java\com\ramesh2\MainApplication.java
> react-native version: 0.60.0
> 
> ![image](https://user-images.githubusercontent.com/23473673/61746587-f1cc3300-ad93-11e9-9766-440fc92d8305.png)

i thing packages added to nodemodule by child package added on package.json need use packges.add(new ...);
thanks you

**Comment by theromie** [comment]
Any one solved this issue
"react-native-svg": "^9.13.3",
"react-native": "^0.61.5",

**Comment by efstathiosntonas** [comment]
same here with the exact same packages as @theromie

**Comment by theromie** [comment]
Fixed issue by adding in MainApplicatio.java file:
```
import com.horcrux.svg.SvgPackage;
return Arrays.<ReactPackage>asList(
      new SvgPackage()
      // eg. new VectorIconsPackage()                
);
```

**Comment by NaveenJamdagani** [comment]
1.Install react-native-svg and react-native-svg-transformer.
2.Uninstall your app from mobile.
3.react-native run-android.
4.yarn start
If linking required then react-native link react-native-svg.
Then again follow step 2 to 4.

**Comment by dennis-bingham-dev** [comment]
If running this on iOS

Check your Podfile and Pods directory, my pods weren't installing after doing an npm install. 

The following steps fixed it for me:
1. cd into ios directory in your application and run `pod install`
2. cd back to root of your app
3. react-native run-ios

This fixed the problem for me.

**Comment by sousadgaspar** [comment]
> 1.Install react-native-svg and react-native-svg-transformer.
> 2.Uninstall your app from mobile.
> 3.react-native run-android.
> 4.yarn start
> If linking required then react-native link react-native-svg.
> Then again follow step 2 to 4.

Thank you very much for your help. It worked for me. 
First I uninstalled the app from the phone, then I Installed react-native-svg only and them restarted the simulator (iOS)

**Comment by Kiranlanke** [comment]
Instead of adding packages.add(new SvgPackage());

Tried as mentione here [](https://stackoverflow.com/a/47716910/3142611)

> npm install react-native-svg --save //(again)
> react-native link react-native-svg //(again)
> rm -rf node_modules/ && yarn cache clean && yarn
> 
> Then in another terminal/restart terminal
> 
> yarn android

Finally got expected output

**Comment by kylemccurley** [comment]
## Android Fix

1. Uninstall App
2. Remove node_modules
3. Rebuild App from Android Studio
4. Reset Metro Server

**Comment by mohdmusthafa** [comment]
> 1.Install react-native-svg and react-native-svg-transformer.
> 2.Uninstall your app from mobile.
> 3.react-native run-android.
> 4.yarn start
> If linking required then react-native link react-native-svg.
> Then again follow step 2 to 4.

This works 🥳 🥳

**Comment by jamekjamek** [comment]
> 1.Install react-native-svg and react-native-svg-transformer.
> 2.Uninstall your app from mobile.
> 3.react-native run-android.
> 4.yarn start
> If linking required then react-native link react-native-svg.
> Then again follow step 2 to 4.

This works, thanks man

**Comment by arturmusin** [comment]
Have similar problem on my Windows machine. Gettings "requireNativeComponent: RNSVGPath was not found in the UIManager.
Here are the versions of the packages I'm using:

"react-native-svg": "^12.1.1",
"react-native-svg-transformer": "^0.14.3",

Installing/Uninstalling/Linking doesn't help at all. Does anyone have experience with running react-native on Windows machine?

**Comment by harnie2275** [comment]
> react-native link is missing the last step. it is not adding "new SvgPackage()"
> 
> Open up `android/app/src/main/java/[...]/MainApplication.java Add new SvgPackage() to the list returned by the getPackages() method. Add a comma to the previous item if there's already something there.
> 
> this is a bug and need to be fixed.

Not working for me

**Comment by harnie2275** [comment]
> ## Android Fix
> 1. Uninstall App
> 2. Remove node_modules
> 3. Rebuild App from Android Studio
> 4. Reset Metro Server

This fixed me mine

**Comment by lucassantosdasilva1** [comment]
sometimes it error show, because we don't type yarn android only yarn start. Everytime when install a new natives libs we need type yarn android.

**Comment by omerg** [comment]
In my case, a dependency had an unmet dependency version of "react-native-vector-icons": "^7.0.0", whereas the parent app had "^9.0.0",. Setting parent version to "^7.0.0" solved it for me.

**Comment by Wipster** [comment]
I've had the same error using expo where react-native-svg was just a dependency of another package I'm using. I could fix the error by running `expo install react-native-svg` although I'm not using it directly.

**Comment by pSnehanshu** [comment]
For expo users, just rebuild using `expo build` or `eas build` and then reinstall the app on your phone after installing `react-native-svg`.

**Comment by CurpraCode** [comment]
I tried to rebuild but still got the same error, I belive there is a bug in the "react-native-svg": "^13.4.0", I downgraded to  "react-native-svg": "12.3.0", and this works for me.

**Comment by lePoissonier** [comment]
> react-native-svg": "12.3.0"

how do i do to install this version specifically ?

**Comment by efstathiosntonas** [comment]
@lePoissonier replace react-native-svg on your package.json with `react-native-svg": "12.3.0"` and run yarn/npm install then `cd ios` and `pod install`.

**Comment by lePoissonier** [comment]
> @lePoissonier replace react-native-svg on your package.json with `react-native-svg": "12.3.0"` and run yarn/npm install then `cd ios` and `pod install`.

can you tell  me what 'cd ios' is supposed to do ? (i did but it said the ios path doesn't exist)
and also what pod install does real quick ?

**Comment by CzepiM200** [comment]
I'm using expo dev-client so in my case, this approach worked:

1. Install  
"react-native-svg": "13.4.0",
"react-native-svg-transformer": "^1.0.0",

2. Build a new "expo go" app with eas
eas build --profile development --platform android
(ios should also work)

3. Install the new app
And it work :D

**Comment by kdenz** [comment]
I have RN 0.70.6, 13.x works on iOS but breaks on Android. Downgrading `react-native-svg` to `12.4.4` works for me

**Comment by PTBYSR** [comment]
> 1.Install react-native-svg and react-native-svg-transformer. 2.Uninstall your app from mobile. 3.react-native run-android. 4.yarn start If linking required then react-native link react-native-svg. Then again follow step 2 to 4.

What if you're using Expo to run your project?

**Comment by Revolt9k** [comment]
`expo prebuild` did nothing but 
**`npx react-native run-ios`** helped me

**Comment by jacesimons14** [comment]
I think the answers on here solve the issue for everyone but just in case somebody needs this:
For phosphor icons with the phosphor-react-native package,
I `uninstalled the app` from my phone (android 13 pixel 7 pro) like I would uninstall any regular app,
then I ran `npm start`, which threw an error about port 8081 alr being in use, but that is fine, then I did `npm run android` and when it reinstalled the app it worked first try.
I did _not_ need to mess around with the Application java files in the android dir or anything, all I did to make it work was to do what I just said 👍

**Comment by Aaslan01** [comment]
Soultion: Uninstalled the App and  kill metro too. Create a new build, worked for me.

**Comment by ericwilsontruerx** [comment]
> I think the answers on here solve the issue for everyone but just in case somebody needs this: For phosphor icons with the phosphor-react-native package, I `uninstalled the app` from my phone (android 13 pixel 7 pro) like I would uninstall any regular app, then I ran `npm start`, which threw an error about port 8081 alr being in use, but that is fine, then I did `npm run android` and when it reinstalled the app it worked first try. I did _not_ need to mess around with the Application java files in the android dir or anything, all I did to make it work was to do what I just said 👍

Thank you for this! After trying everything including deleting my ios folder and rebuilding multiple times, this finally did the trick. I had to delete the app off of my emulator and then rebuild my project. The fresh installation worked!

**Comment by AbhieShinde** [comment]
[lucide-icons with tamaui](https://tamagui.dev/ui/lucide-icons) was causing this error, and I switched to `@expo/vector-icons` which resolved this issue.
