### ISSUE TITLE
Touch events do not get fired on specific devices

### ISSUE THREAD

**Issue by andreaskarantzas** [react-native-community/react-native-svg#836]
The above issue can be reproduced with the TouchEvents view from the library's example. It works fine on the simulator and specific devices like iPhone 6, iPad or the emulator but not with iPhone X or iPhone 7 Plus. The touch events in the 1st & 3rd part of the "TouchEvents" section of the example, cause the alerts to appear on some devices but not others. The same is true for the "hover the svg path" that registers every time in some devices and in the some others it registers once or not at all. All of the devices run on iOS 12

**Comment by maxkomarychev** [comment]
seems to be a duplicate of #592

**Comment by andreaskarantzas** [comment]
That is correct.
