### ISSUE TITLE
Unable to resolve module '../lib/props'

### ISSUE THREAD

**Issue by pavelkeyzik** [react-native-community/react-native-svg#839]
Hey guys. I have some problem with Rect element.

`error: bundling failed: Error: Unable to resolve module "../lib/props" from "\node_modules\react-native-svg\elements\Rect.js": The module "../lib/props" could not be found from "\node_modules\react-native-svg\elements\Rect.js".`

OS: Windows 10
React-Native-Svg: 8.0.8
React-Native: 0.57.1
React: 16.5.1

**Comment by msand** [comment]
Seems like your node_modules folder is corrupted, try deleting it and `npm i` again

**Comment by pavelkeyzik** [comment]
> Seems like your node_modules folder is corrupted, try deleting it and `npm i` again

I tried this and also I cleared cache but it doesn't help me. After all steps, I get a problem like #814.

**Comment by pavelkeyzik** [comment]
> Have you tried React 16.6.0?

Do you think it will help me? I think the problem with installation because I can't find props file in the lib.

**Comment by phenixrizen** [comment]
I'm having the same issue with:

OS: Ubuntu 18.04.1 LTS
React-Native-Svg: 8.0.8
React-Native: 0.57.5
React: 16.6.3

I've tried clearing the npm cache and removing the node_modules directory and reinstall the modules and I still get this error

**Comment by DavidKk** [comment]
I'm having the same issue with:

- React-Native-Svg: 8.0.8
- React-Native: 0.57.1
- React: 16.5.0

**Comment by DavidKk** [comment]
> I'm having the same issue with:
> 
> * React-Native-Svg: 8.0.8
> * React-Native: 0.57.1
> * React: 16.5.0

```
$ watchman watch-del-all
$ rm -fr $TMPDIR/react-*
$ npm start -- --reset-cache
```
it works

**Comment by msand** [comment]
Seems like local caching issues. Closing...

**Comment by marcorm** [comment]
Same issue with:

- react-native-svg: 9.3.3
- react: 16.8.3
- react-native: 0.59.0

Cleaning cache doesn't help...

**Comment by msand** [comment]
@marcorm I have it working fine in a clean react-native init at least, can you make a repro?

**Comment by martincarrera** [comment]
Had the same issue, fixed by:
```
react-native unlink react-native-svg && react-native link react-native-svg
```

**Comment by Rutheniceye92** [comment]
Yup resetting the cache worked

**Comment by parth-koshta** [comment]
I got the same issue today and  **npm start -- --reset-cache**  worked.
Thanks :)
