### ISSUE TITLE
TS error: opacity does not exist on component type

### ISSUE THREAD

**Issue by winghouchan** [react-native-community/react-native-svg#842]
The TS compiler throws an error saying the property opacity does not exist on component types. Below is a reduced test case.

```
import React from 'react'
import Svg, { Circle } from 'react-native-svg'

const SvgComponent = props => (
  <Svg height={200} width={200} {...props}>
    <Circle cx="50%" cy="50%" r={100} opacity={0.25} />
  </Svg>
)

export default SvgComponent
```

produces

```
TS2339: Property 'opacity' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<CircleProps, any, any>> & Readonly<{ children?: ReactNode; }> & Readonly<CircleProps>'.
```

You can reproduce this on other components such as `G`.

I believe this is a bug because `opacity` is applicable to container and graphic elements (see quote from spec below, emphasis mine) of which `circle` is a graphic element.

> ‘opacity’
>  - Value:  `<opacity-value>` | inherit
>  - Initial:  1
>  - **Applies to:  [container elements](https://www.w3.org/TR/SVG11/intro.html#TermContainerElement) (except [‘mask’](https://www.w3.org/TR/SVG11/masking.html#MaskElement)) and [graphics elements](https://www.w3.org/TR/SVG11/intro.html#TermGraphicsElement)**
>  - Inherited:  no
>  - Percentages:  N/A
>  - Media:  visual
>  - Animatable:  yes

– https://www.w3.org/TR/SVG11/masking.html#OpacityProperty

**Comment by msand** [comment]
You can use fillOpacity and strokeOpacity for now. Or fix the type definition. Could add it to: https://github.com/react-native-community/react-native-svg/blob/72a53f373028e4c1d89286c1e6c93c7a229ebc90/index.d.ts#L158
Except that it shouldn't apply to the mask element.

**Comment by winghouchan** [comment]
> You can use fillOpacity and strokeOpacity for now.

This might not be an option in the case where SVG components are generated. For my case I'm using [SVGR](https://github.com/smooth-code/svgr) which uses [SVGO](https://github.com/svg/svgo) to optimise my SVGs.

> Or fix the type definition.

As we can't add `opacity` to `CommonPathProps` we could add it to individual element interfaces. Although it's not ideal because of duplication it would solve this issue in the meantime.

**Comment by winghouchan** [comment]
> As we can't add `opacity` to `CommonPathProps` we could add it to individual element interfaces. Although it's not ideal because of duplication it would solve this issue in the meantime.

I've opened #847 with this fix so you can review it.

**Comment by winghouchan** [comment]
> As we can't add `opacity` to `CommonPathProps` we could add it to individual element interfaces. Although it's not ideal because of duplication it would solve this issue in the meantime.

@msand: I've opened #847 with this fix so you can review it.
