### ISSUE TITLE
change "compile" to "implementation"

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/react-native-svg#846]
When link library to project using `react-native link`, in build.gradle file it adds `compile project(':react-native-svg')` it's better to change linker to add `implementation project(':react-native-svg')`

**Comment by msand** [comment]
This issue probably belongs in the react-native repo, but the issue has already been fixed and the patch will be included in react-native v0.58:
https://github.com/facebook/react-native/commit/4dfdec9b28074b311ffd75084d9d2a3cbd41a800#diff-409fd490b233c234fcd355cf00a9a0dc
You can ask them to cherry pick it for the next 0.57 release if they're planning any more of those.
