### ISSUE TITLE
Crash app only Release

### ISSUE THREAD

**Issue by leo-tavares** [react-native-community/react-native-svg#856]
### Description

The app work fine in debug-mode, but i generate a release apk and now work. O apk crash logo quando inicia

### problem reproduction

1. Create new react-native project ( with init) 
1. Follow setp by setp [react-native-svg](https://github.com/react-native-community/react-native-svg#automatic)
1. follow the [generate-apk](https://facebook.github.io/react-native/docs/signed-apk-android) and use `.\gradlew.bat assemblerelease`
1. install the apk with `react-native run-android --variant=release`
1. run the app

### Issues I've already looked at
https://github.com/react-native-community/react-native-svg/issues/784
https://github.com/react-native-community/react-native-svg/issues/481

### react-native info
`
Environment:
  OS: Windows 10
  Node: 10.13.0
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
`

**Comment by msand** [comment]
Please provide a full replication. Closing until then.

**Comment by mr-savari** [comment]
Try adding -keep public class com.horcrux.svg.** {*;} 
to proguard-rules.pro file

**Comment by mr-savari** [comment]
Try adding `-keep public class com.horcrux.svg.** {*;}` in proguard-rules.pro file

**Comment by Samykills** [comment]
Can we add this to the readme?

**Comment by msand** [comment]
Wanna make a pr?

**Comment by Samykills** [comment]
cool will do :D

**Comment by medonomator** [comment]
> Try adding `-keep public class com.horcrux.svg.** {*;}` in proguard-rules.pro file

Thanks. This is working!

**Comment by MarquisAlexander** [comment]
> Try adding `-keep public class com.horcrux.svg.** {*;}` in proguard-rules.pro file

Thanks man, this working here :)

**Comment by nguyenvantruong17** [comment]
https://github.com/react-native-svg/react-native-svg/issues/856#issuecomment-482713189
@mrsavari Thanks for your information. This works for me.

**Comment by khanhdevvn** [comment]
> Try adding `-keep public class com.horcrux.svg.** {*;}` in proguard-rules.pro file

Could you help me How to fix on iOS
