### ISSUE TITLE
Text wrapping within a bounding box or `Rect`

### ISSUE THREAD

**Issue by Taimoormk** [react-native-community/react-native-svg#862]
I understand SVG's don't natively support text wrapping but would like to see if there is any support provided within this library, as I have created a small piece of code to demonstrate the issue I am getting.

Ideally, I would like my text to wrap naturally within the bounding box like we have `p` tag within a `div` container.
Following is the React Native code I am using;

```
          <Svg height={height * 0.5} width={width} viewBox={`0 0 ${height * 0.5} ${width}`}>
            <Rect x={0} y={0} rx={10} ry={10} width={width} fill="#4682b4" stroke="black" stroke-width="5" opacity=".5" height={49.5}></Rect>
            <Text x={0} y={0} dx={20} dy={20} fontSize={14} fontFamily="arial" fill="red">
              {scorpioText}
            </Text>
          </Svg>
```

![simulator screen shot - iphone 6s - 2018-12-02 at 13 12 15](https://user-images.githubusercontent.com/27800340/49337451-8252d900-f634-11e8-81eb-969067aff4dc.png)

**Comment by msand** [comment]
I started work on the text layout algoritm from svg 2.0 long ago, but never got around to finishing it. If you want multiline text, you either have to do it manually using text/tspan elements and the x and y attributes, or, wrap the svg in a view, and position react native text elements absolutely positioned where you want them.
Or, help out implementing the layout: https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/TextLayoutAlgorithm.java

**Comment by msand** [comment]
You can also use onLayout or UIManager.measure to get the width and height of the text.

**Comment by msand** [comment]
I've implemented support for inlineSize now: https://github.com/react-native-community/react-native-svg/commit/44b700eed808e9364e4248c983fb4297c5d8668f

**Comment by Taylor123** [comment]
@msand whats the proper usage for `inlineSize`? I attempted to set it to the width of my SVG container, but it doesn't seem to auto wrap the text.

version: `9.6.4`
RN version: `0.59.4`

**Comment by donysukardi** [comment]
@msand anywhere we can find documentation on how to use `inlineSize` prop?

**Comment by msand** [comment]
Check e.g. here: https://github.com/react-native-community/react-native-svg/issues/439#issuecomment-524983074
https://github.com/react-native-community/react-native-svg/issues/1051#issuecomment-518292867

**Comment by msand** [comment]
Also https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size
https://www.w3.org/TR/SVG2/text.html#InlineSize
