### ISSUE TITLE
Unnecessary retention and copying of CGPath, leading to memory leak. iOs

### ISSUE THREAD

**Issue by stephenkopylov** [react-native-community/react-native-svg#863]
Hello, guys, and thank you for your amazing library!

So, I found this construction in `RNSVGRenderable.m` that leads to memory leak:

```objective-c
    if (!self.path) {
        self.path = CGPathRetain(CFAutorelease(CGPathCreateCopy([self getPath:context])));
        [self setHitArea:self.path];
    }
```
![screenshot 2018-12-02 at 2 51 39 pm](https://user-images.githubusercontent.com/5202281/49339967-2bec9700-f642-11e8-81db-7a8089beb012.png)

Why do we need extra call of CGPathCreateCopy, CGPathRetain and CFAutorelease, when we already use CGPathRelease later?
Actually, it leaves original CGPath (returned from [self getPath:context]) unreleased forever.

To fix this we can use simplified construction

```objective-c
    if (!self.path) {
        self.path =[self getPath:context];
        [self setHitArea:self.path];
    }
```

**Comment by stephenkopylov** [comment]
The problem is more complicated than I thought, so am closing the PR

**Comment by msand** [comment]
@stephenkopylov What was the complication you found? Not sure I remember all the related issues to this. Think there's something with press/gesture handling related to it.

**Comment by msand** [comment]
Is this even causing any memory leaks? At least when I animate svg content the memory seems to stay flat, similarly if a svg element is rendered and removed based on a flag. Can probably close this, unless an actual memory leak as been found. Please comment if that is the case.

**Comment by stephenkopylov** [comment]
@msand sorry, don't have any more time to investigate the problem =(
Maybe later I'll dig into it again

**Comment by msand** [comment]
At least all leaks I've found are fixed at this point. If you're able to find any others, please open a new issue. Thanks for reporting!
