### ISSUE TITLE
Could not find httpcore.jar (org.apache.httpcomponents:httpcore:4.4.5).

### ISSUE THREAD

**Issue by zim-lee** [react-native-community/react-native-svg#874]
react-native:0.57.7
react-native-svg:8.0.9-8.0.10

I change react-native-svg to 8.0.8, it works fine.

**Comment by msand** [comment]
Strange, we don't depend on that library, and can't see it in any of my android projects. I guess this is a fluke and related to something else. Or can you provide a git repo as reproduction? @zim-lee

**Comment by zim-lee** [comment]
That's weird. I'll check my code again. Thx! @msand
