### ISSUE TITLE
[Android] package com.facebook.infer.annotation does not exist

### ISSUE THREAD

**Issue by agates4** [react-native-community/react-native-svg#876]
Versions

```
    "expo": "^31.0.6",
    "expokit": "31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-svg": "^8.0.10"
```

Android build error

```
error: package com.facebook.infer.annotation does not exist
```

File

```
app/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RenderableViewManager.java
```

On line 16 at the import 
```
import com.facebook.infer.annotation.Assertions;
```

What might be causing this issue?

**Comment by agates4** [comment]
I added 
```
dependencies {
    //noinspection GradleDynamicVersion
    implementation 'com.facebook.react:react-native:+'

    // this dependency was added and resolved this error
    implementation group: 'com.facebook.infer.annotation', name: 'infer-annotation', version: '0.11.2'
}
```

to 
```
node_modules/react-native-svg/android/build.gradle
```

However, this came up with another error: apparently, this SVG library conflicts with the ExpoKit library. 

To anyone reading this that was trying to implement the react-native-qrcode-svg in their ejected android app, you do not need react-native-svg. ExpoKit already has an SVG library. All you have to do is install react-native-qrcode-svg.

**Comment by pckz** [comment]
@agates4 thanks, worked for me, I could generate the APK with no errors.

The problem was when I tried the APK in a real device. I got:

> Uncaught Error native module com.horcrux.svg.svgviewmodule tried to override versioned.host.exp.exponent.modules.api.components.svg.svgviewmodule for module name rnsvgsvgviewmanager. Check the GetPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention,
