### ISSUE TITLE
Nested svg content is rendered twice

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/react-native-svg#880]
This is a wired and annoying bug. When using a svg nested into another svg component, the content of nested svg has been drawn twice for no reason. The more strange thing with it is that one of them has drawn without respect to its parent properties (like width, height, x, y, ...).
My code is very complex, so I provide a simple code to reproduce the problem. 

```
<Svg width={100} height={100} viewBox={'0 0 100 100'}>
    <G key={'item touch zone'} onPress={() => {}} x={20} y={10}>
        <Svg
             key="item"
             width={"100%"}
             height={"100%"}
        >
             <Circle key="circle" cx="7" cy="10" r="8" fill={'green'}/>
         </Svg>
     </G>
</Svg>
```

here is the result, the right circle is what I really draw, the left one is drawn by itself!!!

![screenshot_1545040931](https://user-images.githubusercontent.com/13766432/50080117-9edc3d00-0200-11e9-8402-465329ff9069.png)

I'm using version 8.0.10 (the latest one so far)

**Comment by ReggaePanda** [comment]
i have the same issue. 😳
but it is Android only. 
on iOS it works fine!

**Comment by msand** [comment]
I'm unable to replicate this with v9 at least. Could you make a cloneable git repo (with v9) where i can just install and run to see the issue.

**Comment by msand** [comment]
@SaeedZhiany @ReggaePanda Think I managed to replicate and fix this. Can you test with v9.2.3?

**Comment by react-cat** [comment]
@msand Had a similar problem, I have nested circles and in case I render more than one instance of my class with svg, some additional circles appeared. 
```
<SvgTradeIcon diameter={25} connotation={"negative"} direction={"up"} />
<SvgTradeIcon diameter={60} connotation={"negative"} direction={"up"} />
<SvgTradeIcon diameter={80} connotation={"negative"} direction={"up"} />
```
![cryptuoso](https://user-images.githubusercontent.com/43940398/64070542-35f00480-cc6b-11e9-88a7-67328605ac67.png)

A solution was to add random Ids generated by simple Math.random() to Defs:
```
<Svg height={diameter} width={diameter}>
    <Defs>
        <RadialGradient
            id={`radialGrad${randomId}`}
            ...
        >
           ...
        </RadialGradient>
        <LinearGradient id={`linearGrad${randomId}`} x1="0" y1="0" x2="0" y2="0.8">
            ...
        </LinearGradient>
    </Defs>
    <Circle ... fill={`url(#radialGrad${randomId})`}/>
    <Circle ... fill={`url(#linearGrad${randomId})`} />
</Svg>
```
![cryptuoso (1)](https://user-images.githubusercontent.com/43940398/64070548-7baccd00-cc6b-11e9-9794-a96c95064f45.png)

Hope that it would help someone with similar situation.

**Comment by SaeedZhiany** [comment]
@react-cat, thank you
Which version of react-native-svg you are using?

**Comment by OlegBrazhnichenko** [comment]
@SaeedZhiany 9.8.3 
Here is my full dependencies list : 
```
"dependencies": {
    "expo": "34.0.1",
    "react": "16.8.3",
    "react-dom": "16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-svg": "9.8.3",
    "react-native-web": "0.11.4",
    "victory": "33.0.5",
    "victory-native": "33.0.0"
  },
  "devDependencies": {
    "babel-preset-expo": "6.0.0"
  },
```

**Comment by react-cat** [comment]
@SaeedZhiany 9.8.3 
Here is my full dependencies list : 
```
"dependencies": {
    "expo": "34.0.1",
    "react": "16.8.3",
    "react-dom": "16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-svg": "9.8.3",
    "react-native-web": "0.11.4",
    "victory": "33.0.5",
    "victory-native": "33.0.0"
  },
  "devDependencies": {
    "babel-preset-expo": "6.0.0"
  },
```
