### ISSUE TITLE
Nested react native component always drawn from (0,0) coordinate

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/react-native-svg#881]
When using a react native component inside Svg, it always drawn from the root Svg (0,0) coordinate and none of `G` or `Svg` properties does not affect on it.

here is a code to reproduce the problem.

```
<Svg width={100} height={100} viewBox={'0 0 100 100'}>
    <G key={'item touch zone'} onPress={() => {}} x={20} y={10}>
        <Svg
            key="item"
            width={"100%"}
            height={"100%"}
            //viewBox={`0 0 ${0} 14`}
            //preserveAspectRatio="xMidYMid meet"
        >
            <Text>{"test text"}</Text> <----- this is react native Text component, not this library
        </Svg>
    </G>
</Svg>
```

here is the result:

![screenshot_1545041926](https://user-images.githubusercontent.com/13766432/50081022-aac8fe80-0202-11e9-8ac8-8dd7eb831fb9.png)

as you see the text ignore its `G` parent's `x` and `y`. (I draw the red rectangle  using windows paint program, it's not part of the original svg, I just wanted to specify the approximate location that the text must be draw)
 
because of the Bidi language rendering problem, I have to use react native `Text` component to render non-english text.

I am using version 8.0.10 (the latest one so far)

**Comment by msand** [comment]
Nesting native components inside Svg hasn't really been specified anywhere yet. foreignObject is probably the thing to implement to make the nested components take the current transform matrix into account. I would just place the native components using position: absolute, and place them outside the  svg root such that the normal react-native layout can do it's thing. Alternatively, use native transform to move it around.

**Comment by msand** [comment]
I think we can close this now as foreignObject has been released.
