### ISSUE TITLE
Upgrading to "^6.0.0", "^7.0.0",  or "^8.0.0" fails

### ISSUE THREAD

**Issue by opolyo01** [react-native-community/react-native-svg#882]
I have been on the version of 5.x, and upgrading to 8 throws an error.  I don't even see url dependency.  Any idea?

warning: the transform cache was reset.
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `url` from `/Users/opolyako/citcode/citadel-react-native-viz/examples/RNVizExample/node_modules/xmlhttprequest/lib/XMLHttpRequest.js`: Module `url` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968

**Comment by msand** [comment]
This is unrelated to this library, if you have a repro, please post it to the issue in the react native repo instead.
