### ISSUE TITLE
react-native-svg feDropShadows support

### ISSUE THREAD

**Issue by oleksandr-dziuban** [react-native-community/react-native-svg#883]
Hello guys, just have one question regarding shadows support in react-native-svg package. Do you know is it possible to implement shadows here? Thank you.

P.S. In WEB SVG structure for drop shadows looks like:

```
<defs>
  <filter>
    <feDropShadow>...</feDropShadow>
  <filter>
<defs>
```

**Comment by msand** [comment]
The filters branch has ios support to some degree already, check this issue: https://github.com/react-native-community/react-native-svg/issues/150
