### ISSUE TITLE
Support vector effect property

### ISSUE THREAD

**Issue by ksesong** [react-native-community/react-native-svg#885]
Is there any plans to support the`non-scaling-stroke` value of `vector-effect` property (as described [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect))?

One solution would be to flatten the transformations (using for example: https://github.com/fontello/svgpath), but I wouldn't be able to animate these transforms without changing the stroke appearance.

**Comment by scottmas** [comment]
@ksesong Could you elaborate on how that would be accomplished by flattening the transformation? I don't need to animate the transform and am interested in finding a workaround.

**Comment by ksesong** [comment]
The path data is updated once you flatten the transformation, so the stroke width does not get impacted by the transformation; instead of having `stroke > transform` which transforms the stroke, you get `transform > stroke` (as the transform is integrated into the path data), so the stroke won't get scaled.

**Comment by scottmas** [comment]
That makes sense. Would you mind doing a pseudo code example though to make sure I'm understanding correctly? Googling "flatten svg transform" doesn't turn up a whole lot that an SVG novice like me can make sense of.

**Comment by scottmas** [comment]
Also, for what it's worth here's a gist to enable the x and y dimensions to scale independently, leaving the stroke width unaffected: https://gist.github.com/scottmas/1f662871ed60043bb14a9af4a3fcd3b0

Basically, it's a node script to convert an svg file like so:
```
<svg width="297" height="239" viewBox="0 0 297 239" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.5 119.5C14.5 84.9822 23.9822 57 58.5 57C93.0178 57 121 84.9822 121 119.5C121 154.018 93.0178 182 58.5 182C23.9822 182 14.5 154.018 14.5 119.5Z" fill="white"/>
</svg>
```
Into a parameterized React Component like so:
```javascript
import React from "react";
import Svg,{ Circle, Ellipse, G, Text, TSpan, TextPath, Path, Polygon, Polyline, Line, Rect, Use, Image, Symbol, Defs, LinearGradient, RadialGradient, Stop, ClipPath, Pattern, Mask } from "react-native-svg";

export function LeftField({xScaleFactor, yScaleFactor}){
  return (
    <Svg width={`${xScaleFactor * 297}`} height={`${yScaleFactor * 239}`} viewBox={`${0 * xScaleFactor} ${0 * yScaleFactor} ${297 * xScaleFactor} ${239 * yScaleFactor}`} fill={`none`} xmlns={`http://www.w3.org/2000/svg`}>
      <Path d={`M${xScaleFactor * 14.5} ${yScaleFactor * 119.5}C${xScaleFactor * 14.5} ${yScaleFactor * 84.9822} ${xScaleFactor * 23.9822} ${yScaleFactor * 57} ${xScaleFactor * 58.5} ${yScaleFactor * 57}C${xScaleFactor * 93.0178} ${yScaleFactor * 57} ${xScaleFactor * 121} ${yScaleFactor * 84.9822} ${xScaleFactor * 121} ${yScaleFactor * 119.5}C${xScaleFactor * 121} ${yScaleFactor * 154.018} ${xScaleFactor * 93.0178} ${yScaleFactor * 182} ${xScaleFactor * 58.5} ${yScaleFactor * 182}C${xScaleFactor * 23.9822} ${yScaleFactor * 182} ${xScaleFactor * 14.5} ${yScaleFactor * 154.018} ${xScaleFactor * 14.5} ${yScaleFactor * 119.5}Z`} fill={`white`}/>
    </Svg>
  )
}
```
It does this by understanding what numeric values are defined along the x axis and which are defined long the y axis and lets you scale them independently. It may be able to get you those animations you want ksesong.

**Comment by msand** [comment]
How about something like this? https://snack.expo.io/@msand/non-scaling-stroke-work-around

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';
const { Path } = Svg;

export function LeftField({ scale = 1, xScaleFactor = scale, yScaleFactor = scale }) {
  return (
    <Svg
      width={xScaleFactor * 297}
      height={yScaleFactor * 239}
      preserveAspectRatio="xMidYMid slice"
      viewBox="0 0 297 239">
      <Path
        d="M14.5 119.5C14.5 84.9822 23.9822 57 58.5 57C93.0178 57 121 84.9822 121 119.5C121 154.018 93.0178 182 58.5 182C23.9822 182 14.5 154.018 14.5 119.5Z"
        fill="white"
        stroke="black"
        strokeWidth={10 / scale}
      />
    </Svg>
  );
}
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <LeftField scale={1} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by scottmas** [comment]
I don't follow you msand. The point is that we don't _want_ to preserve the aspect ratio. We want to stretch the vector in any direction and still preserve the stroke width.

**Comment by msand** [comment]
@scottmas Then how about `preserveAspectRatio="none"`?

**Comment by msand** [comment]
Oh, now I got you, was a bit confused when you weren't even using stroke in your example.

**Comment by scottmas** [comment]
Yeah, sorry about that. I was just trying to not clutter up the issue with an excessively long code snippet. The original SVG looks like so:
![screen shot 2019-02-27 at 10 58 51 am](https://user-images.githubusercontent.com/2257337/53511965-ce1fed80-3a7e-11e9-88f8-19c8a67f6b72.png)

And when stretched looks like so:
![screen shot 2019-02-27 at 10 58 38 am](https://user-images.githubusercontent.com/2257337/53511975-d5df9200-3a7e-11e9-9af3-64c83b62aece.png)

You can see in the stretched example how the stroke widths get distorted as it gets stretched. `vector-effects="non-scaling-stroke"` makes it so that we can stretch the svg without the stroke widths getting affected.

**Comment by scottmas** [comment]
What would be involved in supporting vector-effects? Mostly just configuring and exposing functionality in the underlying mobile platform svg libraries?

**Comment by msand** [comment]
All the logic is in house, we only use what is exposed by the operating systems. I think this would require applying the current transform matrix (CTM) to the path, and applying the inverse to the CTM (to make it the identity transform), before filling and stroking it, and restore the rendering context to the previous state as usual. Not completely sure if this covers all of it, but from at least from thinking about it for a few minutes I haven't come up with anything it wouldn't cover.

**Comment by msand** [comment]
@scottmas Would you be willing to work on this? Are you more familiar with java or objective-c?

**Comment by scottmas** [comment]
I'm probably the last person you'd want working on this. But @miles-canfield, you think you could take a stab at this?

**Comment by scottmas** [comment]
I've never hacked on a RN library with native integration. Any tips and tricks msand?

**Comment by msand** [comment]
I've implemented it for Android here, could you try it out? https://github.com/react-native-community/react-native-svg/commit/ffb04c84143c506a6f5cde8bb97ff9fab09d1595

So, the iOS implementation is missing, and mainly consists of porting the changes from RenderableView.java [android/src/main/java/com/horcrux/svg/RenderableView.java](https://github.com/react-native-community/react-native-svg/commit/ffb04c84143c506a6f5cde8bb97ff9fab09d1595#diff-4514e2800c86c3d034626a608dce25b2)
 to RNSVGRenderable.m [react-native-svg/ios/RNSVGRenderable.m](https://github.com/react-native-community/react-native-svg/blob/ffb04c84143c506a6f5cde8bb97ff9fab09d1595/ios/RNSVGRenderable.m)

And then, exposing the setter for vectorEffects in RNSVGRenderableManager.m [react-native-svg/ios/ViewManagers/RNSVGRenderableManager.m](https://github.com/react-native-community/react-native-svg/blob/ffb04c84143c506a6f5cde8bb97ff9fab09d1595/ios/ViewManagers/RNSVGRenderableManager.m) the same way as in RenderableViewManager.java [android/src/main/java/com/horcrux/svg/RenderableViewManager.java](https://github.com/react-native-community/react-native-svg/commit/ffb04c84143c506a6f5cde8bb97ff9fab09d1595#diff-50f7e7f8735df31a6ac08ae41511a2a6)

**Comment by msand** [comment]
Working on the iOS version requires no changes on your part, if you're already able to open the project in xcode and start it from there. Just make modifications to the obj-c files in the ios folder of react-native-svg, and rebuild to test the changes.

**Comment by msand** [comment]
@scottmas Implemented ios here: https://github.com/react-native-community/react-native-svg/commit/1b050834d5c4a8410054bbdbe18470c561325349
Can you try the vector-effect branch?

**Comment by msand** [comment]
Tested using this:
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Svg, Rect, G, Line } from 'react-native-svg';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg width="300" height="200" viewBox="0 0 600 400">
          <Rect
            x="1"
            y="1"
            width="598"
            height="398"
            fill="none"
            stroke="black"
          />

          <G transform="scale(9,1)">
            <Line
              stroke="black"
              strokeWidth="5"
              x1="10"
              y1="50"
              x2="10"
              y2="350"
            />
            <Line
              vectorEffect="non-scaling-stroke"
              stroke="black"
              strokeWidth="5"
              x1="32"
              y1="50"
              x2="32"
              y2="350"
            />
            <Line
              vectorEffect="none"
              stroke="black"
              strokeWidth="5"
              x1="55"
              y1="50"
              x2="55"
              y2="350"
            />
          </G>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
});
```

ios: 
![simulator screen shot - iphone xr - 2019-02-27 at 22 11 26](https://user-images.githubusercontent.com/1131362/53519775-b70fe880-3adc-11e9-8eb4-a0923c1e1d5d.png)

android: 
![screenshot_1551298348](https://user-images.githubusercontent.com/1131362/53519817-d27af380-3adc-11e9-8bf5-d26c2a9ed4a1.png)

**Comment by msand** [comment]
Oh, forgot to add the header file for ios: https://github.com/react-native-community/react-native-svg/commit/014e2375fa4b73feb98cea3a4d69700c4df32514

**Comment by scottmas** [comment]
Wowz, you are one quick wizard of code msand. Me and Miles didn't even have the chance to look at it. I got your example working perfectly on ios and Android by just pointing my package.json to the vector-effect git branch. If you feel good about this branch not causing any regressions or other effects, I'd say it looks good to merge.

I even checked that that when scaling the svg by setting the top level SVG to  `preserveAspectRatio="none"` and then changing its height (or width) also respects the vector-effect property when scaling. So nice job.

**Comment by scottmas** [comment]
Oh also, we should probably update the typings. 
```
export interface VectorEffectProps {
  vectorEffect?: 'none' | 'non-scaling-stroke',
}
```

```
export interface CommonPathProps extends FillProps, StrokeProps, ClipProps, TransformProps, VectorEffectProps, ResponderProps, TouchableProps, DefinitionProps, CommonMaskProps {}
```

**Comment by msand** [comment]
@scottmas You can even make the changes and a pr here in github if you're interested: https://github.com/react-native-community/react-native-svg/edit/vector-effect/index.d.ts
Otherwise, click the fork button, clone the repo, make the changes, commit, push to your own repo, and open a pr, would be the normal workflow for larger commits.

**Comment by msand** [comment]
@scottmas Could you check that hitTesting/onPress behaves as you would expect? especially edge cases (a little bit inside or outside the filled paint or stroke).

**Comment by msand** [comment]
I suspect the points will need to be transformed a similar amount as the paths, but not sure how all this will interact, would have to do some testing and read/step thru some of the code again.

**Comment by msand** [comment]
Could probably just store the coordinates when the hitTest logic enters the Svg root, and use those when deciding if paths with nonScalingStroke have the points inside their paint regions or not.

**Comment by scottmas** [comment]
Hmmm, I actually can't detect any real difference in the hit target if non-scaling-stroke is present. No matter what, I can only trigger touches if I go a few pixels inside the SVG, we're talking like 4 pixels maybe. If that's the current behavior for adding `onPress` to an SVG element, it seems minor to me. 

If you're pretty sure there is a difference in behavior with non-scaling-stroke you'd have to describe it better for me to be able to replicate it.

**Comment by scottmas** [comment]
Ahh, okay. I put the onPress handler on the top level SVG originally. So that's still a thing if you are worried about it. 

But when I put the onPress handler on the actual Line, I get the behavior you're describing. The hit area on the `non-scaling-stroke` element is as large as it would be if the vector-effect were none.
