### ISSUE TITLE
Superposition of translucent shapes yields wrong values

### ISSUE THREAD

**Issue by ksesong** [react-native-community/react-native-svg#886]
I generate a `<Svg>` component consisting of overlaid shapes with different `fillOpacity`, and I get access to the pixel data using the `toDataURL` method. It all works fine, until I read the values and I realize that the superposition is not working as expected.

Here is a snack of the issue:
https://snack.expo.io/@ksesong/sum-of-translucent-shapes
(Instructions: After changing the `fillOpacity` values, I copy the resulting logged `base64` code as an image, and I read the pixel value on an image editor)
When I write the same `svg` on a classic html file, I always get the expected values (see: https://codepen.io/anon/pen/REKMYx)

I've drawn a quick schematic of the expected/actual values. (A, B, and C refer to different sets of parameters.)

![artboard 1](https://user-images.githubusercontent.com/940567/50288069-1a3e2880-0465-11e9-90a4-8962367ee74b.png)

(I also used `react-native-view-shot` to get the snapshot of the view, and it yielded the same result).

**Comment by msand** [comment]
Check e.g. https://twitter.com/kzzzf/status/1075450658050977792
