### ISSUE TITLE
Error while updating property "d" of a view managed by RNSVGPath: null for input string S

### ISSUE THREAD

**Issue by noahtallen** [react-native-community/react-native-svg#887]
I'm getting a full crash on Android only with the error: Error while updating property "d" of a view managed by RNSVGPath. Null. For input string S.

The exact same code works on iOS. I am using react-native `0.57.8` and react-native-svg `8.0.10`. Those should both be the latest versions.

After some investigation, I discovered that this error happens because I needed a bit more education on using SVGs, but my big question is **why does this code give the desired curve on iOS (even when the syntax is wrong), but just completely crashes the whole app on Android?**

Here is the component:
```js
      <Svg
        height={topAreaHeight}
        width={width}>
        <Defs>
          <LinearGradient id="grad" x1="0" y1="0" x2={width} y2={topAreaHeight}>
            <Stop offset="0" stopColor={gradientFirstStop} stopOpacity="1" />
            <Stop offset="1" stopColor={gradientSecondStop} stopOpacity="1" />
          </LinearGradient>
        </Defs>
        <Path
          d={path}
          fill="url(#grad)"
          stroke="none"
        />
      </Svg>
```

Here is the path definition:
```js
// 1. Works on iOS but crashes Android:
const path = `M0 0 H${width} V${curveStartHeight} S${mid} ${topAreaHeight} S${curveStartHeight} 0 L0 0`.toString()
```
Obviously, the error here is that my definition of S was like `S120 140`, whereas S actually wants two coordinate pairs. Alright. So I did that, and it turns out that this curve definition is actually what I wanted:

```js
// 2. The desired path that doesn't crash Android:
const path = `M0 0 H${width} V${curveStartHeight} Q${mid},${topAreaHeight} 0,${curveStartHeight} L0 0`.toString()
```
However, if we draw curve 1 on iOS, it looks the same as curve 2 drawn on Android. Is iOS doing some shenanigans to infer parts of the curve that Android isn't capable of handling? Additionally, why does this error crash the whole app? Why not do some validation before rendering?

**Comment by msand** [comment]
The parser in ios merely keeps parsing the matches of the regular expression, interpreting the second S as a number (resulting in 0), thus giving the first S four values anyway. Then fallback logic interprets another S command incorrectly, ignoring the last line command (L interpreted as number again). It just happens that the values you've used gives the same output, in general this won't be true. Ideally the parser would be stricter and just choke on incorrect inputs, giving an error rather than give the impression that what was given would be a valid path data string.

**Comment by lukewlms** [comment]
FYI for anyone landing on this page, I ran into this error message and it turned out I needed to pass only multi-element arrays to `VictoryLine`.  Passing an array of only 1 element to `VictoryLine` could cause this crash on Android.  (react-native-victory 9.4.0, latest version)

> Error while updating property 'd' of a view managed by: RNSVGPath
> 
> null
> 
> Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

**Comment by purplegamba** [comment]
> FYI for anyone landing on this page, I ran into this error message and it turned out I needed to pass only multi-element arrays to `VictoryLine`. Passing a data array of only 1 element to `VictoryLine` could cause this crash on Android. (react-native-victory 9.4.0, latest version)

Thank you SO MUCH for leaving this comment!  It pointed me on the right track to getting rid of this frustrating error today.

**Comment by EltonCarreiro** [comment]
Yeah, for sure you saved a lot of time of investigation! Thanks for the comment!
