### ISSUE TITLE
Trying to add a RNSVGGroup to a RCTView

### ISSUE THREAD

**Issue by smemamian** [react-native-community/react-native-svg#888]
I want to use `Animated` component to my SVG components.

```
import Svg, { Path, Circle, G } from 'react-native-svg'
const AnimatedCircle = Animated.createAnimatedComponent(Circle);

   <Animated.View style={[styles.tennisBall, this.moveAnimation.getLayout()]}>
          <TouchableOpacity style={styles.button} onPress={()=>this.moveBall(10,10)}>
            <Text style={styles.buttonText}>Press</Text>
          </TouchableOpacity>
          <G>
          <AnimatedCircle
              cx={(100) / 2}
              cy={(100) / 2}
              r="100"
              fill="#d8e8ea"
            />    
            </G>  
  
        </Animated.View>
```

but I got this error:

> cannot add a child that doesn't have a YogaNode to a parent without a measure function! (trying to add a 'RNSVGGroup' to a 'RCTView')

**Comment by msand** [comment]
The error message explains exactly what is wrong, you're trying to add an svg group (G element) to a react native view, you need to wrap it in a Svg root element instead. Same as using svg in the web.
