### ISSUE TITLE
LinearGradient set red to black

### ISSUE THREAD

**Issue by kuangyliang** [react-native-community/react-native-svg#889]
This is my code：

                 <Defs>
                        <LinearGradient id="linear" x1="0%" y1="0%" x2="100%" y2="100%">
                            <Stop offset={"0%"} stopColor={"red"}></Stop>
                            <Stop offset={"100%"} stopColor={"black"}></Stop>
                        </LinearGradient>
                    </Defs>

I want the cicle progress color is from red to black.but sometime  was wrong:
The picture one is right,picture two is not what I want 
Picture one 
![image](https://user-images.githubusercontent.com/7835871/50413938-513d8100-084d-11e9-8edb-9249f3b2ab0f.png)
Picture two
![image](https://user-images.githubusercontent.com/7835871/50413940-55699e80-084d-11e9-990d-ab072fdad95b.png)

**Comment by msand** [comment]
What you're attempting to do isn't part of the spec yet, they're called conical gradients, and you need a polyfill http://leaverou.github.io/conic-gradient/
https://www.w3.org/TR/css-images-4/#conic-gradients
And you'll need to create create some other structure yourself to emulate it

**Comment by kuangyliang** [comment]
> What you're attempting to do isn't part of the spec yet, they're called conical gradients, and you need a polyfill http://leaverou.github.io/conic-gradient/ on the web
> https://www.w3.org/TR/css-images-4/#conic-gradients
> And in react-native-svg you'll need to create create some other structure yourself to emulate it, check how others have done it with svg or canvas for the web.

Thanks!

**Comment by andreymazuro** [comment]
@kuangyliang  did you manage to figure this out?

**Comment by kuangyliang** [comment]
> @kuangyliang did you manage to figure this out?

No,I just modified it briefly.Because svg  LinearGradient  can only set linear gradients，Can only achieve the UI design effect as much as possible
   <LinearGradient id='linear' gradientUnits='userSpaceOnUse' x1='180' y1='150' x2='20' y2='150'>
                <Stop offset='0%' stopColor={startColor} />
                <Stop offset='100%' stopColor={endColor} />
     </LinearGradient>


UI design:
![image](https://user-images.githubusercontent.com/7835871/50959454-f3bc5c00-14fd-11e9-9254-00c889e7bc42.png)

My implementation：
![image](https://user-images.githubusercontent.com/7835871/50959706-852bce00-14fe-11e9-9d5c-98e5610033ce.png)

**Comment by kuangyliang** [comment]
> @kuangyliang did you manage to figure this out?
If your ring doesn't need rounded corners, you can do it with two semicircles. I tried it.

**Comment by msand** [comment]
Seems to me that the bottom middle is opposite to the jump in colors, if you split that image in half (along the middle in the vertical direction) you can use two gradients and paths, one with yellow to orange, and one with orange to red.

**Comment by kuangyliang** [comment]
> Seems to me that the bottom middle is opposite to the jump in colors, if you split that image in half (along the middle so you get a left and a right half) you can use two gradients and paths, one with yellow to orange (from top to bottom) for the right half, and one with orange to red (from bottom to top) for the left half.

I have tried it, it does.But I don't know how to solve the problem of rounded corners.If you are using two semicircles，Your semicircle should have rounded corners on one side and no rounded corners on the other side.
