### ISSUE TITLE
Support for getBBox?

### ISSUE THREAD

**Issue by steveliles** [react-native-community/react-native-svg#89]
Loving react-native-svg - thanks so much!

I am porting some code to React-Native that I originally wrote for the browser using React.js and SVG. Everything is working great so far, but I've run into a problem - I need to calculate the bounding box of various SVG groups (<g> elements).

To obtain the bounding box of a <g> element in a browser, it is enough to use a `ref` to get a callback with the mounted element, then invoke the [SVG spec's `getBBox`](https://www.w3.org/TR/SVG/types.html#__svg__SVGLocatable__getBBox) method on it, e.g.:

```
<g ref={(el)=>{console.log(el.getBBox())}}>
  <circle cx={100} cy={100} r={50}/>
  <circle cx={120} cy={80} r={60}/>
</g>
```

As far as I can tell there isn't currently any support for `getBBox` in react-native-svg, so ... 
1. Are there any plans to introduce this support? (if so, is there a rough timeline?)
2. Is there a good alternative way to calculate the bounding box, taking into account transformations and such?

**Comment by magicismight** [comment]
Yes.there is a plan for shape elements bounding box calculation.
But I\`m not sure if G elements can get the bounding box for its children elements.
Sadly,I don`t have a timeline for this,because this is my free time project.
Maybe after the animation feature.

**Comment by steveliles** [comment]
OK - thanks for the quick response.

In the mean-time I've narrowed my current use-cases down to finding the bounding box of a `<path>` made up only of absolute coordinates or a `<rect>` where neither is subject to any transformation, so I can calculate the bounding box easily enough from the props.

**Comment by 3rd-Eden** [comment]
This would make my life a hell lot simpler as I'm currently decoding the `<path d=`'s value in order to get an estimated with but would be nice if it could be done with the api that was made for this.

**Comment by mdvacca** [comment]
HI @magicismight, 
Do you have any workaround in mind to calculate the resulting width of a <Text> element?
I've been looking for many options but I was unable to find a solution.

Thanks!

**Comment by msand** [comment]
I've implemented matrix transforms of the Canvas.getClipBounds in GroupShadowNode, you could try exposing and using this. 

https://github.com/msand/react-native-svg/blob/48cfe71acaad96e484ce46065c3fab497f37a168/android/src/main/java/com/horcrux/svg/GroupShadowNode.java#L41-L43

**Comment by maxkomarychev** [comment]
I added support for `onLayout` in this PR https://github.com/react-native-community/react-native-svg/pull/651

**Comment by msand** [comment]
You can also use UIManager.measure, closing now.

**Comment by adrian-moisa** [comment]
Sry, but UIManager does not help. All I get are the X and Y. W and H are undefined :( 

    let svgRef: React.Component<SvgProps, any, any>;

    setTimeout(() => {
        UIManager.measure(findNodeHandle(svgRef), (x, y, w, h) => {
            console.log('Args:', x, y, w, h);
        });
    }, 100);

    return (
        <View>
            <Svg fill='none'>
                <Path d={svgPath} ref={ref => svgRef = ref} />
            </Svg>
        </View>
    );

and when using `onLayout` on `<Svg>` I get this nice error:

`index.js:1 Warning: Unknown event handler property `onLayout`. It will be ignored`

Also it seems typescript forbids it on `<Path>`

**Comment by Askill** [comment]
Hej everyone, any update on this?

**Comment by wihlke** [comment]
For anyone wondering, getBBox and onLayout now work! Be aware that the Svg parent need to have both height and width for it to calculate correctly
