### ISSUE TITLE
require('react-native-svg') takes a long time on low end Android

### ISSUE THREAD

**Issue by defualt** [react-native-community/react-native-svg#894]
I'm trying to optimize the launch time of my app and I found react-native-svg to be a bottleneck.  

On a low end Nokia 2 running Android 7.1.1 in production mode I recorded the following lengths of time.
1449ms, 1292ms, 1285ms, 1215ms, 1178ms, 1167ms.

In my iphoneXR Simulator on a 2018 macbookpro I get 94ms, 89ms, 71ms, 67ms.

My monitoring code is:

```
const starttime = Date.now();
const reactNativeSvg = require('react-native-svg');
alert(Date.now() - starttime);
```

"react-native-svg": "^6.3.1",
"react-native": "0.57.3",

**Comment by msand** [comment]
Have you tried upgrading jsc? https://github.com/react-native-community/jsc-android-buildscripts

**Comment by defualt** [comment]
I will try `jsc-android-buildscripts` hopefully before the end of the week.

I just added a timing alert to `extractTransform.js` and it takes 441ms to process on my Nokia 2.  So that would be a nice chunk out of loading time.

I also found that importing the entire lodash library in several places adds 100ms which ain't nothing and can probably be factored out.

**Comment by defualt** [comment]
I tried out jsc-android-buildscripts but I actually got worst performance for the entire app and for react-native-svg.

With `react-native-svg`.  Left value is entire app load time, and right value is `react-native-svg`'s contribution to load time, in milisecends.  The first row of each set is the initial load, and the rows after are subsequent force-quit + load.

### With jsc-android
8618 - 1106
6127 - 1002
5437 - 868
5522 - 924

### Without jsc-android
8159 - 779
5242 - 819
4972 - 792
4978 - 776

**Comment by sundariragavan** [comment]
@msand Hello everyone, react-native-svg is very slow on Android devices. On the other hand, this same app behaves smoothly on iOS devices. The svg image rendering  is very slow. The app is responding, once the image loading completed.The API return correctly. Any idea ?

**Comment by msand** [comment]
Do the android devices you're testing have comparable hardware to the ios devices you're testing? If you compare cheap / low end android to expensive / high end ios devices you can expect performance differences for sure. Also, the rendering pipeline and architecture varies among devices, hardware/os version combinations etc. I would recommend optimizing with e.g. svgo, and profiling the code to find bottlenecks, and attempt to implement equivalent or similar enough output using cheaper rendering primitives and improve reuse/caching. Hard to give more specific suggestions without access to the actual code.

**Comment by msand** [comment]
@defualt I tried removing lodash and compiling the parser in development instead of run-time. I haven't tested it yet, but though you might be interested in trying it out: https://github.com/react-native-community/react-native-svg/tree/optimize_startup

**Comment by defualt** [comment]
Awesome I’ll give it a try on Monday.

**Comment by msand** [comment]
@default have you been able to measure any difference? Can't really find anything else to simplify at this point without changing the interface / semantics. Would need to profile the parse and first execution time in more detail to find any potential optimization targets. But having read the code several times, nothing pops out as having big potential gains at this point. The next step would be to move all the logic from js to the native side. But, that might not happen until a rewrite in rust or something or the changes coming with the fabric rewrite.

**Comment by defualt** [comment]
Looks like massive improvement.  Great work!

Old version start times
878
810
803
820
795

optimize_startup version start times
185
167
146
163
131

**Comment by brentvatne** [comment]
@msand - nice :)

**Comment by msand** [comment]
v9.0.0 has been released with these changes and various spec conformance fixes included.

**Comment by mrousavy** [comment]
@msand Hey! With Fabric + TurboModules + JSI coming up "sometime later this year" (hopefully), do you have a full rewrite for a rust implementation planned? I've noticed really slow performance when rendering complex SVGs such as [react-native-bigheads](https://github.com/felipecespedes/react-native-bigheads)
