### ISSUE TITLE
Use API instead of IMPLEMENTATION

### ISSUE THREAD

**Issue by OleksandrKucherenko** [react-native-community/react-native-svg#898]
https://github.com/react-native-community/react-native-svg/blob/025b8e78694b65ec0d32b52c3f8bd1fc66c7df1d/android/build.gradle#L54

latest android gradle plugin introduce renamed dependency configurations.

**implementation** -- means include dependency JAR into the compiled library
**api** -- means, library force main project to include react-native, but library code itself will not contain any react native API code. _(actually its a partly true)_

more about gradle dependencies: https://jeroenmols.com/blog/2017/06/14/androidstudio3/

**Comment by msand** [comment]
From the article you link to:
> As such the compile dependency has been deprecated and replaced by two new ones:
> 
> api: you leak the interface of this module through your own interface, meaning exactly the same as the old compile dependency
> implementation: you only use this module internally and does not leak it through your interface

It seems correct to use implementation rather than api, afaik we do not leak the react-native api from the interface we expose, and I don't know about any native module which would depend on our interface anyway, so I think this couldn't even have any potential effect on anything at all.

**Comment by msand** [comment]
Btw, why the CAPS? Are you screaming these words inside your head when you write/read them?

**Comment by OleksandrKucherenko** [comment]
> Btw, why the CAPS? Are you screaming these words inside your head when you write/read them?

no other way to highlight the keywords in title of post
