### ISSUE TITLE
error while updating the property 'marginTop' in a shadow node of type

### ISSUE THREAD

**Issue by Yandamuri** [react-native-community/react-native-svg#899]
I am facing some recurrent issues with react-native-svg package as mentioned below,

     Error while updating property 'fill' of a view managed by: RNSVGPath
     Error while updating property 'width' of a view managed by: RNSVGPath  
     Error while updating property 'height' of a view managed by: RNSVGPath
     Error while updating property 'marginTop' of a view managed by: RNSVGPath 
    
 Following code shows how i am using the svg icons

```
case 'chevron-left':
		return (
			<Svg viewBox="0 0 12 21"  {...props.style}>
		              <Path
				    d="M3.05 10.395l8.386-8.11L10.034.852.149 10.395l9.09 10.04 1.62-1.54z"
				    fill={props.color}
				    fillRule="evenodd"
			        />
		          </Svg>
		);
```
maintaining multiple svg icons like above in a dedicated .js file and calling them with their respective name from other pages where it is required as follows,

`<Icon name={'chevron-left'} color={'#959595'} style={{ width: 23, height: 23, marginTop: 10 }} />`

Unable to reproduce or find the root cause of the issue as it is happening randomly and most of the cases happening at app startup. I have posted a question in stackoverflow and referred some git hub issues but didn't get sufficient information about the issue. The above mentioned issues are frequently cashing the app.

I am using 
"react-native": "0.54.2"
"react-native-svg": "8.0.8",

Any help is highly appreciated.
![screenshot_1546940374](https://user-images.githubusercontent.com/31983789/50822591-16147500-1358-11e9-91d5-0b0fbe6a3d6a.png)

**Comment by msand** [comment]
Can you try upgrading react-native to 0.57.4 or newer?
