### ISSUE TITLE
Empty "d" attribute in Path makes iOS app crash

### ISSUE THREAD

**Issue by clems36** [react-native-community/react-native-svg#901]
Hi! I'm using Expo's SVG component which uses `react-native-svg@8.0.10` since their SDK 32 update and since then, my app crashes on iOS when the `d` attribute of a `Path` is `''`. It works fine on Android and before the update (they upgraded from `8.0.8` to `8.0.10`), it worked on iOS aswell.

[Here's a snack that reproduces this](https://snack.expo.io/@emixis/svg-ios-crash), if you switch from v32.0.0 to v31.0.0 it will work, else it will crash.

**Comment by clems36** [comment]
Thanks!

**Comment by clems36** [comment]
@msand can you please re-open this ?

**Comment by msand** [comment]
You need to rebuild the native bundle, have you ejected from expo?

**Comment by clems36** [comment]
No, my bad... Guess I'll have to wait for the next sdk to test that.
