### ISSUE TITLE
v9.0.0 release notes?

### ISSUE THREAD

**Issue by sm1th** [react-native-community/react-native-svg#902]
What are the breaking changes from `v8.x.x`? What are the upgrade steps? Do I have to run `react-native link`?

Thanks

**Comment by msand** [comment]
Linking shouldn't be necessary if you already have v8 linked. Breaking changes should be limited to spec conformance fixes of:
Skew/skewx/skewy as plain attributes or as part of a transform object (transform strings were already conforming)
Use elements with x or y attributes or as part of a transform object
