### ISSUE TITLE
Could not resolve all files for configuration ':react-native-svg:classpath'

### ISSUE THREAD

**Issue by SoloJiang** [react-native-community/react-native-svg#903]
When I use `react-native-svg-charts`, it's peerDependencies is `react-native-svg`. So I `npm i react-native-svg-charts --save`, and then `react-native link react-native-svg`.Finally, I use `react-native run-ios`.But: 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-svg'.
> Could not resolve all files for configuration ':react-native-svg:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         project :react-native-svg
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

It's ok, when I run with ios.

**Comment by witalobenicio** [comment]
@SoloJiang how did you fixed that?

**Comment by SoloJiang** [comment]
> @SoloJiang how did you fixed that?

I found the mistake is that my andriod studio proxy was set in socks. However, this error was caused by it works on http, so I changed my andriod studio proxy method, to be exact, I switch to the http 
proxy listening port.
