### ISSUE TITLE
iOS application crash when use <TSpan> with spaces as text

### ISSUE THREAD

**Issue by oleksandr-dziuban** [react-native-community/react-native-svg#904]
Hello, guys, just noticed a problem when I use <TSpan> element with text which contains only space symbols (or just one space symbol) iOS application causes crash. Android application works fine.

It can be reproduced on empty app with imported Svg, Text, TSpan inside `<View>`.

```
<Svg
      version="1.1"
      id="test"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      style={{ width: 200, height: 200 }}
      viewBox="0 0 200 200"
    >
  <G>
    <Text x="0" y="0">
       <TSpan x="0" dy="10" letterSpacing="1">{' '}</TSpan>
    <Text>
  </G>
</Svg>
```

"react": "16.6.1",
"react-native": "0.57.7",
"react-native-svg": "9.0.0", (same on 8.x.x)

Mac OS 10.14.2 High Sierra
Xcode v10.1
NodeJS v10.13.0
npm v6.4.1

**Comment by msand** [comment]
Unable to replicate in v9.0.1 with this at least:
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { G, Text, TSpan, Svg } from 'react-native-svg';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg
          version="1.1"
          id="test"
          xmlns="http://www.w3.org/2000/svg"
          xmlnsXlink="http://www.w3.org/1999/xlink"
          style={{ width: 200, height: 200 }}
          viewBox="0 0 200 200"
        >
          <G>
            <Text x="0" y="0">
              <TSpan x="0" dy="10" letterSpacing="1">{' '}</TSpan>
            </Text>
          </G>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by oleksandr-dziuban** [comment]
@msand Thank you for your help, let me check on 9.0.1 too

**Comment by oleksandr-dziuban** [comment]
@msand Checked, but still have crash on my iOS 12 iPhoneX emulator + real iPhone 6 Plus (iOS 12.1.3) device

**Comment by oleksandr-dziuban** [comment]
@msand Maybe the reason in combination of another things...

**Comment by msand** [comment]
Did you rebuild the native bundle? Can't replicate it yet at least. Can you try v9.0.3?

**Comment by oleksandr-dziuban** [comment]
@msand I didn't check your simple example yet, just tried to run my large application with complex SVG structure and spaces symbols as svg text and still have the crash.
So maybe the reason in combination of space symbols and another SVG things in my code.
I will let you know when I try basic simple app example. Thank you for your time

**Comment by msand** [comment]
Here's an even simpler example:

```jsx
import * as React from 'react';
import { Svg, Text, Path } from 'react-native-svg';

export default () => (
  <Svg width="100%" height="100%" viewBox="0 0 1 1">
    <Path d="M0,0 L1,1" stroke="blue" />
    <Text> </Text>
  </Svg>
);

```

**Comment by oleksandr-dziuban** [comment]
@msand For me problem replicates in <TSpan> with only space symbols. <Text> works fine

**Comment by oleksandr-dziuban** [comment]
@msand Confirmed issue cannot be reproduced now. Please close this issues. Thanks a lot
