### ISSUE TITLE
Pattern is not displayed on iOS

### ISSUE THREAD

**Issue by c100k** [react-native-community/react-native-svg#906]
Hi there,

Nice job done on the Pattern implementation. Nevertheless, it does not show up on **iOS**. It works as expected on **Android** though.

**Configuration**

- react-native : 0.57.8
- react-native-svg : 9.0.0
- iOS : 12.1

**Pattern.jsx**

```jsx
const PatternBackground = (props: Props) => (
    <Svg width="100%" height="100%" viewBox="0 0 800 400">
        <Defs>
            <Pattern
                id="TrianglePattern"
                patternUnits="userSpaceOnUse"
                x="0"
                y="0"
                width="100"
                height="100"
                viewBox="0 0 10 10"
            >
                <Path d="M 0 0 L 7 0 L 3.5 7 z" fill="red" stroke="blue" />
            </Pattern>
        </Defs>
        <Rect
            fill="none"
            stroke="blue"
            x="1"
            y="1"
            width="798"
            height="398"
        />
        <Ellipse
            fill="url(#TrianglePattern)"
            stroke="black"
            stroke-width="5"
            cx="400"
            cy="200"
            rx="350"
            ry="150"
        />
    </Svg>
);
```

As you can see, it is the exact same code as the [documentation](https://github.com/react-native-community/react-native-svg#pattern) but the pattern is not displayed even after global clean.

<img width="260" alt="capture d ecran 2019-01-22 a 10 46 45" src="https://user-images.githubusercontent.com/5722457/51526678-2a19a580-1e33-11e9-9d04-6177fea8226e.png">

When debugging on React Native Debugger, the following error pops up when opening `RNSVGDefs` > `Pattern`

```js
ExceptionsManager.js:84 RCTJSONStringify() encountered the following error: Invalid number value (infinite) in JSON write
```

Not sure if there is an issue or a missing prop?

**Comment by msand** [comment]
There was a regression, published fix in v9.0.2, thanks for reporting!
