### ISSUE TITLE
How to increase svg width based on text

### ISSUE THREAD

**Issue by saikiranoptisol** [react-native-community/react-native-svg#907]
I'm using this component in my app in many places. recently i found some difficulty with the usage. if i have long text the width of the svg must be adjustable based on the text and the text must be in the center of the box. For suppose 
![microsoftteams-image 3](https://user-images.githubusercontent.com/40380599/51531223-e3dc3a80-1e62-11e9-9fac-b8d4d939fc73.png)

My code is something like below 

`<View style={{marginTop: 50,width:'100%', height: 50, justifyContent: 'center', alignItems: 'center', flexDirection:'row'}}>
                        <Svg  width={200} height={50}  style={{backgroundColor:'yellow'}}>
                            <SvgLinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
                                <Stop stopColor="#C2515D" offset="0%"/>
                                <Stop stopColor="#853C5E" offset="100%"/>
                            </SvgLinearGradient>
                            <Text fill="url(#Gradient)"
                                  x="50"
                                  y="20"
                                  fontSize="18"
                                  fontWeight="700"
                                  textAnchor="start" >
                                hi hello hi hih hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi i hi
                            </Text>
                        </Svg>
            </View>`

here based on the text the width of the svg must be increased how?

**Comment by msand** [comment]
How about something like this?
https://snack.expo.io/@msand/bWVhc3

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';

const { Text, TSpan } = Svg;

export default class App extends React.Component {
  state = {};
  onTextLayout = e => {
    //console.log('text', e.nativeEvent.layout);
    const textLayout = e.nativeEvent.layout;
    const { height, width, x, y } = textLayout;
    if (height && !this.state.textWidth) {
      this.setState({ textWidth: width });
    }
  };
  onRootLayout = e => {
    //console.log('root', e.nativeEvent.layout);
    const { height, width, x, y } = e.nativeEvent.layout;
    const viewBox = `0 0 ${width} 100`;
    if (!this.state.rootWidth) {
      this.setState({ rootWidth: width });
    }
  };
  render() {
    const { rootWidth, textWidth } = this.state;
    const hasMeasured = rootWidth && textWidth;
    const viewBox = hasMeasured
      ? `0 0 ${(100 * textWidth) / rootWidth} 100`
      : '0 0 100 100';
    //console.log('viewBox', viewBox);
    return (
      <View style={styles.container}>
        <Svg
          width="100%"
          height="100%"
          viewBox={viewBox}
          onLayout={this.onRootLayout}>
          <Text
            y="50"
            onLayout={this.onTextLayout}
            fill={hasMeasured ? 'black' : 'none'}>
            Testing, testing, 1, 2, 3...
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by saikiranoptisol** [comment]
if i use   fill={hasMeasured ? 'black' : 'none'}> my app is getting crashed with reason RCTJSONStringify() encountered the following error: invalid number value (infinite) in JSON write.

and more over if i see the code the color of text is only black but i need gradient color

**Comment by msand** [comment]
How about something like this: https://snack.expo.io/@msand/measured-svg-text-with-gradient

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';

const { LinearGradient, Stop, Text, Rect } = Svg;

export default class App extends React.Component {
  state = {};
  onTextLayout = e => {
    const textLayout = e.nativeEvent.layout;
    const { height, width, x, y } = textLayout;
    const { textWidth } = this.state;
    //console.log('text', textLayout);
    if (height && !textWidth) {
      this.setState({ textWidth: width });
    }
  };
  onRootLayout = e => {
    const rootLayout = e.nativeEvent.layout;
    const { height, width, x, y } = rootLayout;
    //console.log('root', rootLayout);
    this.setState({ rootWidth: width, rootHeight: height });
  };
  render() {
    const { rootWidth, rootHeight, textWidth } = this.state;
    const hasMeasured = rootWidth && textWidth;
    const width = 100 * (textWidth / Math.min(rootWidth, rootHeight));
    const viewBox = hasMeasured ? `0 0 ${width} 100` : '0 0 100 100';
    //console.log('viewBox', viewBox);
    return (
      <View style={styles.container}>
        <Svg
          width="100%"
          height="100%"
          viewBox={viewBox}
          onLayout={this.onRootLayout}>
          <Rect x="0" y="0" width="100%" height="100" fill="yellow" />
          <LinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
            <Stop stopColor="green" offset="0%" />
            <Stop stopColor="blue" offset="100%" />
          </LinearGradient>
          <Text
            y="50"
            fontSize="18"
            fontWeight="700"
            onLayout={this.onTextLayout}
            fill={hasMeasured ? 'url(#Gradient)' : 'none'}>
            hi hello hi hih hi hi hi hi hi hi hi hi hi hi 1 hi hi hi ho hi hi i
            hi
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by saikiranoptisol** [comment]
import React, {Component} from 'react'
import {ImageBackground, View, Text as NormalText} from 'react-native'
import FilterNavigation from "../FilterMatches/FilterNavigation";
import {LinearGradient as SvgLinearGradient} from "react-native-svg";
import Stop from "react-native-svg/elements/Stop";
import Text from "react-native-svg/elements/Text";
import Svg from "react-native-svg/elements/Svg";



class EditProfile extends Component{
    constructor(props){
        super(props)
        this.state={
            userInfo:[]
        }
    }

    componentDidMount(){
       this.setState({
           userInfo: this.props.navigation.getParam('userDetails')
       },()=>console.log('userInfo is'+JSON.stringify(this.state.userInfo)))
    }

    onTextLayout = e => {
        const textLayout = e.nativeEvent.layout;
        const { height, width, x, y } = textLayout;
        //console.log('text', textLayout);
        if (height && !this.state.textWidth) {
            this.setState({ textWidth: width });
        }
    };

    onRootLayout = e => {
        const rootLayout = e.nativeEvent.layout;
        const { height, width, x, y } = rootLayout;
        //console.log('root', rootLayout);
        if (!this.state.rootWidth) {
            this.setState({ rootWidth: width });
        }
    };
    render(){
        const { rootWidth, textWidth } = this.state;
        const hasMeasured = rootWidth && textWidth;
        const viewBox = hasMeasured
            ? `0 0 ${(100 * textWidth) / rootWidth} 100`
            : '0 0 100 100';
        return(
        <View style={{flex:1}}>
            <ImageBackground
                style={{width: '100%', height: 150, position: 'absolute',}}
                resizeMode={'stretch'}
                source={require("./../../../assets/Background.png")}
            >
            </ImageBackground>
            <FilterNavigation
                back={() => this.props.navigation.goBack()}
                text={'Profile'}/>

            <View style={{marginTop: 50,width:'100%', height: 50, justifyContent: 'center', alignItems: 'center', flexDirection:'row',}}>
                <Svg
                    width="100%"
                    height="100%"
                    viewBox={viewBox}
                    onLayout={this.onRootLayout}>
                    <SvgLinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
                        <Stop stopColor="green" offset="0%" />
                        <Stop stopColor="blue" offset="100%" />
                    </SvgLinearGradient>
                    <Text
                        y="50"
                        fontSize="18"
                        fontWeight="700"
                        onLayout={this.onTextLayout}
                        fill={hasMeasured ? 'url(#Gradient)' : 'none'}>
                        hi hello hi hih hi hi hi hi hi hi hi hi hi hi 1 hi hi hi ho hi hi i
                        hi
                    </Text>
                </Svg>
            </View>
        </View>
        )}
}
export default EditProfile



My whole code is that. if i use fill as you mentioned my app is crasing with the red screen RCTJSONStringify() encountered the following error: invalid number value (infinite) in JSON write.

**Comment by msand** [comment]
Hmm, strange, what version are you using?

**Comment by msand** [comment]
Does this work?


```jsx
        <Svg
          width="100%"
          height="100%"
          viewBox={viewBox}
          onLayout={this.onRootLayout}>
          <Rect x="0" y="0" width="100%" height="100" fill="yellow" />
          <LinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
            <Stop stopColor="green" offset="0%" />
            <Stop stopColor="blue" offset="100%" />
          </LinearGradient>
          <Rect x="0" y="90" width="100%" height="10" fill="url(#Gradient)" />
        </Svg>
```

**Comment by saikiranoptisol** [comment]
i just modified my code as 
<Svg  width="100%"
                              height="80%"
                              onLayout={this.onRootLayout} style={{backgroundColor:'yellow'}}>
                            <SvgLinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
                                <Stop stopColor="#C2515D" offset="0%"/>
                                <Stop stopColor="#853C5E" offset="100%"/>
                            </SvgLinearGradient>
                            <Text fill="url(#Gradient)"
                                  x="0"
                                  y="20"
                                  fontSize="18"
                                  fontWeight="700"
                                  textAnchor="start"
                                  onLayout={this.onTextLayout}
                            >
                                {this.state.userInfo.fullname}
                            </Text>
                        </Svg> 
. so the result is as below 
![microsoftteams-image 4](https://user-images.githubusercontent.com/40380599/51540344-31b16c80-1e7c-11e9-8804-20714d2447e7.png)

now all i need it that name must come in the center

**Comment by msand** [comment]
![screenshot_20190122-160310](https://user-images.githubusercontent.com/1131362/51540527-50edd100-1e5f-11e9-9055-ae97a4b3e4ae.jpg)

**Comment by msand** [comment]
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';

const { LinearGradient, Stop, Text, Rect } = Svg;

export default class App extends React.Component {
  state = {};
  onTextLayout = e => {
    const textLayout = e.nativeEvent.layout;
    const { height, width, x, y } = textLayout;
    const { textWidth } = this.state;
    //console.log('text', textLayout);
    if (height && !textWidth) {
      this.setState({ textWidth: width });
    }
  };
  onRootLayout = e => {
    const rootLayout = e.nativeEvent.layout;
    const { height, width, x, y } = rootLayout;
    //console.log('root', rootLayout);
    this.setState({ rootWidth: width, rootHeight: height });
  };
  render() {
    const { rootWidth, rootHeight, textWidth } = this.state;
    const hasMeasured = rootWidth && textWidth;
    const width = 100 * (textWidth / Math.min(rootWidth, rootHeight));
    const viewBox = hasMeasured ? `0 0 ${width} 100` : '0 0 100 100';
    //console.log('viewBox', viewBox);
    return (
      <View style={styles.container}>
        <Svg
          width="100%"
          height="100%"
          viewBox={viewBox}
          onLayout={this.onRootLayout}>
          <Rect x="0" y="0" width="100%" height="100" fill="yellow" />
          <LinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
            <Stop stopColor="green" offset="0%" />
            <Stop stopColor="blue" offset="100%" />
          </LinearGradient>
          <Text
            y="50"
            fontSize="18"
            fontWeight="700"
            onLayout={this.onTextLayout}
            fill={hasMeasured ? 'url(#Gradient)' : 'none'}>
            Kushi kapoor
          </Text>
          <Rect x="0" y="90" width="100%" height="10" fill="url(#Gradient)" />
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by saikiranoptisol** [comment]
fill={hasMeasured ? 'url(#Gradient)' : 'none'}>

getting error as RCTJSONStringify() encountered the following error: invalid number value (infinite) in JSON write.

**Comment by msand** [comment]
There was a bug in the iOS implementation, paths without fill and stroke didn't get measured. This works now:

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { LinearGradient, Stop, Text, Rect, Svg } from 'react-native-svg';

export default class App extends React.Component {
  state = {};
  onTextLayout = e => {
    const textLayout = e.nativeEvent.layout;
    const { height, width, x, y } = textLayout;
    const { textWidth } = this.state;
    console.log('text', textLayout);
    if (height && !textWidth) {
      this.setState({ textWidth: width, textX: x });
    }
  };
  onRootLayout = e => {
    const rootLayout = e.nativeEvent.layout;
    const { height, width, x, y } = rootLayout;
    console.log('root', rootLayout);
    this.setState({ rootWidth: width, rootHeight: height });
  };
  render() {
    const { rootWidth, rootHeight, textWidth, textX } = this.state;
    const hasMeasured = rootWidth && textWidth;

    const width = 100 * (textWidth / Math.min(rootWidth, rootHeight));
    const viewBox = hasMeasured ? `0 -18 ${width} 27` : '0 0 100 100';
    console.log('viewBox', viewBox, rootWidth);
    return (
      <View style={styles.container}>
        <Svg
          width="100%"
          height="100"
          viewBox={viewBox}
          onLayout={this.onRootLayout}
          style={{ backgroundColor: 'yellow' }}
        >
          <Rect x="0" y="1" width="100%" height="1" fill="url(#Gradient)" />
          <LinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
            <Stop stopColor="green" offset="0%" />
            <Stop stopColor="blue" offset="100%" />
          </LinearGradient>
          <Text
            fontSize="18"
            fontWeight="700"
            onLayout={this.onTextLayout}
            fill={hasMeasured ? 'url(#Gradient)' : 'none'}
          >
            Kushi kapoor
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by msand** [comment]
Or, if you would want the underline to be the same width as the text (even if you rotate the device), then you could use this:
```jsx
          <Rect x="0" y="1" width={hasMeasured ? width : "100%"} height="1" fill="url(#Gradient)" />
```

**Comment by msand** [comment]
Slightly more involved version:
```jsx
import * as React from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { LinearGradient, Stop, Text, Rect, Svg } from 'react-native-svg';

export default class App extends React.Component {
  state = {};
  onTextLayout = e => {
    const textLayout = e.nativeEvent.layout;
    const { height, width, x } = textLayout;
    const { rootWidth, textWidth, textX } = this.state;
    const hasMeasured = rootWidth && textWidth;
    //console.log('text', textLayout);
    if (height && !textWidth) {
      this.setState({ textWidth: width });
    }
    const { width: w, height: h } = Dimensions.get('window');
    const portraitMode = w < h;
    if (hasMeasured && portraitMode && !textX) {
      this.setState({ textX: x });
    }
  };
  onRootLayout = e => {
    const rootLayout = e.nativeEvent.layout;
    const { height, width } = rootLayout;
    //console.log('root', rootLayout);
    this.setState({ rootWidth: width, rootHeight: height });
  };
  render() {
    const { rootWidth, rootHeight, textWidth, textX = 0 } = this.state;
    const { width: w, height: h } = Dimensions.get('window');

    const portraitMode = w < h;
    const hasMeasured = rootWidth && textWidth;
    const ready = hasMeasured && (!portraitMode || textX);
    const measuredRatio = (textWidth + (portraitMode ? textX : 0)) / rootHeight;
    const width = 100 * measuredRatio;

    const viewBox = hasMeasured ? `0 0 ${width} 20` : '0 0 100 100';
    //console.log('viewBox', viewBox, rootWidth, portraitMode);

    return (
      <View style={styles.container}>
        <Svg
          width="100%"
          height="100"
          viewBox={viewBox}
          onLayout={this.onRootLayout}
          style={{ backgroundColor: 'yellow' }}
        >
          <Rect
            x="0"
            y="19"
            height="1"
            fill="url(#Gradient)"
            width={ready ? width : '100%'}
          />
          <LinearGradient id="Gradient" x1="0%" x2="100%" y1="0%" y2="0%">
            <Stop stopColor="green" offset="0%" />
            <Stop stopColor="blue" offset="100%" />
          </LinearGradient>
          <Text
            y="18"
            fontSize="18"
            fontWeight="700"
            onLayout={this.onTextLayout}
            fill={ready ? 'url(#Gradient)' : 'none'}
          >
            Kushi kapoor
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by msand** [comment]
Published v9.0.1

**Comment by saikiranoptisol** [comment]
@msand  i just copied and pasted the above code completely still i got error like RCTJSONStringify() encountered the following error: invalid number value (infinite) in JSON write. 

if i use  fill={ready ? 'url(#Gradient)' : 'none'} in Text  the error/exception is coming

**Comment by msand** [comment]
Did you upgrade and rebuild the native bundle?

**Comment by albertcito** [comment]
I tried to write this example with hooks and TS. But I'm getting this error in the tag <Text>

> **Unknown event handler property `onLayout`**

I need to change the font size to adjust it to the size of the container.
