### ISSUE TITLE
Image as a background of the polygon isn't displayed 

### ISSUE THREAD

**Issue by pgnedoy** [react-native-community/react-native-svg#910]
So, image isn't displayed when I use clipPath property inside Image. Do you have any ideas? 

        <Defs>
          <ClipPath id="hexagon">
            <Polygon
              points={pointsClipPathPolygon}
            />
          </ClipPath>
        </Defs>

        <Image
          width="100%"
          height="100%"
          preserveAspectRatio="xMidYMid slice"
          href={{ uri: ImageUrl }}
          clipPath="url(#hexagon)"
        />

**Comment by msand** [comment]
Can you provide a full replication? Perhaps try with a <Rect width="100%" height="100%" /> inside the clipPath?

**Comment by bmcn99** [comment]
Try changing href={{ uri: ImageUrl }} to source={{ uri: ImageUrl }}

This worked for me, but I was using a local file.

...and while we're discussing images, I don't suppose anyone has been able to resize any images included this way? I am trying to do so but the x, y, width, and height attributes are being completely ignored. Opacity does work however. 

I had some trouble earlier with resizing my large image but had to tweak the styles on it's containers to get it to work. When I try to use it inside the <Svg> tag it goes back to being full size. I have tried putting the SVG element inside the same structure that I had my image in, in the hopes that it would let me resize the image but that has not worked. The other thing I tried, as a longshot, is taking the styles on the images parent when it worked, and using them on the SVG element itself (Since hey, the image is now a child under that element right?). This did not work either.

**Comment by msand** [comment]
Perhaps can wrap it inside another Svg element, and set the size on that? I'm not sure I understand the question. Executable code / an example would make it easier

**Comment by bmcn99** [comment]
The modal is in a <View> with no extra styling. This is grabbed from the example on https://github.com/react-native-community/react-native-svg, though I changed href to source and the opacity format to get it to work

`                        <Modal
                            animationType="slide"
                            onRequestClose={this.onCloseModal}
                            transparent={false}
                            visible={this.props.memoryBoxModalVisible}
                            
                        >

                                <View>
                                    <View>
                                        <Svg height={height * canvasHeightMultiplier} width={width * canvasWidthMultiplier} viewBox={"0 0 " + width * canvasWidthMultiplier + " " + height * canvasHeightMultiplier}>
                                            <Image
                                                x="5%"
                                                y="5%"
                                                width="50%"
                                                height="90%"
                                                preserveAspectRatio="xMidYMid slice"
                                                opacity={0.5}
                                                source={require('../images/my-image.jpg')}
                                            />
                                        </Svg>
                                    </View>
                                </View>
                        </Modal>`

This code produces the image at it's full size which is several times larger than the screen. I have tried all resizeMode settings, but changing that or the width/height/x/y settings don't change it from being displayed at full size.

When I was able to display an image with a size reduction I had it in a structure like this:

`<View style={{backgroundColor: '#fff',        position: 'relative',        flex: 1,        justifyContent: 'center' }}>
                                <View style={{flexDirection: 'row',        justifyContent: 'space-between',        alignItems: 'center',        paddingBottom: 10}}>
                                    <Image style={{width: undefined,        height: undefined,        flex: 1}} source={_myImage} resizeMode="contain" />
                                </View>
                            </View>`

I tried to replicate this while using the image within the SVG tag but that's where I've been stuck.

**Comment by msand** [comment]
@pgnedoy At least this seems to work fine:

```jsx
import React, { Component } from 'react';

import Svg, {
    Image,
    Defs,
    Circle,
    ClipPath,
    Polygon,
    Text,
} from 'react-native-svg';

class ImageExample extends Component {
    render() {
        return (
            <Svg width="400" height="200" viewBox="0 0 400 200">
                <Defs>
                    <ClipPath id="hexagon" clipRule="evenodd">
                        <Polygon points="160,198 10,78 190,78 40,198 100,10" />
                    </ClipPath>
                    <ClipPath id="hexagon2" clipRule="nonzero">
                        <Polygon x={200} points="160,198 10,78 190,78 40,198 100,10" />
                    </ClipPath>
                </Defs>
                <Image
                    x="0"
                    y="0"
                    width="200"
                    height="200"
                    href={require('../image.jpg')}
                    clipPath="#hexagon"
                />
                <Image
                    x="200"
                    y="0"
                    width="200"
                    height="200"
                    href={require('../image.jpg')}
                    clipPath="#hexagon2"
                />
            </Svg>
        );
    }
}
```

**Comment by msand** [comment]
Or equivalently, but perhaps a bit simpler to see the difference:
```jsx
import React, { Component } from 'react';

import Svg, {
    Image,
    Defs,
    Circle,
    ClipPath,
    Polygon,
    Text,
    G,
} from 'react-native-svg';

class ImageExample extends Component {
    render() {
        return (
            <Svg height="200" width="400" viewBox="0 0 400 200">
                <Defs>
                    <ClipPath id="hexagon" clipRule="evenodd">
                        <Polygon points="160,198 10,78 190,78 40,198 100,10" />
                    </ClipPath>
                    <ClipPath id="hexagon2" clipRule="nonzero">
                        <Polygon points="160,198 10,78 190,78 40,198 100,10" />
                    </ClipPath>
                </Defs>
                <Image
                    x="0"
                    y="0"
                    width="200"
                    height="200"
                    href={require('../image.jpg')}
                    clipPath="#hexagon"
                />
                <G transform="translate(200, 0)">
                    <Image
                        x="0"
                        y="0"
                        width="200"
                        height="200"
                        href={require('../image.jpg')}
                        clipPath="#hexagon2"
                    />
                </G>
            </Svg>
        );
    }
}
```
