### ISSUE TITLE
Unable to resolve module './patternReg' from lib/extract/extractProps.js

### ISSUE THREAD

**Issue by fiid** [react-native-community/react-native-svg#911]
I'm getting a confusing error trying to use react-native-svg on a project.  

```Unable to resolve "./patternReg" from "node_modules/react-native-svg/lib/extract/extractProps.js"``` (this is from the expo bundler)

It seems weird since extractProps.js seems to have no mention of patternReg.

**Comment by fiid** [comment]
I'm using VictoryCharts and expo in this project also.  I think one possible cause is that there's a version of react-native-svg under expo and one up at the project level.  If I remove the project level one though, Victory is then unable to find the expo version of r-n-svg.  Any thoughts or suggestions greatly appreciated.

**Comment by msand** [comment]
This question probably belongs in the VictoryCharts repo, perhaps can try using a recently forked version of it where the dependency has been adapted to be Expo compatible, such as this one: https://github.com/InteractionEcologies/victory-native

**Comment by fiid** [comment]
For sure.  I was able to get it to work by explicitly importing the version of react-native-svg that expo has, which also seems to satisfy the victory dependency, but isn't the version chosen by npm.  Thanks for the suggestion!!

**Comment by christopherfraser** [comment]
I had the same problem. I think deleting the metro cache and haste map in /tmp fixed it for me.

**Comment by aravind1078** [comment]
@christopherfraser  can you explain in detail what you did iam also getting the same issue

**Comment by dskusuma** [comment]
Hi I'm also got the same issue. Anyone have the way to fix it yet?

**Comment by MrShakes** [comment]
`watchman watch-del-all && rm -fr $TMPDIR/react-* && npm start -- --reset-cache` did it for me, basically reset cache
