### ISSUE TITLE
No documentation of Rect rx ry props

### ISSUE THREAD

**Issue by tell-y** [react-native-community/react-native-svg#912]
There is no sample code using rx and ry props of Rect component.
https://github.com/react-native-community/react-native-svg#rect

But actually those was implemented, so we can use those.
https://github.com/react-native-community/react-native-svg/blob/master/elements/Rect.js#L20

**Comment by msand** [comment]
The svg specs includes some examples
https://www.w3.org/TR/SVG11/shapes.html#RectElement
https://www.w3.org/TR/SVG/shapes.html#RectElement

https://svgwg.org/svg2-draft/geometry.html#RY
https://svgwg.org/svg2-draft/geometry.html#RX

Also, e.g. MDN has some documentation:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry

**Comment by msand** [comment]
Also, the example app includes a few: 
https://github.com/magicismight/react-native-svg-example/blob/5a972149f22e0464152d487e6aab015a368ba02a/examples/Rect.js#L52-L115

**Comment by tell-y** [comment]
Thanks.
I would like to edit those example of README.md, What should I follow contributing rule to change the file or screen shot image?

**Comment by msand** [comment]
Sure, feel free to submit a pull request 👍
