### ISSUE TITLE
Broken after upgrading React Native to 0.58: "Unable to resolve module react-native/Libraries/Image/ImageSourcePropType"

### ISSUE THREAD

**Issue by wouterds** [react-native-community/react-native-svg#917]
It can't resolve an import referenced in this library.

```
error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Image/ImageSourcePropType` from `{../..}/my-app/node_modules/react-native-svg/elements/Image.js`: Module `react-native/Libraries/Image/ImageSourcePropType` does not exist in the Haste module map
```

Seems like [they moved or removed the file](https://github.com/facebook/react-native/commit/84f18341aad1c11d97aea042810964ff4a7cbbcb).

**Comment by msand** [comment]
Proptypes have been removed since v8 was released on 19 Oct 2018: https://github.com/react-native-community/react-native-svg/pull/805

**Comment by wouterds** [comment]
You're right, it looks like I'm using an outdated version. Sorry!

**Comment by c-goettert** [comment]
I am facing the same error. I am using v6.5.2 with RN-Version 0.59.5, which should be compatible according to the docs (>=6 >=0.50). Maybe the docs should be updated.

**Comment by msand** [comment]
@c-goettert Have you tried v6.5.3? It contains this commit: https://github.com/react-native-community/react-native-svg/commit/f8a4d96d3dc61cc9830377c2dcd24d114c28ed5d

**Comment by c-goettert** [comment]
@msand thanks for the reply, I switched to v9 now and it works. But still maybe the compatibility section of the docs should be updated.
