### ISSUE TITLE
React-Native Link causes bug on settings.gradle

### ISSUE THREAD

**Issue by jakks-team** [react-native-community/react-native-svg#918]
I'm not sure whether this is a bug from the react-native-svg or the react-native command line. Or maybe even just that I'm using some outdated tools.
So I'll just leave it here. Please recheck the case.

Things I'm using (with their version number).
OS: Windows 10
npm: 6.4.1
node: v10.14.1
Android Studio: 3.1.2
react-native-cli: 2.0.1
react-native: 0.58.3
react-native-svg: 9.0.7

Following the installation guide from https://github.com/react-native-community/react-native-svg#automatically
After react-native link, I noticed the Android studio asked me to "sync" the project to the changes of the gradle made (I suppose made by react-native link).
So I did, and noticed there is an error which is cause by the line below (in settings.gradle) :
`project(':react-native-svg').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-svg\android')`
Notice the directory url use \node_modules (and 2 more slashes after that some problem) and I realize it is read by the compiler as (newline)ode_modules. So, I tried adding another slash to change it to :
`project(':react-native-svg').projectDir = new File(rootProject.projectDir, '..\\node_modules\\react-native-svg\\android')`
And it worked.

So, I'm not sure whether it is okay to leave this here, or should I try to post somewhere else.

**Comment by msand** [comment]
Hmm, haven't seen this before. Are you able to replicate this in a new project? I wonder why/when this would have changed. I'll try on a windows machine later on.

**Comment by jakks-team** [comment]
> Hmm, haven't seen this before. Are you able to replicate this in a new project? I wonder why/when this would have changed. I'll try on a windows machine later on.

Yes, and somehow this issues doesn't happen to only react-native-svg. But i've been adding other libraries as well like react-native-sound, react-navigation, and others, and the same problem also happen.

I'm quite unsure, when react-native link react-native-svg is run, who actually handles what to add to the project?
Is it react-native-cli? or is there a script that is provided by react-native-svg?

So, I'm thinking maybe it is my version of other things that is outdated and cause this problem?

**Comment by msand** [comment]
react-native-svg doesnt have any control of this aspect, we only have the library specific build.gradle file: https://github.com/react-native-community/react-native-svg/blob/master/android/build.gradle
react-native-cli does the rest

**Comment by jakks-team** [comment]
Closing this issue, as this is most likely not on any aspect that react-native-svg contributors have control over.
For future, I just suggest to add in the Readme or tutorial for people who might met similar problem to check the setting.gradle

**Comment by AlexMachin1997** [comment]
@msand Have been able to resolve this issue? Did you start an issue on react-navigation?

**Comment by jakks-team** [comment]
> @msand Have been able to resolve this issue? Did you start an issue on react-navigation?

Not sure what you mean.
This is an issue on react-native-cli **not** react-navigation.
And no, I didn't start an issue there. I somehow manage to fix it myself by just changing the "\" on the settings.gradle to "/" and the problem fixes itself.
This was a problem caused by "react-native link react-native-svg" command.
Which by-itself is not what "react-native-svg" have control over.
