### ISSUE TITLE
Render SVG Image from URL

### ISSUE THREAD

**Issue by matc4** [react-native-community/react-native-svg#92]
It is possible render an SVG image from an URL whit this library?

**Comment by CrystalRanita** [comment]
+1 Hope it can support render SVG images, too.
It is difficult to draw complicated SVG images.

**Comment by derdav3** [comment]
any progress on this?

**Comment by matiascba** [comment]
I have a possible solution. I will try to finish soon and post the source code here.

**Comment by derdav3** [comment]
@matc4 any updates?

**Comment by EQuimper** [comment]
+ 1 We want this

**Comment by matc4** [comment]
Hello, i made this library [react-native-svg-uri](https://github.com/matc4/react-native-svg-uri).
I will ask if this approach is correct for the maintainers of react-native-svg in order to merge the library
