### ISSUE TITLE
Jest tests fail on RN 0.58 (due to Jest Transpiling issue?)

### ISSUE THREAD

**Issue by FransTwisk** [react-native-community/react-native-svg#929]
This issue might affect a lot of packages, but currently I only experiencing it with this one. I believe it's related to https://github.com/facebook/react-native/issues/22175 and the solution is probably to update the import/exports and class arrow methods. 

When running jest tests:
```
TypeError: Cannot read property 'default' of undefined

at new Svg (node_modules/react-native-svg/elements/Svg.js:22:369)
at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3426:18)
at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6550:5)
at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7426:16)
at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10996:12)
at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11028:24)
at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11111:7)
at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11985:7)
at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11897:7)
at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11871:3)
```

**Comment by seanhenry** [comment]
I get this issue too after updating to 0.58.

In the meantime, I'm working around the issue adding the following to `__mocks__/react-native-svg.js`:
```
import React from 'react'
import { View } from 'react-native'

export default () => <View />

export const Circle = () => <View />
export const Ellipse = () => <View />
export const G = () => <View />
export const Text = () => <View />
export const TSpan = () => <View />
export const TextPath = () => <View />
export const Path = () => <View />
export const Polygon = () => <View />
export const Polyline = () => <View />
export const Line = () => <View />
export const Rect = () => <View />
export const Use = () => <View />
export const Image = () => <View />
export const Symbol = () => <View />
export const Defs = () => <View />
export const LinearGradient = () => <View />
export const RadialGradient = () => <View />
export const Stop = () => <View />
export const ClipPath = () => <View />
export const Pattern = () => <View />
export const Mask = () => <View />

```

**Comment by ndiyansah** [comment]
Did you find the answer? i have same issue @FransTwisk

**Comment by FransTwisk** [comment]
I'm mocking it like @seanhenry suggested.

**Comment by msand** [comment]
I tried setting up some end-to-end tests here in case you're interested: https://github.com/msand/react-native-svg-e2e

**Comment by kelset** [comment]
Can confirm that adding that mock file works - thanks @seanhenry.

**Comment by msand** [comment]
I have jest working with detox e2e tests on travis ci here: https://travis-ci.org/msand/react-native-svg-e2e/builds/501950972
Code: https://github.com/msand/react-native-svg-e2e
Locally it works well for taking screenshots too. For iOS I have screenshots working in bitrise as well. Haven't got android e2e tests working there yet (builds work fine), and haven't tried making screenshots work in travis.

**Comment by msand** [comment]
It seems we could provide a mock implementation in a __mocks__ folder: https://jestjs.io/docs/en/manual-mocks.html
https://jestjs.io/docs/en/tutorial-react-native#mock-native-modules-using-jestmock
Something in the style of:
```js
jest.mock('Text', () => {
  const RealComponent = jest.requireActual('Text');
  const React = require('React');
  class Text extends React.Component {
    render() {
      return React.createElement('Text', this.props, this.props.children);
    }
  }
  Text.propTypes = RealComponent.propTypes;
  return Text;
});
```
We could probably provide setters in the files in elements folder, allowing to override the native component with a mock, thus enabling to snapshot even the values sent to the native side to test the js logic for changes.
Although, that seems more like an implementation detail and not really relevant to users of react-native-svg. As it might even change just because of changing the react-native-svg version, when there are api changes made in sync to both js and native, or when the js code has some bugs fixed/features added. But, makes more sense for internal tests in this repo. I guess for external use, something like the Text mock in the example here should allow to snapshot the values which are given to the publicly exposed api of react-native-svg.

**Comment by msand** [comment]
These might interest anyone working on this: 

https://github.com/facebook/react-native/blob/7da864284997109a37bbef739289c5e6e8d0514e/jest/setup.js

https://github.com/facebook/react-native/blob/7da864284997109a37bbef739289c5e6e8d0514e/jest/mockComponent.js

**Comment by msand** [comment]
In case anyones interested, I managed to get x86 and x86_64 android images running on travis using the latest android emulator canary, which now works in headless mode without hardware acceleration / kvm support: https://travis-ci.org/msand/test_emulators/builds/502382369

**Comment by msand** [comment]
Got android working on bitrise now as well: https://app.bitrise.io/build/c31c1a40907cd137

**Comment by msand** [comment]
Btw, have you looked at these?
https://github.com/react-native-community/react-native-svg/issues/198

https://gist.github.com/JCMais/8302a1646ccc9759237947a66bdda8e0

https://github.com/FormidableLabs/react-native-svg-mock

**Comment by msand** [comment]
Closing, as it seems to work fine even without mocking now: https://github.com/msand/VariableFontWeightAnimation/commit/7d87235c5d38e01a37bd3592e794acfa3e235b93

**Comment by kopax** [comment]
I am still having issue to configure expo sdk 36 and this module with jest  (see  #1235)
