### ISSUE TITLE
Update SVG width and height

### ISSUE THREAD

**Issue by telekid** [react-native-community/react-native-svg#93]
`Svg` elements don't seem to update when width / height properties change. Is it possible to resize an `Svg` element?

New to React/Native, so I might be missing something obvious.

**Comment by matiascba** [comment]
Check the viewBox property of SVG

**Comment by ephemer** [comment]
@matc4 thanks for the suggestion to use viewBox. This worked for me to an extent, but when the height / width update, the Svg doesn't stay in proportion. If the Svg is then rendered anew given the new constraints, the Svg renders with the correct aspect ratio. Is this a bug, or is there a feature I'm missing?


            <Svg style={{ flex: 1 }} viewBox="0 0 367 384">
                <GradientDefinitions />
                <AGroupOfPaths />
            </Svg>

I couldn't get the Svg aspect ratio to correct itself with `this.forceUpdate();` either

**Comment by vovkasm** [comment]
Try to play with `preserveAspectRatio` property of `Svg` element.

**Comment by msand** [comment]
I have a PR fixing this: https://github.com/react-native-community/react-native-svg/pull/596

**Comment by msand** [comment]
Seems fixed, closing.
