### ISSUE TITLE
Display attribute not working as expected on SVGs

### ISSUE THREAD

**Issue by Joktaii** [react-native-community/react-native-svg#931]
I'm currently using the react-native-svg library and I've noticed that the display attribute seems to behave differently across the native platforms when utilized with SVG's.

When setting the display attribute of a parent view to none: `display = "none"` the SVG moves to the top left-hand side, and remains visible on Android. However, in iOS, the SVG behaves as expected and is hidden.

### Android 
<img width="340" alt="screenshot 2019-02-11 at 11 43 09" src="https://user-images.githubusercontent.com/45260516/52561093-4ab19b80-2df2-11e9-8f0d-f6bb3fcc0880.png">

display attribute not set.

<img width="341" alt="screenshot 2019-02-11 at 11 31 37" src="https://user-images.githubusercontent.com/45260516/52560572-a8dd7f00-2df0-11e9-93ce-d2a749dba901.png">

`display = "none"`

### iOS

<img width="409" alt="screenshot 2019-02-11 at 11 43 19" src="https://user-images.githubusercontent.com/45260516/52561197-92382780-2df2-11e9-88c1-5dfd20c8f37b.png">

display attribute not set.

<img width="414" alt="screenshot 2019-02-11 at 11 31 49" src="https://user-images.githubusercontent.com/45260516/52561207-9fedad00-2df2-11e9-8c9a-fbd967a43828.png">

`display = "none"`

### Code

```jsx
import React, {Component} from "react";
import { StyleSheet, Text, View} from "react-native";
import SvgFootballUk from "./FootballUK"

const Home = () => {
  return(

    <View >

        <Text style = {styles.text}> Testing display attribute </Text>

        <Text style = {styles.text}> everything visible </Text>

        <View style = {styles.svg} >

        <SvgFootballUk  />

        </View>
    </View>
  )
}

export default class App extends Component {
  render() {
    return (

      <View style={styles.container} >

        <Home/>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },

text: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },

  svg: {
    alignItems: 'center',
  }
});
```

**Comment by msand** [comment]
@Joktaii It seems to work fine in the latest version at least, what versions are you using?
https://github.com/msand/RN059/commit/720be5fa4538da8c695a989044ba6a4d142421c0
```jsx
import React, { Component, useState } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { Svg, Path } from 'react-native-svg';

function SvgTest() {
  return (
    <Svg height="100%" width="100%" viewBox="0 0 100 100">
      <Path d="M0,0 L100,100" stroke="black" />
    </Svg>
  );
}

const Home = () => {
  const [display, setDisplay] = useState('flex');
  return (
    <View>
      <TouchableOpacity
        onPress={() => setDisplay(display === 'flex' ? 'none' : 'flex')}
      >
        <Text style={styles.text}> Testing display attribute </Text>
      </TouchableOpacity>
      <View style={[styles.svg, { display }]}>
        <SvgTest />
      </View>
    </View>
  );
};

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Home />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 50,
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  text: {
    color: '#333333',
  },
  svg: {
    alignItems: 'center',
  },
});

```

**Comment by Joktaii** [comment]
Sorry for the delay in response, hopefully, the information provided below should answer any questions about what versions I am using in the project.

{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-svg": "^9.2.3",
    "react-native-svg-icon": "^0.8.1"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

If not please let me know, thank you.

**Comment by msand** [comment]
@Joktaii Can you give a full reproduction? Or at least one which shows the buggy rendering.

**Comment by Joktaii** [comment]
Hopefully, this shows what you want to see. I have it initially starting with the display property being visible and I then change it to none.

![svg demo](https://user-images.githubusercontent.com/45260516/53030472-c222a300-3462-11e9-9a51-8a770a92dcee.gif)

**Comment by msand** [comment]
I was thinking more in terms of code, could you copy paste the code you used for that video?

**Comment by Joktaii** [comment]
Sure, sorry for the misunderstanding. Though the code is practically the same code I gave within my initial comment.

import React, {Component} from 'react';
import { StyleSheet, Text, View} from 'react-native';
import SvgFootballUk from "./FootballUK"

const Home = () => {
 return(

    <View 
    display = "none"
    >
        <Text style = {styles.text}> Testing display attribute </Text>
        <Text style = {styles.text}> everything visible </Text>
        <View style = {styles.svg} >
        <SvgFootballUk  />
        </View>
    </View>
  )
}

export default class App extends Component {

  render() {
    return (

      <View style={styles.container} >
        <Home/>
      </View>
    );
  }
}`

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },

  text: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },

  svg: {
    alignItems: 'center',
  }
});


Apologies about the formatting, for some reason it doesn't seem to like it when I try to insert a large amount of code.
