### ISSUE TITLE
Too few elements in array (expected at least 5)

### ISSUE THREAD

**Issue by JulianKingman** [react-native-community/react-native-svg#932]
In the latest rnsvg (9.2.4), I get this error. Tracing the error, it appears that the RNSVGCGColor function expects an array of 5+ elements for the color, but the extractBrush (extractColor) function returns an array of length 2.

For example, if I provide a stroke color (`stroke: "rgba(0, 0, 0, 0.3)"`), the extractBrush returns `[0, 1291845632]`, leading to the below screenshot.

![simulator screen shot - iphone x - 2019-02-12 at 10 57 53](https://user-images.githubusercontent.com/1566400/52648806-1c48c480-2eb5-11e9-81cf-7ed79faae092.png)

**Comment by JulianKingman** [comment]
Looks like it's probably related to this commit: https://github.com/react-native-community/react-native-svg/commit/1c518c98960629dd9fc81d8ec89b3229f68bf108

**Comment by msand** [comment]
Can you try rebuilding your native bundle? The changes to the js and native logic were done in sync. This means you must be using old native or js logic with new native or js logic to be able to get this type of error. (new js with old native obj-c code in this case)

**Comment by Limycuk** [comment]
i have the same issue with version 9.2.4
i remove application from emulator and removed react-native-svg from node_modules after that i tried to fix by:

npm install
npm start -- --reset-cache
react-native run-ios

but i've got the same error

**Comment by msand** [comment]
Can you open the project in xcode, clean the build, and build again? Seems your native code didn't update

**Comment by JulianKingman** [comment]
I think my issue is related to expo/expokit. It doesn't update the native dependencies. I thought I could work around it, but it looks like I was wrong...

**Comment by Limycuk** [comment]
clean build doesn't help
we are migrated to cocoapods project and bug resolved

**Comment by Carnage4Life** [comment]
This issue was closed without a solution. How does one resolve this issue if using Expo?

**Comment by msand** [comment]
You use the version of react-native-svg that comes built into expo. And if you need a newer version, you either eject from expo or request them to upgrade the dependency.

**Comment by alphashuro** [comment]
I am having this issue, and I am working on an ejected project. Cleaning the build in XCode did not help.

**Comment by msand** [comment]
Try removing your node_modules, clear caches, install, and run again.

**Comment by willmanio** [comment]
I can confirm that this issue is resolved by cleaning and re-building the iOS app after upgrading. Removing `node_modules` isn't enough; you need to remove _all_ iOS build output. `git clean -fdx` is the nuclear approach, but there are gentler options. 😄

**Comment by dwilt** [comment]
For those of you who can upgrade (not using Expo), the only _full proof_ way for us that worked was following these _exact steps_:

1. Close Xcode
2. Delete app from phone
3. Re-clone the repo
4. Run `yarn` in root
5. `cd ios; pod install --repo-update`
6. Start packager with `npm run start -- --reset-cache`
7. Open project in Xcode (remember to open the `.xcworkspace` and NOT the `.xcodeproj`)
8. Clean (cmd-shift-k)
9. Build (cmd-r)
10. Pray to Xcode
11. Celebrate

**Comment by ngnclht1102** [comment]
> For those of you who can upgrade (not using Expo), the only _full proof_ way for us that worked was following these _exact steps_:
> 
> 1. Close Xcode
> 2. Delete app from phone
> 3. Re-clone the repo (I said it would work - not be short and sweet)
> 4. Run `yarn; cd ios; pod install --repo-update; cd ..; npm run start -- --reset-cache` in root of project
> 5. Open project in Xcode (remember to open the `.xcworkspace` and NOT the `.xcodeproj`)
> 6. Clean (cmd-shift-k)
> 7. Build (cmd-r)
> 8. Pray to Xcode
> 9. Celebrate

worked perfect for me. Thanks man!

**Comment by martsie** [comment]
Having the same issue with 9.4, tried everything in this thread. Reverted to 8.0.11 and it's working again. Error was even occurring with a blank SVG element with no components in it and no colors defined.

**Comment by msand** [comment]
This can only happen if you had upgraded either the js or native code, but not the other. The clearing builds/caches/node modules, reinstall, rebuild, and try again.

**Comment by gianpaj** [comment]
After upgrading and running `pod install`, I had forgotten to rebuild/reinstall the ios app with `react-native run-ios`.
Now I don't see the error any more :)

**Comment by spacesuitdiver** [comment]
I'm having this same error, from a clean install upgrading from 8.0.10 -> ^9.13.2 I was thinking it was from my .svg even and the homer example looks like this. Any more fullproof way of determining if it really is a .js vs. native code incompatibility/upgrade issue?

![image](https://user-images.githubusercontent.com/2807897/67598522-5308f700-f733-11e9-9c28-e1c7e0409922.png)

**Comment by msand** [comment]
@spacesuitdiver Make a clean project and try there: https://github.com/react-native-community/react-native-svg#unexpected-behavior

react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..

Make a reproduction of the problem in App.js

react-native run-ios
react-native run-android

**Comment by spacesuitdiver** [comment]
Well, I can confirm it's something related to my project using only my Podfile it works fine in a new RN project on 0.59.10... 

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CleanProj' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
end
```

Will keep poking around.

**Comment by spacesuitdiver** [comment]
For those of you who might have ran into this, I did a few things to ultimately get the RNSvg product to recompile, I have no idea where or how it was cached, it's rather frightening honestly.

- If you are on legacy build system switch to new build system in workspace settings
- For fun because I was going to debug the package I added RNSvg I added it to my scheme to build AT THE TOP like so, your product will be below.
![image](https://user-images.githubusercontent.com/2807897/67709349-c6a54100-f98b-11e9-8dd4-954358ed51e7.png)

**Comment by mitevdev** [comment]
I had the same issue and the problem was that the class Text was imported from svg module and not from "react-native"

**Comment by freddygarcia** [comment]
> For those of you who can upgrade (not using Expo), the only _full proof_ way for us that worked was following these _exact steps_:
> 
> ....
> 8. Pray to Xcode
> ...

i don't have proof but neither have doubts about this step.
