### ISSUE TITLE
How do put text content inside the rect?

### ISSUE THREAD

**Issue by lanreng** [react-native-community/react-native-svg#942]
version:
   react-native   0.55.4
   react-native-svg 6.0.0 

           <Rect width="40" height="40" fill="blue" />
            <Text
              textAnchor="middle"
              fontWeight="bold"
              fontSize="16"
              fill="blue">
              0
            </Text>

How do put text content inside the rect? 
like this
![data](https://user-images.githubusercontent.com/47716098/52914562-f1230280-3304-11e9-8738-6049114a44ef.png)

**Comment by lanreng** [comment]
@msand  my God   。。。use Defs？ How to do it, I just learned

**Comment by msand** [comment]
You mean something like this? https://snack.expo.io/@msand/spunky-coffee
You're probably just missing a y attribute on the Text element to place it where you wish:
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants, Svg } from 'expo';

const { Rect, Text } = Svg;

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg width="100%" height="100%" viewBox="0 0 100 20">
          <Rect width="100" height="20" fill="blue" />
          <Text
            x="50"
            y="16"
            fill="white"
            fontSize="16"
            fontWeight="bold"
            textAnchor="middle">
            0
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```
