### ISSUE TITLE
Is <Svg fill="..."> officially supported?

### ISSUE THREAD

**Issue by flsilva** [react-native-community/react-native-svg#943]
Hello,

First of all, thank you for your hard work on such an amazing library.

I'm looking for an easy way to color all SVG elements at once. My use case is one of the most common for SVGs: icons. When we work with third-party icons we don't have control over their internal structures, and to be honest, we don't care, do we? All we want to do is to render them, and (easily) color them, all elements with a same color. So most of the times we don't want to have to use fill on each internal SVG element (`<Path>`, `<Circle>`, etc). That'd also prevent us to create a simple and reusable way to change the color of the elements, since each SVG can have its own internal structure. Multicolor icons are a different story though, but they are rare and demands a custom manipulation anyway.

I tried doing `<Svg fill="#FF0000">` on some third-party SVG icons and it does work, i.e., everything is filled with such color. I've tested with icons that have only a single `<Path>`, but also multiple `<Circle>`, and `<Path>` and `<Circle>`. All of them seems to work correctly, i.e., all elements are colored, except the ones that have themselves a fill prop, which is expected to take precedence over a `fill` on the root `<Svg>` anyway.

So my question is: is it officially supported by react-native-svg? Or is there any other way to do that?

AFAIK the current docs only show the use of the `fill` prop on SVG elements (`<Path>`, `<Circle>`, etc), but not on `<SVG>` component itself. So even though it does work, I'd like to make sure that it's officially supported. It seems to me that it should be (or something similar), for the reasons I mentioned above, but not sure about further implications.

If that's officially supported, it'd be great to make it explicit in the docs by having at least one example of it. The other required change I can see would be to add `fill?: string` to `SvgProps` TypeScript type. I'd be glad to send a PR with such changes if that's officially supported. Otherwise, could we get clarifications on why that's not officially supported, even though it works as expected? Or if there's a different way to achieve the same thing?

Thank you for your time.

**Comment by msand** [comment]
Thanks! Sure, same as on the web ideally. So, additionally you can use currentColor in the fill and stroke attribute of the elements and set it using the color attribute of the root Svg element, so you can have a global stroke and fill, plus a third tint/currentColor for context dependent / themable parts. Additionally you can create react components with normal prop overrides, render props etc.

React web: https://codesandbox.io/s/10qm4kozw7
```jsx
import React from "react";
import ReactDOM from "react-dom";
import { View, StyleSheet } from "react-native";

import { Svg, Path } from "swgs";
import "./styles.css";

const Icon = props => (
  <Svg
    title="pencil"
    width="20"
    height="20"
    fill="blue"
    stroke="red"
    color="green"
    style={{
      alignSelf: "center"
    }}
    viewBox="-16 -16 544 544"
    {...props}
  >
    <Path
      d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
      strokeWidth="32"
    />
    <Path d="M0,0L512,512" stroke="currentColor" strokeWidth="32" />
  </Svg>
);

function App() {
  return (
    <View style={styles.container}>
      <Icon width="100%" height="100%" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 8
  }
});

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

Snack: https://snack.expo.io/@msand/forlorn-raisins
```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

import { Svg, Path } from 'swgs';

const Icon = props => (
  <Svg
    title="pencil"
    width="20"
    height="20"
    fill="blue"
    stroke="red"
    color="green"
    style={{
      alignSelf: 'center',
    }}
    viewBox="-16 -16 544 544"
    {...props}>
    <Path
      d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
      strokeWidth="32"
    />
    <Path d="M0,0L512,512" stroke="currentColor" strokeWidth="32" />
  </Svg>
);

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Icon width="100%" height="100%" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});
```

Vanilla web: https://codesandbox.io/s/0y810wkvpn
```html
<div style="display: flex; height: 100vh; flex-direction: column; background-color: #ecf0f1; padding: 8">
  <svg
    title="pencil"
    x="0"
    y="0"
    width="100%"
    height="100%"
    fill="blue"
    stroke="red"
    color="green"
    style="align-self: center"
    viewBox="-16 -16 544 544"
  >
    <path
      d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
      stroke-width="32"
    />
    <path d="M0,0L512,512" stroke="currentColor" stroke-width="32" />
  </svg>
</div>

```

PRs with Improvements to the documentation would be greatly appreciated!

**Comment by msand** [comment]
<img width="405" alt="screen shot 2019-02-17 at 22 39 32" src="https://user-images.githubusercontent.com/1131362/52918871-f4b68980-3304-11e9-8ef7-18b9c71ea6ed.png">

**Comment by flsilva** [comment]
Thank you for your quick response.

That's great, also thanks for the examples, that answers my question. I'll make some time to send a PR to update the docs (`README.md`). I think I can use your pencil draw (code and screenshot), it's a great example to showcase how `color`, `fill` and `stroke` can be used. Sounds good?

I'm using TypeScript, so I want to send another PR to update types since I get type errors when I try to run your examples. I can see some things missing, and I could add them locally to test and get your pencil example working without TypeScript errors, but I'm not sure what other props the Svg component accepts, could you help me figure that out, so that we can have a more complete type?

This is the current `SvgProps` in this repo:

```
export interface SvgProps extends ReactNative.ViewProperties {
  width?: NumberProp,
  height?: NumberProp,
  viewBox?: string,
  preserveAspectRatio?: string,
}
```

As you can see, aside the props it extends from ReactNative's `ViewProps`, it just defines those four props. Based on your examples, I can see other non defined props that are also supported, so we could have something like this:

```
export interface SvgProps extends ReactNative.ViewProperties {
  width?: NumberProp,
  height?: NumberProp,
  viewBox?: string,
  preserveAspectRatio?: string,
  color?: int32ARGBColor | rgbaArray | string,
  fill?: int32ARGBColor | rgbaArray | string,
  stroke?: int32ARGBColor | rgbaArray | string,
  title?: string,
}
```

But now I'm curious, does the Svg component support all `FillProps`? This is what it looks like:

```
export interface FillProps {
  fill?: int32ARGBColor | rgbaArray | string,
  fillOpacity?: NumberProp,
  fillRule?: FillRule,
}
```

If so, we could have something like:

```
export interface SvgProps extends FillProps, ReactNative.ViewProperties {
  width?: NumberProp,
  height?: NumberProp,
  viewBox?: string,
  preserveAspectRatio?: string,
  color?: int32ARGBColor | rgbaArray | string,
  stroke?: int32ARGBColor | rgbaArray | string,
  title?: string,
}
```

And the same question for stroke: does the Svg element support all StrokeProps? This is what it looks like:

```
export interface StrokeProps {
  stroke?: int32ARGBColor | rgbaArray | string,
  strokeWidth?: NumberProp,
  strokeOpacity?: NumberProp,
  strokeDasharray?: ReadonlyArray<NumberProp> | NumberProp,
  strokeDashoffset?: NumberProp,
  strokeLinecap?: Linecap,
  strokeLinejoin?: Linejoin,
  strokeMiterlimit?: NumberProp,
}
```

If so, we could have something like:

```
export interface SvgProps extends FillProps, StrokeProps, ReactNative.ViewProperties {
  width?: NumberProp,
  height?: NumberProp,
  viewBox?: string,
  preserveAspectRatio?: string,
  color?: int32ARGBColor | rgbaArray | string,
  title?: string,
}
```

I'm not very proficient in SVG, so it's possible that the types might be further improved, but I believe those changes would improve the TypeScript experience a lot when working with `react-native-svg`. I can create a PR after we clarify those points.

Thanks.

**Comment by msand** [comment]
Sounds good. Yeah, it supports the stroke, fill, color and additionally onLayout, opacity, transform, inherited font and style. The style property should allow setting default text properties as well, (but I haven't tested it properly):

https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/elements/Svg.js#L58-L90

https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/elements/Svg.js#L112-L144

https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/elements/G.js#L20-L26

https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/lib/extract/extractText.js#L47-L59

https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/lib/extract/extractText.js#L107-L109

**Comment by msand** [comment]
Oh, and the Touchable / PanResponder props: https://github.com/react-native-community/react-native-svg/blob/be6a517029de9a26a796139b641349571944bd7c/lib/extract/extractResponder.js#L1-L16

**Comment by msand** [comment]
The title attribute is only supported by svgs and swgs on the web for now. On native it doesn't do anything at the moment.

**Comment by msand** [comment]
Essentially, anything you can do with a G element + the color, width, height, viewBox, preserveAspectRatio attributes.

**Comment by flsilva** [comment]
Awesome! That clarifies a lot, and should result in the best solution I guess, which is changing `SvgProps` to extend `GProps` like this:

```
export interface SvgProps extends GProps, ReactNative.ViewProperties {
  width?: NumberProp,
  height?: NumberProp,
  viewBox?: string,
  preserveAspectRatio?: string,
  color?: int32ARGBColor | rgbaArray | string,
  title?: string,
}
```

I'm gonna send a PR.
