### ISSUE TITLE
Limit height on android

### ISSUE THREAD

**Issue by datvudang** [react-native-community/react-native-svg#946]
I have a SvgView with height depend on a list of item. Height may be more than 4~5000. Everything works well on iOs but the view disappeared on android.
I had try on snack with react-native-svg-example. Still not works on android.

Example code: 
```
class SvgExample extends Component{
    static title = 'SVG';
    render() {
        return <Svg
            height="3000"
            width="100"
        >
            <Circle
                cx="50"
                cy="50"
                r="45"
                stroke="blue"
                strokeWidth="2.5"
                fill="green"
            />
            <Rect
                x="15"
                y="0"
                width="70"
                height="3000"
                stroke="red"
                strokeWidth="2"
                fill="yellow"
            />
        </Svg>;
    }
}
```

I test on android version 6.0.1

**Comment by msand** [comment]
I would recommend limiting the size of the Svg root element to the size fo the native screen resolution, and use native animation of transforms using a ScrollView instead, like this: https://snack.expo.io/@msand/efficient-transform-of-large-svg-surfaces

```jsx
import React from 'react';
import { StyleSheet, View, Animated, Dimensions } from 'react-native';
import { Svg, G, Rect } from 'react-native-svg';

const AnimatedG = Animated.createAnimatedComponent(G);

const { width, height } = Dimensions.get('window');

// Choose the amount of available viewport you want for scrolling here
const scrollHeight = height * 3;

const styles = StyleSheet.create({
  scroll: {
    height: scrollHeight,
    width,
  },
  absolute: {
    position: 'absolute',
  },
  container: {
    flex: 1,
  },
});

class ScrollSvg extends React.PureComponent {
  render() {
    const { y } = this.props;
    return (
      <Svg
        width={width}
        height={height}
        viewBox="0 0 100 100"
        style={styles.absolute}
        preserveAspectRatio="xMidYMin meet">
        <AnimatedG
          style={{
            transform: [
              {
                translateY: y.interpolate({
                  inputRange: [0, height],
                  outputRange: [0, -100],
                }),
              },
            ],
          }}>
          <Rect y={0} height="100" width="100" fill="red" />
          <Rect y={120} height="100" width="100" fill="green" />
          <Rect y={240} height="100" width="100" fill="blue" />
        </AnimatedG>
      </Svg>
    );
  }
}

export default class App extends React.Component {
  state = {
    y: new Animated.Value(0),
  };
  render() {
    const { y } = this.state;
    return (
      <View style={styles.container}>
        <ScrollSvg y={y} />
        <Animated.ScrollView
          scrollEventThrottle={16}
          onScroll={Animated.event(
            [
              {
                nativeEvent: {
                  contentOffset: { y },
                },
              },
            ],
            { useNativeDriver: true }
          )}>
          <View style={styles.scroll} />
        </Animated.ScrollView>
      </View>
    );
  }
}

```

It seems to crash on Expo when using Android. But works fine with the latest react-native and react-native-svg versions at least.

Do you think this can cover your needs?

**Comment by AdamGerthel** [comment]
Update: I've tried the solution proposed here, i.e. to animate a group within the SVG instead, such as:

```javascript
<View
  {...this._panResponder.panHandlers}>
  <Svg.Svg
    width={deviceSize.width}
    height={deviceSize.height}
    viewBox={`0 0 ${deviceSize.width} ${deviceSize.height}`}
    preserveAspectRatio="xMidYMid slice">
    <AnimatedGroup
      style={{
        transform: [
          { translateX: center.pan.x.interpolate(reversed) },
          { translateY: center.pan.y.interpolate(reversed) }
        ]
      }}>

    <-- Misc SVG stuff goes here -->
    
    </AnimatedGroup>
  </Svg.Svg>
</View>
```
But this causes new issues on Android, such as flickering:
![ezgif-4-5af7c034f499](https://user-images.githubusercontent.com/1490370/64862407-baab2d00-d632-11e9-8d99-fa56567c7a6a.gif)

**Comment by msand** [comment]
If the content inside the svg doesn't change when you pan around, then you shouldn't rerender it. transform the containing view / svg root instead.

**Comment by AdamGerthel** [comment]
@msand Right - which is exactly what I [initially did](https://github.com/react-native-community/react-native-svg/issues/946#issuecomment-531005339). But then the svg needs to be bigger than the screen, which causes the bug that this issue is about, i.e. in my case that some areas of the svg becomes un-clickable on Android. I tried [this solution](https://github.com/react-native-community/react-native-svg/issues/946#issuecomment-531217893) because it was suggested in this thread.

**Comment by msand** [comment]
If you have an animated transform inside the svg root, then you're re-rendering (at least on the native side). Not sure why it's flickering though. Hard to help / make any progress, without a full reproduction.

**Comment by msand** [comment]
@AdamGerthel Could you open a new issue for the flickering, including a full reproduction I can git clone, npm install, react-native run-android, and see the issue without any further work?

**Comment by AdamGerthel** [comment]
@msand Sure, I should be able to reproduce it. Would an Expo Snack work?

**Comment by msand** [comment]
@AdamGerthel Sure, as long as it demonstrates the issue without any extra setup.
