### ISSUE TITLE
Horizontal gradient 

### ISSUE THREAD

**Issue by avet-m** [react-native-community/react-native-svg#952]
HI.
I am trying to create horizontal gradient without  smoothy transition

Smth like this 
<img width="107" alt="screenshot 2019-02-25 at 16 51 18" src="https://user-images.githubusercontent.com/16869204/53341829-a6654400-391d-11e9-9928-75dac1519872.png">

When I set equal values for offsets of second and third stop(e.g 50%), I see only black rectangle
If I set for second stop 49% and for third 50% It works, but is not exactly what i need, because the dividing line is fuzzy
<img width="168" alt="screenshot 2019-02-25 at 16 24 33" src="https://user-images.githubusercontent.com/16869204/53340380-f2ae8500-3919-11e9-90c8-d3009754f8b3.png">

```
import React from 'react'
import Svg, { Defs, LinearGradient, Stop, Rect } from 'react-native-svg'

const SvgComponent = props => (
  <Svg width={200} height={200} {...props}>
    <Defs>
      <LinearGradient id="prefix__a" x1="0%" y1="0%" x2="100%" y2="0%">
        <Stop offset="0%" stopColor="silver" />
        <Stop offset="50%" stopColor="silver" />
        <Stop offset="50%" stopColor="black" />
        <Stop offset="100%" stopColor="black" />
      </LinearGradient>
    </Defs>
    <Rect width="100%" height="100%" fill="url(#prefix__a)" />
  </Svg>
)

export default SvgComponent
```

**Comment by msand** [comment]
How about
```jsx
        <Stop offset="0%" stopColor="silver" />
        <Stop offset={0.5} stopColor="silver" />
        <Stop offset={0.5 + Number.EPSILON} stopColor="black" />
        <Stop offset="100%" stopColor="black" />
```
Or just using two Rect elements?
