### ISSUE TITLE
Constructing a polygon with holes doesn't work if the coordinates are both in the same direction

### ISSUE THREAD

**Issue by kev71187** [react-native-community/react-native-svg#956]
When I draw the polygon in the same direction. IE clockwise clockwise. The resulting polygon fills both polygons.
![image](https://user-images.githubusercontent.com/2372855/53528317-473b3700-3ab7-11e9-9e54-d66eb5670657.png)

```
const bothClockwise = "M 0 0 L 100 100  L 0 100 L 0 0 Z M 10 20 L 30 50 L 10 50 L 10 20 Z" // bad
        <Path
            d={bothClockwise}
            fill="rgba(255,255,255,.40)"
            stroke="white"
            strokeWidth={size/4}
          />

```

When I construct a polygon with path with two polygons and each polygon rotates in a different direction the result is as expected. The inside triangle stamps out the middle.
![image](https://user-images.githubusercontent.com/2372855/53528208-ead81780-3ab6-11e9-93a7-c6d06be692f4.png)
```
const oneCounterOneClockwise = "M 0 0 L 100 100  L 0 100 L 0 0 Z M 10 20 L 10 50 L 30 50 L 10 20 Z" // good
        <Path
            d={oneCounterOneClockwise}
            fill="rgba(255,255,255,.40)"
            stroke="white"
            strokeWidth={size/4}
          />

```

Did I run into a bug or an undocumented feature? Thanks.

**Comment by msand** [comment]
This is called the winding rule in vector based graphics, specifically the non-zero fill-rule in svg. There's also the even-odd value you might want to explore:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule
https://svgwg.org/svg2-draft/single-page.html#painting-WindingRule

https://oreillymedia.github.io/Using_SVG/extras/ch06-fill-rule.html
https://www.sitepoint.com/understanding-svg-fill-rule-property/

https://en.wikipedia.org/wiki/Nonzero-rule
https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule

**Comment by kev71187** [comment]
Awesome! thanks for the references
