### ISSUE TITLE
SVG's not loading when I render multiple times, React Native

### ISSUE THREAD

**Issue by Dellamoresteven** [react-native-community/react-native-svg#957]
I am currently trying to re-render a page a few times in react native, after the fourth or so re-render it stops showing the svg's.

Is anyone else having this problem and or have a solution??

My Dependencies 
    "expo": "^32.0.0",
    "http": "0.0.0",
    "react": "^16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-dialog": "^5.5.0",
    "react-native-dialog-input": "^1.0.7",
    "react-native-easy-grid": "^0.2.1",
    "react-native-elements": "^1.1.0",
    "react-native-pinch-zoom-view": "^0.2.0",
    "react-native-svg": "^9.2.4",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "2.5.2",
    "react-navigation-redux-helpers": "2.0.0",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1"

(On a side note if anyone has any good ideas on how to change the color of a <G> without having to re-render everything I would very much like to hear it!)

**Comment by saikiranoptisol** [comment]
@Dellamoresteven  how you have solved this

**Comment by Dellamoresteven** [comment]
@saikiranoptisol It was actually my fault, I was increasing my Screen Height of a ScrollView by 500 every time I re-rendered. Once that got to ~2000-3000 it broke. 

With that being said the amount I could increase my ScrollView by directly correlated with how many SVG's i was rendering. I have no idea why this was the case but I'm sure someone smarter then me could tell you.  

I recommenced you try to comment code out until you get the issue down to a couple of lines and see if you can fix it. 

Good Luck!
