### ISSUE TITLE
Rename "responsible" property to "interactive"

### ISSUE THREAD

**Issue by aleclarson** [react-native-community/react-native-svg#960]
I don't think the name `responsible` conveys what the property is for. I had to use `git blame` to figure it out from the related commit message. I see the old name used to be `touchable`, which I think is better, but perhaps `interactive` would be best? Another option is to use `userInteractionEnabled` (a property of `UIView`).

🚲 🏚

**Comment by msand** [comment]
I think responsible is a reference to GestureResponser / PanResponder, perhaps isActiveGestureResponder would be more descriptive. What do you think?
