### ISSUE TITLE
Build errors in android "facebook.infer.annotation"

### ISSUE THREAD

**Issue by liron-navon** [react-native-community/react-native-svg#961]
Steps to reproduce:
```
### setting a new project
expo init project # blank project
npm run eject # pick expoKit option

### installing react-native-svg
npm install --save react-native-svg
react-native link react-native-svg

### building with android studio
```

Errors
```
### java compiler error
error: package com.facebook.infer.annotation does not exist
```

If I uninstall react-native-svg, it works fine, if I use another native module like react-native-webview it works fine.

**Comment by msand** [comment]
@liron-navon Can you try with the latest version v9.3.1? It should be fixed there.

**Comment by pckz** [comment]
@msand @liron-navon I have the same error. How can I solve that? thnks
