### ISSUE TITLE
Use webp assets in Image component

### ISSUE THREAD

**Issue by yassinecc** [react-native-community/react-native-svg#963]
The following code results in a blank display on iOS:

```
import React from 'react';
import Svg, { Defs, ClipPath, Image, Path } from "react-native-svg";
import webpImage from "./image.webp"

export const Svg = ({ imageUrl, path }) => (
  <Svg height="96" width="98">
    <Defs>
      <ClipPath id="path">
        <Path d={path} />
      </ClipPath>
    </Defs>
    <Image href={webpImage} clipPath="url(#path)" width={98} height={96} x={-1} y={0} />
  </Svg>
);
```

Looking at native iOS code, I see that the image source is loaded with `RCTImageSource *source = [RCTConvert RCTImageSource:src];` with RCTConvert not supporting webp.

Is there a way to override this behaviour and use webp sources in SVG images?

**Comment by msand** [comment]
I haven't looked at webp support, have you tried any of these? https://github.com/TGPSKI/react-native-webp-support/network

**Comment by yassinecc** [comment]
@msand well we already support webp in our app with SDWebImage but I haven't tried tweaking react-native-svg's code if that's what you meant

**Comment by yassinecc** [comment]
@semantic-release-bot re open

**Comment by msand** [comment]
You can probably use SDWebImage together with ForeignObject by now
