### ISSUE TITLE
Dynamically import SVG components in container

### ISSUE THREAD

**Issue by farrukhhashmi65** [react-native-community/react-native-svg#970]
I have multiple SVG component which uses react native svgs with event binding and I want to include it in our main container App.js by matching names or anything like that. How can I do that ? 
It can be many so import all in one file and switch statements is not a good option.

**Comment by msand** [comment]
If you want actual dynamic import, check random access modules: https://facebook.github.io/react-native/docs/performance#ram-bundles-inline-requires

If you just want to render based on a key, either store them in a object / map, or use import * as MySvgCollection from "./svg"
And export each component as a named export in a index.js file in the svg folder. Then in render, get your component and return it,
const SvgComponent = MySvgCollection[this.props.svgName];
return <SvgComponent />

**Comment by farrukhhashmi65** [comment]
@msand Thanks, Can you please provide me any example of it

>  use import * as MySvgCollection from "./svg"
And export each component as a named export in a index.js file in the svg folder. Then in render, get your component and return it,

**Comment by msand** [comment]
Check here: https://snack.expo.io/@msand/playful-candies

**Comment by farrukhhashmi65** [comment]
@msand Thank you so much. But How can we achieve lazy loading (React.lazy) with this approach, What if we have large svgs components or more that 50 ?

**Comment by msand** [comment]
Can use random access modules, and a loading state, and a componentDidMount and/or onLayout to change state.

**Comment by rosnaib11** [comment]
I got error using * wildcard `none of these files exist` what is the right babel settings for this?

**Comment by aleksandarbos** [comment]
> Can use random access modules, and a loading state, and a componentDidMount and/or onLayout to change state.

is there a snack or something we can use as a reference? thanks

**Comment by Etaliya** [comment]
Here is my solution using `React lazy`


```
const Icon = () => {
  const name = 'imageSparkle.svg';

  const LazySVG = React.lazy(() =>
    import(`../assets/icons/${name}`).then(module => ({
      default: module.default,
    })),
  );
  return (
    <Suspense>
      <LazySVG />
    </Suspense>
  );
};

export default Icon;
```
