### ISSUE TITLE
Dynamic paths within <G> don't update

### ISSUE THREAD

**Issue by ingmaras** [react-native-community/react-native-svg#973]
### The Issue
When `<G>` contains a `<Path>` and the path is dynamically changed, the path does not rerender.

In the following code, when `toggle` is changed, the path is meant to become longer.
```js
        <Text>With G</Text>
        <Svg style={styles.svg}>
          <G>
            <Path d={toggle ? 'M25 10 L98 65 L70 25 L16 77' : 'M25 10 L98 65'} fill="none" stroke="red" strokeWidth={5} />
          </G>
        </Svg>

        <Text>Without G</Text>
        <Svg style={styles.svg}>
          <Path d={toggle ? 'M25 10 L98 65 L70 25 L16 77' : 'M25 10 L98 65'} fill="none" stroke="red" strokeWidth={5} />
        </Svg>
```

However, this only happens in the second `Svg`, which does not use `<G>`. 

![Simulator Screen Shot - iPhone X - 2019-03-18 at 06 55 35](https://user-images.githubusercontent.com/2716710/54512459-2e9e9e00-494c-11e9-81fd-7d267996b6c5.png)

### Environment
Platform: iOS (12.1) only. Tested on Android and everything worked fine.
React Native version: latest (0.59.1)
react-native-svg: latest (9.3.3)

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 143.14 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
```

### Code to reproduce
[Link to app that reproduces the issue.](https://github.com/ingmaras/react-native-svg-charts-issue/blob/svg/App.js)

Possibly related to https://github.com/react-native-community/react-native-svg/issues/111

**Comment by andriinegustorov** [comment]
+1

**Comment by msand** [comment]
I think I've fixed this now, can you try with v9.2.4 ?

**Comment by ingmaras** [comment]
Just tried it and it indeed has been fixed. Thanks so much @msand!

**Comment by ZeeshanAhmadKhalil** [comment]
still getting this issue in `12.1.1`

**Comment by zhiqingchen** [comment]
same issue in `12.4.4`, but only android
