### ISSUE TITLE
transform prop not working

### ISSUE THREAD

**Issue by srfaytkn** [react-native-community/react-native-svg#974]
svg transform prop not working

**Comment by msand** [comment]
Can you make a reproduction with v9.2.4 ?

**Comment by srfaytkn** [comment]
I'm already using version 9.2.4.

**Comment by msand** [comment]
Repro?

**Comment by srfaytkn** [comment]
yes I tried but still not working.

**Comment by F-Moody** [comment]
Same here, trying to apply zoom to the svg (with uri source)

**Comment by msand** [comment]
I cannot help unless you provide the code that is failing... Do you imagine how your statements look for other people? One more useless reply and I'm closing this issue.

**Comment by F-Moody** [comment]
In my case it was my fault, i was passing transform as a prop, now i've just put it on the style prop and it's working.

`<SvgUri
                        width="400"
                        height="400"
                        source={{uri: 'http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg'}}
                        style={{
                            transform: [
                                {translateX: left * resolution},
                                {translateY: top * resolution},
                                {scale: zoom},
                            ]
                        }}
                    />`

Anyway performance wise is a bit laggy in comparison with a webview with same uri and same transform applied (i've set a pan responder on the parent's view).
