### ISSUE TITLE
Changing the opacity of a G-element

### ISSUE THREAD

**Issue by BabakSamimi** [react-native-community/react-native-svg#975]
Greetings, I have a small problem related to updating the opacity-attribute of a G-element. However, this is not done via regular elements. Instead, I'm using the react-native-svg-transformer to show my SVG.

Using:
"react": "16.8.3",
"react-native": "0.59.1"
"react-native-svg": "9.3.5"
"react-native-svg-transformer": "^0.12.1"

```
import Logo from './queue.svg';

....

render() {
    return(
    ...
    <Logo width="100%" height="100%">
    );
}
```

I'm not able to reveal what's inside the SVG-file due to NDA, however, I can give an example that looks like this:
```
<svg>
    <g id="overview">
        <g id="pos0">
          ...
        </g>
    </g>
</svg>
```

The question is: How do I change the opacity of the G-element with the id="pos0" in this example?

Thanks in advance.

**Comment by msand** [comment]
Convert it to a react component using https://svgr.now.sh and set the value using the props.
