### ISSUE TITLE
SVG tree is not re-rendering on iOS platform

### ISSUE THREAD

**Issue by oleksandr-dziuban** [react-native-community/react-native-svg#976]
@msand Hi, just noticed in all latest versions that SVG tree is only rendering once. If we have dynamic behaviour (with Redux or even with local state) SVG tree will not be re-rendered on iOS. Android works fine as expected.

On version 9.2.4 everything is OK, on latest 9.3.5 issue is present on iOS.

I have:
react-native: 0.57.7
react-native-svg: 9.3.5
MacOS: 10.14.3
Xcode: 10.1

To reproduce it use:

``` js-jsx
import React, { Component } from 'react';
import Svg, { Image, G, Text }  from 'react-native-svg';

class App extends Component {
  state = {
    uri: undefined,
    testText: 'no text',
  };

  componentDidMount() {
    setTimeout(() => {
      this.setState(() => ({
        uri: 'https://i.kinja-img.com/gawker-media/image/upload/s--PnSCSSFQ--/c_scale,f_auto,fl_progressive,pg_1,q_80,w_800/z7jcryloxjedsztssw39.jpg',
        testText: 'DONE!'
      }))
    }, 3000);
  }

  render() {
    return (
      <Svg width='400' height='400'>
        <G>
          <Text x='20' y='60'>TEST TEXT</Text>
        </G>
        <G>
          <Text x='20' y='80'>{this.state.testText}</Text>
        </G>
        <G>
          <Image x='0' y='100' width='400' height='400' href={{ uri: this.state.uri || '' }} />
        </G>
      </Svg>
    )
  }
}
```

**Comment by BabakSamimi** [comment]
Shouldn't it look like this?

```
import React, { Component } from 'react';
import Svg, { Image, G, Text }  from 'react-native-svg';

class App extends Component {
constructor(props) {
 super(props);
  this.state = {
    uri: undefined,
    testText: 'no text',
  };
} 


  componentDidMount() {
    setTimeout(() => {
      this.setState(() => ({
        uri: 'https://i.kinja-img.com/gawker-media/image/upload/s--PnSCSSFQ--/c_scale,f_auto,fl_progressive,pg_1,q_80,w_800/z7jcryloxjedsztssw39.jpg',
        testText: 'DONE!'
      }))
    }, 3000);
  }

  render() {
    return (
      <Svg width='400' height='400'>
        <G>
          <Text x='20' y='60'>TEST TEXT</Text>
        </G>
        <G>
          <Text x='20' y='80'>{this.state.testText}</Text>
        </G>
        <G>
          <Image x='0' y='100' width='400' height='400' href={{ uri: this.state.uri || '' }} />
        </G>
      </Svg>
    )
  }
}
```

**Comment by oleksandr-dziuban** [comment]
@BabakSamimi You just changed state initialization from class property to constructor based. It is the same. Android app work correctly with my code, just iOS SVG tree doesn't re-render

**Comment by BabakSamimi** [comment]
Right, my bad, I'm new to this React/JS world. However, I do want to state that I'm facing the same issue. My SVG-tree won't re-render after a call to setState either. I'm currently trying to solve it by wrapping my SVG-tree in a component and update it from a parent-component.

**Comment by oleksandr-dziuban** [comment]
@BabakSamimi Yeah, this issue is present in a few latest versions. If I try 9.2.4 it's OK.
I have a production application with very complex SVG tree and a lot of components, so for me it will not work just to wrap parent component. I think something was broken in latest version and can be fixed quickly. We just need Mr @msand to help us :)

**Comment by BabakSamimi** [comment]
I also have a somewhat complex SVG tree but downgrading to 9.2.4 works wonders for me, thank you. Hopefully this will be hotfixed soon.

**Comment by MeisterTea** [comment]
Same here !

**Comment by oleksandr-dziuban** [comment]
@BabakSamimi @MeisterTea @msand Interesting case I found with iOS app: if I install react-native v0.59.1 - SVG tree re-renders correctly in iOS app

**Comment by BabakSamimi** [comment]
I use react-native v0.59.1, maybe it has to do with older RN? I can only guess.

**Comment by oleksandr-dziuban** [comment]
@BabakSamimi Yep, you are right, it doesn't work on latest react-native@0.59.1 too.

**Comment by msand** [comment]
Hmm, seems to work fine for me with react-native@0.59.1 and react-native-svg@9.3.5 and iPhone XR 12.1 simulator. Can you make a reproducible git repo?

**Comment by msand** [comment]
![Simulator Screen Shot - iPhone XR - 2019-03-21 at 01 35 49](https://user-images.githubusercontent.com/1131362/54725976-b0bfda00-4b79-11e9-8692-a931376c6610.png)

**Comment by BabakSamimi** [comment]
Upgraded back to 9.3.5 with RN v0.59.1 and it still works.

It seems like the error was from my side, which I later corrected.

**Comment by oleksandr-dziuban** [comment]
@msand Yes, sorry, it works fine now, I just clear all the npm/react-native-* cache and it works now.
Just issue with text remaining. I have added steps to reproduce here: https://github.com/react-native-community/react-native-svg/issues/570#issuecomment-474649116

Please close this issue.
