### ISSUE TITLE
None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by adirzoari** [react-native-community/react-native-svg#979]
Hey,
I get error when I try to run my project after installing react-native-svg
`Unable to find a matching configuration of project :react-native-svg: None of the consumable configurations have attributes.`

info:
```
 "react": "16.6.3",
  "react-native": "0.57.8",
  "react-native-svg": "^9.3.6",

```

**Comment by msand** [comment]
Hmm, strange, can you make a reproduction?

**Comment by dustinyoste** [comment]
I encountered this error when I need to run `yarn install`

**Comment by msand** [comment]
No idea how to get this error. Can you make a reproduction?
