### ISSUE TITLE
[android] onPressOut fires immediatly

### ISSUE THREAD

**Issue by ankardon** [react-native-community/react-native-svg#981]
The onPressOut property fires on touchdown and not as expected on release

``` javascript
import React, { Component } from 'react';
import Svg, { TSpan, Text } from 'react-native-svg'

export default class App extends Component {
  render() {
    return (
      <Svg
        height="100%"
        width="100%"
      >
        <Text
          fontSize={500}
          y={400}
          onPressOut={() => { console.warn("Out") }}
        >
          Hello
        </Text>
      </Svg>
    );
  }
}
```
react-native info:
```
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
      Memory: 1.01 GB / 7.67 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 19, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Intel x86 Atom_64
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by msand** [comment]
Is this with the latest version?

**Comment by ankardon** [comment]
Yes, this is with version 9.3.6

**Comment by msand** [comment]
@ankardon At least with the develop branch it seems to work correctly in both iOS and Android. I can replicate it in https://snack.expo.io/@msand/fascinated-celery so it seems like an old bug. Can you try cleaning your build and caches and rebuild again? Or if that doesn't help, try clearing your npm/yarn cache and install again. Or perhaps try in a clean project.

**Comment by ankardon** [comment]
It seems the problem is specific to some phones. I created a new project and tested it again with my Samsung Tab S3, where I still got the same error. But I tried it again on my Moto Z Play, where it worked perfectly.

**Comment by msand** [comment]
If you can find any emulator where it is reproducible, that would be great. Otherwise there's not much I can do on my end. @ankardon Are you still having issues with this?
