### ISSUE TITLE
run-ios fail when using RN 0.58

### ISSUE THREAD

**Issue by Ankarrr** [react-native-community/react-native-svg#984]
Hello everyone. I upgrade RN from 0.55.4 to 0.58.6 and react-native-svg from 6.5.2 to 9.2.4. After that I get error when `run-ios`. However, I can build successfully when using Xcode. Please help.

Error:
```
.../node_modules/react-native-svg/ios/Brushes/RNSVGPainter.h:12:9: fatal error: 'RNSVGLength.h' file not found
#import "RNSVGLength.h"
        ^~~~~~~~~~~~~~~

** BUILD FAILED **
```

Env:
React Native: 0.58.6 
react-native-cli: 2.0.1
React: 16.6.3
react-native-svg: 9.2.4

**Comment by msand** [comment]
Can you try
```
react-native unlink react-native-svg
react-native link react-native-svg
```

**Comment by Ankarrr** [comment]
Yes I try, bug I still encounter same error.

**Comment by msand** [comment]
Can you try removing node_modules and installing again?

**Comment by Ankarrr** [comment]
Yes, but still the same error.

**Comment by msand** [comment]
Can you try in a clean project?

**Comment by Ankarrr** [comment]
I create a clean project and install and then it works. I am wondering why.

**Comment by msand** [comment]
It seems the react-native link command isn't working correctly, you'll probably have to link it manually, perhaps you have several schemes and only one of them has it correctly, and you're using some other scheme which has been duplicated from some old settings or something. I would recommend that you open an issue in the react-native-cli repo instead. There's nothing that can be done about it in this codebase.

**Comment by Ankarrr** [comment]
Thank you. I try to link manually buy following these steps:

> 1. Open your project in XCode and drag the RNSVG.xcodeproj file (located in .../node_modules/react-native-svg/ios) into the Libraries directory shown in XCode.
> 2. Expand the RNSVG.xcodeproj file you just added to XCode until you see: libRNSVG.a (located in RNSVG.xcodeproj > Products )
> 3. Drag libRNSVG.a into the Link Binary With Libraries section (located in Build Phases which may be found at the top of the XCode window)

When I run-ios, it built successfully. However, it shows this error:
<img width="369" alt="螢幕快照 2019-04-03 上午11 21 04" src="https://user-images.githubusercontent.com/8311552/55450774-ded5fd00-5602-11e9-8e05-825f8fc755ea.png">

**Comment by msand** [comment]
Strange, seems like you have an old version of react-native or something, can you make a git repo with reproduction?

**Comment by Ankarrr** [comment]
I'm developing 2 RN project with different version of RN. One is older. Is it might be the reason?

**Comment by msand** [comment]
Probably yes, try perhaps v6.5.3 with the older RN

**Comment by kjlee2016** [comment]
Clean cache
```
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-*
```
