### ISSUE TITLE
Get length of path

### ISSUE THREAD

**Issue by johanolandero** [react-native-community/react-native-svg#986]
Greetings!

Setting a strokeDasharray and strokeDashoffset as stated in #349 can be used to animate a path. However the strokeDasharray should be of the same length as the path. For simple paths, this is not a problem, but in more complex paths it gets difficult to calculate this length manually. 

Found this over at w3, however this doesn't seem to be supported in this library yet. Is it something that could be exposed from the underlying native modules?
https://www.w3.org/TR/SVG11/paths.html#__svg__SVGPathElement__getTotalLength

**Comment by msand** [comment]
We have logic for it in the native code at least, Android has PathMeasure: 
https://github.com/react-native-community/react-native-svg/blob/6d476d43028d749ee8df75b2e155a3f92567e86c/android/src/main/java/com/horcrux/svg/TSpanView.java#L110-L112

And in iOS we have our own custom logic, as there's nothing built in:
https://github.com/react-native-community/react-native-svg/blob/b0852d259568479be226a729836ae3b60d7ecfaf/ios/Text/RNSVGTextPath.m#L169

Example use:
https://github.com/react-native-community/react-native-svg/blob/6bd27dfeba3422482b43b15bef287b72d1bf7d54/ios/Text/RNSVGTSpan.m#L966-L970

These could be exposed as methods on the Svg View Module / Renderable View Manager:
https://github.com/react-native-community/react-native-svg/blob/6d476d43028d749ee8df75b2e155a3f92567e86c/android/src/main/java/com/horcrux/svg/SvgViewModule.java

https://github.com/react-native-community/react-native-svg/blob/b0852d259568479be226a729836ae3b60d7ecfaf/ios/ViewManagers/RNSVGRenderableManager.m

In a similar way as toDataUrl on the Svg View Module / Manager:
https://github.com/react-native-community/react-native-svg/blob/6d476d43028d749ee8df75b2e155a3f92567e86c/android/src/main/java/com/horcrux/svg/SvgViewModule.java#L28-L35

https://github.com/react-native-community/react-native-svg/blob/b0852d259568479be226a729836ae3b60d7ecfaf/ios/ViewManagers/RNSVGSvgViewManager.m#L33-L44

**Comment by msand** [comment]
Could you attempt to implement this an make a pr?

**Comment by johanolandero** [comment]
I wish I could, but my knowledge is very limited when it comes to ios and android development.

**Comment by msand** [comment]
@johanolandero I don't have time to dedicate to this right now, too busy with work for the moment. As a workaround you can use e.g. http://geoexamples.com/svg-path-properties/

**Comment by msand** [comment]
There's also this: https://github.com/substack/point-at-length/blob/master/index.js

**Comment by msand** [comment]
And https://pomax.github.io/bezierjs/#length

**Comment by johanolandero** [comment]
Thank you, will look in to it in the meantime.

**Comment by wcandillon** [comment]
@johanolandero I use `svg-path-properties` as seen here: https://github.com/wcandillon/can-it-be-done-in-react-native/blob/master/season1/revolut-chart/App.js

@msand Thanks for the resource, I would love to be able to calculate this myself using reanimated ;-)

**Comment by johanolandero** [comment]
Thanks! I ended up using svg-path-properties aswell. I found myself getting an incorrect length using bezierjs for the same path. 

Another gem within svg-path-properties was properties.getParts() which would prove to be very valuable.

**Comment by msand** [comment]
@johanolandero @wcandillon  I've made an initial implementation of getTotalLength, getPointAtLength and isPointInFill now
Could you please help testing and ensuring it's compatible with the web?
https://github.com/react-native-community/react-native-svg/pull/1135

Any other native methods you would have use for? I have getBBox, getCTM and getScreenCTM in the pipeline

**Comment by msand** [comment]
Added getBBox, getCTM and getScreenCTM, and changed signatures: made callbacks to be the last argument, unless there are optional options.

**Comment by victorroatt** [comment]
GetTotalLength is returning wrong length value on react native (android).

Svg from https://vemaps.com/cape-verde/cv-01

Display length of path
![image](https://user-images.githubusercontent.com/88899815/207685326-5c3abbcf-5a4e-42c9-ae3e-7bc96d9d25e2.png)
![image](https://user-images.githubusercontent.com/88899815/207685385-bad33b7d-5b8c-494e-98cb-8882d56e08fe.png)

Web Length
![image](https://user-images.githubusercontent.com/88899815/207685584-3ec578ab-eaf5-4df1-bc8c-657647014ee7.png)

Can somebody help me with this issue? There's only a few maps that have this issue, others are working perfectly to measure length of the path.

**Comment by kr-yeon** [comment]
#1942
IOS works fine. The problem with Path seems to only happen on Android.
For the G tag, each onLayout is returned for all paths inside. Any good solutions?
