### ISSUE TITLE
Crash with empty path

### ISSUE THREAD

**Issue by mlecoq** [react-native-community/react-native-svg#987]
I have recently updated my app to expo *32.0.0* (embedding _react-native-svg_)

After this update, the app crash on displaying a page with an _Path_ having a d prop as empty string. 

I have made a small example to help to reproduce the issue:

https://github.com/mlecoq/test-signature

I have a workaround for the moment : I have put a condition on _d_ value to display _Path_ child.

**Comment by msand** [comment]
This should be fixed in the latest version.
