### ISSUE TITLE
Possible to use image as clipPath?

### ISSUE THREAD

**Issue by bmcn99** [react-native-community/react-native-svg#994]
I have an image that is meant to be customizable, changing the colors to red or green, adding some polka dots or stripes, that type of thing. The plan is to take my image, and draw a rect or pattern beneath it, and use a copy of the image as a clipPath so that it only shows beneath the customizable image.

Can this be done?

**Comment by msand** [comment]
I'm not exactly sure what you're asking for, seems it could be one of many things which are possible to do, possibly using clipPath or mask, some other things you might want would possibly require filters, which are partially implemented for ios in the filters branch, but no android implementation in progress yet. Could you give a more concrete example, perhaps a representative image?

**Comment by bmcn99** [comment]
![Box_Close](https://user-images.githubusercontent.com/29124319/56236216-71dd5100-605f-11e9-9b75-d5edb6c2e0e1.png)

I have my box image there, and I want to be able to draw a red rect behind it, since it has transparency, or a design like this: 
![image](https://user-images.githubusercontent.com/29124319/56236337-bd8ffa80-605f-11e9-9438-68c127829b73.png)

I've received a few images from the designer and they've changed sizes a few times so I am reluctant to map out the points for a polygon clipPath, and then have him change the dimensions again and leaving me to re-create all my paths. I was thinking if I could just use the image directly to create the path I wouldn't have that problem.

**Comment by msand** [comment]
If you only want the circle in the middle to show a red rect behind it, isn't it then enough to give a background color to the Image / View (no need for svg), and tell the designer to make the other parts white/filled with color instead of transparent?

**Comment by msand** [comment]
You might want to read this article, and the comments to it: https://css-tricks.com/masking-vs-clipping-use/
And these good as well: https://css-tricks.com/clipping-masking-css/
https://vanseodesign.com/web-design/svg-masking-examples-1/
https://webdesign.tutsplus.com/tutorials/a-comprehensive-guide-to-clipping-and-masking-in-svg--cms-30380
https://lab.iamvdo.me/css-svg-masks/
https://getflywheel.com/layout/css-svg-clipping-and-masking-techniques/

**Comment by bmcn99** [comment]
I'm not at all proficient in react native, so can I just change the css property to clipPath from clip-path and almost use that example code as is?
