### ISSUE TITLE
Shadow issues when using path

### ISSUE THREAD

**Issue by 1070rik** [react-native-community/react-native-svg#996]
Hey!

For one of my apps I need to display an SVG ticket made with a path and it needs a drop shadow effect.
Now, since the package doesn't support filters in the master repo (yet?) I'm just using the out of the box shadows of react native.
This works fine on iOS but when i try it on android it's all messed up.
You can't see the content I have on top of the SVG etc.

This is what it looks like on iOS. 
![image](https://user-images.githubusercontent.com/14279658/56272803-c59d7800-60fb-11e9-84e1-9c3ae303e767.png)

And this is what it looks like on Android. 
![image](https://user-images.githubusercontent.com/14279658/56273797-c6370e00-60fd-11e9-959a-01b8679a383f.png)

As you can see, Android doesn't follow the SVG path whilst iOS does.

This is the code that the card uses:
```
import React from 'react'
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native'
import { Svg, Path } from 'react-native-svg'
import PropTypes from 'prop-types'
import Colors from '../../../Themes/Colors'
import Fonts from '../../../Themes/Parser/Fonts'
import BlackTieIcons from '../../../Config/BlackTie/BlackTieIcons'
import AttendeeList from '../Lists/AttendeeList'

const TicketCard = ({eventTitle, location, time, navigate, attendees}) => {
  return (
    <TouchableOpacity onPress={() => navigate('Tickets')}>
      <View
        style={[{alignItems: 'center'}]}>
        <View style={styles.cardStyles}>
          <Svg width="345" height="185" viewBox='0 45 350 185'
               style={[{transform: [{rotate: '3deg'}], elevation: 4, borderRadius: 10}]}>
            <Path fill={'#fff'} fillRule={'evenodd'}
                  d={'M5,116.005446 L5,51 C5,48.2385763 7.23857625,46 10,46 L345,46 C347.761424,46 350,48.2385763 350,51 L350,116.005446 C337.804495,116.271345 328,126.240691 328,138.5 C328,150.759309 337.804495,160.728655 350,160.994554 L350,226 C350,228.761424 347.761424,231 345,231 L10,231 C7.23857625,231 5,228.761424 5,226 L5,160.994554 C17.1955053,160.728655 27,150.759309 27,138.5 C27,126.240691 17.1955053,116.271345 5,116.005446 Z'}/>
          </Svg>
        </View>
        <View style={styles.cardStyles}>
          <Svg width="345" height="185" viewBox='0 45 350 185'
               style={[{transform: [{rotate: '-3deg'}], elevation: 4, borderRadius: 10}]}>
            <Path fill={'#fff'} fillRule={'evenodd'}
                  d={'M5,116.005446 L5,51 C5,48.2385763 7.23857625,46 10,46 L345,46 C347.761424,46 350,48.2385763 350,51 L350,116.005446 C337.804495,116.271345 328,126.240691 328,138.5 C328,150.759309 337.804495,160.728655 350,160.994554 L350,226 C350,228.761424 347.761424,231 345,231 L10,231 C7.23857625,231 5,228.761424 5,226 L5,160.994554 C17.1955053,160.728655 27,150.759309 27,138.5 C27,126.240691 17.1955053,116.271345 5,116.005446 Z'}/>
          </Svg>
        </View>
        <View style={styles.cardStyles}>
          <Svg width="345" height="185" viewBox='0 45 350 185' style={{elevation: 4, borderRadius: 10}}>
            <Path fill={'#fff'} fillRule={'evenodd'}
                  d={'M5,116.005446 L5,51 C5,48.2385763 7.23857625,46 10,46 L345,46 C347.761424,46 350,48.2385763 350,51 L350,116.005446 C337.804495,116.271345 328,126.240691 328,138.5 C328,150.759309 337.804495,160.728655 350,160.994554 L350,226 C350,228.761424 347.761424,231 345,231 L10,231 C7.23857625,231 5,228.761424 5,226 L5,160.994554 C17.1955053,160.728655 27,150.759309 27,138.5 C27,126.240691 17.1955053,116.271345 5,116.005446 Z'}/>
          </Svg>
        </View>
        <View style={{
          justifyContent: 'center',
          alignItems: 'center',
          height: '100%',
          marginTop: 2,
          width: '77.5%',
          marginLeft: 5
        }}>
          <View style={{
            width: '80%',
            height: '100%',
          }}>
            <View style={{
              height: '30%',
              justifyContent: 'center',
              borderBottomColor: Colors.lightPink,
              borderBottomWidth: 0.5
            }}>
              <Text style={{
                fontFamily: Fonts.Bebas,
                fontSize: 25
              }}>{eventTitle}</Text>
            </View>
            <View style={{height: '40%', justifyContent: 'center'}}>
              <View style={{
                flexDirection: 'row',
                alignItems: 'center',
                marginBottom: 8
              }}>
                <BlackTieIcons name={'uniF0CA'} type={'regular'} color={Colors.cloudyBlue} size={16}
                               containerStyle={{width: 19}} iconStyle={{paddingLeft: 1}}/>
                <Text style={{
                  fontFamily: Fonts.Bebas,
                  fontSize: 18,
                  color: Colors.cloudyBlue
                }}>{location}</Text>
              </View>
              <View style={{
                flexDirection: 'row',
                alignItems: 'center',
                marginBottom: 8,
              }}>
                <BlackTieIcons name={'uniF019'} type={'regular'} color={Colors.cloudyBlue} size={15}
                               containerStyle={{width: 19}}/>
                <Text style={{
                  fontFamily: Fonts.BebasRegular,
                  fontSize: 18,
                  marginBottom: -5,
                  color: Colors.cloudyBlue
                }}>{time}</Text>
              </View>
            </View>
            <View style={{
              height: '30%',
              justifyContent: 'center',
              borderTopColor: Colors.lightPink,
              borderTopWidth: 0.5
            }}>
              <AttendeeList attendeeList={attendees} attendeeExtra={10}/>
            </View>
          </View>
        </View>
      </View>
    </TouchableOpacity>
  )
}

const styles = StyleSheet.create({
  cardStyles: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    shadowColor: Colors.banner,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 3,
    width: 350,
  }
})

TicketCard.propTypes = {
  eventTitle: PropTypes.string.isRequired,
}

export default TicketCard
```

I know, I know, it's a bit messy ;P

Does anyone know if it's possible to achieve this on both android and iOS?

**Comment by msand** [comment]
On android, it would require either filters, or implementing ViewOutlineProvider and getOutline, and it only works with convex paths, so the svg would need to be converter to that first. https://books.google.fi/books?id=rSuuDQAAQBAJ&pg=PA606&lpg=PA606&dq=ViewOutlineProvider+getOutline+convex+path&source=bl&ots=5MfYqIqu6L&sig=ACfU3U2GnuB9HvapQtnCZPa8COm_rjncFQ&hl=en&sa=X&ved=2ahUKEwiNjeT5iNfhAhVkz6YKHdhmAVAQ6AEwB3oECAkQAQ#v=onepage&q=ViewOutlineProvider%20getOutline%20convex%20path&f=false

**Comment by msand** [comment]
You could probably use https://github.com/react-native-community/react-native-blur as well

**Comment by 1070rik** [comment]
Thanks for the recommendations, I'll try it out.

**Comment by 1070rik** [comment]
@msand is the ebook you sent comparable with this package? https://github.com/folofse/androw

**Comment by msand** [comment]
Androw actually seems like a better/more general solution. I would recommend trying that as a first choice.

**Comment by 1070rik** [comment]
Alright thanks! Then i'll try using that.

**Comment by 1070rik** [comment]
Using the androw package and changing the shadowradius depending on the OS I was able to get the shadows to work correctly.

**Comment by msand** [comment]
Great! Could you post a screenshot? Would be interesting to see how well it works, with regards to prioritizing implementation of filters for android (can be achieved using e.g. renderscript).

**Comment by 1070rik** [comment]
Sure! This is what it looks like on iOS right now:
![image](https://user-images.githubusercontent.com/14279658/56356571-82193b80-61d9-11e9-8de2-45b0747e6225.png)
(still need to fix the size, this is on an iPhone 5)

And this is the result on Android:
![image](https://user-images.githubusercontent.com/14279658/56356604-9bba8300-61d9-11e9-8b09-63778b746ef0.png)
Also doesn't have the right size yet but that's not relevant for this thread ;P

Using the package is extremely easy. You just use it as a view and it works immediately on both iOS and Android. Kudos to the creator!

**Comment by msand** [comment]
Looks good. I tried optimizing the implementation a bit, could you try my pr? https://github.com/folofse/androw/pull/1
https://github.com/msand/androw/commit/b8626c403a3087173bc9ed44a4d1d8a07b05e9ea

**Comment by msand** [comment]
The latest commit in my pr seems to perform quite nicely, the dispatchDraw takes 30 000 - 300 000 nanoseconds when animating opacity, color and offset of the shadow. Animating radius of the blur/shadow is slower, but probably needed less often as well.

**Comment by msand** [comment]
I also tried making an experiment with RenderScript, but it was about ten times slower: https://github.com/msand/androw/commit/c3a70d376b895b0a544af35421b43e72f2f6d687

**Comment by 1070rik** [comment]
I'll try both out tonight and post the results on here!

**Comment by karan-gujral** [comment]
@1070rik hey can you please share your code for shadow effect for Android device? It's working only on iOS for me.

<Androw style={styles.shadow}>
      <Svg
        width={292}
        height={126}
        viewBox="0 0 292 126"
        style={{position: 'absolute'}}>
        <G
          id="Group_226"
          data-name="Group 226"
          transform="translate(-497 -316.838)">
          <G transform="matrix(1, 0, 0, 1, 497, 316.84)">
            <Path
              id="Subtraction_3-2"
              data-name="Subtraction 3"
              d="M145.9,96H8a8.009,8.009,0,0,1-8-8V8A8.009,8.009,0,0,1,8,0H145.9c-.018.224-.027.461-.027.706,0,4.282,2.974,7.765,6.629,7.765s6.63-3.483,6.63-7.765c0-.237-.009-.474-.027-.706H254a7.931,7.931,0,0,1,4.823,1.616,8.062,8.062,0,0,1,2.844,4.094c-4.421.494-7.753,3.8-7.753,7.7,0,4.046,3.476,7.37,8.087,7.733v5.71c-4.61.363-8.087,3.687-8.087,7.734s3.476,7.37,8.087,7.733v5.711c-4.61.363-8.087,3.687-8.087,7.733S257.39,63.134,262,63.5v5.71c-4.61.363-8.087,3.687-8.087,7.733s3.476,7.37,8.087,7.733V88a8.009,8.009,0,0,1-8,8H159.11c-.31-4.025-3.148-7.059-6.6-7.059s-6.292,3.035-6.6,7.059Z"
              transform="translate(15 15)"
              fill="transparent"
              stroke="#eee"
              strokeWidth={1}
              opacity="0.9"
            />
          </G>
          <Line
            id="Line_1"
            data-name="Line 1"
            y2="77.574"
            transform="translate(664.353 342.2)"
            fill="none"
            stroke="#707070"
            strokeWidth={1}
            strokeDasharray={5}
            opacity="0.2"
          />
        </G>
      </Svg>
    </Androw>


const styles = StyleSheet.create({
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,

    elevation: 7,
  },
});

This is what I am trying to do.

**Comment by karan-gujral** [comment]
@1070rik, @msand hey can you please share your code for shadow effect for Android device using Androw? It's working only on iOS for me.
[gist.txt](https://github.com/react-native-community/react-native-svg/files/3794523/gist.txt)
This is what I am trying to do. Any help will be appreciated. Thanks!

**Comment by 1070rik** [comment]
@karan-gujral Sure, this is the code that I ended up with and which is working right now.
https://gist.github.com/1070rik/3649de9004dbe0f8d5cb1770cd192f2d
Hope it'll help you out.

**Comment by karan-gujral** [comment]
Thank you so much @1070rik !! It's working now. Seems like the Androw Library does not support Groups in SVG for Android. I removed the groups from my SVG (same as yours) and it worked.

**Comment by 1070rik** [comment]
@karan-gujral No problem, glad I could help!
