### ISSUE TITLE
Transform short hand does not work

### ISSUE THREAD

**Issue by aaronkrohn** [react-native-community/react-native-svg#998]
Upgrading from 5.4.1 to 9.4.0 broke a few of my SVGs. 

Mainly SVG's that had transform written like this `transform={{ translate: '10, 10' }}`

I fixed it by writing it out fully: `transform={{ translateX: 10, translateY: 10 }}`

**Comment by msand** [comment]
Can you try with the latest commit from the master branch? Alternatively you can use the x and y prop.

**Comment by aaronkrohn** [comment]
Yes, the latest commit on master fixes the issue! 👍
