### ISSUE TITLE
[iOS] Occasional Crash in render image

### ISSUE THREAD

**Issue by Godblk** [react-native-community/react-native-svg#999]
in iOS project," react-native-svg/ios/Elements/RNSVGImage.m/renderLayerTo:rect: " Method，sometimes crash at "CGContextDrawImage(context, imageBounds, _image);",I solved like this:
![屏幕快照 2019-04-19 上午9 36 42](https://user-images.githubusercontent.com/8614245/56400497-c31b5980-6286-11e9-80db-89aace7f2459.png)

**Comment by msand** [comment]
You can probably return early in case the bounds are zero. Would you like to open a pr?

**Comment by Godblk** [comment]
YES,perhaps at the beginning of this method,judge the bounds and return would work well,What shall I do to submit a pull request?

**Comment by yusufMeimeh** [comment]
We have the same problem, any updates?

**Comment by msand** [comment]
This fell somewhat under the radar, using the opposite codition to return asap in the method should be good. Can make a fork, make changes, commit, push and open a pr in github
